### ISSUE TITLE
Select from > 2 grouping variables (T-test)

### ISSUE THREAD

**Issue by gikeymarcia** [jasp-stats/jasp-desktop#1004]
I have a 3x2 between-subjects design and tried to use the 3-level IV as the grouping variable but the t-test says there can only be 2 levels.  It would be nice if when there are > 2 levels it asks you to select the cases to compare.

```
Select which two levels to compare:
0
1
2
```

Even better, do all pairwise comparisons with an option to disable ones I don't care about

```
Which analyses would you like to exclude:
0 v 1
1 v 2
2 v 0
```

Even further, let me throw in multiple grouping variables and give me all the combinations

```
Grouping Varibles:
A (3-levels)
B (2-levels)

Which analyses would you like to exclude:
Main Effects:
A0/A1
A1/A2
A0/A2
B1/B2

Simple Main Effects:
@B1
A0/A1
A1/A2
A0/A2

@B2
A0/A1
A1/A2
A0/A2

@A0
B1/B2

@A1
B1/B2

@A2
B1/B2
```

If I wanted to write the logic figuring out which t-tests are needed would that be helpful?  What languages would I need to write it in? I am mostly familiar with PHP, Javascript, C++.  Don't know much R since I was formerly an SPSS guy but would like to do whatever is possible to help JASP crush SPSS.

**Comment by jonathon-love** [comment]
> I have a 3x2 between-subjects design and tried to use the 3-level IV as the grouping variable but the t-test says there can only be 2 levels. It would be nice if when there are > 2 levels it asks you to select the cases to compare.

yes, absolutely. this is something we're wanting to add.

> Even better, do all pairwise comparisons with an option to disable ones I don't care about

yup, we thought about this too. we are trying to strike a balance between keeping the user-interface simple for people to understand, but flexible enough at the same time. it's a delicate balancing act.

what you're proposing is probably is a bit too involved for most people, contains quite a few steps, etc. it would be a good candidate for an "add-on" module. this is where people can download additional analyses. this is something we're going to add support for in the next 12 months.

but if you'd like to be involved in JASP development, and there's something which scratches an itch for you, i'm sure we can slot you in :)

**Comment by gikeymarcia** [comment]
Point me in a direction and I'll give it a look.

**Comment by AlexanderLyNL** [comment]
Filter
