### ISSUE TITLE
Error in mauchly[index,

### ISSUE THREAD

**Issue by LIJIAO1** [jasp-stats/jasp-desktop#1011]
I want to do the repeated measurements. I set  up 2 levels for the first factor, 4 levels of the second factor and 5 levels of the third factor. But when I  tried to export the data to the Repeated Measures Cells, it left the information as the picture showed below.
![image](https://cloud.githubusercontent.com/assets/14852077/10118820/a19f5b20-647a-11e5-9947-df897188286d.png)
Thank you for your help.

**Comment by jonathon-love** [comment]
hi @LIJIAO1 

can you attach the data file you're using? i think you should be able to drag-and-drop the .csv file into the GitHub message box to attach it. (otherwise you can email me: jon [at] thon [dot] love)

thanks for your report, this is really helpful.

with thanks

**Comment by LIJIAO1** [comment]
I sent my data to your email. Thank you!!!

**Comment by jonathon-love** [comment]
hi @LIJIAO1,

what version of JASP are you using? i can't seem to reproduce the issue in 0.7.1.12 (but i may not have specified the analysis correctly)

if you're using the latest, can you save a .jasp file and send it through?

with thanks

<img width="982" alt="screen shot 2015-09-27 at 9 44 10 am" src="https://cloud.githubusercontent.com/assets/3240247/10121786/74f6f2d6-64fc-11e5-85bd-fd58561e889f.png">

**Comment by jonathon-love** [comment]
wait, i've got it!

thanks, we'll get onto this soon.

<img width="894" alt="screen shot 2015-09-27 at 9 48 58 am" src="https://cloud.githubusercontent.com/assets/3240247/10121791/0d693b82-64fd-11e5-977b-9aa4d68901ed.png">

**Comment by jonathon-love** [comment]
hey @LIJIAO1,

we've fixed this, and it will be in the next release (maybe a week or two away).

thanks for your report

**Comment by LIJIAO1** [comment]
Great Thanks! I will further add one factor with 2 levels at the top. So will it be OK if I have 2*2*4*5=80 in the cell?

**Comment by jonathon-love** [comment]
should work. feel free to send it through if you'd like us to test before the release.

with thanks
