### ISSUE TITLE
Factor levels in RM ANOVA plots always sorted alphabetically (problematic for numeric levels)

### ISSUE THREAD

**Issue by knaeckebrot0815** [jasp-stats/jasp-desktop#1015]
The levels in RM ANOVA plots seem to be reordered alphabetically by the program. 

For an RM factor that is numerical (e.g. time) this leads to problems. For example for 'age' = 1, 5, and 20, the order on the x axis becomes 1, 20, 5.

It would be better to maintain the order in which the factors are added.

(It would also be great to have the opportunity to set the range of the y-axis, especially for measures that cannot be <0. At least zero should have it's own tick mark or a baseline.)

**Comment by jonathon-love** [comment]
Thanks for the report.

This is fixed in the development branch, and will be fixed in the next release (a couple of weeks away).

cheers
