### ISSUE TITLE
Highlighting rows in ANOVA tables

### ISSUE THREAD

**Issue by fdabl** [jasp-stats/jasp-desktop#1018]
Hi,

it would be nice to visually highlight specific rows in a Bayesian ANOVA table upon clicking on them. This would make it easier to see what statistics correspond to which model.

Currently, it's pretty hard to get that straight:
![table_highlight](https://cloud.githubusercontent.com/assets/6568110/10242949/151a93f2-68f5-11e5-99ca-07bfa1ee56ca.png)

cheers,
Fabian

**Comment by jonathon-love** [comment]
yeah, i agree. we're planning this sort of functionality, we're just not at the stage yet where we're adding interactivity to the results panel. but it will happen at some point.

**Comment by boutinb** [comment]
Rows have now alternate color.
