### ISSUE TITLE
Data editor bug opening csv file

### ISSUE THREAD

**Issue by danprec** [jasp-stats/jasp-desktop#1019]
I have opened a csv file, and some of my variables are seen as categorical (even though they are numeric). When I switch the type, all values disappear. Data looks ok when I open the file, and turned into a '.' if I change the variable type. Meanwhile, with such "categorical" data, i cant run any analyses (Or at least the program wont rake any variable like that)

**Comment by jonathon-love** [comment]
hi, can you send me an example data set which produces this problem?

you can either attach it to a github message, or you can email it to me at

jon [at] thon [dot] love

with thanks

**Comment by jonathon-love** [comment]
hi @danprec 

the issue is that some of the numbers are surrounded with spaces. this is something i will fix in the next release. in the mean time, you can just "search and replace" all the spaces with nothing.

thanks for your report!

**Comment by danprec** [comment]
Hi Jonathon, 

That did it, thanks a lot! 
Cheers
