### ISSUE TITLE
RM ANOVA works with one input method, not with others?

### ISSUE THREAD

**Issue by nickwan** [jasp-stats/jasp-desktop#1020]
I get the following message:
 "This analysis terminated unexpectedly. Please contact its author. Error in mauchly[index," 

For RM 1, I have two levels. For RM 2, I have 6 levels. I also have a between subjects factor. If I input my factors like this, I get an error. However, if I input my factors where the first level is normally the last level, the RM ANOVA works. 

On other CSV files, I don't need to do this and it works fine. 

I've tried uninstalling and reinstalling and the issue still happens. 

Not exactly sure what's happening -- I've been loading in the stats in all sorts of different ways to get the analysis I want; annoying, but still works. 

Hope that's enough information.

**Comment by jonathon-love** [comment]
thanks for the report. this issue we are aware of, and has been fixed for the next release! should only be a couple of weeks away.

thanks
