### ISSUE TITLE
Correlation matrix only on custom parts

### ISSUE THREAD

**Issue by ghost** [jasp-stats/jasp-desktop#1021]
Hi,

I've encountered a very specific issue: my students made a correlation matrix on their measures, but they had to do it on parts of their points, not on all of them. See attached image (a drawing is worth thousands of words...).
So, maybe a future feature could be to custom-chose the points you want the correlation matrix about?

Sincerly

P.S.: and Jasp is still a so smooth teaching experiment. Once you go Jasp, you don't go back ;)

![intersection](https://cloud.githubusercontent.com/assets/13798585/10266956/dc004a3c-6a7d-11e5-8eb8-d808ed9fe35e.jpg)

**Comment by AlexanderLyNL** [comment]
Fixed using filter:

https://jasp-stats.org/2018/06/27/how-to-filter-your-data-in-jasp/
