### ISSUE TITLE
Error in plots

### ISSUE THREAD

**Issue by danprec** [jasp-stats/jasp-desktop#1023]
Hello, 

I am encountering the following error while trying to plot graphs:
![image](https://cloud.githubusercontent.com/assets/8555841/10306235/cf86e56e-6c25-11e5-8a29-6798411612ec.png)

I get the same error whenever I try to plot any kind of graph using the classical statistics options. Furthermore, on the plots for Bayesian stats (for example, bayesian T tests), I get the plots and all visuals/drawings, but all the legends display boxes instead of text, as if the symbols or letters or numbers were not being loaded / recognized. 

I have remove and reinstalled JASP (on a 10.10 mac) just now, to make sure there was nothing wrong with the installation, but the problem persists. 

Thanks for your support!

**Comment by jonathon-love** [comment]
hmm, that is quite peculiar. i've never seen it before. let me give it some thought.

**Comment by danprec** [comment]
Of course! And thanks for reacting so quickly. 
Let me know if you need any extra info from my side

From:  Jonathon Love
Reply-To:  jasp-stats/jasp-desktop
Date:  Tuesday 6 October 2015 14:01
To:  jasp-stats/jasp-desktop
Cc:  dp
Subject:  Re: [jasp-desktop] Error in plots (#1023)


hmm, that is quite peculiar. i've never seen it before. let me give it some thought.

**Comment by jonathon-love** [comment]
Can you tell me, do you have XQuartz installed? if you do, could you try re-installing it?

with thanks

**Comment by danprec** [comment]
Hi Jonathon, 

I un- and re-installed Xquartz (V. 2.7.7), but still I get the same “Polygon edge not found” error. 
For the record, not sure if it is relevant of if I had already mentioned, but in my computer (macbook running Yosemite 10.10) Xquartz appears to be called X11, yet when I open it I can see in the properties that it is Xquartz V 2.7.7 (I’m pretty new to macs, so I’m not sure how are things supposed to look like)

Thanks and regards, 
Daniel

From:  Jonathon Love
Reply-To:  jasp-stats/jasp-desktop
Date:  Monday 12 October 2015 13:18
To:  jasp-stats/jasp-desktop
Cc:  dp
Subject:  Re: [jasp-desktop] Error in plots (#1023)


Can you tell me, do you have XQuartz installed? if you do, could you try re-installing it?

with thanks

**Comment by boutinb** [comment]
Does this error still occur in the last version (0.8.1)?

**Comment by boutinb** [comment]
If this error still occurs, reopen this issue.
