### ISSUE TITLE
Internal Error JASP

### ISSUE THREAD

**Issue by adsmgmt** [jasp-stats/jasp-desktop#1030]
![error jasp](https://cloud.githubusercontent.com/assets/15151270/10532498/8c349c50-7384-11e5-99f9-addbc8cf5595.png)

I have already uninstalled the software and reinstall but the same issue still appear. It is funny tho when I install it in my laptop, it is perfectly fine. I hope that helps.

**Comment by jonathon-love** [comment]
hi,

can you tell me what version of windows you have installed? is it 32-bit or 64-bit?

http://windows.microsoft.com/en-US/windows7/find-out-32-or-64-bit

and do you have software like R or RStudio. installed?

thanks for your report!

**Comment by adsmgmt** [comment]
Hi Jonathon,

The software R is the problem that prevents me from using JASP. Thanks! I
am planning to use JASP to teach my marketing research students. Is there
any materials that you can provide me?

Best,
Tyson Ang, Ph.D.
Assistant Professor of Marketing and Director of Marketing Research Center
College of Business and Technology
Huston-Tillotson University
900 Chicon St., Austin, TX 78702
Phone: 512-505-3170

**Comment by adsmgmt** [comment]
Hi Jonathon,

I apologize that I replied you too fast. It turns out that the error
message still appears even after I uninstalled R. My windows version is
32-bit (window 7). Thanks!


Best,
Tyson Ang, Ph.D.
Assistant Professor of Marketing and Director of Marketing Research Center
College of Business and Technology
Huston-Tillotson University
900 Chicon St., Austin, TX 78702
Phone: 512-505-3170

**Comment by KadenPrance** [comment]
I am having the same Error.
Windows 10 Pro
64 bit
8 Gigs RAM
Intel i5-5200 CPU
JASP-0.7.1.12
I have installed, uninstalled and reinstalled numerous times and still get the same issue noted in the image above.

I do have R installed but only recently experienced this issue.
I am concerned if I uninstall R and still experience the issue. 
Was there a work around found before I try to install R to try Jasp again.

Please advise.

**Comment by jonathon-love** [comment]
hi @KadenPrance 

thanks for your report.

yes, this is a difficult one to figure out. we haven't been able to reproduce it at our end yet.

did you only start to have this issue after you installed R (or other software like RStudio)? or did it just start being a problem "out of the blue"?

with thanks

jonathon

**Comment by KadenPrance** [comment]
Thanks for the reply Jonathan,
I think it started out of the blue.
I had not touched either program for several weeks. But I initially
installed them one after the other and they both worked.
Is there a Jasp log file I can pull that might help give more information.
Also, is there anything else I can share to help with diagnosis?

Tye

**Comment by boutinb** [comment]
Does this error still occur in the last JASP version (0.8.1)?

**Comment by boutinb** [comment]
If this error still occurs, reopen this issue.
