### ISSUE TITLE
Reordering Variables

### ISSUE THREAD

**Issue by ChrysCC** [jasp-stats/jasp-desktop#1031]
When entering multiple variables to check for correlations, I would like to be able to reorder them, in order to view the results in the way that suits me most at the time (e.g. be able to add a new variable but put it in the first row instead of the last column).

**Comment by jonathon-love** [comment]
yup, good idea. as you say, it's not possible to change the order once you've assigned them, but you can remove all the variables and add them one-by-one in the correct order.

makes sense?

**Comment by boutinb** [comment]
Variable ordering is already implemented, but needs still a neater way in the interface.

**Comment by boutinb** [comment]
This is possible in the last version 8.1.0
