### ISSUE TITLE
Descriptive plot for Bayesian correlation pairs

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1032]
@raviselker Can we have the descriptive plot also for the Bayesian correlation pairs? Right now it is present only for the classical correlations...
Cheers,
E.J.

**Comment by raviselker** [comment]
@EJWagenmakers This is present in the newest release right?

**Comment by EJWagenmakers** [comment]
@raviselker Yes, I was happy to see that!
