### ISSUE TITLE
JASP opens a particular .csv file incorrectly

### ISSUE THREAD

**Issue by pmacedosouza** [jasp-stats/jasp-desktop#1037]
I have a problem with a  c sv file. How can I submit it ?

**Comment by jonathon-love** [comment]
you can either attach it to this issue, or email it to me with `#1037` in the subject line

my email is: jon [at] thon [dot] love

**Comment by boutinb** [comment]
Do you have stilll this problem with the last version of JASP (0.8.1)?

**Comment by boutinb** [comment]
If this error still occurs, reopen this issue.
