### ISSUE TITLE
Infinite number for BF(Inclusion)

### ISSUE THREAD

**Issue by numcog** [jasp-stats/jasp-desktop#1039]
Hello! 

I am a new user of JASP and I am having trouble understanding why I get the infinity sign for a BF(Inclusion) in the Bayesian Linear Regression using JASP. I have attached the output. Any help you might be able to offer would be much appreciated. 

Thanks! 
Daniel
<img width="583" alt="screen shot 2015-11-02 at 7 41 13 pm" src="https://cloud.githubusercontent.com/assets/15621268/10898541/79e3fbae-8199-11e5-84e5-fc510cd59695.png">

**Comment by jonathon-love** [comment]
hi,

the largest number that BF<sub>Inclusion</sub> can accommodate is about 1e+305. once it exceeds this value, then computers automatically change it to an infinity. so while the value isn't infinity, it's so large that it might as well be.

we'll probably fix this in the future, but as you can see, it doesn't really make a lot of difference, so it's not a very high priority.

cheers

**Comment by numcog** [comment]
Thanks! This is very helpful!
