### ISSUE TITLE
ICU soname bump

### ISSUE THREAD

**Issue by stephensrmmartin** [jasp-stats/jasp-desktop#1040]
This is less so an issue for JASP, per se, but the BayesFactor package depends on icu = .55. 
ICU was recently updated to .56, which means BayesFactor fails to load the correct library, and JASP will consequently fail.

**Comment by jonathon-love** [comment]
tell me more :)

is this arch linux specific? i don't even think i know what ICU is :P

**Comment by stephensrmmartin** [comment]
No, ICU was recently updated.
Apparently BayesFactor uses stringi, which uses ICU 55.
On OS's that updated their ICU to 56, all BayesFactor analyses are borked as a result.

This will be fixed when stringi allows ICU 56.

**Comment by jonathon-love** [comment]
ah, ok. in debian/ubuntu land, `stringi` would mark itself as incompatible with `ICU56`, and this would hold back the update of `ICU` until `stringi` was ready.

but i'm guessing you don't have this sort of mechanism in arch.

there's not really anything i can do, is there? :P

**Comment by stephensrmmartin** [comment]
This is fixed now.
There *is* a similar mechanism in arch, btw, but arch is rolling, and everything was built with ICU56.

The stringi developers seem to have updated to ICU56 and all is well.
