### ISSUE TITLE
bayesian normality test

### ISSUE THREAD

**Issue by rickhelmich** [jasp-stats/jasp-desktop#1046]
Hi, is there a way to test the normality of a given parameter, using a bayesian approach? More specifically, what I would like to do is demonstrate that a group of subjects has a normal distribution for parameter A, but a binomial distribution for parameter B. There are normality tests in traditional statistics, but these do not give evidence for a non-normal distribution, let alone for a binomial distribution. Thanks! Rick

**Comment by jonathon-love** [comment]
let's ask @richarddmorey

**Comment by richarddmorey** [comment]
The normal and binomial distributions are completely different; you shouldn't need a test for that. Can you describe what you want in a bit more detail? (the answer is yes, there are Bayesian distributional tests, but I can't think of a case in real research where I'd want to use them -- but the same can be said of the classical tests)

**Comment by rickhelmich** [comment]
Dear Richard,

The issue I would like to address is whether clinical variability within a disease is caused by the presence of two distinct clinical subgroups (binomial distribution of that variability) or whether they reflect two ends of one spectrum (one distribution). I have continuous data that reflect the response of tremor to dopamine. The question is whether there are two discrete groups of dopamine-resistant and dopamine-responsive patients. Does that make sense?

Thanks, Rick

**Comment by richarddmorey** [comment]
ah, so you want a cluster or latent class analysis?

**Comment by rickhelmich** [comment]
Dear Richard, sorry for my late response! Yes, a cluster analysis would be ideal. But I guess that a first simple test would be to test whether or not the data (response of tremor to medication) is normally distributed or not. Do you know of good statistical software to perform these analyses? I guess that for the normality test a Bayesian solution would be ideal, because it also gives the probability that the data are NOT normally distributed.

Thanks in advance!

Yours, Rick

**Comment by richarddmorey** [comment]
No, I do not know any software that implements Bayesian normality tests.

**Comment by boutinb** [comment]
Issue closed due to too long inactivity
