### ISSUE TITLE
Paired-samples t-test: means plot reversed values

### ISSUE THREAD

**Issue by bobbyfiend** [jasp-stats/jasp-desktop#1054]
On certain data files I have found that the means plot for the paired-samples t-test (when "descriptives" and "descriptives" plots are checked) appears to show the value for the mean of group 1 above the label for group 2 and vice-versa. 

JASP 0.7.1.12
OS: Windows 7 Ultimate 64-bit SP 1 (note: also replicated on a student's Mac notebook, but I don't know the specs)
See attached screenshot. Data used to produce behavior is attached (CSV extension renamed as .txt to satisfy restrictions here)

[Homework-GH-data.txt](https://github.com/jasp-stats/jasp-desktop/files/34472/Homework-GH-data.txt)

![reversed-graph](https://cloud.githubusercontent.com/assets/15841065/11160808/466573c8-8a3d-11e5-8554-7e58b7896014.png)

**Comment by jonathon-love** [comment]
oh wow. good catch. we will get onto this right away!

thanks for the report!

**Comment by jonathon-love** [comment]
a lightning fix by @raviselker !

this will be fixed in the next release.

thanks again @bobbyfiend

**Comment by bobbyfiend** [comment]
No problem. I don't think I've ever actually found a bug before. Kind of exciting. And actually my student found it, so I can't take credit. Thanks for going so fast on this. I have been pushing JASP with my undergrad psych stats students after attending your APS presentation in the spring. You're doing amazing work and creating a great resource!
