### ISSUE TITLE
Bayesian LogLinear: Add button to display submodel

### ISSUE THREAD

**Issue by Tahiraj** [jasp-stats/jasp-desktop#1058]
Add the buttons under the statistics tab in Bayesian loglinear model to display the estimates of submodel with the default option of order 1. You can do it like
Statistics -> Display model estimate of order [1] <-  Estimates  and Credible intervals. 
This is important because suppose if we are interested in inference solely based on the model with the second highest posterior model probability, then we can produce posterior summary statistics of that particular model.

**Comment by jonathon-love** [comment]
i'm not exactly sure what you want, something like this? :
<img width="596" alt="screen shot 2015-11-18 at 5 31 57 pm" src="https://cloud.githubusercontent.com/assets/3240247/11246980/57556b58-8e1a-11e5-9e28-7e39cc4289ec.png">

**Comment by Tahiraj** [comment]
You can do like this

**Comment by Tahiraj** [comment]
I have made some changes in B/LogLinear regression codes please merge them.

**Comment by jonathon-love** [comment]
merged.

did you try and send me an image? images can't be sent to GitHub email, so you have to either email me directly, or use the GitHub website.

with thanks

**Comment by Tahiraj** [comment]
Thanks. I have sent on your email.
