### ISSUE TITLE
Help button more prominent?

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1061]
@doramatzke A few people mentioned that the "Help" button is hard to find, and I agree. Perhaps we can think about a way to make that button more prominent. I am not sure whether we should move it to the ribbon, for instance. I am not sure how to address this best, but I think it would be good to address it.

**Comment by raviselker** [comment]
We could add a 'help' entry in the dropdown menu for each analysis:

<img width="861" alt="screen shot 2016-01-08 at 11 48 04" src="https://cloud.githubusercontent.com/assets/4669197/12196270/be102a3a-b5fd-11e5-9327-d0764e19eb84.png">

**Comment by EJWagenmakers** [comment]
Good idea!
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
