### ISSUE TITLE
Suggestion for output

### ISSUE THREAD

**Issue by penpenqueen** [jasp-stats/jasp-desktop#1062]
Please consider that outputs do not have to be in the format of tables. Since APA statements are rather formatted, please consider adding an option where part of the output is standard apa style sentence. For example, assuming a researcher can labels their variables correctly, use the variables listed and resulting data to create the following sentence. 
“A paired-samples t-test indicated that scores were significantly higher for the football (M = 21.21, SD = 7.41) than for the soccer (M = 17.10, SD = 9.49), t(72) = 11.31, p = .02, d = 0.81.”

**Comment by jonathon-love** [comment]
absolutely! we've been thinking about adding this sort of output.
probably won't happen very soon, but definitely something i'd like to get to eventually.

cheers, and thanks for the feedback

jonathon

**Comment by dgromer** [comment]
You may want to check out https://github.com/dgromer/psymisc or https://cran.r-project.org/web/packages/schoRsch/ for implementations of test output formatting according to APA guidelines in R.

**Comment by cnhstreet** [comment]
Another suggestion for the output: it would be great to be able to see the scaling factor used for defining the cauchy prior
