### ISSUE TITLE
B Log. Linear: Error message could be a little clearer

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#1068]
Using the Kitchen Rolls data set:

![loglinerror](https://cloud.githubusercontent.com/assets/8697436/11594481/8de32344-9aaa-11e5-941e-30f0f7d46b71.png)

**Comment by jonathon-love** [comment]
This happens without the interaction.

**Comment by Tahiraj** [comment]
Please send me data set as well.
