### ISSUE TITLE
Error independent t-test: grouping variable must have two levels

### ISSUE THREAD

**Issue by sasazxx** [jasp-stats/jasp-desktop#1069]
Hello, I'm working for the first time with jasp. I have done some analysis with the example data sets and that went very well. When I opened my own data set, however, I got an error when conducting a independent t t-test. The error states that the grouping variable must have two levels but I'm sure by variable has two levels. It isn't much different from the kitchen rolls example data set. Can someone please explain to me why my analysis does not work? The dependent variable is the 'BOC-score' and the grouping variable must be condition.
![jasp error](https://cloud.githubusercontent.com/assets/16159369/11603223/91d58f1a-9ae0-11e5-8a56-5c01871013da.jpg)

**Comment by jonathon-love** [comment]
hi,

can you send through the data file? you should be able to attach a .csv to this issue in github, or you can email me directly.

jon [at] thon [dot] love

with thanks

**Comment by jonathon-love** [comment]
hi @sasazxx 

it looks like your dataset does have three levels after all. see below:

![screen shot 2015-12-06 at 12 02 06 pm](https://cloud.githubusercontent.com/assets/3240247/11613000/5f298f8a-9c11-11e5-8126-f50b6313a033.png)
