### ISSUE TITLE
UI Bayesian t-test is slightly offset

### ISSUE THREAD

**Issue by boutinb** [jasp-stats/jasp-desktop#1075]
the Bayesian t-test looks slightly offset, that is, "Additional Statistics" is too high, and "Additional info" is too much to the right. See the screenshot:
![image](https://cloud.githubusercontent.com/assets/503332/11681928/2d26f6dc-9e62-11e5-99c6-5025a14d27d5.png)

**Comment by jonathon-love** [comment]
this is fixed too.
