### ISSUE TITLE
The Bayesian t-test looks slightly offset

### ISSUE THREAD

**Issue by boutinb** [jasp-stats/jasp-desktop#1078]
The Bayesian t-test looks slightly offset, that is, "Additional Statistics" is too high, and "Additional info" is too much to the right. See the screenshot:
![image](https://cloud.githubusercontent.com/assets/503332/11682218/ba8c4d8c-9e63-11e5-9eee-b3cca74d7979.png)

**Comment by jonathon-love** [comment]
do a rebase.
