### ISSUE TITLE
Batch analysis?

### ISSUE THREAD

**Issue by AliciaFlorrick** [jasp-stats/jasp-desktop#1079]
I have many datasets on which I run a very similar 6 x 2 repeated-measures  ANOVA. Is there a way to save the analysis as a batch and then load it with a new dataset or do I have to write all the condition names every time I open a new dataset?

**Comment by jonathon-love** [comment]
hi alicia,

this is definitely something we want to add in the future! unfortunately, it's not in the current release.

thanks for getting in touch

**Comment by boutinb** [comment]
You can now synchronize a JASP file with different data file in 8.1.0
