### ISSUE TITLE
error after update

### ISSUE THREAD

**Issue by VivRa** [jasp-stats/jasp-desktop#1080]
I did some ANOVAs with JASP without any problems. Today I wanted to continue. During this my computer was making updates (os:linux trusty 14.4) and since this my ANOVA function is not working anymore. Even with files that were working before (also the example files). my JASP version is Version 0.7.5 Beta 1. I already uninstalled and installed JASP two times, still no ANOVA....
![jasp_problem](https://cloud.githubusercontent.com/assets/16226601/11689108/9ce13054-9e90-11e5-83f6-1d7862543693.png)

**Comment by jonathon-love** [comment]
yes, you're right, there is a problem.

i don't think we can support the newer 0.7.5 releases under trusty, and i'm now rolling it back.

it will take about half an hour for the old version to appear in the repo. after that, you can remove jasp, perform a `apt-get update`, and then reinstall jasp.

sorry for the inconvenience.

**Comment by boutinb** [comment]
Does this problem still occur with the latest version (0.8.1)?

**Comment by boutinb** [comment]
If this error still occurs, reopen this issue.
