### ISSUE TITLE
Multi-line graphs are aesthetically odd in that the line markers don't line-up.

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-desktop#1081]
Multi-line graphs are aesthetically odd in that the line markers don't line-up. The markers (e.g., circles) for one line should _NOT_ be horizontally offset relative to the markers on another line (e.g., squares). I noticed this problem when plotting the results of a repeated-measures ANOVA. JASP 0.7.1.12

**Comment by jonathon-love** [comment]
i think this might be a feature, let's ask @raviselker

**Comment by raviselker** [comment]
Yes, it is a feature. The markers are only offset when error bars are plotted. If you would not offset the markers, the error bars would potentially overlap making it impossible to interpret.

**Comment by R180** [comment]
OK. Thanks. Note however, that even with error bars, I think non-offset 
markers are much more common (in psychological reports) than are offset 
ones.

**Comment by AlexanderLyNL** [comment]
This should have been fixed by now.

**Comment by R180** [comment]
I was told that it's by-design, so that each error bar isn't obscured by
another error bar.
