### ISSUE TITLE
simple effects

### ISSUE THREAD

**Issue by goshengott** [jasp-stats/jasp-desktop#1085]
Simple effects
Even though the ANOVA with multiple variables is available, there is no possibility to conduct follow-up simple effects. Simple effects (i.e., ANOVA for an independent variable within one specific level of another independent variable) is a critical analysis to elucidate the nature of an interaction. A simple effects analysis in factorial ANOVA uses the error factor of the omnibus ANOVA and  cannot be replaced with a one-way ANOVA or t-tests.

**Comment by chantelanuit** [comment]
Hi,

I am trying to do simple main effects following a statistically significant interaction. I need this functionality to teach Mixed ANOVA with JASP. Are you considering adding this functionality to JASP ?

**Comment by boutinb** [comment]
This feature should be also added in JASP. Hopefully this will be implemented begin next year.

**Comment by hcp4715** [comment]
Do this functionality added now?

**Comment by AlexanderLyNL** [comment]
This was implemented in 0.8.5
