### ISSUE TITLE
non parametric tests

### ISSUE THREAD

**Issue by goshengott** [jasp-stats/jasp-desktop#1086]
1) Kruskal-Wallis 
2) Friedman ANOVA 
3) Wilcoxon matched pair test
4) Sign test (binomial test for P = 0.5)
5) binomial test

**Comment by jonathon-love** [comment]
binomial test is in the latest beta!

thanks for all the suggestions @goshengott, we'll definitely be looking into providing these in the coming months.

**Comment by coledavis** [comment]
And Mann-Whitney. 
Consider also non-parametric regression.

**Comment by boutinb** [comment]
Mann-Whitney is also implemented
