### ISSUE TITLE
B Log-linear: misleading error message

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#1099]
kitchen rolls, mean_NEO doesn't contain negative values or infinity.

<img width="1292" alt="screen shot 2015-12-11 at 4 43 25 pm" src="https://cloud.githubusercontent.com/assets/3240247/11748008/6ed8e796-a026-11e5-8e15-453b916b8f2d.png">

**Comment by Tahiraj** [comment]
mean_NEO  has negative number e.g., row 5 is  -0.5, row 17 is -0.166667.
