### ISSUE TITLE
Paired T-Test plot label error

### ISSUE THREAD

**Issue by kfinstad** [jasp-stats/jasp-desktop#1100]
When conducting a paired samples t-test the order of variable labels in the plot assumes the order they were entered into the analysis, and don't always line up with the variable values. 
![2015-12-11_10-00-18](https://cloud.githubusercontent.com/assets/16258945/11751431/57a1e45c-9fee-11e5-96ff-42e4e84ecfea.png)
Entering these two variables in the opposite order gives the correct label order in the plot.

**Comment by quentingronau** [comment]
Hi, it is difficult for me to reproduce the error. Could you maybe provide the .csv file you used?
You can, I think, attach it here on github or you can send it to quentingronau@web.de. Thanks!

**Comment by raviselker** [comment]
This was a bug in the previous release (see issue #1054). It should be fixed in the latest beta release.
