### ISSUE TITLE
Editing graphs?

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-desktop#1105]
JASP already does almost everything I would need it to do for teaching and research. A major exception is the graphs. As far as I can tell there's no way to edit them (e.g., line thicknesses, marker sizes, bar patterns, text size, axis ranges, major/minor tick marks, reference lines). And there is no way to export the graph as a high resolution rastor file or as a pdf. Or is there some way to actually do all of these things in JASP?

**Comment by jonathon-love** [comment]
hi @R180 

alas, no, not at present. something we'd definitely like to add in the future.

cheers

**Comment by boutinb** [comment]
The next release we will offer the possibilty to export the graph in eps format

**Comment by hcp4715** [comment]
@boutinb is it possible to export eps format plot now?
I guess it is really important for many ;-)

**Comment by lindeloev** [comment]
Yes, click the drop-down menu just above the graph. Then click "Save image as..." and choose eps format.
