### ISSUE TITLE
Repeated measures graphs display horizontal axis variables alphabetically instead of in order specified by analysis

### ISSUE THREAD

**Issue by mjkofler** [jasp-stats/jasp-desktop#1110]
Current JASP version for Mac (downloaded today) on OS X El Capitan

How reproducible: Give descriptive labels to repeated measures cells. Create graph with these cells on the horizontal axis. I also had a between-groups factor with 2 groups in case that matters.

Expected results: Displays the cells in the order specified by the ANOVA
Actual results: Displays the cells in alphabetical order on the x-axis

If I then rename the cells 1, 2, 3, 4 and recreate the graph, they show in the correct order. But if I label them Pre-treatment, Post-treatment, Follow-up 1, Follow-up 2, then they display in alphabetical order along the x-axis as Follow-up 1, Follow-up 2, Post-treatment, Pre-treatment. I would like to show them in temporal order (corresponding to the order they're listed in the repeated-measures ANOVA) rather than alphabetical (it is confusing to show follow-up before pre-treatment).

BTW, loving JASP so far! Keep up the great work!

**Comment by jonathon-love** [comment]
hey, thanks for the report.

try the latest 0.7.5 beta, i'm pretty sure this is fixed.

jonathon

**Comment by mjkofler** [comment]
Works as expected in the 0.7.5 beta. Thanks for the quick reply!

Michael
