### ISSUE TITLE
Confidence Intervals & feature requests

### ISSUE THREAD

**Issue by MichlF** [jasp-stats/jasp-desktop#1111]
Hi,

it has been a while since I checked this program out. The latest version has improved a lot with respect to the last version I used. Great program now! Keep it up!

I have a question and a couple of feature requests.
Question:
For repeated-measures ANOVAs (non-bayesian), how are CIs calculated? Based on the Loftus & Masson (1994), Cousineau (2005), or Cousineau with Morey (2008) correction?

Feature requests:
- First, a small bug: If I have a RM factor with 10 levels and label each level with a consecutive number, the plotting of this factor will be ordered incorrectly. I.e. assume I would plot an RM factor with 10 levels along the horizontal axis. It will order it 1-10-2-3-4-5-6-7-8-9 instead of the correct order (1 thru 10).
- It would be very very nice if I would not always have to use .csv files to load in my data but to use some sort of an excel like spreadsheet editor (which already exists for displaying the values) in which I could simply copy and paste my values.

(- Speaking about plotting: It would be nice to have more options when plotting. Aside from adding colors, the most important feature would be to be able to adjust the x- and y-axis ranges and maybe have more value labels next the max and min value.) --> Just noticed this feature has been requested before. Looking forward to see it being implemented.

Thanks for putting so much effort into this project. It really pans out nicely.

Best,
Michel

**Comment by raviselker** [comment]
Great that you enjoy using it!

To answer your question:
We use the Morey's (2008) correction to Cousineau (2005) to calculate the CIs for the RM measures ANOVA and the paired t-test.

About the feature requests:
1. Which version are you using? I think this was an issue in a older version that I already fixed, so if you download the latest version this should already be fixed? If I try to replicate the bug in my version (0.7.5 Beta 3) I get the correct ordering:

<img width="1440" alt="screen shot 2016-01-06 at 17 49 47" src="https://cloud.githubusercontent.com/assets/4669197/12148374/5620e9f6-b49e-11e5-8f45-676f898bad15.png">

2. Building a data editor is very high on our priority list, so this feature will definitely be added (hopefully sooner than later).

3. (about the plotting) This is definitely on our list, just not as high up as some of the other features :)

**Comment by MichlF** [comment]
I am using the version JASP 0.7.1.2 and I think I downloaded it like a week ago from the official homepage. But I guess if it is fixed in the latest beta version, then that won't be a problem anymore in the next non-beta version.

Concerning the CIs: I also traditionally use the Cousineau method with Morey correction. I have tried now several data sets, but sometimes my plotted CIs clearly deviate from the graphs in JASP, while other times the seem to be identical (I cannot be certain since I dont see the exact values in JASP). Now I wonder which script is correct? ;)
I am tempted to say mine (cause I checked the script already in the past over and over again), but I will monitor this in the future (versions of JASP) and look whether I find patterns in the differences. I'll let you know in case I should find something that concerns your program.
Something linked to that topic: It would be nice if there is some documentation on this (e.g. description of which methods are used). Did I miss it and it is somewhere on the homepage or in the program? I could not find it.

Best,
Michel

**Comment by raviselker** [comment]
It would be very helpful if you could send an example data set where the CI's in JASP deviate from the CI's in your script, and the script that you used to produce the CI's. You should be able to attach the files directly to this issue in github or you can email me directly (selker [dot] ravi [at] gmail [dot] com).

About the documentation: we are planning to add information like this to the help files. At the moment we haven't finished all help files (so no help file for RM ANOVA just yet), but the paired t-test help file already documents the use of this method:

<img width="1440" alt="screen shot 2016-01-06 at 18 30 41" src="https://cloud.githubusercontent.com/assets/4669197/12149422/f0263d8a-b4a3-11e5-84fc-3b4eb2cc9051.png">

**Comment by boutinb** [comment]
@MichlF Do you have still this problem with latest version of JAS (0.8.1)P?

**Comment by knaeckebrot0815** [comment]
Would it be possible to add the information which kind of error bar is plotted in a footnote? And/or make it an option which one is used (or whether both are plotted)? 

Especially in mixed designs, the majority of users might assume that the error bars are "normal" between-subject error bars, but both might make sense depending on the question being answered. Especially since the summary statistics only show the between subjected standard error, that's not very coherent.

I only got here because my matlab plots deviated. 

Many thanks!!

**Comment by EJWagenmakers** [comment]
Seems sensible & useful. Thanks for the request. Bruno/Frans, can you perhaps assign this to somebody?
E.J.

**Comment by FransMeerhoff** [comment]
@TimKDJ 

Hi Tim, can you have a look at this one. 
If you do any action on this  perhaps it is wise to make a new issue for this.
BTW see also 
Error bars: standard errors #1116

**Comment by markovendelin** [comment]
Hi,

we have been hitting this issue as well and were as confused as in https://github.com/jasp-stats/jasp-desktop/issues/1116. In particular, we have about 10 measurements within subject and it makes more sense to us to be able to see standard error (or confidence) that represents variability of that particular measurement than to have CIs corrected for within-subject design.

In the shown example, I plot only one group of the subjects. Can't do repeated ANOVA on it, obviously, but it shows clearly an issue in hand. The plot produced by JASP (on the left) using Repeated measures ANOVA indicates that we have great confidence in the values close to the average and measurements are way off at the ends. The plot produced by taking SEMs per point without correcting for within-subject design, show rather different story (the right).

I would like to suggest adding an option when plotting repeated ANOVA results which would allow us to choose how to show the data. In essence, I would like to be able to get option "A" in Fig 1 of http://pcl.missouri.edu/sites/default/files/morey.2008.pdf .

Thank you very much for writing this software, its of great help!
![comparison_of_se](https://user-images.githubusercontent.com/3975391/38602631-fe5d1828-3d73-11e8-8d94-9e191df564e0.png)

**Comment by EJWagenmakers** [comment]
Interesting. 
@JohnnyDoorn, @Janto91 ?

**Comment by JohnnyDoorn** [comment]
Hi Marco,
Which version of JASP are you using? In the latest version (8.6), we added an option to pool the SE across the RM factors when plotting error bars, which should result in option A from the article you linked. See the attached screenshot for where to find this option. Please let me know if this is not what you are looking for, as there are multiple ways of going about this type of plotting. 
Kind regards,
Johnny
![poolse](https://user-images.githubusercontent.com/15704203/38810419-ff786412-4186-11e8-8d5a-8ed2c3c5d933.png)

**Comment by markovendelin** [comment]
I am on GitHub master branch. Would love to test it, but the build is broken due to https://github.com/jasp-stats/jasp-desktop/issues/2469 . Let's see who will manage to fix it first (I'll probably can do it towards the end of the week)

**Comment by markovendelin** [comment]
I didn't realize that I was on development branch. When switching to the master, all compiled, as expected. And I can pool the errors, as expected, thank you!
