### ISSUE TITLE
feature requests: z-tests + chi-squared multinomial proportions

### ISSUE THREAD

**Issue by MDSOPT** [jasp-stats/jasp-desktop#1115]
Firstly, thanks for a great piece of software.  I'm thinking of implementing JASP for an intro to business statistics undergraduate class.  The following techniques would be useful.
Single sample z-test
Two sample z-test
Single sample z-test for proportions (normal approximation to binomial)
Two sample z-test for proportions (normal approximation to binomial)
I realize that an argument can be made that these tests are redundant and that the assumptions (e.g., assuming population s.d. = sample s.d.) are problematic. But, most undergraduate intro courses utilize these tests. In fact, in my team taught class I need to teach these subjects.  I will usually show how the t-test converges to the z-test for large sample sizes.  A side by side z/t test comparison would be great and would help JASP supplant MINITAB as well as SPSS!

In addition, I see that there is a chi-squared test in the contingency tables.  It would also be useful to have a one-way chi-squared test for multinomial proportions.

Thanks!
Stephen

**Comment by AlexanderLyNL** [comment]
Multinomial added
