### ISSUE TITLE
Error bars: standard errors

### ISSUE THREAD

**Issue by AliciaFlorrick** [jasp-stats/jasp-desktop#1116]
[Standard Errors.xlsx](https://github.com/jasp-stats/jasp-desktop/files/87321/Standard.Errors.xlsx)

It seems that the error bars displaying standard errors do not correspond to the values of standard errors (and when I plot the graphs in Excel, the error bars look much, much bigger). Are standard errors for the graphs computed differently?

**Comment by raviselker** [comment]
Hi Alicia,

We use different standard errors for within subject designs (Morey's, 2008, correction to Cousineau ,2005, see issue #1111). For more information why use this correction, see http://pcl.missouri.edu/sites/default/files/morey.2008.pdf.

Cheers,
Ravi

**Comment by AliciaFlorrick** [comment]
Thank you for your quick reply!
