### ISSUE TITLE
Self identification of JASP

### ISSUE THREAD

**Issue by janderuiter** [jasp-stats/jasp-desktop#1121]
This is arguably not very urgent, but I still would like to point it out, as it should be very little effort to implement. 

Mac OSX programs usually have an item in the menu item <program name> (here: JASP, next to the apple symbol) which is called "ABOUT <program name>". Clicking it gives you (at least) the date and version number of the current program. This is very practical, for aside from the startup screen, I wouldn't know how to detect which JASP version I'm currently using. (I think Windows programs have a similar provision, but I'm not sure about that).

**Comment by EJWagenmakers** [comment]
Good point JP! We have wanted to include an "about" tab for a while. We'll give that some more priority.
