### ISSUE TITLE
Cauchy prior width

### ISSUE THREAD

**Issue by fdabl** [jasp-stats/jasp-desktop#1122]
hey guys,

I was planning to demo the issue of completely uninformative priors for model selection, but it seems that the max Cauchy prior width is set at 2. Is there any reason for this? Now we're missing out on a great visualization of an important point!

cheers,
Fabian

ps.: I also noticed that your latest JASP release doesn't have a linux ppa ... can the (granted, very small) linux community hope that this is only temporary? :)

**Comment by EJWagenmakers** [comment]
@FransMeerhoff @boutinb 
Hi Fabian,

Ah, not sure why the max is at 2 -- I guess we felt that was wide enough, but I agree it would be useful for teaching purposes. I am not sure what a Linux ppa is, but we are definitely still supporting Ubuntu. A new release is in the works. 

Cheers,
E.J.

**Comment by stephensrmmartin** [comment]
https://launchpad.net/~jonathon-love/+archive/ubuntu/jasp

Is the ppa. I assume it is still working.

**Comment by boutinb** [comment]
@fdabl Do you have still problem with the Ubuntu version?

**Comment by boutinb** [comment]
If this error still occurs, reopen this issue.
