### ISSUE TITLE
Descriptive plots for Bayesian ANOVA

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1129]
Presently we have a descriptive plot in the classical ANOVA, but not one for the Bayesian ANOVA. Can we please have one? @raviselker: for the classical test you just use 95% CIs on the means, right? We can basically use the same intervals (if we simply use uniform priors, which I'm OK with because these are raw means and we do not know the scale). So then we can just use the same code as Ravi already made (and include a note that this is under a uniform prior). I'll add this to the feature request page, but I hope we can do this soon.

**Comment by TimKDJ** [comment]
This was added in PR #1603
