### ISSUE TITLE
On dataset

### ISSUE THREAD

**Issue by khamiz** [jasp-stats/jasp-desktop#1130]
Hello,
I'm trying to analyze a dataset that contains five different locations with multiple samples per location across time. Each samples has multiple variables. The descriptive statistics cannot separate the values based on locations. Any advice on how to organize the data to see differences among locations and time?
Thanks

**Comment by fnymnky** [comment]
I agree: it would be very useful to be apply to apply a grouping variable to the descriptive statistics of another.  My particular application is comparing reaction times on different conditions, I want to see mean and SD for condition 1 separately from condition 2.  

Current workaround: just split the data into separate files by condition and analyze them separately.  This works, but is clearly not ideal, especially when I will also be wanting to perform statistical tests comparing the conditions, requiring them in the same file.

**Comment by akashrajkn** [comment]
Descriptive analysis now has a 'Grouping Variable'
