### ISSUE TITLE
Minor issue regarding layout on EJs miserable laptop (Windows)

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1133]
In the Bayesian t-tests (independent and paired) the final "h" in "Cauchy prior width" drops off. Note: this is on my Windows laptop which is notorious for screwing things up. So it might not be a high priority. Damian improved the layout on Windows a lot but maybe he missed this one. See screenshot.
![image](https://cloud.githubusercontent.com/assets/8603015/12611962/02553f68-c4f0-11e5-95d9-bb0b38d70594.png)

**Comment by vankesteren** [comment]
This EJ's miserable laptop has the same

![image](https://cloud.githubusercontent.com/assets/11596858/24955125/7b9287ee-1f82-11e7-8677-ebc20d5096f8.png)

**Comment by boutinb** [comment]
This will be solved with Qt5.9, that solves High Definition problem on Windows

**Comment by akashrajkn** [comment]
v0.8.6 solves high dpi problems to some extent.
