### ISSUE TITLE
Infelicity in ANOVA

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1135]
From Chris Madan through twitter: "small 'issue', changing variables in ANOVA updates the stats right away, but not plots (need to remove/add factor to get redraw)" @mmarsman1 @raviselker ?

**Comment by cMadan** [comment]
Issue occurs in both 0.7.1.12 and 0.7.5 Beta 2. Tried both versions on Mac, only stable (not beta) on Windows.

I ran a 2x2 repeated-measures ANOVA (1 within-subject factor, 1 between-subjects factor). If I change the two variables for the within-subjects factor, the statistics in the table update automatically. However, the descriptives plot does not re-draw unless I remove one of the factors from the plot and then re-add it.

**Comment by raviselker** [comment]
Thank you, I can replicate the issue now. I will fix this for the next release.

**Comment by raviselker** [comment]
Fixed
