### ISSUE TITLE
Cohen's d calculation

### ISSUE THREAD

**Issue by Theon500** [jasp-stats/jasp-desktop#1137]
Hello,
What formula are you using to compute the Cohen's d estimates that you report,, for example, in independent samples t-test?  The values seem to be a little off, when compared to the traditional Cohen's d formula.
Please let me know.
Thanks,
NMDowlling

**Comment by raviselker** [comment]
Are you using version 0.7.5 Beta 2? If so, someone already mentioned a similar issue (#1106) and the fix will be included in the next release.

**Comment by Theon500** [comment]
Thanks for your quick response on the Cohen's d calculation. Yes, I am using version 0.7.5 Beta 2.

I'm looking forward to the next version!!



________________________________
