### ISSUE TITLE
"Unable to save file" + weirdness copy-pasting text

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1138]
I have edited and saved a file several times without problems (Beta 3 release). However, I then copy-pasted some text in the notes and observed the following:
(1) The copy-paste functionality did not really work very well. I will try this out a few more times.
(2) When I was ready editing and tried to save the file, it returned the message "unable to save file". I restarted my computer, opened the file, added a character to the notes, and tried to save again, with the same result. See screenshot. This will be frustrating for the user! 
![image](https://cloud.githubusercontent.com/assets/8603015/12722479/65d0eb46-c905-11e5-82cd-ae0a6fb7b87e.png)

**Comment by EJWagenmakers** [comment]
UPDATE! 
(1) The error message was correct after all: the file was open in a different JASP window. Sorry.
(2) The copy-paste functionality works fine if you use text from a text file or from within JASP. But go to the JASP website, select the text "0.7.5 Beta 2", and copy-paste it in the notes, in the middle of some text. What I see (and @raviselker was there to confirm :-)) is that the inserted text overwrites some existing text.

**Comment by boutinb** [comment]
Do you have still this problem?

**Comment by EJWagenmakers** [comment]
Yes, the copy-paste functionality still overwrites parts of the old text.
E.J.

**Comment by boutinb** [comment]
@EJWagenmakers I cannot reproduce it. Do you have a reproduction path?
