### ISSUE TITLE
Input file types - delimited txt files

### ISSUE THREAD

**Issue by cMadan** [jasp-stats/jasp-desktop#1142]
When opening a data files, JASP says it only accepts csv files. I prefer tab-delimited txt files and found that renaming a tab-delimited txt to ".csv" does work properly. 

It would be nice if JASP allowed txt files as input (could call it "tab-delimited txt" or "delimited txt" to be more clear about formatting), so this renaming was un-necessary.

**Comment by boutinb** [comment]
This should be fixed in the next release
