### ISSUE TITLE
Support for Debian & installation instructions

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1146]
At the workshop in Lund, one of the participants pointed out that installing JASP on Debian is a pain. He is an astronomer and apparently all of them use Linux. He also said that the difference between Ubuntu and Debian is small, so that we could easily do a Debian release if we already do Ubuntu. 

Regardless of whether we will or will not support Debian, perhaps the download page ought to be clearer on where the source code is, and where the user can find instructions for installing the program.

**Comment by Argafal** [comment]
Some of the pain while trying to compile JASP on Debian Linux has been documented here:
https://github.com/jasp-stats/jasp-desktop/issues/764

**Comment by EJWagenmakers** [comment]
Thanks, that's very useful!
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by aknight1-uva** [comment]
We could go one step further - Build Debian Linux 'flavours' of JASP on Debian and place the DEB packages from the JASP website. Doing this would make the Ubuntu packaging MUCH simpler.

**Comment by mih** [comment]
@EJWagenmakers is there anyone on record to be working on making a package for Debian proper?

If not, I might give it a try. First targeting NeuroDebian, while aiming for eventual inclusion into Debian proper.

**Comment by EJWagenmakers** [comment]
@mih
@akashrajkn 
Hi  Michael,

Any help would be appreciated! Perhaps we could kickstart this by having you over for a visit to our group?

Cheers,
E.J.

**Comment by FransMeerhoff** [comment]
HI @mih 

It would be indeed be very helpful for us to give that a try anyway.

Kind regards
Frans Meerhoff

**Comment by mih** [comment]
A visit would be lovely! But let's first see how far we can get right now. We will do this as a project in the lab's hackathon this Friday.

Pointers to any secret sauce you guys are using to build the PPA packages would be much appreciated. The stuff under `tools/debian` doesn't look like the complete set of what it would need.

**Comment by mih** [comment]
Ah, I missed the .pro file -- maybe it is all there...

**Comment by stephensrmmartin** [comment]
I packaged this for arch linux, including a package of r packages needed for jasp to run. My method may provide some inspiration, and if there's any improvements to be made, I can make them.

In particular,  I really dislike how I had to bundle the r packages  (forcing them to install in the r system library rather than in the jasp folder....).

**Comment by stephensrmmartin** [comment]
Oops,  meant to mention that you can view the build scripts at the AUR if you search for jasp. Two packages are there, one for jasp, one for the r bundle.

**Comment by mih** [comment]
Thanks!

A quick check seems to indicate that we are goods with the deps on Debian
(minus one license issue).

**Comment by allefeld** [comment]
Hi, @EJWagenmakers, after your talk this morning I wanted to give JASP a try, but I'm a Debian user, so I would very much appreciate Debian packages, too.

**Comment by akashrajkn** [comment]
We now ship a flapak based app :)
