### ISSUE TITLE
Bayesian repeated measures ANOVA

### ISSUE THREAD

**Issue by groeinarsdottir** [jasp-stats/jasp-desktop#1147]
Hi there!

Let me just start by saying thank you for this great program. I am very excited about getting started with bayesian analysis (without having to first learn R). 

I tried to conduct a repeated measures Bayesian ANOVA with two factors, each containing three levels. The problem is that the after half an hour the analysis is still loading. So there is no error message, and the program has not crashed or anything, but the buffering circle just keeps spinning without any output coming out.

I´m using the newest version of JASP 0.7.5. beta on a windows computer. 
I´m not sure what I should say about my dataset. It contains answers from around 700 participants and I can send it to you if that helps you to figure out the problem.

All the best
Gró

**Comment by raviselker** [comment]
@mmarsman1 ?

**Comment by mmarsman1** [comment]
Hi Gró, 

Sorry for the late response; I was without internet the past two weeks (the horror!). 

The current implementation of Bayesian Repeated Measures often takes a (very) long time to compute, especially when there are many subjects (in your case 700). I think it had to do with the need to repeatedly invert a large covariance matrix, which is not optimised for these type of analyses yet.

The easiest way to improve the speed with which the analyses are conducted now is to reduce the number of models that need to be computed and mark effects that do not require testing as nuisance.

I hope that clarifies the issue!

Kind regards, 
Maarten

**Comment by groeinarsdottir** [comment]
Thank you for the reply. That explains things.


all the best

Gró

________________________________
Från: Maarten Marsman <notifications@github.com>
Skickat: den 15 februari 2016 12:00
Till: jasp-stats/jasp-desktop
Kopia: Gró Einarsdóttir
Ämne: Re: [jasp-desktop] Bayesian repeated measures ANOVA (#1147)


Hi Gró,

Sorry for the late response; I was without internet the past two weeks (the horror!).

The current implementation of Bayesian Repeated Measures often takes a (very) long time to compute, especially when there are many subjects (in your case 700). I think it had to do with the need to repeatedly invert a large covariance matrix, which is not optimised for these type of analyses yet.

The easiest way to improve the speed with which the analyses are conducted now is to reduce the number of models that need to be computed and mark effects that do not require testing as nuisance.

I hope that clarifies the issue!

Kind regards,
Maarten

-
