### ISSUE TITLE
ANOVA: "Compare main effects" t-values?

### ISSUE THREAD

**Issue by fladd** [jasp-stats/jasp-desktop#1152]
I was wondering, how the t-values for the marginal means are calculated?

I first assumed that this is a simple t-test, but checking in R with the same data quickly revealed that a t-test yields much more conservative results.

This bears the question of how exactly the t-values are calculated, what they reflect, and what the error df are?

Thanks.

**Comment by raviselker** [comment]
Marginal means are not the same as simple t-tests. We use the `lsmeans()` function from the `lsmeans` package to calculate the marginal means. Here's an example:

```{r}
# fit a linear model to ToothGrowth data set
model <- lm(len ~ supp*as.factor(dose), data = ToothGrowth)

# calculate the marginal means
margMeans <- lsmeans::lsmeans(model, ~supp*dose)

# extract bonferroni adjusted p-values
summary(margMeans, adjust = "bonferroni", infer = c(TRUE,TRUE))
```

**Comment by fladd** [comment]
Thanks for the answer! I am especially interested in understanding what the df2 to report would be for those tests. Are they the same as for the corresponding t-test?

**Comment by buraczku** [comment]
Hi, 

I have a similar question. I would like to use JASP to teach ANOVA in the classroom, but the marginal means table for the interaction is hard to interpret. It is specifically difficult to show what is compared with what. Is there a way to observe them as in the post-hoc comparisons table?

Thanks!

**Comment by boutinb** [comment]
@JohnnyDoorn Can you have a look to this question (with maybe Quentin)

**Comment by JohnnyDoorn** [comment]
Hi, 
If I'm not mistaken, the marginal means tables for the (RM) ANOVA in JASP show the means and standard errors per level (or combination of levels) of ANOVA factors. The T-statistic that is shown is computed as the mean divided by SE. These are not so much comparisons between levels (you can use the post-hoc tests for that), but are one-sample t-tests to test if the means differ significantly from 0. 
Cheers,
Johnny

**Comment by buraczku** [comment]
Thank you for your reply Johhny,

I was thinking about a traditional between-subjects anova. If I am not mistaken the posthoc option in JASP is only avilable for the main effects, not the interaction (to compare each cell with one another). This is also a tedious task in spss, one has to paste the analysis and modify the compare means line in the syntax to get these values.

Would you like me to provide an output using the tooth growth data to illustrate what I mean?

Thanks again,

**Comment by JohnnyDoorn** [comment]
Hi,
Thanks again for your input! Do you mean the output I included below?
![margmeanstablejasp](https://cloud.githubusercontent.com/assets/15704203/25136133/694b57e2-2454-11e7-9ccc-420cc8c55ede.png)

If I understand correctly, you would like to do a posthoc test on the interactions, which at the moment is not yet possible in JASP, but it's on our todo list for future releases.
On the other hand, the marginal means test does allow for interactions, but it merely tests for differences with 0, instead of testing different cell means against each other. 
I hope this clarifies it a bit, but feel free to elaborate!
Cheers,
Johnny

**Comment by buraczku** [comment]
Yes, exactly what I meant. Thank you very much for your detailed response.

Looking forward to having this feature, I am sure it will be helpful to many who would like to teach using JASP.

All best,
Buraczku

**Comment by AlexanderLyNL** [comment]
https://jasp-stats.org/download/
