### ISSUE TITLE
Analysis termination error if percentiles are requested in descriptives

### ISSUE THREAD

**Issue by jdittrich** [jasp-stats/jasp-desktop#1163]
**Version:** 0.7.1.12, Ubuntu 14.04

**Steps to reproduce the error:** 
1. Open a dataset (e.g. the Big 5 Example)
2. Choose Common -> Descriptives
   1. Add a variable (e.g. Neuroticism)
   2. Expand »Statistics«, check any "Percentile Values" checkbox (e.g. "Quartiles")

**Error Message**: Red box in the output area: »_This analysis terminated unexpectedly. Please contact it’s author. Error in quantile.default(na.omitted, c(0.25), type = 6, names=F)_

**Comment by boutinb** [comment]
This is solved in the last version of JASP
