### ISSUE TITLE
Missing Descriptive Frequency Table

### ISSUE THREAD

**Issue by rustbelt** [jasp-stats/jasp-desktop#1180]
I'm just starting out with both JASP and statistics, so I'll apologize for my stupidity in anything I say…incorrectly.

I need to display a frequency table for a sample dataset that I'm using and checking "Display Frequency Tables" doesn't do so. HELP!!! :-)

…and thank you very much!

Setup:
Mac OS 10.11.3
2.6 GHz Intel Core i7 with 16GB RAM.
JASP Version 0.7.5 Beta 2

And a screenshot to boot:
<img width="1353" alt="screen shot 2016-02-18 at 9 48 20 pm" src="https://cloud.githubusercontent.com/assets/17328047/13165352/a11ee5f8-d68a-11e5-9512-ae8d88671246.png">

**Comment by boutinb** [comment]
This must be for nominal or ordinal variable. You chose a scale variable.
