### ISSUE TITLE
Visualization bug in contingency tables

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1183]
Hi guys,

This is a bug I found in the beta3 version (but I'm pretty sure it will be in the other releases too). I run a Bayesian contingency table, tick the two boxes under "Plots" (everything fine so far) and then I also tick the box "Log odds ratio" under "Additional Statistics". Ticking that box makes the plot disappear! I'll Email the jasp file separately.

![image](https://cloud.githubusercontent.com/assets/8603015/13196856/7510bfac-d7db-11e5-9feb-0533424cda0f.png)

**Comment by EJWagenmakers** [comment]
Oh, the screenshot shows that there is no plot and the "log odds ratio" box is unticked. That is perhaps confusing. Ticking that box made the plot disappear, and unticking it did not make it re-appear.

**Comment by akashrajkn** [comment]
This does not occur in v0.8.6. (Tested on ubuntu)
