### ISSUE TITLE
"p<.001" issue

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1184]
@raviselker 
I noticed that in the classical binomial test, p-values that are lower than .001 are summarized by "p<.001". Is this the case for other classical analyses as well? I would think that --similar to how we report extreme values for the Bayes factor-- we might want to switch to scientific notation for those cases. The way we are doing it now just hides information which some people might find relevant (I personally care whether p=.0009 or p=.000000000000000000000000000000000000000000000000000000000001.

**Comment by raviselker** [comment]
It's best if we make the p-value in the table clickable so you can access the actual p-value if you would like to. Summarizing this to p<.001 by default is nice behavior as it makes the table very clear. Btw, all the classical analyses do this.

**Comment by EJWagenmakers** [comment]
I agree it makes the table look nice, but the information should be
available somehow. An alternative is to make this an option somewhere.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam
Nieuwe Prinsengracht 130
1018 VZ Amsterdam, The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by hvidaldossantos** [comment]
Ciao all,
As some journals require exact p values for publication, not having the option to get exact p values in tables or at least access this information otherwise, turns out to be a deal breaker.
I would be happy to contribute to this, but I'm new to JASP and I don't know how the program is structured. In particular I don't know where to find the code that creates tables.
Thanks

**Comment by EJWagenmakers** [comment]
@AlexanderLyNL @TimKDJ  @vankesteren 
Thanks for the feedback. We hope to address this soon.

**Comment by AlexanderLyNL** [comment]
Just to clarify to the people following this thread. We now have implemented a global option that allows JASP to report the exact p-value. By default we report p<.001 (in accordance to APA guidelines), whenever the exact p-value is indeed smaller than .001. When the exact p-value option is turned on and the p-value is small, we now report its exact value in scientific notation. This feature will be implemented in our next release.

**Comment by vankesteren** [comment]
Hi,

We just created a pull request for this. Look for the "display exact p-values" preference setting in the next release of JASP!

[gif](http://i.imgur.com/uQLNhCO.gifv)

Cheers.

**Comment by hvidaldossantos** [comment]
Sorry to add this here in a closed tread, but this is very much related.
I noticed a similar problem with effect sizes. In particular with omega squared. When effect size is extremely small, JASP displays 0.000. Of course it can be inferred that the size is not zero, but a very small number. Would it be possible to display the exact effect size in scientific notation?

**Comment by EJWagenmakers** [comment]
I am not 100% sure whether this holds here, but I do know that in some cases, the frequentist estimate of effect size is exactly zero. This is sometimes done when the actual estimate is negative (and the effect size measure is a percentage). Not sure whether that's the case here though. Maybe @JohnnyDoorn knows

**Comment by hvidaldossantos** [comment]
Hi,
Omega^2 can range from -1 to 1 (is not a percentage). Negative values result when F < 1, which is the case in my analysis. Could it be that JASP is rounding to zero?

It might also be that is common practice to report zero when F is smaller than 1. According to Lakens, this might be the case, but reporting negative values might be better for future meta-analysis.

More here:
http://daniellakens.blogspot.it/2015/06/why-you-should-use-omega-squared.html
