### ISSUE TITLE
Feature request Z statistic for Wilcoxon and Mann-Whitney

### ISSUE THREAD

**Issue by vdsmagt** [jasp-stats/jasp-desktop#1187]
Nice to see you've implemented non parametric T-test alternatives! (still hoping for kruskal-wallis and friedman though ;-)). In most papers in my field, the test-statistic reported for those non parametric tests is the z statistic instead of the W or U. Would it be possible to add that one? And the r as effect size for the both non parametric would be highly appreciated too.

keep up the good work!

**Comment by AlexanderLyNL** [comment]
https://jasp-stats.org/download/
