### ISSUE TITLE
Bug in classical repeated measures ANOVA

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1197]
@raviselker 
So I'm illustrating this repeated measures ANOVA at the AMC (the classical one, by mistake). And JASP throws a fit, for the insect data. See screenshot.

![image](https://cloud.githubusercontent.com/assets/8603015/13318033/c3b4f12e-dbb8-11e5-98f6-6f620e79d74c.png)

**Comment by raviselker** [comment]
That's weird, it works on my mac:

<img width="1552" alt="screen shot 2016-02-25 at 12 20 10" src="https://cloud.githubusercontent.com/assets/4669197/13318272/3613ad04-dbba-11e5-9f2a-f46c45ae781c.png">

Maybe the 'afex' package is not included in the windows build. @boutinb, @FransMeerhoff?

**Comment by raviselker** [comment]
Fixed

**Comment by eort** [comment]
Hi, 

Is the fix already released? I am working on Ubuntu 14.04, use jasp 0.7.5 and bumped into the same issue. I had to downgrade to 0.7.1 to be able to run the repeated measures ANOVA. 

Eduard

**Comment by boutinb** [comment]
Does this problem still occur with the latest version (8.1.0)?

**Comment by boutinb** [comment]
If this error still occurs, reopen this issue.
