### ISSUE TITLE
Feature request: vector graphics

### ISSUE THREAD

**Issue by saviochan** [jasp-stats/jasp-desktop#1198]
We need the flexibility to modify the graphics for more effective data visualization and publications.

**Comment by jdittrich** [comment]
Do you mean being able to export vector graphics ( like in #1225 ?) or editing them *in* JASP?

**Comment by saviochan** [comment]
Yes, export.

**Comment by boutinb** [comment]
EPS export will be implement in the release (in April/may probably).

**Comment by AlexanderLyNL** [comment]
https://jasp-stats.org/download/
