### ISSUE TITLE
JASP puts your computer at risk message

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1200]
This may be unavoidable, but Windows warns the user about installing JASP. If we can figure out something to avoid this it would be great. I don't think I get this message when I install other Open Source software...

![image](https://cloud.githubusercontent.com/assets/8603015/13322808/8482c440-dbd6-11e5-85e0-7aa459302bd9.png)

**Comment by aknight1-uva** [comment]
The JASP installer is not providing a signature and certificate  for the app - one way of going this is shown here: http://blog.didierstevens.com/2008/12/31/howto-add-a-digital-signature-to-executables
I would guess the simplest way of doing the signature is to use a (paid-for?) Microsoft IDE to build the MSI files...

**Comment by boutinb** [comment]
This should be solved when we have a certificate. Coming soon.

**Comment by akashrajkn** [comment]
@boutinb this issue is resolved I think.
