### ISSUE TITLE
JASP release does not add to "installed programs"

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1202]
After installation, my laptop indicates that JASP (0.7.5.1) has been installed, but it does not place an icon in the menu:

![image](https://cloud.githubusercontent.com/assets/8603015/13323102/32800002-dbd8-11e5-95d9-045eb9855622.png)

**Comment by FransMeerhoff** [comment]
Can't reproduce anymore.
