### ISSUE TITLE
OSF sync

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1203]
I'm using the new version and trying the OSF sync. First thing I noticed is that I do not need to log in to the OSF: it immediately shows the contents of my stuff on OSF. I am not sure how this is possible -- does it get that information from a previously installed version? This is not safe; I should be required to log back in after installing a new version of JASP.

![image](https://cloud.githubusercontent.com/assets/8603015/13323262/ee83868e-dbd8-11e5-9d4b-4d18a5404a43.png)

**Comment by raviselker** [comment]
Fixed: implemented the "remember me" option.
