### ISSUE TITLE
Bug in Descriptives Plot in Repeated Measures ANOVA

### ISSUE THREAD

**Issue by ansanborn** [jasp-stats/jasp-desktop#1206]
I am using the non-Bayesian repeated measures ANOVA, and I like the plots that it produces. However, in this case I found the descriptives plot did not match the descriptive means. In the screenshot, the descriptives means show that the older group was always worse than the younger group, but in the plot the two groups cross over. The younger group appears to be plotted too low, while the older group appears to be plotted too high. 

<img width="1440" alt="screen shot 2016-02-26 at 18 07 07" src="https://cloud.githubusercontent.com/assets/17500955/13360995/f828fd78-dcb3-11e5-8983-f1f773d208ac.png">

**Comment by raviselker** [comment]
Can you check whether this still happens in the latest release (0.7.5.5). You can download the new release over here: https://jasp-stats.org/download/

**Comment by ansanborn** [comment]
I redid the plots in the new release and it looked correct. Thanks!

Best,
-Adam

**Comment by raviselker** [comment]
Fixed
