### ISSUE TITLE
Contingency Table: "Log odds ratio" not "Logodds ratio

### ISSUE THREAD

**Issue by Tahiraj** [jasp-stats/jasp-desktop#1208]
@boutinb @FransMeerhoff 
In Bayesian Contingency Table and Contingency Table label should be "Log odds ratio" not "Logodds ratio". See the screen shot
<img width="602" alt="screenshot 2016-02-29 16 38 29" src="https://cloud.githubusercontent.com/assets/9108433/13399735/0b9e8afa-df05-11e5-8fb4-1983a4e72e52.png">
<img width="610" alt="screenshot 2016-02-29 16 38 54" src="https://cloud.githubusercontent.com/assets/9108433/13399736/0ba1a58c-df05-11e5-9044-cb5d99284578.png">

**Comment by boutinb** [comment]
Hi Tahiraj,

We cannot reproduce this problem with the last version of JASP (0.7.5.2). What is the version you use? You can control this with the About dialog box.

Cheers,
Bruno

**Comment by Tahiraj** [comment]
@boutinb I changed the label in dialog box. Done

**Comment by FransMeerhoff** [comment]
Solved with #1239
