### ISSUE TITLE
Classical ANOVA: Add support for random factors

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#121]

**Comment by jonathon-love** [comment]
@raviselker says it's too hard.

**Comment by mmarsman1** [comment]
he should buckle down and do it nonetheless ;-)
On 16 Mar 2015, at 15:54, Jonathon Love <notifications@github.com<mailto:notifications@github.com>> wrote:


@raviselker<https://github.com/raviselker> says it's too hard.
