### ISSUE TITLE
feature request: widen columns repeated-measures table

### ISSUE THREAD

**Issue by lvanderlinden** [jasp-stats/jasp-desktop#1211]
Hello,

(I believe I already saw this feature request before, but I can't find it back...) 

It would be great if their would be the possibility to widen the columns of the repeated-measures table. Now, when the labels of the levels of the first factor are long, we cannot read the labels of the levels of the other factor(s) and it becomes difficult to fill in the cells in the right order.

I'm using version 0.7.5 Beta 2 on Linux, but the same "problem" occurs on Windows and Mac.

![screenshot](https://cloud.githubusercontent.com/assets/2217254/13496774/688aa4fc-e152-11e5-84df-8d89813ae81f.png)

Cheers,

Lotje

**Comment by raviselker** [comment]
@FransMeerhoff @boutinb  I think it is important to fix this for the next major release

**Comment by boutinb** [comment]
We have put a tooltip to read the column names.

**Comment by lvanderlinden** [comment]
Amazing! Thank you so much!
