### ISSUE TITLE
Input option text not fully visible

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1212]
On my Windows 10 laptop, the input option text is sometimes not fully visible. Damian once did a lot of work on this, but the problem appears to have resurfaced. I attach two screenshots. In the first, "Group 1 > Grou" (Bayesian t-test) is all I can read; in the second, "Measure 1 > M" ().

![image](https://cloud.githubusercontent.com/assets/8603015/13503449/b72fbfee-e16f-11e5-98ff-490b04594218.png)

![image](https://cloud.githubusercontent.com/assets/8603015/13503458/c8124b60-e16f-11e5-9010-64c6b2b6894d.png)

**Comment by FransMeerhoff** [comment]
@vankesteren 

You have the same problem.? Can you mention other option panels where this also occurs?

**Comment by akashrajkn** [comment]
#2308 solves hi-DPI issues
