### ISSUE TITLE
Text for one-sided tests has not been fixed yet

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1213]
@AlexanderLyNL fixed the text for the one-sided correlation test underneath the table; the text for the one-sided t-test still awaits improvement. Maybe Alexander can fix this as well...see screenshot. I forgot when I posted a concrete suggestion for how this should be improved, but I had a very specific idea.

![image](https://cloud.githubusercontent.com/assets/8603015/13503529/21ad6f74-e170-11e5-8715-2c7177eb3317.png)

On a related point, there is no such warning about the one-sidedness for the binomial test. See screenshot. @quentingronau is too busy now, but after Tuesday he can add the message perhaps. 

![image](https://cloud.githubusercontent.com/assets/8603015/13503570/5ca04502-e170-11e5-8a4c-779dea93fb24.png)

The text also needs to be fixed for the contingency tables -- @Tahiraj can do this. See screenshot.

![image](https://cloud.githubusercontent.com/assets/8603015/13503627/aee8904e-e170-11e5-8cf5-551a30590bc2.png)

**Comment by quentingronau** [comment]
Could you maybe tell me again what text exactly should appear for the one-sided t-test and the one-sided binomial test?

**Comment by EJWagenmakers** [comment]
@quentingronau @FransMeerhoff 
I see now that the text may have changed?! Maybe it's not in the latest developer's release? See screenshot
![image](https://cloud.githubusercontent.com/assets/8603015/13505396/427bdce6-e179-11e5-894c-762ad82b3564.png)

**Comment by EJWagenmakers** [comment]
@quentingronau Maybe you can look at how it is done for the correlation and come up with a suggestion...let me try to find my earlier report...

**Comment by quentingronau** [comment]
Maybe something like this?

Binomial Test:
""For all tests, the alternative hypothesis specifies that the proportion is greater/less than [test value]."

One-Sample T-Test:
"For all tests, the alternative hypothesis specifies that the mean is greater/less than [test value]."

Independent-Samples T-Test:
"For all tests, the alternative hypothesis specifies that the mean is greater in group [group1/2] than in group [group1/2]."

For the paired samples t-test, this is a little difficult, since when specifying multiple test, the variables that are compared are different, I think. At the moment, I do not have a good solution for this case.

**Comment by AlexanderLyNL** [comment]
I suppose that Quentin is taking care of this now? I don’t mind doing it, but I don’t want our updates to clash. So I’ll let Quentin wrap up this one.

**Comment by quentingronau** [comment]
Yes, I will take care of this.

**Comment by Tahiraj** [comment]
So what is the new suggestion? I'll change the contingency accordingly.

**Comment by EJWagenmakers** [comment]
Maybe I did not cc you...can you coordinate this with Quentin please?

Cheers,
EJ

**Comment by Tahiraj** [comment]
Ok. I'll coordinate with Quentin.

**Comment by quentingronau** [comment]
Tahira, I have forwarded you E.J.'s mail.
Another question: Is it correct that I should also change this for the frequentist t-test/binomial test?

**Comment by EJWagenmakers** [comment]
Yes that would be nice
EJ

**Comment by Tahiraj** [comment]
@EJWagenmakers 
In Bayesian contingency table, If it is fine I'll commit the changes. See attachment.
<img width="1032" alt="screenshot 2016-03-04 15 51 21" src="https://cloud.githubusercontent.com/assets/9108433/13530351/3a347342-e221-11e5-985c-1712405ce597.png">

**Comment by EJWagenmakers** [comment]
Yes, great!
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam
Nieuwe Prinsengracht 130
1018 VZ Amsterdam, The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by Tahiraj** [comment]
Done for Bayesian contingency table.

**Comment by quentingronau** [comment]
I committed the changes for the binomial test and the t-tests as well.
