### ISSUE TITLE
Notes in Contingency Table

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1215]
In the Bayesian contingency table, if I click "add notes" for a table, it creates a note several tables down. In the example shown in the screenshot, I want to add a note below the first table that shows the counts. However, when I select "add note" for that table, the note it creates is two tables down. See screenshot.

![image](https://cloud.githubusercontent.com/assets/8603015/13529759/1031afb8-e21e-11e5-9d14-0d81fcf1cda4.png)

**Comment by EJWagenmakers** [comment]
A follow-up on the above issue. First, I've ended up creating a note below the three tables. See this screenshot:

![image](https://cloud.githubusercontent.com/assets/8603015/13553415/e2f9b2f4-e388-11e5-8cba-88fd06e79cfa.png)

Second, when I upload this file to the OSF, it repeats this note three times, once for every table! This is clearly not optimal. See screenshot. Perhaps when the bug for the contingency table notes is addressed, the OSF issue will also be fixed. 
![image](https://cloud.githubusercontent.com/assets/8603015/13553423/28f65122-e389-11e5-9c61-c868407518a3.png)

**Comment by raviselker** [comment]
Fixed
