### ISSUE TITLE
IImportant issue with file saving

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1217]
So I've created a file, closed JASP, and sent the file to Alex for editing. Alex edits the file and sends it back to me. I open the file with JASP, change a few minor things, and select "save". At that moment, JASP gives me an error message telling me the file is in use (!). That looks like a bug. (I can get around this by selecting "save as" and choosing a different file name, it is is not optimal). Perhaps JASP remembers the file names from a previous session and falsely believes it is still in use. I double checked that I did not have an instance of JASP open somewhere else. This happened on Windows 10.

![image](https://cloud.githubusercontent.com/assets/8603015/13553283/7592dc44-e384-11e5-805b-0df127447322.png)

**Comment by boutinb** [comment]
This error message comes from the operating system self (not JASP). Probably a (hidden) JASP instance was still using this file.
