### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1218]
I'm not sure whether JASP has keyboard shortcuts for "open", "save", and "save as", but:
(1) if they are there, it would be nice to attend the user to them in the file menu
(2) if they are not there, we might want to add them

**Comment by akashrajkn** [comment]
Keyboard shorcuts have already been implemented for open and save.

**Comment by EJWagenmakers** [comment]
Nice. Then we should attend users to the existence of the shortcuts through
the file menu (as in most other programs)
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam
Nieuwe Prinsengracht 130
1018 VZ Amsterdam, The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by AlexanderLyNL** [comment]
Done
