### ISSUE TITLE
CSV importer

### ISSUE THREAD

**Issue by aknight1-uva** [jasp-stats/jasp-desktop#1223]
The CSV importer attempts to treat strings that are blank (i.e. zero length, or a single space) as absent values. However, the search for blank string stops on the first found blank string in any one column.
(File importers/csvimporter.cpp - about line 280)

**Comment by akashrajkn** [comment]
@aknight1-uva , in csvimporter.cpp, line 266, unique_copy function has been used on the (sorted)vector - this removes multiple blank strings from the vector. The modified vector (column) has only one blank string - hence search for blank string stops after the first found blank.

**Comment by FransMeerhoff** [comment]
Is not an issue. Incorrect code interpretation.
