### ISSUE TITLE
SVG format for figures

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1225]
Hi guys,

I'm not sure whether this already came up (I could not find it easily), but it would be really nice to be able to save the figures in svg format. A suggestion from the forum: "It seems that if you copy a figure, you get a bitmap copy, which you cannot easily edit (i.e. you cannot select and delete individual elements from the plot). It would be great if you could export the graph in `.svg` format, which you can edit in free tools like Inkscape. This would probably be really easy to implement (assuming that you're using a `QGraphicsScene` for rendering the graphs)."

Cheers,
E.J.

**Comment by jdittrich** [comment]
That would be very useful and would match the idea, that the results can be easily copied e.g. to Word for contiuing to use these.

**Comment by raviselker** [comment]
Duplicate of #1198
