### ISSUE TITLE
OSF error message after logging out

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1228]
So I've logged into the OSF, and then logged out. Later I suddenly get an error message when I try to open a csv file on my computer:

![image](https://cloud.githubusercontent.com/assets/8603015/13670318/0701cfc0-e6c1-11e5-806e-cba0fbf6ae6a.png)

**Comment by FransMeerhoff** [comment]
Solved by: Fixes #1128 OSF error message after logging out
