### ISSUE TITLE
failing independent frequentist ttest on Ubuntu Trusty (14.04 LTS)

### ISSUE THREAD

**Issue by benutzer1234** [jasp-stats/jasp-desktop#1231]
I downloaded the linux version for Ubuntu Trusty (14.04 LTS) and tried an independent frequentist t-test on the kitchen roll dataset. I set mean_NEO as dependent and Rotation as grouping variable. Instead of a t-value the table displayed a NaN (see the attached screenshot).

![ttest_bug](https://cloud.githubusercontent.com/assets/13048329/13682917/e61e1d32-e6fb-11e5-8fb1-12a639c49356.jpg)

**Comment by akashrajkn** [comment]
@benutzer1234 Which version of JASP are you using?

**Comment by benutzer1234** [comment]
@akashrajkn: It statets version  0.7.1.12

**Comment by akashrajkn** [comment]
@benutzer1234 the new stable version of JASP will be out soon - But you can download the 0.7.5.2 beta version which does not have this issue.
