### ISSUE TITLE
OSF Login screen still looking suboptimal

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1234]
JASP developers' version: Maybe it's because I have a touch-screen on my laptop? They sometimes mess up the format. See screenshot.
![image](https://cloud.githubusercontent.com/assets/8603015/13702401/4a9a1e52-e786-11e5-861d-35dca610532e.png)

**Comment by boutinb** [comment]
@EJWagenmakers: Is this solved?

**Comment by EJWagenmakers** [comment]
Nope, see attach. Could just be my laptop; some other text in the input panel is also "cut off".
E.J.
![osflogin](https://cloud.githubusercontent.com/assets/8603015/23948245/7bb18d94-0982-11e7-8315-3a266a71fb40.png)

**Comment by FransMeerhoff** [comment]
Oldie,
Solved with #2308
