### ISSUE TITLE
Sorting variables in analysis views

### ISSUE THREAD

**Issue by MattiHeino** [jasp-stats/jasp-desktop#1238]
Hi,

I don't know if it's the best possible solution, but in SPSS you can right click the variable list when choosing what to drag-and-drop to the analysis boxes, and then sort the variables in the variable list. This helps a lot when one is working with 1000+ variable sets (especially, when those variables are in a more or less arbitrary order)!

In fact, an even better option would be to include a search functionality, where one could type in a part of a variable name and filter the list by that. Hope to see you consider this at some point.

All the best and keep up the amazing work,

Matti

**Comment by boutinb** [comment]
Hi Matti,
We are just busy to add a feature so that variable list can be reordered and editable. Coming soon...
Cheers,
Bruno

**Comment by boutinb** [comment]
This feature is added in 0.8.1
