### ISSUE TITLE
Results are not updated consequently when changing options in the Bayesian Correlation Pairs analyses

### ISSUE THREAD

**Issue by FransMeerhoff** [jasp-stats/jasp-desktop#1247]
If you load the LonelyBathingStudy6 example and set all the plot settings on in the Bayesian Correlation Pairs analyses you wil find that when switching the Hypothesis from correlated to corelated positively or negatively the results screen is sometimes not updated.
[LonelyBathingStudy6.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/176286/LonelyBathingStudy6.jasp.zip)

**Comment by FransMeerhoff** [comment]
This issue is found on a Mac with version 0.7.5.5

**Comment by boutinb** [comment]
Duplicate with #1292
