### ISSUE TITLE
Ubuntu ppa no longer seems to work

### ISSUE THREAD

**Issue by froukehe** [jasp-stats/jasp-desktop#1252]
Up to the adding the ppa and update all works well.
However then I get:

frouke@frouke-Latitude-D620:~$ sudo apt-get install jasp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package jasp

This is on two PCs now. Previously the ppa worked.

Can you make a package available for download?

Another problem I had with the Linux version is that (previously installed) after clicking on an option to create plots, the program crashes.

**Comment by FransMeerhoff** [comment]
Hello Froukehe,

Two questions:
To be sure: which ppa are you talking about? We recently switched to the ppa described below.
Are you using this one?

For Ubuntu (new installation): 
	sudo add-apt-repository ppa:jasp-uva/jasp
	sudo apt-get update
	sudo apt-get install jasp

Next question is:
Which version of Ubuntu are you using?

For the problem about creating the plots, let's wait till the new version of JASP 0.7.5.5 is running.

Kind regards 
Frans Meerhoff

**Comment by luketudge** [comment]
@froukehe Hi Frouke. Looking at the ppa webpage at https://launchpad.net/~jasp-uva/+archive/ubuntu/jasp I would guess that your problem occurs because there is only a version listed for Ubuntu 15 (Wily), whereas you probably use Ubuntu 14.04 (the current long-term support version of Ubuntu).

@FransMeerhoff is this intentional, or is the aim also to provide an up-to-date JASP version for the current Ubuntu LTS? I learned about JASP at the TeaP conference today, and I would be interested in trying it out with some of my students, for which it would be most useful to have the latest version on Ubuntu LTS.

P.S. JASP 7.1.33 for Ubuntu 14.04 is still available and successfully installs from ppa:jonathon-love/jasp

**Comment by littlesis92** [comment]
@luketudge Hey fellow TeaP-visitor :) I also learned about jasp there and now wanted to try it out myself, but I encounter the same problem as @froukehe described (with Trusty). I didn't know if the Jonathan-love PPA was to be trusted, but if you say so, I'll try that until the most recent version can be downloaded again.

**Comment by fdabl** [comment]
same issue here -- JASP does not support the long-term support version of Ubuntu (14.04). any updates?

**Comment by singmann** [comment]
I had the same problem on Linux Mint 17.2 which is based on Ubuntu 14.04. I needed to go via Jonathan Love's repository to install Jasp. However, this repository is not kept up-to-date. In any case, here the necessary steps:

```
sudo add-apt-repository ppa:jonathon-love/jasp
sudo apt-get update
sudo apt-get install jasp
```

**Comment by fdabl** [comment]
yes, however, my problem is that I want the new version :)

**Comment by singmann** [comment]
@fdabl What about you figure out the exact necessary steps to [build from source](https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-building-guide.md) and let us know here? That would be a good job to the community and a nice contribution to Jasp.

**Comment by fdabl** [comment]
you. are, of course, totally right. just hoped that somebody else (eg. jonathon) has done that already somewhere. i will have a look sometime next week

**Comment by singmann** [comment]
Jonathan has unfortunately left the active Jasp development. You can now only find him under [former Team members](https://jasp-stats.org/the-team/). So that might be the reason that Ubuntu is not that strongly supported anymore.

**Comment by boutinb** [comment]
Hi @fdabl, @froukehe and @singmann 
We support at the moment only Ubuntu Willy version for JASP 0.7.5.5
When we took over the development, Trusty version was not supported for the last version of JASP. We made the decision to limit the number of supported version for the time being, thinking that we could wait for the new LTS version when it will be released (Xenial Xerus planned on 21st of April).
We may consider updating our PPA (ppa:jasp-uva/jasp) to support Trusty if many users request it.
Have you tried to build JASP yourself with the source code? The debian folder is in the github repository: https://github.com/jasp-stats/jasp-desktop/tree/development/Tools/debian.

**Comment by muranyia** [comment]
Please update the PPA to support Trusty. Thank you.

**Comment by stephensrmmartin** [comment]
You can look at the arch aur jasp packages for guidance on the build
process. I don't know much about Debian packaging or else I'd do it for the
team.

**Comment by lindeloev** [comment]
Ubuntu 16.04 is out. Support for that in the ppa would be much appreciated! Thanks. It does work to install the 15.10 version of JASP on Ubuntu 16.04. Simply add the ppa, then go to **Software & Updates** --> **Other Software** --> Select the **ppa.launchpad.net/jasp-uva/ubuntu xenial main** line --> Click **Edit...** --> Change "xenial" to "wily". Then OK, Done, etc. and install JASP with the usual:

`sudo apt-get update`
`sudo apt-get install jasp`

**Comment by jdittrich** [comment]
Would also love to have a PPA for the current LTS.

**Comment by boutinb** [comment]
We have just updated our PPA to support Ubuntu Xenial. It is not fully tested yet, but it seems to work so far.
Can you try this:
New installation: 
sudo add-apt-repository ppa:jasp-uva/jasp
sudo apt-get update
sudo apt-get install jasp

For upgrade:
sudo apt-get update
sudo apt-get upgrade gasp

**Comment by lindeloev** [comment]
Yes, the Xenial PPA works here. Thank you!

**Comment by TorstenMH** [comment]
Hi,
I know that this has been asked in other places, but instead of supporting ever changing new Ubuntu Versions, wouldn't it make sense to focus on supporting Debian. This would most likely resolve all the issues and all Ubuntu, Mint, whatever, versions would work as well. This would cover probably 90% of the "privat/scientific" Linux users.
Torsten
