### ISSUE TITLE
Upon installation and automatic launch, data files can't be browsed

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-desktop#1253]
With JASP 7.5.5 and Windows 7, I've found that when JASP is launched automatically upon being installed, File > Open > Computer > Browse > Desktop, does not locate any existing files (csv, jasp, or others). Only folders appear on the list. This is remedied by closing and then re-launching JASP.

**Comment by boutinb** [comment]
Dear R180,
We have just tested on Windows 7, with a new installation of JASP 7.5.5. We could see a cvs or jasp file, but they have no icon. Is this what you mean?

Cheers,
Bruno

**Comment by R180** [comment]
On a newer machine, I see what you see. But on an older one, no files with a csv or jasp extension were shown within JASP's file viewer until I closed JASP and then re-opened it.

**Comment by boutinb** [comment]
Not reproduceable
