### ISSUE TITLE
Bayesian contingency table: posterior log odds does not respond to prior concentration

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1254]
@Tahiraj 
As pointed out by Alexander Etz (and I confirmed this), changing the "prior concentration" does affect the BF (as it should) but fails to affect the posterior log odds and credible intervals (both in the descriptive table and the plot). This looks like a bug to me!?

![image](https://cloud.githubusercontent.com/assets/8603015/13921359/c19d2500-ef77-11e5-80a3-20dec0bf9623.png)

Cheers,
E.J.

**Comment by FransMeerhoff** [comment]
Solved by #1255
