### ISSUE TITLE
Dummy Coding for Linear Regression Analysis

### ISSUE THREAD

**Issue by neurotroph** [jasp-stats/jasp-desktop#1260]
From what I have seen, Linear Regression Analysis in JASP only supports metric covariates/predictors. Automatic dummy coding for categorial variables would be a great feature. A further option to select different types of coding (dummy, effect, ...).

R does this, from what I know, automatically when using factors() in a data.frame.

Any plans on adding this in the future?

**Comment by philippberens** [comment]
I agree - that would be nice. In particular, since this already seems to be implemented for the log-linear model.

**Comment by lindeloev** [comment]
This is a duplicate of https://github.com/jasp-stats/jasp-desktop/issues/902. I also want to cast my vote for this in both Bayesian and Linear regression.

**Comment by AlexanderLyNL** [comment]
Use ANCOVA for this purpose instead.

**Comment by carlosquintanillaa** [comment]
I cast my vote for this improvement. The minute you can create dummy variables inside JASP I'll adopt JASP for my Stat Course. Most real datasets are a combination of continuous and categorical variables. We need them for both Linear Regression and Logistic Regression. Currently I use Gretl in my courses.
