### ISSUE TITLE
SPSS importer: error when loading file with missing values

### ISSUE THREAD

**Issue by raviselker** [jasp-stats/jasp-desktop#1263]
When opening an sav file with missing values ([multipleregression.sav.zip](https://github.com/jasp-stats/jasp-desktop/files/187696/multipleregression.sav.zip), unzip before use), I get the following error message:

<img width="1181" alt="screen shot 2016-03-24 at 12 16 43" src="https://cloud.githubusercontent.com/assets/4669197/14015635/bf980f96-f1ba-11e5-9580-ac362739ee40.png">

**Comment by aknight1-uva** [comment]
It looks like this file was created with a (old / non Intel processor) Mac - In which case this is "as designed", in that older Macs used "bigendin" notation, whilst Intel machines use "littleendin" nation. JL suggested to me (whey back when) that we were not going to support anything apart from Intel format SAV files.
This is fixable - but it will take much work. Do we want to do this?

**Comment by raviselker** [comment]
Maybe not right now then. Is it easy to catch this error and give a more informative error message instead?
