### ISSUE TITLE
qt 5.6 doesn't work on Mac

### ISSUE THREAD

**Issue by randy3k** [jasp-stats/jasp-desktop#1267]
It is [stated](https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-building-guide.md#mac-os-x) that

> Qt: building JASP on OS X is pretty robust, and most versions work. We currently use 5.4.0, but newer versions will probably work too.

I have spent the last two-three hours trying to use qt 5.6 to build jasp...

It turns out that qt 5.6 uses `libc++` in default and crashes with the `boost` binary and `R.framework` which were built with `libstdc++`. Moreover, qt5.6 doesn't ship with webkit anymore...

Finally, I downgraded to qt 5.5 and it works like a charm...

**Comment by boutinb** [comment]
Dear randy3k,
JASP on Mac runs indeed on Qt 5.5. Support for Qt 5.6 is for later.
Why do you want to compile JASP, and not use the setup? Are you planning to add some features? In this case, you are really welcome!

Cheers,
Bruni

**Comment by randy3k** [comment]
I found that this open-source project very promising and interesting. There are quite some missing "classical tests" and I am definitely interested in contributing to the project. Ultimately, I want to use JASP to teach my statistical classes.

But I know nothing about qt, it will take me some time..

**Comment by boutinb** [comment]
It is the goal indeed that people around the world can contribute to JASP! It takes some time to get used with the C++ code.  But if you know R, you can propose a R analysis by following the JASP Development guides in the github front page.
Which classical tests do you mis?  Maybe we are planning already to implement them. In this case you could help us with tour ideas.

Cheers,
Bruno

**Comment by akashrajkn** [comment]
We use Qt 5.10 now.
