### ISSUE TITLE
JASP hangs after one analysis on OS X 10.11.4

### ISSUE THREAD

**Issue by pgiemsa** [jasp-stats/jasp-desktop#1270]
doing an analysis on JASP works fine (e.g. ANOVA, ANCOVA, t-test), but after switching back to the data window, JASP hangs and doesn't recover. Nothing I can do. Happens every single time for me after the first analysis.

**Comment by boutinb** [comment]
Dear pgiesma,
Which version of JASP do you use, and on which platform (Windows/Mac or Linux, and which version)?
Can you send us the JASP file you use?

Thanks,
Bruno

**Comment by pgiemsa** [comment]
hi,

i am using mac 10.11.3. and jasp 0.7.5.5.

i have attached the the csv file i am using.

Patrick

**Comment by FransMeerhoff** [comment]
Sorry Patrick,

It is impossible to use the github reply mail adres to attach files.
Can you please send us the data again by:
- Go to the issue in github and attach the cvs file at the bottom of the issue with:
  'Attach files by dragging & dropping or  selecting them.'
- Or send it directly to the following mail adres:  F.A.M.Meerhoff@uva.nl

Kind regards
Frans Meerhoff

**Comment by pgiemsa** [comment]
hope you have gotten the file. i have sent it to the specified email address.

**Comment by FransMeerhoff** [comment]
Hello Patrick,

Thank you, we received the data fie.
We are able to reproduce the problem.
We will keep you informed about the continuation.

Regards
Frans Meerhoff
[070116 Datensatz gefiltert mit und ohne MRT FINAL SAMPLE.txt](https://github.com/jasp-stats/jasp-desktop/files/205902/070116.Datensatz.gefiltert.mit.und.ohne.MRT.FINAL.SAMPLE.txt)

**Comment by AMeta09** [comment]
Hi

I'm trying to download the latest version of JASP from the given link (https://jasp-stats.org/download/) but everytime i click on the link for windows XP and above, I get an error message. I think the link is possibly broken. I got the same message when I tried to post this problem in the Forum.

Could you please look into it? It will be really helpful.

Thank you.
Aakanksha

**Comment by boutinb** [comment]
@AMeta09 If I click on the (http://static.jasp-stats.org/JASP-0.8.0.0-Setup.exe) it downloads the file. Maybe there is a security setting that forbid to download exe files?
