### ISSUE TITLE
copy-paste variables into JASP ?

### ISSUE THREAD

**Issue by nbara** [jasp-stats/jasp-desktop#1271]
It would be great if one could paste data from Excel/Matlab/Spyder(/etc.) directly into JASP.

At the moment the only solution is to first save your data as .csv files, then import them into JASP. However, I usually perform my analyses in other software (typically Matlab), and copy/paste relevant variables in SPSS:

![screen shot 2016-04-04 at 11 49 39](https://cloud.githubusercontent.com/assets/10333715/14244428/55bfebee-fa5b-11e5-9983-fa6a9e634c9e.png)

This is not yet possible in JASP, but it would be great feature to speed up the process :)

**Comment by boutinb** [comment]
@nbara 
We have already planned an SPSS file import for the next release.
We haven't planned yet to copy/paste data. It would be indeed a nice feature. This is a enhancement request.
Cheers,
Bruno.

**Comment by mdekker760** [comment]
I second the copy/paste feature. I'm regularly switching between excel and spss and depend on copy/paste for my work flow.

**Comment by boutinb** [comment]
With the newest version (0.8.1), you can now edit your data in Excel/SPSS/... and JASP will synchronize automatically these changes into your analyses.

**Comment by nbara** [comment]
Fantastic ! Great job, devs !
