### ISSUE TITLE
Nothing compiles in JASP

### ISSUE THREAD

**Issue by mlanier** [jasp-stats/jasp-desktop#1278]
On the .7.5.5 when I hit enter nothing compiles in the side panel. I have tried nearly every feature and I get nothing.

**Comment by akashrajkn** [comment]
Hi @mlanier , on which system are you getting this issue? [OS & version you are using]

**Comment by mlanier** [comment]
Windows 7 professional, the latest download. 7.5

**Comment by boutinb** [comment]
This issue is closed due to long inactivity. If this problem still occurs, please reopen it.
