### ISSUE TITLE
JASP failure on Windows 10

### ISSUE THREAD

**Issue by FransMeerhoff** [jasp-stats/jasp-desktop#1281]
JASP version 0.7.5.5 does not run on Windows 10 laptop.
Data is loaded but no analyses can be done.

**Comment by FransMeerhoff** [comment]
Beste Rob,

Zoals Eric-Jan al meldde kunnen wij het probleem hier nog niet reproduceren.
Zou je ons daarbij kunnen helpen met het beantwoorden van de volgende vragen:

- Foutmelding:
Krijg je nog wel een foutmelding op het scherm, en zo ja welke.
Kan ook bijv. iets zijn: ‘JASP has experienced an unexpected internal error’ maar dan willen we dat ook graag weten

-Data
Zou je de gebruikte data file naar ons op kunnen sturen.
Je kunt de data gewoon attached terugsturen naar dit mail adres 

-R
Heb je zelf ook een versie van R geïnstalleerd en zo ja welke.

-Machine gegevens.
Op windows 10 kin je via de Start knop->Settings->System->About alle machine gegevens vinden.
Zou je ons deze kunnen opsturen. 

Op onze github pagina is een issue aangemaakt waarin je de vorderingen kunt volgen, en commentaar toevoegen

https://github.com/jasp-stats/jasp-desktop/issues/1281

Vriendelijke groet,
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Beste Frans,
Voor nu alvast de dataset (via Excel voor JASP in csv bestand omgezet) m.b.t. ANOVA en het volgende:
- er zijn geen foutmeldingen
- Rx64 3.2.2 is geïnstalleerd
Volgens het personeel van de computerwinkel waar ik de laptop gekocht heb, gaat het om blokkades, zowel van AVG Free als van de firewall van Windows10 , vanavond weet ik meer, ik hou je op de hoogte.
De settings-system-about informatie heb ik niet kunnen vinden.
Vriendelijke groet en dank voor je reactie,
Rob Flohr
[FruitFlies.txt](https://github.com/jasp-stats/jasp-desktop/files/216520/FruitFlies.txt)

**Comment by FransMeerhoff** [comment]
Beste Frans,
Het probleem is nog niet opgelost, morgen gaan iemand van de computerwinkel er mee verder aan de slag. Via Configuratiescherm->systeem heb ik nog de volgende machinegegevens gevonden:
Windows 10 Home
@2015 Microsoft computer
Asus Tek Computer Inc
model: X556UB
Processor: Inter(R)Core (TM) i5-6200U CPU @ 2.30 GHz  2.40 GHz
Geïnstalleerd geheugen: 8.00 GB
Type systeem: 64 bits besturingssysteem, x64-processor
Product-id: 00325-95891-55062-AAOEM

Zijn dit de gegevens die je bedoelde of ontbreekt er nog iets?

Vriendelijke groet,
Rob Flohr

**Comment by FransMeerhoff** [comment]
Beste Rob,

Dank voor de info en data.
We hebben helaas het probleem met de opgestuurde data en de door jou geïnstalleerde versie van R nog niet kunnen reproduceren.

Ik onderzoek hier ondertussen verder of de genoemde virusscanner of FileWall een rol kunnen spelen.

Zou je nog het volgende kunnen proberen:
Op de download pagina is tegenwoordig een gezipte geïnstalleerde versie van JASP op Windows aanwezig.
Zie hiervoor :  https://jasp-stats.org/download/  bij Advanced downloads.
Als je deze zip file (64-bit versie)  JASP 0.7.5.5 64-bit installation download en uitpakt dan kun je JASP gewoon opstarten vanuit die folder waar de zip file is uitgepakt.
Dit staat dus helemaal los van een eerder geïnstalleerde versie (en deze uitgepakte folder kan daarna gewoon opgeruimd worden).
- In de uitgepakte folder hoef je slechts JASP.exe te dubbelklikken en dan kunnen we kijken of dat een verschil maakt en of de installatie van JASP zelf een rol speelt.
- Ook kun je JASP dan makkelijk met behulp van de rechtermuis runnen als Administrator en controleren of dat een rol speelt (en van invloed is op virusscanner).

Als je dat zou kunnen proberen zou dat mooi zijn.

Met vriendelijke groet,
Frans Meerhoff

PS Machine gegevens waren de gegevens die we wilden zie.

**Comment by mlanier** [comment]
I cannot read german at all, but I am getting a similar response on Windows 7 professional.

**Comment by FransMeerhoff** [comment]
Beste Frans,
Het systeem is opnieuw geïnstalleerd en verder is de nvidea videokaart uitgeschakeld. Degene die zich hiermee heeft beziggehouden (Ron de Jonge) denkt dat het probleem te maken had met de videokaarten, er zitten namelijk twee videokaarten in mijn laptop, een Intel videokaart en de genoemde nvidea videokaart. Hij vermoedt dat JASP voor het uitvoeren van de analyses contact zocht met de nvidea videokaart en dat dat niet lukte.  JASP werkt nu zonder problemen.
Voor het geval je meer en/of meer gedetailleerde informatie wenst, kun je contact opnemen met Ron de Jonge van Compèl Computers in Winsum (Groningen) (ron@compel.nl).
Hartelijk dank voor je medewerking.
Fijn weekend toegewenst.
Met vriendelijke groet,
Rob Flohr
