### ISSUE TITLE
SPSS importer issues

### ISSUE THREAD

**Issue by akashrajkn** [jasp-stats/jasp-desktop#1285]
1) error - unable to open "Bias value unexpected, cannot read floating point numbers!"
files: multipleregression.sav, pearson_scorrelation.sav

2) error - **date format wrong**
expected - "09/04/2013 13:36:26";  obtained - "1.35977e+10"
file: GORN_music_pilot_anonymized.sav

3) error - **special characters not recognized**
expected - "“yessing”";  obtained - "�yessing�"
file: earning prospects meta-analysis men only.sav

4) error - some of the floating values are shown as integers
expected - "3.5"; obtained - "3" [row:  "179"; column:  "68"]
file: Exp1_Data.sav
other files: dotprobeall.sav, DataUsedforStereotypeAwarenessExclusion.12.4.2013.sav

5) error - certain character strings are not read properly (consecutive double inverted commas not shown properly)
expected - >>""net""<<; obtained - >>"net"<<
file: data_EpleyAkalisWaytzCacioppo.sav

I have uploaded the files here - https://drive.google.com/open?id=0ByZfAEja_lrMd0luczhEWlJfcUU

@aknight1-uva

**Comment by aknight1-uva** [comment]
Please do not cover more than one found problem in any one issue: It makes the work flow unmanageable.

**Comment by boutinb** [comment]
@aknight1-uva I think all these issues are now solved?

**Comment by aknight1-uva** [comment]
I thinks so too.
