### ISSUE TITLE
.sav import error.

### ISSUE THREAD

**Issue by aknight1-uva** [jasp-stats/jasp-desktop#1286]
unable to open "Bias value unexpected, cannot read floating point numbers!"
files: multipleregression.sav, pearson_scorrelation.sav @ https://drive.google.com/open?id=0ByZfAEja_lrMd0luczhEWlJfcUU

**Comment by aknight1-uva** [comment]
multipleregression.sav import already fixed (in my fork).

**Comment by akashrajkn** [comment]
Okay, I'll redo the tests from your code and let you know...

**Comment by aknight1-uva** [comment]
Hoi Raj,

I’ve split up the issue to five new ones: You don’t need to redo them..

 _____
Patrick Alan Knight
Programmer
T: +31 (0)20 525 5993 | M: +31 (0)6 46 85 58 60

**Comment by aknight1-uva** [comment]
pearson_scorrelation.sav also readable.

**Comment by aknight1-uva** [comment]
Fixed a while ago.
