### ISSUE TITLE
Text for classical one-sided t-test

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1291]
@raviselker 

The classical one-sided t-test gives the following text underneath the table [with comments]:

"For all tests, the alternative hypothesis specifies that group Fixation is less than group Horizontal .[EJ: there's an extra space here]
ᵃ Levenes [EJ: can we add the apostrophe please? It is Levene's, right? Or else it it Levenes' -- please check] test is significant (p [EJ: the < sign does not show] .05), suggesting a violation of the equal variance assumption" [EJ: can we end this sentence with a period?]

![image](https://cloud.githubusercontent.com/assets/8603015/14558811/c6e10ad6-0304-11e6-8964-04f834b6e344.png)

E.J.

**Comment by EJWagenmakers** [comment]
Hey this is weird; if I do not use the OSF previewer but open a file directly in JASP then the text *does* look good. See screenshot!

![image](https://cloud.githubusercontent.com/assets/8603015/14559067/8d67d2ce-0306-11e6-9185-6dc4609119be.png)

**Comment by akashrajkn** [comment]
@EJWagenmakers can you share the jasp file here?

**Comment by EJWagenmakers** [comment]
https://osf.io/6qyxe/

See text under the table for the classical t-test (you have to scroll down
a little, the first analysis is Bayesian)

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam, Nieuwe Prinsengracht 129B
Letter: PO Box 15906, 1001 NK Amsterdam
Parcel: Valckenierstraat 59,  1018 XE Amsterdam

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by boutinb** [comment]
I cannot reproduce this problem on OSF.
