### ISSUE TITLE
T-test and state system bug

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1292]
Consider the Bayesian t-test for the kitchen roll data. Suppose you tick all options. Some analyses are pretty slow (robustness check, sequential plot). Suppose you test an order-restricted hypothesis; JASP is calculating the plots, and as it is busy calculating, you change the hypothesis (you tick a different order-restriction). The result: JASP is confused and does not produce any plots at all (what it should be is recompute the plots based on the latest hypothesis specified). See screenshot.

![image](https://cloud.githubusercontent.com/assets/8603015/14562349/5d95c3d8-031c-11e6-8240-7f66a73784af.png)

**Comment by FransMeerhoff** [comment]
See also #1247. Probably same issue.

**Comment by boutinb** [comment]
Duplicate with #1247
