### ISSUE TITLE
variables lost in variable window, despite being on JASP data sheet?

### ISSUE THREAD

**Issue by metamorphose42** [jasp-stats/jasp-desktop#1293]
After importing data from a cvs file into JASP, with all variables perfectly to be found in the data sheet, when I go to analyse my data, not all variables appear in the variable window. It's usually the last one from the data sheet that just isn't there...? Anyone any clue why this happens?

Thanks!

Best,
Clarisse

**Comment by boutinb** [comment]
@metamorphose42 Sorry for the late answer... Does this problem still occur in the last version of JASP (0.8.1)? If yes, can you send us the csv file?
