### ISSUE TITLE
Bayesian Repeated Measures ANOVA on Macbook 

### ISSUE THREAD

**Issue by krismartens** [jasp-stats/jasp-desktop#1294]
Yesterday in a introductory course of EJWagenmakers I experienced this: 
In Bayesian Repeated Measures Anova: after adding the factors, output was given.
But after that, changing the Bayes Factor, of checking Effects, or checking factors as Nuisance, didn't give another output. Nothing happened. 

With a Macbook OS X El Capitan 10.11.3. But a colleague with Yosemite experienced the same on her Macbook.  

![probleem met niet kunnen veranderen met macbook](https://cloud.githubusercontent.com/assets/18496102/14579718/91a76f30-03b4-11e6-8809-33b08be16662.png)

**Comment by boutinb** [comment]
Sorry for the late answer... Can you reproduce this problem with the newest version of JASP (0.8.1), and if yes, can you precise exactly which columns you use?

**Comment by boutinb** [comment]
If this problem comes up again with the newest version of JASP, reopen this issue.
