### ISSUE TITLE
post hoc for interaction

### ISSUE THREAD

**Issue by jquadril** [jasp-stats/jasp-desktop#1298]
Any chance you can add post-hoc capabilities for interaction effects on ANOVA

**Comment by raviselker** [comment]
Duplicate of #423. We definitely want to implement this, but the implementation unfortunately is not as straightforward as it appears.

**Comment by R180** [comment]
Did this ever get addressed in JASP? It does seem to exist in R, and in some other open-access R-based stats programs.
