### ISSUE TITLE
Linear regression t-values

### ISSUE THREAD

**Issue by ProfCLC** [jasp-stats/jasp-desktop#1299]
v. 0.7.5.5: The t-values in the coefficients table in the linear regression procedure are missing. A comparison table output of this version and 0.7.1.12 is attached.

![0 7 1 12_coeff_output](https://cloud.githubusercontent.com/assets/8106710/14754758/43ebe5e0-0892-11e6-8923-f7c5a62ce9e5.PNG)
![0 7 5 5_coeff_output](https://cloud.githubusercontent.com/assets/8106710/14754759/43ec7f3c-0892-11e6-8fa9-b3a3225899df.PNG)

**Comment by raviselker** [comment]
Yes, we are aware of this issue. We already fixed it and it will be included in a bug-fix release which will probably be online this week.

**Comment by raviselker** [comment]
The bug-fix release is now online: https://jasp-stats.org/download/
