### ISSUE TITLE
Cannot make contingency tables with Mac OS X

### ISSUE THREAD

**Issue by paulinedefromagier** [jasp-stats/jasp-desktop#1303]
Hello, I've tried to create a simple 2x2 contingency table but it will not process. The message I get is: This analysis terminated unexpectedly. Please contact its author.\n\nError : map::at\n

I am currently using version 0.7.5.6 on my Mac OS X

Any help would be greatly appreciated!

**Comment by FransMeerhoff** [comment]
Hello  @paulinedefromagier 

I've added an example of a 2x2 contingency table that works for me on the same version and OS that you are using. Can you check the difference in data between you're and this version. 
If this won't help you please sound us the data that you are using.
You can do that in this issue, by saving the data as a .txt file or send the data attached to F.A.M.Meerhoff@uva.nl.

Kind regards 
Frans Meerhoff
[CT2x2.txt](https://github.com/jasp-stats/jasp-desktop/files/244788/CT2x2.txt)

**Comment by JMiranda7878** [comment]
I'm having a similar problem. I'm able to create tables using the example data, but the dataset i'm using is larger (~1MB). Could that be the problem?

**Comment by FransMeerhoff** [comment]
Hi @Tahiraj 
Can you have a look at this issue?

@paulinedefromagier 
Do you still have this problem with a simple 2x2 contingency table?

**Comment by Tahiraj** [comment]
@JMiranda7878 could you please send the data ?

**Comment by JMiranda7878** [comment]
Thanks! The data is attached.

**Comment by JMiranda7878** [comment]
@Tahiraj  Thank you! I've attached the data. 

[cb6_june17.sav.zip](https://github.com/jasp-stats/jasp-desktop/files/336754/cb6_june17.sav.zip)

**Comment by Tahiraj** [comment]
@JMiranda7878 for which variable you want to make contingency table.You have too many variables,  Specify row, column and layers variables.

**Comment by JMiranda7878** [comment]
I've tried to make several tables, but failed anytime I add any 2 variables getting the same message. 

I tried to use impact and age initially (column, row) and immediately got the error when the second variable was selected. The same happens with any 2 variables. 

I also forgot to mention that I'm using version 0.7.5.6 on Mac OSX 10.11.3

Thanks again.

**Comment by Tahiraj** [comment]
@JMiranda7878 what you can do save the SPSS file as csv file and then you can make the table in JASP. JASP does not support the spss data file in released version. Might be in the next release this functionality would be available, our team is working on it. I am attaching the csv file.
[cb6_june17.csv.zip](https://github.com/jasp-stats/jasp-desktop/files/343719/cb6_june17.csv.zip)

**Comment by boutinb** [comment]
@JMiranda7878 Do you have still this problem?

**Comment by boutinb** [comment]
If this problem comes up again with the newest version of JASP, reopen this issue.
