### ISSUE TITLE
NHST t-test: Cohen's d wrong

### ISSUE THREAD

**Issue by cnhstreet** [jasp-stats/jasp-desktop#1308]
[FakeData.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/255744/FakeData.jasp.zip)

Attached is a .jasp file. Run an independent samples (NHST) t-test with accuracy as the DV and conscious/unconscious as the IV. If you ask for an effect size, it reports it at around _d_ = 0.8 (a fairly substantial effect). But the group means are 0.54 (SD = 0.10) and 0.56 (SD = 0.15) (on a scale of 0 to 1). The reported p-value is 0.658. Unless I'm misinterpreting something (always a possibility!), I think this is an error. Note that the distribution for one of the levels of the manipulation is skewed

**Comment by raviselker** [comment]
Which version of JASP are you using? I just ran the analysis in the latest version of JASP (0.7.5.6) and here it gives a cohen's d of around 0.1. There was a bug in a previous release that lead to a wrong effect size (I think it was the beta version of 0.7.5, see issue #1106). If you download the latest version of JASP (https://jasp-stats.org/download/) this bug should be fixed.

**Comment by cnhstreet** [comment]
Ah yes you are correct - I was using the beta version of 0.7.5. Sorry about that! I've now updated to the most recent version
C
