### ISSUE TITLE
Adding between-subject factor to RM ANCOVA

### ISSUE THREAD

**Issue by susanneschweizer** [jasp-stats/jasp-desktop#1320]
I have a mixed within-between repeated measures ANCOVA design for which I am trying to do Baysian analyses.  I can add the repeated measures IDs as well as the covariate but when I add the between-subject factor the programme crashes with the following warning:
"This analysis terminated unexpectedly. Please contact its author."

I was wondering if there was a way I could work around this.
Thank you

**Comment by raviselker** [comment]
Could you save what you did in a .jasp file and send it to me? You can either attach a zipped version of the JASP file to the issue on github, or you can email it to me directly to selker dot ravi at gmail dot com.

**Comment by raviselker** [comment]
@bruno this is not an issue with the analysis, but with a function in ```rbridge.cpp```. I did some debugging and found that when you call ```.readDatasetToEndNative``` on the data set the following bug appears:
<img width="483" alt="screen shot 2016-05-17 at 16 09 14" src="https://cloud.githubusercontent.com/assets/4669197/15325147/ba1aa592-1c49-11e6-9264-1afea09be0fe.png">

Can you have a look?

**Comment by matthewdye** [comment]
Exact same error on both Windows PC and Mac book. Following thread ...

**Comment by yatinmahajan** [comment]
Any update on this bug. I also encountered the same problem. Seems like happening only when between subject factors are added.

**Comment by susanneschweizer** [comment]
No, I am still waiting to hear (and very keen!) about a solution

**Comment by cameissner** [comment]
Same issue, Mac OS X El Capitan

**Comment by cameissner** [comment]
Any chance this might be evaluated and corrected soon?

**Comment by raviselker** [comment]
We are working on solving this issue. For now we found a possible workaround: if you change the variable type of the between-subjects factor from nominal (three circles) to scale (ruler) in the data editor and then drag the variable of type scale to the between-subjects factor box, the analysis seems to work again.

**Comment by cameissner** [comment]
Thanks so much for the update and work-around.  Love what you are doing
with JASP!

**Comment by raviselker** [comment]
So we think it has something to do with how the original .csv file is encoded. If you load it into JASP and than export it as .csv the problem does not occur anymore. In order to reproduce this problem we need the original .csv file of someone who encountered this problem. Could someone send me this to the following email: selker [dot] ravi [at] gmail [dot] com?

**Comment by boutinb** [comment]
@cameissner  I am still interested to understand why the raw data generated this problem? Can you send it in the ZIP file? Or is this problem actually solved with the newest release (0.8.1)?

**Comment by boutinb** [comment]
If this problem comes up again with the newest version of JASP, reopen this issue.
