### ISSUE TITLE
File does not save via the save menu option

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1323]
I created a csv file, analyzed it in JASP, and then attempted to select "save" from the file menu using the mouse. However, this was not possible. "Save as" was active automatically, and selecting "save" with the mouse did not work (I have Ravi as a witness). Then Ravi executed the "save" command using the shortcut keys (which will not be known to many users, because they are not indicated) and that _did_ work.
Cheers,
E.J.

**Comment by EJWagenmakers** [comment]
Maybe JASP expects the very first "save" to be a "save as", because that option actually does work and is preselected (although this is not intuitively clear). However, it is weird that the keyboard shortcut for "save" does work.

**Comment by boutinb** [comment]
This is solved in the newest version (0.8,1)
