### ISSUE TITLE
Debian PPA: Releasefile missing

### ISSUE THREAD

**Issue by jdittrich** [jasp-stats/jasp-desktop#1329]
When using the officially [recommended PPA](https://jasp-stats.org/user-guide/) (ppa:jasp-uva/jasp), I can’t install JASP, and get the following warning (on Ubuntu 16.04): 

> E: The repository 'http://ppa.launchpad.net/jasp-uva/jasp/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by akashrajkn** [comment]
@boutinb @FransMeerhoff 

@jdittrich , jasp-uva PPA currently supports only the wily(Ubuntu 15.10) version. We will soon update the PPA with the xenial(Ubuntu 16.04) version.

** work around **
_[This is only temporary method- you will need to reset when the ppa is updated with a xenial version]_

If you want to use JASP in Xenial, you can force-install ppa to use the wily version on your machine(I tested this on Kubuntu 16.04, so it should work fine). First add the repostiory (add-apt-repository)

1.  open "Software & updates"
2.  navigate to "other software"
3.  locate the checkbox - "http://ppa.launchpad.net/jasp-uva/jasp/ubuntu xenial main" [only one will be checked, select that and click "Edit" button].
4. Change the 'Distribution' from "xenial" to "wily"
5. in terminal, execute - sudo apt-get update
6. in terminal, execute - sudo apt-get install jasp

Let me know if it doesn't work out
