### ISSUE TITLE
Confidence interval for the one-sample t-test

### ISSUE THREAD

**Issue by MartinvanLeerdam** [jasp-stats/jasp-desktop#1330]
It appears to me that the confidence interval for the one-sample t-test is incorrect when the population value is not equal to 0. I would assume that the confidence limits express uncertainty with respect to the difference between estimation and population value. From the output it seems that the confidence limits are fixed on the estimated mean.
[CI one-sample t-test.pdf](https://github.com/jasp-stats/jasp-desktop/files/276275/CI.one-sample.t-test.pdf)

**Comment by JohnnyDoorn** [comment]
The confidence interval that is calculated is centered on the mean difference in the data, rather than the specified test-value. The test-procedure then consists of checking whether the test-value is located in the confidence interval, so it should not be centered on the test-value.

**Comment by MartinvanLeerdam** [comment]
Hallo Johnny,

Spreek je ook Nederlands? ​ (otherwise I'll send you a mail in English)

Zie onderstaand voorbeeld. Wanneer een andere test value wordt gekozen
blijft het 95% CI gelijk, en volgens mij klopt dat niet.

Groet,

Martin




2017-09-04 16:44 GMT+02:00 JohnnyDoorn <notifications@github.com>:

**Comment by MartinvanLeerdam** [comment]
Hi Johnny,

Dit voorbeeld is dezelfde data, maar dan met SPSS geanalyseerd. Hier wordt
wel het betrouwbaarheidsinterval rondom de sample mean difference
gecontrueerd. De alternatieve en, ik denk, gebruikelijke benadering is om
na te gaan of de waarde 0 in het interval ligt. Wat denk jij?

Groet,

Martin

2017-09-04 17:31 GMT+02:00 Martin van Leerdam <m.van.leerdam@gmail.com>:

**Comment by MartinvanLeerdam** [comment]
​

2017-09-04 18:16 GMT+02:00 Martin van Leerdam <m.van.leerdam@gmail.com>:

**Comment by JohnnyDoorn** [comment]
Hi Martin,
Nederlands mag ook! Bedankt voor alle info en feedback - je hebt gelijk dat het verwarrend is dat de "Mean Difference" wel berekend wordt op basis van de test value (als in, het gemiddelde van de variabele - de test value), maar het confidence interval niet. Ik zal even gaan overleggen met het team en kijken hoe we hiermee om kunnen gaan. Mijn gok is dat we de mean difference aan zullen passen (i.e., het gemiddelde rapporteren en niet het verschil tussen het gemiddelde en de test waarde), in plaats van het confidence interval. 
Hartelijke groet,
Johnny

**Comment by MartinvanLeerdam** [comment]
Ha Johnny,

Graag gedaan. Je zou natuurlijk ook twee betrouwbaarheidsintervallen in de
tabel kunnen zetten; een voor de schatting van het steekproefgemiddelde, en
een voor het gemiddeld verschil met de testwaarde.

Groet,

Martin

Op 4 september 2017 om 18:27 schreef JohnnyDoorn <notifications@github.com>:
