### ISSUE TITLE
Linear regression option is not working.

### ISSUE THREAD

**Issue by patel307** [jasp-stats/jasp-desktop#1337]
I get an error when I click "Linear Regression" under the "Regression" button.

This analysis terminated unexpectedly. Please contact its author.\n\nError in summary(fits[[i]])$coefficients : \n  $ operator is invalid for atomic vectors\n

**Comment by akashrajkn** [comment]
@patel307 which version of JASP are you using? (I tested on 0.7.5.5 and it is working fine).

If it's still not working for you, please share the file so that we can reproduce the issue.

**Comment by patel307** [comment]
I tried it on my Mac desktop earlier today and could not work it out. But
now, I tried it on a PC laptop with the same dataset and it's working
perfectly.

On Mon, May 30, 2016 at 9:38 PM, akash raj <notifications@github.com> wrote:

> @patel307 <https://github.com/patel307> which version of JASP are you
> using? (I tested on 0.7.5.5 and it is working fine).
>
> If it's still not working for you, please share the file so that we can
> reproduce the issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jasp-stats/jasp-desktop/issues/1337#issuecomment-222580282>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AOVtFgaTYQl7XfiWqLUa5Gs1xiTDXzBtks5qG58igaJpZM4IqDUy>
> .
>



-- 
Purav Patel
Graduate Research Assistant
Cognitive Architecture Lab
Department of Educational Psychology
University of Minnesota - Twin Cities

**Comment by boutinb** [comment]
@patel307 do you have still this problem with the latest JASP version (0.8.1)?

**Comment by patel307** [comment]
No, I have JASP 0.8.1 now and ran a linear regression without problems.

**Comment by AlexanderLyNL** [comment]
Great to hear that. Thank you for your comments. I'll close this issue.
