### ISSUE TITLE
ANOVA: error

### ISSUE THREAD

**Issue by Franzilatanzi** [jasp-stats/jasp-desktop#1340]
Hello,

I tried to calculate a repeated-measures ANOVA but as soon as I define a between-subject factor an error message appears. The same happens for a regular univariate ANOVA. What's wrong?

**Comment by raviselker** [comment]
Do you get the same error as described in issue #1320?

**Comment by cameissner** [comment]
I get the same error as #1320...

**Comment by boutinb** [comment]
Duplicate of #1320
