### ISSUE TITLE
Unexpected Internal Error

### ISSUE THREAD

**Issue by maia27** [jasp-stats/jasp-desktop#1343]
Hey guys, 

I'm trying to use your program on a Window's 8 computer, I had it working for a day and the next time I logged on it has come up with an "unexpected internal error" and force quits. I have tried un and re installing and have also tried downloading older versions and the same error keeps appearing. Sometimes I am able to open a data set (but never long enough to run anything) or sometimes it closes within a few seconds. 

I don't have R installed on my computer either.

Thanks,

**Comment by FransMeerhoff** [comment]
Hello maia27,

Let's try to get the latest version of JASP 0.7.5.6 working again (and solve problems on this version)
Can you do once more:
- uninstall JASP (from control panel->programs->programs and features->JASP uninstall)
- install JASP 0.7.5.6 from https://static.jasp-stats.org/JASP-0.7.5.6-Setup.exe
- Load one of the examples e.g. 'Kitchen Rolls'
- Try if you can start Descriptives and we have some result.

Moreover 
- I suppose you have a 64 bit Windows running?
- You logged on to you're computer with the same account and privileges?
 
Kind regards 
Frans Meerhoff

**Comment by maia27** [comment]
Hi Frans, 

I followed your steps and managed to open both an example data set and run statistics, and then do the same on my won data set. However if restart my computer and re-open JASP I get the same "unexpected internal error" and the program force closes (I couldn't even open an example set this time) 

And yes a 64bit Windows 8 and the same account and privileges

Thanks,
Maia

**Comment by FransMeerhoff** [comment]
Hi @maia27 ,

You can imagine this kind of problem is hard for us to solve if we do not have a reproduction path, but there are still some options you can try:
- A work around for this problem might be:
Download the 64 zipped version of JASP and unzip this file at some location. You can find it at the Windows download section of JASP. https://static.jasp-stats.org/JASP-0.7.5.6-64-bit.zip  
When you unzip this version and double click the JASP.exe JASP will run without any other installation settings.
- You can try to find the cause of problem by running the TaskManager and check if free memory is very low or check the programs that will be started automatically when windows starts that might cause this problem.

Kind regards
Frans Meerhoff

**Comment by maia27** [comment]
Hi Frans, 

sorry for the slow reply on this one.
Using the zipped version seems to be working for now!

Thanks for all your help!
Maia
