### ISSUE TITLE
Bayesian ANOVA's Bayes Factors values changing depending upon title of variables

### ISSUE THREAD

**Issue by jaspcheck** [jasp-stats/jasp-desktop#1347]
When I was double checking some of my Bayesian Repeated Measures ANOVAs using JASP, I noticed that if I change the name of the factor to something different from my original factor name, it would give me different Bayes Factors outputs. This seems like an inherently serious problem with JASP as surely the Bayes Factor values should be identical regardless of what I name my factors?!? These values also change depending on how I even name the levels in my factors too. Surely JASP should give exactly the same output regardless of factor titles? The way JASP works at the minute means no-one can replicate my analyses unless they enter exactly the same titles in their analyses. 

I am using JASP version 0.7.1.12

**Comment by akashrajkn** [comment]
@jaspcheck the current version of JASP is 0.7.5.6. Could you update and check if you are still facing the same problem?

**Comment by jaspcheck** [comment]
Hi @akashrajkn 

I've just check with the new version of JASP and unfortunately this issue still occurs. This is really concerning.

**Comment by raviselker** [comment]
Can you send us the file where this is happening so that we can try to replicate the issue? I think the difference in Bayes factor is probably due to sampling error. JASP uses numerical approximations for the Bayes factor so if you rerun the analysis, the Bayes factor can differ slightly from the previous time you ran the analysis.

**Comment by lindeloev** [comment]
@jaspcheck, An easy way to check the sampling error hypothesis that @raviselker proposed is to re-run the analysis without changing any factor names. If @raviselker is correct, the change in Bayes Factors should be no larger or smaller than if you change a factor name. If not, then there indeed is a problem.

**Comment by raviselker** [comment]
Any updates?

**Comment by jaspcheck** [comment]
Hi again,

Do you have an email address I can send the file to?

**Comment by raviselker** [comment]
You can send it to selker [dot] ravi [at] gmail [dot] com

Thank you!

**Comment by metamorphose42** [comment]
i have a similar issues, and i dont even change my variables names... everything is the same in these three analyses, yet the output is different... how is that possible?! many thanks

![screen shot 2016-08-26 at 15 37 19](https://cloud.githubusercontent.com/assets/18419722/18009889/0a57d308-6ba6-11e6-848d-0e77a783f51d.png)
![screen shot 2016-08-26 at 15 37 32](https://cloud.githubusercontent.com/assets/18419722/18009890/0a588fb4-6ba6-11e6-86c3-3d82f377f966.png)
![screen shot 2016-08-26 at 15 43 19](https://cloud.githubusercontent.com/assets/18419722/18009891/0a5abb36-6ba6-11e6-9b23-2e5926bfd020.png)

**Comment by lindeloev** [comment]
@metamorphose42, try reading what I and @raviselker wrote. Looks very much like an expected sampling error. It does not qualitatively change the BFs.

**Comment by metamorphose42** [comment]
@lindeloev thanks! i did all that, but my issue is which to report? (same concern: with anyone else rerunning it, even with identical variable names - and getting different results.. especially if i want to opensource my dataset) qualitatively similar but yet not the same..?

**Comment by lindeloev** [comment]
Usually, you would report the first you run to prevent cherry-picking. I wouldn't worry too much about an uncertainty of 2-3%. Multiple runs is a standard procedure to test convergence.

I Don't have JASP installed right now, but I think that in newer versions, you can change the number of samples. The more samples, the less variability in estimates - and the longer computation time.

**Comment by boutinb** [comment]
@JohnnyDoorn Hi Johnny, can we close this issue, or do you want to add some comments?
