### ISSUE TITLE
Error with specific variable 

### ISSUE THREAD

**Issue by IunoGroot** [jasp-stats/jasp-desktop#1353]
When i try to do a Bayes independent t-test (but also when i try doing other analyses where i have to use the 'group' variable (labeled with 1 and 2's) , i immediately get the following error:

This analysis terminated unexpectedly. Please contact its author.\n\nError :
map::at\n

What to do?

[MoCA-MMSE-CFQ-IG_1.zip](https://github.com/jasp-stats/jasp-desktop/files/327756/MoCA-MMSE-CFQ-IG_1.zip)

**Comment by raviselker** [comment]
I think this is the same issue as #1320 and we are working on a fix. For now I found a possible workaround: if you change the variable type of the grouping variable from nominal (three circles) to scale (ruler) in the data editor and then drag the variable of type scale to the group variable box, the analysis works again.

**Comment by IunoGroot** [comment]
Thank you so much! It works now :)

Date: Wed, 22 Jun 2016 05:57:22 -0700

**Comment by raviselker** [comment]
When I open the .csv from your zipped file and replicate your analysis it works fine. Did you use the export function to create the .csv? If so, could you send us the original data (so the one you loaded into JASP to do the analyses)?

**Comment by boutinb** [comment]
@IunoGroot I am still interested to understand why the raw data generated this problem? Can you send it in the ZIP file? Or is this problem actually solved with the newest release (0.8.1)?

**Comment by boutinb** [comment]
If this problem comes up again with the newest version of JASP, reopen this issue.
