### ISSUE TITLE
rpm Packaging

### ISSUE THREAD

**Issue by luigino** [jasp-stats/jasp-desktop#1354]
Trying to package jasp-desktop for openSUSE, so far it crashes on startup, also JASPEngine
complains about R extensions.
Are the version numbers in export packagecheck.R hard requirements? I couldn't track down all of them on CRAN archive.

Could this be the source of my problem? Pardon my vagueness, but I'm rather new at this.

Regards

**Comment by luigino** [comment]
![jasp_error](https://cloud.githubusercontent.com/assets/1450716/16365107/5c1fc7ca-3bf6-11e6-9eda-dac0a07cf25d.png)

Update: the attachment shows what I see when clicking on any of the analyses after loading one of the examples.

**Comment by boutinb** [comment]
Hi Luigino
We only know that JASP works fine with the version numbers in packagecheck.R. These versions are not hard requirements, so you could try with other R package versions. Unfortunately, I cannot help you much about that, I have no experience with OpenSUSE. But that would be great if you find a way to build it on this platform.

Kind regards,
Bruno

**Comment by luigino** [comment]
The app is packaged, but it crashes like shown in the screenshot above.

I've tried including the recommended version, but it doesn't make a difference.

It would be good to know if there's a way to debug this problem, because right now I'm stuck.

**Comment by boutinb** [comment]
This error means it cannot find the json files. It has in fact nothing to do with the R packages.
These json files should be found in Resources/Library of the executable folder. JASP tries to find this directory via the function exeDir() in the dirs.cpp (in JASP-Common). You can see here that this function is written for Windows, Mac, en per default you have the Linux version (that works on Ubuntu). Maybe you can try to check this code, and make one version that works on OpenSUSE

**Comment by boutinb** [comment]
@luigino Do you have still this problem?

**Comment by luigino** [comment]
I'm sorry to have left this open, I gave up on it long ago.
Perhaps the next packager will have more luck.

**Comment by boutinb** [comment]
If this problem comes up again with the newest version of JASP, reopen this issue.
