### ISSUE TITLE
Regression in SPSS versus JASP

### ISSUE THREAD

**Issue by amatejko** [jasp-stats/jasp-desktop#1365]
Hi! 

I happened to run the same analysis in SPSS and JASP, and I noticed there were some major differences. In SPSS, the regression model was not significant however in JASP it was.The data are identical. I have attached images of both to compare. They are both run with the "enter" method, and the findings from the effects are the same (neither of the variables are significant predictors). I was just puzzled about why the results from the overall models were so different?

Any help would be very much appreciated! 

SPSS
<img width="586" alt="screen shot 2016-07-06 at 10 13 38 pm" src="https://cloud.githubusercontent.com/assets/20330172/16640613/77e238ac-43c7-11e6-8757-4a5bce437e62.png">

JASP
<img width="978" alt="screen shot 2016-07-06 at 10 14 18 pm" src="https://cloud.githubusercontent.com/assets/20330172/16640612/74c3e5f8-43c7-11e6-81c7-3b22c436b44a.png">

**Comment by raviselker** [comment]
@quentingronau, can you check this?

**Comment by quentingronau** [comment]
Hi @amatejko ,

It would be great if you could please send me the .csv file with your data so that I can take a look.
You can either do this via github or you can send me a mail to [quentingronau@web.de](url)

Thank you!

**Comment by amatejko** [comment]
Hi @quentingronau and @raviselker 

As I was prepping the CSV I noticed the problem! It was simply a file sorting problem. I am so sorry and so embarrassed. 

Thanks for the very quick response! And once again I am so sorry! Perhaps we can delete the thread so others don't get concerned by this!

**Comment by raviselker** [comment]
Don't worry about it! I'll close this issue.
