### ISSUE TITLE
Download Unavailable

### ISSUE THREAD

**Issue by JSmith-MSU** [jasp-stats/jasp-desktop#1369]
I am attempting to download the latest version of the JASP software (v 0.7.5.6) from the website.  When clicking on either the "Windows XP and above" link or either link in the "Windows (zipped installation versions)" section I receive a "Site Not Found" from DreamHost.  I do not get this error when trying to download the older version (0.7.5.5) of the software from the same website.  I have tried from multiple versions of Windows OS (10, 7), multiple browsers (Chrome, Firefox, & IE), multiple locations (home, work, and friend's work in a different city) and in all variables I receive the same result....Site Not Found.  I contacted JASP through their FaceBook page and was asked to post a message here.  I am interested in installing the software, however must move forward within the next day or two due to having to get labs and classrooms ready for the upcoming academic school year.  Please advise.  Thanks!

**Comment by raviselker** [comment]
There is some issue with the https certificate of DreamHost. We changed the links on our download page to http (temporarily), and now it should work again.

**Comment by JSmith-MSU** [comment]
Thank you for the information.  I was able to obtain the file and have installed it on our master image.
