### ISSUE TITLE
The way we express interactions;     age:gender   or     age*gender

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#137]
@raviselker

**Comment by raviselker** [comment]
SPSS uses the "*" sign for interactions (see screen shot), so I think it's best to adopt this. Another reason to use the "*" sign for interactions is that an interaction is basically a multiplication of the variables in that interaction. The "*" sign is often used for multiplication while the ":" sign isn't (to my knowledge at least). Therefore, it makes more sense to use the "*" sign.

![image](https://cloud.githubusercontent.com/assets/4669197/5645404/3a4278d8-966f-11e4-9899-004239d7f497.png)

**Comment by jonathon-love** [comment]
here are a few different options:

1. target + trialType + trialType:target
2. target + trialType + trialType*target
3. target + trialType + trialType * target
4. target + trialType + trialType∗target
5. target + trialType + trialType ∗ target
6. target + trialType + trialType ∗ target

i think i like 5.

what do you think @EJWagenmakers ?

**Comment by EJWagenmakers** [comment]
I like the LaTeX \times sign, similar to an "x". This is the symbol that
":" and "*" try to emulate.
Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
1. target + trialType + trialType:target
2. target + trialType + trialType*target
3. target + trialType + trialType * target
4. target + trialType + trialType∗target
5. target + trialType + trialType ∗ target
6. target + trialType + trialType ∗ target
7. target + trialType + trialType×target
8. target + trialType + trialType × target
9. target + trialType + trialType × target

yeah,  i like 8.

**Comment by raviselker** [comment]
In 8, the '×' sign could be mistaken for the letter x because you don't add any whitespace between the factors and the sign. So I would go for 6 or 9.

**Comment by EJWagenmakers** [comment]
9 then

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by raviselker** [comment]
I thought about it, and I actually think the "∗" is clearer than the "×" symbol. For one, people that use SPSS are used to the "∗" symbol and we want to make the transition for them as smoothly as possible. Second, the "×" symbol is easily confused with the character "x"; that's also why in general the "×" symbol is not used in mathematical equations.

**Comment by jonathon-love** [comment]
yeah, i think i agree with ravi.

**Comment by raviselker** [comment]
This is how the "×" symbol in the ANOVA table looks like. I don't think it's a clear separator.

![screen shot 2015-01-15 at 12 42 13](https://cloud.githubusercontent.com/assets/4669197/5756803/0246c65a-9cb4-11e4-95f5-89c9ec2d67f1.png)

**Comment by EJWagenmakers** [comment]
Yeah that's a good argument

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
OK, so let's do interactions separated with:

"&#x2009;&#x273B;&#x2009;"

this is, a [Teardrop-Spoked Asterisk](http://unicode-table.com/en/273B/) surrounded by [thin spaces](http://unicode-table.com/en/2009/).

In R, this is:

    "\u2009\u273B\u2009"

**Comment by jonathon-love** [comment]
Ok, I *now* think we should move back to the conventional asterisk for interactions. The teardrop one looks a bit demented under windows.

![screen shot 2015-04-30 at 4 15 24 pm](https://cloud.githubusercontent.com/assets/3240247/7414633/4b98bc8a-ef54-11e4-86fc-af4eeb5cd5ce.png)

**Comment by EJWagenmakers** [comment]
I am indifferent.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
