### ISSUE TITLE
Jasp Installation Problem in Linux Mint

### ISSUE THREAD

**Issue by eayan** [jasp-stats/jasp-desktop#1375]
Hi,
I came across the fetching error while installing jasp as in the screenshot. Can anyone help me solve the problem ASAP? Is there any way to compile the newest version on a linux machine?

![selection_187](https://cloud.githubusercontent.com/assets/5304822/16870976/08a2f5e0-4a8d-11e6-9d1a-911b43eb9ae2.png)

**Comment by FransMeerhoff** [comment]
Hi @eayan ,

Can you help us with the following:

- did you add the uva ppa repo fist with
>sudo add-apt-repository ppa:jasp-uva/jasp 
- Which version of Linux are you running
-Can you send us the complete log file by redirecting it
-Not so common but jasp application name on Linux is in capitals. 

Kind regards 
Frans Meerhoff

**Comment by eayan** [comment]
Hi @FransMeerhoff ,

I have already added that repo, but the output was always the same. You can see the output and my system details here in the attached screen shots. I have managed to install Jasp on my second netbook machine and I have realized that even the version for Linux is missing some statistical analysis tools such as Mann Whitney U-test even though the latest version of it has all statistical tools, which is confusing and interesting. It is very easy to install the program for windows and Mac machines but it is a challenge for only linux users, which is nonsense. What kind of a vision is that to liberate the field of Statistics (?!).

I have searched a lot but could not find a way to compile it on my own machine. Is there a trustful 
![selection_192](https://cloud.githubusercontent.com/assets/5304822/16900474/2fe9e198-4c2e-11e6-851b-39c953f4511f.png)
way to compile it by myself?

I hope some people come up with a solution for that.

Best..

Erdal Ayan, MA-M.Sc.


![selection_191](https://cloud.githubusercontent.com/assets/5304822/16900454/bfde42ea-4c2d-11e6-9e1c-facd6795644e.png)
![selection_190](https://cloud.githubusercontent.com/assets/5304822/16900455/bfe604bc-4c2d-11e6-85e9-ddf2453154d2.png)
![selection_189](https://cloud.githubusercontent.com/assets/5304822/16900456/bfe6fee4-4c2d-11e6-94c1-d5112843649d.png)
![selection_188](https://cloud.githubusercontent.com/assets/5304822/16900457/bfeed1d2-4c2d-11e6-8ff0-1418339ae01a.png)

**Comment by akashrajkn** [comment]
@eayan @FransMeerhoff 

1. Linux Mint 13 (Maya) is based on Ubuntu 12.04 (Precise). We do not package JASP for the 12.04 version. You can build JASP from source code available in github (master branch)

2. Linux Mint 17 is based on Ubuntu 14.04 (Trusty) - JASP version 0.7.1.2 is available for Trusty version. Currently we have the latest version of JASP (0.7.5.6) on the LTS release of Ubuntu 16.04.

**Comment by AlexanderLyNL** [comment]
Flatpak should solve this

https://jasp-stats.org/linux-installation-guide/
