### ISSUE TITLE
Paired Bayesian t-Test returns BF of infinity

### ISSUE THREAD

**Issue by Suggestions-Only** [jasp-stats/jasp-desktop#1376]
I ran a paired samples t-test on an, admittedly, rather large dataset.  I received a Bayes Factor of infinity and none of the plots would function.  While I realize that data with this many cases is not commonly used in the social sciences, I'm wondering if anything can be done to get the plots to work, even if out of scale or with a portion cut-off and labeled.  I'm assuming that the Bayes Factor is hitting a number that JASP isn't designed to handle.

![github 1](https://cloud.githubusercontent.com/assets/20453113/16898294/77e950b4-4b98-11e6-9127-4c0009a013cf.JPG)

![github 2](https://cloud.githubusercontent.com/assets/20453113/16898295/81dcaf80-4b98-11e6-890c-1b5329cbcfcb.JPG)

![github 3](https://cloud.githubusercontent.com/assets/20453113/16898297/891f9078-4b98-11e6-803b-b82b83a8432b.JPG)

**Comment by boutinb** [comment]
Can you send the data (in the ZIP file)?

**Comment by Suggestions-Only** [comment]
[Analysis Result Is Infinite.zip](https://github.com/jasp-stats/jasp-desktop/files/856501/Analysis.Result.Is.Infinite.zip)

Did this work?

**Comment by boutinb** [comment]
I have got your file.
@quentingronau Can you have a look to this problem?

**Comment by AlexanderLyNL** [comment]
I assume that this is fixed now. Open a new issue if this reappears
