### ISSUE TITLE
Nothing appears in output section on Mac

### ISSUE THREAD

**Issue by alvarezlionel** [jasp-stats/jasp-desktop#1388]
Hi guys,
similar to what happened to patwms, I have nothing that happen in the output window, even if I run a test, or just navigate through the menus.

I work on Mac OS 10.11.6, I have XQwartz 2.7.9 installed, and open JASP 0.7.5.6.
![printscreen](https://cloud.githubusercontent.com/assets/17438310/17179491/c004a19e-5419-11e6-8e7e-6c5bf760f32c.png)

Do you know what I have to do (except changing my machine ;-)

Thank you in advance
l

**Comment by boutinb** [comment]
Hi @alvarezlionel,
Could you please run JASP in this way from a terminal: you go to /Applications/JASP.app/Contents/MacOS and start ./JASP
In this way all warnings and errors should be written to the terminal. Can you then send me the output?
Thanks,
Bruno

**Comment by alvarezlionel** [comment]
Hello,

thank you so much.

Here is what you asked me:
_____________________________________________

Last login: Tue Aug  9 16:45:10 on ttys000
wifi-secure-154-56:~ alva$ /Applications/JASP.app/Contents/MacOS/JASP ; exit;
QLayout: Attempting to add QLayout "" to BackStageWidget "backStage", which already has a layout
QLayout: Attempting to add QLayout "" to VariablesWidget "variablesPage", which already has a layout
subprocess started
subprocess started
subprocess started
subprocess started
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"{\n   \"messages\" : [\n      \"Package afex is not the correct version; expected: 0.12-135, installed: 0.14-2\",\n      \"Package coda is not the correct version; expected: 0.16-1, installed: 0.17-1\",\n      \"Package gnm is not the correct version; expected: 1.0-7, installed: 1.0-8\",\n      \"Package lsmeans is not the correct version; expected: 2.15, installed: 2.17\",\n      \"Package vcdExtra is not the correct version; expected: 0.6-3, installed: 0.6-1\"\n   ],\n   \"official\" : false\n}\n\n"
child not found :  "plotWidth"  in AnalysisForm::setOptions()
child not found :  "plotHeight"  in AnalysisForm::setOptions()
______________________________________________

A couple of words are in french, sorry…
Let me know if you need something else.

Thanks!

lionel



Lionel Alvarez

-----------------------------------------------------
Collaborateur Scientifique
Département de Pédagogie Spécialisée
Université de Fribourg - Suisse
www.unifr.ch/spedu<http://www.unifr.ch/spedu>

Le 9 août 2016 à 16:26, bruno boutin <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi @alvarezlionel<https://github.com/alvarezlionel>,
Could you please run JASP in this way from a terminal: you go to /Applications/JASP.app/Contents/MacOS and start ./JASP
In this way all warnings and errors should be written to the terminal. Can you then send me the output?
Thanks,
Bruno

**Comment by boutinb** [comment]
Hi Lionel,
For the french, no problem... I am also french! But let's continue in english so that other people can help us in case.
I don't see any strange things in the output, only the exit appearing just after the start of JASP. Did you type it?
Another question: do you have several versions of JASP installed on your Mac?
All macs I have tested work perfectly here... so it is for me really hard to find out what is the problem. So if you can tell me if you have any peculiar installations on you Mac, R in particular, or graphic/video cards, that would help up, maybe...

Bruno

**Comment by alvarezlionel** [comment]
Hi,

you asked several questions:

First, I didn’t type anything in the terminal output. I just opened the file /Applications/JASP.app/Contents/MacOS and start ./JASP as you asked.

Then, I always installed the new versions by replacing the previous. Should I change something here?

Finally, my Mac is an MacBook Air 5.1, IntelCore i5, 1.7Ghz, with the built in graphic card (intel HD Graphics 4000 1536 Mo).
I have R3.3.1 and RStudio0.99.903 installed. And the version of JASP I have is the 0.7.5.6.

lionel





Lionel Alvarez

-----------------------------------------------------
Collaborateur Scientifique
Département de Pédagogie Spécialisée
Université de Fribourg - Suisse
www.unifr.ch/spedu<http://www.unifr.ch/spedu>

Le 9 août 2016 à 18:06, bruno boutin <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi Lionel,
For the french, no problem... I am also french! But let's continue in english so that other people can help us in case.
I don't see any strange things in the output, only the exit appearing just after the start of JASP. Did you type it?
Another question: do you have several versions of JASP installed on your Mac?
All macs I have tested work perfectly here... so it is for me really hard to find out what is the problem. So if you can tell me if you have any peculiar installations on you Mac, R in particular, or graphic/video cards, that would help up, maybe...

Bruno

**Comment by boutinb** [comment]
Hmm, this is quite strange. The only think I can think of, is the R version... We use now R 3.1. This should not interfere with the installed R version (JASP installs its own version), but you never know...
Are you also admin of your MAC? You may try also to start JASP from your terminal with sudo ./JASP (if you are in the /Applications/JASP.app/Contents/MacOS folder).
Bruno

**Comment by alvarezlionel** [comment]
I changed R version to the 3.1, but nothing changed. I also tried to change the XQuartz to the 2.7.7 version as proposed on JASP website. Nothing changed.

Then I tried to « export results » (.html format) to test if the problem is only about visualisation, but no file were created when I tried the results export.


So finally, I have to change my machine ;-) Sad, I like it.
Or do you think about something else ?

Thank you so much for your time anyway

lionel



Lionel Alvarez

-----------------------------------------------------
Collaborateur Scientifique
Département de Pédagogie Spécialisée
Université de Fribourg - Suisse
www.unifr.ch/spedu<http://www.unifr.ch/spedu>

Le 11 août 2016 à 16:50, bruno boutin <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hmm, this is quite strange. The only think I can think of, is the R version... We use now R 3.1. This should not interfere with the installed R version (JASP installs its own version), but you never know...
Are you also admin of your MAC? You may try also to start JASP from your terminal with sudo ./JASP (if you are in the /Applications/JASP.app/Contents/MacOS folder).
Bruno

**Comment by akashrajkn** [comment]
@alvarezlionel can you test with JASP version 0.8.0 Beta5 and let us know if you are still facing the same problem?

**Comment by alvarezlionel** [comment]
Thanks for the update!!

Sorry to say, but I’m facing the same problem.

Here is the terminal output with JASP 0.8.0 Beta5:
Last login: Tue Aug 23 08:17:52 on ttys001
wifi-secure-154-56:~ alva$ /Applications/JASP.app/Contents/MacOS/JASP ; exit;
QObject::connect: No such signal FSBModel::hideAuthentication()
QObject::connect: No such signal FSBModel::hideAuthentication()
QObject::connect:  (receiver name: 'browser')
QObject::connect: No such signal FSBMExamples::hideAuthentication()
QLayout: Attempting to add QLayout "" to BackStageWidget "backStage", which already has a layout
QLayout: Attempting to add QLayout "" to VariablesWidget "variablesPage", which already has a layout
subprocess started
subprocess started
subprocess started
subprocess started
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"Avis : l'espace de nom \xE2\x80\x98""BayesFactor\xE2\x80\x99 n'est pas disponible et a \xC3\xA9t\xC3\xA9 remplac\xC3\xA9\npar .GlobalEnv lors du traitement de l'objet \xE2\x80\x98\xE2\x80\x99\n"
"{\n   \"messages\" : [\n      \"Package afex is not the correct version; expected: 0.12-135, installed: 0.14-2\",\n      \"Package coda is not the correct version; expected: 0.16-1, installed: 0.17-1\",\n      \"Package gnm is not the correct version; expected: 1.0-7, installed: 1.0-8\",\n      \"Package lsmeans is not the correct version; expected: 2.15, installed: 2.17\",\n      \"Package vcdExtra is not the correct version; expected: 0.6-3, installed: 0.6-1\"\n   ],\n   \"official\" : false\n}\n\n"


When I select “descriptives” > “Descriptives statistics” on JASP, the terminal output is:
child not found :  "plotWidth"  in AnalysisForm::setOptions()
child not found :  "plotHeight"  in AnalysisForm::setOptions()



I also updated XQwartz to version 2.7.9, nothing changed.


all the best

l




Le 22 août 2016 à 20:30, akash raj <notifications@github.com<mailto:notifications@github.com>> a écrit :


@alvarezlionel<https://github.com/alvarezlionel> can you test with JASP version 0.8.0 Beta5 and let us know if you are still facing the same problem?

**Comment by boutinb** [comment]
@alvarezlionel I re-visit old issues. Does this issue still occur with the new version of JASP? What I can see already from the output is that the versions of some R packages are not the right one.

**Comment by alvarezlionel** [comment]
Thanks for revisiting old issues.
I work on a new machine now, so it is impossible for me to tell you about what happens on my old MacBook Air.





Dr. Phil. Lionel Alvarez

____________________________
Lecteur
CERF –  Départ. des Sc. de l’Educ.
Université de Fribourg - Suisse
www.unifr.ch/cerf<http://www.unifr.ch/cerf>

+41 26 300 76 08
Regina Mundi – Bureau S2.131

On 19 Dec 2017, at 09:48, bruno boutin <notifications@github.com<mailto:notifications@github.com>> wrote:


@alvarezlionel<https://github.com/alvarezlionel> I re-visit old issues. Does this issue still occur with the new version of JASP? What I can see already from the output is that the versions of some R packages are not the right one.

**Comment by boutinb** [comment]
If I understand, it works now correctly and I can close this issue?

**Comment by alvarezlionel** [comment]
It works now correctly on another machine (MacBook Pro).
I don’t know about the previous machine (MacBook Air) because I don’t have it anymore.

So, personally, I can use JASP without any problem.

Thanks



Dr. Phil. Lionel Alvarez

____________________________
Lecteur
CERF –  Départ. des Sc. de l’Educ.
Université de Fribourg - Suisse
www.unifr.ch/cerf<http://www.unifr.ch/cerf>

+41 26 300 76 08
Regina Mundi – Bureau S2.131

On 19 Dec 2017, at 11:29, bruno boutin <notifications@github.com<mailto:notifications@github.com>> wrote:


If I understand, it works now correctly and I can close this issue?
