### ISSUE TITLE
Labels are swopped when setting up a RM-ANOVA (freq & Bayesian) with 4 factors 

### ISSUE THREAD

**Issue by MarliesV** [jasp-stats/jasp-desktop#1389]
Hi,
When setting up a repeated measures ANOVA with 4 within-subject factors that have two levels each, there seems to be something strange going on with the factor-level labels in the Repeated Measures Cells, making it complicated to interpret the output without confusing the effects of different factors. 
When using a model with 4 factors, the labels of the levels of the 3rd factor in the 'repeated measures cells' window, are replaced by the level-labels of the 4th factor. The levels of the 4th factor are now labeled as 'Level 1' and 'Level 2' again (even though I provided alternative labels for the 2 levels of the 4th factor under Repeated Measures Factors). 
The mixing/swopping of labels occurs in the output too. This makes it a bit difficult to still keep track of which cell is entered into the model under which factor. 
I'm using JASP on my Mac (El Capitan), not sure whether that matters... If you need my datafile in order to be able to replicate this issue, please let me know.
Regards,
Marlies

**Comment by FransMeerhoff** [comment]
Hi @MarliesV 

We just made an improvement on this issue for that in the new release JASP 0.8.0 which will arrive on a short term (We expect next release in about two weeks). I added a screenshot to check if this is the problem you are talking about.

<img width="500" alt="screen shot 2016-07-27 at 17 02 55" src="https://cloud.githubusercontent.com/assets/15656960/17180275/2adaa8f4-541c-11e6-8100-eb3dedc86069.png">

Kind regards
Frans Meerhoff

**Comment by MarliesV** [comment]
Hi Frans,
Thanks for your quick reply. Does the issue you refer to concern difficult-to-read labels? Then I think my issue might be different..
In my case, the 3rd factor Freq has the levels 16 & 18, and the 4th factor Int has the levels E and R. If you now look at the level labels as displayed under Repeated Measures Cells, the levels of Int (4th factor) E and R are displayed 3rd, whereas the levels of Freq (3rd factor; 16-18) have disappeared (are now displayed as Level 1 and Level 2 but difficult to read here), see the screenshot.
I am not sure whether this is merely a display issue due to the length of the labels,  there also seems to be some additional swopping of labels.
Marlies
![screen shot 2016-07-27 at 17 34 39](https://cloud.githubusercontent.com/assets/20684862/17181554/da69401a-5420-11e6-8c30-3914cfe9f820.png)

**Comment by FransMeerhoff** [comment]
Hi @MarliesV 

I think I know what you mean now. but I can't reproduce it.
I have added a 4x2 example file that does the same as what you are doing,
but no mixing up of labels is happening there.

[4x2.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/387865/4x2.jasp.zip)

Can you send us the file it concerns. (You can do this by adding it as zip to this issue -best- or send it directly to F.A.M.Meerhoff@uva.nl)

BTW, you can check this issue on the latest Beta we are testing at the moment. (But remember this is not an official release)

https://static.jasp-stats.org/JASP-0.8.0.0-Beta-3.dmg

Kind Regards
Frans Meerhoff

**Comment by boutinb** [comment]
Hi @MarliesV Do youhave still still this problem with the latest version (0.8.1)? If yes, can you send us the JASP file?

**Comment by boutinb** [comment]
If this problem comes up again with the newest version of JASP, reopen this issue.
