### ISSUE TITLE
No Output on Mac

### ISSUE THREAD

**Issue by jerhae1** [jasp-stats/jasp-desktop#1399]
I am experiencing the same exact issue as 2 previous posts.  I can open data sets, but cannot alter them and analyses do not run.  The output window stays on "welcome."   I am running Mac OS 10.11.6, I have XQwartz 2.7.9 installed, and open JASP 0.7.5.6.
thanks,
Jerry

**Comment by boutinb** [comment]
Hi @jerhae1 ,
This is indeed an annoying problem. I have installed the last version of XQuartz, but I cannot reproduce this problem. Could you please run JASP in this way from a terminal: you go to /Applications/JASP.app/Contents/MacOS and start ./JASP
In this way all warnings and errors should be written to the terminal. Can you then send me the output?
Thanks,
Bruno

**Comment by jerhae1** [comment]
Hi Bruno,
Thanks so much for your response.  I have to apologize as I'm not well versed with terminal.  I open up the Terminal application on my mac and typed "/Applications/JASP.app/Contents/MacOS".  It then says "is a directory".  I then typed "start./JASP" and it says "no such file or directory."  I'm guessing I'm not typing this in correctly or am using Terminal incorrectly.  Sorry!
Jerry

**Comment by jerhae1** [comment]
Hi Bruno,
Sorry for repeated comments.  I tried running JASP again, and now I received the following error message in the output window:  "This analysis terminated unexpectedly. Please contact its author.\n\nError : No such file or directory\n

**Comment by boutinb** [comment]
Hi Jerry,
On the terminal, you have to type "cd /Applications/JASP.app/Contents/MacOS", and then yo type "./JASP".
Can you manage to start JASP in this way?

**Comment by jerhae1** [comment]
Okay, that worked. Thanks!  Below is the output.  I opened 2 of the example data sets and tried to run an analysis:


l$ ./JASP
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
QLayout: Attempting to add QLayout "" to BackStageWidget "backStage", which already has a layout
QLayout: Attempting to add QLayout "" to VariablesWidget "variablesPage", which already has a layout
subprocess started
subprocess started
subprocess started
subprocess started
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"{\n   \"messages\" : [\n      \"Package afex is not the correct version; expected: 0.12-135, installed: 0.14-2\",\n      \"Package coda is not the correct version; expected: 0.16-1, installed: 0.17-1\",\n      \"Package gnm is not the correct version; expected: 1.0-7, installed: 1.0-8\",\n      \"Package lsmeans is not the correct version; expected: 2.15, installed: 2.17\",\n      \"Package vcdExtra is not the correct version; expected: 0.6-3, installed: 0.6-1\"\n   ],\n   \"official\" : false\n}\n\n"
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
child not found :  "plotWidth"  in AnalysisForm::setOptions()
child not found :  "plotHeight"  in AnalysisForm::setOptions()
child not found :  "plotWidth"  in AnalysisForm::setOptions()
child not found :  "plotHeight"  in AnalysisForm::setOptions()
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
QLayout: Attempting to add QLayout "" to BackStageWidget "backStage", which already has a layout
QLayout: Attempting to add QLayout "" to VariablesWidget "variablesPage", which already has a layout
subprocess started
subprocess started
subprocess started
subprocess started
child not found :  "plotWidth"  in AnalysisForm::setOptions()
child not found :  "plotHeight"  in AnalysisForm::setOptions()
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"{\n   \"messages\" : [\n      \"Package afex is not the correct version; expected: 0.12-135, installed: 0.14-2\",\n      \"Package coda is not the correct version; expected: 0.16-1, installed: 0.17-1\",\n      \"Package gnm is not the correct version; expected: 1.0-7, installed: 1.0-8\",\n      \"Package lsmeans is not the correct version; expected: 2.15, installed: 2.17\",\n      \"Package vcdExtra is not the correct version; expected: 0.6-3, installed: 0.6-1\"\n   ],\n   \"official\" : false\n}\n\n"

**Comment by haraldbj** [comment]
I just installed JASP and XQuartz to my Mac today and I have the exact same problem as  jerhae1. I can open a file, but all attempts to do an analysis results in the same error-message in the output-window: "This analysis terminated unexpectedly. Please contact its author.\n\nError : No such file or directory\n"

**Comment by FransMeerhoff** [comment]
Hello @jerhae1 

I'm taking over this issue from Bruno Boutin who's on Holiday for a while.
At the moment we are at the and of the test cycle of the new version of JASP 0.8.
This version is available as Beta at 
https://static.jasp-stats.org/JASP-0.8.0.0-Beta-5.dmg 
We would like to know of course if this issue occurs on the latest version (some points at startup are changed there.)
> Would you like to install this version and check if you're problem is solved
> If not please resend the startup info with
On the terminal, you have to type "cd /Applications/JASP.app/Contents/MacOS", and then yo type "./JASP".

@haraldbj 
Although you have a slightly different problem in the sense that yo get an 'This analysis terminated unexpectedly' error and jerhae1 only a welcome screen, would you be able to check the same. 

Thanks a lot  for helping us out with this nasty issue we can't reproduce.

Kind regards 
Frans Meerhoff

**Comment by haraldbj** [comment]
Hi,

Thank you for your assistance. I´ve installed the beta now and it seems that it helped some, but did´t solve everything. I get the same error message as previously when running descriptives and independent samples T-test, but most other analysis´seems to work, including the new reliability and factor-analysis programs (love that you’ve included those by the way!).

Kind regards

Harald Bækkelund
16. aug. 2016 kl. 09.15 skrev FransMeerhoff <notifications@github.com<mailto:notifications@github.com>>:


Hello @jerhae1<https://github.com/jerhae1>

I'm taking over this issue from Bruno Boutin who's on Holiday for a while.
At the moment we are at the and of the test cycle of the new version of JASP 0.8.
This version is available as Beta at
https://static.jasp-stats.org/JASP-0.8.0.0-Beta-5.dmg
We would like to know of course if this issue occurs on the latest version (some points at startup are changed there.)

Would you like to install this version and check if you're problem is solved
If not please resend the startup info with
On the terminal, you have to type "cd /Applications/JASP.app/Contents/MacOS", and then yo type "./JASP".

@haraldbj<https://github.com/haraldbj>
Although you have a slightly different problem in the sense that yo get an 'This analysis terminated unexpectedly' error and jerhae1 only a welcome screen, would you be able to check the same.

Thanks a lot for helping us out with this nasty issue we can't reproduce.

Kind regards
Frans Meerhoff

**Comment by jerhae1** [comment]
Hi Frans,
Thanks for your email.  Unfortunately, I'm experiencing the same problem.  No output, only the welcome screen. Is it possible that I do not have Quartz working properly?  Below is the output from terminal.  I tried to run a descriptive analysis and a linear regression:

 ./JASP
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
QObject::connect: No such signal FSBModel::hideAuthentication()
QObject::connect: No such signal FSBModel::hideAuthentication()
QObject::connect:  (receiver name: 'browser')
QObject::connect: No such signal FSBMExamples::hideAuthentication()
QLayout: Attempting to add QLayout "" to BackStageWidget "backStage", which already has a layout
QLayout: Attempting to add QLayout "" to VariablesWidget "variablesPage", which already has a layout
subprocess started
subprocess started
subprocess started
subprocess started
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"{\n   \"messages\" : [\n      \"Package afex is not the correct version; expected: 0.12-135, installed: 0.14-2\",\n      \"Package coda is not the correct version; expected: 0.16-1, installed: 0.17-1\",\n      \"Package gnm is not the correct version; expected: 1.0-7, installed: 1.0-8\",\n      \"Package lsmeans is not the correct version; expected: 2.15, installed: 2.17\",\n      \"Package vcdExtra is not the correct version; expected: 0.6-3, installed: 0.6-1\"\n   ],\n   \"official\" : false\n}\n\n"
child not found :  "plotWidth"  in AnalysisForm::setOptions()
child not found :  "plotHeight"  in AnalysisForm::setOptions()

**Comment by FransMeerhoff** [comment]
Hello @jerhae1 

- It is indeed a good suggestion to check the XQuartz version you are using. We publish the following version at our site: https://static.jasp-stats.org/XQuartz-2.7.7.dmg. I'm running version 2.7.9 without any problem. You can check this version if you press the Go tab -> Utilities -> select XQuartz and the version is show at the last line.

- You are already familiar with start JASP from the command line. Could you do the following. Start JASP again from the command line and now try to perform some analyses. More output should be generated then in the terminal box. Could you send this extra information.

Kind regards 
Frans Meerhoff

**Comment by jerhae1** [comment]
Hi Frans,
I opened up JASP from the command line, opened example file "Big 5", and then ran a descriptive analysis as well as a regression analysis. When I ran the descriptive analysis this time, the output box now displayed the same message that Haraldbj (above) reported: "This analysis terminated unexpectedly. Please contact author.\n\nError : No such file or directory\n."   And when I open up the T-TEST I can see the table in the output box, but after adding a variable, I then get the error message again. Below is all of the output from the terminal.  As you'll see, there does not appear to be any output added to the terminal when I run analyses.  I ran analyses multiple times and the terminal output remained constant after opening the application.

I am running Quartz 2.79.  I have restarted my computer multiple times. Is there anything that I have to do to "activate" XQuartz?  Or do I have to have XQuartz open when running JASP (or start JASP from the XQuartz dialog box)?  I'm trying to figure out if I'm missing something on my end.

Thanks for all of your help,
Jerry


./JASP
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
QObject::connect: No such signal FSBModel::hideAuthentication()
QObject::connect: No such signal FSBModel::hideAuthentication()
QObject::connect:  (receiver name: 'browser')
QObject::connect: No such signal FSBMExamples::hideAuthentication()
QLayout: Attempting to add QLayout "" to BackStageWidget "backStage", which already has a layout
QLayout: Attempting to add QLayout "" to VariablesWidget "variablesPage", which already has a layout
subprocess started
subprocess started
subprocess started
subprocess started
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"Warning: namespace \xE2\x80\x98""BayesFactor\xE2\x80\x99 is not available and has been replaced\nby .GlobalEnv when processing object \xE2\x80\x98\xE2\x80\x99\n"
"{\n   \"messages\" : [\n      \"Package afex is not the correct version; expected: 0.12-135, installed: 0.14-2\",\n      \"Package coda is not the correct version; expected: 0.16-1, installed: 0.17-1\",\n      \"Package gnm is not the correct version; expected: 1.0-7, installed: 1.0-8\",\n      \"Package lsmeans is not the correct version; expected: 2.15, installed: 2.17\",\n      \"Package vcdExtra is not the correct version; expected: 0.6-3, installed: 0.6-1\"\n   ],\n   \"official\" : false\n}\n\n"
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
child not found :  "plotWidth"  in AnalysisForm::setOptions()
child not found :  "plotHeight"  in AnalysisForm::setOptions()
child not found :  "plotWidth"  in AnalysisForm::setOptions()
child not found :  "plotHeight"  in AnalysisForm::setOptions()
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
child not found :  "plotWidth"  in AnalysisForm::setOptions()
child not found :  "plotHeight"  in AnalysisForm::setOptions()
child not found :  "plotWidth"  in AnalysisForm::setOptions()
child not found :  "plotHeight"  in AnalysisForm::setOptions()
child not found :  "plotWidth"  in AnalysisForm::setOptions()
child not found :  "plotHeight"  in AnalysisForm::setOptions()

**Comment by boutinb** [comment]
Sorry for the late answer... Do you have still this problem?

**Comment by JohnnyDoorn** [comment]
Some people are still experiencing this issue - is the solution still to run JASP from the terminal?

**Comment by AlexanderLyNL** [comment]
Please post JASP and OS version number.

**Comment by JohnnyDoorn** [comment]
The issue is present for 2 people:
JASP 0.8.1.1
Sierra 10.12.3 
OSX 10.9.5

So they're running different OS versions.. I tried to run it from the command line but still it didn't work sadly enough.

**Comment by AlexanderLyNL** [comment]
Try reinstalling xquartz first. 

https://www.xquartz.org/

**Comment by JohnnyDoorn** [comment]
Yeah we tried that already, with the latest version of xquartz.

**Comment by AlexanderLyNL** [comment]
I'm not sure what to do now. As I can't reproduce this problem here. I'll ask Bruno once I'm back in Amsterdam. Please write down emails and we'll keep in contact.

**Comment by jerhae1** [comment]
I was never able to get it working.  I've switched to jamovi, which seems to be operating correctly.
Thanks

**Comment by AlexanderLyNL** [comment]
Hi Jerry,

It's a pity you've given up on it. We're getting to the bottom of this issue, as it seems to be reproduced by two other people. We hope that the fix also helps you out. 

Cheers,
Alexander

**Comment by anomalosepia** [comment]
any luck on this issue? I can reproduce on my mac and I'm happy to test stuff out. 
thanks!

**Comment by boutinb** [comment]
@anomalosepia The problem lies in the process intercommunication. Next week I will implement a new way to communicate. I hope this can solve this problem. The problem is that I cannot reproduce this problem on my Mac (and on any other macs I have access to). So I will make a test version, and maybe you can test it?

**Comment by anomalosepia** [comment]
Happy to do any testing. 

Thanks!

-A

**Comment by boutinb** [comment]
@anomalosepia I put a new test version here:  https://static.jasp-stats.org/JASP-0.8.1.2.59_debug.dmg
Would it be possible to test it by starting it from a terminal, with this command: /Applications/JASP.app/Contents/MacOS/JASP
Then do one descriptive analysis from an example dataset. Can you tell me whether the results appear, and send me the log you see on the terminal?
Thank you,
Bruno

**Comment by anomalosepia** [comment]
Huh, never even got that far. Maybe it’s trying to look for a local path to your machine? 

Thanks!

-A

 

This happened (screen shot)

Terminal and screen shot below

 

Sepiida-2:~ adam$ /Applications/JASP.app/Contents/MacOS/JASP

BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList

QObject::connect: No such signal FSBModel::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101

QObject::connect: No such signal FSBModel::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101

QObject::connect: No such signal FSBModel::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101

QObject::connect:  (receiver name: 'browser')

QObject::connect: No such signal FSBMExamples::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101

PPI: 96.

Master: Shared memory created

R HOME PATH: /Applications/JASP.app/Contents/MacOS/../Frameworks/R.framework/Versions/3.3/Resources

DESKTOP: subprocess started

Error in gzfile(file, mode) : cannot open the connection

In addition: Warning message:

In gzfile(file, mode) :

  cannot open compressed file '/private/var/folders/4q/2k_v3g5d13b01bff9nh76bwh0000gn/T/Cleanup At Startup/libloc_236_311ab74b95ce5d96.rds', probable reason 'No such file or directory'

**Comment by boutinb** [comment]
@anomalosepia The problem lies in the shared memory on your computer. I don't know why exactly yet. I put a new debug version https://static.jasp-stats.org/JASP-0.8.1.2.59_debug.dmg.
Can you try it?
Also can you type on a terminal: sysctl -A | grep shm
And send me the result?
Thank you really much!
Bruno

**Comment by anomalosepia** [comment]
Same problem, crash on launch

 

 

Terminal output

BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList

QObject::connect: No such signal FSBModel::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101

QObject::connect: No such signal FSBModel::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101

QObject::connect: No such signal FSBModel::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101

QObject::connect:  (receiver name: 'browser')

QObject::connect: No such signal FSBMExamples::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101

PPI: 96.

Master: Shared memory created with name JASP-IPC-11462

Master: Shared memory found with name JASP-IPC-11462

R HOME PATH: /Applications/JASP.app/Contents/MacOS/../Frameworks/R.framework/Versions/3.3/Resources

DESKTOP: subprocess started

ENGINE: {

   "official" : true

}

 

Slave: Cannot find shared memory with name JASP-IPC-11462 :No such file or directory

 

 

And sysctl returns

 

kern.sysv.shmall: 1024

kern.sysv.shmseg: 8

kern.sysv.shmmni: 32

kern.sysv.shmmin: 1

kern.sysv.shmmax: 4194304

machdep.pmap.hashmax: 21

security.mac.posixshm_enforce: 1

security.mac.sysvshm_enforce: 1

**Comment by boutinb** [comment]
@anomalosepia The problem is that is that the engine cannot find the shared memory created by JASP. This shared memory is probably simulated with a file in /tmp/boost_interprocess
Can you go to this folder with a terminal (cd /tmp/boost_interprocess) and type "ls -al"
Give me the results.
I have made a new debug version at the same place https://static.jasp-stats.org/JASP-0.8.1.2.59_debug.dmg
This version gives more permission to use the shared memory file. Can you open it from a terminal again and try to run a descriptive analysis. Can you give me the logs, and send me again the results of "ls -al" in /tmp/boost_interprocess ?
I think we are really nearby a solution!
Bruno

**Comment by anomalosepia** [comment]
ok results of LS-al

```
total 0
drwxrwxrwx  2 root  wheel   68 Jul 12 07:09 ./
drwxrwxrwx  3 root  wheel  102 Jul 12 07:09 ../
```

however, same problem on launch with the crash. Results below. No difference if I verify the app through gatekeeper or not. 

```
BackStageForm::loadRecents();  setting 'recentItems' is not a QStringList
QObject::connect: No such signal FSBModel::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101
QObject::connect: No such signal FSBModel::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101
QObject::connect: No such signal FSBModel::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101
QObject::connect:  (receiver name: 'browser')
QObject::connect: No such signal FSBMExamples::hideAuthentication() in /Users/brunoboutin/JASP/Develop/bruno/JASP-Desktop/backstage/fsbrowser.cpp:101
PPI: 192.
Master: Shared memory created with name JASP-IPC-20059
R HOME PATH: /Applications/JASP.app/Contents/MacOS/../Frameworks/R.framework/Versions/3.3/Resources
DESKTOP: subprocess started
ENGINE: {
   "official" : true
}

Slave: Cannot find shared memory with name JASP-IPC-20059 :No such file or directory
DESKTOP: subprocess error: 1
DESKTOP: subprocess finished
```

**Comment by boutinb** [comment]
@anomalosepia Well... apparently it cannot use the temporary folder in /tmp/boost_interprocess
I have made a new debug version: https://static.jasp-stats.org/JASP-0.8.1.2.59_debug.dmg where it forces to use the ~/.JASP/temp folder. So again, can you download this version, and run it from the terminal with /Applications/JASP.app/Contents/MacOS/JASP ?
This time, can you with another terminal go to  ~/.JASP/temp (cd cd ~/.JASP/temp), and again type
     ls -al
Thanks,
Bruno

**Comment by boutinb** [comment]
@anomalosepia I have made a new JASP version that solves the same problem for another user. You can download it from https://static.jasp-stats.org/JASP-0.8.1.2.mac.dmg
After installing it, can you start JASP (in the normal way) and check if you can start a analysis?

**Comment by FransMeerhoff** [comment]
Hi @anomalosepia 

If you still have this problem, or also on the latest version JASP 0.8., please reopen this issue.

Kind regards
Frans Meerhoff
