### ISSUE TITLE
DOE module

### ISSUE THREAD

**Issue by ghost** [jasp-stats/jasp-desktop#1402]
Hello,

In agronomy and industry, my students often have to set up classical designs of experiments such as randomized block designs and Latin square designs.

Minitab is very efficient with this issue (but very expensive) https://www.youtube.com/watch?v=SbktyedPfY0

Do you have any plan to make this possible in Jasp? Maybe a module?

Sincerly

**Comment by FransMeerhoff** [comment]
Hello @Indycool 

I can assure you that this issue is not yet on our roadmap, but
I've  send your request internally for comment.

Kind Regards 
Frans Meerhoff

**Comment by EJWagenmakers** [comment]
Hello @Indycool

Thanks for bringing this up. Right now JASP does have classical and Bayesian ANOVA. So when I look at the Minitab example, this is a simple repeated measures 2x2x2x2 ANOVA. In the ANOVA input panel, users can define factors and levels. Is there anything specific that you would like us to add? 

Cheers,
E.J.

**Comment by Indycool** [comment]
Thank you for your answer :) I'm trying to input datas in Jasp in a way that I'd get a Latin square experiment (special 3 factors Anova).

Here is an example that my students have to deal with on a regular basis when they do their internships.

[http://www.statsdirect.com/help/default.htm#analysis_of_variance/latin_square.htm%3FTocPath%3DAnalysis%2520of%2520variance%7C_____6](url)

I try to get the same results but I can't figure it out how, so I certainly get something wrong but I can't see it :/ 
Here is the file with the raw datas from the url (sorry it's not a .csv, github won't take it)

[Latin square.xlsx](https://github.com/jasp-stats/jasp-desktop/files/414946/Latin.square.xlsx)

Thank you for your help
