### ISSUE TITLE
RM ANOVA not working in JASP 0.8.0.0 Beta

### ISSUE THREAD

**Issue by IndrajeetPatil** [jasp-stats/jasp-desktop#1416]
Hi,

I just downloaded JASP 0.8.0.0 Beta and was carrying out RM ANOVA, but I get the following error.

![image](https://cloud.githubusercontent.com/assets/11330453/17743268/6e93479e-64a3-11e6-9e34-587446968587.png)

**Comment by IndrajeetPatil** [comment]
Additionally, the paired samples t test also doesn't work.

![capture](https://cloud.githubusercontent.com/assets/11330453/17743540/541f87e6-64a4-11e6-81d5-3a0e8e08f7af.PNG)

**Comment by FransMeerhoff** [comment]
Hi @IndrajeetPatil 

Can you tell us
- Which platform are you running
- Can you send us the data you are using and describe a little bit more in detail what goes wrong with what parameters.
- Does other analyses run smoothly?

Kind regards
Frans Meerhoff

**Comment by IndrajeetPatil** [comment]
Hi,

- I am using a Windows OS. 
- Actually, it's not specific to my data. I ran the same analysis with example data-sets provided in JASP and I get the same error. 
- I haven't tried all other analyses, but descriptive stats, regression, crosstabs, correlation analyses were running smoothly.

**Comment by EJWagenmakers** [comment]
Hi @IndrajeetPatil,

Thanks for the superquick feedback! The t-test error is because of interference with new functionality that will be added in the next release (SellkeMPR). We have already fixed this. The other error we hope to fix tomorrow. We will then issue a new release. Obviously these analyses are kinda important :-)
Thanks again!!
E.J.

**Comment by FransMeerhoff** [comment]
Hi @IndrajeetPatil ,

Thanks again for helping us finding this issue so quick.
If you download the new placed version, these problems should be solved.

Kind regards
Frans Meerhoff

**Comment by IndrajeetPatil** [comment]
Great! Thanks for resolving this so quickly, will download it and work with
it now! :)

**Comment by scottbateman** [comment]
Hi @FransMeerhoff 
I  just had the same problem. Can you clarify where to the download the fix? And I will confirm if it solved the problem for me.

**Comment by FransMeerhoff** [comment]
Hi @scottbateman 

You can download the  fix from the location:
at the Jasp download site for Windows:
http://static.jasp-stats.org/JASP-0.8.0.0-Beta-5-Setup.exe

Kind regards 
Frans Meerhoff

**Comment by scottbateman** [comment]
@FransMeerhoff OK. I thought, it may have been tagged differently for the change. 

I can confirm that a uninstall and reinstall of the install file fixed the problem for me on Windows 10.

Thanks!

**Comment by FransMeerhoff** [comment]
Hello @scottbateman 

Thank you for testing again!
Hope also that the new functionality is valuable for you.

Kind regards, 
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Solved in last Beta 5

**Comment by IndrajeetPatil** [comment]
Hi, 

I am now using JASP-0.8.0.0-Beta-5, but still there is an error in the descriptive statistics unit. 

![capture](https://cloud.githubusercontent.com/assets/11330453/17970144/93390f60-6ad5-11e6-8a1c-e76e38f6684f.PNG)

**Comment by FransMeerhoff** [comment]
Hi @IndrajeetPatil 

Sorry to hear that, that's pretty annoying.

But I do need to ask you 
- Can you confirm that your about box now shows the exact same info as ours, especially the timestamp?

<img width="385" alt="screen shot 2016-08-25 at 15 29 42" src="https://cloud.githubusercontent.com/assets/15656960/17970973/1727b2ce-6ad9-11e6-8145-1aa41d61dc19.png">

- Are you using a specify dataset or one of our example data files. Can you send us the JASP file or tell us what descriptive goes wrong.

Kind regards 
Frans Meerhoff

**Comment by IndrajeetPatil** [comment]
Oops, it started working again! Maybe it was just a temporary problem.
Sorry for the trouble!

**Comment by FransMeerhoff** [comment]
No problem.
Thanks
