### ISSUE TITLE
Block Hierarchical Regression

### ISSUE THREAD

**Issue by renenob** [jasp-stats/jasp-desktop#1418]
would like to request that there be an option for Block hierarchical regression.  Social Sciences people rarely use stepwise regression.  We need some control on which block of variables would come first, and which block would come next. Thank you.

**Comment by diogenesbido** [comment]
It is very common to include "control variables" in the first block and the independent variables in the second block.

**Comment by renenob** [comment]
That's true.

**Comment by Jannik012** [comment]
When I do a hierarchical regression as diogenesbido recommends, it seems like I am not able to choose which variable is computed in the first block and which is added in the second block. It seems to be completely random. Any ideas on how I can solve this problem?

**Comment by diogenesbido** [comment]
In this version 0.8.0.0) is not possible to run hierquical regression (to controlling the sequence of input of IV in the model)

**Comment by chantelanuit** [comment]
I agree, block hierarchical regression would be essential for using JASP within a statistical course in psychology. In my field, most of the analyses are theory-driven and it is advised that students avoid pure mathematical models (e.g. stepwise or setwise, apart if they have very big samples to replicate the analysis with split-half). So, the ability to specify blocks manually would be a great addition to JASP.

**Comment by boutinb** [comment]
Our researchers are thinking of adding this feature to JASP. Hopefully this should be implemented soon.

**Comment by renenob** [comment]
Thank you very much, JASP!

**Comment by robert-reich** [comment]
I would like this feature as well.
