### ISSUE TITLE
Mixed Design ANOVA error using .sav file

### ISSUE THREAD

**Issue by NickMKitchen** [jasp-stats/jasp-desktop#1422]
Hi, I have had an issue with running a mixed design ANOVA with 1 repeated measure, that has 3 levels (Target Number) and 1 between subjects factor with 3 levels (Group) from a .sav file I generated in SPSS, in JASP version 0.7.5.6

I can add the repeated measures variables but I get this error when I try and add the between subjects factor...

"This analysis terminated unexpectedly. Please contact its author.\n\nError : map::at\n"

If I save it as a .csv file from within SPSS then it seems to work okay but the codes for missing values don't translate across from the .csv file to JASP

Thanks,

Nick

**Comment by raviselker** [comment]
Officially JASP version 0.7.5.6 doesn't support importing .sav files, so anything going wrong there is due to the functionality not being completely ready. However, the new 0.8.0.0 beta release does support importing .sav files, so I would download the new version and try it on this version.

**Comment by NickMKitchen** [comment]
Thanks for your message, I have tried with the new 0.8.0.0 beta release and I have the same issue of the "This analysis terminated unexpectedly. Please contact its author.\n\nError : map::at\n" error when I try to add the between subjects factor

**Comment by boutinb** [comment]
Can you give us the SAV file that provokes this error?

**Comment by AlexanderLyNL** [comment]
sav files readable in JASP now. Please open a new thread if the problem resurfaces.
