### ISSUE TITLE
No images in Export Results

### ISSUE THREAD

**Issue by scottbateman** [jasp-stats/jasp-desktop#1423]
In version 0.8.0.0 Beta 5, when exporting an HTML results file no image plots are displayed, there is just a broken image link. Looking at the image source shows that the path is set to a "resources/..." sub-directory. However, this sub-directory does not exist.

**Comment by scottbateman** [comment]
Follow-up... I overwrote my results file and this seemed to embed the images correctly. Not sure how I might replicate consistently.

**Comment by boutinb** [comment]
If you have a reproduction path, can you re-open this issue?
Thanks,
Bruno
