### ISSUE TITLE
Post-hoc tests disappear from RM-Anova output

### ISSUE THREAD

**Issue by scottbateman** [jasp-stats/jasp-desktop#1424]
When adding post hoc test to the results of an RM ANOVA, the table disappear after clicking back on the results view. I have tried both with and without clicking OK, after adding the post hoc tests.

Version 0.8.0.0 Beta 5 on Windows 10. 

I have tried post hocs with other tests.

**Comment by boutinb** [comment]
I think this problem is already solved in the new JASP version
