### ISSUE TITLE
Unable to build jasp on Mac

### ISSUE THREAD

**Issue by aditya1315** [jasp-stats/jasp-desktop#1426]
Hi,

I am facing a difficulty while building jasp on my Mac system - I am using OS X El Captain. I followed the steps in the readme docs - Guide to building JASP. 

I have maintained the directory structure given there 

- jasp-desktop
- boost_1_54_0
- build-JASP-Desktop-Debug
  - libarchive.a
  - ...

I get an error when I build it on QT - "[InstallJASPRPackage] Error 127"

Any help is appreciated

**Comment by FransMeerhoff** [comment]
Hi @aditya1315 

Had you installed R on your mac?

If not you can try the following. Probably this will solve your build problem:

Install the R 3.1 package on the mac:
•	Download from https://r.research.att.com/   
•	Install the package.
You will then have a /Lybrary/Frameworks/R.framework folder on the Mac which is referenced in the project file.

Kind Regards 
Frans Meerhoff

**Comment by aditya1315** [comment]
Hi @FransMeerhoff, thank you for your response

I have R 3.3.1 on my mac. But I am still getting the error. What could be going wrong?

**Comment by akashrajkn** [comment]
@aditya1315 , _R_HOME path looks for the path ".../R.framework/Versions/3.1/Resources/library" on mac OS X [check the file JASP-Engine.pro where R_HOME variable is set]. As Frans pointed out, install R 3.1 from the link. (Alternately you could try modifying the path in JASP-Engine.pro to use Versions/3.3/... )

**Comment by aditya1315** [comment]
That seemed to fix the issue. Now, when I try to build jasp, as soon as the jasp window loads up, I get a popup saying "JASP has experienced an unexpected internal error."

My compile output shows

QLayout: Attempting to add QLayout "" to BackStageWidget "backStage", which already has a layout
QLayout: Attempting to add QLayout "" to VariablesWidget "variablesPage", which already has a layout
subprocess started
"Error in loadNamespace(name) : there is no package called 'rjson'
"
subprocess error 1
subprocess finished 0

But I have already installed "rjson" package. I confirmed this after looking at the rjson folder inside the library folder of R.framework. Any reason why this is happening?

**Comment by akashrajkn** [comment]
@aditya1315 this could happen if you already have a newer version of "rjson" installed on your system. Look at [this thread on stackoverflow](http://stackoverflow.com/a/32724388). Try this - uninstall "rjson" package and then reinstall it (using R 3.1 version). Let us know if this works out

**Comment by aditya1315** [comment]
@akashrajkn I looked at the thread. I reinstalled rjson, the problem persists. I have redefined the R_HOME path in JASP-Engine.pro to point to Library/Frameworks/R.framework/Versions/3.1/Resources/library . I double-checked the R version I am using and installed all the necessary R packages required for compiling jasp given in https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-building-guide.md
I have installed Qt 5.4. Should I try reinstalling Qt?

**Comment by akashrajkn** [comment]
I think I see the problem. You only modified _R_HOME in JASP-Engine.pro. But there is an absolute path defined in enginesync.cpp file.

`#elif __APPLE__
QString rHomePath = programDir.absoluteFilePath("../Frameworks/R.framework/Versions/3.1/Resources");`

You have to change this path accordingly. Try modifying this and let me know if you still face a problem.

**Comment by aditya1315** [comment]
@akashrajkn this worked. Thanks!
