### ISSUE TITLE
No output shown 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1427]
At the WinBUGS workshop, one of the participants (running Windows 10) had a previous JASP version working. However, after installing the latest release (the one with the ANOVA running), he could start JASP, load a file, but the welcome screen never disappeared and no output was shown, regardless of the analyses that were selected. He was going to post a screenshot but perhaps he didn't get to it.
E.J.

**Comment by boutinb** [comment]
This is too vague to investigate further.
