### ISSUE TITLE
Principal Component Analysis - Chi squared test table is empty

### ISSUE THREAD

**Issue by aditya1315** [jasp-stats/jasp-desktop#1428]
I ran PCA on an example dataset (Big 5, included variables - Neuroticism, extraversion). The Component Loadings table shows the output, but the Chi-squared test table is empty. Please look into this. I used jasp version 0.8.0 beta on mac.

**Comment by akashrajkn** [comment]
@boutinb this issue still exists in the current build. Can you please tag the author of this analysis?

**Comment by aditya1315** [comment]
I can try to make a fix for this.

**Comment by boutinb** [comment]
@aditya1315 Did you try to fix this?
