### ISSUE TITLE
Corrupted data in OSF

### ISSUE THREAD

**Issue by FransMeerhoff** [jasp-stats/jasp-desktop#1429]
During JASP Workshop users saved files in the OSF
Some JASP files appeared to be corrupted.
One repro is:
From a generated jasp file choose 'Export Results' and fill in '<filename>.jasp'
The correct message appears that the extension of the exported file should be .html'
BUT: The file is even though saved in the OSF as jasp file but the content is html
Downloading the file an renaming the extension shows the correct result but the OSF depicts it as corrupted because it expects a .jasp file as content.

**Comment by FransMeerhoff** [comment]
Another way to corrupt the data in the OSF is:
Open a .csv file in the OSF.
And save it without changing anything. This wil corrupt the file too.

**Comment by boutinb** [comment]
Solved in next release
