### ISSUE TITLE
Compile problem on CentOS 7

### ISSUE THREAD

**Issue by cypresstwist** [jasp-stats/jasp-desktop#1430]
I run into the following problem while compiling on CentOS 7:

_In file included from /usr/include/c++/4.8.2/backward/strstream:51:0,
                 from engine.cpp:20:
/usr/include/c++/4.8.2/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^
In file included from engine.cpp:31:0:
**rbridge.h:21:21: fatal error: RInside.h: No such file or directory**
 #include <RInside.h>
                     ^
compilation terminated.
make[1]: **\* [engine.o] Error 1
make[1]: Leaving directory `/home/cypress/Downloads/JASP/jasp-desktop/JASP-Engine'
make: **\* [sub-JASP-Engine-make_first] Error 2_

But the R-RInside-devel.x86_64 package _is_ installed:

_$ yum info R-RInside-devel.x86_64
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
- base: mirrors.ulbsibiu.ro
- elrepo: www.jules.fm
- epel: mirrors.neterra.net
- extras: mirrors.ulbsibiu.ro
- nux-dextop: li.nux.ro
- updates: mirrors.ulbsibiu.ro
  Installed Packages
  Name        : R-RInside-devel
  Arch        : x86_64
  Version     : 0.2.13
  Release     : 3.el7
  Size        : 9.7 k
  Repo        : installed
  From repo   : epel
  Summary     : RInside Development Files
  URL         : http://cran.r-project.org/web/packages/RInside/
  License     : GPLv2+
  Description : Header files for RInside._

Since I could not find a CentOS package I am trying to compile JASP on my machine.

**Comment by aditya1315** [comment]
@cypresstwist most likely, RInside has been installed at a different path. On linux, R_HOME (check JASP-Engine.pro file) point to the path "/usr/lib/R". The packages must normally be installed in '/usr/lib/R/library'.

Try this,
1) On terminal, type "R" to fire up the R console.
2) type ".libPaths()". This shows you the paths where R packages might be installed. [If it is not pointing to '/usr/lib/R/library', you can set it manually, type - .libPaths('/usr/lib/R/library') on the R console.]
3) install RInside from R console - install.packages("RInside", lib="/usr/lib/R/library')

Let me know if this does not work

**Comment by aditya1315** [comment]
@cypresstwist most likely, RInside has been installed at a different path. On linux, R_HOME (check JASP-Engine.pro file) point to the path "/usr/lib/R". The packages must normally be installed in '/usr/lib/R/library'.

Try this,
1) On terminal, type "R" to open the R console.
2) type ".libPaths()". This shows you the paths where R packages might be installed. [If it is not pointing to '/usr/lib/R/library', you can set it manually, type - .libPaths('/usr/lib/R/library') on the R console.]
3) install RInside from R console - install.packages("RInside", lib="/usr/lib/R/library')

**Comment by cypresstwist** [comment]
I did a

> install.packages("RInside", lib="/usr/lib/R/library")
Warning in install.packages("RInside", lib = "/usr/lib/R/library") :
  'lib = "/usr/lib/R/library"' is not writable
Would you like to use a personal library instead?  (y/n) y
Would you like to create a personal library
~/R/x86_64-redhat-linux-gnu-library/3.3
to install packages into?  (y/n) y

Then exited R and did a

>make clean
qmake-qt5 JASP.pro 
make

in the jasp source code folder folder and still got a 

>In file included from engine.cpp:31:0:
rbridge.h:21:21: fatal error: RInside.h: No such file or directory
 #include <RInside.h>
compilation terminated.

Also

> .libPaths()
[1] "/home/cypress/R/x86_64-redhat-linux-gnu-library/3.3"
[2] "/usr/lib64/R/library"                               
[3] "/usr/share/R/library"

so i do have a /usr/lib64/R/library but not a /usr/lib/R/library folder on my CentOS 7 machine. 
I next tried to 

>.libPaths('/usr/lib/R/library')

in R console and this created a symlink to /usr/lib64/R/library. Trying to 

> install.packages("RInside", lib="/usr/lib/R/library")

again gives me the following message:

>lib = "/usr/lib/R/library"' is not writable

I tried starting R with 

>sudo R

but the same permissions message appears. How do I install those packages in /usr/lib/R/library with administrator rights?

**Comment by akashrajkn** [comment]
@cypresstwist 

1) can you tell me where R is installed on your system?
2) If your R_HOME is "/usr/lib64/R/" , then try installing Inside in the path "/usr/lib64/R/library" [Alternatively, you can modify the enginesync.cpp to point to the path where R packages are installed - but keep that as the last resort]

**Comment by cypresstwist** [comment]
1)

>$ whereis R
R: /usr/bin/R /usr/lib/R /usr/lib64/R /usr/include/R /usr/share/R /usr/share/man/man1/R.1.gz

2) I tried that already. I get a

>lib = "/usr/lib/R/library"' is not writable

How do I install packages from within R so that I can write to a path to which I as a user don't have access permissions to?

**Comment by akashrajkn** [comment]
@cypresstwist , i'll get back to you on this

**Comment by akashrajkn** [comment]
@cypresstwist , you can modify the code to point to the path where R packages are installed. Look at [enginesync.cpp](https://github.com/jasp-stats/jasp-desktop/blob/development/JASP-Desktop/enginesync.cpp), line 411 (under the macro for linux). You can add the path where RInside is installed to the R_LIBS. 

```
env.insert("R_LIBS", programDir.absoluteFilePath("R/library") + ":" + rHome.absoluteFilePath("library") + ":" + rHome.absoluteFilePath("site-library") + ":" + "path/to/RInside/");
```

Let me know if this doesn't work

**Comment by silberzwiebel** [comment]
Hi, I had a smiliar problem when trying to compile jasp under Fedora 24. I managed to compile by changing the R_HOME variable in JSAP-Engine.pro (line 40) from `/usr/lib/R` to `/usr/lib64/R`.
However, I ran into [another issue after compiling...](https://github.com/jasp-stats/jasp-desktop/issues/1507)
