### ISSUE TITLE
Runtime error: JASP crashes

### ISSUE THREAD

**Issue by janakl4us** [jasp-stats/jasp-desktop#1431]
I had JASP repeatedly crash as I was running analyses. This is a screenshot of the error message, after which my laptop just shuts the programme down (and of course doesn't save anything unsaved): http://i66.tinypic.com/2hs7qzm.jpg Any ideas?

**Comment by FransMeerhoff** [comment]
Hi @janakl4us 

The strange thing about your crash is that Microsoft Visual Studio shows the error message.
We do not develop JASP with MVS. Can you:
- Check in the Windows TaskManager if something running from Visual Studio. If So can you check if your problem disappears if you stop that process.
- Can you send us the JASP file. You can do this by 
adding it to this issue as zip file or send it directly to F.A.M.Meerhoff@uva.nl
- Is the crash now very easy to reproduce or if you start all over again with a new JASP file all goes well again?

Kind Regards
Frans Meerhoff

**Comment by janakl4us** [comment]
I can't find any programs that run from MVS. Also, the crash happened as I was using different example datasets (twice, with different files), but of course, I haven't been able to reproduce the error as such yet. What I did notice was that when I open the Task Manager, four versions of JASPEngine.exe were running even though at the moment, I only have one JASP window open - is that normal?

**Comment by janakl4us** [comment]
Okay, it just happened again, this time with the singer.csv dataset from the workshop.

**Comment by FransMeerhoff** [comment]
Four versions of the engines is normal. The reason for that is that every engine can do analyses simultaneously for one started JASP application.

**Comment by FransMeerhoff** [comment]
Hi @janakl4us 

Sorry for the inconvenience now. Which version of Windows do you have?
Did this problem not occurred yesterday ??
About the MVS. I think it must be installed somewhere on your machine.
JASP and Microsoft Visual Studio should not interfere, but that might be a clue to search further.

Frans

**Comment by janakl4us** [comment]
No, weirdly it didn't happen yesterday (or any other time I've used JASP before). If I look at my installed programs, I do have a program called "Microsoft Visual Studio 2010 Tools for Runtime" and a German equivalent in the list.

**Comment by janakl4us** [comment]
Oh, and I use Windows 10.

**Comment by FransMeerhoff** [comment]
Hi @janakl4us 

First thing you can try, if there are updates available for Windows or Microsoft Visual Studio 2010.
If you go to theSstart button -> Settings-> Update @ Security you can check if you have missing updates.
You can find some problems on the internet with this issue.

Frans

**Comment by janakl4us** [comment]
Okay, thanks @FransMeerhoff - I ran the updates and will keep you posted if the problem still persists.

**Comment by lesajm** [comment]
I am having this exact same error.  I used JASP just days ago with no issues but now I get this Runtime Error everytime I try to run any tests on my data.

**Comment by FransMeerhoff** [comment]
@lesajm 

We are close to a new release of JASP 0.9 .
If you still have the problem with that version please reopen this issue.

Kind regards
Frans Meerhoff
