### ISSUE TITLE
Within-Subjects Repeated Anova with Between Subjects Factor Reporting Issue

### ISSUE THREAD

**Issue by wilhelmhofmann** [jasp-stats/jasp-desktop#1432]
There is a reporting bug in the within-subjects effects portion of the table output when adding a between subjects factor to a 2 x 2 repeated factors design. The problem is with the report of the A x B interaction and the A x B x between factor report -- both lines are identical, see the attached figure. (this was done with the preinstalled BUGS dataset. 

![image](https://cloud.githubusercontent.com/assets/21197948/17893222/34065a8e-6945-11e6-9b4e-9c51a34519e5.png)

**Comment by JohnnyDoorn** [comment]
Hi Wilhelm,
I managed to replicate your bug. However, I do not think it is a bug in JASP, but simply a property of the bugs dataset - if you specify another between subjects variable, these lines do differ. I tested some other datasets as well, and it appears to be specific to the bugs dataset with gender, so I'm inclined to believe there's no programming error in there but just a weird result. Feel free to correct me though, maybe SPSS or R give different results.
Kind regards,
Johnny
