### ISSUE TITLE
UI behavior inconsistent with "standard behavior" when saving via OSF

### ISSUE THREAD

**Issue by paullemmens** [jasp-stats/jasp-desktop#1433]
When saving a (new) JASP file on OSF storage, one first selects Save as and follows through with selecting the appropriate OSF folder, inputting a file name, and clicking the save button. 

After modifying the file and needing to save, clicking the Save button, in the file menu, brings up a dialog popup to save locally.

To me this is against "default" behavior of other programs where using Save as to save a file somewhere (else) is a one-time action only. After that a regular Save is automatically to the file's location. 

At a higher level, it feels as if the OSF interaction should be a separate item in the File menu rather than integrated in the Save (especially) and Open menu because it behaves so differently from the other File menu buttons. This off-default behavior might also be related to [the easy errors overwriting OSF files](https://github.com/jasp-stats/jasp-desktop/issues/1429).

**Comment by boutinb** [comment]
@paullemmens: I could see this inconsistency. I will fix it.
File handling on computer should get the same behaviour as with OSF. The first vertical tab shows the actions (Open/Save, etc), the second tab shows the location of the files. That is how we designed it, but it may of course still have some inconsistencies we should fix.

**Comment by boutinb** [comment]
When opening or creating a file on OSF, after modifying it, typing CTRL-S, or clicking on the Save button, save the JASP file in OSF and does not ask to save it locally. So I think this problem has been solved.
