### ISSUE TITLE
Plotting functionality in Bayesian ANOVA

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1434]
@raviselker @mmarsman1 
The classical ANOVA has some cool plotting options. It would be nice to make exactly the same options available in the Bayesian ANOVA. Hopefully this just means copy-pasting code.
E.J.

**Comment by boutinb** [comment]
@TimKDJ Did you implement this?

**Comment by TimKDJ** [comment]
Yes this was added in PR #1603
