### ISSUE TITLE
Allow window resize?

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1435]
From the JASP Forum: "I'm running into a problem with not being able to see my full variable names when setting up a repeated measures analysis. Is there a way to resize the variable window to see the full variable names in the column from which you grab them for the analysis? Seems like this should be an easy window drag, but that is not working for me. (I'm working in Mac OSX.)"

E.J.

**Comment by boutinb** [comment]
tooltip has been added
