### ISSUE TITLE
Frequentist paired t-test not working

### ISSUE THREAD

**Issue by arnig** [jasp-stats/jasp-desktop#1436]
I am unable to perform a paired samples t-test in JASP 0.8.0.0 Beta, on a Mac, running El Capitan. This was not a problem in JASP 0.7.5.6. Screenshot of the error provided here:

https://dl.dropboxusercontent.com/u/3576423/ttest_error.png

I've reproduced this on several datasets, which I had previously analyzed without problems. 

Other frequentist t-tests are working, as well as ANOVAs and Bayesian analyses performed at the workshop this week. So it seems to me that it's linked specifically to the paired samples t. 

Cheers, 
Árni

**Comment by akashrajkn** [comment]
@arnig this issue has been fixed. Please download the dmg file again from the jasp-stats website.

**Comment by arnig** [comment]
Great! Thanks.
