### ISSUE TITLE
sav import error for categorical data

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1437]
Feedback through the gmail account:
"<JASP> also allows for the import of .sav files, but this was a case of modified rapture: there seems to be a bug on this that allows such files to be processed using regression analysis, but not analysis using categorical variables such as t-tests, ANOVA and RM ANOVA. Those programs work fine on the same data imported as a .csv file, so there is nothing wrong with the data. 

To clarify: if a .sav file is imported as .csv file, all the programs work perfectly. 
If the same file is opened just as the original .sav file, the correlation, regression and factor analysis programs are fine with it, whereas the t-test, ANOVA and RM ANOVA programs return an error message. " I will ask for more details.

**Comment by aknight1-uva** [comment]
-Huummmm - The big difference between CSV and SAV import is that SAV import does a _*much*_ better job of preserving the data type than CSV. Is there something unexpected in his SAV files - as far as column types goes - which gets lost in the CSV export/import? Copies of both her/his files, and some idea of which version of which program created them would be extremely helpful.

**Comment by EJWagenmakers** [comment]
I will send a file over regular Email.
