### ISSUE TITLE
RManova bug

### ISSUE THREAD

**Issue by elke2222** [jasp-stats/jasp-desktop#1439]
Since installing JASP 8 for the workshop in Amsterdam, repeated measures anova results in the following output (also during the workshop with the data and variables used in the workshop):
![image](https://cloud.githubusercontent.com/assets/21257751/17998653/cd299b90-6b75-11e6-8321-ba71b267b7e0.png)

My computer:
![image](https://cloud.githubusercontent.com/assets/21257751/17998720/1cdde6e6-6b76-11e6-9e56-cb989fb4757d.png)

**Comment by FransMeerhoff** [comment]
Hello @elke2222 

This is a known problem. Please Uninstall your version of JASP and reinstall the latest Beta version that is now on the site. This should fix your problem.

Kind regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
See #1416 for this.
If you have a different problem, please contact us again.
