### ISSUE TITLE
Repeated Measures Cells Order in RMANOVA

### ISSUE THREAD

**Issue by tpleskac** [jasp-stats/jasp-desktop#1440]
This bug has been around for a while. You can get around it...but it should be fixed.

 I have a dataset with 4 factors each with 2 levels (to be clear this is not my own as ANOVAs with 4 factors can be a bit mind boggling to digest). Everything works well up to 3 factors, but when you add the 4th factor the cell names get shuffled such that the level labels are swapped into the 3rd factor. And the labels for the 4th factor are lost. The same problem is present in the Bayesian RMANOVA. Underneath the hood I am pretty confident that the order is actually maintained (as the ANOVA results line up with things like SPSS). But, this should be confirmed for both RMANOVA and Bayesian RMANOVA. 

Here are the first 2 factors:
![first2factors](https://cloud.githubusercontent.com/assets/8436912/18053457/b818dd42-6dff-11e6-8cbf-72327a639346.png)

Here are factors 3 and 4
![factors3and4](https://cloud.githubusercontent.com/assets/8436912/18053474/d26acd7c-6dff-11e6-842f-1e9bcca8a3c1.png)

Here are the scrambled cell labels.
![scrambledcelllabels](https://cloud.githubusercontent.com/assets/8436912/18053493/ed8cd10e-6dff-11e6-8a9d-8da4ef896a79.png)

Enjoy. And thanks for this software.

**Comment by AlexanderLyNL** [comment]
This should have been fixed now. If not please open a new issue.
