### ISSUE TITLE
Descriptives

### ISSUE THREAD

**Issue by groeinarsdottir** [jasp-stats/jasp-desktop#1441]
Hi!

Great job with the new release! Some very nice features and a lot of improvements.
However, I came across an issue when doing descriptive analysis. When I wanted to use ordinal or categorical variables I had a problem with getting the output. The following error message came up:

This analysis terminated unexpectedly. Please contact its author.\n\nError in data.frame(group = group, y = y) : \n  arguments imply differing number of rows: 154, 91\n

Again, when I wanted to plot the data from a continuous variable but split it with a categorical variable I also had the similar problem.

This analysis terminated unexpectedly. Please contact its author.\n\nError in data.frame(group = group, y = y) : \n  arguments imply differing number of rows: 154, 153\n

What is going on here? Is this something you can fix?

All the best
Gró

**Comment by IndrajeetPatil** [comment]
I also sometimes encounter the same problem *solely* when I am working with categorical variables.

**Comment by boutinb** [comment]
Hi @groeinarsdottir 
Could you send your data file and tell exactly which columns you use (with which parameters)? Then we can hopefully reproduce your problem.

Thanks,
Bruno

**Comment by groeinarsdottir** [comment]
Hi Bruno,


I have been using a couple of data files and I get the same problem with all of them. As soon as I start using categorical variables I get an error message. For example, I was analysing data from this open OSF file and none of the categorical variables worked when I was doing descriptive analysis and Bayesian ANOVA.


https://osf.io/vyibm/files/


All the best

Gró


________________________________
Från: bruno boutin <notifications@github.com>
Skickat: den 30 augusti 2016 13:34
Till: jasp-stats/jasp-desktop
Kopia: Gró Einarsdóttir; Mention
Ämne: Re: [jasp-stats/jasp-desktop] Descriptives (#1441)


Hi @groeinarsdottir<https://github.com/groeinarsdottir>
Could you send your data file and tell exactly which columns you use (with which parameters)? Then we can hopefully reproduce your problem.

Thanks,
Bruno

-

**Comment by boutinb** [comment]
Dis you try the last version (0.8.1). I have tried of your files with this version and I got no problem,=.
