### ISSUE TITLE
Plotting bug w/ summary stats module

### ISSUE THREAD

**Issue by EtzAlex** [jasp-stats/jasp-desktop#1446]
When I input a sufficiently large t value (>~4) into the t-test summary stats module, my posterior distribution disappears. I have attached a .jasp file with the output.
[SummaryStatsBUG.zip](https://github.com/jasp-stats/jasp-desktop/files/454009/SummaryStatsBUG.zip)

I am running JASP 0.8.0.0 beta on my mac.

**Comment by akashrajkn** [comment]
This bug is fixed in PR: #1447
