### ISSUE TITLE
Follow-up tests for every cell in classical ANOVA

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1448]
Feature request, from the JASP Email:
"One other question, for follow-up tests after a significant interaction in a factorial ANOVA, will there be an option added for conducting tests (e.g., Tukey HSD) that test the comparison of every cell in the analysis? This option is available on JMP software, and it is very useful for helping students quickly interpret significant interaction effects in a factorial ANOVA. This would be a very welcome addition to JASP for interpreting significant interactions! (as it stands, the post hoc tests just interpret significant main effects)"

Cheers,
E.J.

**Comment by sahrii** [comment]
Hello, when you say the post hoc tests just interpret significant main effects, what if I don't have a significant main effect, but the post hoc test which has been pbonf corrected for the same factor is significant?
<img width="527" alt="screen shot 2017-11-20 at 10 57 09 pm" src="https://user-images.githubusercontent.com/33831632/33018407-33588b04-ce46-11e7-8a60-e75003dea743.png">

**Comment by JohnnyDoorn** [comment]
Hi Sahrii,
That does look a little strange. Would you mind sharing your dataset or jasp-file so I can take a closer look at it? You can also email it to me at j.b.vandoorn <at> uva.nl if that is more convenient
I would expect these two p-values to be the same when you only have one RM factor with two levels - see the attached screenshot, for example.
![rm_anova_twolevels](https://user-images.githubusercontent.com/15704203/33020183-91f7e8b0-cdfd-11e7-88e6-dff8d65af3c6.png)

Kind regards
Johnny

**Comment by sahrii** [comment]
Hi Johnny, have emailed it though. Thanks!

**Comment by AlexanderLyNL** [comment]
I think that this is fixed now.

**Comment by AlexanderLyNL** [comment]
I think that this is fixed now.
