### ISSUE TITLE
Jasp freezing and will not show results

### ISSUE THREAD

**Issue by ThompsonAD** [jasp-stats/jasp-desktop#1451]
Hello!
I am using an ASUS, with the following settings:
Windows 10, Intel core i5-5200U CPU @ 2.20GHz 2.19GHz, 8.00GB RAM, 64-bit operating system x64-based processor
(I hope that is all the info you needed)

I am having multiple problems with JASP.
The first is that is freezes and has the "(not responding)" icon upon opening. It freezes for awhile but finally loads. It lets me upload the csv. data sheet into it. the second problem occurs when I try to run the tests on the data. It will not let me run any statistical tests. I select everything properly (I know this because I follow the same instructions people in my class next me follow and nothing pops up). I select the data and put it into the rows and columns, when I press "OK" the screen shows me my data set on the left as always but continues to display the "welcome to JASP" message instead of the tables. I tested the example tables provided by JASP and still nothing popped u

**Comment by boutinb** [comment]
Sorry for the late answer... Do you have still this problem with the last version? If yes, did you try to download the ZIP version (https://jasp-stats.org/download/#advanced)?

**Comment by ThompsonAD** [comment]
It's okay! I ended up figuring it out!

On Mar 15, 2017, at 10:22 AM, bruno boutin <notifications@github.com<mailto:notifications@github.com>> wrote:

*****THIS IS AN EXTERNAL E-MAIL. STOP AND THINK BEFORE CLICKING A LINK, OPENING AN ATTACHMENT OR REPLYING TO THIS MESSAGE*****

Sorry for the late answer... Do you have still this problem with the last version? If yes, did you try to download the ZIP version (https://jasp-stats.org/download/#advanced)?

**Comment by boutinb** [comment]
What was the problem?

**Comment by ThompsonAD** [comment]
When I would run the software it would let me input my data but when I submitted it all it wouldn't show me the statistics, it would just keep the welcome to jasp screen. I updated my computer software (windows) then it ran just fine!

On Mar 16, 2017, at 4:43 AM, bruno boutin <notifications@github.com<mailto:notifications@github.com>> wrote:

*****THIS IS AN EXTERNAL E-MAIL. STOP AND THINK BEFORE CLICKING A LINK, OPENING AN ATTACHMENT OR REPLYING TO THIS MESSAGE*****

What was the problem?

**Comment by boutinb** [comment]
From which to which version of Windows did you upgrade?

**Comment by ThompsonAD** [comment]
I have windows 10, it just needed a normal maintenance update

On Mar 17, 2017, at 3:21 AM, bruno boutin <notifications@github.com<mailto:notifications@github.com>> wrote:

*****THIS IS AN EXTERNAL E-MAIL. STOP AND THINK BEFORE CLICKING A LINK, OPENING AN ATTACHMENT OR REPLYING TO THIS MESSAGE*****

From which to which version of Windows did you upgrade?
