### ISSUE TITLE
File/Close

### ISSUE THREAD

**Issue by coledavis** [jasp-stats/jasp-desktop#1456]
This is a minor issue, I know, but I would just advise that File/Close does not seem to work.

Version 0.8.0.0.
Windows7 64 bit computer. Old user.

**Comment by coledavis** [comment]
Ah, I understand. It closes the current file, not the program. Sorry.

**Comment by FransMeerhoff** [comment]
OK @coledavis 

No problem, indeed the close gives the possibility to open a new file without creating a new instance of JASP itself.
