### ISSUE TITLE
SumStats correlation bug

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1457]
@akashrajkn 

When I run correlation pairs and switch to BF_01, the dot remains in the old (wrong) spot. See screenshot!
I haven't checked the other analyses but that would be worth doing.

![image](https://cloud.githubusercontent.com/assets/8603015/18515453/b3684880-7a95-11e6-9d6a-f455b7689c4c.png)

**Comment by akashrajkn** [comment]
Fixed this in pull request #1462
