### ISSUE TITLE
Sumstats issue

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1463]
@akashrajkn 

When I conduct a SumStat unpaired t-test, and I press "OK", then I only see the output, but the input panel turns blank. If I then press an output element the issue is resolved. Still, the initial blank input panel is not how it's supposed to work. See screenshot.
![image](https://cloud.githubusercontent.com/assets/8603015/18619653/8e7869a4-7e02-11e6-9c4e-7ba3dc706541.png)

**Comment by akashrajkn** [comment]
@EJWagenmakers I think this is the expected behaviour. In JASP-Common, when the OK button is clicked, the (input) options form is closed and it shows the dataset on the left. In Summary stats, since dataset is not required, it shows an empty panel.

**Comment by FransMeerhoff** [comment]
Hi @EJWagenmakers , @akashrajkn 

It's very easy to disable the OK button in the summer statistics (not shown). I can do that for the moment?
(After the panel redesign this problem would not be occur anyway.)

Gr. Frans

**Comment by EJWagenmakers** [comment]
OK!
