### ISSUE TITLE
[Debian] source of backbone-min-1.1.2.js is missing

### ISSUE THREAD

**Issue by mih** [jasp-stats/jasp-desktop#1472]
This file in JASP-Desktop/html/js exists only in minified form. This is not considered "the preferred form for modification". Please add the actual source for this library.

Without the complete source this packages is not suitable for inclusion in Debian.

An alternative action would be to strip the minified file from the sources.

**Comment by AlexanderLyNL** [comment]
See flatpack 

https://jasp-stats.org/linux-installation-guide/
