### ISSUE TITLE
[Debian] exhaustive specification of (optional) dependencies on R packages

### ISSUE THREAD

**Issue by mih** [jasp-stats/jasp-desktop#1473]
Here is what I compiled from the website and the existing packages:

Depends (doesn't work without)
- afex
- bayesfactor
- car
- effects
- hypergeo
- lme4
- logspline
- rjson

Recommends (expected for a default install, but not required):
- ggplot2
- lsmeans
- plotrix
- rcpp
- rinside
- vcd
- vcdextra

With all these and their dependencies installed, I see the following at start-up:
- Package acepack not installed
- Package corpcor not installed
- Package d3Network not installed
- Package ellipse not installed
- Package fdrtool not installed
- Package Formula not installed
- Package ggm not installed
- Package glasso not installed
- Package Hmisc not installed
- Package huge not installed
- Package igraph not installed
- Package jpeg not installed
- Package latticeExtra not installed
- Package lavaan not installed
- Package matrixcalc not installed
- Package mnormt not installed
- Package pbivnorm not installed
- Package pixmap not installed
- Package png not installed
- Package psych not installed
- Package qgraph not installed
- Package quadprog not installed
- Package RJSONIO not installed
- Package rtiff not installed
- Package sem not installed
- Package semTools not installed
- Package sendplot not installed
- Package sna not installed
- Package whisker not installed

How can these be classified into dependencies, recomendations, suggests (nice to have), and false-positives?

**Comment by stephensrmmartin** [comment]
The packages you mentioned as 'not installed', I believe, are dependencies of the JASP R dependencies. I would classify all of those as dependencies *of* the R packages that need them, not as JASP dependencies, per se.

This is a ton of work, if debian doesn't have those R packages in the repos. Because I didn't want to create separate packages for every JASP R dependency and their dependency tree, I created one large package that provided all of the JASP R dependency and their respective dependencies; in the metadata, I simply stated that the jasp-rbundle provides r-cran-semtools and such.

**Comment by mih** [comment]
There is cran2deb which makes it easy to get Debian packages for anything R. However, if those are dependency of 3rd-party dependencies something is broken anyway. For example we have a dedicated r--cran-hmisc package, but it is not installed -- so something isn't specifying its dependency properly (assuming your assessment is correct). Any idea how to trace what library is causing hmisc to be expected as present on a system?

**Comment by mih** [comment]
I got JASP to complain about one missing dep:

File -> Examples -> Big 5 -> PCA -> Pic two  variables:

````
This analysis terminated unexpectedly. Please contact its author.\n\nError in loadNamespace(name) : there is no package called ‘psych’\n
````

**Comment by mih** [comment]
Interestingly, JASP seems unable to benefit from the presence of the psych library in my local user installation:

````
% R

R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library("psych")
>
````

Error in JASP remains the same, though. Is there any switch to make JASP be able to use local user installations? That would make it possible to dynamically obtain missing dependencies via R's own package manager. Or is that undesirable for some reason?

**Comment by akashrajkn** [comment]
@mih , currently jasp checks the paths "rHome/library" and "rHome/site-library" for installed r packages. Try installing psych into one of these paths.

**Comment by mih** [comment]
@akashrajkn Thanks! Are we talking about this code? https://github.com/jasp-stats/jasp-desktop/blob/development/JASP-Desktop/enginesync.cpp#L407

On my system, R places packages installed by a user into directories like this: `$HOME/R/x86_64-pc-linux-gnu-library/3.3/psych`. I don't know a way to make R reveal this programmatically. `R CMD config` doesn't seem to offer this.

**Comment by akashrajkn** [comment]
@mih , yes, that's where R_LIBS is set. 
On R console, .libPaths() command tells you where the packages are installed. You can even specify a custom path where you want R to install the packages - .libPaths("/path/to/install")

**Comment by mih** [comment]
@akashrajkn Thanks. Looking at this further, it seems that JASP is overwriting the default behavior of how R looks up libraries. As on Debian I can already rely on the presence of all required component (ensured via the package manager), it seems that I could just disable the entire environment setup. In doing so, R used in JASP would behave just like regular R.  Is there anything that would speak against that kind of thing?

**Comment by mih** [comment]
FTR: I have added this patch: https://github.com/neurodebian/jasp-desktop/blob/debian/debian/patches/no_custom_env

It minimizes the impact on a particular systems setup, and allow JASP to benefit from user-installed packages.

**Comment by joucoski** [comment]
@mih thanks for the help, I also have the same problem.
I accessed the https://github.com/neurodebian/jasp-desktop/blob/debian/debian/patches/no_custom_env  but I do not know how to use it.
Could you tell me how I use it in my JASP? Do I need to compile it or something like that?

**Comment by mih** [comment]
@joucoski Yes, the patch would need to be applied to the source and JASP needs to be built from the patches source tree.

**Comment by mih** [comment]
Updated list to reflect the fact that JASP doesn't start without `rjson` anymore.

**Comment by AlexanderLyNL** [comment]
See flatpack 

https://jasp-stats.org/linux-installation-guide/
