### ISSUE TITLE
[Debian] embedded-library: libjsoncpp

### ISSUE THREAD

**Issue by mih** [jasp-stats/jasp-desktop#1476]
```
E: jasp: embedded-library usr/lib/JASP/JASPEngine: libjsoncpp
N: 
N:    The given ELF object appears to have been statically linked to a
N:    library. Doing this is strongly discouraged due to the extra work needed
N:    by the security team to fix all the extra embedded copies or trigger the
N:    package rebuilds, as appropriate.
N:    
N:    If the package uses a modified version of the given library it is highly
N:    recommended to coordinate with the library's maintainer to include the
N:    changes on the system version of the library.
N:    
N:    Refer to Debian Policy Manual section 4.13 (Convenience copies of code)
N:    for details.
N:    
N:    Severity: serious, Certainty: possible
N:    
N:    Check: binaries, Type: binary, udeb
N: 
```

**Comment by mih** [comment]
This seems to be correct. There are substantial differences to the recent jsoncpp library, but this must have started out as a convenience copy.

Are their any plans to rectify this?

**Comment by mih** [comment]
FTR: This copy seems to be at least three years old. It pretty much hasn't seen any updates since. Looking at https://github.com/open-source-parsers/jsoncpp there are hundreds of changes in the same time, and about 200 issues closed.

From an blunt attempt to replace the embedded code with the current version in Debian I see only

````
/home/mih/debian/jasp/git/build/JASP-Desktop/../../JASP-Desktop/mainwindow.cpp:476: undefined reference to `Json::Value::operator=(Json::Value const&)'
````

There may be more, but it is not *that* bad.

**Comment by mih** [comment]
@boutinb FTR this is not a Linux issue. It simply points out that JASP uses and outdated fork of libjsoncpp.

**Comment by boutinb** [comment]
@FransMeerhoff Can you have a look at this issue?

**Comment by akashrajkn** [comment]
Now `libjson` is dynamically linked (#1989)
