### ISSUE TITLE
[Debian] JASP core dumps on load of two example datasets

### ISSUE THREAD

**Issue by mih** [jasp-stats/jasp-desktop#1478]
File -> Examples -> Tooth Growth
File -> Examples -> Kitchen Rolls

immediately yields a core dump:

```
jasp: ../nptl/pthread_mutex_lock.c:82: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
[1]    32621 abort (core dumped)  jasp
```

all other examples load fine.

Using a build of 962a1bfa2289872a134e9d25c18c698a04b26e05

**Comment by boutinb** [comment]
Does this problem still occur?

**Comment by mih** [comment]
With v0.8.1.0 all examples load fine.
