### ISSUE TITLE
[Debian] embedded-library: base64

### ISSUE THREAD

**Issue by mih** [jasp-stats/jasp-desktop#1480]
At first glance, also modified, e.g.:

```
% diff -u JASP-Common/base64/cencode.h /usr/include/b64/cencode.h
--- JASP-Common/base64/cencode.h    2016-09-20 12:50:12.738203716 +0200
+++ /usr/include/b64/cencode.h  2010-06-15 11:56:08.000000000 +0200
@@ -18,12 +18,11 @@
    base64_encodestep step;
    char result;
    int stepcount;
-   const char *encoding;
 } base64_encodestate;

-void base64_init_encodestate(base64_encodestate* state_in, const char *encoding);
+void base64_init_encodestate(base64_encodestate* state_in);

-char base64_encode_value(char value_in, const char *encoding);
+char base64_encode_value(char value_in);

 int base64_encode_block(const char* plaintext_in, int length_in, char* code_out, base64_encodestate* state_in);
```

**Comment by boutinb** [comment]
@aknight1-uva Can you have to this issue? You made also an issue about encoding problem.

**Comment by aknight1-uva** [comment]
Almost certainly redundant: The only use for these functions is in the RBridge.
It's not as if these functions were built for general use: They are only intended for use within JASP. 
Why these functions exists at all is a puzzle to me: Base 64 encoding functionality  is available in the QT library: http://doc.qt.io/qt-4.8/qbytearray.html.

**Comment by AlexanderLyNL** [comment]
See flatpack instructions

https://jasp-stats.org/linux-installation-guide/
