### ISSUE TITLE
[Debian] make R-based tests fail on failure

### ISSUE THREAD

**Issue by mih** [jasp-stats/jasp-desktop#1481]
The following command will always succeed (return value 0), regardless of whether the executed tests fail.

`JASP-Tests % R --no-save --no-restore -f run_tests.R`

This makes it unsuitable for automated tests, which rely on a non-zero return value if any tests fail.

**Comment by akashrajkn** [comment]
@TimKDJ since you are working on unit-tests can you take a look at this?
