### ISSUE TITLE
Feature request for more complete Bayesian ANOVA

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1482]
@mmarsman1 @raviselker 
Email from a journal editor:
"If I’m not missing something, I would like to suggest a simple addition to JASP that is very important to me when I use the program. For the Bayesian ANOVA, I think one doesn’t get the N and the means. I then do a regular ANOVA in JASP to get the means, but it’s not as comforting. For me, seeing the N and means come out of the same analysis that produces the F values, etc., is my way of checking that the program seems to be working on the right data with means that can be checked against other ways of processing the same data (e.g., to be sure that I selected the right columns of data for the analysis).  Am I missing a way to get it?"

As far as descriptive options are concerned (plots, means, etc) we want to have the same information in the classical ANOVAs as in the Bayesian ANOVAs. Hopefully this is just a case of copy-pasting the relevant code from classical to Bayesian. There's a few other people who might help out.

**Comment by TimKDJ** [comment]
Descriptives were added in PR #1603
