### ISSUE TITLE
Reshaping data between long/wide formats

### ISSUE THREAD

**Issue by ghost** [jasp-stats/jasp-desktop#1483]
Hello,

We currently can't input datas directly into Jasp (i.e. we have to use a .csv file) and I remember a post saying that this feature is on the to-do list.

I was wondering if it was possible to also add the possibility to reshape datas. Inputing datas and switching between long / wide format with ease would be very much appreciated by the students.

And keep up the good work, Jasp is a big success in my classroom mostly because of its ergonomy.

Sincerly

**Comment by boutinb** [comment]
@Indycool What do you mean: which format do you want to use as input. Currently we support CSV & SPSS files. In the near future we plan to support also ODS format.

About long format, we are considering also to support it, but not in the near future. We have to take care of performance issues.

Kind regards

**Comment by boutinb** [comment]
We have implemented data & label editing in the version (0.8.1). Does this answer your issue?

**Comment by AlexanderLyNL** [comment]
Sync data and compute column implemented

https://jasp-stats.org/download/
