### ISSUE TITLE
Text copied from annotations

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1497]
When I copy sentences from annotated JASP text, these often contain some unusual characters. For instance, a url looks like this: https://stat.ethz.ch/R-manual/R-devel/library/lattice/html/singer.html

It appears that every period is preceded by a backslash. I have not encountered that when copy-pasting from html output before...
E.J.

**Comment by boutinb** [comment]
Duplicate with #1138
