### ISSUE TITLE
Module ribbon not automatically activated upon loading old JASP file

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1501]
@akashrajkn @FransMeerhoff 
Suppose I have used the SumStats module to produce some results. I save the file, and later open it again. Now I see the output, and if I click on it, the SumStats options pop back up and I can adjust my analyses. So far so good.
However, the menu on the ribbon only shows "Common", even though I'm clearly working in SumStats. If I go to the module menu, it says that the SumStats module is not loaded, even though that is clearly the case. See screenshot for proof

![image](https://cloud.githubusercontent.com/assets/8603015/19153379/9ef52a60-8bd6-11e6-85e9-aa67872dfede.png)

**Comment by FransMeerhoff** [comment]
@akashrajkn, @EJWagenmakers,
This one seems familiar.
Akash, I will take care of this one.

**Comment by boutinb** [comment]
This is solved.
