### ISSUE TITLE
Bug in SumStats

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1502]
@akashrajkn @AlexanderLyNL 
This bug may have been solved after the most recent bug was addressed. At any rate, I wanted to report is because it is important. Suppose I run a t-test in SumStats. I keep BF10, and I use n=27, t=0.22 in a paired t-test (the one-sample test shows the same thing I believe). The plot and the numbers appear to be correct. The BF10 =0.208. Then I do a one-sided test where the alternative hypothesis specifies a positive effect. This helps H1 and the new BF10 is 0.243. However, the plot and the Savage-Dickey density ratio are incorrect. In the unrestricted case, the posterior should be much higher than what it is; the ratio between prior and posterior height should be a factor of 4, and it's clearly not. Another way of putting it: for the unrestricted case, the height of the posterior distribution at delta=0 is slightly higher than 2. After restricting the posterior, it is now _lower_ than 2. That should not happen. So something is wrong with the renormalization. I will send the jasp file by Email. Again, perhaps this is already addressed when we solved the last bug. Please let me know. 

E.J.

**Comment by akashrajkn** [comment]
Pull request: #1504 solved this bug.
