### ISSUE TITLE
Is JASP's Exploratory Factor Analysis Maximum Likelihood or Principal Axis Factoring?

### ISSUE THREAD

**Issue by lebegs** [jasp-stats/jasp-desktop#1503]
Hi. 

Brilliant piece of software but I'm bothered by not knowing what fitting procedure/extraction method does the EFA in Jasp use?  My limited understanding of EFA suggests its should be either Maximum Likelihood or Principal Axis Factoring. 

Thanks in advance,
Grateful stressed PhD student

**Comment by Suggestions-Only** [comment]
It's neither. When the option isn't specified in R (which JASP's engine is coded in), the default is a method called Minimum Residual.

**Comment by Suggestions-Only** [comment]
I believe it's also called Ordinary Least Squares?

**Comment by lebegs** [comment]
Yeah I looked it up, it is and its seemingly a good fit for my data so I get to drop SPSS for this analysis. Thanks for the info!

**Comment by lebegs** [comment]
Hi, 
@boutinb @jonathon-love @doramatzke  @SachaEpskamp 

I have another related EFA  question which I'd be hugely grateful if anyone can shed some light on. It needs a little preamble: 

Parallel analysis suggests I retain 6 factors (using O'Connors syntax for SPSS https://people.ok.ubc.ca/brioconn/nfactors/nfactors.html).

PA of the same data in JASP suggests 5 factors.

I suspected the discrepancy may be due to the PA parameter setting in spss. However, tinkering with these doesn't work; the numbers don't change irrespective of change in n datasets, seed, or whether I specify PA raw data permutations or normally distributed random data. 

Note I don't change the percentile in SPSS as I know JASP is set at @95th.
Does anyone know why there would be a difference here?

When parameters are kept constant as poss  -   Unweighted Least Squares (equivalent to MinRes in JASP I believe) , Direct Oblimin (delta:0) and .4 cut off. Following  Jasp's PA I get a nice clean, theoretically-sensible solution in a few iterations. If I follow SPSS's  PA  I start out with a similar solution but after a few iterations I end up with a much less coherent solution.

Any explanations very welcome! thanks in advance

**Comment by Suggestions-Only** [comment]
The O'Conners syntax only does parallel analysis for either principal components analysis or principal axis factoring (a specific method of factor analysis).  Differences between parallel analyses (JASP vs. SPSS) will likely represent small differences in the way factors are extracted for each method.  Also, with large sample sizes (N around 1000), parallel analysis will overestimate the number of factors (typically by one) that should be extracted.  In other words, if fewer factors make more sense theoretically, go with that solution.  Parallel analysis just gives you a helpful max to start from.
