### ISSUE TITLE
Issue with split plot in descriptives

### ISSUE THREAD

**Issue by ojr23** [jasp-stats/jasp-desktop#1506]
I just got the below error when trying to use the plot function in descriptives. Possibly because it is not possible to split a plot if the splitting variable has uneven numbers in each group?

"This analysis terminated unexpectedly. Please contact its author.\n\nError in data.frame(group = group, y = y) : \n  arguments imply differing number of rows: 133, 131\n"

![image](https://cloud.githubusercontent.com/assets/5824361/19188065/34a01ec0-8c87-11e6-8cf2-ab75b65d5117.png)

**Comment by vankesteren** [comment]
Hi ojr23, 

thank you for your message! The issue you mentioned is not caused by uneven numbers in each group, but probably by missing values in your original data. I will fix this asap.

**Comment by ojr23** [comment]
Ah, yes, that is exactly the cause. It works if I remove the missing cases.
Thanks
