### ISSUE TITLE
Error in running Bayesian ANCOVA

### ISSUE THREAD

**Issue by Louise-AnnLeyland** [jasp-stats/jasp-desktop#1513]
I am using version 0.8.00 of JASP to conduct Baysian ANOVAs.  I have covaraites, a fixed factor and the DV in the corresponding boxes abd the output states 'This analysis terminated unexpectedly. Please contact its author.\n\nError : map::at\n'.  Please let me know if you need any more information!

**Comment by FransMeerhoff** [comment]
Hello @Louise-AnnLeyland 

Can you send us the JASP file or data file? You can do this by adding it to this issue in github as zip file or send it directly to F.A.M.Meerhoff@uva.nl as attachment.

Kind Regards
Frans Meerhoff

**Comment by boutinb** [comment]
Reopen this issue, if it still occurs (and send the JASP file).
