### ISSUE TITLE
Error in repeated-measures ANOVA

### ISSUE THREAD

**Issue by Anna-LenaSchubert** [jasp-stats/jasp-desktop#1514]
I tried to run a 3 x 3 x 2 x 2-repeated measures ANOVA and received the following error msg:

> This analysis terminated unexpectedly. \n\nError in 'row.names'<-.data.frame'('_tmp_', value=value)
> :\n duplicate row.names are not allowed\n

After restarting and trying to run the analysis again, I get the following error msg:

> Error in (is.finite(value)) return(value): argument is of length zero

Windows 10, JASP version 0.8.0.0

**Comment by FransMeerhoff** [comment]
Hello @Anna-LenaSchubert 

Can you please send us the data file, or the jasp you are using?
You can do this by uploading this file in github (as zip or txt)
Or send it directly as attachment to F.A.M.Meerhoff@uva.nl

Kind regards
Frans Meerhoff

**Comment by edand** [comment]
Same for me : 
working on JASP 0.8.0.1, running repeated measures ANOVA (4 factors, total of 36 levels)
have been running this same analysis for a few days now with no errors, 
today it started terminating, even when running on different datasets. 
No problem to load old analyses, but can't re run them although using the exact same method. 

Error: 
This analysis terminated unexpectedly.

Error in if (is.finite(value)) return(value) : argument is of length zero

To receive assistence with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by edand** [comment]
In addition, a small bug which has been consistent over the past week, 
When I conduct a 4-way repeated measures analysis, and insert the repeated measures cells - 
usually, I am not able to insert the variables using the arrow right away..
It seems that the levels of the 4th factor are accidentally connected to the 3rd variable, and the levels that were inserted as levels for the 4th factor- disappear. 
So what I had to do was insert the variables as desired-> press ok (closes the analysis window) -> reopen the repeated measures analysis -> correct the levels for factors 3 & 4 -> drag the variables into the fitting cells-> run analysis.

**Comment by FransMeerhoff** [comment]
Hello @edand 

Thanks for your reporting.
Can you please send us the data files, or the jasp files you are using?
You can do this by uploading this file in github (as zip or txt) in this issue.
Or send it directly as attachment to F.A.M.Meerhoff@uva.nl

@JohnnyDoorn 
Can you please take a look at this issue?

Kind regards
Frans Meerhoff

**Comment by edand** [comment]
Sent by mail. Thanks!

**Comment by FransMeerhoff** [comment]
@JohnnyDoorn 

Hi Johnny, here's the attached cvs file hat eland send me.
[JASP_4way_repeatedanova.txt](https://github.com/jasp-stats/jasp-desktop/files/686839/JASP_4way_repeatedanova.txt)

@edand 
Thanks again for your assistance 

attached the csv file, 
the levels are : 

Side
   Right
   Left
Time
   Pre
   Post
Treatment
   LR
   SHAM
   RL
Window
   Win1
   Win2
   Win3


The described error stopped appearing when I closed and opened JASP, 
Yet the issue with inserting the levels of the 3rd and 4th factors is consistent. 


Thanks in advance ! 

Edan.

**Comment by FransMeerhoff** [comment]
@Anna-LenaSchubert 

Please reopen this issue if this issue is not solved for you in the latest version

Kind Regards
Frans Meerhoff
