### ISSUE TITLE
Problems changing measurement level

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1516]
@FransMeerhoff @boutinb 
Feedback from the twitterverse:
"tried it out this morning. I'm not able to change the level of scale (nominal,...) of variables. works with previous version." I checked this myself and also encounter problems. For me it works sometimes, but not smoothly, and sometimes not at all.
E.J.

**Comment by FransMeerhoff** [comment]
@aknight1-uva 
Do you know if we changed something here with respect to the spss import?

**Comment by aknight1-uva** [comment]
Yes and No: The importer now applies as the (value) labels (for both ordinal and nominal columns), producing a readable result. However the last version didn't do that. This version can "reinvent" data values when importing floating point ordinal/nominal columns.

**Comment by boutinb** [comment]
@EJWagenmakers Can you give us a file you work with, and what you do exactly so that we can reproduce it.

**Comment by EJWagenmakers** [comment]
Every file has this problem. I can demonstrate today.
EJ

**Comment by boutinb** [comment]
I think this has been solved already. I cannot reproduce it.
