### ISSUE TITLE
Windows 10, Jasp doesn't run....

### ISSUE THREAD

**Issue by Hello44** [jasp-stats/jasp-desktop#1520]
Jasp doesn't make anything since the last update of Window 10. (13/10/2016). I can open Jasp, but it's impossible to make the analyses.
Can you help me ?
Thank You !

**Comment by FransMeerhoff** [comment]
Hello @Hello44 

We do not know the cause of this problem but can you try the following in advance:
Uninstall the latest version of Jasp from the Control Panel.
Install the latest JASP version again from https://static.jasp-stats.org/JASP-0.8.0.0-Setup.exe
I hope this will solve your problem.

Regards
Frans Meerhoff

**Comment by Hello44** [comment]
I juste restart , then restart my computer, window 10 finishs installing something, and..... it's ok ! It was only a problem with window 10. Thank you, and sorry to disturb you...
