### ISSUE TITLE
Nominal, ordinal

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1521]
From the forum, a legitimate gripe:
"Thanks. Yes, a regular histrogram would be great. I can make JASP do it if I change the variable to ordinal, but that rounds all my data and doesn't seem to be the right approach. By the way, once I change it to ordinal, it permanently changes the data and there is no way to change it back to continuous. Seems like a big inconvenience."
The rounding is an issue, and not being able to go back to continuous is another.
Cheers,
E.J.

**Comment by boutinb** [comment]
@EJWagenmakers I have changed this behaviour so that data are not changed when you change their type.
