### ISSUE TITLE
OSF integration issues v0.8.0.0

### ISSUE THREAD

**Issue by cehartwright** [jasp-stats/jasp-desktop#1543]
Hello.

I'm using JASP v.0.8.0.0 on various macs running OS X El Capitan. I've noticed a couple of minor issues with the integration between JASP and OSF. 

First, when trying to open files in the OSF through JASP, it seems that JASP can only detect a limited number of directory levels (but this seems intermittent). For example, in my OSF, I have my overarching project > component 1 > subcomponent 1. Sometimes, it doesn't show subcomponent 1 so I cannot navigate to the contents there. Sometimes it will show subcomponent 1. I think this happens when I've navigated into the directory, then come back up a level, then gone back to look for it.

Second, when saving a .JASP file directly to the OSF (in JASP using 'save as' > OSF), if you have a results table or figure that is wider than the JASP window, only what was visible in the JASP window will be viewable if then logging directly into the OSF. No issue with downloads, but it's a pain that, at the moment, anyone looking at my OSF page can only see partial tables/figures. See screenshot for example. 
![screen shot 2016-11-10 at 11 30 13](https://cloud.githubusercontent.com/assets/23379111/20175121/1bc99fa8-a739-11e6-9949-0b90481a7c1d.png)

Hope you can help!

Charlotte

**Comment by boutinb** [comment]
Sorry for the late answer. The first issue is solved with the newest version (0.8.1).
For the second issue, this is in fact an OSF issue, and I made request to OSF to solve it.

**Comment by boutinb** [comment]
@cehartwright OSF has solved the second problem.
