### ISSUE TITLE
Citation should be corrected

### ISSUE THREAD

**Issue by mjnsr** [jasp-stats/jasp-desktop#156]
In order to use the correct citation, I have clicked the "Cite" button on top of the analysis output in JASP. Next to other papers, this provided me with the following:

Rouder, J. N., Speckman, P. L., Sun, D., Morey, R. D., & Iverson, G. (2009). Bayesian t-tests for accepting and rejecting the null hypothesis. Psychonomic Bulletin & Review, 16, 752-760

In an attempt to download the paper, I went to the journal website and found this paper:

Wetzels, R., Raaijmakers, J. G. W., Jakab, E., & Wagenmakers, E.-J. (2009). How to quantify support for and against the null hypothesis: A flexible WinBUGS implementation of a default Bayesian t test. Psychonomic Bulletin & Review, 16(4), 752–760. doi:10.3758/PBR.16.4.752

Guessing from title you probably refer to this:

Rouder, J. N., Speckman, P. L., Sun, D., Morey, R. D., & Iverson, G. (2009). Bayesian t tests for accepting and rejecting the null hypothesis. Psychonomic Bulletin & Review, 16(2), 225–237. doi:10.3758/PBR.16.2.225

**Comment by jonathon-love** [comment]
Thanks for the report!
I've implemented the fix, and it will be in our next release.
Really appreciate you taking the time to report this!
