### ISSUE TITLE
No stat called Statİdentity

### ISSUE THREAD

**Issue by ecaybek** [jasp-stats/jasp-desktop#1560]
Hi,
I try to run Principal Component Analysis and Exploratory Factor Analysis, but I'm keeping get "no stat called Statİdentity" error.

![jasperror](https://cloud.githubusercontent.com/assets/13003352/20725915/23eeb748-b67c-11e6-96cc-677f573e1e15.png)

Jasp 0.8 under Xubuntu 16.04.1 LTS

Windows version runs smoothly though.

Thanks.

Edit: I've tried on Ubuntu 16.04.1 LTS and it works perfect. Linux Mint Xfce and Xubuntu give same error, even with the clean install.

**Comment by FransMeerhoff** [comment]
Hi @ecaybek 

Thanks for your investigation so far.
We will try to find the cause of this problem to.
Our policy at the moment is to test JASP release versions thoroughly only on  Ubuntu LTS (Xenial at this moment) and Windows, Mac OS.

Kind Regards
Frans Meerhoff

**Comment by boutinb** [comment]
Hi @ecaybek 
I have seen this issue also here: http://stackoverflow.com/questions/35051374/error-statidentity-is-not-an-exported-object-from-namespaceggplot2-when-ca
Can you try to check if it is not a problem of the version of ggplot or ggmap?
Kind regards,
Bruno

**Comment by ecaybek** [comment]
@FransMeerhoff and @boutinb thank you for your answers.

Installing devtools didn't help at all. But after so many distros and installations, finally I've tried that I should have tried at the first place.

`LC_ALL=C JASP` fixed it for Ubuntu 16.04 LTS. 

Now I'm going to try it for Xubuntu too. I'll let you know about the result.

Best regards,
Eren.
