### ISSUE TITLE
QQ plot in repeated measures ANOVA

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1566]
From the forum:
"Also, in the repeated measures ANOVA tab the Q-Q plot assumption is missing (but in the ANOVA tab it is there)."

**Comment by FransMeerhoff** [comment]
@JohnnyDoorn 

Hi Johnny, Is there a special reason for this,
Or should we put this on the list ?

Gr. Frans

**Comment by boutinb** [comment]
Duplicate of #848
