### ISSUE TITLE
Compute and transform function

### ISSUE THREAD

**Issue by ItsaraBoonyarit** [jasp-stats/jasp-desktop#1567]
JASP is ofne of the great and easy to use program I recommend to my undergraduate and research students. It is basically easy to teach coupled with handed-Calculation in my statistics course. However, it would be great if it has a function likes transform  and compute variable which we can editing the variables before further analysis.

**Comment by FransMeerhoff** [comment]
Hi @ItsaraBoonyarit 

Thanks a lot for using JASP and your suggestion.
We are indeed currently busy with a version that makes it possible to edit variables and data.
These options will be implemented in JASP version 0.8.1, with expected release date end of January 2017. (There will be 0.8.0.x versions in between coming soon)

Kind Regards
Frans Meerhoff
