### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by HelenSteingroever** [jasp-stats/jasp-desktop#1570]
When I wanted to open a recent JASP file with an older JASP version, I got the error message "Unable to open file. The file version is to new. Please update to the latest version of JASP to view this file." "to new" should be "too new" (maybe the error message should also rather read "Your JASP version is too old").

**Comment by akashrajkn** [comment]
@HelenSteingroever this typo has been [rectified](https://github.com/jasp-stats/jasp-desktop/blob/development/JASP-Desktop/importers/jaspimporter.cpp#L50) in the recent versions (I think older versions - 0.7.1.x still contains the typo)
