### ISSUE TITLE
Independent T-Test distributions not updating when switching between hypothesis

### ISSUE THREAD

**Issue by mzoltak** [jasp-stats/jasp-desktop#1572]
When running a test and switching between the hypothesis to be tested, I have noticed that the prior/posterior distribution plots don't update and in the end actually crashed for me.

![image](https://cloud.githubusercontent.com/assets/24542692/21136998/4c4aefca-c128-11e6-83eb-4700056c0d64.png)

**Comment by akashrajkn** [comment]
@mzoltak 
1) Which version of JASP are you using? (On version 0.8.0.0, it works fine for me)

2) In the pic you uploaded, are you using the example dataset - Kitchen Rolls? If yes, the 'Condition' variable (grouping variable) has more than 2 levels (which is not plottable).

**Comment by boutinb** [comment]
If this issue still occur, re-open it.
