### ISSUE TITLE
Output issues in 0.8.0.0 &  0.8.0.1, and a feature request 

### ISSUE THREAD

**Issue by robustbayesian** [jasp-stats/jasp-desktop#1580]
In both versions 0.8.0.0 and 0.8.0.1 exporting the results often causes JASP to freeze. It will output a results.html.tmp file, not respond for a few moments, and then windows asks to close it for not responding. 

In any case, will there be an output option more similar to SPSS? I like how in SPSS tables can be copied or exported as pictures or as an item you can paste into excel or word. That would make working with JASP much easier. 

Thank you!

**Comment by FransMeerhoff** [comment]
Hi @vaughanbkv 

Thank you for the suggestion and the info about the export.

Some remarks
- We can only investigate the freeze of the export of the result if you will send us the jasp file that you use or give  was a reproduction path for it. We are aware of the fact that the export is sometimes very time consuming but we must be sure whats going on there. You can do this by zipping it and attach it to this issue or send it to me at F.A.M.Meerhoff@uva.nl
-Perhaps superfluous but you are aware of the fact of that you can export the data separately as  cvs file and read that in a spread sheet or word, also data that was imported from SPSS before?
- We are busy at the moment to support the export using the eps format. This will probably makes your work easier, and we expect that in the next or release after.  

Kind regards
Frans Meerhoff

**Comment by boutinb** [comment]
We cannot reproduce this problem. If it still occurs, re-open it.
