### ISSUE TITLE
Multigroup SEM

### ISSUE THREAD

**Issue by Jazwaq** [jasp-stats/jasp-desktop#1581]
Hi,

Thank you for creating a very good statistical software. I hope to see many features, such as multi-group SEM etc in future. Also it would be great to to have video tutorials(at YouTube) for each new function that is introduced.

Good luck,

Jaz

**Comment by boutinb** [comment]
@Jazwaq Thanks for your comment. We may indeed implement a multi-group SEM feature. We are also working to make new updated videos.

**Comment by SachaEpskamp** [comment]
Yes, an implementation of multi-group SEM is coming in a future version!

**Comment by vankesteren** [comment]
This has been implemented a while ago in the SEM module under the options (grouping variable). I'll close this issue.
