### ISSUE TITLE
Paired-Samples T-Test analysis termination 

### ISSUE THREAD

**Issue by JamesEBartlett** [jasp-stats/jasp-desktop#1584]
Hello, 
I attempted to do a paired samples T-Test and the following error message appears below the Results and T-Test headings: 

This analysis terminated unexpectedly. Please contact its author.\n\nError in if (options$SellkeMPR) { : argument is of length zero\n

I thought it might be because one of the rows contained zero but removing that value still produced the error message. However, if I perform a Bayesian Paired-Samples T-Test it appears to work fine. This message appears every time I try to perform the T-Test even when opening different data files. 

<img width="515" alt="screen shot 2017-01-11 at 08 47 06" src="https://cloud.githubusercontent.com/assets/20024119/21841555/909e5072-d7da-11e6-8256-e09ad8b096fb.png">

**Comment by JamesEBartlett** [comment]
Ignore this, it works fine after downloading the 0.8.0.1 update.

**Comment by FransMeerhoff** [comment]
Hi @JamesEBartlett 

Thanks for solving this by yourself and using JASP.

Cheers Frans Meerhoff
