### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by jessicaelaine24** [jasp-stats/jasp-desktop#1589]
Hi! I'm teaching with JASP in a lab of 24 computers. We were using 0.8.0.0. At the end of last semester, all the machines were functioning well. When we started lab last week, only about 6 of the 24 computers showed output. The others stayed on the Welcome screen. I thought that maybe the new version of JASP would fix the problem, so I had IT install it. Still only 6 computers show the output.

All 24 computers are running Windows7 Enterprise. Clearly something changed on the machines between the end of last term and now, but I'm not sure what. I'm going to talk to our IT department to troubleshoot as well. Do you have any potentials issues that you know might cause output to not appear?

**Comment by jessicaelaine24** [comment]
The issue resolved on its own after a series of reboots.

**Comment by boutinb** [comment]
Fine! Such a problem is always really hard to solve from far…

Kind regards,
Bruno Boutin
