### ISSUE TITLE
Descriptive Plots - New export formats..? Increase resolution of png..? 

### ISSUE THREAD

**Issue by JasperRobinson** [jasp-stats/jasp-desktop#1590]
Hi - I really like the Descriptive Plots in Jasp but I'm struggling to use them for research articles, they are a little too hazy for publication. 

If it were an easy fix, I'd really like the feature of being able to export Descriptive Plots to PDF or tiff; or perhaps it is possible to increase the default resolution for the PNG part of the Descriptive Plot (the text labels seem higher resolution). 

Thanks for everything :)

**Comment by boutinb** [comment]
@JasperRobinson Hi Jasper, We are busy to add the possibility to save images in vector format like eps (it takes a bit of time because of R upgrade issues). Would that solve your problem?

**Comment by JasperRobinson** [comment]
EPS would be FANTASTIC. All the journals that I know of accept it and it will produce beautifully clean graphs. 
BTW - the jiggle (?) feature that you get when you select error bars - so the data points sit side-by-side, rather than on top of each other - is really helpful. 

Thank you!

**Comment by vankesteren** [comment]
Thanks Jasper,

I just submitted a pull request (#1727) implementing the save image functionality. If everything goes well with testing, this will be implemented in the next release in a few weeks.

Have a nice day!
