### ISSUE TITLE
ANOVA output option

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1593]
I think we ought to have an option to display the ANOVA output with the best model on top; right now, the null model is always on top, but that model often does not do very well, so the comparison is not informative.
E.J.

**Comment by EJWagenmakers** [comment]
@TimKDJ maybe something for you to look at, as you are working on ANOVAs anyway...
@mmarsman1

**Comment by mmarsman1** [comment]
The output table is created before the analyses are run. Choosing a different order after seeing the results means that the tables change as the results come in. This would go against the way that we designed JASP output until now.

**Comment by EJWagenmakers** [comment]
The current tables can be the default. But surely we can have a tick box "Table with Best Model on Top" (or something similar) which produces the extra table? This is similar to how JASP produces figures on command. Let's discuss this live.

**Comment by mmarsman1** [comment]
Sure. 
I actually still think that we need to redo the analysis. With three factors, there are 18 models compared (most of which does not interest the analyst, I hope); producing long and unreadable tables, and requiring the user to calculate things by hand (as all models are compared to null). With focused analysis these issues do not play a role.

**Comment by EJWagenmakers** [comment]
Absolutely. It would be nice if the user could do follow-up targeted analyses and select specific models. Actually, we need that for regression as well! Let's sit down with @TimKDJ  and work this out. On a related note, @FransMeerhoff, it would be nice if JASP could produce tables with an alternating pattern of shaded rows for increased visibility. This could be an output option under "general settings", as as exact vs thresholded p-values, font size, etc.

**Comment by mmarsman1** [comment]
Awesome. We have meeting with @TimKDJ if I recall correctly, let's discuss this then.

**Comment by TimKDJ** [comment]
Yes, we have a meeting next week. I'll add the items to the to-do list we created in the last get-together.

**Comment by boutinb** [comment]
This has been solved by #1712
