### ISSUE TITLE
create new variables ??

### ISSUE THREAD

**Issue by vpillaud** [jasp-stats/jasp-desktop#1605]
Hi guys, 
I'm just wondering how can I create a new variable (the sum of three other variables or anything else), surprised not to be able to find any ways to do it. This is not possible so far ?

**Comment by boutinb** [comment]
Hi @vpillaud : over some weeks we will will deliver a new release, with the possibility to synchronize your data in Excel or LibreOffice (or any Spreadsheet tools), with the data read by JASP. In this way you will be able to do all manipulation you like with the spreadsheet tool you like, and see immediately the results in JASP.

**Comment by vpillaud** [comment]
Hi, thanks for your answer. Would be super convenient to be able to merge several variables into one or recode one into another without being forced to switch to excel. Thanks for developping this, teaching stats using this software and gotta say its 16548161% better than R.

**Comment by boutinb** [comment]
Hi @vpillaud Label feature is coming soon also!
