### ISSUE TITLE
Robust correlations

### ISSUE THREAD

**Issue by IndrajeetPatil** [jasp-stats/jasp-desktop#1606]
Hi,

Although it has been argued that Spearman's rho (versus Pearson's r) can protect us from false positives when there are univariate outliers, this measure is still susceptible to false positives when there are bivariate outliers present (http://journal.frontiersin.org/article/10.3389/fpsyg.2012.00606/full). 

Pernet and colleagues have provided some options to remedy this situations in their toolbox for MATLAB (https://sourceforge.net/projects/robustcorrtool/) and I was wondering if it'd be possible to assimilate these correlations in future editions of JASP.

Thanks.

**Comment by boutinb** [comment]
@EJWagenmakers : do you have an answer for this issue?

**Comment by EJWagenmakers** [comment]
Yes, were are considering to add robust methods to JASP in the future, not just for correlations but for other measures too. Note that we do have Kendall's tau in there already, and Spearman's rho too (albeit only the classical version; the Bayesian version is soon to follow). I personally prefer these rank-based methods over anything else, but I accept that there is a useful place for robust methods, and they deserve more attention.
Cheers,
E.J.

**Comment by AlexanderLyNL** [comment]
Kendall's tau, Spearman rho all implemented. A Bayesian version of Spearman is almost done, Bayesian Kendall's tau already implemented.
