### ISSUE TITLE
Extra options analyses window

### ISSUE THREAD

**Issue by raviselker** [jasp-stats/jasp-desktop#161]
If I do a two finger click on a mac (right click on windows) in the analyses window, I get some extra options (see screenshot). If I click "Go Back", I cannot perform any new analyses anymore until I click "Go Forward" again. It's probably best to remove these options all together.

![screen shot 2015-01-10 at 20 57 51](https://cloud.githubusercontent.com/assets/4669197/5693010/5e207bbc-990b-11e4-817e-c2555aec5a12.png)

**Comment by jonathon-love** [comment]
i use these options fairly regularly, so i like them in there - but if you do a "release build" this menu is automatically disabled.
