### ISSUE TITLE
Bug report upgrade

### ISSUE THREAD

**Issue by ulrichdettweiler** [jasp-stats/jasp-desktop#1610]
Hi, just upgraded JASP on MacOS Sierra and got the attached error code. Sorry to bother you. U
<img width="1262" alt="screenshot_16" src="https://cloud.githubusercontent.com/assets/25491193/22525142/66de5cb2-e8c6-11e6-8e68-956569f78833.png">

**Comment by boutinb** [comment]
Hello @ulrichdettweiler 
Can you try to start JASP in this way: open a terminal, type "cd /Applications/JASP.app/Contents/MacOS", and type "./JASP"
This should start JASP and prints some logs on the terminal. Can you send us what is the log?

Kind regards,
Bruno

**Comment by ulrichdettweiler** [comment]
Hi. I have slteady deinstalled the update in order to work with the old version. Do you want me to reinstall it again and start it then from the terminal?
Best wishes. Ulrich


Von Samsung Mobile gesendet



-------- Ursprüngliche Nachricht --------
Von: bruno boutin <notifications@github.com>
Datum: 02.02.2017 17:49 (GMT+01:00)
An: jasp-stats/jasp-desktop <jasp-desktop@noreply.github.com>
Cc: Ulrich Dettweiler <ulrich.dettweiler@uis.no>,Mention <mention@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-desktop] Bug report upgrade (#1610)



Hello @ulrichdettweiler<https://github.com/ulrichdettweiler>
Can you try to start JASP in this way: open a terminal, type "cd /Applications/JASP.app/Contents/MacOS", and type "./JASP"
This should start JASP and prints some logs on the terminal. Can you send us what is the log?

Kind regards,
Bruno

-

**Comment by boutinb** [comment]
You may also install JASP 8.01 without deinstalling the old version. I am quite curious to know why the new version crashes on your computer. I have also Mac Sierra, and I don't have this problem. So if you can install the new version, start it with the command line, and tell me what the log says, that would be I hope interesting.

Kind regards,
Bruno

**Comment by ulrichdettweiler** [comment]
Hi Bruno,


here comes the log from JASP 0.8.


a10081:MacOS 2916729$ ./JASP

QObject::connect: No such signal FSBModel::hideAuthentication()

QObject::connect: No such signal FSBModel::hideAuthentication()

QObject::connect:  (receiver name: 'browser')

QObject::connect: No such signal FSBMExamples::hideAuthentication()

QLayout: Attempting to add QLayout "" to BackStageWidget "backStage", which already has a layout

QLayout: Attempting to add QLayout "" to VariablesWidget "variablesPage", which already has a layout

subprocess started

subprocess started

subprocess started

subprocess started

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"{\n   \"messages\" : [\n      \"Package qgraph is not the correct version; expected: 1.3, installed: 1.3.3\",\n      \"Package vcdExtra is not the correct version; expected: 0.6-3, installed: 0.6-1\"\n   ],\n   \"official\" : false\n}\n\n"



________________________________
Fra: bruno boutin <notifications@github.com>
Sendt: 2. februar 2017 17:49
Til: jasp-stats/jasp-desktop
Kopi: Ulrich Dettweiler; Mention
Emne: Re: [jasp-stats/jasp-desktop] Bug report upgrade (#1610)


Hello @ulrichdettweiler<https://github.com/ulrichdettweiler>
Can you try to start JASP in this way: open a terminal, type "cd /Applications/JASP.app/Contents/MacOS", and type "./JASP"
This should start JASP and prints some logs on the terminal. Can you send us what is the log?

Kind regards,
Bruno

**Comment by ulrichdettweiler** [comment]
And here comes the log from 0.8.1

Surprisingly, most function seem to work now.


a10081:MacOS 2916729$ ./JASP

QObject::connect: No such signal FSBModel::hideAuthentication()

QObject::connect: No such signal FSBModel::hideAuthentication()

QObject::connect:  (receiver name: 'browser')

QObject::connect: No such signal FSBMExamples::hideAuthentication()

QLayout: Attempting to add QLayout "" to BackStageWidget "backStage", which already has a layout

QLayout: Attempting to add QLayout "" to VariablesWidget "variablesPage", which already has a layout

subprocess started

subprocess started

subprocess started

subprocess started

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"Warnung: Namensraum \xE2\x80\x98""BayesFactor\xE2\x80\x99 ist nicht verf\xC3\xBCgar und ist durch.GlobalEnv ersetzt worden w\xC3\xA4hrend Objekt \xE2\x80\x98\xE2\x80\x99 verarbeitet wurde\n"

"{\n   \"messages\" : [\n      \"Package qgraph is not the correct version; expected: 1.3, installed: 1.3.3\",\n      \"Package vcdExtra is not the correct version; expected: 0.6-3, installed: 0.6-1\"\n   ],\n   \"official\" : false\n}\n\n"

QLayout: Attempting to add QLayout "" to BoundAssignWidget "postHocTestsVariables", which already has a layout

child not found :  "plotWidthDescriptivesPlotLegend"  in AnalysisForm::setOptions()

child not found :  "plotHeightDescriptivesPlotLegend"  in AnalysisForm::setOptions()

child not found :  "plotWidthDescriptivesPlotNoLegend"  in AnalysisForm::setOptions()

child not found :  "plotHeightDescriptivesPlotNoLegend"  in AnalysisForm::setOptions()

child not found :  "plotWidthQQPlot"  in AnalysisForm::setOptions()

child not found :  "plotHeightQQPlot"  in AnalysisForm::setOptions()

"ymax not defined: adjusting position using y instead\n"

"ymax not defined: adjusting position using y instead\n"

"ymax not defined: adjusting position using y instead\n"

"ymax not defined: adjusting position using y instead\n"

"ymax not defined: adjusting position using y instead\n"

"ymax not defined: adjusting position using y instead\n"

"ymax not defined: adjusting position using y instead\n"

"ymax not defined: adjusting position using y instead\n"

"ymax not defined: adjusting position using y instead\n"

"ymax not defined: adjusting position using y instead\n"

"ymax not defined: adjusting position using y instead\n"

"ymax not defined: adjusting position using y instead\n"

child not found :  "effectsStepwise"  in AnalysisForm::setOptions()

child not found :  "posteriorDistributions"  in AnalysisForm::setOptions()

child not found :  "posteriorEstimatesMCMCIterations"  in AnalysisForm::setOptions()

"Callback 1 : 0.00430202484130859 \n"

"Callback 2 : 0.350193977355957 \n"

"Callback 3 : 0.0507581233978271 \n"

"Callback 4 : 0.0149049758911133 \n"

"Callback 5 : 0.00353789329528809 \n"

"Callback 6 : 0.000946044921875 \n"

"Callback 7 : 0.0527389049530029 \n"

"Callback 8 : 0.0180091857910156 \n"

"Callback 9 : 0.00502276420593262 \n"

"Callback 10 : 0.00104403495788574 \n"

"Callback 11 : 0.0526690483093262 \n"

"Callback 12 : 0.0201990604400635 \n"

"Callback 13 : 0.00288295745849609 \n"

"Callback 14 : 0.00102996826171875 \n"

"Callback 15 : 0.161988019943237 \n"

child not found :  "plotWidthDescriptivesPlotLegend"  in AnalysisForm::setOptions()

child not found :  "plotHeightDescriptivesPlotLegend"  in AnalysisForm::setOptions()

child not found :  "plotWidthDescriptivesPlotNoLegend"  in AnalysisForm::setOptions()

child not found :  "plotHeightDescriptivesPlotNoLegend"  in AnalysisForm::setOptions()

child not found :  "plotWidthQQPlot"  in AnalysisForm::setOptions()

child not found :  "plotHeightQQPlot"  in AnalysisForm::setOptions()

child not found :  "plotWidthDescriptivesPlotLegend"  in AnalysisForm::setOptions()

child not found :  "plotHeightDescriptivesPlotLegend"  in AnalysisForm::setOptions()

child not found :  "plotWidthDescriptivesPlotNoLegend"  in AnalysisForm::setOptions()

child not found :  "plotHeightDescriptivesPlotNoLegend"  in AnalysisForm::setOptions()

child not found :  "plotWidthQQPlot"  in AnalysisForm::setOptions()

child not found :  "plotHeightQQPlot"  in AnalysisForm::setOptions()


________________________________
Fra: bruno boutin <notifications@github.com>
Sendt: 2. februar 2017 17:49
Til: jasp-stats/jasp-desktop
Kopi: Ulrich Dettweiler; Mention
Emne: Re: [jasp-stats/jasp-desktop] Bug report upgrade (#1610)


Hello @ulrichdettweiler<https://github.com/ulrichdettweiler>
Can you try to start JASP in this way: open a terminal, type "cd /Applications/JASP.app/Contents/MacOS", and type "./JASP"
This should start JASP and prints some logs on the terminal. Can you send us what is the log?

Kind regards,
Bruno

**Comment by boutinb** [comment]
@ulrichdettweiler You mean that you have no problem anymore? It was maybe just an installation problem the first time you tried.

**Comment by ulrichdettweiler** [comment]
Hi Bruno,


the program runs smoothly now, with some errors under the way.


So a simple post-hoc test in an ANCOVA on the variable "time.point" (categorical with three values: time.point <- c("morning", "midmorning", "noon")) would not run and produce an error. Post-hoc teste on the other two categorical variables, however, are performed.

But I can easily do that in r. This was just playing around a little, and I love the convenience of JASP producing tables you can just paste into the word file.

Another thing is that JASP puts the variables in alphabetical order when plotting. That works fine with the variables season <- c("fall", "spring", "summer") describing a school year, but unfortunately not with time.point ;-) Nothing big. I just have to rename the variables or use the numerical values 8.30, 10.30 and 12.30 as ordinal variables. No worries here.


I attach screenshots from the error message adding time.point to the post-hoc section and the output without time.point post-hoc. You decide if you want to look at it or not. In case you are interested, I can send you the data file, no problem.


Best, Ulrich


________________________________
Fra: bruno boutin <notifications@github.com>
Sendt: 6. februar 2017 10:15
Til: jasp-stats/jasp-desktop
Kopi: Ulrich Dettweiler; Mention
Emne: Re: [jasp-stats/jasp-desktop] Bug report upgrade (#1610)


@ulrichdettweiler<https://github.com/ulrichdettweiler> You mean that you have no problem anymore? It was maybe just an installation problem the first time you tried.

**Comment by boutinb** [comment]
Hi Ulrich, if can send a JASP file of the error, that would eeasier for us. Coming soon: you can set labels and their order (over 2, 3 weeks).
