### ISSUE TITLE
Case numbers get mixed up in the residuals statistics?

### ISSUE THREAD

**Issue by mrgnth** [jasp-stats/jasp-desktop#1612]
Hi everyone,

I've been playing around with data in order to get a good deal on a used car and stumbled into an oddity today. Please take a look at case number 347 in the attached screenshot. The price of the car is 199, yet in the casewise diagnostics on the right the price of case number 347 is shown as 188 (this is actually the price of the car a few rows down, No. 351).

![jasp case number mixup](https://cloud.githubusercontent.com/assets/20441576/22620230/8562b2bc-eb07-11e6-8a5c-42ade6f7c042.png)

Am I missing something here?

**Comment by boutinb** [comment]
Hi @mrgnth, can you send us your JASP file? We can can search then what's happening.

**Comment by mrgnth** [comment]
[cars_cleaned.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/765111/cars_cleaned.jasp.zip)
Sorry, GitHub forced me to zip it.

**Comment by boutinb** [comment]
Hi @mrgnth We think that the mistake comes from the missing values in the gas_label column. The regression analysis cannot handle this. Can you fill in these missing values and try again?

**Comment by boutinb** [comment]
If this problem still occur, reopen this issue
