### ISSUE TITLE
A bug of Reliability Analysis

### ISSUE THREAD

**Issue by SCgeeker** [jasp-stats/jasp-desktop#1613]
Hi, 
I'm testing the teaching data for my students. In this data, there are 500 responses for each 15 questions. I will use this data explain how to exclude the inappropriate question. The 5th question is the only question to be excluded because its item-rest correlation is negative. However, JASP gave me the positive correlation for this question. The correct Cronbach's alpha is 0.835, but JASP gave me 0.907. 

The below is the item reliability statistic conducted by R CTT package:
 [1,] "Q1"  "0.595"  "0.818"
 [2,] "Q2"  "0.645"  "0.813"
 [3,] "Q3"  "0.675"  "0.812"
 [4,] "Q4"  "0.662"  "0.812"
 [5,] "Q5"  "-0.774" "0.895"
 [6,] "Q6"  "0.44"   "0.827"
 [7,] "Q7"  "0.113"  "0.84" 
 [8,] "Q8"  "0.556"  "0.82" 
 [9,] "Q9"  "0.566"  "0.818"
[10,] "Q10" "0.558"  "0.819"
[11,] "Q11" "0.557"  "0.82" 
[12,] "Q12" "0.741"  "0.807"
[13,] "Q13" "0.561"  "0.819"
[14,] "Q14" "0.542"  "0.82" 
[15,] "Q15" "0.693"  "0.81" 

And this is the [JASP output](https://osf.io/k7zp2/) and the [raw data](https://osf.io/vwbbg/). 
Wish my information could help you fix this bug. 

best wish,

**Comment by boutinb** [comment]
@vankesteren: could you check this issue?

**Comment by vandenman** [comment]
Good catch! The reliability estimate is indeed wrong because we're still using an older version of the "psych" package to calculate reliability. The most recent version of the package also returns 0.835 for Cronbach's alpha. We'll update this once we've checked for any backwards compatibility issues.

**Comment by boutinb** [comment]
This is solved in the latest version (0.8.1).
