### ISSUE TITLE
Error in JASP Output

### ISSUE THREAD

**Issue by lcoome** [jasp-stats/jasp-desktop#1615]
I noticed another error in JASP.
It re-prints the residual/error line of the ANOVA table from the within-subjects section—into the between-subjects section.
If it’s a mixed-design and there is a between-subjects IV, there’s no problem. 
![screen shot 2017-02-06 at 12 57 14 pm](https://cloud.githubusercontent.com/assets/13381277/22662681/d6baddc6-ec77-11e6-89bc-1de6dd9f9afb.png)

**Comment by JohnnyDoorn** [comment]
Hi Lindsay,
Thanks again for your help! Of course, the table shouldn't be shown when there are no between subject factors. I updated the code accordingly.
Cheers,
Johnny

**Comment by boutinb** [comment]
Fixed with the new version 0.8.1.
