### ISSUE TITLE
Variable window resets when you enter or remove a variable

### ISSUE THREAD

**Issue by awismer7** [jasp-stats/jasp-desktop#1624]
This feature request is a relatively minor request that would greatly support ease of use.

Currently, whenever you either enter a variable into an analysis or remove a variable from an analysis, your window of variables from your dataset on the left resets and goes back to the beginning. It would be much more convenient - especially for large datasets - if the window remained in the same location or moved back to the section pertaining the retained variable (as SPSS does). Most often when you are entering and removing variables you will be switching a variable out for one that is nearby in the list of variables, so this would support user functioning. 

Thank you for considering this feature request!

**Comment by boutinb** [comment]
Thanks for your remark. We will try to fix this.

**Comment by FransMeerhoff** [comment]
Hi @awismer7 

I was picking up this request, but now we do not really quite understand anymore what you ment with this request. I made a screen shot of what I tried: Switch variable from the options panel and try to reproduce that the dataset goes back to the beginning, but I couldn't. I tried this on 0.8.1.1 but I do not expect that this issue was accidentally solved. Could you explain it again? 

Kind Regards
Frans Meerhoff

![screen shot 2017-04-19 at 12 49 34](https://cloud.githubusercontent.com/assets/15656960/25176531/b39ec8e2-24fe-11e7-88c5-340f6ecd3bfd.png)

**Comment by awismer7** [comment]
Hi Frans,

Thanks for looking into my request. The issue is one that comes into play
with large datasets when you have a large number of variables in the
options window (more than in your example). Anytime you are not at the top
of the option/variable window and you add or remove a variable say to the
dependent variable slot in the ANOVA analysis, it moves the variable window
back up toward the top of the list. This can be frustrating when you are
looking at many individual variables and you want to keep looking at
variables in the same location in the variable list.

I tried to screen capture an example for you. In the top image, it shows
that I am currently looking at a DSSQ variable midway down my list of
variables. The bottom image is what happens immediately after I transfer a
variable over to the Dependent Variable for analysis. The option window
slid back up toward the top of the list and is now showing Presence
variables. The same problem occurs when I am removing a variable from the
dependent variable slot, for example. It would be more user-friendly for
the list to not move at all when adding variables, and when you remove a
variable it would be better for the window to adjust back to that
variable's location in the list. This is how SPSS is set up.

[image: Inline image 1]

[image: Inline image 2]

Does this make sense? Please let know me if you still don't quite
understand my request. Thank you again for looking into this. I am quite
pleased with JASP and thank you guys for all your hard work on it.

Sincerely,
Andrew

**Comment by awismer7** [comment]
Also, I have been using 0.8.1.1 and the issue was not accidentally solved.

Thanks

**Comment by FransMeerhoff** [comment]
Hi @awismer7 

If you still have this problem, could you please make a new issue of it?

Kind regards  
Frans Meerhoff
