### ISSUE TITLE
C Correlation: error when a variable contains infinity

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#163]
![error](https://cloud.githubusercontent.com/assets/3240247/5701944/65e38788-9a53-11e4-9e60-aa0ee30e482d.png)

**Comment by jonathon-love** [comment]
... same error with missing values

**Comment by jonathon-love** [comment]
hey, i think this fix might need a bit more love. doesn't seem to produce a complete correlation matrix when one of the variables has infinity in it.

![screen shot 2015-01-15 at 9 07 52 pm](https://cloud.githubusercontent.com/assets/3240247/5765574/fa2a6d36-9cfa-11e4-8f9d-31aa92e7ba85.png)

**Comment by quentingronau** [comment]
Hi, I will take a look at it. Maybe you could send me the ssgo-fred2 dataset so I can reproduce the output? I just have ssgo-fred, I think this is a different one.
