### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by radrian** [jasp-stats/jasp-desktop#1640]
Hello,

I tried to do some statistics with JASP 0.8.0.0 & JASP 0.8.0.1 for Windows, but I didn't get any outputs.
Do I need to install something else in my computer?

Thank you!
Adrian

**Comment by FransMeerhoff** [comment]
Hi @radrian 

To answer your question: no you do not need to install anything else on your computer. JASP uses R but the used packages are shipped with the installation. Let's focus on 0.8.0.1 to get that working
Some question in advance before we search further:
- Did you try to uninstall all previous versions and reinstall 0.8.0.1, not just by removing directories?
- I assume that JASP starts and does not crash, but does not give output on any analysis.
- Could you send us some more information of the system you are running JASP? Windows version, 32-64 bit, etc.
- Do you have also another version of R installed on your computer by yourself?

After answering your questions we could try to find a solution.
We are very close to the point of releasing 0.8.1 expected within two weeks, you could also wait for that new release of course.

Kind regards 
Frans Meerhoff

**Comment by radrian** [comment]
Hello Mr. Meerhoff,

First, I would like to thank you for your quick response.
I really enjoy JASP. I have started to use it in my research projects and I
have a submitted a paper where I cited your software.
I am thinking of using the JASP in future within the statistics and
research methods classes I teach. I teach in at a small private university
in US.

Below I have my short responses to your comments:

1. I installed all previous versions and reinstalled 0.8.0.1
2. Yes, JASP starts and does not crash (below I attached a screen picture)
3. Below you have the information about my system.
4. Yes, I have other R versions installed (see below).

I could wait until you release 0.8.1 and give you a new report.

Thank you so much!

All the best.
Adrian Rus


[image: Inline image 3]




[image: Inline image 2]



[image: Inline image 1]

**Comment by FransMeerhoff** [comment]
Hello @radrian 

First of all thanks for the nice words about JASP.
We will do all the best to help you using JASP in your research projects.

Can you try the zipped Windows installation of JASP?
This is a complete installed version of JASP that you can run by double clicking the JASP.exe from the extracted folder.
(http://static.jasp-stats.org/JASP-0.8.0.1-64-bit.zip or http://static.jasp-stats.org/JASP-0.8.0.1-32-bit.zip for 32 bit computer)? 
You can then unzip it where you want, and bypass any permission issue.

Kind regards
Frans Meerhoff

**Comment by radrian** [comment]
Hello Frans,

It works!

Thank you so much!

All the best.
Adrian

**Comment by FransMeerhoff** [comment]
Hello @radrian 

Good to hear that it works. 

Kind regards
Frans Meerhoff
