### ISSUE TITLE
Mixed Linear Models

### ISSUE THREAD

**Issue by AlessioToraldo** [jasp-stats/jasp-desktop#1643]
Hi all, I have now used JASP and it looks very promising.
As a cognitive psychologist I often use Mixed Linear Models (MLM), and was just wondering whether JASP developers see them as a priority. MLM allow one to model virtually any data set - another step would be to be able to implement non-gaussian distributions (generalized mixed linear models), but having the classical MLM in JASP would be great. I believe that MLM is exactly the analysis which would make JASP irreplaceable. If MLM were implemented (with Bayesian analyses) I would give up SPSS completely.
All the best and thank you for your beautiful program

**Comment by boutinb** [comment]
@EJWagenmakers Can you answer this?

**Comment by EJWagenmakers** [comment]
Hi Alessio,
Yes, this is high on our list. However, first we want to give more attention to ANOVA and linear regression. But I see the Bayesian and frequentist implementation of GLMMs as unavoidable and natural.
E.J.

**Comment by boutinb** [comment]
Duplicate with #1103

**Comment by ftv88** [comment]
Any updates on when you are going to add mixed models?
