### ISSUE TITLE
Decimal points in Descriptives

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1647]
From the JASP Forum: http://forum.cogsci.nl/index.php?p=/discussion/comment/9994#Comment_9994

Maybe we can add an option to Descriptives that allows the user to set the number of decimal points that are displayed.

Cheers,
E.J.

**Comment by akashrajkn** [comment]
@EJWagenmakers the descriptives code (also anova multivariate) formats only to 4 significant digits. (Other analyses use 4 significant digits and 2/3 decimal places).

1. Should this be uniform across all analyses?
2. Would a global preference to specify number of decimal points be more useful?

**Comment by EJWagenmakers** [comment]
@akashrajkn Well the example on the forum showed that the Descriptives code sometimes gives one decimal point. I guess when the numbers are large, fewer points are plotted. So I suspect it plots 1.113 but 5679 and 546.1. I like the idea of having a global preference for the number of decimal points!
E.J.

**Comment by boutinb** [comment]
Done in previous JASP version
