### ISSUE TITLE
0.8.0.1 module SEM doesn't perform analysis

### ISSUE THREAD

**Issue by pa0** [jasp-stats/jasp-desktop#1652]
Output is empty:

<img width="1163" alt="zrzut ekranu 2017-02-22 o 13 31 49" src="https://cloud.githubusercontent.com/assets/4692217/23211622/4bf45684-f903-11e6-8238-9afd8cf85d33.PNG">

Data is from example file.

**Comment by SachaEpskamp** [comment]
Hi,

You only need to enter the lavaan syntax, not other R syntax. That is, remove model = ' and the sem() call and only write:


y =~ y1 + y2 + y3
x =~ x1 + x2 + x3
y ~~ x

**Comment by pa0** [comment]
After corected code SEM still doesn't work, but in new window everything is ok.

**Comment by SachaEpskamp** [comment]
What do you mean with "in new window everything is ok"?

**Comment by pa0** [comment]
If I made mistake in SEM (as like as on screenshot) this analysis is "frozen" - corecting syntax doesn't help. Only in new analysis JASP print an output.

**Comment by SachaEpskamp** [comment]
Yes I have the same issue. We will look into it, thanks!

**Comment by dellagiulia** [comment]
Hi, I use JASP 0.8.3.1 for MAC.
SEM module doesn't perform analysis.
Please see screenshot,

![screen shot 2017-10-24 at 09 36 06](https://user-images.githubusercontent.com/33052362/31930147-f90967be-b89e-11e7-9fa3-a588dfc599d6.png)


best,
Antonio

**Comment by JanowskiMaciej** [comment]
For Windows users:
Try to write everything in the windows notepad and then paste it into Jasp. Ctrl+enter.

**Comment by AlexanderLyNL** [comment]
Hi Antonio,

Can you please zip the jasp file and upload it here? Alternatively, you can also send it to me, then I can have a look at it. 

Cheers,
Alexander

**Comment by dellagiulia** [comment]
Many thanks for your answer!

I run the SEM on my PC win10 and works perfectly.

I start to use JASP after the ECDP conference in Utrecht and I really appreciate the software!,
Best,
Antonio

**Comment by AlexanderLyNL** [comment]
Hi Antonio, 

Thanks for your encouraging words! I can't find the JASP file in this thread, could you email (a.ly@jasp-stats.org) it to me instead? 

Cheers, 
Alexander

**Comment by boutinb** [comment]
I think this issue can be closed now. If not reopen it.
