### ISSUE TITLE
Windows JASP 0.8.0.1 doesn't start JASPEngine in enterprise environment

### ISSUE THREAD

**Issue by MigTBorges** [jasp-stats/jasp-desktop#1653]
Hi,

I've recently installed version 0.8.0.1 on my laptop where JASP runs perfectly fine. However, yesterday I submitted a request for installing JASP on a work desktop machine and when I loaded up a dataset and tried running descriptives, nothing was generated in the analysis window. This was also true of every other option like ANOVAS or T-Tests.

![jasp1](https://cloud.githubusercontent.com/assets/25935887/23213116/fce61b3e-f909-11e6-85ca-1a8cc397eeea.PNG)

Trying to figure out the problem, I attempted to run JASPEngine.exe and got this error:

![jasp2](https://cloud.githubusercontent.com/assets/25935887/23213165/2a0f0bd4-f90a-11e6-8d60-c36832a9b105.PNG)

This is the message that appears now, after trying a re-install. Before re-installing, the error was different and instead said that R.dll wasn't found (even though it was there in the R subfolders).

The work environment is an enterprise environment and I'm a normal user. I've contacted the admins and with them we tried first to run JASP as Administrator and then we tried re-installing JASP to the D drive, where I have full authorization. The installation wizard doesn't give us the option to change the installation folder, however, so it got re-installed in the C drive anyway (where problems persisted, despite the error message changing as I mentioned above).

Any suggestions on other fixes I should try? I should note that not only is R.dll present in the subfolders of JASP, R.exe runs as intended.

Thanks,
Miguel Borges

**Comment by boutinb** [comment]
@MigTBorges What is exactly the operating system you use? Can you try the zipped Windows installation of JASP (http://static.jasp-stats.org/JASP-0.8.0.1-64-bit.zip or http://static.jasp-stats.org/JASP-0.8.0.1-32-bit.zip for 32 bit computer)? You can then unzip it where you want, and bypass any permission issue.
That you get an error when starting the JASP engine is not surprising: it cannot be started alone, it depends on the JASP Desktop.
Bruno

**Comment by MigTBorges** [comment]
The operating system is Windows 7 Enterprise, SP 1 64-bit.
We've just tried using the zipped installation of the 64-bit version to install to a drive where I have permission, but nothing changed: the analysis window is still not producing anything.

I've checked with another user here that has had JASP 0.8.0.1. installed on her machine, and everything seems to work correctly: analyses run and update as they should That makes it unlikely that this is an issue with permissions.
-Miguel

**Comment by boutinb** [comment]
Just to be sure: did you click on the JASP.exe of the unzipped file?
Maybe another influence would be the R installation on your computer. Do you have R installed on your work computer? If yes, which version?

**Comment by MigTBorges** [comment]
Yes, I did.
I do have R installed on my work computer, version 3.2.3, along with R Studio.  If this installation is generating some conflicts with JASP is there any way to correct them without uninstalling R?

**Comment by akashrajkn** [comment]
@MigTBorges this could happen when R_HOME is not set properly (RInside might use the R_HOME of the build machine). Could you try the following methods? -

1. Set the environment variable, R_HOME. Or
2. Uninstall RInside and re-build it on your machine

**Comment by boutinb** [comment]
@MigTBorges Another thing you can do is to install Process Explorer (https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx): with this tool you can check the environment setting of each process. Check whether the R environment settings of the JASPEngine process correspond to the JASP installation folder.

**Comment by boutinb** [comment]
@MigTBorges You can also send a screenshot of the environment settings of the JASPEngine process.

**Comment by MigTBorges** [comment]
Thank you for the replies.

@akashrajkn The process explorer shows some paths mentioning RInside, but a system search failed to show where it might be and these paths don't match my structures in my machine. How can I re-build RInside, or set the environement variable?

@boutinb The R_HOME value seems to be correctly pointing to the JASP installation folder (even when I run JASP from the D drive instead of C drive). The R_ENVIRON, however, doesn't point to the folder, how can I fix this? Do you see anything else that could be amiss?

![jasp3](https://cloud.githubusercontent.com/assets/25935887/23258038/bf9bff2e-f9c6-11e6-96f5-3dbfca915c54.PNG)

**Comment by boutinb** [comment]
@MigTBorges The environment settings prove that you have loaded the right RInside package (this package generates strange settings like R_MAKEVARS_USER). The R_ENVIRON setting is set by JASP self: this is set to an unknown place to prevent other R environment settings to interfere with the engine. Are there settings in the R_ENVIRON that are needed on your computer?

**Comment by MigTBorges** [comment]
@boutinb I don't think so. Running R Studio and examining it with the Process Explorer doesn't show a R_ENVIRON variable. What other steps could I take to verify this?

**Comment by boutinb** [comment]
@MigTBorges What is annoying, is that we cannot see the log that JASP produces on Windows. We will try to make a version that produces this log. It is now really difficult to guess what is going wrong on your computer... mostly this kind of problems is solved by using the ZIP file (a permission setting was then the problem), or by using a R setting. Hopefully it won't take too much time to make this version with log output for windows.

**Comment by boutinb** [comment]
@MigTBorges We made a Windows version that can log the output of the engines. Hopefully this can help us to find out where is your problem. This is version is here: http://static.jasp-stats.org/JASP-0.8.1.0-Setup-Special.exe
If you install this version, starts then JASP with the command prompt in this way:
 . Go to the JASP installation folder.
 . Type  JASP.exe > c:\temp\jasp.log
Hopefully this will output some useful information in jasp.log file.
This version has also the newest features of JASP! Check on the JASP site.

**Comment by MigTBorges** [comment]
@boutinb Thanks for looking into this.

I installed this version and tried to run analyses again, still running into the same problem. I followed your instructions and produced a log with this info in it:

```
{
   "messages" : [
      "Package lsmeans is not the correct version; expected: 2.17, installed: 2.20-2",
      "Package RInside not installed!"
   ],
   "official" : false
}
```
The lack of RInside might be the problem. I don't know what could be preventing it from installing.

**Comment by akashrajkn** [comment]
@MigTBorges please try installing RInside from github (source).
`
library(devtools)
install_github("eddelbuettel/rinside")
`

**Comment by MigTBorges** [comment]
@akashrajkn In installing this, how do I do it in a way that applies to JASP? Through the R.exe included in the JASP installation folder?

**Comment by boutinb** [comment]
@MigTBorges The RInside warning is unfortunately a wrong warning (it is just a case sensitivity problem when the packages are checked. We will fix this for the next release). Rinside is anyway loaded because the settings displayed by Process Explorer proves that the right Rinside is loaded.
I have just tried JASP on Windows 7 entreprise machine with a non-admin user, and it works without problem.
But I have another idea what the cause of your problem might be: to run the analyses, JASP needs to write some state in the temp folder. It needs the right to write on this temp folder. Can you check the permissions on your temp folder (apparently  c:\migbor\AppData\Local\Temp) ?

**Comment by MigTBorges** [comment]
@boutinb Checking the permissions on the Local/Temp folder (right click on Temp folder, Properties, Security tab) shows me that the SYSTEM, Admin and my own user names all have the same permissions, including Read and Write. Only unticked permission is at the end, "Special Permissions", and that's unticked for all users and groups.

**Comment by boutinb** [comment]
Hello @MigTBorges: there are least 2 other users who have the same problem as you. We have decided to publish a debug version on Windows. Hopefully this will give us more information about the problem. I give you a sign when this debug version is ready.

**Comment by boutinb** [comment]
Hello @MigTBorges Can you install the debug version http://static.jasp-stats.org/JASP-0.8.1.1-Setup-Debug.exe
Then start JASP form the command line as described above. Give me the results of the log.

**Comment by FransMeerhoff** [comment]
Hello @MigTBorges 

A new release JASP 0.8.1.2 is coming soon.
The behaviour of the Engine in combination with RInside has changed in this version.

A prerelease version Is temporary available at https://static.jasp-stats.org/JASP-0.8.1.2-Setup.exe

Could you check if this version solves your problem?

Kind regards 
Frans Meerhoff

**Comment by MigTBorges** [comment]
Hello @boutinb and @FransMeerhoff, 

My apologies for not trying out the debug solution yet. I'll be out of office for some days but I'll check back on this issue in early May and report back on the results.

Best,
Miguel

**Comment by FransMeerhoff** [comment]
Hi @MigTBorges 

If you still have this problem on the latest version JASP 0.8.3.1 
please reopen this issue.

Kind regards
Frans Meerhoff
