### ISSUE TITLE
JASP 0.8.0.1 Mac fails to launch in multi-user environment

### ISSUE THREAD

**Issue by craigrichardson** [jasp-stats/jasp-desktop#1666]
Hi There,

We've ben deploying JASP with Munki to hundreds of Macs (see https://github.com/munki/munki )

This installs JASP as the root user so the contents of the /Applications/JASP.app folder are owned by root:admin and the permissions on files/folders are 644/755 respectively.
i.e.
ls -l JASP.app/
drwxr-xr-x  7 root  admin  238  1 Dec 03:02 Contents

This is normally not a problem for applications, and JASP was no exception.  We've deployed 0.7.1.12 this way for a long time.

However we've just deployed JASP 0.8.0.1 and now when it tries to start it crashes with the attached error message (we've only tested on macOS 10.12.3).

<img width="1181" alt="screen shot 2017-03-08 at 1 22 13 pm" src="https://cloud.githubusercontent.com/assets/6346746/23687630/983eabc4-0403-11e7-8ea6-c6182f785d69.png">

If we change the owner to be a user account on the computer it will start working again for only that user - i.e. 

chmod -R username /Applications/JASP.app

However this isn't a solution or workaround as if another user then logs into the Mac they get the same crash that is in the attached image.  Bear in mind we also deploy this to computer labs, where anyone of 1000s of students on campus might login to use this.

Cheers,
Craig

**Comment by FransMeerhoff** [comment]
Hi @craigrichardson ,

Sorry to hear but thanks for reporting this. 
I agree that the 'chmod' is just a workaround and not a good solution. We are not aware of this problem yet . Can you help us with the following in advance.
If you start JASP from a terminal in /Applications/JASP.app/Contents/MacOS by ./JASP it produces some log information. Could you do that for both a 'working user' and a 'not working use'r and send us the output of both.
In a mean time we will try to reproduce this problem and try to find us what's going on.

By coincidance we are publishing a new version of JASP this week but you could already try if this version would solve your problem. It is available at http://static.jasp-stats.org/JASP-0.8.1.0.dmg
We are of course very anxious to know if this version solves your problem. (It has some nice extra features as data synchornisation and label editing and manipulation, but you will be informed on the JASP site soon about hat)  

Kind regards 
Frans

**Comment by boutinb** [comment]
@craigrichardson We could reproduce your problem, and solve it (it was a right problem in our R framework). We have just made a new mac setup for the 0.8.1.0 version. Can you try it?

**Comment by craigrichardson** [comment]
I've tested deploying 0.8.1.0 and its working fine.

Thanks!
Craig
