### ISSUE TITLE
En dash symbol does not display in plots

### ISSUE THREAD

**Issue by stjep** [jasp-stats/jasp-desktop#1669]
If an en dash (–) is assigned to a label name, it doesn't render properly in the plots, but is instead replaced with the Unicode placeholder. This is on Mac OS 10.11.6 and JASP 0.8.1.0. Screenshot attached, the label should be:

CS–

![screenshot 2017-03-10 09 59 48](https://cloud.githubusercontent.com/assets/3305421/23800001/941c8888-0578-11e7-8f35-dc239213d98d.png)

**Comment by boutinb** [comment]
@vankesteren: In a table, the dash '–' (or any special character as '±'. Be careful '-' is not a dash!) label is well displayed, proving that the engine and R get the right value. But in an image, the '–' gets the wrong value. Probably it is due to a Unicode problem when making the image.

**Comment by akashrajkn** [comment]
This does not occur on the latest release v0.9 (Tested on ubuntu). Should I close the issue?

**Comment by akashrajkn** [comment]
Fixed in #2658
