### ISSUE TITLE
Descriptives won't run if label contains en-dash

### ISSUE THREAD

**Issue by stjep** [jasp-stats/jasp-desktop#1670]
This seems linked to the issue in #1669 

Using an en dash in the label for Repeated Measures Cells results in an ANOVA that runs fine, but JASP won't give Desc reptiles for that cell (screenshot attached). Changing the cell name so that it doesn't use the en dash fixes the issue (screenshot attached).

![screenshot 2017-03-10 10 07 30](https://cloud.githubusercontent.com/assets/3305421/23800344/02d26580-057a-11e7-9e6c-c27000caa05d.png)
![screenshot 2017-03-10 10 11 47](https://cloud.githubusercontent.com/assets/3305421/23800345/02d9a494-057a-11e7-80fa-43a844e045b5.png)

**Comment by boutinb** [comment]
@JohnnyDoorn I am not sure if this is exactly the same error as in #1669. It is surely a Unicode problem, but in #1669, this problem occurs when making the image, which is an apart piece of code than when the Mean and SD are calculated.

**Comment by akashrajkn** [comment]
Fixed in #2658 and #2664
