### ISSUE TITLE
Increasing size of Scree Plot re-runs FA

### ISSUE THREAD

**Issue by stjep** [jasp-stats/jasp-desktop#1672]
Increasing the size of the Scree plot in an EFA using the drag corner causes JASP to re-run the whole EFA. This seems unintended and is annoying on two fronts:

- Dragging the bottom-right corner when the plot is already on the bottom of the output means that it only increases by a tiny amount
- Re-running an EFA with a lot of variables takes a while (~1-2 minutes)

**Comment by boutinb** [comment]
My commit fixed something else...

**Comment by vankesteren** [comment]
@SachaEpskamp would this be an easy fix?

**Comment by vankesteren** [comment]
@boutinb this issue has not been fixed yet, @vandenman referenced the wrong issue in the commit.
