### ISSUE TITLE
JASP crashes loading CSV on Windows 7 - Assertion failed 

### ISSUE THREAD

**Issue by becky-gilbert** [jasp-stats/jasp-desktop#1682]
Hi,

JASP is crashing when I try to load a csv file. The message I get is "Assertion failed!" with a program, file and line number, followed by "Expression: allocated == next_block_prev_allocated" (see screenshot below). If I click "Retry" or "Ignore" I get another error and JASP closes. I'd be happy to send the csv file.

Thanks,
Becky

## Environment 

* JASP version: 0.8.1
* OS name and version: Windows 7 (Enterprise and Professional)
* Analysis: none 

![jasp_loading_csv_error](https://cloud.githubusercontent.com/assets/9041788/23989601/fead2584-0a2a-11e7-831b-3b4ac13cf01d.PNG)

**Comment by boutinb** [comment]
@becky-gilbert Can you send me the CSV file?

**Comment by becky-gilbert** [comment]
Sent. Let me know if you don't receive it soon. 
Thanks very much!

**Comment by boutinb** [comment]
I received it, and can reproduce the error. I'll have a look to this problem.

**Comment by FransMeerhoff** [comment]
Hi @becky-gilbert 

We made a hotfix for this.
You can download it from :
https://static.jasp-stats.org/JASP-0.8.1.1-Setup.exe

Next week after more testing we will publish the fix.
We are of course very interested in the results of your testing too.

Kind regards 
Frans Meerhoff

**Comment by becky-gilbert** [comment]
Hi @FransMeerhoff 
Thanks very much for the quick fix! 
My csv file loads fine now in the hotfix version. I'm still in Windows 7 Professional.
Becky
