### ISSUE TITLE
NA in grouping variable in T-test generate error level ≠ 2

### ISSUE THREAD

**Issue by pa0** [jasp-stats/jasp-desktop#1683]
## Environment (for bugs)

* JASP version: 0.8.1.0
* OS name and version: OSX Sierra
* Analysis: Independent t-test

Grouping variable with NA aren't excluded and generate third level of variable (level ≠ 2)

<img width="541" alt="zrzut ekranu 2017-03-16 o 15 13 54" src="https://cloud.githubusercontent.com/assets/4692217/24001204/cb34c58a-0a5d-11e7-91fe-f504cb077c10.PNG">

<img width="655" alt="zrzut ekranu 2017-03-16 o 15 34 05" src="https://cloud.githubusercontent.com/assets/4692217/24001290/07464094-0a5e-11e7-8c9a-be066fcc6b91.PNG">

**Comment by TimKDJ** [comment]
Hi @pa0

Thank you for reporting this to us!
I will rectify it in a minute.

Cheers,
Tim

**Comment by TimKDJ** [comment]
Alright this is now fixed.
Our next release (due somewhere next week) will include the updated version of the t-test.

Thanks again.
