### ISSUE TITLE
Possibility to run test suite in non-interactive environment?

### ISSUE THREAD

**Issue by mih** [jasp-stats/jasp-desktop#1690]
When running `OSFTest::loginAuthenticationTest([1-7])` as part of the test suite 11 dialog popups open that need to be closed with a button click in order to continue the test run. Is there a switch that disables any interactive tests? Or can this particular test be ran without leading to this behavior?

**Comment by boutinb** [comment]
@akashrajkn Could you tackle this issue?

**Comment by akashrajkn** [comment]
@boutinb I'll solve this

**Comment by AlexanderLyNL** [comment]
This should be solved now with our flatpak solution:

https://jasp-stats.org/linux-installation-guide/
