### ISSUE TITLE
Error in Reliability test

### ISSUE THREAD

**Issue by niteshkhilwani** [jasp-stats/jasp-desktop#1693]
## Environment (for bugs)

* JASP version: Mac 0.8.1.0
* OS name and version: Mac OS
* Analysis: While performing reliability analysis on the dataset with 

- Mean: 0.009804
- Std. Dev: 0.099
- Min: 0
- Max: 1

Getting following error: 

This analysis terminated unexpectedly.
Error in min(eigens$values): invalid 'type' (complex) of argument
Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback)
.reliabilityResults(dataset, options, variables, perform)
psych::alpha(d, key = key)
alpha.1(C, R)
smc(R)
cor.smooth(R)

**Comment by boutinb** [comment]
Can you send us the csv and jasp files you use (in a zip format)?

**Comment by phehks** [comment]
I have an issue exactly same as this. I noticed that the problem only occurs when I have more than 25 items for reliability analysis.

Please advise. Thank you.

![image](https://cloud.githubusercontent.com/assets/28689487/26035868/5ebfcdaa-3906-11e7-872b-e5f724746045.png)

**Comment by vandenman** [comment]
Hi, @phehks could you perhaps send us the .csv and .jasp files you use (in a zip format)? That way we can reproduce the error and see what exactly goes wrong. An initial guess is that this error is caused by missing values.  You could try to rerun the analysis without cases that contain missing values.

**Comment by akashrajkn** [comment]
#1860 mostly fixes this issue. Please reopen the issue if an error occurs.

**Comment by phehks** [comment]
Thank you so much.
