### ISSUE TITLE
JASP quits unexpectedly repeatedly

### ISSUE THREAD

**Issue by kevinvschie** [jasp-stats/jasp-desktop#1694]
## Environment (for bugs)

* JASP version: 0.8.1.0
* OS name and version: Windows 7 Enterprise
* Analysis: none specifically

JASP used to be working just fine; analyses were running, figures were created. All of a sudden, it stopped working. Let me be clear. If I open JASP itself, it opens and I can load a new file and start running analyses. However, there is a specific .jasp-file that I did all my analyses in that will not open properly. When I click on that .jasp-file, JASP opens and the data set is loaded till 49% and then I receive the error that 'JASP.exe has stopped working'; a standard Windows error screen. For as far as I am aware no changes were made to the original data file (.csv). Also, I cannot detect any strange things in the .csv file. Hope someone can help me out here. I would rather not redo all the analyses.

**Comment by boutinb** [comment]
Can you send us the csv and jasp files (in zip format)?

**Comment by kevinvschie** [comment]
Sure, what's the email I can send it to?

**Comment by boutinb** [comment]
You can add it in the issue self. If it does not work, send it to jasp.stats at gmail dot com.

**Comment by boutinb** [comment]
I cannot reproduce your problem, JASP can load your csv or jasp file without problem. I have tried on Mac and Windows. We are busy to make a new (hotfix) release, which is already available here: http://static.jasp-stats.org/JASP-0.8.1.1-Setup.exe. Can you try it?

**Comment by kevinvschie** [comment]
That is strange. I downloaded and installed it, but keeps giving me the same error.

**Comment by boutinb** [comment]
With the last version you downloaded, you can start JASP from the command line (go to Program Files/JASP 0.8.1, and start JASP). In this way, the log will be printed in the command box. Can you send me what you see then?

**Comment by kevinvschie** [comment]
I'm not sure if this is what you require (let me know if I copied the wrong stuff):

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	JASP.exe
  Application Version:	0.0.0.0
  Application Timestamp:	00000000
  Fault Module Name:	JASP.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	000000000000d72c
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1043
  Additional Information 1:	d219
  Additional Information 2:	d219db11a6f08db5364eac20ce766f44
  Additional Information 3:	9a19
  Additional Information 4:	9a196be36ca0901736867c7bd771fc04

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by boutinb** [comment]
No this is not I wanted. You have to start JASP from the command line in this way JASP > log.txt
If you do not have write permission in this directory, use a log.txt in folder where you have this permission, for example: JASP > d:\temp\log.txt. Can you then send me this log.txt

**Comment by kevinvschie** [comment]
I'm not sure what you want me to do. Do you mean the cmd interface in Windows?

**Comment by boutinb** [comment]
Yes this is it.

**Comment by kevinvschie** [comment]
When I type in JASP, it won't find it.

**Comment by boutinb** [comment]
In the command prompt, type: 
> C:
> cd "\Program Files\JASP 0.8.1.1"
> JASP > %TEMP%\jasp.log

%TEMP% is the temporary folder where you may add files.
To find your jasp.log, type
> cd %TEMP%
Here you should see it.
You can open it with notepad
> notepad jasp.log

Kind regards

**Comment by kevinvschie** [comment]
When I enter the first part after the final line it simply opens JASP as it normally opens. 

cd %TEMP% gives me a new line C:\Users\schie006\AppData\Local\Temp. 

But that's it. Should I add something?

**Comment by boutinb** [comment]
When you are in the TEMP folder (cd %TEMP%), and you type:
> notepad jasp.log
Do you see something?

**Comment by kevinvschie** [comment]
I get this back:

{
   "messages" : [
      "Package lsmeans is not the correct version; expected: 2.17, installed: 2.20-2",
      "Package RInside not installed!"
   ],
   "official" : false
}

**Comment by boutinb** [comment]
Do you have problem only with this JASP file? We had a look to this file, and the only thing we could find is that as the first column is called ID, then think Excel that it is a SYLK file... JASP should not have any problem with this, but we don't see any other problem with this particular file.

**Comment by kevinvschie** [comment]
Yes, it seems to be this file specifically. If I open JASP and then select that file I'm able to do analyses. The problem is only when loading the .jasp file with all my previous analyses.

**Comment by boutinb** [comment]
This is really strange. I have no problem with this file. I loaded this file, and saved it again. Here is is it:
[Intrusions_Exp2_Results_20170103_FINAL.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/858090/Intrusions_Exp2_Results_20170103_FINAL.jasp.zip)
Can you try again?

**Comment by kevinvschie** [comment]
This one seems to work. That is really odd. Any idea why this happened? I saved it myself a number of times, and I still got the error.

**Comment by boutinb** [comment]
Fine that this one works! It is still quite strange. There was maybe a setting in this file that was not understood in the new JASP version... In which JASP version you created this jasp file?

**Comment by kevinvschie** [comment]
In JASP 0.8.1.0

**Comment by boutinb** [comment]
It is occurs again with another jasp file, reopen this issue
