### ISSUE TITLE
ANOVA with Huyn-Feldt correction gives strange error messages

### ISSUE THREAD

**Issue by annatemp** [jasp-stats/jasp-desktop#1698]
JASP Version 0.8.1
OS: Mac OS Sierra (10.12.3)
Analysis: repeated measures ANOVA with Huyn-Feldt correction

Error message:

"This analysis terminated unexpectedly.

Error in complete.cases(x, y): not all arguments have the same length

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback)

.resultsPostHoc(referenceGrid, options, dataset, fullModel)

t.test(unlist(postHocData[listVarNamesToLevel[[k]]]), unlist(postHocData[listVarNamesToLevel[[i]]]), paired = T, var.equal = F)

t.test.default(unlist(postHocData[listVarNamesToLevel[[k]]]), unlist(postHocData[listVarNamesToLevel[[i]]]), paired = T, var.equal = F)

complete.cases(x, y)"

Initially I thought this meant that I had missing data in the file causing the arguments to have different lengths, but I don't.

**Comment by JohnnyDoorn** [comment]
Hi Anna,
Thanks for filing this bug-report. Could you maybe share your dataset here, so I can try to replicate your issue? If you want to send it by mail, you can send it to J [dot] B [dot] vanDoorn [at] uva [dot] nl
That way I can take a closer look and solve the issue.
Kind regards
Johnny
