### ISSUE TITLE
Error msg

### ISSUE THREAD

**Issue by nronaldvdberg** [jasp-stats/jasp-desktop#1699]
## Environment (for bugs)

* JASP version: 0.8.0.0
* OS name and version: Windows 10
* Analysis:

I got the following error message:

This analysis terminated unexpectedly. Please contact its author.\n\nError in plot$data : $ operator is invalid for atomic vectors\n

....after doing the following:
1. perform a paired frequentist t-test
2. perform a paired Bayesian t-test
3. go back to the frequentist test by clicking on its result in the result window
4. add the same pair of variables by accident (hence, same test performed twice)
5. remove the first variable (by selecting the left one of the variable pair and click the triangle arrow button)

Screenshot 1 (before clicking the triangle arrow button) :http://imgur.com/a/zNSls
Screenshot 2 (after clicking the triangle arrow button): http://imgur.com/a/ZGLv8

**Comment by boutinb** [comment]
Hi @nronaldvdberg Can you send us the data file and the jasp file?

**Comment by nronaldvdberg** [comment]
I have attached it.

To reproduce the error, it seems essential that you first do a test 

[bugged.zip](https://github.com/jasp-stats/jasp-desktop/files/871996/bugged.zip)

**Comment by nronaldvdberg** [comment]
[jasp_error.zip](https://github.com/jasp-stats/jasp-desktop/files/872063/jasp_error.zip)

See attached - i also made two movies showing when the error does and does not occur. Hope this helps.

**Comment by nronaldvdberg** [comment]
oops i had accidentally closed this issue - sorry for the mess, i'm not so familiar yet with github. See previous comment for a .zip file with requested data files as well as a movie showing a reproduction of the error.

**Comment by boutinb** [comment]
@nronaldvdberg Thanks for the movies, that makes it indeed really clear.
@quentingronau Can you have a look to this problem?

**Comment by AlexanderLyNL** [comment]
Fixed 

https://jasp-stats.org/download/
