### ISSUE TITLE
About Dialog doesn't work.

### ISSUE THREAD

**Issue by janderuiter** [jasp-stats/jasp-desktop#1700]
## Environment (for bugs)

* JASP version: 8.1
* OS name and version: Mac OSX 10.12.3 Sierra
* Analysis: N/A
Selecting "About JASP" from the main menu does nothing. It should report version etc.

**Comment by FransMeerhoff** [comment]
Hi @janderuiter 

Thanks for this notification..
But there always another way to check the JASP version. On the main window, right top,  there is an 'option list' icon where the options of JASP reside. Here is also the  'About' option, where the JASP version, with other info are shown.
We wil fix this issue in a new release.

Kind regards
Frans Meerhoff

**Comment by boutinb** [comment]
Solved in next release
