### ISSUE TITLE
From Twitterverse: error in t-test?

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1702]
![image](https://cloud.githubusercontent.com/assets/8603015/24405194/4d3815cc-13c4-11e7-8207-5ba02d779906.png)

From the twitterverse. Was our error handling overly enthusiastic? Here the user wants to run multiple t-tests, but the error message states that there are more than two levels. This is a key analysis so would be good to fix.
@TimKDJ 

E.J.

**Comment by EJWagenmakers** [comment]
@TimKDJ 
To clarify the figure: above is the analysis in the latest release (the error message); below is the same analysis in the previous release (no error message).

**Comment by TimKDJ** [comment]
@EJWagenmakers without seeing the dataset I'm not sure what is happening.
My guess is that it's the same problem mentioned here: issue #1683 
NA was seen as an unique level, I've fixed this and it should be included in the latest hotfix patch.

**Comment by mjkofler** [comment]
This was my report via twitter. Can confirm that it seems to be related to missing data in my grouping variable. Analyses ran as expected after filling in 1 missing case in grouping variable. 

Version 0.8.1.1 downloaded from jasp-stats website gives different error message than screenshot above. (screenshot attached)

[as an aside ... I'm loving JASP - Thanks for letting me let me SPSS license expire!]

<img width="360" alt="screen shot 2017-03-28 at 8 00 52 pm" src="https://cloud.githubusercontent.com/assets/16530100/24432694/e67b9952-13f1-11e7-92c8-8224681ac3ef.png">

**Comment by TimKDJ** [comment]
Hi @mjkofler 

Glad you like JASP!

Would you be so kind as to attach the dataset or JASP file?
Alternatively you may send it to t.dejong3 at uva dot nl

Cheers,
Tim

**Comment by mjkofler** [comment]
Sent via email!

**Comment by TimKDJ** [comment]
Alright, so the problem was again related to missing values in the predictor.
I have added a fix for this and a t-test on your dataset now runs fine.

If you want to perform a t-test before this fix is put in the release version you should manually remove the missing levels in ADHD_YN (listwise).

Thank you very much for reporting this to us @mjkofler
