### ISSUE TITLE
Please add Chinese support in your next version

### ISSUE THREAD

**Issue by Sciurus365** [jasp-stats/jasp-desktop#1704]
## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: Windows 7 
* Analysis:
I found that JASP can not open any files with name or path including Chinese words.
The figures generated by JASP can not show Chinese words, either.
I really like this software, but some of my works are required to be reported in Chinese, so I can't use JASP to analysis these data. Could you please add Chinese support in your next vision? Thank you!

**Comment by SCgeeker** [comment]
Hi, be sure your Chinese words are encoded in utf-8. You could check my files for teaching.

https://osf.io/x4h7d/

**Comment by Sciurus365** [comment]
I've checked my file and it is encoded in uft-8. And I tried again with your file. The words are displayed correctly in the **charts**, but Chinese words are still not able to be shown in the **plots** (see the picture attached. Could you please check it?

**Comment by aknight1-uva** [comment]
Duplicate issue #1695

**Comment by boutinb** [comment]
Solved by #2064
