### ISSUE TITLE
Changing type of variable already in analysis

### ISSUE THREAD

**Issue by TimKDJ** [jasp-stats/jasp-desktop#1708]
## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: Windows 10
* Analysis: None. It's a problem with the UI.

If the type of a variable is changed after it was included in an analysis (and it is changed to something that is not allowed) it will turn grey and cannot be removed anymore. However, it still impacts the analysis.

Steps to reproduce:
1) Open the debug dataset under Examples
2) Perform an Independent Samples T-Test (may be a different analysis as well)
3) Place debBinom as Grouping Variable and debInf as Dependent Variable
4) Press OK and double click a value in the dataset to trigger data editing
5) Change ANY value not related to 'debInf' and save

**Comment by boutinb** [comment]
This is solved
