### ISSUE TITLE
Problems installing JASP 0.8.1.1.

### ISSUE THREAD

**Issue by ttome2016** [jasp-stats/jasp-desktop#1713]
Folks, I'm sorry if this is not the best place to post this, but I'm feeling lost - I tried to install the latest version on one of my computers (running on 64 bit win 8.1). The process got completed, but when I tried to open JASP, it behaved as if no files had been installed (for instance, it would not recognize JASP's icon and associate it with the .exe file).

So, I proceeded to try and uninstall it, so that I could reinstall it afterwards and see it that would work. I even ran Ccleaner  and also checked the registry key for any entries left behind and deleted all of them.

Now, whenever I try to reinstall JASP 0.8.1.1., the system tells me it is already installed. It even allows me to install the previous version, but not 0.8.1.1.

Can anyone help me with this? What can I do?

Many, many thanks!

**Comment by FransMeerhoff** [comment]
Hi @ttome2016 

I do not know exactly what's going on on your system but in advance we could try the following to solve your problem.  We ship for Windows JASP version als a preinstalled version that you might try.

1. You can find it on http://static.jasp-stats.org/JASP-0.8.1.1-64-bit.zip
2. Download it and unzip the file at some location.
3. Start JASP.exe from double clicking in in the unpacked folder.

If this work around runs then I suggest that you will wait for the next release 8.1.2 that is under the hood. We wil expect this new release in a couple of weeks.

Kind regards
Frans Meerhoff

**Comment by ttome2016** [comment]
Frans, many many thanks! This works perfectly and it is also a perfect solution for when you are not allowed to install software, given that it can be used right out of a flash drive! I would like to add that the regular installation method for 0.8.1.1 worked perfectly on my other machine (running on win 10 64 bit), so this is just an issue regarding my win 8.1 machine (well, I was considering the possibility of formating it soon, so I guess that will probably solve the original problem, in the end).

One other thing I'd like to suggest:
maybe it's just my own inability, but I guess these portable versions of JASP should be included in the downloads page of the JASP website - I could not find them there and, if you had not sent me the link for downloading the zip file, I would have never known that there was such a thing as a standalone version of JASP. Ever since 2016 I've been suggesting JASP to my students and, by personal experience, the easier it is to interact with the project, the better.

Once again, many thanks (and I'll be looking out for the future versions of JASP - this is, for me, one of the most exciting open source projects out there)!

**Comment by EJWagenmakers** [comment]
Frans, maybe we can advertise this option more prominently on the download
page?

**Comment by FransMeerhoff** [comment]
Hi @ttome2016 

Nice to hear this solution works, and thanks for your enthusiasm about JASP.

About your suggestion:
The portable versions of  JASP are already available on our download site.
As EJWagenmakers also suggested, we should advertise this option more prominently.
But for now, if you go the download page of JASP you will find at the bottom of this page
an option:
'Advanced downloads' There are the links to download the zipped versions.

<img width="397" alt="screen shot 2017-04-06 at 08 45 22" src="https://cloud.githubusercontent.com/assets/15656960/24741586/d9202096-1aa6-11e7-8018-cbb130714250.png">
 
Kind regards 
Frans Meerhoff

**Comment by ttome2016** [comment]
Thanks for the heads up, Frans!
