### ISSUE TITLE
Jasp crashes for no apparent reason

### ISSUE THREAD

**Issue by baltzis** [jasp-stats/jasp-desktop#1715]
## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: Windows 10 64-bit
* Analysis: After working normally on a file imported from SPSS and making regular saves I closed JASP. After some time, when trying to re-open the same .jasp file the application crashes for no apparent reason. I then repeated the import, re-run the same (descriptive) analysis of the data, save and close JASP and for a couple of times this procedure did not seem to cause any trouble. However, again after hours, when trying to re-load the .jasp file, JASP crashed again. The application probably corrupts its own file at some point. I am adding the event log:

**- System** 
  **- Provider** 
   **[ Name]**  Application Error 
  **- EventID** 1000 
   **[ Qualifiers]**  0 
   **Level** 2 
   **Task** 100 
   **Keywords** 0x80000000000000 
  **- TimeCreated** 
   **[ SystemTime]**  2017-04-05T18:47:34.764701300Z 
   **EventRecordID** 27617 
   **Channel** Application 
   **Computer** BALTZIS 
   **Security** 
**- EventData** 
   JASP.exe 
   0.0.0.0 
   00000000 
   JASP.exe 
   0.0.0.0 
   00000000 
   c0000005 
   000000000000d72c 
   28b4 
   01d2ae3d127e06c9 
   C:\Program Files\JASP 0.8.1.1\JASP.exe 
   C:\Program Files\JASP 0.8.1.1\JASP.exe 
   0c834ad2-f9e4-4055-8a52-002f5251683f 

I am also getting the following info from the Windows Event Log (sorry for inaccurate translation, but my system is in Greek):
Defective application name: JASP.exe, version 0.0.0.0, time stamp: 0x00000000
Defective functional unit name: JASP.exe, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Offset error: 0x000000000000d72c
Defective process ID: 0x28b4
Defective application start time: 0x01d2ae3d127e06c9
Defective application path: C:\Program Files\JASP 0.8.1.1\JASP.exe
Defective functional unit path :C:\Program Files\JASP 0.8.1.1\JASP.exe
Report ID: 0c834ad2-f9e4-4055-8a52-002f5251683f
Defective package full name: 
Application identifier associated with the defective package: 

Regards
Alexandros

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by FransMeerhoff** [comment]
Hello @baltzis 

Could you please send us the original file imported from SPSS and the JASP file that cause JASP to crash. If you add these files to one zip file you can add the zipped file to this issue.

Cheers 
Frans Meerhoff

**Comment by baltzis** [comment]
Dear Frans,
I'm afraid I cannot, at least for the moment, because I saved a new .jasp file over the old one by mistake and today I have to use the SPSS only for I can't find how to produce multiple response sets in JASP. I will do so, however, as soon as the problem reappears.

By the way, shouldn' t JASP re-read a changed SPSS file and import any new variables after synchronization?

Regards
Alexandros

**Comment by boutinb** [comment]
@baltzis If you start JASP from .sav file, and you change the sav file via SPSS, JASP should reload automatically the new data (and reprocess the analyses you made in JASP).
If you have again the same problem, please send us the sav and jasp files. You can then reopen this issue.

**Comment by baltzis** [comment]
I am not sure what you mean by starting JASP from .sav file. Shouldn't I load the .jasp file that contains the analyses?

**Comment by boutinb** [comment]
I mean to open the sav file from JASP. Then JASP is automatically synchronized with this sav file: all analyses you will make in JASP are automatically updated with the new data, if you change the data is SPSS.
If you have a JASP file with already your analyses, check in File/Sync Data/Current with which data file it is synchronized. If it is not synchronized with the right .sav file, you can still do it by browsing it on your Computer.

**Comment by baltzis** [comment]
Thanks

**Comment by baltzis** [comment]
Hello, again! Well, after conducting a series of analyses, saved several times, closed and re-opened the file it seemed that there was no problem. Then, I had to do some other work and left it alone. After about six hours I tried to open the file and continue the analyses, but JASP keeps crashing. Interestingly enough, the file can be seen in OSF without a problem. When downloading the same file from OSF, JASP crashes upon the attempt to open it.

Anyway, I am attaching the .jasp file as I am positive that this is a JASP problem. Perhaps it is related with value labels with non-ASCII characters (e.g. Greek) that for some reason, at some point, causes JASP to crash (but not the OSF viewer). Fortunately, I did not rely only on JASP and did not loose the results of six hours work (and there are deadlines running...). 

[jasp-working.zip](https://github.com/jasp-stats/jasp-desktop/files/903616/jasp-working.zip)
I am attaching the file.

Good luck with figuring out what is going on. I sincerely wish that JASP could be freed from such problems, because I liked it very much.

Regards
Alexandros

**Comment by boutinb** [comment]
@baltzis Can you give also the sav file?

**Comment by baltzis** [comment]
Sorry for the delay. Here is the file.
[jasp-working.zip](https://github.com/jasp-stats/jasp-desktop/files/907287/jasp-working.zip)

**Comment by baltzis** [comment]
Hello, again. I don't know if some more information might be of any help to cope with the crash issue. It seems that JASP has its own mysterious ways: today it opened the file in question without a problem. I should emphasize, however, that before retrying to open it, I had my computer cleaned up with CCleaner, cleared the system temp directory, and used the CCleaner registry cleaner as well. It also synchronized the re-opened file with several changes and corrections I had done meanwhile to the original .sav file.

I am really confused.

Regards
Alexandros

**Comment by boutinb** [comment]
Hello @baltzis Probably the crash is due to synchronization problem. You may set the synchronization off (In the top-right menu, choose Preferences, unset 'Synchronize automatically on data file save'): this should prevent the crash.
I have just made some fixes for SPSS file synchronization. This will be in the release over 2 weeks. Hopefully, this solves also your problem.

**Comment by baltzis** [comment]
Thanks again for your quick response!

Regards
