### ISSUE TITLE
JASP cannot handle non-English systems

### ISSUE THREAD

**Issue by baltzis** [jasp-stats/jasp-desktop#1719]
## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: Windows 10 64-bit (Greek)
* Analysis: Probably JASP cannot work in OS that is not in English not only because it cannot read path names with non-ASCII characters, but also because even if the files are stored in paths with names in plain ASCII, then there is always the incapability of handling paths to user profiles that may not contain plain ASCII characters. The following message was received after a failure to carry out an analysis:

This analysis terminated unexpectedly.
Error in grid.newpage(): could not open file 'D:/Users/������ & ����/AppData/Local/JASP/temp/7280/resources/5/_18.png'
Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback)
.independentSamplesTTestDescriptivesPlot(dataset, options, perform)
print(p)
print.ggplot(p)
grid.newpage()
To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

This may also answer the issue about .jasp files that although they have been saved in paths with names containing only ASCII characters, for some obscure reason after a while or some time later, they can't be opened by JASP which then crashes.

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by aknight1-uva** [comment]
Duplicate #1695

**Comment by boutinb** [comment]
Solved by #2064
