### ISSUE TITLE
box plot error

### ISSUE THREAD

**Issue by joucoski** [jasp-stats/jasp-desktop#1720]
## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: Ubuntu 16.04
* Analysis: Box Plot error

This analysis terminated unexpectedly.

Error: Unknown parameters: stat_params

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback)

.descriptivesSplitPlots(dataset, options, run, last.splitPlots)

ggplot2::stat_boxplot(geom = 'errorbar', size = 0.75, stat_params = list(width = boxWidth/2))

layer(data = data, mapping = mapping, stat = StatBoxplot, geom = geom, position = position, show.legend = show.legend, inherit.aes = inherit.aes, params = list(na.rm = na.rm, coef = coef, ...))

stop('Unknown parameters: ', paste(extra, collapse = ', '), call. = FALSE) 

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:
![tela_erro_boxplot](https://cloud.githubusercontent.com/assets/14141667/24811821/1586cee8-1b9e-11e7-9d48-8ecdc0f7416f.png)

and the same error with the Example of the JASP:
![tela_erro_example](https://cloud.githubusercontent.com/assets/14141667/24811872/433ff954-1b9e-11e7-9531-f897d4a0dc94.png)

**Comment by boutinb** [comment]
@joucoski JASP works currently with R 3.1 and ggplot2 version 1.0.0. Can you check which version you have? I think this error comes from a newer version of ggplot2. We will release soon a version that supports R 3.3 and ggplot2 2.2.1.

**Comment by vankesteren** [comment]
This issue should be solved with the newest JASP version
