### ISSUE TITLE
Variable names/labels imported from SPSS

### ISSUE THREAD

**Issue by buraczku** [jasp-stats/jasp-desktop#1721]
Hi 

I have been working on a dataset that was created in SPSS (.sav). Until now the labels in SPSS appeared as the variable names in JASP, but now variable names in SPSS appear as names in JASP.

When I open the .jasp files I saved earlier, SPSS labels are loaded as variable names for the same dataset. If I open the dataset with JASP, SPSS variable names appear. 

Did I alter a setting about it without noticing?

Thank you for your help! 

* JASP version: 0.8.1.1
* OS name and version: Win 7

**Comment by boutinb** [comment]
Hi,
We use now name in place of label for the column, since label can be much too long. There is now no concept of column label in JASP, so we cannot use name & label together.
Where would you like to use column label in JASP?

**Comment by buraczku** [comment]
Hi,

Thank you for your answer. I have the variable names short (eg A1), and labels more informative (eg income), so the output looked better with the labels. My main confusion is that the same dataset loads differently in the same computer. It is of course not a big deal, but a "show labels" option like in SPSS would be useful in some cases.

Thank you!

**Comment by boutinb** [comment]
We might add this in a future release if more people wants this.
