### ISSUE TITLE
Enhancement: transform of dependent variable in regression

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-desktop#1724]
A small and simple enhancement would be the option to transform the dependent variable in regression. This could be implemented as a checkbox for log-transformation or a drop-down menu if multiple transforms are offered (e.g. log and rank).

It is possible to do this by editing the data externally, but it's a bit cumbersome and therefore not good for teaching. I don't my students to get stuck with Excel problems when I want them to focus on understanding log-transformation. It's useful when the residuals are log-normal.

Thanks for making JASP!

**Comment by AlexanderLyNL** [comment]
Compute column implemented

https://jasp-stats.org/download/
