### ISSUE TITLE
Sync Data execution failure

### ISSUE THREAD

**Issue by baltzis** [jasp-stats/jasp-desktop#1729]
## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: Windows 10 (64bit), Windows 10 (32bit)
* SPSS 23.0.2 (64bit and 32bit 
* Analysis:
a) When transferring or copying the .jasp file and its corresponding .sav file onto another computer, synchronization is lost. Instructing JASP to synchronize using the Sync Data option, has no effect whatsoever. In the new location JASP does not recognize the two files as "connected" and/or it cannot make the connection (although nothing else has been changed).
b) JASP cannot synchronize with the .sav file when new variables are added to the .sav file.
c) Synchronization between two copies of the same .jasp file (one on the computer and the other on the OSF) does not seem to work (unless, of course, I have misinterpreted the use of Sync Data with the OSF).

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by boutinb** [comment]
This is solved in the next release.

**Comment by baltzis** [comment]
Thanks again!

A.
