### ISSUE TITLE
Support for Ubuntu 17.04?

### ISSUE THREAD

**Issue by SvenHeim-UDE** [jasp-stats/jasp-desktop#1737]
Will you add support for Ubuntu 17.04 (Zesty) in the near future? Due to missing dependencies it is not installable.

**Comment by FransMeerhoff** [comment]
HI @SvenHeim-UDE 

Yes we will. Definively when it becomes a LTS version.
Kind regards
Frans Meerhoff

**Comment by SvenHeim-UDE** [comment]
Ok, so this means no for the near future. Because the next scheduled LTS will be 18.04 that will be released in April next year. That's fine for me, I will leave at least one computer on 16.04 LTS.

**Comment by FransMeerhoff** [comment]
Sorry @SvenHeim-UDE 

I think I was unclear about this.
I wanted to say that  LTS versions  are always supported, but meanwhile we try to support other new versions of Ubuntu too.

**Comment by SvenHeim-UDE** [comment]
Alright, thanks for the clarification. :-)

**Comment by jstbcs** [comment]
Was pleased to see that someone brought this up before. Ubuntu is now at 17.10. Not a new LTS release, but I would appreciate support for any of the two newest versions.

**Comment by akashrajkn** [comment]
From v0.8.6, we ship a flatpak app. It's quite easy to install on ubuntu 17.04. :)

**Comment by SvenHeim-UDE** [comment]
Just wanted to let you know: Flatpak app is flawlessy working on both of my Linux machines, Ubuntu and Arch. Thanks! :-)
