### ISSUE TITLE
Population Proportions in Summary Stats Module

### ISSUE THREAD

**Issue by JASPUser** [jasp-stats/jasp-desktop#1746]
## Environment (for bugs)

* JASP version:
* OS name and version:
* Analysis:
## Environment (for enhancement requests)
 
* Enhancement: Provide a simple version of **Population Proportions tests and intervals for one and two independent samples** like prop.test (or binomial test) but where the user just enters the simple counts for x and n and the package computes a 1 or 2 sided test p-value and Wald confidence intervals and estimates rather than working from raw data. So this is just a simple dialogue with no data to import. This is a classical stat version of the Bayesian Binomial test.  Also do a sample size n calculation for a given MOE and Confidence level. So 5 functions in all.
* Purpose:

**Comment by EJWagenmakers** [comment]
Right now we don't have the "counts" option that the contingency tables do
have. I think it would be sense to add this functionality.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam, Nieuwe Achtergracht 129B
Letter: PO Box 15906, 1001 NK Amsterdam
Parcel: Valckenierstraat 59,  1018 XE Amsterdam

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Cell: (+31) 6 45626624

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by AlexanderLyNL** [comment]
Can be done using syncing
