### ISSUE TITLE
Develop a Simulation Module

### ISSUE THREAD

**Issue by JASPUser** [jasp-stats/jasp-desktop#1749]
## Environment (for bugs)

* JASP version:
* OS name and version:
* Analysis:
## Environment (for enhancement requests)
 
* Enhancement: Develop a simulation module, perhaps drawing on what Excel's Data Analysis Random Number Generation does to do simple simulations of distributions with transformations of the random data and with plots. 
eg It should be able to model questions like "If we toss 4 dice what is the proportion of these trials where no 2 dice have the same number?"  "If we toss 2 dice what proportion of these trials have an even product of the outcomes?" Can we simulate tossing a coin 1000 times and plot the proportion of heads as n increases? (A converging random walk?) 
![image](https://cloud.githubusercontent.com/assets/27625429/25391047/9eef8cf0-2a18-11e7-8f20-eef51b889c45.png)

Subtle difference: Do 1000 trials of n coin tosses (incrementing n each trial from 1 up to 1000) and plot the proportion of heads - a simulation of the Law of Large Numbers.  
![image](https://cloud.githubusercontent.com/assets/27625429/25390962/5d32b09e-2a18-11e7-9f60-e295c6a940a1.png)

Ideally any specifiable function of the outcomes should be modelable. The R scripts are individually fairly easy but the challenge is to design the interface and generic processing.
* Purpose:

**Comment by AlexanderLyNL** [comment]
Hi JASPUser, 

Great suggestions, though, it's not high up on our priority list at the moment as we're focussing on other modules at the moment. We're happy to hear your suggestions regarding the user interface. 

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
Can be done with compute column

https://jasp-stats.org/download/
