### ISSUE TITLE
Typo in reliability analyses

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1761]
@vandenman (Don, I assume this is you)
Hi guys,

Under Reliability analysis we have the "McDonalds' \omega". However, the name of the progenitor is McDonald, without an s at the end. So it should be "McDonald's \omega" -- the apostrophe should immediately follow the "d". Can we fix this before we have our new release please? NOTE: it should also be fixed in the output.

Cheers,
E.J.

**Comment by vandenman** [comment]
Yes that's me! Good catch, will fix this tonight.
