### ISSUE TITLE
About dialog does not work in mac

### ISSUE THREAD

**Issue by janderuiter** [jasp-stats/jasp-desktop#1775]
## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: MacOS 10.12.4 (Sierra)
* Analysis: N/A

The "About" dialog does nothing. It doesn't crash; it just doesn't do anything at all. I was hoping it would display the version number and the way to properly cite JASP. 

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by FransMeerhoff** [comment]
Hello @janderuiter 

Thanks from the info, we are aware of this problem. Fix will be in the next release.
But you can also reach the JASP release and download information, and other preferences,  from the option button on the right top go the main window. Its the button with the three bars.

Kind regards
Frans Meerhoff

**Comment by janderuiter** [comment]
Thanks Frans. It's not for me, but for my students, who all referred to
Love et al (2015) instead of JASP Team 2017 :-)

**Comment by FransMeerhoff** [comment]
Ok I see..

A final remark then: Besides a citation in the about box you can also find a citation on the JASP site at
https://jasp-stats.org/faq/
There by the FAQ's is:  How do I cite JASP?
Here you can find how to cite JASP including a BibTex citation.

Cheers Frans

**Comment by janderuiter** [comment]
Does closed mean "fixed"?

**Comment by boutinb** [comment]
Yes. The new version (with this fix) will be officially release probably next monday

**Comment by janderuiter** [comment]
Cool! The new version with vector graphics for the plots? (Which I think is
the Holy Grail of graphics :-)

**Comment by boutinb** [comment]
Yep!

**Comment by janderuiter** [comment]
YEEEHAAAA!
