### ISSUE TITLE
Not a bug - but clarification: Why is there a discrepancy between JASP & SPSS for lin reg results

### ISSUE THREAD

**Issue by susanneschweizer** [jasp-stats/jasp-desktop#1783]
## Environment (for bugs)

* JASP version: 0.8
* OS name and version: Windows 7
* Analysis:
## Environment (for enhancement requests)
Please ignore - resolved didn't manage to delete post - sorry!

* Enhancement: No
* Purpose: Clarification

**Comment by AlexanderLyNL** [comment]
Hi Susanne, 

Thanks for your comment and great to know that everything is clear now. I'll close the thread for you. 

Cheers,
Alexander
