### ISSUE TITLE
Error with graphics

### ISSUE THREAD

**Issue by DenisFouc** [jasp-stats/jasp-desktop#1795]
## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: El Capitan 10.11.6
* Analysis: ANOVA then Descriptive Plots

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

This analysis terminated unexpectedly.

Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : extr'emit'es de polygone non trouv'es

Stack trace
preDrawDetails.gTableParent(x)

pushViewport(x$layoutvp, recording = FALSE)

lapply(vps, push.vp, recording)

FUN(X[[1]], ...)

push.vp.viewport(X[[1]], ...)

grid.Call.graphics(L_setviewport, vp, TRUE)

(function (x) 
{
    widthDetails(x)
})(list(label = 'Standardized Residuals', x = -0.2, y = 0.5, just = 'centre', hjust = 0.5, vjust = 1.2, rot = 90, check.overlap = FALSE, name = 'axis.title.y.text.81', gp = list(fontsize = 18, col = 'black', fontfamily = '', lineheight = 0.9, font = 1), vp = NULL))

widthDetails(x)

widthDetails.text(x)

grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, resolveHJust(x$just, x$hjust), resolveVJust(x$just, x$vjust), x$rot, 0)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by vandenman** [comment]
Thanks for the report! Could you perhaps send a .zip file with either a .csv of a .jasp file so we can reproduce the error?

**Comment by DenisFouc** [comment]
OK…
I have just installed the (superb !) Jasp, and I have tried to run the example. My error occurs with the example file « Tooth… ». Note that all works perfectly on my laptop or on another Apple machine.
I can also say that this kind of errors occur also in almost all the analysis, when I try to draw the plots. For example, in “descriptive statistics”, with the BIG 5 file, the “Display distribution plots” and the Correlation plots are well drawn. But not the “display Boxplots” that make this error:


This analysis terminated unexpectedly.

Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : extr'emit'es de polygone non trouv'es

Stack trace
preDrawDetails.gTableParent(x)

pushViewport(x$layoutvp, recording = FALSE)

lapply(vps, push.vp, recording)

FUN(X[[1]], ...)

push.vp.viewport(X[[1]], ...)

grid.Call.graphics(L_setviewport, vp, TRUE)

(function (x)
{
    widthDetails(x)
})(list(label = 'Neuroticism', x = 0.1, y = 0.5, just = 'centre', hjust = 0.5, vjust = 0.9, rot = 90, check.overlap = FALSE, name = 'axis.title.y.text.103', gp = list(fontsize = 18, col = 'black', fontfamily = '', lineheight = 0.9, font = 1), vp = NULL))

widthDetails(x)

widthDetails.text(x)

grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, resolveHJust(x$just, x$hjust), resolveVJust(x$just, x$vjust), x$rot, 0)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports





Thank’s !
Denis




Denis Foucambert

Directeur des cycles supérieurs
Département de linguistique
Université du Québec à Montréal
C.P. 8888, succursale Centre-Ville
Montréal (Québec) H3C 3P8
CANADA
tél. : 514-987-3000 poste 3670
Bureaux : DS 3531 - 3444



De : vandenman <notifications@github.com>
Répondre à : jasp-stats/jasp-desktop <reply@reply.github.com>
Date : jeudi 1 juin 2017 03:12
À : jasp-stats/jasp-desktop <jasp-desktop@noreply.github.com>
Cc : "Foucambert, Denis" <foucambert.denis@uqam.ca>, Author <author@noreply.github.com>
Objet : Re: [jasp-stats/jasp-desktop] Error with graphics (#1795)


Thanks for the report! Could you perhaps send a .zip file with either a .csv of a .jasp file so we can reproduce the error?

**Comment by boutinb** [comment]
Bonjour @DenisFouc 
We cannot reproduce your problem, helas. Did you install XQuartz (and if you did some upgrade, did you re-install XQuartz)?
You have MacOS El Capitan. Is it an option for you to upgrade to Sierra?

**Comment by DenisFouc** [comment]
Bonjour !
I have made an upgrade, on the same computer, to Sierra. Before that, I have uninstalled XQuartz and Jasp.
Then, in this order, I have reinstalled Xquartz and Jasp.
And then, run the ANOVA analysis on your file « Tooth growth »
But it isn’t better as you can see in the screen capture…


Denis


De : bruno boutin <notifications@github.com>
Répondre à : jasp-stats/jasp-desktop <reply@reply.github.com>
Date : mardi 6 juin 2017 à 05:09
À : jasp-stats/jasp-desktop <jasp-desktop@noreply.github.com>
Cc : "Foucambert, Denis" <foucambert.denis@uqam.ca>, Mention <mention@noreply.github.com>
Objet : Re: [jasp-stats/jasp-desktop] Error with graphics (#1795)


Bonjour @DenisFouc<https://github.com/denisfouc>
We cannot reproduce your problem, helas. Did you install XQuartz (and if you did some upgrade, did you re-install XQuartz)?
You have MacOS El Capitan. Is it an option for you to upgrade to Sierra?

**Comment by DenisFouc** [comment]
I know how difficult it can be to solve this kind of problem... I was also a developer in a past life…

The version 0.8.1.2 always send the same message of error.
I’ve tried the debug version, again the same. But I send you the content of the terminal window in the PDF attached file.

Don’t hesitate to ask me something else, if I can help, I’ll do it!


Thanks for all

Denis

De : bruno boutin <notifications@github.com>
Répondre à : jasp-stats/jasp-desktop <reply@reply.github.com>
Date : mercredi 14 juin 2017 à 05:56
À : jasp-stats/jasp-desktop <jasp-desktop@noreply.github.com>
Cc : "Foucambert, Denis" <foucambert.denis@uqam.ca>, Mention <mention@noreply.github.com>
Objet : Re: [jasp-stats/jasp-desktop] Error with graphics (#1795)


@DenisFouc<https://github.com/denisfouc> It is always really difficult to solve a problem we can't reproduce... What I can do, is to give you access to the development release, which use up-to-date libraries. Hier is the link: http://static.jasp-stats.org/JASP-0.8.1.2.new.dmg.
If this does not help, I made another build with more debug information: http://static.jasp-stats.org/JASP-0.8.1.2.new-debug.dmg. With this debug version, you can try to start JASP in this way:
. start a terminal.
. type /Applications/JASP.app/Contents/MacOS/JASP (if you install the debug version with another name like JASP-debug, then type /Applications/JASP-debug.app/Contents/MacOS/JASP)
. JASP should start, and on the terminal, you will see some logs.
. Try to display the boxplots.
. Send me what you see on the terminal.

**Comment by boutinb** [comment]
Hi @DenisFouc I did not receive the PDF file. Did you use the GitHub website to attach the file?

**Comment by boutinb** [comment]
Hi @DenisFouc I haven't received anything... If you send me something with GitHub, compress is first with ZIP. Does this problem still occur with the last version of JASP?

**Comment by DenisFouc** [comment]
Hello,
Yes… always the same pattern…

I didn’t send you anything because I have the same type of errors… Even with the new version.
Here is another picture of my screen after demanding a descriptive plot…
If you can help me… But there is a problem- bug somewhere…

Thank’s
Denis
[cid:image001.png@01D378B1.3AF251A0]
De : bruno boutin <notifications@github.com>
Répondre à : jasp-stats/jasp-desktop <reply@reply.github.com>
Date : mardi 19 décembre 2017 à 06:08
À : jasp-stats/jasp-desktop <jasp-desktop@noreply.github.com>
Cc : "Foucambert, Denis" <foucambert.denis@uqam.ca>, Mention <mention@noreply.github.com>
Objet : Re: [jasp-stats/jasp-desktop] Error with graphics (#1795)


Hi @DenisFouc<https://github.com/denisfouc> I haven't received anything... If you send me something with GitHub, compress is first with ZIP. Does this problem still occur with the last version of JASP?

**Comment by vandenman** [comment]
Hi @DenisFouc, the image you send is not visible for us. Could you please create a .zip file and resend it? Any other data format is not accepted by Github. See [this link](http://osxdaily.com/2012/01/10/how-to-zip-files-in-mac-os-x/) for how to make a .zip file on OSX.

**Comment by vandenman** [comment]
Also, this error might appear because your computer is missing a default font (Arial), which can be removed after installing MS office on Mac. Here is a [stackoverflow link](https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon) where people experienced the same error (albeit that the error message is in English). Perhaps something to try:

- Open Font Book, go to File -> Restore Standard Fonts.

Does the problem persist afterwards?

**Comment by DenisFouc** [comment]
Here it is…


De : vandenman <notifications@github.com>
Répondre à : jasp-stats/jasp-desktop <reply@reply.github.com>
Date : mardi 19 décembre 2017 à 11:21
À : jasp-stats/jasp-desktop <jasp-desktop@noreply.github.com>
Cc : "Foucambert, Denis" <foucambert.denis@uqam.ca>, Mention <mention@noreply.github.com>
Objet : Re: [jasp-stats/jasp-desktop] Error with graphics (#1795)


Also, this error might appear because your computer is missing a default font (Arial), which can be removed after installing MS office on Mac. Here is a stackoverflow link<https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon> where people experienced the same error (albeit that the error message is in English). Perhaps something to try:
·         Open Font Book, go to File -> Restore Standard Fonts.

Does the problem persist afterwards?

**Comment by AlexanderLyNL** [comment]
This seems to be fixed. Open a new issue if the problem reappears.
