### ISSUE TITLE
Confidence intervals missing in descriptives plot (RM ANOVA)

### ISSUE THREAD

**Issue by isakohrlund** [jasp-stats/jasp-desktop#1796]
When running a repeated measures ANOVA, descriptive plots sometimes lack confidence/credible intervals. I found the issue when I ran the RM ANOVA with 1 repeated measures factor (2 levels) and 2 between subject factors (2 levels + 4 levels).

This is the plot missing confidence intervals:
![image](https://cloud.githubusercontent.com/assets/1136649/26672939/58f9a43c-46bb-11e7-9074-f04dc7e151e0.png)

This is the descriptives table:
![image](https://cloud.githubusercontent.com/assets/1136649/26672982/8978cdc2-46bb-11e7-8298-779cf6af38b4.png)

## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: Windows 10 enterprise 64 bit
* Analysis: Repeated measures ANOVA / Bayesian repeated measures ANOVA

**Comment by TimKDJ** [comment]
Hi @isakohrlund,

Thanks for bringing this to our attention!
I played around a little in JASP, but unfortunately (fortunately?) I was unable to make the confidence intervals disappear.

\*Just to be sure\* did you place a checkmark in the checkbox under "Display"?
It's titled "Error bars displaying" and must be checked in addition to the radiobuttons.
If this box is not checked no intervals are shown by default.

If you did place a checkmark in the box, this is definitely a bug.
You mentioned this happens sometimes; is it specific to a dataset, or specific to a set of actions you perform?
Could you maybe attach the .jasp file with the bugged out plot (or send it to t.dejong3 [at] uva [dot] nl)?
That would be very helpful.

Cheers,
Tim

**Comment by isakohrlund** [comment]
Hi,

Yes of course, I put a checkmark checkmark in the checkbox under "Display". Not sure whether it depends on the dataset, just noticed that it happened with the dataset I was working with. I'm sending you the file.

Best regards
Isak

**Comment by TimKDJ** [comment]
Cheers! I'll look into it.

**Comment by TimKDJ** [comment]
Alright so it appears that we do get intervals, they are just very narrow.
As an example, let's look at {Test year, 1, 4} which has the highest variance in your dataset. 
The 95% confidence interval for this subgroup ranges from 3.52 to 3.61.
Consequently, as these bounds are so close to the means, the icons of the means confiscate the error bars.
When you set the confidence interval to 99% you'll notice that they do become visible.

We should probably find a more suitable way of displaying narrow error bars.

**Comment by isakohrlund** [comment]
Really! OK, yes, that would be great. Or some warning text saying that the
intervals might not show if small enough.

Best regards
Isak

2017-06-07 14:28 GMT+02:00 Tim de Jong <notifications@github.com>:
