### ISSUE TITLE
ANOVA plot does not save as a Windows-readable png or eps file

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-desktop#1800]
ANOVA plot does not save as a Windows-readable png or eps file. JASP 0.8.1.2 Windows 7.
![image](https://cloud.githubusercontent.com/assets/16230091/26811821/2173af50-4a42-11e7-8950-6cf58c84875b.png)

**Comment by boutinb** [comment]
Hallo @R180,
I am not completely sure if I understand the error. You save an image somewhere on your computer: can you see this file on the place you saved, with the name you gave? The error you give is about a shortcut, it is better to check directly with a WIndows Explorer if a new file has been created on the folder you selected.
Also, do you use a Windows 32 or 64 bit machine?

**Comment by R180** [comment]
What was happening [64 bit] is that the file would not appear in windows 
explorer. But "search"ing for it would return a shortcut to the 
non-existent file. Nor that I have re-started windows, after installing 
JASP, it seems to work fine.

**Comment by AlexanderLyNL** [comment]
Hi R180, 

Great to see that the problem has resolved itself. I'm closing this issue now. If the problem returns, please open a new thread. 

Kind regards,
Alexander
