### ISSUE TITLE
Include effect size in Post Hoc Tests for ANOVAs

### ISSUE THREAD

**Issue by YamilVidal** [jasp-stats/jasp-desktop#1805]
Include effect size in Post Hoc Tests for ANOVAs.
The request is quite self explanatory.

Reporting effect sizes is (should be) more important than reporting p-values.

Thanks

**Comment by boutinb** [comment]
@JohnnyDoorn Could you answer this request?

**Comment by JohnnyDoorn** [comment]
Hi,
I looked into this, but did not find any cohesive way of doing this - do you have a suggestion yourself? It would be bad practice to simply report cohen's d for each post hoc comparison, as this does not correct for multiple testing. Maybe there's a way to correct cohen's d that I am not aware of.
Cheers,
Johnny

**Comment by AlexanderLyNL** [comment]
Included in 0.8.2.0

https://jasp-stats.org/download/
