### ISSUE TITLE
Incorrect confidence interval for independent samples t-test

### ISSUE THREAD

**Issue by noahmotion** [jasp-stats/jasp-desktop#1811]
## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: OS Sierra 10.12.5
* Analysis: independent samples t-test

I did an independent samples t-test, and got these results, wherein the lower CI limit is greater than the observed t-statistic (if I include the Mann-Whitney U test, I get an observed statistic much larger than the upper CI limit, too):

![screen shot 2017-06-12 at 3 48 30 pm](https://user-images.githubusercontent.com/5066779/27052118-a2e1cb3c-4f86-11e7-9f3c-9176857efad0.png)

Everything else seems to be working okay (e.g., the descriptive stats, the descriptive plot with CIs, etc).

Edited to add that I'm getting the same problem with a paired samples t-test (i.e., CIs that exclude the observed statistic).

**Comment by boutinb** [comment]
@noahmotion Can you send your dataset (in a zip file)?

**Comment by EJWagenmakers** [comment]
@AlexanderLyNL  @quentingronau 
No need for that file. I think this refers to the same issue we discussed previously, namely that the CI is not on the statistic but on the raw difference in the means (right, guys?). Let's discuss how to fix this, because I agree it is confusing.
E.J.

**Comment by noahmotion** [comment]
I think it is that issue:

![screen shot 2017-06-13 at 9 46 16 am](https://user-images.githubusercontent.com/5066779/27085424-365aefb0-501d-11e7-8638-091ca53f91ff.png)

I'm happy to send the data file, if anyone wants it. And not that you necessarily want my input on this, but it seems like it could be useful to have either/both types of CI reported, depending on whether or not "Mean difference" is selected (i.e., report CIs for the t statistic if just "Confidence interval" is selected, report both if "Mean difference" is also selected). Or maybe that would be too much for a single table, so maybe the t-specific numbers could appear in one table and the mean-difference-specific numbers in a separate table (or separate row)?

**Comment by EJWagenmakers** [comment]
@AlexanderLyNL @JohnnyDoorn @quentingronau 
We are having a meeting to discuss the options right now, so we'll go over your suggestions. We will address this issue soon. Thanks!
