### ISSUE TITLE
Unable to choose JASP as the default program to open .sav files 

### ISSUE THREAD

**Issue by prgmga** [jasp-stats/jasp-desktop#1812]
I have been using jasp for several months now. I have been using it to teach a statistics course for Psychology. I have had it set up to automatically open .sav files (from our class website etc.) and have instructed students to set this up to make life easier for the class. I accidentally chose another program to automatically open .sav files today. Now I am unable to select JASP as the default program to always open .sav file types. A student of mine had the same issue on a Mac (I was using a PC) after downloading the program. It seems that JASP is no longer being recognized as a program able to open .sav files (but of course it can open them if I go to a .sav file I have recently downloaded. Is this a regular problem?

**Comment by aditya1315** [comment]
@prgmga on Mac, you can right click on any .sav file and choose "open with" -> "other.." -> enable "all applications" and change the default program to jasp. 

You can also choose "get info" and change the default open with application.

**Comment by boutinb** [comment]
@prgmga On windows, you can do this way: https://www.cnet.com/how-to/how-to-set-default-programs-in-windows-10/
