### ISSUE TITLE
Moving focus via keyboard is unpredictable

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-desktop#1813]
## Environment (for bugs)

* JASP version: 8.1.1
* OS name and version: ubuntu 16.04

Set the marker in an analysis setting field, press the TAB key and watch the focus jump randomly around. It also eventually goes to the menus (again in a non-sequential order), before cycling back to the analysis settings.

Maybe it's order of implementation? Anyway, it would be nice detail if the focus shifted in the order implied by the GUI.

**Comment by akashrajkn** [comment]
@lindeloev yes, the default tab order follows of the order of creation (of the widgets). I will fix this, thanks for pointing it out.

**Comment by akashrajkn** [comment]
Fixed in Pull Request #1817
