### ISSUE TITLE
Binomial Sequential Plot Does Not Offer "Save As" Functionality

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1819]
In contrast to the other plots, this one does not offer the "Save As" functionality so that it cannot be saved as eps. It is interesting that this happens only for this plot -- I checked some others and they do work. See screenshot.
@vankesteren 
![binomialsequentialdoesnotsaveaseps](https://user-images.githubusercontent.com/8603015/27223703-ef40cf42-5291-11e7-961d-0b327e58ef48.png)

**Comment by AlexanderLyNL** [comment]
Issue fixed with pull request #1821 and feature will be available in the next release
