### ISSUE TITLE
Intrusion From B. Correlation Matrix to B. Correlation Pairs

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1820]
I first executed Bayesian correlation matrix, then switched to Bayesian correlation pairs. For some reason, the box "credible intervals" **intruded** in the panel for correlation pairs. I could even tick the box. See attach.

![matrixfirstthenpairs](https://user-images.githubusercontent.com/8603015/27223784-3da09230-5292-11e7-9aeb-4ff1b242e107.png)

**Comment by AlexanderLyNL** [comment]
I've implemented the credible intervals in the new issue. It should come up in the table. I agree that the placement is a bit off. We'll get into these issues after some backend upgrades. 

<img width="1320" alt="screen shot 2017-06-16 at 13 09 35" src="https://user-images.githubusercontent.com/10271675/27224369-1a5f563c-5295-11e7-9934-7ae8fcf68268.png">

**Comment by EJWagenmakers** [comment]
Ah OK, my bad. My confusion was also due to the fact that the box does not display properly (no horizontal lines). But that's on my laptop, which has issues. We might want to double-check on another windows machine.

**Comment by EJWagenmakers** [comment]
By the way, it might be nice (and consistent with other intervals) to have users input the % they want for the credible interval.

**Comment by AlexanderLyNL** [comment]
Great idea, we'll include it into our next release.

**Comment by AlexanderLyNL** [comment]
Duplicate issue #2041 and issue #1842 and issue #1545

**Comment by boutinb** [comment]
@AlexanderLyNL is this solves?

**Comment by AlexanderLyNL** [comment]
This will be solved with Qt5.9
