### ISSUE TITLE
error on JASP startup

### ISSUE THREAD

**Issue by adamism6** [jasp-stats/jasp-desktop#1825]
## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: Ubuntu 16.04.2
* Analysis: I installed jasp as follows at the command line:

```
sudo add-apt-repository ppa:jasp-uva/jasp
sudo apt-get update
sudo apt-get install jasp
sudo R
install.packages(c("GPArotation","qgraph","RJSONIO","semTools"))
```

Upon startup, I receive this message:
JASP has experienced an unexpected internal error.
""
If you could report your experiences to the JASP team that would be appreciated.
JASP cannot continue and will now close.

Any help is appreciated.

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by FransMeerhoff** [comment]
Hi @adamism6 

Could you please create some logfiles for and send them to us:
From a terminal type
$ JASP > logjasp.txt 2>&1
$ sudo lshw > sysinfo.txt
Please send us the created logjasp.txt and sysinfo.txt

Hope that this information can help us to solve this issue.

Kind regards
Frans Meerhoff

**Comment by adamism6** [comment]
Hi Frans, sure thing. Files attached.

Best,
Adam

[sysinfo.txt](https://github.com/jasp-stats/jasp-desktop/files/1089523/sysinfo.txt)
[logjasp.txt](https://github.com/jasp-stats/jasp-desktop/files/1089522/logjasp.txt)

**Comment by FransMeerhoff** [comment]
@adamism6 

Hi Adam

Thanks for helping us.
In the logjasp file  I noticed that the cause of the problem is RInside  i.e the communication between JASP and R
(symbol lookup error: /usr/lib/JASP/JASPEngine: undefined symbol: _ZN7RInsideixERKNSt7)

Can you please find out which version of R you are using and if the package Rcpp is installed
e.g with
$R
$installed.packages()

Kind regards 
Frans Meerhoff

**Comment by adamism6** [comment]
Hi Frans,

I see. I'm using R version 3.4.0, and Rcpp is listed (though not compiled?):

Rcpp           NA                    NA      NA     "yes"            "3.2.3"

Also, I'm not sure if this is relevant, but I recently upgraded Ubuntu from 14.04 to 16.04. Is it possible that upgrades to R were/weren't made that are creating problems?

Best,
AC

P.S. Tried sending this message by email-reply, but not sure it went through. Sorry if you're receiving this more than once.

**Comment by FransMeerhoff** [comment]
Hi @adamism6 

Thanks for helping us solving this issue.
This is quite hard to find what's going on.
At the moment we are busy to prepare a 8.1.2 JASP version for Ubuntu 16.04 and 17.04
We expect to deliver this version at the end of this week or beginning next week. 
I suggest that we wait till that  version is ready and then try again.

Kind regards
Frans Meerhoff

**Comment by adamism6** [comment]
OK I'll update to v8.1.2 when the new release is available and post an update.

Thanks,
Adam

**Comment by adamism6** [comment]
Hi Frans,

Happy to report it launched and runs without error after updating to v8.1.2.

Best,
Adam

**Comment by boutinb** [comment]
@adamism6 Happy to hear this works!
