### ISSUE TITLE
Bayesian repeated measures anova - high BF10 but no visible effect in plot

### ISSUE THREAD

**Issue by LolaJansen** [jasp-stats/jasp-desktop#1828]
Hi,

I am running a bayesian repeated measures anova. The model with the highest BF10 includes an effect of a continuous variable R. If I plot the effect of this continuous variable R on my dependent variable with a scatterplot with a linear trend line, there seems to be no effect; the line is almost horizontal. 
The BF10 of the model with only this continuous variable R is 0.359. The BFinclusion value of the analysis of effects of this continuous variable R is 40, which indicates some support for this variable.

How is it possible that the analysis seems to indicate strong support for an effect of this variable, while there is no visible effect of this variable if i plot the effect?

Thanks in advance

**Comment by EJWagenmakers** [comment]
Weird. I think we would need the data & jasp file to investigate more. Also, this might be an issue for the JASP forum more than the JASP GitHub pages...

**Comment by RCL29** [comment]
Did they solve this issue? I'm having the same issue but the opposite way: getting a BF01 of 10, while a p-value of 0.066. It makes no sense at all.
