### ISSUE TITLE
Error in solve.default(r, result$Structure): Lapack routine dgesv: system is exactly singular: U[74,74] = 0  Stack trace

### ISSUE THREAD

**Issue by jpw525** [jasp-stats/jasp-desktop#1829]
## Environment (for bugs)

* JASP version:0.8.1.2
* OS name and version: macOS Sierra version 10.12.5
* Analysis: PCA

This analysis terminated unexpectedly.

Error in solve.default(r, result$Structure): Lapack routine dgesv: system is exactly singular: U[74,74] = 0

Stack trace

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by AlexanderLyNL** [comment]
Could you please send us the JASP file so we can look into it?

**Comment by boutinb** [comment]
If this error still occurs, re-open this issue
