### ISSUE TITLE
Error during reliability analysis 

### ISSUE THREAD

**Issue by lisaharris** [jasp-stats/jasp-desktop#1830]
* JASP version: 0.8.1.1
* OS name and version: Windows 10 pro 
* Analysis: Reliability 

This was the error message received: "**This analysis terminated unexpectedly.

Error in min(eigens$values): invalid 'type' (complex) of argument
Stack trace"**

I was running a reliability analysis on my data - and the error came up when selecting all the questions for analysis - and then I added one by one and it was when I added the 7th question that the error happened as well.

**Comment by phehks** [comment]
I have encountered similar problem earlier. Do you have any missing data in any cell of the 7th question? JASP may have issues in handling missing data as SPSS do.

**Comment by AlexanderLyNL** [comment]
Hi Lisa and Phehks,

Could you please attach the JASP file as a zip file in this issue?

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
This problem should be in the newest version 

https://jasp-stats.org/download/

Please open a new issue if the problem occurs.
