### ISSUE TITLE
Installing JASP - Zorin OS and Trisquel OS Linux distro

### ISSUE THREAD

**Issue by JLPuga** [jasp-stats/jasp-desktop#1839]
## Environment (for bugs)

* JASP version: current 0.8.1.2
* OS name and version: Zorin OS educative version 9 and Trisquel OS
* Analysis: I have tried to install JASP on two different Linux based operating systems without success. Both systems are Ubuntu based: Zorin OS (educative version 9, https://zorinos.com/) and Trisquel OS (https://trisquel.info/). I have tried the instructions in the web https://jasp-stats.org/installation-guide/ but I was unable to get it installed. The message I got in both systems is quite similar. It seems my systems do not find the due packages. This is the message  I got when trying to install JASP in a fresh installation of Trisquel OS:

mipc:~$ sudo add-apt-repository ppa:jasp-uva/jasp 
[sudo] password for mipc: 
 JASP, a low fat alternative to SPSS, a delicious alternative to R. Bayesian statistics made accessible.
 Más información: https://launchpad.net/~jasp-uva/+archive/ubuntu/jasp
Pulse [Intro] para continuar o ctrl-c para cancelar

gpg: anillo «/tmp/tmpefl8dzk0/secring.gpg» creado
gpg: anillo «/tmp/tmpefl8dzk0/pubring.gpg» creado
gpg: solicitando clave A402E8BE de hkp servidor keyserver.ubuntu.com
gpg: /tmp/tmpefl8dzk0/trustdb.gpg: se ha creado base de datos de confianza
gpg: clave A402E8BE: clave pública "Launchpad PPA for JASP-UvA" importada
gpg: Cantidad total procesada: 1
gpg:               importadas: 1  (RSA: 1)
OK
mipc:~$ sudo apt-get update
Obj http://in.archive.trisquel.info belenos InRelease        
Obj http://in.archive.trisquel.info belenos-security InRelease                 
Obj http://in.archive.trisquel.info belenos-updates InRelease                  
Obj http://in.archive.trisquel.info belenos/main Sources                       
Obj http://in.archive.trisquel.info belenos/main i386 Packages                 
Obj http://in.archive.trisquel.info belenos/main Translation-es                
Obj http://in.archive.trisquel.info belenos/main Translation-en                
Obj http://in.archive.trisquel.info belenos-security/main Sources              
Obj http://in.archive.trisquel.info belenos-security/main i386 Packages        
Obj http://in.archive.trisquel.info belenos-updates/main Sources               
Obj http://in.archive.trisquel.info belenos-updates/main i386 Packages         
Obj http://ppa.launchpad.net trusty InRelease                                  
Obj http://ppa.launchpad.net trusty/main Sources                               
Obj http://ppa.launchpad.net trusty/main i386 Packages
Obj http://ppa.launchpad.net trusty/main Translation-en                  
Ign http://in.archive.trisquel.info belenos/main Translation-es_ES             
Ign http://in.archive.trisquel.info belenos-security/main Translation-es_ES    
Ign http://in.archive.trisquel.info belenos-security/main Translation-es       
Ign http://in.archive.trisquel.info belenos-security/main Translation-en       
Ign http://in.archive.trisquel.info belenos-updates/main Translation-es_ES     
Ign http://in.archive.trisquel.info belenos-updates/main Translation-es        
Ign http://in.archive.trisquel.info belenos-updates/main Translation-en        
Leyendo lista de paquetes... Hecho                                             
mipc:~$ sudo apt-get install jasp
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete jasp
mipc:~$ 

I am a new user of Linux and I would like some help to install the software in my computer, could you please give me some advice? Thanks a lot.
## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by FransMeerhoff** [comment]
Dear @JLPuga 
Of course we like to help you, but unfortunately we do not test JASP on all possible Linux OS variants. But we do on all Ubuntu LTS versions with Ubuntu Xenial 16.04 as the latest.   

- What  I can tell you is that we just (yesterday) updated the ppa with JASP 8.1.2. Perhaps something has crossed during your attempt. 
- However if the problem still occurs, because of your error 'No se ha podido localizar el paquete jasp', it is clear that Zorin or Trisquel can not find the Xenial-jasp version in the ppa:jasp-uva/jasp. Perhaps some systems manager at your site could help you with that. We  are busy with trying to find easier ways of distributing JASP versions on other Linux machines. If you have suggestions on Zorin OS  and Trisquel OS they are welcome. 

Kind regards 
Frans Meerhoff

**Comment by JLPuga** [comment]
Dear  @FransMeerhoff  

Firstly, thanks for the quick answer. 

I have tried it again today but the result was the same. The reason why I am using this Linux distros is because my machines are quite old and do not work with Ubuntu LST. I had even tried the Lubuntu distribution but the problem does disappears. Do you have any idea about how to help Zorin OS (this seems to be the fastest system for my machines) to find the Xenial-jasp version in the ppa?

Cheers,
Jorge.

**Comment by akashrajkn** [comment]
@JLPuga ZorinOS v9 is based on Ubuntu 14.04 (LTS) which is why it's not able to install the xenial packages from the ppa.

@FransMeerhoff Should we have the Trusty packages in the ppa?

**Comment by JLPuga** [comment]
Yes, @akashrajkn that is the thing, could it be solved @FransMeerhoff including the trusty packages in the ppa? Thanks!

**Comment by akashrajkn** [comment]
@JLPuga we now also ship a flatpak version. Check it out.

**Comment by JLPuga** [comment]
Ok, thanks a lot @akashrajkn.
