### ISSUE TITLE
Various t-test errors

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-desktop#1842]
## Environment (for bugs)

* JASP version: 8.1.2
* OS name and version: Ubuntu 16.04
* Analysis: t-tests

I just got the latest JASP from your Debian repo and took it for a spin out of pure procrastination. I'm considering JASP for a stats course in the fall, so I'm following you guys - excellent work! :-) I discovered a few bugs in the t-test analyses. While I'm at it, I also propose a few improvements.

# Frequentist independent t-test error:
The first thing I noticed: the frequentist independent samples t-test fails with an error on the Bugs dataset:

```
Error: could not find function 'startsWith'

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)

.hasErrors(dataset, perform, type = 'factorLevels', factorLevels.target = options$groupingVariable, factorLevels.amount = '≠ 2', exitAnalysisIfErrors = TRUE)
```

I haven't look into your project's development setup, but this should've been caught by a unit test?

# Bayesian t-test credible interval error
1. When selecting an informed prior, the plot does not update it's intervals. E.g. set a Normal(0, 0.001) prior. The effect of that should be visible on the plot, but I see no change.
2. It's not a "descriptive plot" if there are credible intervals since the latter are inferential. Maybe a title like "Plot of parameters" or the like?
3. It would be nice to get the credible interval(s) in a table as well. Perhaps under "additional statistics."

# Inconsistent t-test layout
When moving between the different types of t-test, the layout changes for fields where the content is the same. E.g. the box for entering the credible interval is indented more in paired samples than independent samples. This is true of Bayesian and frequentist analyses as well.

**Comment by JohnnyDoorn** [comment]
Hi Jonas,
Thanks for your interest and following! I can respond to your first and third inquiry - the second one is maybe for @quentingronau , as he implemented the subjective Bayesian t-test.
1. I have had this issue as well (I'm on Ubuntu 16.04), when I was still on an older version of R (I think I was at 3.2, when 3.4 was already out). Updating my R version fixed this error message - this startsWith function is probably a function that was included in R in the new version.
3. Thank you for catching this - I had already fixed the indentations and spacings for the frequentist t-tests a couple of days ago, so it should be in the next release! I will also take a look at the Bayesian tests and fix the indentations accordingly.
Kind regards,
Johnny

**Comment by AlexanderLyNL** [comment]
Does JASP depend on the R version that's installed on Ubuntu? If so, it might be good to take into account that JASP 0.8.1.2 runs on R 3.3.3 

Cheers,
Alexander

On 30 Jun 2017, at 13:52, JohnnyDoorn <notifications@github.com> wrote:

Hi Jonas,
Thanks for your interest and following! I can respond to your first and third inquiry - the second one is maybe for @quentingronau , as he implemented the subjective Bayesian t-test.

I have had this issue as well (I'm on Ubuntu 16.04), when I was still on an older version of R (I think I was at 3.2, when 3.4 was already out). Updating my R version fixed this error message - this startsWith function is probably a function that was included in R in the new version.Thank you for catching this - I had already fixed the indentations and spacings for the frequentist t-tests a couple of days ago, so it should be in the next release! I will also take a look at the Bayesian tests and fix the indentations accordingly.Kind regards,Johnny
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by EJWagenmakers** [comment]
The intervals in the descriptive plot are obtained under a flat prior. This
is why they do not change. The reason for using a flat prior is exactly
because the plot is descriptive.

Cheers,
EJ

**Comment by lindeloev** [comment]
@JohnnyDoorn @AlexanderLyNL I can confirm that upgrading from (system-wide) R 3.2.3 to 3.4.0 fixed the problem! I added the rstudio's R ppa.

@EJWagenmakers Thanks for clarifying regarding priors for the plot. At the risk of nitpicking AND bloating, maybe the fact that the prior is flat could be added as a figure text or tooltip for the setting? "Descriptives" usually has to do with properties of the sample while credible intervals are inferential. It's sometimes surprisingly hard for some students to understand the descriptive-inferential distinction so the JASP terminology could be confusing here.

**Comment by EJWagenmakers** [comment]
Yes, we certainly could clarify this a bit more. If this were a table we
could footnote it; putting text in the figure is a little to invasive. So I
am not 100% sure how to deal with this, other then to indicate this in the
help file....
The tooltip might work, but I'm not sure how easy it is to implement.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam, Nieuwe Achtergracht 129B
Letter: PO Box 15906, 1001 NK Amsterdam
Parcel: Valckenierstraat 59,  1018 XE Amsterdam

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Cell: (+31) 6 45626624

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by akashrajkn** [comment]
@lindeloev, thank you. On the matter of unit tests - 

I haven't been maintained (both R tests and core jasp unit tests) for a while. I will soon set up the tests and a CI so that such errors can be caught beforehand.

**Comment by AlexanderLyNL** [comment]
Koen is working on the credible intervals, don't worry about those.

**Comment by AlexanderLyNL** [comment]
Duplicate
