### ISSUE TITLE
unexpected termination of analysis

### ISSUE THREAD

**Issue by lfromkin** [jasp-stats/jasp-desktop#1847]
## Environment (for bugs)

* JASP version:
* OS name and version:
* Analysis: correlation matric 
## Environment (for enhancement requests)
 
* Enhancement:
* Purpose: told me to report the message below

This analysis terminated unexpectedly.

Error in cor.test.default(v1, v2, method = test, alternative = 'two.sided', : not enough finite observations

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback)

.correlationTable(dataset, perform, variables = options$variables, pearson = options$pearson, kendallsTauB = options$kendallsTauB, spearman = options$spearman, hypothesis = options$hypothesis, reportSignificance = options$reportSignificance, flagSignificant = options$flagSignificant, reportVovkSellkeMPR = options$VovkSellkeMPR, meansAndStdDev = options$meansAndStdDev, crossProducts = options$crossProducts, state = state, diff = diff, options = options)

cor.test(v1, v2, method = test, alternative = 'two.sided', conf.level = options$confidenceIntervalsInterval)

cor.test.default(v1, v2, method = test, alternative = 'two.sided', conf.level = options$confidenceIntervalsInterval)

stop('not enough finite observations')

**Comment by JohnnyDoorn** [comment]
Hi,
Thanks for reporting this. Could you please elaborate a bit on the data you are using? Are there any infinities or NA's in your data? If you can, could you share your dataset? That way we can try to replicate your issue and fix the bug you found. 
Kind regards,
Johnny

**Comment by boutinb** [comment]
No answer after 5 months, so this issue can be closed. This can be re-opened if necessary.
