### ISSUE TITLE
This analysis terminated unexpectedly

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-desktop#1848]
## Environment (for bugs)

* JASP version: 0.8.1.2
* OS name and version: MAC OS X El Capitan 10.11.6 (15G1510)
* Analysis: Linear regression

This analysis terminated unexpectedly.

Error in if (minimumPvalue < options$steppingMethodCriteriaPEntry) {: valor ausente donde TRUE/FALSE es necesario

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)

.stepwiseRegression(dependent.base64, independent.base64, dataset, options, weights)

.includeVariable(dependent.variable, old.candidate.variables, data, options, weights, new.variables.in.model)

**Comment by boutinb** [comment]
No answer after 5 months, so this issue can be closed. This can be re-opened if necessary.
