### ISSUE TITLE
Linear regression

### ISSUE THREAD

**Issue by akikicarole** [jasp-stats/jasp-desktop#1851]
Was trying to do a linear regression with the method: forward . I couldn't finish it because it stops working and give me this message 
**_"This analysis terminated unexpectedly. 
Error in summary(fits[[i]])$coefficients: $ operator is invalid for atomic vectors
Stack trace. 
To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports"_**

My JASP version is 0.8.1.2
i have window 7 Professional, version 2009, service pack 1

**Comment by akashrajkn** [comment]
@akikicarole can you please provide the dataset so that we can look into the problem?

**Comment by akashrajkn** [comment]
This issue could be related to #1848

**Comment by akashrajkn** [comment]
Could not reproduce this issue on the latest release (0.8.4). Please reopen this if it occurs
