### ISSUE TITLE
Cronbach alpha confidence interval

### ISSUE THREAD

**Issue by Marian-Popa** [jasp-stats/jasp-desktop#1853]
## Environment (for bugs)

* JASP version:
* OS name and version:
* Analysis:
## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by Marian-Popa** [comment]
Hi to the JASP Team! 
You did and do a great job, and I know what I say, beeing a long time SPSS teacher with psychology students.
I would like to suggest to add confidence interval for Cronbach alpha coeficient, which is insistently urged by some authors în the recent years.
(http://www.psyctc.org/stats/R/Feldt1.html)
Best wishes
Marian

**Comment by EJWagenmakers** [comment]
Yes, this is an excellent suggestion, also for the other measures. 
@vandenman?

**Comment by vandenman** [comment]
It's on my todo list!

**Comment by AlexanderLyNL** [comment]
Implemented in 8.2.0
