### ISSUE TITLE
Reliability analysis using Cronbach alpha is not completed

### ISSUE THREAD

**Issue by christance** [jasp-stats/jasp-desktop#1854]
## Environment (for bugs)

* JASP version: 0.8.1.2
* OS name and version: Windows 10
* Analysis: Reliability analysis
[jasp cronbach.docx](https://github.com/jasp-stats/jasp-desktop/files/1155389/jasp.cronbach.docx)

The analysis has been running for more than 5 minutes and has not completed.  There is no result for the analysis.  I have tried with less variables and it is able to complete the analysis.  But it seems to remain stuck when I include all 27 variables.  

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by FransMeerhoff** [comment]
Hi @christance 

Sorry to hear that.
Could you please send us the jasp file and/or the data you are using?
You can do that by adding these files to a zip file and drag and drop this file to this issue.

Kind regards
Frans Meerhoff

**Comment by christance** [comment]
[pilot data 180717.xlsx](https://github.com/jasp-stats/jasp-desktop/files/1155455/pilot.data.180717.xlsx)

I have to save as .xlsx format, because I can't paste .csv here.

**Comment by christance** [comment]
I also can't seem to upload the jasp file here.

**Comment by christance** [comment]
[180717 analysis.zip](https://github.com/jasp-stats/jasp-desktop/files/1155478/180717.analysis.zip)
Sorry, managed to do it.

**Comment by FransMeerhoff** [comment]
Hi  @christance 

Thanks a lot for for your data.
We will look what's going on there. And get back to you as soon as we know more about this issue.

@vandenman 
Can you have a look at this issue too?

Cheers Frans

**Comment by vandenman** [comment]
The problem is in `psych::glb`, which treats square datasets as correlation matrices regardless of whether they're symmetrical or not. This results in all kinds of troubles for symmetric input. I've written a fix for it but I need to test it a bit more thorough. I expect a PR on the weekend.
