### ISSUE TITLE
Labels for "Factor Scaling" options are switched

### ISSUE THREAD

**Issue by HeikoBreitsohl** [jasp-stats/jasp-desktop#1857]
## Environment (for bugs)

* JASP version: 0.8.1.2
* OS name and version: Win10
* Analysis: SEM
## Environment (for enhancement requests)
 
* Enhancement: Revise labels for "Factor Scaling" options
* Purpose: When using default settings (i.e. residual variance) in the SEM module, referent factor loadings are fixed to unity. Conversely, when selecting "Factor Loadings", factor variances are fixed to unity - according top the output. Maybe this is just a labeling problem in the options menu.
Keep up the great work!

**Comment by TimKDJ** [comment]
Thanks for notifying us! There is indeed a small error in the labels.
This will be fixed in the newest release.
