### ISSUE TITLE
Label does not change

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1861]
Clicking on a label does nothing, so I cannot rename it. EJ's laptop.

![labeldoesnotchange](https://user-images.githubusercontent.com/8603015/28468002-f935d9dc-6e31-11e7-8e28-07efbabf67ac.png)

**Comment by FransMeerhoff** [comment]
Hi @EJWagenmakers 

But a double  click should work, does that fail too on your laptop? 
(similar to editing the data)

Cheers Frans

**Comment by EJWagenmakers** [comment]
I was clicking like crazy, no response

**Comment by akashrajkn** [comment]
@FransMeerhoff I can take this issue if you are not working on it.
