### ISSUE TITLE
Feature request: Compute variable

### ISSUE THREAD

**Issue by emilycsd** [jasp-stats/jasp-desktop#1864]
Hello! I am using JASP for an (undergrad) introductory statistics course. I think for a novice stats software user, it would be helpful to have an option to compute a new variable without having to open another program (e.g., compute a simple mean composite score). I don't currently see a way to do this.
I also think being able to get descriptives with the file split on some variable would be helpful; I see that there was a prior thread on this but would like to add my support to this feature request. Thanks for a great program!

**Comment by AlexanderLyNL** [comment]
Dear Emily,

Thanks for your support and the suggestion. Regarding the computation of a new variable, perhaps the following video might help:

https://youtu.be/1dT-iAU9Zuc

As for the split function, this will be available in our next release that is due soon. I hope that this answers your questions. 

Cheers,
Alexander

**Comment by emilycsd** [comment]
Thanks for the tip and speedy response! 
I will have them edit that way for now, although I still think having a drop-down option would be nice for novice users.

**Comment by EJWagenmakers** [comment]
Give it a shot, you may find it is actually rather easy & cool (at least I
like to think so).
EJ

**Comment by AlexanderLyNL** [comment]
I'm closing this issue for my overview, but it doesn't mean that I'm not considering this. Please let us know how it went and if you have any other suggestions for jasp. We'll releasing descriptives with split functionality soon.
