### ISSUE TITLE
Tukey's test with ANOVA

### ISSUE THREAD

**Issue by PJCatUTexas** [jasp-stats/jasp-desktop#1871]
Your ANOVA provides a number of post hoc test options, one of which is Tukey's test. 
Tukey wrote several post hoc tests. The one you offer is Tukey's LSD, which has serious problems with alpha inflation. It isn't used much. The more commonly used Tukey's test is Tukey's HSD. 
LSD has sqrt((2*MSwithin)/n) in the denominator, while HSD uses sqrt(MSwithin/n) in the denominator. I believe the "car" package" (among others) in R calculates Tukey's HSD. 
Thanks for this great application. I'm using it teaching introductory statistics and it fills a real need.

**Comment by EJWagenmakers** [comment]
Thanks. We should add Tukey's HSD, and label them clearly as well (one "Tukey's HSD", the other "Tukey's LSD"). @vandenman @JohnnyDoorn

**Comment by PJCatUTexas** [comment]
Thanks so much for your response. Your solution—include both the HSD and LSD—is the right one.
I’m looking forward to using JASP in the classroom.
Best wishes,
Patrick Carroll

[cid:image001.png@01D30AA8.045A0BF0]

Patrick J. Carroll, Ph.D.
Department of Psychology
University of Texas at Austin
Austin, TX 78722
(512)477-3906
carroll@utexas.edu

**Comment by AlexanderLyNL** [comment]
Tukey correction for post hoc tests in ANOVA implemented

http://jasp-stats.org/download/
