### ISSUE TITLE
Unexpected termination

### ISSUE THREAD

**Issue by DrNateB** [jasp-stats/jasp-desktop#1873]
## Environment (for bugs)

* JASP 0.8.1.2:
* OS Sierra 10.12.6:
* I'm attempting to run a cronbach analysis and get this message. Thanks for any help in advance!:

This analysis terminated unexpectedly.

Error in items[, 1]: subscript out of bounds

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)

.reliabilityResults(dataset, options, variables, perform)

psych::alpha(dataAsMatrix, key = key)

response.frequencies(x, max = max)

nlevels(factor(items[, 1]))

levels(x)

factor(items[, 1])

**Comment by vandenman** [comment]
Hi thanks for reporting the bug! Could you perhaps send a .zip file with the dataset? That way, I can check whether the problem is solved in the current pull request with updates for the reliability analysis.

**Comment by boutinb** [comment]
No answer after 5 months, so this issue can be closed. This can be re-opened if necessary.
