### ISSUE TITLE
Include the leading zero in p-values

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-desktop#1876]
All p-values are printed without the leading zero (.123) while all other values include it (0.123). I'd propose to add the zero (1) for consistency and  (2) because the ".xxx" format is unfamiliar to some other countries (in Denmark at least) that don't have this strange habit of avoiding zeros ;-) The lacking zero occasionally confuses a few Danish students.

**Comment by EJWagenmakers** [comment]
Hi Jonas,

Our choice for this format is informed by the APA guidelines. If I recall correctly, the APA guidelines state that for scales that are always between 0 and 1 (like a p-value), the leading 0 is omitted. It would be straightforward to change, or add it as an additional option in the preferences. The upcoming version already has an option "display exact p-values" (see the JASP blogpost on the topic), so we could probably add this. @vankesteren, what do you think? (Erik-Jan is on vacation so his reply might take a while)

Cheers,
E.J.

**Comment by lindeloev** [comment]
Oh, you're right about the APA. Very good point! I'm closing this issue.
