### ISSUE TITLE
Feature Request: running multiple contingency tables

### ISSUE THREAD

**Issue by bazar0ff** [jasp-stats/jasp-desktop#1878]
Hello there.
I apologize if I'm not posting this stuff correctly, I'm new to github.

When I try to generate multiple contingency tables the output is one table repeated again and again for the number of tables that should actually be generated.  

For example if I select Q1 and Q2 as my rows and Q3 and Q4 as my columns, the output should be a table for every combination. 
Q1 v Q3
Q1 v Q4
Q2 v Q3
Q2 v Q4

What ends up getting produced is 4 copies of Q2 v Q4.

screenshot attached.

<img width="1440" alt="screen shot 2017-07-31 at 1 46 15 pm" src="https://user-images.githubusercontent.com/30602172/28790336-b04eaa2e-75f6-11e7-9fe8-bbef7a66a2a5.png">

Thoughts?
Thanks
Jay

**Comment by EJWagenmakers** [comment]
This behavior looks suboptimal. Guys, who can help fix this? This needs to be addressed before we release the next version, I would say. Jay, thanks for pointing this out! @TimKDJ @AlexanderLyNL 

Cheers,
E.J.

**Comment by TimKDJ** [comment]
Fixed in the new release. Thank you for pointing this out to us!
