### ISSUE TITLE
Summary Stats Module: Bug in informed t-test

### ISSUE THREAD

**Issue by FransMeerhoff** [jasp-stats/jasp-desktop#1879]
## Environment (for bugs)

* JASP version: 0.8.2
* OS name and version:
* Analysis: Informed -t-tes

When I tick "informed prior" and it is set to the same prior as the
default, the result is different.

**Comment by quentingronau** [comment]
![differentresultwithsamedefaultprior](https://user-images.githubusercontent.com/8697436/28816119-ee73944c-76a3-11e7-9acb-4ea9c4491da4.png)
![resultwithdefaultprior1](https://user-images.githubusercontent.com/8697436/28816120-ee74e61c-76a3-11e7-9a22-1176f51cc43e.png)
