### ISSUE TITLE
Bug in summary stats t-test plots?

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#1883]
Hi,

When using the Bayesian t-tests in the summary stats module, it appears that the BF in the plot does not match the one in the table? Also, note that in the robustness check plot, the dot for the user prior is not on the line.

Cheers,
Quentin
![bug_2](https://user-images.githubusercontent.com/8697436/28862652-10bf9a74-7766-11e7-9b23-b8d75016942d.png)
![bug_1](https://user-images.githubusercontent.com/8697436/28862653-10c166a6-7766-11e7-9140-1a22267be61e.png)

**Comment by akashrajkn** [comment]
Hi @quentingronau, do you have the latest code on your system? (The user prior is being plotted correctly on my system) I will take a look at the code either way.

**Comment by quentingronau** [comment]
Hi Akash,

Yes, I think so, I just did a rebase this morning.

Cheers,
Quentin

**Comment by akashrajkn** [comment]
Cool, I'll look into it.

**Comment by akashrajkn** [comment]
@quentingronau  I have submitted a pull request for this issue. The issue was with the parameter passing. The previous Bayes factor calculation function sent logBF, while the new function sends BF. The bug arose due to the mismatch.

Please review the pull request

**Comment by quentingronau** [comment]
Ok, great, thanks.
Quentin
