### ISSUE TITLE
ANOVA Type II and Type III issue

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1890]
From our contact form:

"I may be missing something, or this may be something that has been mentioned before. I have been testing JASP and have attempted the same analyses between SPSS from a colleague, R from myself, and now JASP using an ANOVA with two within-subjects variables, and one between-subject variable. Long story short, the values did not match and it seems to be that JASP is using type II as the default. I checked by playing with the options and the output was the same using type II and type III. Nothing major, just wanted to pass on this in case no-one had raised before (sorry if I've made a mistake or jumped the gun on something that is in development)."

Let's figure out what's going on before releasing the new version.
Cheers,
E.J.

**Comment by FransMeerhoff** [comment]
HI @JohnnyDoorn 

Can you have a look at this ?

**Comment by JohnnyDoorn** [comment]
Yes, I'll look at this when i get back from vacation!

**Comment by JohnnyDoorn** [comment]
So I checked out this issue,and it might be the case that the data are balanced, in which case the types of the ANOVA all provide the same results.
The R-code that JASP uses is quite straightforward:
```{r}
if (options$sumOfSquares == "type1") {
				SSt <- sum(result[,"Sum Sq"], na.rm = TRUE)

			} else if (options$sumOfSquares == "type2") {

				result <- car::Anova(model, type=2)
				SSt <- sum(result[,"Sum Sq"], na.rm = TRUE)

			} else if (options$sumOfSquares == "type3") {

				result <- car::Anova(model, type=3, singular.ok=TRUE)
				SSt <- sum(result[-1,"Sum Sq"], na.rm = TRUE)

			}
```
So I do not think it's a problem with JASP. Did the submitter include a datafile/R-code that he used?

**Comment by TimKDJ** [comment]
@JohnnyDoorn you can find R code in the email I forwarded (titled "Fw: New Message via the JASP Website").

**Comment by AlexanderLyNL** [comment]
Consistency between R, SPSS and JASP fixed
