### ISSUE TITLE
JASPEngine processes remain active in memory after opening/closing GUI on Ubuntu

### ISSUE THREAD

**Issue by bogdanlalu** [jasp-stats/jasp-desktop#1894]
## Environment (for bugs)

* JASP version: 0.8.1.2
* OS name and version: Ubuntu 16.04 LTS
Linux 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Analysis: irrelevant - this occurs every time after using  the software
## Problem description
Everytime I open and close the GUI there are 4 processes that remain in memory taking up some RAM.
What I have noticed today is that this seems to stack up - I have opened the GUI 3 times and closed it and now I have 12 processes still active, each taking between 33-120 MB RAM in my case.
![screenshot from 2017-08-04 08-46-06](https://user-images.githubusercontent.com/16867980/28959423-3e159284-78f2-11e7-9cc6-fee09c03b394.png)

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by AlexanderLyNL** [comment]
We'll have a look at it once a couple of people are back.

**Comment by aknight1-uva** [comment]
Cant reproduce with upstream/development (15-08-2917) on ubuntu: 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aknight1-uva** [comment]
@bogdanlalu
I have noticed that ubuntu 16:04 has had a couple of kernel updates in the last couple of weeks (I update dally). I would suggest that you try again after updating Ubuntu OS. If this doesn't help, we are going to have to try and figure-out how your Ubuntu installation is different from mine.
-- 
Patrick

**Comment by bogdanlalu** [comment]
@aknight1-uva Hi there. I'm updating every few days. The problem is still there, even today.
If I run 'uname -a ' i get this:
Linux 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Please let me know what other info you might need, I'm happy to help.

**Comment by akashrajkn** [comment]
@aknight1-uva I got this issue on mac (tested on Sierra) also. Here's a way to reproduce it - 

Use a large dataset (tested on a 14MB file). Run Bayesian Linear Regression (it takes a lot of time due to the size of the dataset). Close JASP before getting the output. Ideally this should kill all the child processes.

But for this scenario, "JASPEngine 0" process is orphaned and continues to execute even after JASP app is exited.

**Comment by boutinb** [comment]
Solved by #2066
