### ISSUE TITLE
crash just after start

### ISSUE THREAD

**Issue by Mat-Teusz** [jasp-stats/jasp-desktop#1896]
## Environment (for bugs)

* JASP version: 8.2.0
* OS name and version: Microsoft Windows 10 Enterprise Version 10.0.15063 Build 15063 
* System Type:	x64-based PC
* Description: the app crashes just after start (start app-->crash - no actions between). Got runtime error - "this application has requested the Runtime to terminate it in an unusual way".

**Comment by AlexanderLyNL** [comment]
I'll merge this with #1897
