### ISSUE TITLE
"Welcome to JASP" screen does not vanish when you want to start analysis

### ISSUE THREAD

**Issue by Mat-Teusz** [jasp-stats/jasp-desktop#1897]
## Environment (for bugs)

* JASP version: 8.1.2
* OS name and version: Microsoft Windows 10 Enterprise Version 10.0.15063 Build 15063 
* System Type:	x64-based PC
* Description: when i'm using JASP i have an issue with "Welcome to JASP" screen showed on the right side of the window. When i'm going into analysis (no matter what analysis exactly) "Welcome to JASP" screen should vanish but it is not. 
![jasp issue](https://user-images.githubusercontent.com/13604072/28994906-3903bca6-79da-11e7-9db8-3e324d05186f.PNG)

**Comment by FransMeerhoff** [comment]
Hi @Mat-Teusz 

Because you've posted 2 issues on this subject could you lets check the following first:
- Uninstall JASP (Via Right Click on Start->Apps and Features . Search for any JASP version and Un-Install.)
- Install the latest pre-release version from https://static.jasp-stats.org/JASP-0.8.2.0-Setup.exe
- Run some example file from JASP and check if you have the same problem.

Kind regards
Frans Meerhoff

**Comment by matwod11** [comment]
Hi @FransMeerhoff 

i've tried with 0.8.2.0 already :) The second issue that i posted is from 0.8.2.0 version.

Cheers,
Mateusz

**Comment by FransMeerhoff** [comment]
Hi @Mat-Teusz 

Thank you for helping us with such hard to find, for us unreproducible problems.
Can you answer or try the following;
- Does this problem only occurs on the latest versions of JASP or are you new to JASP?
- Can you try to start JASP as administrator and check if hat makes any difference. (You can do this by starting the explorer, go to the JASP installation folder e.g. c:\Program Files\JASP 0.8.2.0
and right click JASP.exe and run as administrator)
- I've uploaded a zipped installation version of JASP at  https://static.jasp-stats.org/JASP-0.8.2.0-64-bit.zip Could you download that file, unzip it at some location and run JASP.exe from there?

Thanks in advance
Cheers
Frans Meerhoff

**Comment by matwod11** [comment]
> Does this problem only occurs on the latest versions of JASP or are you new to JASP?
The last time when i used JASP it was around 3-5 months ago and then everything was fine (same device, same OS, only a bit older version).

> Can you try to start JASP as administrator and check if hat makes any difference. (You can do this by starting the explorer, go to the JASP installation folder e.g. c:\Program Files\JASP 0.8.2.0
and right click JASP.exe and run as administrator)
Already did this. No success. 

> I've uploaded a zipped installation version of JASP at https://static.jasp-stats.org/JASP-0.8.2.0-64-bit.zip Could you download that file, unzip it at some location and run JASP.exe from there?
Will try and let you know.

Cheers,
Mateusz

**Comment by FransMeerhoff** [comment]
Hi @Mat-Teusz 

I was wandering what the state of this issue is.
Did the zipped version of JASP work for you?

Kind regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
@Mat-Teusz 

If you still have this problem, please reopen it.
