### ISSUE TITLE
crash after data editing

### ISSUE THREAD

**Issue by vdsmagt** [jasp-stats/jasp-desktop#1898]
## Environment (for bugs)

the following crash occurred after editing data within Jasp => excel (see the picture)
![screen shot 2017-08-07 at 11 17 37](https://user-images.githubusercontent.com/17410938/29020402-2d366156-7b62-11e7-80f7-37fbddd7a4b5.png)
It was a simple two column data file, with a grouping variable and a data variable). I added more data, but with the data column first. After saving the file in excel  (I think, might have been earlier) Jasp gave me the error message. restarting Jasp and opening the same Jasp file makes Jasp crash again.
* JASP version: 0.8.1.2
* OS name and version: Mac OS 10.12.6
* Analysis: ?

**Comment by FransMeerhoff** [comment]
Hi @vdsmagt 

Although you mention that is a simple to column data file, can you please send this file to us.
You can add it to a zip file and drag and dropout to this issue .
Thanks in advance.

Kind Regards
Frans Meerhoff

**Comment by vdsmagt** [comment]
[Archive.zip](https://github.com/jasp-stats/jasp-desktop/files/1213842/Archive.zip)
Both the accompanying csv file and the jasp file

**Comment by FransMeerhoff** [comment]
Hi @vdsmagt 

Thanks for the data.
I'm now able to reproduce the error.
When there is a solution (or a temporary work around) we let you know soon.

Kind regards 
Frans Meerhoff

**Comment by boutinb** [comment]
I think this problem has been solved. I cannot reproduce this problem with the new version 0.8.5.
