### ISSUE TITLE
chronbach's alpha

### ISSUE THREAD

**Issue by herzogcollege** [jasp-stats/jasp-desktop#1899]
Does the latest version of JASP offer chronbach's alpha and if so where can I find it?

**Comment by EJWagenmakers** [comment]
It's under Descriptives -> Reliability Analysis

Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam, Nieuwe Achtergracht 129B
Letter: PO Box 15906, 1001 NK Amsterdam
Parcel: Valckenierstraat 59,  1018 XE Amsterdam

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Cell: (+31) 6 45626624

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by herzogcollege** [comment]
The answer is yes and its under descriptive statistics.

**Comment by AlexanderLyNL** [comment]
I love these fairy tale endings! Please let us know if something else is unclear.
