### ISSUE TITLE
Feature request: Logistic regression

### ISSUE THREAD

**Issue by JimWeinrich** [jasp-stats/jasp-desktop#1901]
* Enhancement: Logistic regression
* Purpose:
I read somewhere that logistic regression is on your list of planned enhancements. Please add my name to the list of people who want this. Thanks!

**Comment by FransMeerhoff** [comment]
Hi @JimWeinrich 

Thanks for your notification. Good for us to know in which enhancements people are really interested in.
And it is indeed on our planned enhancements. We are in the test phase of version JASP 8.2.0 but I can assure you that the release after that will contain it. 

Kind regards
Frans Meerhoff
