### ISSUE TITLE
JASP Version 0.8.1.2 on Mac OSX 10.8.5

### ISSUE THREAD

**Issue by Zasahan** [jasp-stats/jasp-desktop#1905]
## Environment (for bugs)

* JASP version: 0.8.1.2 
* OS name and version:Mac OSX 10.8.5
* Analysis: Almost all of the possible analyses (descriptives, T-tests, etc.)
This error pops up for descriptives:
Error: package or namespace load failed for 'stats'

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)

.descriptivesDescriptivesTable(dataset, options, run, last.stats.table)

(function (name, package, ...) 
{
    name <- paste0(name, '')
    rm(list = name, envir = .AutoloadEnv, inherits = FALSE)
    m <- match.call()
    m$name <- NULL
    m[[1]] <- as.name('library')
    eval(m, .GlobalEnv)
    autoload(name, package, reset = TRUE, ...)
    where <- match(paste('package', package, sep = ':'), search())
    if (exists(name, where = where, inherits = FALSE)) 
        eval(as.name(name), as.environment(where))
    else stop(gettextf('autoloader did not find '%s' in '%s'', name, package), domain = NA)
})(name = 'xtabs', package = 'stats')

eval(m, .GlobalEnv)

eval(expr, envir, enclos)

library(package = 'stats')

stop(gettextf('package or namespace load failed for %s', sQuote(package)), call. = FALSE, domain = NA)

**Comment by FransMeerhoff** [comment]
Hi @Zasahan 

Let's first check if the stats package is available after out installation.
Out R installed packages reside in 
/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.3/Resources/library
Could you check if the 'stats' package is available there?

Kind Regards
Frans Meerhoff

**Comment by Zasahan** [comment]
Hello
Thanks for helping out
The stats package is available in that location

**Comment by FransMeerhoff** [comment]
Hello @Zasahan 

Sorry for this late response, but we were quite busy releasing a new version on JASP.
So the question is :
Could you try if your problem is solved with the latest version of JASP 0.8.2 see https://jasp-stats.org/download/
 If not we have to investigate this issue further.

Kind Regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Hello @Zasahan 

If you still have this problem please reopen this issue.

Kind regards
Frans Meerhoff

**Comment by Milan3462** [comment]
Hi there, have the same problem, just downloaded the latest version (8.3) and still have it now too...

-I was unable to verify what you stated as " Let's first check if the stats package is available after out installation. Out R installed packages reside in
/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.3/Resources/library
Could you check if the 'stats' package is available there?"

- I unfortunately didn't understood what it mean. I looked for Jasp.app in my application but couldn't find it. I do have the Jasp software though.

Cheers
