### ISSUE TITLE
Uninformative error message when repeated-measures factor name matches a between-subjects factor name

### ISSUE THREAD

**Issue by tvickery** [jasp-stats/jasp-desktop#1906]
## Environment (for bugs)

* JASP version: 0.8.1.2
* OS name and version: Platform-independent (test Windows 10 + macOS Sierra)
* Analysis: If you name a repeated-measures factor the same name as a between-subjects factor in a mixed-effects anova, you receive an uninformative error message (pasted below). I eventually discovered that I had done this, but the error greatly puzzled me and it took some time for me to figure out what I had done. The code currently doesn't appear to check for this and warn the user.

ERROR MESSAGE THIS YIELDS:

This analysis terminated unexpectedly.

Error in t.test.default(unlist(postHocData[listVarNamesToLevel[[k]]]), : 'y' is missing for paired test

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)

.resultsPostHoc(referenceGrid, options, dataset, fullModel)

t.test(unlist(postHocData[listVarNamesToLevel[[k]]]), unlist(postHocData[listVarNamesToLevel[[i]]]), paired = T, var.equal = F)

t.test.default(unlist(postHocData[listVarNamesToLevel[[k]]]), unlist(postHocData[listVarNamesToLevel[[i]]]), paired = T, var.equal = F)

stop(''y' is missing for paired test')

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by TimKDJ** [comment]
You are correct, we do not check for this. 
I can imagine that the error message left you rather confused ;)

It shouldn't be a very hard thing to add. Thanks for notifying us!

**Comment by JohnnyDoorn** [comment]
This issue will be fixed in the next release, I just updated the code!
