### ISSUE TITLE
B PS T-Test: error with particular analysis

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#192]
using ssgo-fred2.csv

![screen shot 2015-01-19 at 6 06 12 pm](https://cloud.githubusercontent.com/assets/3240247/5804404/e83650fa-a005-11e4-965c-5826977981cd.png)

**Comment by jonathon-love** [comment]
I can produce the same error in the B IS T-Test too.

**Comment by quentingronau** [comment]
Has been fixed with another commit.
