### ISSUE TITLE
PostHoc output disappears

### ISSUE THREAD

**Issue by kevinvschie** [jasp-stats/jasp-desktop#1921]
## Environment (for bugs)

* JASP version: 0.8.2.0
* OS name and version: Windows 7 Enterprise
* Analysis: posthoc test after BANOVA

Running posthocs seems to work fine. JASP produces an output table. However after a couple of sections the output table is removed. It's possible to rerun the posthoc tests and the output table appears again, but after that it disappears too.

**Comment by AlexanderLyNL** [comment]
Hi Kevin,

Could you please send us the JASP file in a zip file? Then we can have a look at it.

Cheers,
Alexander

**Comment by kevinvschie** [comment]
Sure, where can I send it too?

**Comment by AlexanderLyNL** [comment]
a.ly@uva.nl please.

**Comment by TimKDJ** [comment]
Thanks for bringing this to our attention @kevinvschie!
I can reproduce the problem and will work on a fix.
This appears to be an older bug (I can also do reproduce it in the frequentist RM ANOVA of version 0.8.1.2).
