### ISSUE TITLE
eps export and text

### ISSUE THREAD

**Issue by vdsmagt** [jasp-stats/jasp-desktop#1928]
## Environment (for bugs)

* JASP version: 0.8.2.0 (and earlier)
* OS name and version: mac os 10.12.6 
* Analysis:
Text on graphs exported to .eps (and .pdf in the newest version) is highly pixelated, also missing symbols. The latter also occurs for the conversion to .tiff. Is there a problem embedding (or converting) fonts? In fact, the only 'nice' export is the .png version, but this cannot be edited (by for instance AI). Importing the .eps or .pdf in AI makes it possible to select the individual 'letters' and remove them of course (it recognises them as bitmaps), so I can still edit the figure and replace
 the text with a normal font. But this is not ideal.

I have attached there 4 output versions of the same figure, and in case this is mac (or _my_ mac) specific also included a screenshot of all of them side by side.
[testimages.zip](https://github.com/jasp-stats/jasp-desktop/files/1248032/testimages.zip)

**Comment by TimKDJ** [comment]
That is definitely not right.
@vankesteren can you have a look at this?

**Comment by vdsmagt** [comment]
I guess this issue can be closed as the output scales and is not pixelated anymore in 9.0.1.

**Comment by AlexanderLyNL** [comment]
Thanks for informing us on this.
