### ISSUE TITLE
Bayesian correlation pairs error

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1933]
Bayesian correlation pairs allows you to enter multiple pairs of values. If you take the Big 5 data set, and enter the pair "Neuroticism - Conscientiousness" multiple times, the third time gives an uninformative error. 
@AlexanderLyNL 
![terminatedunexpectedlymultiplepairs](https://user-images.githubusercontent.com/8603015/29660716-47c2911c-88c2-11e7-9e69-603c23be7b72.png)

**Comment by AlexanderLyNL** [comment]
This also happens to the Bayesian paired t-test when the prior and posterior plots are selected. It's a state problem. I'm thinking about redesigning these two analysis as it also brushes on the plot problem.

**Comment by AlexanderLyNL** [comment]
This is fixed for both the paired t-test and correlation.
