### ISSUE TITLE
Feature request: add Robusteness check additional info of summary stat to the main analyses 

### ISSUE THREAD

**Issue by tressoldi** [jasp-stats/jasp-desktop#1936]
* Enhancement: add Robusteness check additional info of summary stat to the main analyses
* Purpose: it is a useful info to have also for the the "non summary" stats

**Comment by EJWagenmakers** [comment]
@akashrajkn 
I agree it would be nice if the t-test in JASP common has the same cool robustness check functionality as the t-test in JASP Summary Stats. We'll deal with this.
Cheers,
E.J.

**Comment by AlexanderLyNL** [comment]
I'll manage this.
