### ISSUE TITLE
Bug in sum stats t-test with informed priors

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1943]
See attach
![buginttest](https://user-images.githubusercontent.com/8603015/29822178-dfb0faac-8cca-11e7-8dc0-2f74a90befb7.png)

**Comment by FransMeerhoff** [comment]
Hi @akashrajkn 
See you soon!
Can you have a look at this one, or assign it to the proper person?

**Comment by EJWagenmakers** [comment]
Quentin might want to help out here.
EJ

**Comment by AlexanderLyNL** [comment]
Fixed
