### ISSUE TITLE
Unstable behaviour in sum stats for t-test with informative prior

### ISSUE THREAD

**Issue by hoogkpx** [jasp-stats/jasp-desktop#1944]
![sumstats_v1](https://user-images.githubusercontent.com/14014358/29822652-7a1a34b8-8ccc-11e7-8465-2c87ef34131e.png)
![sumstats_v2](https://user-images.githubusercontent.com/14014358/29822653-7a1c89d4-8ccc-11e7-89c3-662c7c7c02ee.png)

## Environment (for bugs)

* JASP version: 0.8.2.0
* OS name and version: Windows 7 (64 bit)
* Analysis: sum stats t-test
## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by EJWagenmakers** [comment]
The error message is unavoidable, but its contents may be improved; instead of "infinite value encountered" it should say something along the lines of "posterior too peaked" (or: prior too peaked). @quentingronau, maybe you know best who can help fix this -- @TimKDJ perhaps?

**Comment by akashrajkn** [comment]
Changed error message in #2634
