### ISSUE TITLE
Display (optionally) more or less decimal digits (e.g., for correlations)

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#1945]

**Comment by mvanlaethem** [comment]
Yes, that would be great. I often use 2 decimals in correlation tables, it would come in handy to be able to switch the amount of decimal places after the point from 3 to 2.

**Comment by EJWagenmakers** [comment]
Is the number of decimal places a setting we could make general, just as we did for exact p-values? Would allow users to quickly obtain more or fewer decimal places upon demand, for any analysis.
E.J.

**Comment by TimKDJ** [comment]
I think we can make this a general preference.
I'll have a look.
