### ISSUE TITLE
Flip (maybe optionally) the correlation table in such a way that all correlations are displayed below the diagonal instead of above the diagonal

### ISSUE THREAD

**Issue by mvanlaethem** [jasp-stats/jasp-desktop#1946]
![screen shot 2017-08-29 at 15 55 31](https://user-images.githubusercontent.com/31443403/29824703-86d251c6-8cd2-11e7-9c4e-3255f0c710f7.png)

Example of how it looks now.

![screen shot 2017-08-29 at 15 54 36](https://user-images.githubusercontent.com/31443403/29824708-87d8575a-8cd2-11e7-9a57-02a4a8e509b2.png)

How it would be even more helpful for exporting to word and creating correlation tables for publication (ignore the M and SD).

**Comment by EJWagenmakers** [comment]
Agreed! 👍 
@TimKDJ , can you take care of this, or find somebody else to do so? :-)

**Comment by TimKDJ** [comment]
Yes, I'll add an option to flip the table.
