### ISSUE TITLE
JASP-Tests broken on Windows

### ISSUE THREAD

**Issue by aknight1-uva** [jasp-stats/jasp-desktop#1951]
* JASP version: upstream/development (as of 31-08(
* OS name and version: Windows (any)
* Analysis: Automated tests in JASP-Tests are broken: Test files directory cannot be found, resulting in an unhandled exception - The basic reason for this is that path-names of the form
some-dir\\..\\someother-dir are illegal on windows.
* Steps to reproduce:  Run on Windows

**Comment by AlexanderLyNL** [comment]
Hi Patrick, 

Am I correct that this relates to issue #1911 ?

Cheers,
Alexander

**Comment by akashrajkn** [comment]
@aknight1-uva JASP-Tests project searches for TestFiles. you need to unpack the TestFiles.zip present in the path: Resources/

PS: Restructuring (and rewriting) the tests is on top my list. I will implement it in the near future.
Cheers.

**Comment by aknight1-uva** [comment]
_As written_, the tests are supposed to unpack themselves: They don't since the library that is supposed to  unpack them cannot find the library.
