### ISSUE TITLE
Issue with generating prior/posterior plot in paired samples t-test

### ISSUE THREAD

**Issue by paystobebayes** [jasp-stats/jasp-desktop#1958]
## Template for bug reports

* JASP version: 0.8.2
* OS name and version: Windows 7 
* Analysis: Bayesian Paired Samples T-Test
* Steps to reproduce: 1. Open Bayesian Paired Samples T-Test procedure; 2. enter more than one pair of variables to compare in the right hand box; 3. request prior and posterior with additional info under plots; 4. for every prior/posterior plot after the first one, an error message will come up saying "missing value where TRUE/FALSE needed."

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by TimKDJ** [comment]
Thanks for opening the issue Nathan.

Unfortunately, I can't reproduce the problem you describe.
If I add three pairs, I receive three prior/posterior plots.
I'm guessing this is unique to your data. 
Is there any chance you could attach the .jasp file here with the problem you describe? (just go File -> Save As and then .zip it) 
Alternatively you may send the .jasp file to t.dejong@jasp-stats.org

**Comment by paystobebayes** [comment]
Tim,

Sorry for the delay in responding. I just recently tried this procedure
again with the same data file and the problem did not emerge again. Sorry
for the confusion on this. Seems to have been a one time hiccup.

Thanks,
Nathan

**Comment by AlexanderLyNL** [comment]
Awesome, thanks for getting back to us. Please reopen if the problem returns. Thanks for your feedback.

Cheers,
Alexander
