### ISSUE TITLE
Vovk-Sellke option makes correlation crash

### ISSUE THREAD

**Issue by TimKDJ** [jasp-stats/jasp-desktop#1959]
* JASP version: 0.8.2
* OS name and version: macOS Sierra
* Analysis: Correlation Matrix
* Steps to reproduce:
1) From debug.csv add "debCollin1", "debCollin2" and "contNormal"
2) Tick "Flag significant correlations"
3) Tick "Vovk-Sellke maximum p-ratio"

I think the cause lies in the footnote the Vovk-Sellke option tries to add.

Edit: somewhat related, if you add "debInf" and then remove some other variable, the infinity footnote disappears.

**Comment by JohnnyDoorn** [comment]
I just talked to Quentin (macOS Sierra 10.12.6) and Don (windows 10), who also could not replicate the issue, just like myself (ubuntu 16.04). I'll discuss it with the developers, maybe they can zoom in on when/where this happens..
