### ISSUE TITLE
B T-Tests, figures and tables should format BFs to the same decimal places

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#196]

**Comment by jonathon-love** [comment]
At the moment we do tables to 3 decimal places, where as figures go to 2. We should make these consistent. I don't mind which way, maybe @EJWagenmakers cares?

**Comment by jonathon-love** [comment]
Also, scientific notation can contain a dash, i.e.

1.35e-34

the dash is a different width to the plus sign, so they don't align, i.e.

1.35e-34
1.35e+26

however, a minus sign is the same width as a dash, so it's nice if you string replace all dashes for minuses before plotting, i.e.

1.35e−34
1.35e+26

you can get a minus sign in R with "\u2212"

**Comment by EJWagenmakers** [comment]
Safest to go to 3.
EJ
