### ISSUE TITLE
JASP 0.8.2.0 error when starting up

### ISSUE THREAD

**Issue by kpeenz** [jasp-stats/jasp-desktop#1965]
## Template for bug reports

* JASP version: 
0.8.2.0
* OS name and version: 
Microsoft Windows 10
* Analysis: 
Installed JASP during last week (3 to 8 September).  It seems to have worked fine with initial tests using the sample data files included.  I upgraded Microsoft Office from 2007 to Office 365 (Office 16) this weekend and cannot get JASP to work.  The error message as displayed is as per attached Word doc.

* Steps to reproduce: See above
[JASP_Bug.docx](https://github.com/jasp-stats/jasp-desktop/files/1293627/JASP_Bug.docx)

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by kpeenz** [comment]
Problem solved by uninstalling, rebooting the PC, then rerunning the installation after checking that the Program Files folders were all gone.  It now works again.

**Comment by AlexanderLyNL** [comment]
Hi Kpeenz, 

Thanks for reaching out. Glad to know that this got fixed.

Cheers,
Alexander
