### ISSUE TITLE
opening PSPP authored SAV files fails

### ISSUE THREAD

**Issue by sebwin** [jasp-stats/jasp-desktop#1966]
## Template for bug reports
* JASP version: 0.8.2
* OS name and version: macOS 10.12.6
* Analysis: JASP successfully opens SPSS authored SAV files, but fails to open PSPP authored files. Previous versions opened them without problem.
* Returns: "Unable to open file. Cannot find charactor [sic.] set ascii"
* Steps to reproduce: Try opening attached SAV file.
[test.zip](https://github.com/jasp-stats/jasp-desktop/files/1295821/test.zip)

**Comment by boutinb** [comment]
@sebwin I found the problem. This will be fixed in the next release (beginning of oktober).
