### ISSUE TITLE
Weird labels appear when changing the type of a variable

### ISSUE THREAD

**Issue by vandenman** [jasp-stats/jasp-desktop#1970]
## Template for bug reports
* JASP version: 0.8.2
* OS name and version: Windows 10
* Analysis: NA
* Steps to reproduce: 

1) Open Debug dataset
2) Click on variable type Icon of "debBinMiss20"
3) Change to Numeric
4) Change back to Ordinal
5) Observe that suddenly -2147483648 appeared as label.
6) Next, running Descriptives with "debBinMiss20", tick Display frequency tables and the label appears again, with frequency 0.

**Comment by boutinb** [comment]
Solved by Pull Request #2030
