### ISSUE TITLE
404 Repository Not Found

### ISSUE THREAD

**Issue by PeeWeed** [jasp-stats/jasp-desktop#1973]
Hi,
since the JASP is an open source 'SPSS' we use at the university I have tried to run it on my Ub (Ubuntu 16.10). I followed the install guide but as far as I could get the terminal reports me this:

> W: The repository 'http://ppa.launchpad.net/jasp-uva/jasp/ubuntu yakkety Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> W: The repository 'http://ppa.launchpad.net/jonathon-love/jasp/ubuntu yakkety Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> W: The repository 'http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu yakkety Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Download failed http://ppa.launchpad.net/jasp-uva/jasp/ubuntu/dists/yakkety/main/binary-i386/Packages  404  Not Found
> E: Download failed http://ppa.launchpad.net/jonathon-love/jasp/ubuntu/dists/yakkety/main/binary-i386/Packages  404  Not Found

The system seems to meet some authentification issues for your repositories. If you have an idea how to help?
Thanks

**Comment by FransMeerhoff** [comment]
Hello @PeeWeed 

Yes,  unfortunately we do the (always planned) support of all the LTS versions of Ubuntu so 16.04 Xenial the latest LTS version will work. In between we try to deliver as much versions (you can imagine that it is quite time consuming support all the linux versions).  At this time we  do plan to deliver the Ubuntu 17.04 version for the next release JASP. 

Kind regards
Frans Meerhoff
