### ISSUE TITLE
JASP Crashed after attempting to exclude an interaction effect term from Bayesian repeated measures ANOVA that was restored from a JASP file

### ISSUE THREAD

**Issue by xxelloss** [jasp-stats/jasp-desktop#1975]
## Template for bug reports

* JASP version: 0.8.2
* OS name and version: macOS 10.12.6
* Analysis: Bayesian repeated measures ANOVA
* Steps to reproduce: 
1. open the previously saved jasp file [https://drive.google.com/file/d/0B7d0K6pqVbHHcy1HTS1WNzJCVFU/view?usp=sharing](url) containing Bayesian repeated measures ANOVA
2. in the model tab, try to exclude the interaction effect
3. JASP is crashed

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by vandenman** [comment]
Replicated on windows 10. The supplied link didn't work for me but a slight modification of it did. Attached the .zip. [bf_trans.zip](https://github.com/jasp-stats/jasp-desktop/files/1313332/bf_trans.zip)

**Comment by AlexanderLyNL** [comment]
Fixed in 0.9.1

http://jasp-stats.org/download/
