### ISSUE TITLE
Cohen's d CIs change with hypothesis direction

### ISSUE THREAD

**Issue by SvenHeim-UDE** [jasp-stats/jasp-desktop#1977]
[cohens_wild-cis.zip](https://github.com/jasp-stats/jasp-desktop/files/1314628/cohens_wild-cis.zip)

## Template for bug reports

* JASP version: 0.8.2
* OS name and version: Arch Liunx
* Analysis: Frequentist Independent Samples t-Test
* Steps to reproduce: Attached .jasp File

See attached minimal dataset. 

If the direction of hypothesis testing is changed, the CIs for _d_ change, which should not be the case. As far as I know, _d_ and its CI should be independent of the test direction, because it's based on _M_, _SD_ and _NCP/t_ as parameter for CI. And none of these parameters change when the hypothesis testing direction is changed. I don't know what JASP uses for effect size CI calculation, but MBESS (which I use for effect size CIs) has a good reputation to be quite reliable.

**Comment by SvenHeim-UDE** [comment]
Ok, nevermind. Should have read Chapter 4 of Cumming (2014) on one-sided CIs. Stuff like that was not even barely mentioned in any of my stats courses.

**Comment by EJWagenmakers** [comment]
One-sided CI are interesting and, imo, pretty counter-intuitive!
E.J.

**Comment by SvenHeim-UDE** [comment]
I completely agree. At first, it was a mindbender. But for starters I got a basic idea.

**Comment by SvenHeim-UDE** [comment]
I completely agree, At first, it was a mind bender. But for starters I got a basic idea.
