### ISSUE TITLE
logBF discrepancy

### ISSUE THREAD

**Issue by xxelloss** [jasp-stats/jasp-desktop#1981]
## Template for bug reports

* JASP version:
* OS name and version:
* Analysis:
* Steps to reproduce: 

## Template for enhancement requests
 
* Enhancement: There is a discrepancy between the way to calculate logBF in the cases of Bayesian AN(C)OVA and correlation analysis. In the case of Bayesian AN(C)OVA, the option logBF calculates log e BF (natural log). On the other hand, in the case of Bayesian correlation analysis, the option logBF calculates log 10 BF. 
* Purpose: This issue should be addressed to make the overall notations consistent across the whole JASP.

**Comment by EJWagenmakers** [comment]
Good point. We should use natural logs everywhere, it is what people expect.
E.J.
