### ISSUE TITLE
Continous data graphed as ordinal in distribution plots

### ISSUE THREAD

**Issue by JimWeinrich** [jasp-stats/jasp-desktop#1982]
## Template for bug reports
* JASP version: 0.8.2.0
* OS name and version: Mac OS X 10.11.6
* Analysis: Descriptives
* Steps to reproduce: 
Choose "Descriptive statistics", then "Display distribution plots"
If there are gaps in the distribution (i.e., a variable with values of 1, 2, 3, 6, 7, 8, but no cases with 4 or 5) the distribution is plotted as if the variable consists of categories, so the bar for "3" is adjacent to the bar with "6".

If the variable is set to Nominal, this is the correct behavior. If it is set to Ordinal, it is arguably the correct behavior. If it is set to Continuous (ruler icon), this is incorrect; there should be a gap in the histogram that shows that cases with values of 4 or 5 are absent.

Sample csv data set is pasted at the end of this report.

If a variable's values are all decimal numbers that happen to equal integers (e.g., 3.0), the data are graphed as if they are ordinal, not continuous, even though the ruler icon correctly appears at the head of the column. Some of the data must have a non-zero decimal part (e.g., 3.1) in order for the variable to be graphed as continuous.

An additional problem is that users apparently cannot adjust the bin size along the X axis (see subsequent Feature Request).

Here is a data set in which this problem appears for var6, var7, and var8. It WOULD have appeared for var2, had I not changed a value of 9.0 to 9.1.

var1,var2,var3,var4,var5,var6,var7,var8
4.0,9.1,10.0,8.0,7.0,1.0,4.0,7.0
5.0,8.0,10.0,10.0,7.0,1.0,10.0,6.0
9.0,5.0,8.0,8.0,8.0,9.0,9.0,5.0
4.0,4.0,9.0,8.0,5.0,1.0,8.0,4.0
5.0,7.0,10.0,10.0,8.0,10.0,7.0,5.0
3.0,3.0,10.0,8.0,7.0,3.0,8.0,8.0
10.0,10.0,10.0,10.0,10.0,7.0,10.0,9.0
10.0,7.0,9.0,9.0,6.0,6.0,8.0,5.0
6.0,6.0,8.0,7.0,7.0,7.0,7.0,5.0
1.0,4.0,7.0,6.0,7.0,2.0,3.0,7.0
3.0,4.0,8.0,6.0,4.0,2.0,9.0,4.0
8.0,8.0,9.0,8.0,6.0,9.0,10.0,5.0
8.0,9.0,9.0,7.0,5.0,8.0,8.0,5.0
2.0,1.0,10.0,8.0,9.0,2.0,10.0,10.0
6.0,7.0,9.0,7.0,7.0,8.0,7.0,7.0
4.0,3.0,9.0,8.0,6.0,6.0,9.0,3.0
8.0,7.0,9.0,5.0,7.0,9.0,9.0,5.0
4.0,6.0,10.0,9.0,8.0,2.0,9.0,9.0
7.0,10.0,10.0,10.0,8.0,9.0,8.0,1.0
7.0,9.0,10.0,9.0,6.0,6.0,7.0,7.0

**Comment by EJWagenmakers** [comment]
Thanks. We were aware of the "gap" issue. @TimKDJ @FransMeerhoff: did we agree on a solution?
E.J.

**Comment by AlexanderLyNL** [comment]
Fixed in 0.9.1

http://jasp-stats.org/download/
