### ISSUE TITLE
SumStats Prior confusion

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-desktop#1984]
## Template for bug reports

* JASP version: 0.8.2
* OS name and version: Ubuntu 16.04
* Analysis: SumStats T-Test
* Steps to reproduce: 

See attached screenshot. When I load a JASP file that has some SumStats plots, and I look at the prior options used to produce that plot, it looks a little confusing. Even though an informed normal prior is used, the informed prior options are greyed out and the non-informed ones are not. Also, the fields for the informed T-prior are visible, even though the fields for the informed normal prior should be visible (since that is one used). 
Thanks!
![sumstatspriorbug](https://user-images.githubusercontent.com/15704203/30688893-a872c532-9ebf-11e7-8452-8df4ec87a424.png)

**Comment by lindeloev** [comment]
Cannot reproduce on JASP 8.2, Ubuntu 16.04

![image](https://user-images.githubusercontent.com/1439417/30689861-9b6a6e32-9ec2-11e7-9c3f-3371efbc095a.png)

**Comment by JohnnyDoorn** [comment]
Hi Jonas, 
What did you try to reproduce it? For instance, can you try opening the attached jasp file (in the zip file), and looking at the prior options? 
Kind regards,
Johnny

[sumstatsTtest.zip](https://github.com/jasp-stats/jasp-desktop/files/1320713/sumstatsTtest.zip)

**Comment by vandenman** [comment]
Replicated on windows 10 by opening Johnny's .zip
![image](https://user-images.githubusercontent.com/21319932/30691862-8417aeb4-9ec9-11e7-96a0-ad9c3f3463da.png)

**Comment by lindeloev** [comment]
@JohnnyDoorn, Still no UI error here when opening the file you sent and changing prior options.

**Comment by JohnnyDoorn** [comment]
Hi Jonas,
Sorry for the confusion - what I meant was that the way the settings look is a little confusing for people opening a jasp file that contains plots from the sumstats module. It's no explicit error message or crash, but more of a little gui thing.

**Comment by lindeloev** [comment]
Oh, I did not notice that it initially displays wrong (so replicated here too, screenshot below). That's subtle. But when interacting with it (e.g. just pressing "informed"), the UI looks right.

Without having touched any settings:
![image](https://user-images.githubusercontent.com/1439417/30771643-d978c0a8-a04c-11e7-8dcf-17c3607a23ba.png)

**Comment by akashrajkn** [comment]
PR #2132 Fixes this
