### ISSUE TITLE
Analysis does not appear

### ISSUE THREAD

**Issue by ttaattyy** [jasp-stats/jasp-desktop#1990]
Hi there,
It seems like I am struggling with JASP. I work on Windows 7, JASP version 0.8.1.2. When I input the data for the analysis, nothing happen, and I cannot see any analysis. I had a new version previously 0.8.2, but this send me an error message of run time termination. 
It is the same for all type of analysis. However, I have successfully uploaded a file from .csv
Could you please help me with this

ttaattyy

**Comment by FransMeerhoff** [comment]
Hi @ttaattyy 

I'm afraid I do not understand you quit well about your quote  'I had a new version previously 0.8.2, but this send me an error message of run time termination'. I Assume that you first installed the previous version 0.8.1.2 and afterwards the later version 0.8.2 that gave the run time error.
In those unclear cases we advise to try the following. We deliver this JASP for windows platforms in a zipped file. You only have to download that file, unzip it, and start JASP.exe from the unzipped folder. You can find this file at https://static.jasp-stats.org/JASP-0.8.2.0-64-bit.zip
(And https://static.jasp-stats.org/JASP-0.8.2.0-32-bit.zip for a 32 bits version)

I hope that this workaround will solve your problem.
If not, could you please uninstall all the JASP versions, reinstall 0.8.2 and send me as much details about the error and  reproduction path.

Kind regards 
Frans Meerhoff

**Comment by ttaattyy** [comment]
Hi Frans,
Thank you for the reply. The problem is sorted now. Just if anyone has a similar problem I would explain what happened. There was a conflict between versions of visual c++. So I uninstalled old versions. This solved the problem.
Kind regards,
Tatjana

**Comment by boutinb** [comment]
@ttaattyy Happy to hear that it is solved. But if you can give us more details about the problem and its solution, that could help us to help other users.
