### ISSUE TITLE
Bug - This analysis terminated unexpectedly.

### ISSUE THREAD

**Issue by Maelle234** [jasp-stats/jasp-desktop#2013]
Hi, 

Sorry but I have an issue with my 8.2 JASP software.
When I try to get any analysis, the message "This analysis terminated unexpectedly" appear

![capture d ecran 2017-09-29 a 12 29 07](https://user-images.githubusercontent.com/32388507/31012730-2b0b58d4-a513-11e7-917c-9e2f7c648e9e.png)

Can I have some help for that.
Thank in anticipation, 

Regards
Maelle

**Comment by akashrajkn** [comment]
@Maelle234 can you please give more details - which OS are you using and which analysis gives you this error?

**Comment by Maelle234** [comment]
*Hi, *

*Here my OS, and I have this message for all analysis (descriptives,
t-test, ANOVA,…)*
*(et en dessous tu colles l’image que tu m’as envoyé).*

*Regards, *
*Maelle*


Le vendredi 29 septembre 2017, akash raj <notifications@github.com> a
écrit :

**Comment by boutinb** [comment]
Hallo Maelle,
Do you still have this problem? We could not read your previous answer.

**Comment by AlexanderLyNL** [comment]
This should have been fixed by now. Please open a new issue if the problem occurs.
