### ISSUE TITLE
Rcpp issue on 14.04

### ISSUE THREAD

**Issue by williamstome** [jasp-stats/jasp-desktop#2016]
* JASP version:
Most recent commit: 5eb99e95d95653cd9de0de21c67e9748a98dc77c
* OS name and version:
Ubuntu 14.04 (Trusty Tahr)
* Analysis:
Compilation fails on Ubuntu 14.04, with the following error re: Rcpp: 

/usr/lib/R/site-library/Rcpp/include/Rcpp/storage/PreserveStorage.h: In instantiation of ‘void Rcpp::PreserveStorage<CLASS>::set__(SEXP) [with CLASS = Rcpp::InternalFunction_Impl<Rcpp::PreserveStorage>; SEXP = SEXPREC*]’:
/usr/lib/R/site-library/Rcpp/include/Rcpp/InternalFunction.h:43:40:   required from ‘void Rcpp::InternalFunction_Impl<StoragePolicy>::set(SEXP) [with StoragePolicy = Rcpp::PreserveStorage; SEXP = SEXPREC*]’
/usr/lib/R/site-library/Rcpp/include/Rcpp/generated/InternalFunction__ctors.h:69:111:   required from ‘Rcpp::InternalFunction_Impl<StoragePolicy>::InternalFunction_Impl(OUT (*)(U0, U1, U2, U3, U4)) [with OUT = Rcpp::DataFrame_Impl<Rcpp::PreserveStorage>; U0 = SEXPREC*; U1 = SEXPREC*; U2 = SEXPREC*; U3 = SEXPREC*; U4 = SEXPREC*; StoragePolicy = Rcpp::PreserveStorage]’
/home/tom/code/jasp-try2/jasp-desktop/JASP-Engine/rbridge.cpp:63:86:   required from here
/usr/lib/R/site-library/Rcpp/include/Rcpp/storage/PreserveStorage.h:22:13: error: ‘class Rcpp::InternalFunction_Impl<Rcpp::PreserveStorage>’ has no member named ‘update’
             static_cast<CLASS&>(*this).update(data) ;

**Comment by akashrajkn** [comment]
@williamstome can you please tell me which version of Rcpp you are using? (Because, I'm able to build it successfully on my linux machine)

**Comment by williamstome** [comment]
Certainly, @akashrajkn 

r-cran-rcpp:
  Installed: 0.11.0-1
  Candidate: 0.11.0-1
  Version table:
 *** 0.11.0-1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
        100 /var/lib/dpkg/status

**Comment by AlexanderLyNL** [comment]
This should be fixed by now with flatpak

https://jasp-stats.org/linux-installation-guide/
