### ISSUE TITLE
Failure to discriminate different JASP versions

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2021]
See screenshot
![differentversion](https://user-images.githubusercontent.com/8603015/31124303-31fb3004-a844-11e7-9d51-1bc59cc1f2ed.png)

**Comment by TimKDJ** [comment]
I don't really see what's incorrect in the screenshot. Can you explain why this behavior is wrong?

**Comment by EJWagenmakers** [comment]
You are right. I just read it way too quickly.
