### ISSUE TITLE
New "About" window does not resize nicely

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2027]
See the green area in attached screenshot
![aboutbox](https://user-images.githubusercontent.com/8603015/31171703-f660fd18-a900-11e7-9101-ca124a9c4b3a.png)

**Comment by FransMeerhoff** [comment]
@EJWagenmakers 

We've noticed these issue(s) on  other high def screens too ( Erik-Jan's). 
I'm working on it. (You will probably have a similar issue on the preference window too.)

Cheers Frans

**Comment by boutinb** [comment]
Fixed in version 0.8.5
