### ISSUE TITLE
Planned contrasts - ANOVA

### ISSUE THREAD

**Issue by TomasAPalma** [jasp-stats/jasp-desktop#2035]
I would like to see in JASP a more complete package of planned contrasts for ANOVAS. For example, something similar to what we can find in STATISTICA, namely, to have the option to run all sorts of comparisons between all cells in any design (between, within, and mixed). If you had this option, I would probably use JASP for all my analyses.

**Comment by EJWagenmakers** [comment]
Yes we should do this, very important.
E.J.

**Comment by TomasAPalma** [comment]
Thanks for the reply E.J. Looking forward to that.
Keep up with the excellent work!

**Comment by AlexanderLyNL** [comment]
Planned contrasts implemented.

**Comment by TomasAPalma** [comment]
Yes, just saw it. Great news!
Keep going with the fantastic work!

AlexanderLyNL <notifications@github.com> escreveu no dia quinta, 11/10/2018
à(s) 20:12:

**Comment by TomasAPalma** [comment]
Did you implement planned contrasts in this last update? Maybe I'm missing
something, but I can't find it.

Thanks!

Tomás Palma <t.a.palma@gmail.com> escreveu no dia quinta, 11/10/2018 à(s)
20:51:

**Comment by AlexanderLyNL** [comment]
Hi Tomas,

You can find it under the contrast tab. Here's an example from our Data Library  - ANOVA - Facebook Friends

<img width="1312" alt="screen shot 2018-10-11 at 23 31 18" src="https://user-images.githubusercontent.com/10271675/46835232-d61c1100-cdad-11e8-88e0-a7f7854e8828.png">

**Comment by AlexanderLyNL** [comment]
Hi Hello44,

Specifying custom contrasts is not yet possible. We'll implement that later. 

Cheers,
Alexander

**Comment by TomasAPalma** [comment]
Okay, I see. However, I was also looking for custom contrasts. Hope it will be implemented soon. 

Best,
Tomás


Enviado do meu iPhone

No dia 12/10/2018, às 08:39, AlexanderLyNL <notifications@github.com> escreveu:

**Comment by mpeters2** [comment]
Another vote for custom contrasts!
