### ISSUE TITLE
Is the null hypothesis for correlations a point hypothesis or a very narrow prior spiked over zero? 

### ISSUE THREAD

**Issue by robustbayesian** [jasp-stats/jasp-desktop#2038]
If the null hypothesis used in bayes factor calculation is a distribution, which is it? 

Thanks

**Comment by AlexanderLyNL** [comment]
For (Pearson's) correlation we fix \rho to zero and let the means \mu_{1}, \mu_{2} and standard deviations \sigma_{1} and \sigma_{2} vary freely. The set-up is given in the paper

Ly, A., Verhagen, A. J., & Wagenmakers, E.-J. (2016). Harold Jeffreys’s default Bayes factor hypothesis tests: Explanation, extension, and application in psychology. Journal of Mathematical Psychology, 72, 19-32.

More detailed calculations can be found in the paper

Ly, A., Marsman, M., Wagenmakers, E.-J. (2017). Analytic Posteriors for Pearson’s Correlation Coefficient. Statistica Neerlandica

Preprints might be available on my website. I hope that this answers your questions. 

Cheers,
Alexander
