### ISSUE TITLE
Enhancement requests: Export tables to LaTeX, or image

### ISSUE THREAD

**Issue by YamilVidal** [jasp-stats/jasp-desktop#2040]
* Enhancement: Export tables to LaTeX, or image

* Purpose: Currently JASP exports tables only to HTML. Being able to export tables to LaTeX or images (e.g. .png) would facilitate to insert the output of JASP into publications.

**Comment by EJWagenmakers** [comment]
I agree! We've often talked about this, but maybe we should proceed.
