### ISSUE TITLE
repeated measures anova, looking for the intercept

### ISSUE THREAD

**Issue by metamorphose42** [jasp-stats/jasp-desktop#2042]
Hi,

I was wondering why in JASP the intercept is not provided for a one-way repeated measures? I'm looking for the main effect of each of my comparisons across a between subject factor = intercept in SPSS... and was also hoping to get the BF for this.

Thanks!

Best,
Clarisse

**Comment by metamorphose42** [comment]
Any update on this?

Many thanks!

**Comment by EJWagenmakers** [comment]
Ah, sorry, I have been looking for your mail, but in the wrong place (the JASP Forum). So about your question. I am not 100% sure that I understand your question -- a concrete data set or example would help. My first response was "oh you are asking about the grand mean, but this gets an uninformative prior and so it is not something we test" but now I'm not so sure. So we have a between-subjects factor (gender, say) and we have a one-way factor in a RM design (two levels, say, weight on Mondays and weight on Fridays).  So now you want to assess the effect of day separately for men and for women, is that it?

**Comment by metamorphose42** [comment]
Hi!

No problem, I’m sure you are very busy and appreciate you taking the time.

I only have SPSS files, attached. 

To be honest I’m asking you because I don’t know whether my supervisor makes much sense. In my neuroimaging data, I have two within subject conditions, namely posture (sitting versus laying down) and we used fNIRS and ran six contrasts on the 16channels (for each we have a measure of HBO and HBR). He wanted me to run repeated measures analyses separately for each of the 16 channels and each of our contrasts for HBO and HBR.

So for example in the SPSS file, the data is from contrast 1, and compares channel 1 for sitting versus laying in a repeated measures. And what he wants me to report is the last output box named between subject effects which gives us the intercept:


In theory, that is supposed to be the main effect across postures for that contrast.

Does this make sense to you? And if so, what is the BF equivalent?

Thank you so much for taking the time to look at this. I have been trying to find more information in stats books, but am blindly trusting my supervisor. I am reporting BF for all my other analyses though, so I already dislike having to run this in SPSS and not having BFs.

Best,
Clarisse

**Comment by boutinb** [comment]
@EJWagenmakers Does it make sense? Should we do an enhancement request?

**Comment by EJWagenmakers** [comment]
I am still not 100% sure what is desired. @metamorphose42, can you perhaps send a screenshot of the relevant SPSS output?

**Comment by metamorphose42** [comment]
Hi,

Thanks for still looking into this. My supervisor now explained that the reason I should just report intercepts is because its equivalent to performing one sample t tests on my data against zero, but because it is easier to just run this in SPSS than to rearrange my data, he suggested intercepts as its the same thing minus the extra work of data sorting. When I have more time, I will run this on the means in JASP, just to see whether this adds up.

I don’t think anyone uses intercepts ever, so maybe its good that JASP doesn’t bother with it, it doesn’t seem that useful.

Best,
Clarisse

**Comment by boutinb** [comment]
This issue can be closed apparently. If not re-open it.
