### ISSUE TITLE
Preference Box on High Res Screen

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2045]
On my infamous laptop screen, the preference box looks suboptimal (see screenshot). However, I can fix that by simply resizing the box. 
1. It would be nice if it looked good without having to resize;
2. The boxes for "OK" and "Cancel" are slightly too small, and I can't resize those.
E.J.
![prefboxonhighresscreen](https://user-images.githubusercontent.com/8603015/31413883-6e254952-ade9-11e7-8608-c870e577ba3c.png)

**Comment by boutinb** [comment]
Duplicate can be closed
