### ISSUE TITLE
About Box on High Res Screen

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2046]
See attach. On my infamous laptop, the About box is a bit small, and I cannot resize to make the text more readable.
E.J.
![aboutboxabitsmallonhighresscreen](https://user-images.githubusercontent.com/8603015/31413937-9e045820-ade9-11e7-8da0-f1e72decd57f.png)

**Comment by boutinb** [comment]
Duplicate can be closed
