### ISSUE TITLE
JASP Version 0.8.1.2 on Mac OSX 10.8.5

### ISSUE THREAD

**Issue by Milan3462** [jasp-stats/jasp-desktop#2052]
Hi there, just downloaded the 8.3 version and have this message:
Error: package or namespace load failed for 'stats' 

I saw the previous thread about this problem, but didn't understand what you meant by 

"Let's first check if the stats package is available after out installation.
Out R installed packages reside in
/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.3/Resources/library
Could you check if the 'stats' package is available there?"

I wasn't able to verify this because I didn't understand what it meant. In my applications folder, there is the JASP app, but opening it opens the app, instead of leading to the "Contents" folder, as I assume that's what you meant.

Thanks for the help

**Comment by FransMeerhoff** [comment]
Hi @Milan3462 

Sorry for the misunderstanding.
But I'm a bit confused too about this error.

Could you first describe when exactly this message occurs. 
- Does JASP doesn't start at all and give this error?
- Does this error occur running some analysis?
Could you describe as specific possible the reproduction path?

What I meant was that on the Mac JASP.app is an application folder where all our installed software resides. You could reach this folder from a terminal
(If you do not know how to  open a terminal: type 'terminal' in the Mac search icon)
In this terminal type
>cd /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.3/Resources/library
>ls -al 
The last command shows all the R packages installed by JASP
>ls -al stats
The last command checks for the existence of the stats package 

I hope you could help us further to solve this issue

Kind regards
Frans Meerhoff

**Comment by Milan3462** [comment]
Hi Frans, thank you for answering quickly.

Jasp opens up perfectly, loading up a data set (.csv format) works fine too. I am able to click the "descriptive analysis" button in "descriptives" too. However, when I choose data, put it in the "variables" rectangle and click "ok", I get this message:

Error: package or namespace load failed for 'stats'

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)

.descriptivesDescriptivesTable(dataset, options, run, last.stats.table)

(function (name, package, ...) 
{
    name <- paste0(name, '')
    rm(list = name, envir = .AutoloadEnv, inherits = FALSE)
    m <- match.call()
    m$name <- NULL
    m[[1]] <- as.name('library')
    eval(m, .GlobalEnv)
    autoload(name, package, reset = TRUE, ...)
    where <- match(paste('package', package, sep = ':'), search())
    if (exists(name, where = where, inherits = FALSE)) 
        eval(as.name(name), as.environment(where))
    else stop(gettextf('autoloader did not find '%s' in '%s'', name, package), domain = NA)
})(name = 'xtabs', package = 'stats')

eval(m, .GlobalEnv)

eval(expr, envir, enclos)

library(package = 'stats')

stop(gettextf('package or namespace load failed for %s', sQuote(package)), call. = FALSE, domain = NA)


I get problems when running any other stats like ANOVA and T-tests. I get this:

Error in dyn.load(file, DLLpath = DLLpath, ...): impossible de charger l'objet partag'e '/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.3/Resources/library/grDevices/libs/grDevices.so':
  dlopen(/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.3/Resources/library/grDevices/libs/grDevices.so, 6): Symbol not found: ___sincos_stret
  Referenced from: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.3/Resources/library/grDevices/libs/grDevices.so
  Expected in: /usr/lib/libSystem.B.dylib
in /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.3/Resources/library/grDevices/libs/grDevices.so

Stack trace
(function (dataset, target, equalTo = 0, grouping = NULL, groupingLevel = NULL) 
{
    result <- list(error = FALSE, errorVars = NULL)
    getVariance <- function(x) {
        validValues <- x[is.finite(x)]
        variance <- -1
        if (length(validValues) > 1) {
            variance <- stats::var(validValues)
        }
        return(variance)
    }
    for (v in target) {
        if (length(grouping) > 0) {
            variance <- .applyOnGroups(getVariance, dataset, v, grouping, groupingLevel)
        }
        else {
            variance <- getVariance(dataset[[.v(v)]])
        }
        if (any(variance = equalTo)) {
            result$error <- TRUE
            result$errorVars <- c(result$errorVars, v)
        }
    }
    return(result)
})(dataset = list(XTUVUUmh5dGht = c(28, 40, 26, 41, 39, 47, 47, 49, 41, 46, 40, 36, 44, 36, 40, 40), XTm9MYW5ndWFnZXM = c(2, 5, 5, 2, 4, 3, 3, 4, 1, 4, 4, 3, 2, 4, 6, 3)), target = c('METRhythm', 'NoLanguages'), equalTo = 0, grouping = NULL, groupingLevel = NULL)

getVariance(dataset[[.v(v)]])

stats::var

getExportedValue(pkg, name)

asNamespace(ns)

getNamespace(ns)

tryCatch(loadNamespace(name), error = function(e) stop(e))

tryCatchList(expr, classes, parentenv, handlers)

tryCatchOne(expr, names, parentenv, handlers[[1]])

value[[3]](cond)


I opened the terminal, typed in what you asked, and saw many words like "stats", "stats4", "tibble", etc. Hopefully this is is informative. "stats" was written in this context:

"drwxr-xr-x@  10 macbookpro  admin   340 10 oct 12:47 stats".

Thanks for your help!

**Comment by FransMeerhoff** [comment]
HI @Milan3462 

Because we cannot reproduce your problem could you answer some more questions 
But it seems that this is caused by some installation failure.

- Could you download the latest version 0.8.3.1 reinstall JASP. The safest way is to remove the previous version first by opening a Finder go to Applications an drag and drop JASP.app to the Trash  
- We deliver some sample data files. Could you load the 'Big 5' example got to Descriptives, choose Neuroticism as variable and see what happens?
- Could you click on the preference icon on JASP (i.e. the most right upper button 'the Hamburger menu') and choose the About. Could you send us a screenshot of the about window. (If you place it in a zip file you can drag it to this issue)
- I assume you start JASP from Go->Applications->JASP.app?

I hope we can help you solving this issue.

Kind regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
@Milan3462 

If you still have this problem reopen issue.
