### ISSUE TITLE
Admin rights needed to install on Windows - it is useless for this kind of software

### ISSUE THREAD

**Issue by mozny** [jasp-stats/jasp-desktop#2053]
## Template for bug reports

* JASP version: 0.8.3.0
* OS name and version: WIndows 7
* Analysis: It is not possible to install JASP without administrative rights. It is probably due to attempt to install it for all users. It would be great to install it wherever possible
* Steps to reproduce: Install as a user without admin rights

**Comment by FransMeerhoff** [comment]
Dear @mozny 

We made a special advanced download for this issue.
If you go to the download page of JASP and you scroll down to 'ADVANCED DOWNLOADS'
you will find a zipped version of JASP that is made of an already installed version.This means that if you download file from https://static.jasp-stats.org/JASP-0.8.3-64-bit.zip
( or https://static.jasp-stats.org/JASP-0.8.3-32-bit.zip for the 32 bit version) and unzip the file
you can run JASP by double clicking JASP.exe from the unzipped folder. You do not need administrative rights in this way.

I hope this will solve your problem.

Kind regards 
Frans Meerhoff

**Comment by mozny** [comment]
Great!

Thank you for immediate help!
Jasp is very good.

Regards

Ladislac

čt 12. 10. 2017 v 10:43 odesílatel FransMeerhoff <notifications@github.com>
napsal:
