### ISSUE TITLE
What are the ANOVA post-hoc mean differences?!? 

### ISSUE THREAD

**Issue by parnystrom** [jasp-stats/jasp-desktop#2061]
* JASP version:  JASP(Version 0.8.3.1)
* OS name and version: Windows 10
* Analysis: ANOVA
* Steps to reproduce: Any ANOVA with two factors

I've asked knowledgeable people at my department about how to interpret the post-hoc tests of main effects in the ANOVA function, and they thought this looked like a bug in JASP. As seen in the screenshot below the post-hoc mean difference between HR-ASD and HR-no-ASD is  0.079, but the descriptive figure below suggest a much larger mean difference. 

![jasp_problem](https://user-images.githubusercontent.com/32871582/31665016-d65063b4-b347-11e7-9fc5-e96c9371371f.gif)

The problem seems to arise when there are two or more factors in the analysis. I.e. if I remove site as a factor I can get the same results in JASP and SPSS. However, when I add site as another factor only JASP will change the mean differences and other stats. Is it a bug in JASP, or do you know why JASP and SPSS behave differently?

**Comment by JohnnyDoorn** [comment]
Hi, 
Thanks for letting us know! Would you mind sharing your JASP-file, or datafile? This way I can try to replicate the issue and fix the potential bug. You can share it here, or send it by email to j.b.vandoorn ( at ) uva.nl
Kind regards
Johnny

**Comment by JohnnyDoorn** [comment]
After some investigating I found the culprit: we use the R-package multcomp. This package conducts post-hoc tests for linear models and contains a lot of neat features. When dealing with more than 1 factor in the ANOVA model, the interaction between the factors gets incorporated in the post-hoc statistics. This means that one factor influences another factor's post-hoc test. 
As it is now, this is rather unclear in the tables itself and can be misleading. I will discuss with the team about how we can deal with this issue, as something needs to be changed - either don't have behind the scenes correction for multiple factors/interactions in the post-hoc tests, or include a note in the table that clarifies the correction.
Again, thanks for your help!
Kind regards
Johnny

**Comment by parnystrom** [comment]
Great! Thank you for your clarification and for your super-fast response!!! Knowing that JASP uses multcomp also gives us possibilites to dig further :)

**Comment by boutinb** [comment]
I think this issue can be closed. If not re-open it.

**Comment by kairikeymaster** [comment]
I'm having this same problem, but I only have one factor. 

![image](https://user-images.githubusercontent.com/43684867/46229217-77c14e00-c32a-11e8-8fe1-31937f1ca7d8.png)

The factor has three levels and the post hoc table doesn't seem to be showing the comparison between levels 1 and 3.

Data:

[Levels of Processing Scores - Dummy Coded.xlsx](https://github.com/jasp-stats/jasp-desktop/files/2429466/Levels.of.Processing.Scores.-.Dummy.Coded.xlsx)

**Comment by AlexanderLyNL** [comment]
Hi kairikeymaster,

You can find the comparison between levels 1 and 3 on the second line. 

Cheers,
Alexander
