### ISSUE TITLE
Logistig Regression in Ubuntu

### ISSUE THREAD

**Issue by WillemVlakveld** [jasp-stats/jasp-desktop#2065]
When conducting a Logistic Regression applying JASP Version 0.8.3.1 running in the Linux operating system Ubuntu version 16.04 LTS, I get an error messages as soon as I select a dependent variable (with the values 0 and 1). This error does not occur when I do the same analysis with JASP running in Windows. The Error message is:

This analysis terminated unexpectedly.

Error: could not find ‘startsWith’

Stack trace
analysis(dataset = NULL, options = options, perform, callback = the.callback, state = state)
.hasErrors(dataset, perform, type = ‘factorLevels’, factorLevels.target = options[[‘dependent’]], factorLevels.amount = ‘≠ 2’, exitAnalysisifErrors = TRUE)

**Comment by vandenman** [comment]
Hi,

This is a known issue with the R version in Ubuntu repositories being a outdated (as was similarly observed  in #2063 ). A workaround for updating R is also given in #2063 .
