### ISSUE TITLE
Mysterious BF10, U in post hoc comparison 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2069]
@TimKDJ 
See http://forum.cogsci.nl/index.php?p=/discussion/comment/11956#Comment_11956
Issue: BF10, U is not explained anywhere. Maybe we ought to add this in the table header. Can you send me a proposal?
E.J.

**Comment by TimKDJ** [comment]
Ah yes. This slipped my mind.

I think the best place to clarify this is in the footnote.
The text currently states:
> The posterior odds have been corrected for multiple testing by
> fixing to 0.5 the prior probability that the null hypothesis holds
> across all comparisons (Westfall, Johnson, & Utts, 1997). Individual
> comparisons are based on the default t-test with a Cauchy (0, r =
> 1/sqrt(2)) prior.

We could make it something like:
> The posterior odds have been corrected for multiple testing by
> fixing to 0.5 the prior probability that the null hypothesis holds
> across all comparisons (Westfall, Johnson, & Utts, 1997). Individual
> comparisons are based on the default t-test with a Cauchy (0, r =
> 1/sqrt(2)) prior. The "U" in the Bayes factor denotes that this statistic is uncorrected.

Thoughts?

**Comment by EJWagenmakers** [comment]
Yes. Perhaps replace "this statistic" with "it" (some people would argue
that the Bayes factor is not a statistic, depending on how it is defined).
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam, Nieuwe Achtergracht 129B
Letter: PO Box 15906, 1001 NK Amsterdam
Parcel: Valckenierstraat 59,  1018 XE Amsterdam

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Blog: bayesianspectacles.org
Email: EJ.Wagenmakers@gmail.com
Cell: (+31) 6 45626624

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
