### ISSUE TITLE
Non-Parametric tests for related and unrelated samples

### ISSUE THREAD

**Issue by LNickels** [jasp-stats/jasp-desktop#2071]
Would it be possible to include non-parametric tests (equivalent of related and unrelated t), such as McNemar's test, Cochrane's Q, Wilcoxon Matched Pairs, Mann-Whitney U test.
This would be invaluable, and the major limitation for our research group for using JASP currently.
I note another request for Fisher Exact which is also invaluable to us.
Thank you!

**Comment by JohnnyDoorn** [comment]
Hi,
I am currently working on implementing the Bayesian nonparametric t-tests in JASP (the Wilcoxon signed rank test and Mann Whitney U test), which should be in the next release or the one after that. 
As for the frequentist versions of these tests, they are already present in JASP and you can find these under their respective t-test menu's. 
We are also looking into implementing the other tests you mentioned, but this might take a little bit longer.
Kind regards
Johnny

**Comment by LNickels** [comment]
Thank you so much Johnny, that’s really good to know. I apologise for missing the frequentist Wilcoxon/Mann whitney, but its good to know that the Bayesian versions are coming soon, and that McNemar etc are being thought of.
Regards,
Lyndsey
