### ISSUE TITLE
Linear regression bugs

### ISSUE THREAD

**Issue by TimKDJ** [jasp-stats/jasp-desktop#2074]
[bugslinreg.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/1411367/bugslinreg.jasp.zip)
* JASP version: 0.8.3
* OS name and version: macOS Sierra
* Analysis: Linear Regression
* Steps to reproduce (issue 1): 
1. Add a dependent variable and a covariate
2. Set method to "Forward" or "Stepwise"
3. Tick "Collinearity diagnostics"
The analysis will crash.
* Steps to reproduce (issue 2): 
1. Add a dependent variable and a covariate
2. Tick "Residuals vs. dependent" and "Residuals vs. covariates"
One of two things will happen, (1) the covariate plot is shown twice or (2) one covariate plot is shown and the other is set to waiting. Neither should happen.

Edit: I attached the .jasp file.

**Comment by TimKDJ** [comment]
@JohnnyDoorn you've recently gone through the code.
Any chance you could have a look at these issues?

**Comment by TimKDJ** [comment]
[bugs-linear-regression-0.8.4.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/1441610/bugs-linear-regression-0.8.4.jasp.zip)
And these...

**Comment by Janto91** [comment]
For better clarity, all unresolved issues from the post from Nov 3 are moved to new issues.
