### ISSUE TITLE
Can't add contrast to RM factor

### ISSUE THREAD

**Issue by TimKDJ** [jasp-stats/jasp-desktop#2082]
* JASP version: 0.8.3
* OS name and version: macOS Sierra
* Analysis: RM ANOVA
* Steps to reproduce: 
1) Fill the repeated measures cells with any two variables
2) Click on the "Contrasts" tab
The box will be empty. However, if you now add a between subjects factor, both that factor and the RM factor will appear.

**Comment by AlexanderLyNL** [comment]
Fixed
