### ISSUE TITLE
Additional info for prior-posterior plot and robustness check on by default

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-desktop#2083]
## Template for enhancement requests
 
* Enhancement: Have the additional on by default
* Purpose: Change default behaviour

Easy to get started

**Comment by akashrajkn** [comment]
![screensht](https://user-images.githubusercontent.com/6959308/32067874-e652d302-ba84-11e7-9b38-c8d9ffa7cab8.jpg)

The selection of option `prior and posterior plots` should select `Additional info` by default.

Details - The default state of options are mentioned in the Resources (json) file of each analysis.
