### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by SabineHollmann** [jasp-stats/jasp-desktop#2088]
I have a problem installing JASP on my computer. It's a windows 10 computer (ACER swift), with RAM 8 gb and IntelCore i5. Attachted is the error I get. 

<img width="960" alt="jasp_error" src="https://user-images.githubusercontent.com/33151043/32099377-5a326c84-bb10-11e7-9b50-6c2aa6b40976.png">

Sabine

**Comment by FransMeerhoff** [comment]
Hello @SabineHollmann 

You could try the following to solve this annoying problem:

1. A work around is:
Download a the zip file from http://static.jasp-stats.org/JASP-0.8.3.1-64-bit.zip which contains an installed version of JASP 0.8.3.1. Unzip this file and start JASP.exe from the unzipped folder
2. Be sure that your Windows system is updated. This message was generated by Microsoft Visual Studio. So updating your windows system and/or Visual Studio might solve your problem.
3. Uninstall all previous installed version of JASP and reinstall 0.8.8.1. Check the in your "program files" folder JASP does not exist anymore.

Hope that one of these actions might solves your problem.

Kind Regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Hi @SabineHollmann 

Sorry for the typo in the last option, I meant of course 0.8.3.1 to reinstall latest download from the JASP site.

Cheers Frans

**Comment by ftv88** [comment]
Hi @FransMeerhoff , I have the same issue and none of your steps 1-3 above works. 
Any other suggestions?

**Comment by fedoracoreuser** [comment]
I have the same issue. I tried launching the JASPEngine.exe file and it complains that it can't find R.dll. Maybe it could be related?

**Comment by FransMeerhoff** [comment]
Hi @SabineHollmann, @ftv88 , @fedoracoreuser 

We've waited on the latest release JASP 0.8.4 (released last monday 13-11-2017) to test this issue more thoroughly. Unfortunately we are still not able to reproduce this problem.
We have installed a Windows 10 machine with Visual Studio 2017 and Microsoft Open R but this also not led to a reproduction path. 

The only thing we can offer now is:

- Would you be so kind to install the latest 0.8.4 version and check if the problem still occurs?
- Is so we are we can make a special debug version of 0.8.4 with extra logging that might help us to find this problem.

Kind regards 
Frans Meerhoff

**Comment by fedoracoreuser** [comment]
I had previously downloaded and installed it, the issue still occurs. Since the uninstaller started to crash, I am unable to uninstall and reinstall. What file/registry key does it check for?

If you want, I can download the source and try building it, maybe we see what it chokes on.

**Comment by FransMeerhoff** [comment]
Hi @fedoracoreuser 

It's very weird that the uninstaller crashes too, because that has nothing do do with JASP.

But if you want the JASP setup to continue you can rename (or remove) the following key in the registry
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\JASP 
and rerun the setup.

When this works could you try the following?
- Unzip the file I've attached in the "C:\Program Files\JASP 0.8.4.0" folder.
- Check that in "C:\Program Files\JASP 0.8.4.0" folder now a new 'platforms' folder is created.
- Start JASP again

Thanks a lot so far.

Kind regards
Frans Meerhoff

[platforms.zip](https://github.com/jasp-stats/jasp-desktop/files/1482231/platforms.zip)

**Comment by fedoracoreuser** [comment]
Unbelievable. I don't know what happened or changed, but this morning it works with no changes on my behalf.
- Machine 1: JASP was crashing, unistaller not working. Registry key removed, reinstalled, now just works.
- Machine 2: JASP was crashing. No apparent changes, now just works.

I suspect some background issue like Windows Update. Surprising, anyway.
If there is anything else I can help with, please let me know.

**Comment by caofei0806** [comment]
Try  updating Microsoft Visual Studio and be sure components that run C++ are installed. I have solved the issue and all JASP versions run well.

**Comment by FransMeerhoff** [comment]
If this problem still occurs please noisy this on Issue 

https://github.com/jasp-stats/jasp-desktop/issues/1431
