### ISSUE TITLE
Error in complete.cases(x, y): not all arguments have the same length

### ISSUE THREAD

**Issue by steph2708** [jasp-stats/jasp-desktop#2089]
* JASP version: 0.8.3.1
* OS name and version:
* Analysis: Repeated measures ANOVA
* Steps to reproduce: 

I am trying to run a repeated measures ANOVA on my data, where all variables have the same amount of cases (see attached), yet I receive the following error message: Error in complete.cases(x, y): not all arguments have the same length
Is it because the number of decimals is different?
[Data_full.xlsx](https://github.com/jasp-stats/jasp-desktop/files/1422090/Data_full.xlsx)

**Comment by JohnnyDoorn** [comment]
Hi Steph,
Thanks for filing this bug report. Could you please tell me how you specified your RM ANOVA? I tried to replicate your issue but was unsuccesful - I tried specifying a model with 1 factor and 9 levels ( = number of columns in your datafile) and a model with 3 factors with 2 levels each, but both run fine. 
How are you reading in your data file? Does your csv file have column names? If not, JASP will take the first observation in each column and use that as the column name, which might cause the issue. 
Kind regards
Johnny

**Comment by steph2708** [comment]
Hi Johnny,


Thanks for your email. It's a 3 x 3 ANOVA, so 3 factors with 3 levels each (factor 1: sameelec/diffelec/diffderma) (factor 2: 1more/PSE/1less). I was actually reading the data in from an SPSS file, and the variable names seem to have copied over correctly (see the screenshot attached).


Kind regards,


Stephanie



Dr Stephanie Cook
Research Assistant
Institute of Cognitive Neuroscience
University College London
17 Queen Square, London WC1N 3AR


________________________________

**Comment by JohnnyDoorn** [comment]
Hi Stephanie,
Thanks for clarifying. I made a .jasp file and attached it to this post (I had to put it in a zip file so github allows me to upload). I specified the 3x3 model, but still did not get an error.
[RM_ANOVA_Stephanie.zip](https://github.com/jasp-stats/jasp-desktop/files/1426735/RM_ANOVA_Stephanie.zip)
Also I don't see your screenshot. If you want you can also send the screenshot (or jasp file with the error - to do so, carry out the steps that lead to the error, and then click 'save as' in the main menu) to my email address: j.b.vandoorn (at) uva.nl
Kind regards
Johnny

**Comment by steph2708** [comment]
Hi Johnny,


I managed to get it working in the end - although still not sure what was going wrong before. Thanks for your help.


Kind regards,


Stephanie


________________________________
