### ISSUE TITLE
This analysis terminated unexpectedly. 

### ISSUE THREAD

**Issue by zfyao** [jasp-stats/jasp-desktop#2091]
## Template for bug reports

* JASP version: 0.8.3.1
* OS name and version: Windows 10 home
* Analysis: correlation matrix
* Steps to reproduce: Regression->Correlation matrix->selects 102 variables-> This analysis terminated unexpectedly. 

Errors as follows:
Error in grDevices::png(filename = fullPathpng, width = width * pngMultip, : unable to start device 'png'
Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)
.plotCorrelations(dataset, perform, options)
.writeImage(width = width, height = height, plot = .plotFunc, obj = TRUE)
grDevices::png(filename = fullPathpng, width = width * pngMultip, height = height * pngMultip, bg = 'transparent', res = 72 * pngMultip, type = type)

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by AlexanderLyNL** [comment]
Hi zfyao,

Can you please upload the jasp file in a zip so we can have a look at it?

Cheers,
Alexander

**Comment by boutinb** [comment]
No answer, if this problem still occurs, re-open this issue
