### ISSUE TITLE
Renaming T-test effect sizes

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-desktop#2095]
![image](https://user-images.githubusercontent.com/1439417/32178456-0739172e-bd8d-11e7-8976-b9be2f686a45.png)

I would suggest renaming the following:
* Rename "Location Parameter" to "Mean difference."
* Rename "Effect size" to "Cohen's d"

Both would yield a consistency between the naming in the options and in the results tables. Furthermore, the mean difference is an unstandardized effect size, so presenting it as an alternative to "effect size" is not precise. To my mind, mentioning the specific statistic (Cohen's d) rather than the general family ("effect size") is also more user-friendly and aids understanding.

While I'm at it: For the Bayesian t-tests, it would be nice with a similar option to choose between unstandardized and standardized effect sizes. It currently only allows for the latter, which can make it difficult to set priors and interpret the interval.

**Comment by lindeloev** [comment]
I thought this would be easy to do a pull request on, even though I'm not familiar with C++. However, when I look at the source code, there is no "Location parameter" but rather a "Mean difference" as I suggested: https://github.com/raoelg/jasp-desktop/blob/development/JASP-Desktop/analysisforms/ttestonesampleform.ui. 

Are you building from a different source or branch or am I missing something here? :-)

**Comment by AlexanderLyNL** [comment]
That's Raoul's branch. I think that you'd like to edit this one:

https://github.com/jasp-stats/jasp-desktop/blob/development/JASP-Desktop/analysisforms/ttestonesampleform.ui

I very much agree with you when we only have the student t-test, but I don't think that mean difference and Cohen's d are appropriate when we're using the Wilcoxon signed-rank test. For instance, the Wilcoxon signed-rank test is concerned with the location of symmetry of the population, which might not be the mean.

**Comment by lindeloev** [comment]
Yes, you are right! The current solution is probably the best so I will close this. Naming "Standardized effect size" would be accurate but perhaps also put people off when "effect size" has become almost anonymous with the standardized ones.

Thanks for pointing me to the correct source; I got lost looking at Raoul's meta-analysis ;-)
