### ISSUE TITLE
Bug analysis terminated unexpectedly

### ISSUE THREAD

**Issue by scoriat** [jasp-stats/jasp-desktop#2114]
This analysis terminated unexpectedly on Oct 13 2017 09:06:53 (Netherlands) JASP 0.8.3.1

Error in grDevices::png(filename = fullPathpng, width = width * pngMultip, : unable to start device 'png'

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)

.descriptivesMatrixPlot(splitDat[[i]], options, splitLevels[i], run)

.writeImage(width, height, plot = .matrixPlotFunc)

grDevices::png(filename = fullPathpng, width = width * pngMultip, height = height * pngMultip, bg = 'transparent', res = 72 * pngMultip, type = type)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by AlexanderLyNL** [comment]
Hi Sarah, 

Could you please zip the jasp file and upload it here? We can then have a look at it and see what's going on. 

Cheers,
Alexander

**Comment by boutinb** [comment]
No answer. If the problem still occurs, re-open this issue.
