### ISSUE TITLE
Bug: unexpected internal error

### ISSUE THREAD

**Issue by FeBall** [jasp-stats/jasp-desktop#2117]
* JASP version: 0.8.3.1
* OS name and version: Win10
* Analysis: Bayesian repeated measures ANOVA
* Steps to reproduce: 

I ran a 2x2x2x2x2 ANOVA. I had 2 within and 3 between subject factors with 120 participants total. First, I entered the within subject factors (repeated measures factors). These are TE (with steps 'E' and 'UE') and Which TE (with steps 'Mul' and 'Max'). Next, I dragged the data (within factors) to the field on the right side (repeated measures cell). Afterwards, I dragged all between subject variables (SP, TA, EX) to the "between subject factors" field.

As the number of models to test is quite large, it took approx. 12 hours to arrive at the bug. I guess that the progress was roughly 90 % given the progress bar (see png). I tried it 3 times. It always produced an error roughly at the same time. I say roughly as the RAM usage was not 100% identical (differed between 2.5 - 2.8 GB). I have a total of 32 GB so RAM should not be a problem. Also the CPU usage was quite low (~10%). 

I would appreciate if you have any solution for the problem.  Thanks and Best, Felix
[JASP_Bug.zip](https://github.com/jasp-stats/jasp-desktop/files/1443867/JASP_Bug.zip)

**Comment by boutinb** [comment]
@FeBall It might be a problem with the communication between the JASP and its Engine. I have a look at it.

**Comment by boutinb** [comment]
@FeBall We have added more memory for the communication of JASP en its Engines. Maybe, this works on a new version of JASP. Can you try?

**Comment by FeBall** [comment]
Dear Bruno, The new version works perfectly. Thank you for your help.

 


Gesendet: Freitag, 22. Dezember 2017 um 15:29 Uhr
Von: "bruno boutin" <notifications@github.com>
An: jasp-stats/jasp-desktop <jasp-desktop@noreply.github.com>
Cc: FeBall <FelixBall@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-desktop] Bug: unexpected internal error (#2117)


@FeBall We have added more memory for the communication of JASP en its Engines. Maybe, this works on a new version of JASP. Can you try?
