### ISSUE TITLE
spaces in Log(BF10)

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2122]
This is obviously a minor point, but it is also easy to fix:
When selecting "Log(BF10)" (in all of the Bayesian analyses), the output in the table refers to this as "Log( BF10 )". I am not sure why we need the extra spaces. @TimKDJ?

**Comment by AlexanderLyNL** [comment]
3 t-tests,

correlation pairs,
 
binomial,
contingency

and the equivalent tests in sumStat. Easy fix.
