### ISSUE TITLE
Median and 25/75 percentile for non parametric data

### ISSUE THREAD

**Issue by MHvid** [jasp-stats/jasp-desktop#2124]
Hi,
Enhancement: I would like to be able to choose median/25/75 percentiles for paired, non parametric data instead of mean/95% CI. Is this a possibility? For instance, in Wilcoxon tests.

**Comment by AlexanderLyNL** [comment]
We have the option to change the 95% confidence interval and if you change it to 50% you'll get a lower bound that corresponds to the 25% quantile, while the upper bound corresponds to the 75% procent quantile. Note however that these quantiles are based on a normal approximation (please correct me if I'm wrong @johnnydoorn). This means that you shouldn't over interpret the numbers, especially, whenever
- the sample size is small
- other assumptions are not met, such as the data being bimodal, while we assume that it is not. 
So don't forget to also look at the descriptives. Please let me know if I can close this.

**Comment by boutinb** [comment]
No answer, if this is still a problem, re-open it
