### ISSUE TITLE
Auto recode and replace missing values

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-desktop#2152]
These are two functions that send me back to SPSS. I have noticed Qualtrics messes up the coding on some variables, so they must be recoded. The SPSS auto recode is hit the button easy. Also missing values, would be nice to have an auto replace, possibly based on a mean approximation from other values within the variable.

**Comment by AlexanderLyNL** [comment]
This is something we'll discuss with the team.

**Comment by AlexanderLyNL** [comment]
Fixed, see gif

https://jasp-stats.org/wp-content/uploads/2017/10/NAplacement.gif
