### ISSUE TITLE
Error: Non-numeric argument to binary operator

### ISSUE THREAD

**Issue by bw729** [jasp-stats/jasp-desktop#2153]
Hi there, I'm using JASP Version 0.8.1.2 to run a Bayesian Repeated Measures ANOVA. My OS is Windows 7 Home. I've done it once successfully using an old dataset and now I'm using a slightly amended dataset where I've included one extra subject, and changed the names of some variables.

I received an error message that the analysis terminated unexpectedly due to an error in model.object[[m]]$bf/null.model$bf: non-numeric argument to binary operator with the following stack trace message:

analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)
.theBayesianLinearModels(dataset, options, perform, status, .callbackBayesianLinearModels, .callbackBFpackage, results, analysisType = 'RM-ANOVA')

My dataset has no missing values, infinities, or unusual values. Can anyone enlighten me on where I have gone wrong and what I can do? It is puzzling that I can perform this analysis successfully on a previous dataset, but not this one. Also I can perform other analyses on this dataset (e.g., frequentist repeated-measures ANOVA), just not the Bayesian repeated-measures ANOVA . 

Thank you!

**Comment by bw729** [comment]
EDIT: I managed to solve this problem by closing and re-opening JASP. Thanks :)

**Comment by TimKDJ** [comment]
Let us know when the problem resurfaces :)
