### ISSUE TITLE
R Package List update necessary?

### ISSUE THREAD

**Issue by stephensrmmartin** [jasp-stats/jasp-desktop#2157]
https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-r-packages-list.md

Again, I am the arch aur maintainer for jasp. With the addition of new analyses, is the above list of needed R packages complete?

**Comment by akashrajkn** [comment]
@stephensrmmartin thank you reporting this.

@TimKDJ I believe you already a list of R packages, can you please update the documentation?

**Comment by TimKDJ** [comment]
I just wrote the script to detect the packages. Frans usually adjusts the packages when we make any changes. @FransMeerhoff can you change this file when a package is added? I can write scripts if needed.
