### ISSUE TITLE
ods import does not import all rows of the ods spreadsheet

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-desktop#2167]
[Logistic regression and chi square.zip](https://github.com/jasp-stats/jasp-desktop/files/1478799/Logistic.regression.and.chi.square.zip)

As an example: When I use JASP 0.8.3.1 to open the attached ods file, the result is an import of rows 1 through 16 only, instead of all 24 rows.

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by akashrajkn** [comment]
@R180 
Thank you for reporting this. We will fix this.

Workaround for now: Open the file in jasp, double click on any cell -> this opens your preferred editor which shows all the rows. Now save it (Crtl + S). JASP will display all the rows after this.
