### ISSUE TITLE
CSV file

### ISSUE THREAD

**Issue by scoriat** [jasp-stats/jasp-desktop#2172]
My Office version of Excel on my PC does not save my files under the right CSV file to be issued under JASP. I have tried so many times. 
[DataJASP.xlsx](https://github.com/jasp-stats/jasp-desktop/files/1482478/DataJASP.xlsx)
[DataJASP2.xlsx](https://github.com/jasp-stats/jasp-desktop/files/1482479/DataJASP2.xlsx)

I am sorry to bother you with such little issue. But could you help me save and send back these two files as CSV please?
Best Sarah

**Comment by AlexanderLyNL** [comment]
Hi Sarah,

Pleas let me know whether this works. If so, could you please close this issue? In case you're interested in other editors you might want to checkout:

https://www.openoffice.org/
https://www.libreoffice.org/

both are free. 

Cheers,
Alexander

[Sarah3.zip](https://github.com/jasp-stats/jasp-desktop/files/1482499/Sarah3.zip)

**Comment by scoriat** [comment]
Alexander Thanks you again. I am very grateful for your help and time. 
I have downloaded the news version of JASP and yes now the data is correct and working fine. This issue can be closed :-)
I will look at the editors you are recommending too. 
All the best, Sarah
