### ISSUE TITLE
Garbled file name?

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2175]
Lexi explained an issue using a .jasp file on our Forum. The file was called "Missingexplained.jasp". After I downloaded it, the name was changed to "p32h00wh46bd.jasp". Weird & unwanted?!
See screenshot
![garbledfilename](https://user-images.githubusercontent.com/8603015/32992815-8233e856-cd4f-11e7-8485-cfee351373e7.png)

E.J.

**Comment by AlexanderLyNL** [comment]
Probably a problem of that forum. I can't even remove the file in a post once it's uploaded. This problem does not occur on the OSF or on my website.

**Comment by AlexanderLyNL** [comment]
Yes it's a problem of that forum.
