### ISSUE TITLE
Bug reports: Meta-analytically combined effect size missing from Forest Plot when Covariates and or Factores are included

### ISSUE THREAD

**Issue by YamilVidal** [jasp-stats/jasp-desktop#2176]
* JASP version: 0.8.4
* OS name and version: Windows 10
* Analysis: Meta-Analysis
* Steps to reproduce: 

When Covariates and or Factores are included in the analysis, the Forest Plot stops showing the Meta-Analytic Effect Size.
I noticed this while playing around with the data from the Meta-Analysis tutorial: https://jasp-stats.org/2017/11/15/meta-analysis-jasp/

Jasp file and figure attached:
[ForestPlot.zip](https://github.com/jasp-stats/jasp-desktop/files/1485860/ForestPlot.zip)

Thx!

**Comment by raoelg** [comment]
Hi Yamil,

This is not actually a bug: If you include covariates and/or factors in a meta-regression, you are trying to predict the (average) effect size from these predictors. The underlying thought is that the effect sizes differ across studies in accordance with the meta-regression model. That implies that there is no overall combined effect size; just a predicted effect size for each study. That is what you see in the forest plot indicated as grey diamonds for each study: The meta-analytically predicted effect size and it's confidence interval. We'll update the blog post to make this explicit. Thanks for drawing our attention to this problem!

**Comment by YamilVidal** [comment]
Hi Raoul,
Thanks for the explanation. I see what you mean. But now a theoretical question. Wouldn't it make sense to take the meta-analytically predicted effect size of each study (grey diamonds) and calculate an overall predicted effect size based on them?
Would this be equivalent to obtain an overall predicted effect size accounting for the influence of the covariates/factors?

Finally, and sorry for departing from the topic of the thread, It would be useful to add in the tutorial info about how to use the model's section to specify models with interactions. Is it only possible to specify interactions between covariares?

Thanks!
