### ISSUE TITLE
Bug: Confidence intervall of ES depends on direction of hypothesis in a paired t-test

### ISSUE THREAD

**Issue by fplatz** [jasp-stats/jasp-desktop#2178]
## Template for bug reports

* JASP version: 0.8.4
* OS name and version: Mac OS 10.12.6 (macOS Sierra)
* Analysis: Confidence intervall of Effect size 
* Steps to reproduce: I used a paired t-test in my own data, but I could replicate the (possible) bug with the example dataset "kitchen rolls". When changing the hypothesis' direction, the confidence interval of the ES will also change and suggest an **95%CI ranging to infinity**. According to Cooper et al.'s (2009) Handbook of research synthesis and meta-analysis this calculation is somewhat deviating from the standards as reported there (and elsewhere).
The same behavior could be observed for the option "location parameter" > "confidence interval"
I have made a screenshot of all three possible outcomes (M1≠M2, M1<M2,M1>M2). 

When I was working on a meta-analysis I remember that most of (the older published) paired t-test results could have been incorporated, if the correlation between both measurements would have been reported too. It is possible to get the correlation by using the correlation calculation separately, but it would be nice to have it with "one click" in the paired t-test.

Best wishes
Friedrich

![confidence intervall of es](https://user-images.githubusercontent.com/15184353/33044905-13f7f74a-ce4b-11e7-9f4b-a0770aac9ddb.png)

[Confidence-intervall-ES.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/1489353/Confidence-intervall-ES.jasp.zip)

**Comment by EJWagenmakers** [comment]
Hi Friedrich,

I think the interval is correct. The CI interval includes all values that are not rejected based on a one-sided test. For a one-sided test, H0 is defined as, say, H0<= testvalue, so values smaller than testvalue will never be rejected. R also gives this interval. What exactly would the alternative solution be?

Cheers,
E.J.

**Comment by fplatz** [comment]
Hi Jan Eric,

I think that the confidence Intervall of the effect size does not depend on the statistics test used for significance testing.  I unterstand the ES reported in the tables as a (posteriori) description of the mean differences in standard deviation units as also claimed by Cohen himself, which should be also reported along with its confidence intervals (t-distribution or z) according to APA. When calculating the ES with metafor for instance you will get other values (especially, no infinity). In other words, what will be described with the ES confidence Intervall if not the (un)certainty of the ES estimate?
Best wishes 
Friedrich

**Comment by fplatz** [comment]
Dear Eric-Jan,

I think I know, what is "wrong" (from my perspective). 

I have replicated the calculation in R (see the file). You're right (please see below), the confidence interval reported in t.test() gives "a confidence interval for the mean appropriate **to the specified alternative hypothesis**" (as written in the help file), but not in terms of accent size (Cohen's d).
Thus, the table's column labels have names with ambiguous meanings. However, I would prefer to have both informations, the confidence interval of the mean as well as the confidence interval of effect size. 

What do you think?

Best wishes
Friedrich
[t.test-and-effect-size-with-R.zip](https://github.com/jasp-stats/jasp-desktop/files/1495390/t.test-and-effect-size-with-R.zip)
 

```
#install.packages("effsize")
#library(effsize)

my.data<-read.csv("~/##YOUR PATH###/Kitchen Rolls.csv")
attach(my.data)
head(my.data)

(H1a<-t.test(q1_check,q2_check,alternative = c("two.sided"), paired=TRUE))

# Paired t-test

# data:  q1_check and q2_check
# t = -0.74179, df = 101, p-value = 0.4599
# alternative hypothesis: true difference in means is not equal to 0
# 95 percent confidence interval:
 # -0.9725939  0.4431822
# sample estimates:
# mean of the differences 
             # -0.2647059 

(H1b<-t.test(q1_check,q2_check, alternative = c("greater"), paired=TRUE))

# Paired t-test

# data:  q1_check and q2_check
# t = -0.74179, df = 101, p-value = 0.77
# alternative hypothesis: true difference in means is greater than 0
# 95 percent confidence interval:
 # -0.8571003        Inf
# sample estimates:
# mean of the differences 
             # -0.2647059 

(H1c<-t.test(q1_check,q2_check, alternative = c("less"), paired=TRUE))

# Paired t-test

# data:  q1_check and q2_check
# t = -0.74179, df = 101, p-value = 0.23
# alternative hypothesis: true difference in means is less than 0
# 95 percent confidence interval:
      # -Inf 0.3276886
# sample estimates:
# mean of the differences 
             # -0.2647059 
             
#Effect size calculation with "effsize"

cohen.d(q1_check,q2_check, paired=TRUE)

# Cohen's d

# d estimate: -0.07344829 (negligible)
# 95 percent confidence interval:
       # inf        sup 
# -0.3496454  0.2027488 


cohen.d(q2_check,q1_check, paired=TRUE)

# Cohen's d

# d estimate: 0.07344829 (negligible)
# 95 percent confidence interval:
       # inf        sup 
# -0.2027488  0.3496454    
```

**Comment by boutinb** [comment]
@EJWagenmakers Should we add an enhancement request? To whom?

**Comment by EJWagenmakers** [comment]
I am willing to defend our present choice. If users want the CI that corresponds to the two-sided test, they can obtain it with a single click.
