### ISSUE TITLE
Bug: Crash when performing calculation in .ods

### ISSUE THREAD

**Issue by isakohrlund** [jasp-stats/jasp-desktop#2183]
JASP crashes when I perform a calculation (e.g. sum or log) in a .ods file. Even if I restart JASP and try to open the file it crashes.

* JASP version: 0.8.4
* OS name and version: Windows 10 Pro 64-bit v 1703
* Analysis: (opening the file)
* Steps to reproduce: open the attached .ods, edit the data in Excel (2016 in my case), perform some kind of calculation, save. 

[crime_beer_and_church.zip](https://github.com/jasp-stats/jasp-desktop/files/1495517/crime_beer_and_church.zip)

**Comment by akashrajkn** [comment]
@isakohrlund I can reproduce when I try to create a new column without explicitly adding a column name. We will fix this in the upcoming release, but for now you can try the workaround.

When you create a new column (eg: sum), add a column name also.

**Comment by boutinb** [comment]
This is solved in the new release 0.8.5
