### ISSUE TITLE
running time error while open file for correlation matrix

### ISSUE THREAD

**Issue by zfyao** [jasp-stats/jasp-desktop#2185]
## Template for bug reports

* JASP version: 0.8.3.1
* OS name and version: Windows 10 home edition
* Analysis: correlation matrix
* Steps to reproduce:  open JASP-->click recent file.ods -->then pop-out running time error.
see picture

![image](https://user-images.githubusercontent.com/9247645/33130859-fed36f7a-cf94-11e7-99b9-91bee1ea0093.png)

**Comment by akashrajkn** [comment]
This is related to issue #2183.

**Comment by zfyao** [comment]
How to solve this issue?

**Comment by akashrajkn** [comment]
@zfyao 

I can reproduce when I try to create a new column without explicitly adding a column name. We will fix this in the upcoming release, but for now you can try the workaround.

When you create a new column (eg: sum), add a column name also.

**Comment by boutinb** [comment]
This ODS problem should be solved in the new release 0.8,5
