### ISSUE TITLE
Bug during independent sample Bayesian t-test

### ISSUE THREAD

**Issue by philippberens** [jasp-stats/jasp-desktop#2196]
* JASP version: 0.8.4.0
* OS name and version: Win 7
* Analysis: Independent sample Bayesian t-test
* Steps to reproduce: 
Load [ex6_geneexp.zip](https://github.com/jasp-stats/jasp-desktop/files/1517722/ex6_geneexp.zip)
Run Bayesian t-test
with Group as Factor and Expression as Variable

Output by JASP:
This analysis terminated unexpectedly.

Error in ttest.rows[[rowNo]]$BF: $ operator is invalid for atomic vectors

Stack trace 
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)

.ttestBayesianIndependentSamplesTTest(dataset, options, perform, state = state, diff = diff)

**Comment by AlexanderLyNL** [comment]
In case you'd like to see the result sooner rather than later, here it is:

![image](https://user-images.githubusercontent.com/10271675/33517819-24e59afa-d78b-11e7-9673-8a82abaaf508.png)

**Comment by philippberens** [comment]
Thanks!
