### ISSUE TITLE
ANOVA contrasts -- important note from Facebook

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2198]
copied from Facebook:

#JASP #JAMOVI #R

I get different results from those three softwares when running an univariate #ANOVA with planned #contrasts.

My data structure: 
  - 170 participants
- IV: four groups (originally called 1,2,3,4 — but I also tried using letters)
- DV: continuous (M1=.009 (SD1=.393), M2=-.091 (SD2=.0412), M3=.253 (SD3=.572), M4=.453 (SD4=.608)
                  - no missing data
                  - repeated contrasts (1 vs. 2; 2 vs. 3; 3 vs. 4)
                  
                  Results in #JAMOVI:
                  - ANOVA: F(3,166)=9.56, p<.001
                  - contrast 1-2: Estimate = .100, SE = .115, t = .0872, p = .385
                  - contrast 2-3: Estimate = -.344, SE = .114, t = -3.008, p = .003
                  - contrast 3-4: Estimate = -.200, SE = .108, t = -1.853, p = .066
                  => seems reasonable because the distance between 1 and 2 is almost exactly .100 (-.344 between 2 and 3; -.200 between 3 and 4)
                  
                  Results in #JASP:
                  - ANOVA: F(3,166)=9.56, p<.001 (same as in JAMOVI)
                  - contrast 1-2: Estimate = -.147, SE = .067, t = -2.183, p = .030
                  - contrast 2-3: Estimate = -.393, SE = .079, t = -3.008, p < .001
                  - contrast 3-4: Estimate = -.296, SE = .067, t = -4.445, p < .001
                  => these results seem suspicious. The estimates are absolutely not in line with the distances between the groups and at least contrast 1-2 should have a different sign than the other two contrasts
                  
                  Results in #R: using the functions contrasts() and summary.lm()
                  - ANOVA: F(3,166)=9.56, p<.001 (same as in JAMOVI and JASP)
                  - Intercept: Estimate = .156, SE = .039, t = 3.969, p < .001
                  - contrast 1-2: Estimate = .147, SE = .067, t = 2.183, p = .030
                  - contrast 2-3: Estimate = .393, SE = .079, t = 3.008, p < .001
                  - contrast 3-4: Estimate = .296, SE = .067, t = 4.445, p < .001
                  => almost the same as in JASP, but now a get an additional intercept! Using this intercept, we can re-calculate the original group means, e.g. for group 3: intercept + (0 * contrast1-2) + (1 * contrast2-3) + (-1 * contrast3-4) = .253 (which is exactly the mean for group 3)
                  
                  +++++++++++++
                    
                    My conclusion:
                    Thumbs up for #JAMOVI. Results seem to be correct and interpretation is straight forward.
                  At first glance #JASP seemed to provide wrong results. Comparing it to R revealed that it only missed to report the intercept — but without the intercept the results are incorrect…
                  #R seems to provide correct results but in my view the interpretation is really complicated. When I calculate a planned contrast, I expect the software to give a simple answer. In my case, one of the questions was: Does group 3 outperform group 2? I don’t want to end up making linear combinations of estimates in order to answer that question…                  
                  
                  What are your thoughts on this? 
                  And a technical question: Does this have to do with the format of the group variable? For preprocessing I used R and Excel to create a .csv-file which I imported to JASP and JAMOVI for analyses.
Henrik Bellhäuser
Best, Henrik

**Comment by acontent** [comment]
maybe useful to note that repeated contrasts were correct in 7.5.5 :
![image](https://user-images.githubusercontent.com/8482944/33607422-57e3c584-d9c1-11e7-943b-1433e914e28f.png)

**Comment by acontent** [comment]
Actually I think that all requests for non-orthogonal contrasts aren't realized as specified, ie, "simple", "deviation", and "repeated" .

**Comment by JohnnyDoorn** [comment]
Hi Alain,
Thank you for bringing this to our attention - I updated the repeated contrasts so the new release will display the correct contrasts again. I will look into the other non-orthogonal contrasts and fix these.
Kind regards,
Johnny

**Comment by AlexanderLyNL** [comment]
@JohnnyDoorn Is this also fixed by pull request  #2216? If so, please close.

**Comment by JohnnyDoorn** [comment]
No, the fixes are still on my branch - will pull request tomorrow! (and close the relevant issues)

**Comment by akashrajkn** [comment]
Fixed in #2223
