### ISSUE TITLE
Missing values in frequency tables

### ISSUE THREAD

**Issue by baltzis** [jasp-stats/jasp-desktop#2202]
*** JASP version:** 0.8.4
*** OS name and version:** Windows 10 (64- and 32-bit)
*** Analysis:** When missing values are defined, in the frequency table they always appear as zero answers and the percent column is always identical to the valid percent column. I think that this can't be right, because the difference between the two columns - as I understand it - are indeed the missing values.

JASP seems unable to show the frequency of the missing values. Is this a bug? Shouldn't there be some difference between percent and valid percent columns (like in SPSS)?

Please not, that I am not sure whether my question is related with some bug in JASP 0.8.4 or I am not doing something right.

Thank you

*** Steps to reproduce:** Import some data file (.sav) with missing values in a variable and get Descriptive Statics for this variable. Ask JASP to display the frequency tables.

**Comment by EJWagenmakers** [comment]
You are correct. Currently the frequency tables do not really use the "percent" column, as the invalids appear to be ignored. We'll fix this. @TimKDJ @vankesteren

**Comment by TimKDJ** [comment]
The correct table will be in version 0.8.5. Thank you for reporting this to us.
