### ISSUE TITLE
Chrash on loading of dataset

### ISSUE THREAD

**Issue by vandenman** [jasp-stats/jasp-desktop#2209]
## Template for bug reports

* JASP version: 8.4.0
* OS name and version: Windows 10 & Development build (7-12-17) on Ubuntu 17.10
* Analysis: NA
* Steps to reproduce:  Load attached dataset, JASP chrashes.

JASP chrashes when trying to load the attached .csv. Both `read.csv` and `readr::read_csv` can read the file without setting any arguments. Perhaps the Timestamp column is the problem (wild guess)? Saving the .csv as a .txt did not solve the problem. 
[survey.zip](https://github.com/jasp-stats/jasp-desktop/files/1538745/survey.zip)

**Comment by boutinb** [comment]
[survey.csv.zip](https://github.com/jasp-stats/jasp-desktop/files/1543294/survey.csv.zip)
Hi @vandenman  I don't know exactly what is going wrong with this file, but if I load it Excel and save it again, then I can load it in JASP. There is apparently some bytes that JASP does not like when reading it...

**Comment by AlexanderLyNL** [comment]
I close this for the moment. Bruno's work around suggests that there's something wrong with the csv file. We should keep in mind that date can be worrying. Please reopen if the problem reappears. 

<img width="1312" alt="screen shot 2018-10-11 at 21 36 44" src="https://user-images.githubusercontent.com/10271675/46829327-c7c5f900-cd9d-11e8-85b9-8f1b59936790.png">
