### ISSUE TITLE
Add coefficient estimates to Bayesian regression

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#2211]
## Template for enhancement requests
Enable users to see the posterior estimates from BayesFactor
* Purpose: Users do not need to look at the classical coefficient estimates anymore
Suggested by one of our participants at the workshop.

**Comment by quentingronau** [comment]
Ah, as far as I understand it, the new BAS functionality will allow the users to get these estimates, right?

**Comment by boutinb** [comment]
@vandenman Is that true that BAS will to this functionality?

**Comment by EJWagenmakers** [comment]
Yes, BAS will do this
