### ISSUE TITLE
Across matched model

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2225]
@TimKDJ 
See screenshot. Should it be "across matched model" (what we have now) or "across matched models"?
I'll also ask Sebastiaan.
![acrossmatchedmodel](https://user-images.githubusercontent.com/8603015/33983670-51aea580-e0b5-11e7-8c19-bd94866cd6f9.png)

Cheers,
E.J.

**Comment by TimKDJ** [comment]
It already is 'models', but it appears to be cut-off on your screen.
Is there an easy fix for this situation @akashrajkn?
<img width="620" alt="screen shot 2017-12-14 at 09 59 51" src="https://user-images.githubusercontent.com/18737241/33983765-a3262ffa-e0b5-11e7-8abc-e6a4846762fd.png">

**Comment by EJWagenmakers** [comment]
Oh yes that's my high-res screen again. Hopefully your update will resolve this issue soon.

**Comment by boutinb** [comment]
Should be solved when we have Qt5.10 and we can use its High Definition feature.

**Comment by vankesteren** [comment]
Fixed in #2308 👍
