### ISSUE TITLE
Some ideas: constraints, collapse-rename-rearrange, mediation, scatter in linreg, autotext

### ISSUE THREAD

**Issue by hmustafamail** [jasp-stats/jasp-desktop#2235]
Dear JASP developers,

First, I want to tell you how much I love JASP. When I first ran an ANOVA in it, and saw how easy it was, I nearly cried. It has quickly become my favorite tool. I deeply appreciate all the work that is going into it and I am excited to see what comes next!

There are some things I would love to see in JASP, so we can live the dream of doing everything in one well-designed tool. I looked for them in the tracker, and I did not find them. I’ve detailed my several ideas here, but if separate tickets are better for you, I will try to delete this post and separate it out. The ideas vary in necessity and difficulty; I have done my best to categorize them appropriately. 

**Using “if” to constrain data to test**
Necessity: 5/5 (5 high)
Difficulty: 2/5 (5 high)

I might just be missing something here, but I believe it is not possible to constrain what data to test using IF. For example, in Stata, I could say something like “regress livingspace income if density=urban,” so that I could see what the effect is in cities, ignoring all the other data. In SPSS, I think this is “select data,” which is kind of clunky. Right now, I am doing this in JASP by creating a new CSV with the data filtered out — not ideal! 

**Ability to collapse, rename, and rearrange analyses**
Necessity: 3/5
Difficulty: 2/5

It would be nice to be able to collapse different tests into their headings (ANOVA, Linear Regression) and rename the headings (e.g., “Linear Regression for cities”) so that I can see what’s going on at a high level. It would also be nice to be able to rearrange the different analyses in the report — sometimes I forget to do an analysis and then it is difficult to backtrack. 

**ANOVA mediation testing**
Necessity: 3/5
Difficulty: 4/5

I believe it’s pretty common in social sciences to have a mediator variable, so it would be nice to have a shortcut way of performing the Baron and Kenny (1986) steps for mediation testing. An integrated Sobel test would be a huge plus, so that the user does not need to copy-paste values into an online calculator. And, as I understand it, the Hayes test of mediation is a requirement for publication in top marketing journals like the Journal of Consumer Psychology, making the Hayes plugin for SPSS something of a “killer app.” 

**Scatter plot option in linear regression**
Necessity: 2/5
Difficulty: 1/5

It would be nice to have an option to display a scatter plot as a check box in the Linear Regression analysis panel, rather than having to add an additional correlation analysis for a plot. 

**Automatic text generation**
Necessity: 1/5
Difficulty: 3/5

Journalists now have tools like Automated Insights that automatically generate natural language from structured data. These are helpful for business reports, since phrases like “Disney’s stock closed at $111.27 on Friday, up 0.66%” don’t take much imagination to write. In my experience, writing results sections is similarly straightforward; phrases like “experimentcondition control was higher than intervention on days to recovery (8.001 v. 3.776, F = 1936.364, df = 1, p < 0.001)” would be a very convenient starting point in my writing, saving me a lot of copy-pasting. 

These are just ideas, ranked by order of how important I think they really are (although I think the more out-there ones would be _very_ cool). If anything is unclear, or needs more justification, I am happy to follow up. 

Thank you so much for this excellent tool -- it means a lot to a poor grad student like me!

**Comment by EJWagenmakers** [comment]
Dear hmustafamail,

Thanks for your kind words and your suggestions. We agree completely. In fact, every last one of your suggestions is already in our road map! That does not mean all the work will be done before Xmas, but it does mean we are keenly aware of this and we will get to these suggestions in due time. Great minds think alike, I guess ;-)

Cheers,
E.J.

**Comment by hmustafamail** [comment]
Thank you for the quick response, this is wonderful to hear :)

Best,
- Mustafa Hussain
