### ISSUE TITLE
Pre-activate "additional info" for Bayesian contingency tables 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2240]
In the t-test, we now pre-activate the "additional info" option (as most users will want it). But this has not yet been done for the contingency table analysis. Would be good to do this, for consistency.
See screenshot. This is not urgent
![additionalinfo](https://user-images.githubusercontent.com/8603015/34166397-0cf7dfaa-e4df-11e7-8ff8-6a5f4c29edb8.png)
.

**Comment by akashrajkn** [comment]
Fixed in #2621
