### ISSUE TITLE
Repeated-measures ANOVA error with high(ish) number of cells (complex numbers or unequal size arrays)

### ISSUE THREAD

**Issue by esdalmaijer** [jasp-stats/jasp-desktop#2241]
* JASP version: 0.8.2 (but also present in 0.7.1.12)
* OS name and version: Windows 7
* Analysis: Repeated-measures ANOVA
* Steps to reproduce: Run a repeated-measures ANOVA with two factors, one of 3 and one of 9 levels.

An issue that has persistent over the past and current versions occurs when the number of cells in a repeated-measures ANOVA is relatively high. For example, a 3x9 analysis will fail to run (see error messages and traceback below). In version 0.8.3, on the same data, a 3x6 rm-ANOVA will work, and in version 0.2.1.12 a 2x9 will work.

This issue has been reported before: 1) In issue #947 on 9 September 2017, 2) on the [forum](http://forum.cogsci.nl/index.php?p=/discussion/3412/repeated-measures-anova-error-with-high-ish-number-of-cells) on 14 September 2017 (closed without being solved), and 3) as a [comment](https://github.com/jasp-stats/jasp-desktop/issues/947#issuecomment-329453360) on issue #947 (issue was never re-opened, hence this one).

Error message in 0.8.2:
```
This analysis terminated unexpectedly.

Error in complete.cases(x, y): not all arguments have the same length

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)

.resultsPostHoc(referenceGrid, options, dataset, fullModel)

t.test(unlist(postHocData[listVarNamesToLevel[[k]]]), unlist(postHocData[listVarNamesToLevel[[i]]]), paired = T, var.equal = F)

t.test.default(unlist(postHocData[listVarNamesToLevel[[k]]]), unlist(postHocData[listVarNamesToLevel[[i]]]), paired = T, var.equal = F)

complete.cases(x, y)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
```

Error message in 0.7.1.12:
```
Invalid comparison with complex values
```

**Comment by JohnnyDoorn** [comment]
Hi Edwin,
Thanks your post. I just looked into it, by simply generating a 9x3 RM dataset with 50 observations per column, but for me the analysis runs fine (see the attached jaspfile). Would you mind sharing the dataset (or even better, the JASP-file containing the error) so I can try to reproduce it? 
Also, did you try it with the latest version of JASP? It might be that this was (perhaps accidentally) fixed in a code-cleanup of the analysis. 
Kind regards
Johnny
[rmCheck.zip](https://github.com/jasp-stats/jasp-desktop/files/1572607/rmCheck.zip)

**Comment by esdalmaijer** [comment]
Hi Johnny,

Thanks for the response! Interestingly, your file works. I've attached a file of mine that doesn't, with a 2x9 rm-ANOVA (also doesn't work with a 3x9 one).

Cheers,
Edwin

[example_data.zip](https://github.com/jasp-stats/jasp-desktop/files/1573133/example_data.zip)

**Comment by esdalmaijer** [comment]
After thinking about this for a bit, the labels `20` and `200` seem to be what makes the errors listed above occur. So I generated a new minimum example, this time with only one factor (`F1`) that has two levels (`20` and `200`). As expected, this results in the same error as above. (File is attached.)

How are variable names resolved, and does it matter that these two have non-unique characters for their first two characters?

[rmCheck_v2.zip](https://github.com/jasp-stats/jasp-desktop/files/1573211/rmCheck_v2.zip)

**Comment by JohnnyDoorn** [comment]
Hi Edwin,
Great detective work - you made solving this a lot easier! I just fixed it in the code and the next release should be able to handle the datasets you shared :)
Kind regards,
Johnny

**Comment by AlexanderLyNL** [comment]
I presume that this is solved. If not, please re-open.

**Comment by esdalmaijer** [comment]
Thanks for that! I'll also mark it as solved on the cogsci forum.
