### ISSUE TITLE
Data Filters are too hard to create using JASP

### ISSUE THREAD

**Issue by robkoper** [jasp-stats/jasp-desktop#2242]
For me, one of the major shortcomings of JASP is the restrictions in data wrangling. The idea to use an external editor like Libreoffice or Excel through .ods files is great. However, this does not support data filters. When you set a filter in Libreoffice to analyse a subgroup (select rows), you need to copy and paste into a new spreadsheet, save it and reopen a new instance of JASP. This is because it seems that the filter information is not used from the ods file by JASP (it should be there because when you save a file with a filter, close it and reopen the file in Libreoffice, the filter is set).

Two possible improvements depending on technological challenges:
1. Include the filter options in JASP itself, like the value editing which is also supported.
2. Read and apply the information from the filter information in the ods file. This last option would be the preferred option, in line with the idea that editing is done in a separate application.

**Comment by boutinb** [comment]
@robkoper We are indeed planning to add filtering options in JASP in the coming months. ODS filtering might be also something we may support. We'll think about it, but filter options in JASP self will be definitively implemented.
Thanks for your comment.

**Comment by JorisGoosen** [comment]
Filtering has been added to JASP, you can use R-code to filter rows or an "easier" filter constructor. It also possible to (de)select nominal/ordinal values and have the corresponding rows filtered in/out.

This is included in the next release.
