### ISSUE TITLE
Bug: Partial eta-squared and omega-squared not available in ANOVA

### ISSUE THREAD

**Issue by Emoll9** [jasp-stats/jasp-desktop#2244]
The options to select partial eta-squared and omega-squared as effect sizes in ANOVA are unavailable (greyed out). The selection is defaulted to eta-squared and cannot be changed.

* JASP version: 0.8.5
* OS name and version: Windows 7 Enterprise SP1
* Analysis: ANOVA
* Steps to reproduce: 1. Open JASP example dataset "Tooth Growth". 2. Select ANOVA -> ANOVA from the menu bar. 3. Select "supp" and "dose" as fixed factors and "len" as dependent variable. 4. Open "Additional Options" tab and select "Estimates of effect size".

**Comment by EJWagenmakers** [comment]
@FransMeerhoff @boutinb @JohnnyDoorn 
Good point. This is actually close to being worth a hot-fix. Let's wait until we get some more feedback (maybe by that time we will have a Windows-signed version too...)
E.J.

**Comment by JohnnyDoorn** [comment]
Thanks for pointing this out - I just fixed it. 
In the meantime, I suggest you use the ancova, but not specify any covariates, since in the ancova gui the different effect sizes are still available!
Kind regards
Johnny

**Comment by boutinb** [comment]
We made a hotfix version 0.8.5.1. You can download it from the JASP file.

**Comment by Emoll9** [comment]
Many thanks for fixing this so fast! Keep up the good work!

**Comment by EJWagenmakers** [comment]
Many thanks to you for finding it so fast!
E.J.
