### ISSUE TITLE
Backward regression not working?

### ISSUE THREAD

**Issue by coledavis** [jasp-stats/jasp-desktop#2248]
[Regression.zip](https://github.com/jasp-stats/jasp-desktop/files/1585941/Regression.zip)

Using linear regression, comparing Enter with Backward regression. Essentially, the results appear to be the same, whereas I think Backward should have removed some variables from the model.
From the csv file I've zipped to you, Sales was the dv, with Price, Instore, Street and Radio as the covariates. 

Jasp version 0.8.5
Operating system Windows 10

Using R, 
file = read.csv("Regression.csv") 
shops = with(file, data.frame(Sales, Price, Instore, Street, Radio))
shops = na.omit(shops)
model = lm(Sales ~ Price + Instore + Street + Radio, data = shops)
step(model, direction=c("backward"))

Alternative R method:
library(MASS)
stepAIC(model, direction="backward")

## Template for bug reports

* JASP version:
* OS name and version:
* Analysis:
* Steps to reproduce: 

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by boutinb** [comment]
@vandenman Can you have a look?

**Comment by AlexanderLyNL** [comment]
It's related to a method changed and we should follow the same steps as the ones done by @vankesteren
