### ISSUE TITLE
Additions of Monte Carlo Simulation and Resampling Methods

### ISSUE THREAD

**Issue by pyemia24131** [jasp-stats/jasp-desktop#2253]
## Template for enhancement requests
 
* Enhancement: Would it be possible to add some Monte Carlo Simulation and resampling methods of analyses to your program?

* Purpose: You have two of the three main approaches to statistical analysis (Frequentist analyses and
Bayesian analyses) but there is a third approach : Monte Carlo simulation using resampling and randomization. This approach is rapidly replacing many non-parametric procedures. See the articles below of Clifford E. Lunneborg and the book MONTE CARLO SIMULATION AND RESAMPLING METHODS FOR SOCIAL SCIENCE by Carsey and Harden. Also take a look at the introductory statistics text book by Lock,Lock,Lock,Lock and Lock. It would be totally awesome if JASP could do Frequentist, Bayesian, **and** resampling/randomization analyses!!!!!!!

[diajrnl.pdf](https://github.com/jasp-stats/jasp-desktop/files/1601678/diajrnl.pdf)

[randomiz.pdf](https://github.com/jasp-stats/jasp-desktop/files/1601683/randomiz.pdf)

**Comment by EJWagenmakers** [comment]
Dear Pyemia24131,

Philosophically, resampling methods are frequentist (see the Efron & Tibshirani book). They take the sample as representative of the population, and then look at the sampling variability across repeated outcomes. So we only use that method if the analytical solution is not available. There are Bayesian bootstraps as well, but the same principle holds: we use these more time-intensive procedures if the analytical method is unavailable.

Cheers,
E.J.

**Comment by AlexanderLyNL** [comment]
I think that this question has been answered. In principle we agree with the request and we will add more bootstrap methods for analyses, where we do not have the exact sampling distribution, or asymptotic approximation to the aforementioned sampling distribution. It also depends on the analysis, which we will identify. One example that implemented this already are the bootstrap confidence intervals in the network analysis.
