### ISSUE TITLE
Segmentation fault in Ubuntu artful (T-Tests - Independent Samples T-Test)

### ISSUE THREAD

**Issue by dbonner** [jasp-stats/jasp-desktop#2257]
## Template for bug reports

* JASP version: 0.8.1 and 0.8.5.1
* OS name and version: Ubuntu 17.10 64 bit (64 gig RAM)
* Analysis:
I was able to install JASP 0.8.1 from the neuro.debian repository and also was able to build JASP 0.8.5.1 from source.   Both versions seem to run fine at first (descriptive statistics works).
* Steps to reproduce: 
1) Load the attached dataset
[Schroeder and Epley 2015 Study 4 data.csv.zip](https://github.com/jasp-stats/jasp-desktop/files/1608547/Schroeder.and.Epley.2015.Study.4.data.csv.zip)
2) Select T-tests - Independent Samples T-Test
3) As soon as you click on 'Independent Samples T-Test' jasp crashes.  If you run it from the terminal, the error message is "Segmentation fault (core dumped)"
The exact same problem occurs whether I run JASP 0.8.1 or JASP 0.8.5.1

I have the same versions of JASP installed on my laptop which runs Ubuntu 17.04 64 bit (32 gig RAM).   The error does not occur on my laptop.  I therefore suspect this is something to do with Ubuntu 17.10 or with the fact that I have 64 gigs RAM on the desktop. 

Does anyone else have Ubuntu 17.10 running who can replicate this error or not?

**Comment by dbonner** [comment]
I upgraded my laptop to Ubuntu 17.10 (artful) and now JASP has the same error (both JASP 0.8.1 and 0.8.5.1).  There must be something in Ubuntu 17.10's upgraded packages that causes the error.

**Comment by JorisGoosen** [comment]
I checked it out under ubuntu 17.10 and it does indeed crash, although only when running it in release mode.
It seems to be something in qtwebkit, we spend some time looking for what went wrong but couldn't find what went wrong exactly. Webkit is actually deprecated in Qt and in the newer versions it is dropped, so we are prepared for a switch to qtwebengine. 

This means there are two workarounds available to you right now, the first is that you run JASP in debug mode. The other is that you checkout the qt510 branch (which works fine with the included Qt5.9 of 17.10) and compile it with that. This is of course not an official release yet but is up-to-date right now.

**Comment by dbonner** [comment]
How do you run JASP in debug mode?
What is the command line to do this?
Thanks,
Daniel

**Comment by JorisGoosen** [comment]
Well, you would have to build it in QtCreator and select the debug-profile.
However, you can also use the ppa, I added a version of jasp that should run without crashing on 17.10. Maybe this is more practical.

**Comment by dbonner** [comment]
Thank you so much Joris for adding Ubuntu 17.10 to the ppa.  It works wonderfully.

**Comment by JorisGoosen** [comment]
Great! And you're welcome.
