### ISSUE TITLE
One-sided t-test and NaN for error%

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2261]
From the Forum:
http://forum.cogsci.nl/index.php?p=/discussion/3699/bayesian-one-sample-t-test-gives-nan-for-error
@AlexanderLyNL (BTW, the one-sided test BF > 2* the two-sided test BF, probably an approximation error)
E.J.

**Comment by boutinb** [comment]
@AlexanderLyNL Is is something we will solve, or can we close this issue.

**Comment by AlexanderLyNL** [comment]
Solved
