### ISSUE TITLE
Re-enable SEM on Linux?

### ISSUE THREAD

**Issue by stephensrmmartin** [jasp-stats/jasp-desktop#2267]
Since I have been packaging jasp for Arch linux, the SEM ribbon has been disabled.

A previous issue suggests this was due to the ubuntu PPA not including enough packages (https://github.com/jasp-stats/jasp-desktop/issues/874), but references no other issues.

I've patched SEM back in for the users of my package with a warning about how it's an unsupported feature for linux users.

Is there a particular reason for why SEM is still disabled by default for linux users?

**Comment by boutinb** [comment]
@akashrajkn Can you try to add SEM on linux (by removing the ifndef linux in module.cpp), and test if everything works correctly?
