### ISSUE TITLE
package or namespace load failed for 'stats'

### ISSUE THREAD

**Issue by ErinMMiller** [jasp-stats/jasp-desktop#2272]
## Template for bug reports
<!--- One of my students. She opened her EXCEL csv file and clicked on Descriptives
![jasp error](https://user-images.githubusercontent.com/35706542/35243430-c018e58a-ffb4-11e7-947e-1034111b2aa5.png)

* JASP version: 0.8.5
* OS name and version: Apple
* Analysis: Descriptives
* Steps to reproduce: Click on Descriptives

**Comment by boutinb** [comment]
@ErinMMiller Could you give more details about this problem: which OS/version do you use? When does this error occur exactly, with which data/analysis?

**Comment by AlexanderLyNL** [comment]
This should be fixed now. Please reopen if the problem resurfaces.
