### ISSUE TITLE
XQuartz not required on macOS anymore?

### ISSUE THREAD

**Issue by hoechenberger** [jasp-stats/jasp-desktop#2275]
Currently the [download page](https://jasp-stats.org/download/) states:

> Installation Notes: On OS X, please have XQuartz installed before commencing installation of JASP.

However, JASP 0.8.5.1 appears to be running fine without XQuarts on my macOS 10.13.3 High Sierra machine.

Notably, the [installation guide](https://jasp-stats.org/installation-guide/) does not suggest to install XQuartz, so probably the note on the download page is just a leftover from previous times and should be removed.

**Comment by boutinb** [comment]
Hi @hoechenberger, XQuartz was needed for plots in R. We have changed the way JASP generates plots, so it is quit plausible that XQuartz is not needed anymore. The documentation is R is not quite clear about it. We have tried to remove XQuartz from out Macs, but we are not completely sure that some parts of it are still installed.
To be sure that XQuartz is not needed anymore, can you generate a plot with JASP, and save it as an eps or a tiff file? If this works on you Mac, we can be quite sure that XQuartz is not necessary anymore, and remove this note from the download page.

**Comment by AlexanderLyNL** [comment]
I think that we fixed this.
