### ISSUE TITLE
Confidence interval of meta effect size is different from jamovi

### ISSUE THREAD

**Issue by RowlinAPsychologist** [jasp-stats/jasp-desktop#2277]
z | SE(z)
-- | --
0.28 | 0.15
0.46 | 0.16
0.03 | 0.09
0.58 | 0.09
0.34 | 0.12
0.40 | 0.16
0.40 | 0.15
0.19 | 0.09
0.54 | 0.12
0.29 | 0.12
-0.11 | 0.14
0.01 | 0.12
0.43 | 0.13
0.29 | 0.14
-0.03 | 0.17
0.03 | 0.09
0.08 | 0.11

* JASP version: 0.8.5.1
* OS name and version: win10
* Analysis: meta-analysis, overall effect size
* Steps to reproduce: ML method

JASP interval: .14 to .34; jamovi (version 0.8.1.14) interval: .08 to .41
Both intervals are 95% by default, right?
Is it because of some methodological contention on formula?

**Comment by boutinb** [comment]
@JohnnyDoorn Can you have a look to this?

**Comment by JohnnyDoorn** [comment]
I think this is better suited for @raoelg , who implemented the meta-analysis.

**Comment by RowlinAPsychologist** [comment]
Sorry, it seemed I confounded standard error (JASP) with sampling variance (jamovi). What I learned was all about standard error, so I thought "variance" refers to the same thing.

**Comment by boutinb** [comment]
So I think we can close this issue.
