### ISSUE TITLE
Proposed changes to "support/significance levels" of B Correlations

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#228]
hey @EJWagenmakers 

I'm proposing that we change the support/significance levels for the correlation table from:

    * > 3, ** > 10, *** ...

to

    * > 10, ** > 100, *** > 1000

to date, the single asterisk has the interpretation that "this is probably an effect", and is considered publishable. in contrast, a BF of 3 is considered anecdotal evidence ("barely worth a mention" i think the quote might be). i think if we try and change the meaning of the asterisk, this will be confusing.

i see the argument that p-values of .05 in some contexts equate to BFs of 2 or 3, and this is an opportunity to discredit p < .05, but i don't know if people will get the point, and might just think that Bayesians have a really low criteria for thinking there's an effect.

**Comment by EJWagenmakers** [comment]
If you'd apply those new criteria, you would never see two stars for most
research efforts. The criteria we picked are already stricter than those
that are in current use [!!], and consistent with Jeffreys. We can point
this out in the help.

Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
> If you'd apply those new criteria, you would never see two stars for
most research efforts.

surely a lot of those p < .001 correspond to BFs > 100 ?

but if not, perhaps:

* BF > 10, ** BF > 50, *** BF > 500

would be more appropriate.

> The criteria we picked are already stricter than those that are in
current use

perhaps it's stricter, but i don't think a BF of 3 is strict enough (or that anyone would publish a finding and back it up with a BF of 3)

> and consistent with Jeffreys

i thought that it was jeffreys who said a BF of 3 was "barely worth a
mention", in which case *not* marking a BF of 3 as "supported" would be
consistent with him?
having said that, i don't know how many people are familiar with jeffrey's.

> We can point this out in the help.

there's no substitute for doing things in the way people expect, and not need the help! (no-one reads the help either) it's better to use symbols in the way that people expect
them to be used (this is what communication is after all). we
could change the meaning of the asterisk, and people could learn about
this in the help, people will want to publish these tables - and JASP's help will not be immediately available to readers of a publication.

i appreciate you want to make a point about p < .05 being really weak,
but i think people won't pick up on this, and will probably just be
puzzled.

we can certainly test this; give people a bayesian correlation table with asterisks marked, and ask them how strong the evidence is.

also if we use the `* BF > 3` criteria, i predict that people will manually
change the tables to `* BF > 10` for publication.

i also predict that stats courses with JASP will begin with

> just be mindful with JASP, it marks BFs > 3 as 'significant', this isn't really appropriate and it's only that way because the people behind JASP wanted to make a point about p-values, so ignore the single asterisk

**Comment by EJWagenmakers** [comment]
Good points. Perhaps 3 is too low. Maybe 5, 20, 100? Or perhaps 10, 30, 100
-- these are still the Jeffreys bounds (chosen because the steps are about
equally large on the log scale!). Having 10 as a lower bound is very strict
though. We also want to be consistent with some of the plots in which we
use the criteria too. So if we opt for more strictness than I say 10, 30,
100. Or maybe introduce a separate symbol for 3 < BF < 10.
EJ

**Comment by jonathon-love** [comment]
> Having 10 as a lower bound is very strict though

but if you think of it in terms of type I error rates (as everyone does?), then if anything it feels a bit weak.

> Or maybe introduce a separate symbol for 3 < BF < 10

a p-value of .04 might have a BF of 3, but surely we're wanting to signal that this is not very strong evidence (barely worth a mention)? surely we want the user to experience the sombre silence of no legitimating symbol?

**Comment by EJWagenmakers** [comment]
Yeah but this will be tough on the null. Anyway, OK, I support the bounds
of 10, 30, 100, for the reasons given before. For now we can work with
that. We can change later if someone has good arguments.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
hey @AlexanderLyNL, this will be relevant to you.

**Comment by AlexanderLyNL** [comment]
The calibration is somewhat complicated. If I remember correctly, a BF_{01} = 2.7 is nearly a p-value of 0.05. See, 

Wetzels, R, Matzke, D, Lee, MD, Rouder, JN, Iverson, GJ, Wagenmakers, EJ (2011). Statistical Evidence in Experimental Psychology An Empirical Comparison Using 855 t Tests

for more details. The more general ideas can be found in Sellke, Berger, Bayarri or Sellke and Berger. If we'd change the point the first cut-off to BF < 10 we'd be treating the Bayesian method much more harsh. We should add another symbol for the BF < 3 category. I think it's worth a paper (short note 2 pages) in explaining the Bayes factor.

**Comment by jonathon-love** [comment]
so Jeffries actually said that a BF of 3 was "substantial evidence", so maybe we should use 3, 10 and 30.

(so if a p-value of .05 is roughly equivalent to 2.7, then it's "nearly substantial", and maybe the take home message of that wetzels paper is that we should use p < .04 for significance)

but 3 doesn't seem very substantial to me.

**Comment by AlexanderLyNL** [comment]
The calibration of 2.7 to a p-value less than .05 only only applies to the t-test. In other case a p of .05 might correspond to 1.5, 3.1, or 1.8. 

What one actually does is a classification — either the null model or the alternative model is worthwhile for further exploration. This implies a 0-1 decision, the one or the other. 

The Bayes factor on the other hand quantifies the evidence within a data for either model. Hence, it is a perfect tool in quantifying evidence on a continuous scale, when only want to report the evidence within the data. 

Any cut-off, thus, also Jeffreys’s, implies a decision criteria. When you make decisions, you should take into account the options you have, the possible consequences of your actions and the situation at hand. Choosing the Grolsh or IJ bier when there’s nothing else to drink or when you have choice. 

In sum, I don’t think that there should be standard cut off of the Bayes factor, as it does not respect the setting of the user. That being said, the same argument goes against a cut-off of p < .05 as it also ignores the situation at hand. One should really take into account what is being studied. However, people (and you as well) want to categorise evidence and, hence, by default one could recommend Jeffreys’s cut-offs. 

Moreover, the fact that you don’t think that a BF of 3 is substantial implies that you wouldn’t believe a p-value less than .05 either. In addition, you reasoning from the Bayes factor to make a judgement about the p-value implies that you’ve got some respect for the Bayes factor. But if you think in terms of Bayes factor to get to a p-value, why not do so directly and cut out the p-value to begin with? 

Lastly, the take home message of 855 t-test is definitely not to lower the p-value, as that wouldn’t help science in general.

**Comment by jonathon-love** [comment]
> In sum, I don’t think that there should be standard cut off of the Bayes factor, as it does not respect the setting of the user. That being said, the same argument goes against a cut-off of p < .05 as it also ignores the situation at hand. One should really take into account what is being studied. However, people (and you as well) want to categorise evidence and, hence, by default one could recommend Jeffreys’s cut-offs.

yeah, i don't want to categorise evidence, but i do recognise that it is a fundamental need of human cognition; i don't consider the purpose of the stars to make the decision for the person; (as you say that depends on the consequences, etc.) it is to make the table of values more apprehendable at a glance.

> Moreover, the fact that you don’t think that a BF of 3 is substantial implies that you wouldn’t believe a p-value less than .05 either. In addition, you reasoning from the Bayes factor to make a judgement about the p-value implies that you’ve got some respect for the Bayes factor. But if you think in terms of Bayes factor to get to a p-value, why not do so directly and cut out the p-value to begin with?

yeah, my statement was facetious and framed within the claims of the paper; that a p-value of .05 corresponds to anecdotal evidence.

**Comment by EJWagenmakers** [comment]
>
> yeah, i don't want to categorise evidence, but i do recognise that it is a
> fundamental need of human cognition; i don't consider the purpose of the
> stars to make the decision for the person; (as you say that depends on the
> consequences, etc.) it is to make the table of values more apprehendable at
> a glance.
>

I agree. I don't think the purpose of the categories is to make decisions;
instead, it is a rough description of the evidential impact in terms people
understand.

By the way, Jeffreys used the term "substantial", but I think this is in
the old-fashioned sense of non-ephemeral. When we translated it we used
"moderate" instead.

Cheers,
E.J.

**Comment by jonathon-love** [comment]
> By the way, Jeffreys used the term "substantial", but I think this is in the old-fashioned sense of non-ephemeral

righto. in which case, i think 10, 30 and 100 is appropriate.

> In sum, I don’t think that there should be standard cut off of the Bayes factor

if it's any consolation @AlexanderLyNL, this will be off by default

**Comment by EJWagenmakers** [comment]
OK. I threw Maarten's magic die and the number came up 12. Because 12 > 10, we will go with bounds of 10, 30, and 100. For now.

**Comment by mmarsman1** [comment]
Always glad to help @EJWagenmakers !
