### ISSUE TITLE
NEW JASP User: No axis labels?

### ISSUE THREAD

**Issue by mwlimoges** [jasp-stats/jasp-desktop#2283]
I am a new user to JASP (and to statistics), and it is a required program for my graduate level statistics class. I am trying to get familiar with the JASP by playing with a fairly simple data set. After opening the data file in JASP under 'descriptive statistics' and placing 'X' in 'variables' and 'student' in 'split', and then checking the 'displaying distribution plots' button, all tables/graphs displayed have no title labels or axis labels. The same for all other tables/graphs. Am I doing something wrong? Any help would be greatly appreciated. Thanks!

[Test.xlsx](https://github.com/jasp-stats/jasp-desktop/files/1678883/Test.xlsx)

* JASP version: 0.8.5.1
* OS name and version: OSX 10.13.3
* Analysis: Descriptive Statistics --> Display distribution plots
* Steps to reproduce: Please see explanation above.

<img width="1280" alt="jasp issues" src="https://user-images.githubusercontent.com/35971251/35584617-8b61b6ae-05c3-11e8-9660-82fba8c880c1.png">

**Comment by boutinb** [comment]
Hello @mwlimoges, this is quite strange, I cannot reproduce it with the same OS, same JASP version, same data (I transformed the xls file into a csv file)... Can you send also the JASP file?

**Comment by mwlimoges** [comment]
Thank you for looking into this. Attached you will find the JASP file with the data.

[JASP Errors copy.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/1682679/JASP.Errors.copy.jasp.zip)

**Comment by boutinb** [comment]
Hello @mwlimoges, this might be a problem with a missing font. The plots use the Arial font. If you open the Font Book app on your Mac, you can check if the Arial Font installed and enabled is.

**Comment by mwlimoges** [comment]
This worked! I did not release my MacBook had Arial fonts off for whatever reason. I enabled all Arial fonts, restarted the OS and fired up JASP and low-and-behold, all axis had labels. Thank again for your help. Cheers!

**Comment by AlexanderLyNL** [comment]
Thanks for the feedback and glad that we could help.
