### ISSUE TITLE
Feature request: option to print R code to the output

### ISSUE THREAD

**Issue by drleehw** [jasp-stats/jasp-desktop#2290]
Could you please consider adding a single checkbox option to every test that would output the actual R code executed in the output window? It would make JASP the single best teaching tool for R. One could run an analysis, get the output, but also see precisely how the R code is put together to obtain such an output. 

(I realise this won't work where a test doesn't rely on R, but I get the impression most of the tests do rely on R packages.)

In my view, this would make JASP of significant interest to people who really want to teach their students R, ultimately, and who would therefore have little interest in JASP. As a teaching tool, it could be unsurpassed.

**Comment by EJWagenmakers** [comment]
I can say a lot about this, but I'll keep it short: we have been working on this for some time now, and one of our team members has this as his only job. I am reluctant to set a time line but it will be done.

**Comment by drleehw** [comment]
This is wonderful news! Exciting! Thanks.
