### ISSUE TITLE
Distribute in GNU/Linux using flatpak

### ISSUE THREAD

**Issue by diazbastian** [jasp-stats/jasp-desktop#2294]
* Enhancement: Provide a universal package for installation in GNU/Linux
* Purpose: A distro-agnostic package is a better way to distribute easy-to-install software over a wide range of distributions. Currently there are no native packages for other distros besides Ubuntu or Arch and the compilation is somewhat complicated for new users. [Flatpak](https://flatpak.org/) is the best solution for this problem.

I was inspired by this [Github ticket from Jamovi](https://github.com/jamovi/jamovi/issues/423) that shares the same spirit.

**Comment by charlesjt** [comment]
I think it's appropriate. Last year was discussed at the University where I study, looking for a better alternative to SPSS, where JASP was a candidate, however, was ruled out by its difficulty of installation and maintenance in CentOS (CentOS and Windows are used equally). In the end they opted for an agreement with Stata where low cost support was offered.

Some academics try to promote alternatives, but there were always obstacles such as the lack of advanced procedures in PSPP or the difficulty of learning R for non-specialized biostatistics courses.

**Comment by EJWagenmakers** [comment]
Good point, let's see what we can do. 
E.J.

**Comment by JorisGoosen** [comment]
This looks like an interesting way to distribute to all linux-distro's equally easy. Ill try it out soon.

**Comment by dietrichstats** [comment]
I'm sorry to comment here, I did not fully understand the forum. I've been using Jasp for about a year, in its version for Windows 32 bit with Wine and it's better than it sounds. Any method that facilitates a native installation is good. Thanks for this excellent Software.

**Comment by JorisGoosen** [comment]
So I took a look and it seemed doable and luckily I turned out to be right ;)
Next release will include flatpak and will thus be installable on all linux-distros that support flatpak!
(which should include a lot of them)

**Comment by EJWagenmakers** [comment]
Great work @JorisGoosen ; 
@diazbastian: thanks for the suggestion, this was extremely useful

**Comment by bertob** [comment]
@JorisGoosen to make the flatpak easier to discover and available to more people you could submit it to [Flathub](https://flathub.org/). It's kind of like an app store for flatpaks. Some distributions enable the Flathub repository by default, so users can find Flathub apps in their native software installation app (e.g. GNOME Software).

**Comment by diazbastian** [comment]
I am very excited about this [news](https://jasp-stats.org/2018/02/23/jasp-0-8-6-preview-frequentist-chi-square-test-revamped-bayesian-regression/) and I can attest that a community is very interested in this release. Thank you very much for the quick consideration of this proposal.

**Comment by JorisGoosen** [comment]
@bertob, trying to get it in flathub would be a good idea, for this I have to work a bit more on specifyin specific versions for components. At the moment it will be set up so that installing it will be as easy as copy-pasting a single line to the commandline so I think this will already be pretty nice.
