### ISSUE TITLE
Descriptives plots failure

### ISSUE THREAD

**Issue by angelamsli** [jasp-stats/jasp-desktop#2299]
This is what happens when I click descriptives plots. Mac pro retina. OS X El capitan. Version 10.11.6

**Comment by angelamsli** [comment]
This analysis terminated unexpectedly.

Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : polygon edge not found

Stack trace
lapply(vps, push.vp, recording)

FUN(X[[i]], ...)

push.vp.vpTree(X[[i]], ...)

push.vp(vp$parent, recording)

push.vp.viewport(vp$parent, recording)

grid.Call.graphics(L_setviewport, vp, TRUE)

(function (x) 
{
    widthDetails(x)
})(list(label = 'ActualWait', x = 2, y = 0.5, just = 'centre', hjust = 0.5, vjust = -1, rot = 90, check.overlap = FALSE, name = 'GRID.text.112', gp = list(fontsize = 18, col = 'black', fontfamily = '', lineheight = 0.9, font = 1), vp = NULL))

widthDetails(x)

widthDetails.text(x)

grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, resolveHJust(x$just, x$hjust), resolveVJust(x$just, x$vjust), x$rot, 0)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by akashrajkn** [comment]
This is similar to issues #2496 and #2449. 

Restoring the standard fonts should solve this error (check out this [stackoverflow thread](https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon/49653833#49653833)).

Open `Fontbook` -> `File` -> `Restore standard Fonts`.

Reopen the issue if the problem persists
