### ISSUE TITLE
Post-Hoc effect Size calculation

### ISSUE THREAD

**Issue by 1990jr** [jasp-stats/jasp-desktop#2300]
* JASP version: 0.8.5.1
* OS name and version: 
* Analysis: one way anova post-hoc tests
* Steps to reproduce: 
Hi there,

I conducted a one-way anova with 3 groups (N=55, N=76, N=90). I got a significant main effect and I conducted post-hocs on JASP with Holm correction. 
I wanted to get the cohen's and I realized that for calculation of the cohen's implemented in JASP seems to be just the t-value/sqrt(N). However, the N is not pooled (like for the pooled std) but simply summation of all the subjects (55+76+90). Is it the correct way to do it? Because the cohen's d for unpaired t-test, we do the pooling of the std deviations.

Thanks in advance.

J

**Comment by JohnnyDoorn** [comment]
Hi J,
Thanks for the feedback - the effect size calculation was indeed taking the total N. I updated the code so now it uses the correct denominator for the effect size.
If you want you can send me your data, so I can take a closer look, or you can wait for the next release, which should be within two weeks =)
Kind regards,
Johnny

**Comment by 1990jr** [comment]
Dear Johnny,

Thanks a lot for your reply and promptness to help. However, I have already made a small script for data. Looking forward for the new release of JASP. It's very convenient for this sort of stats.
Keep the good work.

J

**Comment by 1990jr** [comment]
Dear Alexander and Johnny,

Thanks for your reply. I'm sorry that I didn't reply earlier. I see that you guys have released a new version of JASP, great job!
However, regarding the cohen's d calculation, for the post-hoc t-test, for the t-value calculation to compare group 1 with group 2, for the SD you are using the pooled SD of N groups (N is the number of groups you used in your ANOVA). However, for the cohen's d calculation, for the group 1 and group 2, you only use SD pooled across group 1 and 2. Do make it consistent you shouldn't put you the pooled SD across all the N groups?

For example, if you have 3 groups, for a post-hoc calculation for comparison between group 1 and group 2, it shouldn'd be:

M1 = mean(X1);          % mean group 1
M2 = mean(X2);          % mean group 2
SD1 = std(X1);          % std of group 1
SD2 = std(X2);          % std of group 2
SD3 = std(X3);          % std of group 3
N1 = length(X1);        % number of elements in group 1
N2 = length(X2);        % number of elements in group 2
N3 = length(X3);        % number of elements in group 3

% pooled SD accross all 3 groups
pooledSD = sqrt(((N1-1)*SD1^2+(N2-1)*SD2^2+(N3-1)*SD3^2)/(N1+N2+N3-3));

CohensD = (M1-M2)/pooledSD;         % cohen's D
t_val = CohensD/sqrt(1/N1+1/N2);    % t-value
SE = pooledSD*sqrt(1/N1+1/N2);      % stardand error

Sorry for the matlab notation.

Best,

J
