### ISSUE TITLE
Repeated Measures ANOVA

### ISSUE THREAD

**Issue by boutinb** [jasp-stats/jasp-desktop#2307]
Test Repeated Measures ANOVA

**Comment by AlexanderLyNL** [comment]
The addition of a Celebrity (identifier 1 to 8) as between subject factors leads to an error. Most likely not enough data (vector(0) like) and the evaluation of the value goes bad. 
[alexanderRmAnova.zip](https://github.com/jasp-stats/jasp-desktop/files/1725641/alexanderRmAnova.zip)
