### ISSUE TITLE
B t tests: add varaible name to plots

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#232]
Hi Jonathon,

Concerning the headings for the plots: Can I do that in the R file or do you
need to do that in the cpp file?

**Comment by jonathon-love** [comment]
yup, you can do that in R. take a look at the classical ANOVA; there should be an entry in the .meta object of type h1, or h2

**Comment by quentingronau** [comment]
Ok. Currently, I am creating one list for the plots of all variables. I know that the meta objects usually  appear one after another. Is there a smart way to "fit in" the headings in the plots list at distinct positions? If not, I will just create a list of plots for every single variable with a corresponding header.

**Comment by jonathon-love** [comment]
oh you're right. i don't have support for this. leave it to me.

**Comment by quentingronau** [comment]
Ok, thanks.

**Comment by jonathon-love** [comment]
hey @quentingronau, it now uses the title from the image object to add headings. at the moment, if adjacent plots have the same heading, it removes all but the first; this may or may not be what we want.

the heading is a h2, which is consistent with the sub-headings in the ANOVA; but we can make them larger (or smaller) if you think that would be appropriate.

alternatively, if you just think everything is fine, let me know i will close this issue.

**Comment by quentingronau** [comment]
I like it. I think we want that the variable name just appears for the first plot when there are several for one variable, as you implemented. Just three things:
1)  This does not seem to work when there are more than 2 plots, then the third plot receives a label again. 
![unbenannt](https://cloud.githubusercontent.com/assets/8697436/6041207/70748a38-ac7a-11e4-867a-94293d2044b0.png)

2) Could we move the label undeneath the plots a little bit away from the previous one?
3) The labeling does not work properly when one of the plots is omited, for example when the sequential plot is not possible.

**Comment by quentingronau** [comment]
Variable name is displayed twice also for two plots when doing the paired t test:
![unbenannt2](https://cloud.githubusercontent.com/assets/8697436/6041581/00850f50-ac7e-11e4-9d2c-d5be751e414b.png)

**Comment by jonathon-love** [comment]
I've changed it so that it doesn't remove the titles when two adjacent plots have the same title. When you have a lot of plots, they don't all fit on the screen, (including the heading not fitting on the screen) and it's easy to lose track of what is what.
But the heading spacing should be fixed. Let me know what you think.

**Comment by quentingronau** [comment]
I have an open pull request, so I think I need to wait until it is merged before I can rebase my repo, right?

**Comment by jonathon-love** [comment]
good catch! it's now merged.

**Comment by quentingronau** [comment]
Thanks. Looks great! I agree that it is better to label every single plot.

Concerning "3) The labeling does not work properly when one of the plots is omited, for example when the sequential plot is not possible."

That is an issue caused by me, because I do not place the plots at the position of the corresponding variable name in the list if one is omited. I will work on it tomorrow, today I have a class.

**Comment by quentingronau** [comment]
Ok, I think with my latest pull request the plots should now be placed at the right positions, even when some plots are omited.
