### ISSUE TITLE
Test Bayesian Binomial Test

### ISSUE THREAD

**Issue by boutinb** [jasp-stats/jasp-desktop#2328]
Test Bayesian Binomial Test for new release

**Comment by AlexanderLyNL** [comment]
1. Posterior of debSame vanishes when moving from BF10 to BF01 or log(BF). Shouldn't happen
2. With highly skewed prior alpha = 9999 and beta = 1 we get a negative posterior density
3. With highly skewed prior alpha = 9999 and beta = 1 the sequential analysis searches for Inf0
[alexanderBBinom.zip](https://github.com/jasp-stats/jasp-desktop/files/1725502/alexanderBBinom.zip)
