### ISSUE TITLE
Test Bayesian Contingency Table

### ISSUE THREAD

**Issue by boutinb** [jasp-stats/jasp-desktop#2329]
Test Bayesian Contingency Table for new analysis

**Comment by AlexanderLyNL** [comment]
0. No state, no callback, log odds ratio plot add warning [Next release]
1. Continuous data are processed differently when used as rows or columns. In rows, does not work [No regression]
2. contBinom-contNorm works, but once you change the row ordering get an error. [No regression], see my dropbox

[alexanderBConting.zip](https://github.com/jasp-stats/jasp-desktop/files/1725628/alexanderBConting.zip)
