### ISSUE TITLE
Test Log Linear Regression

### ISSUE THREAD

**Issue by boutinb** [jasp-stats/jasp-desktop#2332]
Test Log Linear Regression for new release

**Comment by Kucharssim** [comment]
No bugs found.

Enhancements:
- Allow selecting options 'confidence intervals' and 'VS-MPR' only when 'Estimates' table is already selected
- Check if 'Counts' variable contains only integers (what does it do when counts are decimal numbers?)
- Missing data handling
- Producing descriptive tables/plots (or at least include 'Counts' in Descriptives for producing tables for aggregated data)
- Compared with Bayesian log-linear #2330: Coefficients tables have different parametrisations. For example, in case of binary factors, frequentist reports the coefficients associated with level 2, bayesian the one associated with level 1. Making it the same would allow producing corresponding tables in freq. and bayes version in one JASP file. See figures.

![image](https://user-images.githubusercontent.com/7093546/36440670-66d1daea-1670-11e8-933c-860c3a4b863d.png)

![image](https://user-images.githubusercontent.com/7093546/36440673-71fbf63a-1670-11e8-8ea6-15cf3d7ebc3d.png)

**Comment by AlexanderLyNL** [comment]
Done
