### ISSUE TITLE
Warning in Bayes Factor robustness check plot

### ISSUE THREAD

**Issue by koenderks** [jasp-stats/jasp-desktop#2336]
## Template for bug reports

* JASP version: 0.8.6
* OS name and version: Windows
* Analysis: All Bayesian t-tests
* Steps to reproduce: Put any variables in the  boxes, then click informed prior but do not change anything. Then click bayes factor robustness check. Plot will be made (which means you wait), but then a warning is given that it is not supported for informed priors. But plot does show up?

## Template for enhancement requests
 
* Enhancement: Before calculating anything, give the warning that it is not supported.
* Purpose: Clarity

**Comment by boutinb** [comment]
@Janto91 can you solve this?

**Comment by Janto91** [comment]
@boutinb I think I solved it.
