### ISSUE TITLE
Test Feedback ANOVA

### ISSUE THREAD

**Issue by Janto91** [jasp-stats/jasp-desktop#2337]
- [ ] Bug 1: In an ANOVA with DV = V1, IVs = contBinom, facGender, facExperiment, and facFive, there is a warning "Singular fit encountered; one or more predictor variables are a linear combination of other predictor variables", but still all effects are estimated. However, post-hoc tests are not conducted.
- [ ] Bug 2: In an ANOVA with DV = V1, IVs = contBinom, facGender, facExperiment, facFive, and debString, no 3-way, 4-way, and 5-way interaction effects are estimated and it is not clear why.

[Here](https://github.com/jasp-stats/jasp-desktop/files/1727421/Test_ANOVA_Bugs.zip) are the jasp-files for Bug1 and Bug 2.

- [ ] Other 1: For Additional options / Marginal means, change "Compare main effects" to "Compare marginal means to 0".
- [ ] Other 2: For contrasts, I think there should be a list of options that people can choose from rather than having to write a word. Especially since there are no further information on which options are accessible.

**Comment by Janto91** [comment]
Here are the jasp-files for Bug 1 and Bug 2
[Test_ANOVA_Bugs.zip](https://github.com/jasp-stats/jasp-desktop/files/1727421/Test_ANOVA_Bugs.zip)

**Comment by JohnnyDoorn** [comment]
I don't understand your "other 2" - we offer several contrast choices (simple, deviation, etc) so I'm not sure where someone would have to write something..

**Comment by Janto91** [comment]
Regarding Bug1, I think the reason for the warning is that there is a perfect relationship between subsets of the levels of the the different factors. For example for "Gender" and "Region", there is only one female and no male living in Australia. Therefore, for this level of Region, there is a perfect relationship between "Gender" and "Region". Thus, the degrees of freedom in the ANOVA table are decreased for each combination of levels for which this is the case and post-hoc tests cannot be conducted.

So, the warning seems to be justified. The problem is rather that it is not very informative for the user.
