### ISSUE TITLE
Test Feedback RM ANOVA

### ISSUE THREAD

**Issue by Janto91** [jasp-stats/jasp-desktop#2339]
- [ ] Bug 1: Error message: "Reciprocal condition number = (very small number)" in a RM ANOVA with contcor1 and contcor2 as RM cells and contExpon, contWide, or contNarrow as Covariate.
- [ ] Bug 2: In a RM ANOVA with two within subjects factors, one with three and one with two levels (contExpon, contWide; V1, debCollin1; debCollin2, debEqual1)
a. a sphericity test results in NaN for the p-values,
b. for post hoc tests, Tukey and Scheffe p-values are NaN (there is footnote stating that Scheffe is not appropriate for RM ANOVA (does this mean they should be NaN?), but no additional information for Tukey is provided)
c. pooling the error term for RM factors results in an error message.
d. requesting effect sizes results in an error message.

[Here](https://github.com/jasp-stats/jasp-desktop/files/1727519/Test_RM_ANOVA_Bugs.zip) are the jasp-files for Bug 1 and Bug 2.

- [ ] [Alexander](https://github.com/jasp-stats/jasp-desktop/issues/2307) (moved here to have everything in one issue): The addition of a Celebrity (identifier 1 to 8) as between subject factors leads to an error. Most likely not enough data (vector(0) like) and the evaluation of the value goes bad. [Here](https://github.com/jasp-stats/jasp-desktop/files/1727541/alexanderRmAnova.zip) is the jasp-file.
- [ ] Other 1: For contrasts, I think there should be a list of options that people can choose from rather than having to write a word. Especially since there are no further information on which options are accessible. In the analysis from 3, I get an error message for whatever I type in there except for "none" (although I am not sure what my options are).

**Comment by AlexanderLyNL** [comment]
Please add the jasp-file to this.

**Comment by Janto91** [comment]
Here are the jasp-files for both bugs.
[Test_RM_ANOVA_Bugs.zip](https://github.com/jasp-stats/jasp-desktop/files/1727519/Test_RM_ANOVA_Bugs.zip)

**Comment by boutinb** [comment]
@JohnnyDoorn Is this something to be solved for the release?
