### ISSUE TITLE
B t test: callbacks are not working anymore

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#234]
Hi Jonathon,

One or two weeks ago, I implemented callbacks so that the table and the different plots appeared one after another. On my computer, after rebasing my repo yesterday, this appears to not work anymore. Do you have an idea why?

**Comment by jonathon-love** [comment]
ah yes, i've possibly broken something. i'll look into it.

**Comment by quentingronau** [comment]
Thanks
