### ISSUE TITLE
Bugs in Bayesian Correlation Matrix

### ISSUE THREAD

**Issue by ASarafoglou** [jasp-stats/jasp-desktop#2351]
Bug for variable debMiss99.

Accompanying JASP file can be found here:

https://www.dropbox.com/s/jtbp3mqga2cyrz3/BUGS_BayesianCorrelationMatrix_0.8.6.jasp?dl=0

Error in if (!(numericCheck[i] && sdCheck[i] && infCheck[i])) {: missing value where TRUE/FALSE needed

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.correlationMatrixPlotBayesian(dataset, perform, options, hypothesis = options$hypothesis)

**Comment by AlexanderLyNL** [comment]
This is a plot thingie that I'll fix in a next release. It occurs with some boundary cases that I'll cover after the revamp.
