### ISSUE TITLE
Changing dataset without new JASP instance opening

### ISSUE THREAD

**Issue by timdraws** [jasp-stats/jasp-desktop#2354]
* Enhancement: When you have a dataset loaded in JASP, and you open a new one, a new instance of JASP opens immediately. Instead it would be cool if an option pops up to close the current analysis / dataset _or_ open a new instance of JASP.

* Purpose: Sometimes I accidentally open the wrong dataset. If I then just open the dataset I actually wanted to open, a new JASP window opens, which is often annoying. To prevent that, I have to close the current dataset manually, state that I don't want to save, and then load the new dataset.

**Comment by boutinb** [comment]
I'm not sure this a good idea. You don't want this question to pop up each time you open a new data file. Besides, In the file menu, you have also the Close option, which does what you want already.
Someone has another meaning about it?

**Comment by timdraws** [comment]
What do others think about this? Am I the only one that thinks it's annoying that a new instance of JASP opens every time you open a new dataset? Maybe it's just because I often work with several datasets for the video's and GIFs we're making.

Maybe a tab-function could be the solution, just like you open different websites in tabs inside browsers. This way, you could have several datasets / (strings of) analyses opened at the same time.

**Comment by AlexanderLyNL** [comment]
I'll close this for now. We'll discuss this in person and I'll keep it in mind.
