### ISSUE TITLE
Bayesian RM Anova: options

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#237]
There are a bunch of options in the tab that we do not need.
We do need the options (I guess):
- covariates
- random factors
- outputEffects (produce effects table)
and for the future:
- posterior Distributions
- posterior Estimates

**Comment by jonathon-love** [comment]
Implemented

**Comment by mmarsman1** [comment]
Awesome!

**Comment by jonathon-love** [comment]
wait. i did this ages ago.

**Comment by mmarsman1** [comment]
Oh really? I'll check tomorrow if everything works properly then (=

**Comment by jonathon-love** [comment]
*chuckles*
