### ISSUE TITLE
Cannot copy figures

### ISSUE THREAD

**Issue by lvanderlinden** [jasp-stats/jasp-desktop#2372]
* JASP version: 0.8.5.1
* OS name and version: Ubuntu 17.10

When trying to copy a figure, a window with an error message pops up (see attachment). In the terminal, I also see this message: 
libpng warning: iCCP: known incorrect sRGB profile

![screenshot from 2018-02-25 17-50-41](https://user-images.githubusercontent.com/2217254/36644030-9267a74c-1a54-11e8-89fd-dc22df00f7f7.png)

**Comment by akashrajkn** [comment]
@lvanderlinden thank you for reporting this issue. For now, as a work around, you can use 'Save image as' option.

**Comment by akashrajkn** [comment]
#2376 Fixes this issue

**Comment by lvanderlinden** [comment]
Thank you so much!!!
