### ISSUE TITLE
Meta-analysis: Error in (function (class, type, ...)

### ISSUE THREAD

**Issue by oolon-colluphid** [jasp-stats/jasp-desktop#2373]
JASP Version 0.8.5.1
macOS High Sierra (10.13.3)

Issue with Meta-analysis running Hedges approach as well as when trying to run Hunter-Schmidt approach.

I get the following error:
Error in (function (class, type, ...) : Could not find message for class error and type NA

Please help resolve.

Thanks.

**Comment by Janto91** [comment]
@oolon-colluphid : Thanks for reporting this error. Would you mind sharing your jasp-file with us?

You can save your analysis as jasp-file by
- reproducing the error you reported above
- clicking on "File"
- clicking on "Save as"
- selecting a name and a location to save the file
- uploading the file to this thread

Thanks again for your cooperation!

**Comment by AlexanderLyNL** [comment]
This should be fixed now. Please reopen if the issue reappears.
