### ISSUE TITLE
Add function to adjust the Y-axis range of plots manually

### ISSUE THREAD

**Issue by hcp4715** [jasp-stats/jasp-desktop#2378]
## Template for enhancement requests
<Yesterday my colleague, who has no experience in R, used the boxplot of the descriptive statistics, and find the box plot of JASP is very impressive. 
However, she found that all the y-axis scale are automatically generated, so it is difficult to compare different plots. So I guess it would be good to have the option to adjust the range of y-axis mannually> 
* Enhancement: add an option that allows adjusting the range of y-axis manually.
* Purpose: People might find the plot function more flexible and useful.

**Comment by vankesteren** [comment]
Hi @hcp4715,

Thanks for the suggestion! We're definitely looking into ways of doing this, not only  for the box plot, but more generally for all plots. This is what @boutinb mentioned. Keep an eye on JASP development for this feature!

(I'm closing this issue for now 😄 )

Erik-Jan
