### ISSUE TITLE
One Sample T-Test: Possible error in the estimation of the 95% CI for Mean Difference

### ISSUE THREAD

**Issue by rhileno** [jasp-stats/jasp-desktop#2381]
## Template for bug reports

* JASP version: v. 0.8.6
* OS name and version: Windows 10 Home
* Analysis: One Sample T-Test - 95% CI for Mean Difference
* Steps to reproduce: We have detected a possible error in the One Sample T-Test. We believe that the estimation of the 95% CI for Mean Difference is incorrect (see picture). The CI would have to give -10.96 to -8.14. However, it gives 23.592 to 26.408. We believe that this confidence interval is not the 95% IC for Mean Difference, but that it is the 95% IC for Mean.

![one sample t-test - error ci for mean difference](https://user-images.githubusercontent.com/36966655/36861242-aa229a22-1d83-11e8-82a2-8a396ac512cc.png)

**Comment by Janto91** [comment]
Thank you, @rhileno!

You are totally right! I fixed this issue and the correct version of the one sample t-test will be available in the next release of JASP!

**Comment by AlexanderLyNL** [comment]
There's a difference between a confidence interval and a prediction interval. The confidence interval is an interval use to estimate and not necessarily to test, see 

https://arxiv.org/abs/1705.01064

Section 2.2 and Section 2.3
