### ISSUE TITLE
Data Editing/Automatic Sync doesn't work on GNU/Linux

### ISSUE THREAD

**Issue by haevalencia** [jasp-stats/jasp-desktop#2392]
* JASP version: 0.8.6 - Feb 28 2018 15:35:46 (Netherlands) gnu/linux Flatpak
* OS name and version: Fedora 26
* Analysis: When trying to edit data (double click on a cell) it is expected to open the default spreadsheet, however this doesn't happen, even if the spreadsheet is opened with the data manually, automatic synchronization doesn't work either. Manual synchronization works well.
* Steps to reproduce: 
Open a Data Set
Double click on a cell

**Comment by diazbastian** [comment]
This was already the case with the version provided in the PPA for Ubuntu, however, using the keyboard shortcut Ctrl + Y to update the data works well with LibreOffice and OnlyOffice.

**Comment by haevalencia** [comment]
I noticed that in the recently updated version 0.9, the synchronization works perfectly, it even shows a nice dialog to select the default app to open data, all very cool. I guess if nobody else has problems, this ticket can be closed.

@diazbastian Can you test if the synchronization works for you? Thank you

**Comment by diazbastian** [comment]
Automatic sync works well for me after the update.

**Comment by AlexanderLyNL** [comment]
Thanks for the feedback, this is very useful! Please reopen if the problem reappears.

**Comment by 4x1eg** [comment]
- JASP version: 9.0.1 - September 17, 2018,  gnu/linux Flatpak
- OS name and version: Debian 9.5 (Stretch)
- Analysis: Can't edit data file (CSV or ODS) with Libreoffice directly from JASP 9.0.1 on Debian Stretch
- Steps to reproduce: 1) Open a Data Set with analysis. 2) Double click on a cell

Any ideas why can't I edit a data file with LibreOffice on Debian Stretch 9.5? 
Tried different syntaxes for command (in preferences) but to no avail. Although it should work with: "Libreoffice". Libreoffice is associated CSV and ODS and naturally opens it.
Also, it is the default editor. It always states: "Unable to start the editor: Libreoffice. Please check your editor settings in the preference menu."
On Windows 10 it works fine as it should with LibreOffice. 
Any ideas?

**Comment by haevalencia** [comment]
@4x1eg What version of flatpak are you using? Only in the newer versions appear a dialog that allows you to select an application to edit the data set.

![flatpak](https://user-images.githubusercontent.com/17348259/45669054-2a0c4080-baf5-11e8-9c85-94ead6caaec8.png)

 I noticed that in the last update of the LibreOffice package (flatpak) doesnt appear in the list of applications, but it does appear if you have installed the official version downloaded from the web or installed from the repositories (tested on fedora).

Anyway, if you have the synchronization turned on in Jasp and you open the file corresponding to the active data set with LO Calc, any saved change will be reflected in Jasp automatically.

**Comment by diazbastian** [comment]
Can anyone confirm if this is a JASP, LibreOffice Flatpak or xdg-desktop-portal-gtk issue to create an bug report in the right place?

**Comment by haevalencia** [comment]
@AlexanderLyNL Maybe reopening this issue is a good idea to follow up on the problem.

I suggest to indicate on the Jasp download website the minimum version of Flatpak required to ensure all the expected functionality.

**Comment by JorisGoosen** [comment]
Well, if @4x1eg responds with the version of flatpak used (debian tends to be slow with updates) then we can see if that is in fact the issue.

On my pc the selection menu shows up fine, so it is probably an old issue that got fixed along the way in flatpak. And if that is the case we should definitely specify it on the downloads/flatpak instruction yeah.

**Comment by 4x1eg** [comment]
Sorry for the delay in my finding the flatpak ver. 
I looked in my Synaptic package management and it says: 
0.8.9-0+deb9u1

**Comment by JorisGoosen** [comment]
Ah, yeah that probably explains it then. Maybe you can install the newer version from stretch-backports?
(https://packages.debian.org/stretch-backports/flatpak) And then see if that solves the problem.

**Comment by haevalencia** [comment]
About the problem I describe above (not see flatpak applications) seems to be an issue of gtk desktop portal so I will open a report to debug the problem (doesn't affect all users).

**Comment by AlexanderLyNL** [comment]
This is fixed isn't? Please reopen if this problem resurfaces with the new flatpak version:

https://jasp-stats.org/linux-installation-guide/
