### ISSUE TITLE
unable to open file, Archive entry access failed

### ISSUE THREAD

**Issue by sincyc** [jasp-stats/jasp-desktop#2395]
## Template for bug reports

* JASP version:0.8.6.0
* OS name and version:Windows 10 (1709)
* Analysis: I tried to open jasp with administrator privileges, but still did not open the data
* Steps to reproduce: 

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by sincyc** [comment]
e.....
It has been resolved. The original is the need to delete the file personal information on it. Right-click the data file, properties, details, delete properties and personal information, you can successfully open the data file.

**Comment by AlexanderLyNL** [comment]
Thanks for the feedback. Please re-open if the problem re-occurs.
