### ISSUE TITLE
Bayesian linear regression error when adding interaction

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-desktop#2400]
* JASP version: 8.6
* OS name and version: Ubuntu 16.04
* Analysis: Bayesian linear regression
* Steps to reproduce: using the big5 data set, try to add any interaction term to the model. Results in the error:
"This analysis terminated unexpectedly.
Error in rawToChar(as.raw(out)): embedded nul in string: 'Agreeableness0x97Conscientiousness' "
I would add a jasp file, but see my other issue..

**Comment by vandenman** [comment]
I can replicate this on ubuntu, it appears to be an error on my part that appears to make including interaction effect not possible. In addition, it appears that the function `d64()` in common doesn't work as intended.
