### ISSUE TITLE
Correlation Matrix Plot: Problem with particular analysis

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-desktop#241]
For this particular data set we have r=1 and r=-1 I suspect that this creates some problems with the confidence intervals, which is why the analysis breaks down. I'll email you the data set. (The same issue will apply for the Bayesian version of this in where the Bayes factor goes to infinity, as we have discussed, Quintin)

![screen shot 2015-02-04 at 15 33 18 pm](https://cloud.githubusercontent.com/assets/10271675/6042231/47fa3f2c-ac83-11e4-86cd-41719332f01c.png)

**Comment by quentingronau** [comment]
I will try to figure it out, and yes, it would be great if you could mail me the data set.

**Comment by jonathon-love** [comment]
FYI @quentingronau, i've made some changes to correlation.R, so do a rebase before beginning work on correlations
