### ISSUE TITLE
jasp files

### ISSUE THREAD

**Issue by filescomputer** [jasp-stats/jasp-desktop#2410]
## Template for bug reports

* JASP version: 0.8.6
* OS name and version: windows 7
* Analysis: downloaded jasp, but it can't find any Excel files from my computer.
* Steps to reproduce: 

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by boutinb** [comment]
JASP can load CSV, ODS (Open Document Spreadsheet also supported by Excel) or SPSS file. It can't xls file directly.

**Comment by AlexanderLyNL** [comment]
The problem with opening xls files directly is its flexibility: colours, multiple tabs etc, which is why do not have full xls support. The workaround is to save your excel file as a csv or ods file. Hope that this helps.
