### ISSUE TITLE
Bayesian Linear Regression error

### ISSUE THREAD

**Issue by vankesteren** [jasp-stats/jasp-desktop#2414]
* JASP version: 0.8.6-debug
* OS name and version: Windows 10
* Analysis: Bayesian Linear Regression
* Steps to reproduce: 
    - Start Bayesian linear regression on the debug dataset
    - Add contCor1 to dependent
    - Add contCor2 as covariate
    - Add contNormal as covariate -> error!

`Error in BAS:::list2matrix.bas(object, 'mle.se'): incompatible types (from NULL to double) in matrix subset assignment`

(maybe this has to do with #2400?)

![image](https://user-images.githubusercontent.com/11596858/37391832-c3a6b454-276c-11e8-8a2c-1771742879b0.png)

**Comment by vandenman** [comment]
Did this happen on your development branch? I cannot replicate the problem on Ubuntu from the current development, nor from windows with the latest release. Perhaps you still have an old version of the BAS package. There was a pretty annoying bug in a previous version and this looks like a sideeffect of it.

**Comment by vankesteren** [comment]
It probably was this issue - hadn't updated my packages in a while. Sorry!
