### ISSUE TITLE
Bayesian Correlation Matrix: Matrix plot

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-desktop#242]
Jonathon could you add the plot option for the matrix plot in the Bayesian UI:

![screen shot 2015-02-04 at 15 39 11 pm](https://cloud.githubusercontent.com/assets/10271675/6042319/02043d6e-ac84-11e4-82d5-2b0cb17b2ac1.png)

**Comment by jonathon-love** [comment]
@EJWagenmakers 

what plot options do we need for the bayesian correlation matrix?

i'm invisaging:

    Plots ------------------
      [  ] Correlation Matrix
           [  ]  Densities
           [  ]  Posteriors

*Correlation Matrix* produces the plot, and enables the *Densities* and *Posteriors* options. Off by default.
*Densities* replaces the diagonal (normally marked with a dash) with the density plot. Off by default.
*Posteriors* replaces the lower left corner with posterior plots (normally blank). Off by default.

If only *Correlation Matrix* is checked and there are only two variables selected, then the scatter plot should fill the plot completely.

**Comment by EJWagenmakers** [comment]
This is all good, except for the names "densities" vs "posteriors". The
problem is is that the posterior distribution is itself a density. What you
really mean is that you will show a density (or a histogram?! or both?!) of
the raw *data*, and that the posterior is for the correlation coefficient.

To disambiguate, we might go for something like
[ ] data densities
[ ] posterior for \rho

Maybe we can do better than "data density", but it does seem clear what is
meant.

Cheers,
E.J.




********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by AlexanderLyNL** [comment]
It really depends on what we would like to convey with the matrix plot. If we would be consisted, we should then have posteriors instead of data densities on the diagonal, which brings us back to the purpose of the matrix plot — Is it exploratory? Or is it concerned with inference? 

Furthermore, if we add the posteriors for \rho in, we implicitly state that H_{1} holds true. Is this still exploratory? The same question can be said about the confidence intervals in the classical correlation matrix plot.

**Comment by EJWagenmakers** [comment]
So we have a matrix plot for classical and Bayesian analysis.
Both plots have the regression-line data in the top right panels; both
plots have inferential information in the bottom-left panels (r and CIs for
classical; posteriors for Bayesian). In both plots, the diagonal includes
the marginal distribution of the data. I think this is consistent and
sensible. It may not respect a strict separation between data visualization
and inference, but it is what users would want to be able to do. So I think
we are good here.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
what about:

    Plots ------------------
      [  ] Correlation Matrix
           [  ]  Variable densities
           [  ]  Posteriors

or

    Plots ------------------
      [  ] Correlation Matrix
           [  ]  Variable histograms
           [  ]  Posteriors

we refer to columns as variables.

    Plots ------------------
      [  ] Correlation Matrix
           [  ]  Histograms for variables
           [  ]  Posteriors

**Comment by EJWagenmakers** [comment]
I prefer the last option (also because it is least ambiguous and not the
opposite of a "fixed histogram"). But the histograms are shown, right --
not only the densities? Can you send a screenshot?
EJ

**Comment by AlexanderLyNL** [comment]
I definitely would like to to have a reference to the data in it. So instead of “Variable” change that into “Data”. Furthermore, I’m still not convinced that we should report posteriors as we then assume that H_{1} holds true.

Example: 

https://www.dropbox.com/s/rsqg0tswuq249o3/Presidents.eps?dl=0

Presidents, r=0.39, n=48
BF_{10} =6.33

and look at the picture below. 

https://www.dropbox.com/s/uv96wujhl5kwu9z/stulp2013PriorPosterior.eps?dl=0

While the posterior suggests that H_{0} should be discarded. Does a BF_{10} = 6.33 validate this suggestion? Aren’t we giving a wrong impression then? Isn’t it better just to give the r value? Rather than suggesting that one does not need to test anymore.

It is okay to plot the posterior of \rho if it were concentrated and peaked at zero when the data are generated from \rho=0, but this is not always the case.

**Comment by EJWagenmakers** [comment]
So we could instead have:

Plots ------------------
  [  ] Correlation Matrix
       [  ]  Histograms for data
       [  ]  Posteriors under H1

I do want people to be able to see the posteriors under H1, but they
should be aware that this is a valid summary only when H1 holds.

Cheers,

E.J.



********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by AlexanderLyNL** [comment]
I like that idea, as it is concerned with an estimate, should we then use the prior that such that \rho \propto (1- \rho^{2})^{-1}?

**Comment by EJWagenmakers** [comment]
Nope, because the priors Jeffreys proposed for testing are also perfectly
OK for estimation. Even if you disagree with that general claim, the
differences in the estimates will be so small that the discussion is purely
theoretical.
Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
i like `Densities for variables` rather than `Densities for data`, because data could be anything, where as the density plots *are* actually for each variable.

i'd also prefer to drop the `under H1` thing, because i think that's a technical detail that people won't be interested in; if the posterior is above the prior at 0, then that's evidence for the null, if it's below the prior at 0, then that's evidence for the alternative. technically, i see that this is different to the prior and posterior plots for the t-tests, but in practice it seems pretty much the same.

Havin said that: `Densities for data` is ambiguous, but only until the user clicks it, and then they'll know. `under H1` is only a little bit different, and once they click it they'll see it's the same as what they've seen before; so i think my suggestions are the best ones, but in both cases i don't really care, and if people feel strongly about them, i'm happy to do them that way.

Plots ------------------
  [  ] Correlation Matrix
       [  ]  Densities for variables
       [  ]  Posteriors

![_2](https://cloud.githubusercontent.com/assets/3240247/6098196/d010d126-afd7-11e4-9159-3bb457ca8cc1.png)

**Comment by EJWagenmakers** [comment]
OK. I don't care much either. I am fine with

Plots ------------------
[ ] Correlation Matrix
[ ] Densities for variables
[ ] Posteriors

But perhaps "Matrix" should read "matrix"?

Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by AlexanderLyNL** [comment]
I don’t agree, we should have H1 in it. 
> i'd also prefer to drop the under H1 thing, because i think that's a technical detail that people won't be interested in; if the posterior is above the prior at 0, then that's evidence for the null,if it's below the prior at 0, then that's evidence for the alternative. technically, i see that this is different to the prior and posterior plots for the t-tests, but in practice it seems pretty much the same.
> 
This implies that you’re doing posterior p-values, which is definitely not what should be done, you want to do Kruschke testing of course.

**Comment by jonathon-love** [comment]
sure. my guess is that most users either won't pick up that that is (arguably) implied, or are sophisticated enough to understand what's going on, but i'm happy to add it in. i don't suppose it matters either way.

**Comment by EJWagenmakers** [comment]
So the compromise is: variables instead of data, and leave in "under H1".
EJ

**Comment by jonathon-love** [comment]
it's true, you can think of it as a compromise, but i prefer not to think about it or phrase it in those terms.

it implies that our goal is to placate our team's internal wants, rather than do the best by our users.

**Comment by EJWagenmakers** [comment]
Sure, but these particular decisions are quite subtle. Let's go with an
option we can all live with, at least for now. I simply have no strong
preference and can see either argument.
EJ
