### ISSUE TITLE
"save as" only saves  plots as .png, but none of the other formats

### ISSUE THREAD

**Issue by euabela** [jasp-stats/jasp-desktop#2421]
Hi all - I can't save the "Descriptives plot " (e.g. from an 2 x 2 ANOVA) in any other formats than .png with transparent background. Same for the boxplots etc from the "Descriptives" tab. I'd like to use the 300dpi TIFF option... Thanks!

* JASP version: 0.8.6
* OS name and version: masOS Sierra 10.12.6
* Steps to reproduce: Try to save a descriptives plot via drop-down

**Comment by AlexanderLyNL** [comment]
Hi Euabela,

This will be fixed in the next issue. One work around for now is to refresh the analysis and then save the plot in your preferred format. Let me know whether this works.

Cheers,
Alexander

**Comment by euabela** [comment]
Thank you - that worked!

- Eugenio
On 11 Apr 2018, at 21:44, AlexanderLyNL <notifications@github.com> wrote:

Hi Euabela,

This will be fixed in the next issue. One work around for now is to refresh the analysis and then save the plot in your preferred format. Let me know whether this works.

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
Thanks for the feedback. Sorry for the inconvenience, but the bug will be fixed in a next issue.
