### ISSUE TITLE
BAS - Posterior summary table not updating?

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#2425]
## Template for bug reports
* JASP version: 8.6
* OS name and version: Mac 
* Analysis: Bayesian linear regression
* Steps to reproduce: 
With the big 5 personality dataset, load a model with Neuroticism as the DV, and Conscientiousness and Agreeableness as predictors. Then select show "Most complex model" (i.e., change from the default "Best model" to "Most complex model" after having added the covariates) - the posterior summary table does not include Agreeableness. However, when first selecting "Most complex model", and then adding all the predictors, we obtain the correct table. See attached screenshot for the incorrect behavior.
<img width="1410" alt="bas_bug" src="https://user-images.githubusercontent.com/8697436/37484276-5cd6f6e0-2888-11e8-9c01-6b1419fdb5d3.png">

Cheers,
Johnny and Quentin

**Comment by vandenman** [comment]
yeah that's a bad state bug on my part. In case you need this to work properly right now, this (and more) is fixed on [basUpdates](https://github.com/vandenman/jasp-desktop/tree/basUpdates).

**Comment by quentingronau** [comment]
Thanks!

**Comment by akashrajkn** [comment]
Fixed in #2462
