### ISSUE TITLE
Filtering whitelist can be circumvented by calling a function from it's namespace

### ISSUE THREAD

**Issue by vandenman** [jasp-stats/jasp-desktop#2427]
## Template for bug reports

* JASP version: Development
* OS name and version: Ubuntu 17.10
* Analysis: Filtering
* Steps to reproduce: Call a non whitelisted function from namespace to avoid the whitelist.

The filter code below works and definitely shouldn't!

```
base::setwd("~/")
grDevices::png("IshouldNotExist.png")
graphics::plot(stats::rnorm(100))
grDevices::dev.off()
os <- base::Sys.info()["sysname"]
ifelse(os == "Linux",
    base::system("xdg-open IshouldNotExist.png"),
    base::system("open IshouldNotExist.png")
)
genFilter <- rep(TRUE,100)
```

## Template for enhancement requests
 
* Enhancement: check for functions called from namespace.
* Purpose: prevent arbitrary code execution from within JASP.

**Comment by JorisGoosen** [comment]
Nice catch!
I changed the functionnameregex so that it considers :: to be part of functionnames and now it does recognize them.
