### ISSUE TITLE
Visual(?) Bug in ANOVA and linear regression

### ISSUE THREAD

**Issue by timdraws** [jasp-stats/jasp-desktop#2430]
Below are two images of linear regression and ANOVA; both with variables loaded that should, according to the indication on the bottom right of the window, not be suitable for that part of the analysis. So either there is a visual bug, or it should really not be possible to drag these types of variables in there. I didn't look at all analyses, this bug might appear elsewhere as well.

<img width="561" alt="screen shot 2018-03-20 at 14 30 41" src="https://user-images.githubusercontent.com/36475541/37659843-46c16b20-2c51-11e8-9e30-b847ab5f1906.png">

<img width="563" alt="screen shot 2018-03-20 at 14 30 55" src="https://user-images.githubusercontent.com/36475541/37659844-46e999ce-2c51-11e8-848d-a2e9cd8944be.png">

**Comment by akashrajkn** [comment]
This is not a bug. For many analyses, we have the following - **suggested** and **allowed**. Only suggested variable types are indicated on the bottom right.

**Comment by AlexanderLyNL** [comment]
Fix
