### ISSUE TITLE
NA as missing value by default

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2437]
Right now "NA" is not recognized as missing value by default: we only have NaN, ., and nan. Can we add NA to this list by default, so that users don't need to change the preferences? It is customary to have NA denote a missing value, particularly for R users. 
![na](https://user-images.githubusercontent.com/8603015/37826880-860b0fd4-2e95-11e8-884d-2a1c07482c92.png)

Cheers,
E.J.

**Comment by JohnnyDoorn** [comment]
It's in there by default - maybe you removed during a demonstration?

**Comment by FransMeerhoff** [comment]
The Reset button should get the defaults back again, including NA
