### ISSUE TITLE
Issues in assigning appropriate labels for 4 way RM ANOVA

### ISSUE THREAD

**Issue by mukeshmakwana** [jasp-stats/jasp-desktop#2440]
## Template for bug reports
 When performing RM ANOVA with more than 3 factors, the third factor labels gets replaced by the last factor labels and the labels for 4th factor on wards shows the default value of Level1, Level2 (does not accept the allotted names) 
0.8.1.1

* JASP version: 0.8.1.1
* OS name and version: Windows 7 Ultimate
* Analysis: Four way Repeated Measures ANOVA
* Steps to reproduce: 
Try to add, more that 3 factors and add minimum 2 levels in each factor. You will see the third factor labels gets replaced by the last factor labels and the labels for 4th factor shows the default value of Level1, Level2 (does not accept the allotted names) 
![rm_anova_label issue](https://user-images.githubusercontent.com/37741074/37864913-00a064dc-2f9b-11e8-8ec1-6d2f9a77b5e2.png)

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by AlexanderLyNL** [comment]
Hi M8999ak, 

Does this problem still occur in our newest version? If it does, can you please include the JASP file as a zip to this conversation?

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
This should be fixed in our newest version:

https://jasp-stats.org/download/

Please reopen if this is not the case.
