### ISSUE TITLE
lavaan ERROR: missing observed variables in dataset

### ISSUE THREAD

**Issue by gynt** [jasp-stats/jasp-desktop#2443]
## Template for bug reports

* JASP version: 0.8.6
* OS name and version: Windows 7
* Analysis: SEM using lavaan. Subcommand: lav_data_full
* Steps to reproduce: Use any dataset with variable names that include a '_'

I have a dataset that contains variables that include a '\_'.  
I can succesfully run a simple SEM if I only specify variables without a '\_', such as:  
 `abc =~ a + b + c`.  
The error output tells me that variables are missing in the dataset.  
What is striking, is that the Xbase64 string that it gives me, still contains the '\_'. I assume that this is the issue.

NOTE: all letters are blue in the model syntax box in JASP, except after the underscore, they turn black.

**Comment by vankesteren** [comment]
hi @gynt,

thanks for your feedback! we're currently working on improving the syntax parser for the SEM module. I'll definitely make sure that we check for this issue too!

**Comment by MAgojam** [comment]
Hi @vankesteren,
thanks if you want to solve problems using the SEM module with Jasp.
I am attaching screenshots  and zip with jasp file that raises the error "**lavaan ERROR**: missing observed variables in dataset".
A simple example of Mediation, which does not give problems if done with RStudio and the laavan package.

All my esteem and interest in the great work you are doing.
Maurizio
![screenshot_sem](https://user-images.githubusercontent.com/36552289/38194829-4ea07362-367a-11e8-8513-2b0c23a13598.png)
[Med_Mod_Lavan.zip](https://github.com/jasp-stats/jasp-desktop/files/1867978/Med_Mod_Lavan.zip)

**Comment by gynt** [comment]
hahaha, the default green and blue are horrendous ;)

I love these kind of updates you give!
