### ISSUE TITLE
Font in results window tiny, unreadable

### ISSUE THREAD

**Issue by milenra** [jasp-stats/jasp-desktop#2447]
As of 0.8.6, the font in the results window has become so small, it is almost unreadable on 1920 x 1080 resolution, making this version unusable. I downgraded to 0.8.5 and it's large enough there, just as it used to be on 0.8.4, which I upgraded from. Please provide a way to increase font size. 

JASP version: 0.8.6
Windows 7

**Comment by AlexanderLyNL** [comment]
Hi Milenra,

Thanks for the suggestion. Interestingly, there was an scaling issue with hdpi screens and 0.8.6 was supposed to fix this. The idea of changing the font size is natural. We hope to fix this up soon. 

Cheers,
Alexander

**Comment by boutinb** [comment]
@milenra Do you use high DPI Windows feature?

**Comment by AlexanderLyNL** [comment]
Hi milenra,

We fixed this. On windows, the result can be resized as follows:
- Increase size: ctrl + 
- Decrease size: ctrl -
- Back to default: ctrl =

On mac, the results are resized using cmd instead of ctrl. Please reopen this issue if this doesn't fix your problem. 

Cheers,
Alexander
