### ISSUE TITLE
Error when trying to run descriptive t-test

### ISSUE THREAD

**Issue by elisemessina** [jasp-stats/jasp-desktop#2449]
This analysis terminated unexpectedly.

Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : polygon edge not found

Stack trace
lapply(vps, push.vp, recording)

FUN(X[[i]], ...)

push.vp.vpTree(X[[i]], ...)

push.vp(vp$parent, recording)

push.vp.viewport(vp$parent, recording)

grid.Call.graphics(L_setviewport, vp, TRUE)

(function (x) 
{
    widthDetails(x)
})(list(label = 'MEMORY', x = 2, y = 0.5, just = 'centre', hjust = 0.5, vjust = -1, rot = 90, check.overlap = FALSE, name = 'GRID.text.30', gp = list(fontsize = 18, col = 'black', fontfamily = '', lineheight = 0.9, font = 1), vp = NULL))

widthDetails(x)

widthDetails.text(x)

grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, resolveHJust(x$just, x$hjust), resolveVJust(x$just, x$vjust), x$rot, 0)

**Recently downloaded JASP - (have both xQuartz and Javescripted downloaded)and when running my first analysis I was meet with the above error and don't know how to fix it?? I have tried deleting and redownloading already.

I am on a Mac Laptop running the newest software HighSierra**

**Comment by AlexanderLyNL** [comment]
Do other analyses work? Could you please send us the JASP file in a zip so we can have a look at it.

**Comment by boutinb** [comment]
Probably, you don't have the Arial font: open the Font Book and check whether the Arial fonts are enabled.

**Comment by AlexanderLyNL** [comment]
Here's a guide on how to install fonts. 

https://mac-fusion.com/how-to-install-fonts-into-font-book/

But before doing this, it's good to verify that this indeed the problem. You can find the font book in your Application folder.

**Comment by akashrajkn** [comment]
This could be due to broken fonts on the system (A simple check is Login to the guest account and check if the problem persists). Restoring the standard fonts should solve this error (check out this [stackoverflow thread](https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon/49653833#49653833)).

Open Fontbook -> File -> Restore standard Fonts.

Reopen the issue if the problem persists
