### ISSUE TITLE
Bug in Bayesian RM ANOVA

### ISSUE THREAD

**Issue by timdraws** [jasp-stats/jasp-desktop#2450]
When performing a Bayesian RM ANOVA (i.e., using the example data set 'Bugs'), everything works fine until I try to create a plot. The following error comes up:

<img width="1280" alt="screen shot 2018-03-30 at 14 49 00" src="https://user-images.githubusercontent.com/36475541/38138152-8551b428-3429-11e8-9307-70b805520277.png">

Here's the JASP file: https://www.dropbox.com/s/jddj44b2x1mg5k3/Bug%20RM%20ANOVA.jasp?dl=0

Edit: This problem doesn't seem to occur in JASP version 0.8.4.

**Comment by JohnnyDoorn** [comment]
This was fixed in PR #2439
