### ISSUE TITLE
Enhancement request - option to create new sum/mean variable during reliability analysis

### ISSUE THREAD

**Issue by juliebmorrison** [jasp-stats/jasp-desktop#2451]
I love how easy it is to run a Cronbach's alpha in JASP, particularly including reverse scoring. We always run these analyses before computing the summed or mean score for a measure. I didn't see a way to create a new variable in JASP.
 
* Enhancement: Create a new variable (sum or mean) during the reliability analysis process
* Purpose: To allow for analyses of measures once we know they are reliable

**Comment by EJWagenmakers** [comment]
The next version of JASP will have filtering of specific cases, and the version after that will allow users to create new columns with new variables. Would that address the issue?

**Comment by juliebmorrison** [comment]
Yes, that will work perfectly. You all are the best. Thank you!
