### ISSUE TITLE
Enhancement request - Descriptives Plots split on 2 or more variables

### ISSUE THREAD

**Issue by juliebmorrison** [jasp-stats/jasp-desktop#2452]
The boxplot feature under Descriptives is great, particularly the ability to select colored bars. However, I have some plots where I would like to split on 2 or more variables. 
 
* Enhancement: Allow data to be split on more than one variable in Descriptives Plots
* Purpose: More detailed graphs

**Comment by EJWagenmakers** [comment]
Ahh I see. Not sure how much work that is. @vankesteren?

**Comment by vankesteren** [comment]
This would indeed be very nice, but not a priority right now. In the future we will look into this again!

**Comment by juliebmorrison** [comment]
Thank you! I used JASP the other day to analyze the data from 5 student projects, and it worked great. I look forward to continued improvements in the program.

**Comment by markovendelin** [comment]
I wonder whether the future has arrived now and if this issue can be reopened. We frequently have a data that requires a split by two parameters and cannot really use descriptive stats for it
