### ISSUE TITLE
Scatterplot axes in Bayesian Correlations are not scaled well

### ISSUE THREAD

**Issue by Kucharssim** [jasp-stats/jasp-desktop#2461]
## Template for bug reports

* JASP version: 0.8.6.0
* OS name and version: Windows 10 Home, version 1709, OS Build 16299.309
* Analysis: Bayesian Correlation Pairs
* Steps to reproduce: Open the Adam Sandlers dataset and select Bayesian Correlation Pairs. Input the Year and Freshness as variables of interest and select Scatterplot. The plot clearly does not scale the axes well, making it hard to see how the data actually look like:

![adamsandlerbug](https://user-images.githubusercontent.com/7093546/38499543-39500142-3c08-11e8-8469-ac5cbe398c99.png)

The same bug is produced in the Bayesian correlation matrix. But with different variables/datasets, this have not occurred to me. Note that prior including Year in the analysis, I had to change the type of variable to continuous (JASP automatically recognized it as categorical) - maybe this induces some error?

[AdamSandler.zip](https://github.com/jasp-stats/jasp-desktop/files/1890023/AdamSandler.zip)

**Comment by EJWagenmakers** [comment]
This is an old scaling issue that we really ought to fix. @AlexanderLyNL I think we need to define the difference between min and max, and then offset using a proportion of the observed range or something.

**Comment by koenderks** [comment]
This will be solved in the next update!
![solved](https://user-images.githubusercontent.com/25059399/38556993-e0703974-3ccb-11e8-9481-e0ae89a4c444.png)
