### ISSUE TITLE
JASP build broken due to hardcoded jsoncpp path

### ISSUE THREAD

**Issue by markovendelin** [jasp-stats/jasp-desktop#2469]
Recent commit (2eaa958b57a1e65716731e13ff29dfe64f52e7a7) broke JASP compilation on Gentoo:

```
jsonredirect.h:10:31: fatal error: libjson/json/json.h: No such file or directory
```

I can see from the source, that you try to guess JSONCPP library location and flags. There is much easier and supported solution: using `PKGCONFIG` in your qmake file. See https://doc.qt.io/qt-5/qmake-project-files.html, under "Configuration Features". In this case, you would have to add

```
CONFIG += link_pkgconfig
PKGCONFIG += jsoncpp
```

into JASP-Common.pro and use `#include <json/json.h>` for inclusion of the file. [haven't had time to test it, but I would expect it to work]

**Comment by JohnnyDoorn** [comment]
Same here, on Arch

**Comment by JorisGoosen** [comment]
Hey @markovendelin that sounds like a good plan, we'll try it out

**Comment by markovendelin** [comment]
Great! Ping me if you run into trouble

**Comment by JorisGoosen** [comment]
Well we added it to development, it seems to work here on arch. Does it do the same on Gentoo?

**Comment by markovendelin** [comment]
It breaks now on different stage:

```
/usr/lib64/qt5/bin/rcc -name resources /home/markov/code/thirdparty/jasp-desktop/JASP-Desktop/resources/resources.qrc -o qrc_resources.cpp
RCC: Error in '/home/markov/code/thirdparty/jasp-desktop/JASP-Desktop/resources/resources.qrc': Cannot find file 'FilterConstructor/ColumnDrag.qml'
```

I am on development branch, with the last commit:

```
commit 5f18378b4c3b1fdef3eb3090835d74e5fd1ed8f0 (HEAD -> development, origin/development, origin/HEAD)
Author: AlexanderLyNL <a.ly@jasp-stats.org>
Date:   Thu Apr 19 11:11:07 2018 +0200

    Update jasp-building-guide.md
    
    Updated links to R3.4.4 repository instead of R.3.3.3 for Windows and mac.
```

You may want to setup some CI for the project to avoid these issues. See https://github.com/marketplace/category/continuous-integration for available services.

**Comment by JorisGoosen** [comment]
Well we have a Travis build check running but to set up more would be impractical.

Your error is caused because I forgot to merge the pullrequest  #2475 yesterday..
I just did so and now it should work. 

My apologies for the clumsiness there!

**Comment by markovendelin** [comment]
No problem :) 

Now it compiled nicely - we could close the issue.

Travis should be sufficient, but it looks to be not enforced on merge (aka you can merge with the broken build). If you look into travis build reports they are all in red, but reported on main page as all is fine. Its probably due to travis tracking some different branch.

**Comment by JorisGoosen** [comment]
Yeah Travis has some problems with some R-packages, so sadly enough it wouldn't be very practical to disable merge when Travis complains because then we wouldn't be able to merge anything :p

But that will be fixed at some point of course and at least this issue can be closed now :)
