### ISSUE TITLE
"Exact p-values" do not work for the t-test when p<.001 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2487]
https://twitter.com/nikegnanateja/status/988344409065275392

When "exact p-values" are set in the preference menu, the users wants exact p-values. This works for ANOVA, but for the t-test it fails for p-values smaller than .001. Attached is a screenshot. Send me an Email if you like the matching .jasp file

E.J.
![problemwithexactpvalues](https://user-images.githubusercontent.com/8603015/39121638-7ea19680-46f2-11e8-8727-1274ad5a5fb7.png)

**Comment by EJWagenmakers** [comment]
@vankesteren ?

**Comment by EJWagenmakers** [comment]
OK, more info: "I discovered that if you untick the preference, press OK, and then tick it again (and press OK) it does work (at least for ANOVA, and on my machine). Clearly a bug, but at least this should be a workaround."

**Comment by AlexanderLyNL** [comment]
Fixed by pull request #2629
