### ISSUE TITLE
Enhancement: Data manipulation (compute new variable, aggregate data, & restructure data)

### ISSUE THREAD

**Issue by tkahan** [jasp-stats/jasp-desktop#2495]
## Template for enhancement requests
 
* Enhancement: Add data manipulation to JASP (e.g., ability to compute new variable, aggregate data, restructure data).  In many experiments each participant may have hundreds of rows of data and computations are needed before a statistical analysis can be performed.  This may include creating new variables after a mathematical procedure (for example, computing log values of reaction times only when accuracy is correct), aggregating data in order to compute the mean per condition per participant (for example computing the mean of these log reaction time values), and transforming the data so each participant has one row of data.  These features (compute variables, aggregate data, and restructure data) are all currently available in SPSS.

* Purpose: Members of my lab will certainly use JASP for Bayesian Analyses.  However, if these features were added to JASP then SPSS would no longer have any value in my lab.

**Comment by EJWagenmakers** [comment]
Thanks for the suggestion. All of this is under development and will be implemented in the next two releases!
