### ISSUE TITLE
Plots (fonts) are not showing up properly. [Solved] Restore standard fonts. 

### ISSUE THREAD

**Issue by kurdupelek** [jasp-stats/jasp-desktop#2496]
## Template for bug reports

* JASP version: 0.8.6
* OS name and version: macOS High Sierra Version 10.13.4
* Analysis: Bayesian Independent Samples T-test
* Steps to reproduce: Anytime I run a Bayesian Independent Samples T-Test (regardless of the data set used), the plots do not display properly. I have attached examples using the Tooth Growth data set that came with JASP, although the error was first discovered using my own data set. I have checked my font book to make sure that is not the problem.
The Descriptives Plot always remains empty, so no screen shot is necessary.
The Inferential Plots show rectangles instead of numbers:
<img width="504" alt="screen shot 2018-04-28 at 5 05 39 pm" src="https://user-images.githubusercontent.com/38819253/39400864-9d2a4472-4b06-11e8-8195-29ac1427b3f6.png">
<img width="454" alt="screen shot 2018-04-28 at 5 06 23 pm" src="https://user-images.githubusercontent.com/38819253/39400866-9d3f79b4-4b06-11e8-93c6-ebace1f8afa3.png">
<img width="463" alt="screen shot 2018-04-28 at 5 06 36 pm" src="https://user-images.githubusercontent.com/38819253/39400867-9d5009dc-4b06-11e8-9779-32c02901fee0.png">
Thank you very much for your assistance.

**Comment by EJWagenmakers** [comment]
Thanks for reporting this -- I haven't seen this one before!
E.J.

**Comment by kaimikael** [comment]
I'm getting the same.
Jasp 0.8.6
macOS High Sierra 10.13.5
Analysis: Correlation matrix
No numbers on the plot axes.

<img width="563" alt="screen shot 2018-06-18 at 14 35 14" src="https://user-images.githubusercontent.com/10616212/41536157-12f339ea-7305-11e8-92ff-682f9b28dd02.png">

**Comment by kurdupelek** [comment]
I never followed up with sharing the .jasp file. I did a good old reboot prior to the original posting and kept getting the same thing. I rebooted my computer one more time after I posted and haven't had the problem since. I know that may not be helpful, but having to reboot twice to get it working is a little odd but worked nonetheless.

**Comment by kaimikael** [comment]
Aha, resetting the fonts did the trick, thanks!

**Comment by AlexanderLyNL** [comment]
Awesome stuff, thanks for reporting this and glad that this works out. This is very valuable. I'll edit the title so we it's clear what the solution is. Please reopen if the problem reoccurs.
