### ISSUE TITLE
B Correlation Matrix: needs a couple of tweaks

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#250]
Just a few small things to make this consistent with the classical correlation

1. The table heading can just be `Pearson Correlations`. The fact that these are BFs is listed in the table itself. It also caters to the situation where the user has `Report Bayes Factors` turned off (like in the screenshot) and there are no BFs in the table.
2. We handle missing values automatically, usually be excluding them (Incidentally, we don't refer to missing values as NAs, because people don't know what they are)
3. Also worth taking a look at the error list, and trying to make error messages consistent with that (something to consider; in this case you're reporting that the standard deviation is undefined, but the user might think "but i've not requested the standard deviation")

![screen shot 2015-02-05 at 12 17 23 pm](https://cloud.githubusercontent.com/assets/3240247/6059374/0ca05b2e-ad31-11e4-9aa0-c4a78ba28d45.png)

**Comment by AlexanderLyNL** [comment]
1. Sure, then I’ll make it into “Bayesian Pearson Correlations”. Actually it’s very non-Bayesian to report a point. Instead, it would make much more sense to report a posterior. 
2. It makes sense to tell the user that there’s an NA in it. The user knowns that it can be solved by pressing the button that tells them to exclude NAs
3. Which error list? I’ll change it into “Sample correlation r is undefined - …. ” then.

**Comment by jonathon-love** [comment]
2. yeah, we normally exclude either analysis by analysis, or listwise. we don't normally have the option "throw an error". i can add some radio buttons in for "analysis by analysis" or "listwise" if you want to implement these, or you can leave it and just do it "analysis by analysis" (which is what the classical correlation does)
3. you'll find the error list in the documentation: https://github.com/jasp-stats/jasp-desktop
