### ISSUE TITLE
Can't Perform a Binary logistics regression

### ISSUE THREAD

**Issue by Newstats** [jasp-stats/jasp-desktop#2506]
## Template for bug reports.  
I can not perform a binary logistics regression in Windows. 64bit I've watched JASP videos were it worked correctly but not on my download. downloaded uninstalled several times.  When I try and perform the regression it allows me to transfer to items to _Covariates_ but the button won't work for me to add the Dependent Variable. I've tried dropping and like the video and I get a red circle with a diagonal line through it. Can you tell me if there is something else I need to download to get this to work like it does on the video? It says when I downloaded it that it was a new release which seems like the old version because I can see on the video it actually works there.  I can't find any other versions to download or any extention packs.  Please help me I have homework I'm using this on.  Thank you.

* JASP version:
* OS name and version:
* Analysis:
* Steps to reproduce: 

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by akashrajkn** [comment]
For covariates, you can add variables of type *Scale*.

**Comment by vankesteren** [comment]
![image](https://user-images.githubusercontent.com/11596858/39802750-2664afaa-536f-11e8-8b01-21e4197a714b.png)

For the dependent variable, make sure it is set to categorical or ordinal, too! `You can do this by clicking on the variable type indicator ![image](https://user-images.githubusercontent.com/11596858/39802781-51db7c86-536f-11e8-9385-65de3067d09b.png) ![image](https://user-images.githubusercontent.com/11596858/39802793-59dc714c-536f-11e8-85d2-fa40243b897d.png) ![image](https://user-images.githubusercontent.com/11596858/39802820-6d1ffb3e-536f-11e8-891d-d76fd044e3e3.png) next to the variable name.

I hope this solves your issue!

**Comment by AlexanderLyNL** [comment]
I think that this is solved, if not please reopen.
