### ISSUE TITLE
Copy-pasting notes include backslashes

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-desktop#2511]
If I add a note to an analysis and copy-paste it elsewhere, it include backslashes. So this:

    We conducted a Repeated Measures ANOVA... bla bla... F(1, 46) = 11.803, p < 0.001) and some special charaters #(/¤)(%#"

copy-pastes as this:

    We conducted a Repeated Measures ANOVA\.\.\. bla bla\.\.\. F\(1, 46\) = 11\.803, p < 0\.001\) and some special charaters \#\(/¤\)\(%\#"

JASP 8.5.1, Ubuntu 16.04.

**Comment by akashrajkn** [comment]
@lindeloev this is by design. The text is copied as Markdown.

**Comment by lindeloev** [comment]
OK, this may be slightly confusing to the novice, so an option to copy it for Word could be useful (and perhaps default). But since this is not a bug, I'll close this issue. Thanks for explaining!
