### ISSUE TITLE
Internal error ""

### ISSUE THREAD

**Issue by BryanBurnham** [jasp-stats/jasp-desktop#2518]
* JASP version: 0.8.6.0
* OS name and version: Windows 10
* Analysis: Independent Groups t-Test
* Steps to reproduce: Created data file from the attached .txt file, tried to begin running a t-Test, but an Error window keeps appearing saying there is an internal error with "" as the only message on the error.

[Red Study Replication Project Data .txt](https://github.com/jasp-stats/jasp-desktop/files/1988005/Red.Study.Replication.Project.Data.txt)

**Comment by akashrajkn** [comment]
@BryanBurnham  can you try installing the pre-installed version for windows? It is available on the [downloads page](https://jasp-stats.org/download/):

**Comment by boutinb** [comment]
We have made a new version (0.9). The installation on Windows is slightly different. Maybe this solves your problem. Could you try it?

**Comment by AlexanderLyNL** [comment]
This should have been fixed in 0.9.1. If not please reopen.
