### ISSUE TITLE
Proposed changes to Bayesian and Classical Menus

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#252]
### background

at the moment, we have our classical and bayesian analyses separated into two mirroring halves;

we have t-tests, anovas, etc. at the left side, and then we have bayesian equivalents available from the right hand side.

### the problem

this arrangement has a few issues

#### for new users

from a new users perspective, if they are wanting to do a bayesian t-test, they perform a quick visual search and find the t-test, and without noticing that it is in the "classical box" they click that by mistake.

from krug:

"When we're designing [UIs], we tend to assume that users will scan the page, consider all the available options, and choose the best one. In reality, though, most of the time we don't choose the best option - we choose the first *reasonable* option"

this issue is, in itself not a total deal-breaker. new users *will* make mistakes, and *will* need instruction, but it does motivate the search for a more optimal solution.

#### for experienced users

from an experienced users perspective, this separation resists *automatization*.

as we become familiar with a piece of software, we begin to use it without even thinking; we make keystrokes, execute commands, do things without a moments thought. this is great, and in many respects the goal of software; to make things so automatic that people only need think about their goals, and not about how they're doing it.

i find that i regularly select the classical t-test, or the classical ANOVA when i mean to run a bayesian t-test, or a bayesian ANOVA. the goal seeking automatic processes latch onto the first "t-test", or "ANOVA" that they see. given that we typically scan left-to-right, i usually select the classical ones.

next i begin dragging and dropping variables (all automatic), and at some point i make the realisation that i'm looking at what i'm not expecting to be looking at. this realisation is always surprising "oh! have i really run a classical ANOVA again?"

this doesn't seem to be something you can learn either. i have run each of these analyses tens of thousands of times, but i still semi-regularly make these mistakes. other people have reported experiencing the same thing.

the way you compensate is by concentrating. you have to "perform an act of cognitive control" to prevent this mistake from occuring; but if your concentration lapses, or you're distracted, you'll end up making the mistake again.

#### hypothesis

my hypothesis (in part) as to why this occurs, is that automatic processes are goal focused, and the order is:

1. "i want to compare two means"
2. "i want a t-test"
3. "i want a bayesian one"

and not:

1. "i want to compare two means"
2. "i want a bayesian test"
3. "i want a bayesian t-test"

#### proposed solution

to combine the classical and bayesian menus into a single menu for each category of test.

![screen shot 2015-02-05 at 1 44 52 pm](https://cloud.githubusercontent.com/assets/3240247/6060452/68bf544e-ad3d-11e4-8ed4-644381b17fbf.png)

this aligns with the predicted order of automatic thought outlined above. although it is possible that the user will similarly select the first t-test (the classical one) when they are meaning to select the bayesian one, (because it is the first thing they see, assuming people scan left-to-right, top-to-bottom), i don't think this will happen because of the close proximity of the Bayesian items to the classical ones. the bayesian items will still fall within the users 'search spotlight'.

this also has the added advantage that, where appropriate, bayesian and classical analyses can be combined into the one analysis. there are places where it would be nice to provide bayes factors and p-values side-by-side; i.e. in a correlation table, but the existing separation between classical and bayesian has prevented us from doing this.

#### possible objections

last time i floated this idea, there were two objections. one was that it signals that the bayesian analyses are "alternative", and less legitimate. but i think bayesian stats are well enough known that i don't think this is really a problem.

the other objection i will not attempt to describe because i never really understood it; it is some sort of aesthetic issue (which doesn't mean it isn't real; i recently objected to using "Finish" buttons rather than "OK", this is also an aesthetic issue which i don't expect outsiders to understand) so i'll leave that for @EJWagenmakers to explain.

**Comment by EJWagenmakers** [comment]
I am not sure about this one. Why don't we ask the users? Perhaps we can
have Shane's students look into this. It is important enough to consider
very carefully before we change things.

Actually, I dislike the way the proposed solution gives long menus; also,
this way of doing things hides the symmetry between the Bayesian and the
classical analyses. Finally, I suspect this solution will become
increasingly problematic as we start adding more analyses.

As an alternative solution, we could add a special menu button on top that
toggles the menu settings; either as we have it now, or only the classical
stuff, or only the Bayesian stuff. This might be handy for teaching and
prevent the confusion you describe without resulting in long menus.

Cheers,
EJ

**Comment by jonathon-love** [comment]
> Why don't we ask the users?

because they typically don't know or think about things like automaticity, etc.

> Perhaps we can have Shane's students look into this.

yeah, tricky one. i think to answer this beyond our own intuitions would require a lot of testing; we need people using it a fair bit to achieve the automaticity; which is more than a simple UI study generally gives you.

> Actually, I dislike the way the proposed solution gives long menus

Long menus are only really problematic when the user has difficulty parsing the list. In our case, the list is almost the same list replicated twice, which makes parsing it very easy. Further, a menu with 12 or 16 items is pretty common in software, so i think we'll remain within normal/useable limits.

> this way of doing things hides the symmetry between the Bayesian and the classical analyses

it would appear to me that the symmetry here:

![68bf544e-ad3d-11e4-8ed4-644381b17fbf](https://cloud.githubusercontent.com/assets/3240247/6126093/3266830c-b11d-11e4-8839-88ff9785f432.png)

is as apparent as here:

![screen shot 2015-02-10 at 11 59 33 am](https://cloud.githubusercontent.com/assets/3240247/6126102/46a73276-b11d-11e4-8d17-1175af9ead72.png)

> I suspect this solution will become increasingly problematic as we start adding more analyses.

so one of our goals is to only provide the most common analyses in the "Common" tab (so we don't end up like SPSS). once we start adding less common analyses, we'll put these in a different tab; so i don't think this will be a problem.

> As an alternative solution, we could add a special menu button on top that toggles the menu settings; either as we have it now, or only the classical stuff, or only the Bayesian stuff.

i don't think this solves the original problem; you're still making the person choose Bayesian or classical first (which is error prone), *then* the analysis. this is basically what we have now, with some non-standard stuff bolted on top.

**Comment by EJWagenmakers** [comment]
Let's postpone this until later.
I like the present look better but perhaps it's a matter of taste.
I also think the menu button is nice for teaching but we are leave that for
later discussion as well.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment]
I do accept the general argument, people think of the test first and the
statistical paradigm later. It is just that I find the current layout
visually more appealing and impressive.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
yeah, i get that. familiarity has led me to like it as well, and i am genuinely reluctant to change.

**Comment by jonathon-love** [comment]
i'm going to activate the combined classical and bayesian menus in-house just to see how it goes. trivial to change back.

**Comment by EJWagenmakers** [comment]
Nooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
*chuckles*

**Comment by jonathon-love** [comment]
it's funny how attached you can get to a particular aesthetic, and then how strongly you can feel about it.

**Comment by jonathon-love** [comment]
hey @raviselker, @Tahiraj, @quentingronau, @mmarsman1, @AlexanderLyNL, @doramatzke

EJ and i have been discussing some potential changes to the menus in JASP (in this email, there should be a link which says "view this discussion on github" or some such, if you click that, it will bring up the whole discussion, the rationale etc.).

I've temporarily rolled these changes out (you'll get them if you do a rebase) (but i'm planning to revert these changes for the 0.6). play around with it and get a feel for it. Change is always a bit jarring at first, so i'd recommend giving it a few days before deciding. I certainly need more time to make up my mind.

cheers

**Comment by raviselker** [comment]
I think there is not enough emphasis on the Bayesian analysis in the new menu structure. People will click on ANOVA, after which they can choose for ANOVA or Bayesian ANOVA. The old menu structure made it very clear that there is an old way of doing it (classical) and a new way (Bayesian). Now, it seems as though there is a default way of doing it (classical) and an advanced way of doing it (Bayesian).

**Comment by jonathon-love** [comment]
> The old menu structure made it very clear that there is an old way of doing it

my hunch is that the separate menu structure isn't actually that clear for a lot of people - atleast not for a while - especially if you don't explain the separate bayesian/classical thing.

**Comment by EJWagenmakers** [comment]
Hi @Tahiraj <https://github.com/Tahiraj>, @quentingronau
<https://github.com/quentingronau>, @mmarsman1
<https://github.com/mmarsman1>, @AlexanderLyNL
<https://github.com/AlexanderLyNL>,@doramatzke
<https://github.com/doramatzke>

This issue is dear to my heart. Can you weigh in please?
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
i feel like the question here is a little ill-defined.

is the question:
 1. which looks better?
 2. which provides a better user experience?
 3. which is better for new users?
 4. which does one simply prefer?

2 and 3 i'm continuing to research, so this may be a little premature.

**Comment by raviselker** [comment]
or:
5. which is better suited to promote using Bayesian methods

**Comment by EJWagenmakers** [comment]
indeed :-)

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by doramatzke** [comment]
Sorry, it looks like  I junked this email. I prefer the new menu structure: the menu ribbon is less cluttered and it places emphasis on the statistical model as opposed to the inferential framework.

Gr,
d
