### ISSUE TITLE
Repeated measures ANOVA - Simple contrasts incorrect? 

### ISSUE THREAD

**Issue by kcsa** [jasp-stats/jasp-desktop#2521]
## Potential Bug: Repeated measures ANOVA - Simple contrasts incorrect? 
* JASP version: 0.8.6 (MacOS)
* OS name and version: Mac OS X El Capitan (10.11.6)
* Analysis: Repeated Measures ANOVA with Simple Contrasts
* Steps to reproduce: Data and syntax are attached as a .jasp file (in a .zip)

Hello, 
I recently tried out JASP for performing a repeated measures ANOVAs with Simple Contrasts. I think that the Simple Contrasts are being calculated incorrectly. 

To demonstrate why I think the contrasts are being calculated incorrectly, I made up some data and attached it.

In this data file, I made a matrix with three variables (A, B, and C). Variables A and B are not significantly different from each other, while C has much higher values. The post-hoc t-tests show that this is the case.

However, when running this as simple contrasts, (A vs B; A vs C), both contrasts are significant (p <.001). This shouldn't be the case (A vs B should be non-significant). I've also attached a screenshot of output for running a similar Simple Contrasts routine in SPSS for comparison. 

Sorry if I'm missing something obvious / misunderstanding the intended analysis.

Thank you!

Download JASP file here: 
[TestContrasts.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/1993211/TestContrasts.jasp.zip)

<img width="1337" alt="screenshot_jasp" src="https://user-images.githubusercontent.com/5225365/39894143-8843d1fe-546b-11e8-873e-58825fdc9c1d.png">

<img width="738" alt="screenshot_spss" src="https://user-images.githubusercontent.com/5225365/39894144-88503db8-546b-11e8-85c4-df6b5f5457af.png">

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by AlexanderLyNL** [comment]
Hi Kirsten 

Thanks for reporting this! @JohnnyDoorn  and @Kucharssim can you add this to the list and look into this?

Cheers,
Alexander
