### ISSUE TITLE
when the new version can be released

### ISSUE THREAD

**Issue by psyqf0719** [jasp-stats/jasp-desktop#2522]
for some specical reason,my windows can not install the 0.8.6 version,and alway warning  there are some virus.anyway,i wonder when the new version release and try again

**Comment by AlexanderLyNL** [comment]
Dear psyqf0719,

The new release is on its way and will be out soon. Can you tell us what kind of message you get? Furthermore, does the pre-installed zipped version work for you?

https://jasp-stats.org/download/

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
Today 

https://jasp-stats.org/2018/10/11/announcing-jasp-version-0-9-1-now-with-compute-columns/

Please let me know how this works out for you. Please reopen if the problem resurfaces.
