### ISSUE TITLE
Error while running Bayesian RM ANOVA

### ISSUE THREAD

**Issue by kevinvschie** [jasp-stats/jasp-desktop#2523]
## Template for bug reports

This analysis terminated unexpectedly.

Error in if (usePooledSE) {: argument is of length zero

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.rmAnovaDescriptivesPlot(descriptivesDataset, options, perform, status, stateDescriptivesPlot = NULL)

.summarySEwithin(as.data.frame(dataset), measurevar = 'dependent', betweenvars = .v(betweenSubjectFactors), withinvars = .v(repeatedMeasuresFactors), idvar = 'subject', conf.interval = options$confidenceIntervalInterval, na.rm = TRUE, .drop = FALSE, errorBarType = options$errorBarType, usePooledSE = options$usePooledStandErrorCI)

.summarySE(data, measurevar, groupvars = c(betweenvars, withinvars), na.rm = na.rm, conf.interval = conf.interval, .drop = .drop, errorBarType = errorBarType, usePooledSE = usePooledSE)

* JASP version: 0.8.6.0
* OS name and version: Windows 7 Enterprise
* Analysis: Bayesian RM ANOVA
* Steps to reproduce:

**Comment by markovendelin** [comment]
Same here, on Linux using flatpack. It seems that its introduced with PooledSE for regular repeated ANOVA plots. The corresponding options are missing for the Bayesian RM ANOVA and analysis fails due to that

**Comment by AlexanderLyNL** [comment]
Fixed by issue #2505
