### ISSUE TITLE
wrong label / count of boxplots outliers

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-desktop#2537]
Version 0.8.6 (flatpak)
Built on: Mar 22 2018 14:47:07 (Netherlands)
OS name and version: openSUSE Tumbleweed, Linux kernel 4.16.8-1 64bit, KDE
* Analysis: Boxplot outlier labels usually show the right ID/row of the case where they occured. But if there are NaN or other ignored values and the ID lies beneath one of those "data-gaps" the number is to low. The gaps are just not counted, thus the number points to a lower ID/row
* Steps to reproduce: produce a boxplot with the attached edited example data set. Case 2 has no value at all while case 23 has a NA value. Only with the NA value the outlier label count is wrong. It should be 24 and not 23, see screenshot
[thomas.zip](https://github.com/jasp-stats/jasp-desktop/files/2012043/thomas.zip)

enhancement requests
 
* Enhancement: make JASP also count NaN values to label outliers
* Purpose: better identify / find the correct outliers

**Comment by JorisGoosen** [comment]
This is fixed, also takes into account filtered rows (filtering is possible in the next version!)
