### ISSUE TITLE
Bayesian ANOVAs: Proposed changes to default model building

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#254]
@EJWagenmakers 

So at the moment when a person assigns fixed factors, random factors and covariates, by default they are all *not* nuisance, and the model is full factoral.

This can produce massive model lists (120 models in the case of 5 factors i think).

To ameliorate this, @mmarsman1 and I propose:

1. random factors are nuisance by default
2. interactions with covariates are not included in the model by default

The user can still change this in the model builder

I think we may have decided on something similar in the past, but it got lost in time (possibly my fault)

**Comment by jonathon-love** [comment]
@EJWagenmakers?

**Comment by EJWagenmakers** [comment]
Agreed
EJ

**Comment by jonathon-love** [comment]
wait, you agree to the proposal? or that it's my fault?

**Comment by mmarsman1** [comment]
Both, I think :)
On 09 Feb 2015, at 12:08, Jonathon Love <notifications@github.com<mailto:notifications@github.com>> wrote:


wait, you agree to the proposal? or that it's my fault?

**Comment by EJWagenmakers** [comment]
Haha. Agreed to the proposal! :-)
EJ

**Comment by jonathon-love** [comment]
should interactions with random factors be excluded by default as well?

**Comment by mmarsman1** [comment]
Im not sure about the general public, but I would :)

Verzonden van mijn HTC

----- Reply message -----
Van: "Jonathon Love" <notifications@github.com>
Aan: "jasp-stats/jasp-desktop" <jasp-desktop@noreply.github.com>
CC: "Marsman, Maarten" <M.Marsman@uva.nl>
Onderwerp: [jasp-desktop] Bayesian ANOVAs: Proposed changes to default model building (#254)
Datum: za, feb. 14, 2015 17:12


should interactions with random factors be excluded by default as well?
