### ISSUE TITLE
Does EJ love Bayes bug in Bayesian correlation

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2541]
Take the file DoesEJLoveBayes.csv (on the OSF, in the "generic JASP workshop" folder available at https://osf.io/r73y9/ under the "Correlation" subfolder). The data are weird (on purpose, see scatter plot). The analysis works just fine, but what does not work is the sequential analysis; it gives an error message saying "plotting not possible" and something else. Now I've created this data set by drawing, so it may be that for the initial 5 points or so, the BF is in fact close to infinity. Perhaps that is the problem, but then it seems that a more informative error message in needed. @AlexanderLyNL ?

![plottingnotpossible](https://user-images.githubusercontent.com/8603015/40183836-136a90c8-59ef-11e8-90f2-7b8d932f9dae.png)

**Comment by AlexanderLyNL** [comment]
Will be fixed by the Bayesian correlation and t-test revamp.

**Comment by AlexanderLyNL** [comment]
Fixed by pull request #2630
