### ISSUE TITLE
no numbers on distribution plot y-axis

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-desktop#2546]
Version 0.8.6 (flatpak)
Built on: Mar 22 2018 14:47:07 (Netherlands)
OS name and version: openSUSE Tumbleweed, Linux kernel 4.16.8-1 64bit, KDE
* Analysis: descriptive statistics distribution plots do not show any numbers on the y-axis if the data is set continuous. My first semester students tell me this makes the graph harder to read. I tend to agree despite the fact that the emphasis of the shown y-axis seem to be on the density, which is useful but hard to read / interpret if the bin size varies.
* Steps to reproduce: open the example file below. no numbers are shown on the histograms y-axis

enhancement requests
 
* Enhancement: offer options to show absolute and relative numbers on the y-axis and tick them on by default. Only untick them if the bin size varies, however currently there seems to be no option to controll the bin size, so this last point is moot at the moment.
* Purpose: more information; beginners say its important for them

[example.zip](https://github.com/jasp-stats/jasp-desktop/files/2014115/example.zip)

**Comment by AlexanderLyNL** [comment]
@EJWagenmakers what would you like on the y-axis?

**Comment by EJWagenmakers** [comment]
Well, it is a density, so the units on the y-axis don't add much information. People easily misinterpret the numbers as probabilities. [If anything, I'd like to offer the opportunity to change the number of bins.] So I remain to be convinced...

**Comment by tomtomme** [comment]
you could show absolute numbers / counts instead. no need for a density except in the case of varying bin size

**Comment by AlexanderLyNL** [comment]
I don't know what to put on the y-axis, but the only thing I can come up is quite technical. Out of curiosity, would you be able to explain to students: the Radon-Nikodym derivative of the measure with respect to the Lebesgue measure?

**Comment by EJWagenmakers** [comment]
We'll discuss this in the team. It is a relevant complaint because students are generally confused. The question is whether the numbers will increase or decrease the confusion. Perhaps we can make the numbers optional. We'll take this under consideration.

**Comment by EJWagenmakers** [comment]
@vankesteren , any thoughts?

**Comment by AlexanderLyNL** [comment]
To clarify, I'm not against having units on the y-axis, I just don't know what it should be, other than something very technical, and how this should be explained to students. It wasn't meant to offend.

**Comment by tomtomme** [comment]
Thanks @AlexanderLyNL and others for having this discussion. I´ll try my best to explain my (and my students) point of view. 
Before, I think there might be some misunderstanding in the room that we have to clear up before we can reach further. Above you wrote "how would you explain to students the Radon-Nikodym derivative of the measure with respect to the Lebesgue measure?" 
I never heard those names, so I did a quick search. As I am not a mathematician that did not help much. Are those terms practically relevant for a simple histogram? My understanding of a histogram is, that it can display absolute or relative counts, same as a bar graph. The difference is that a bar graph is usually representing discrete data better and a histogram is better at displaying the characteristics of continuious data. The area of a histogram is also good at displaying the density. However this is only really useful if the bars width is differing, e.g. when there are varying bin sizes. Then we re-compute the height of the bars by dividing the count (absolute or relative) through the bin width. However thats a special case and it is not possible to change bin size (or number) in JASP at the moment. Going forward it would be nice to display / compute the density only in that special case and show absolute numbers or percentages in all other cases.
As I am not an english native speaker I hope it is clear what I am saying?

The point of my confused "medical controlling" students was, that seeing nothing on the axis was very unusual. They would have felt more comfortable if there was at least something, even something where I would have said "to complicated to explain". Then they could ignore it. They had dificulties seeing the naked axis. Maybe it would also be an option to not show the axis at all. When I paint normal plots for example I never paint a y-axis.

**Comment by vankesteren** [comment]
I have a few thoughts on this:

1. I think we should have a y-axis
2. Indeed, density is a very difficult concept and it is slightly arbitrary in the case of a kernel density estimate (KDE) plot (continuous line) because the bandwith of the KDE in part determines this. 
3. The discretisation of a continuous variable leads it to have a defined and easily interpretable y-axis: the height indicates the count of observations that fall in this category. 

![image](https://user-images.githubusercontent.com/11596858/41029094-198f3666-697b-11e8-8e3a-f963bbc9d575.png)


Technically, therefore, the distribution plot has 2 y-axes: density (for the KDE) and count. 

Perhaps we can add the KDE only as an option, and then make the axis unspecified only if we select this option; else we show counts on the y axis?

**Comment by EJWagenmakers** [comment]
Good idea Erik-Jan, let's do it like this
E.J

**Comment by tomtomme** [comment]
I feel the same :)
We could even show 2 y-axis at the same time with count on the left and KDE on the right side of the plot. Probably not as default though but as an option. If this is hard to implement, don´t mind - it would be just the cherry on the cake.

**Comment by vankesteren** [comment]
I'll see if I can fix this today

**Comment by AlexanderLyNL** [comment]
@koenderks also has something for this, perhaps you can combine your efforts.

**Comment by vankesteren** [comment]
I will also fix http://forum.cogsci.nl/index.php?p=/discussion/4260/possible-bug-on-descriptive-statistics-plot-jasp-0-9-2& at the same time

**Comment by AlexanderLyNL** [comment]
Fixed in 0.9.1.
