### ISSUE TITLE
B 1S T-Test: results change as the analysis progresses (!)

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#255]
using ssgo-fred.csv

with the following analysis, it at first produces a BF-0 of 1.361e+91, then when the plot appears, this value changes to 1.360e+91

![screen shot 2015-02-05 at 8 08 35 pm](https://cloud.githubusercontent.com/assets/3240247/6067164/c8966b52-ad72-11e4-90bd-c083bce1a004.png)

**Comment by jonathon-love** [comment]
also, if you use a minus sign rather than a dash in the scientific notation for the BFs above, they would nicely align.

**Comment by jonathon-love** [comment]
also, the y-axis scaling in that plot seems sub-optimal. not bad, just not optimal.

**Comment by quentingronau** [comment]
Concerning the changing values: To be honest, I'm a little bit puzzled. It seems that if the result is returned via callback the value is not rounded correctly. I printed every intermediate BF (before and after every callback) and they all are identical up to 6 decimal places. I saw that the rounding appears to happen elsewhere. Could you maybe tell me which file contains the rounding procedure for the JASP output? But of course it's peculiar that this is only a problem for the left-sided one-sample t test. But in the absence of better ideas, maybe I can find a hint what's wrong with my code there.

**Comment by jonathon-love** [comment]
you are completely right. may bad.
