### ISSUE TITLE
Cant change panel size

### ISSUE THREAD

**Issue by Maland18** [jasp-stats/jasp-desktop#2562]
## Template for bug reports

* JASP version:0.8.6
* OS name and version: macOS High Sierra10.13.4
* Analysis: general
* Steps to reproduce: --

## Template for enhancement requests
 
* Enhancement: Can't adjust the size of different windows (output window and analysis window) by dragging the border with mouse to left or right. Would be handy when having output tables that include a lot of columns. Thanks :)
* Purpose: Improve visibility of output

**Comment by FransMeerhoff** [comment]
Hi @Maland18 

Thanks for reporting this. A good point where we are working on (besides a lot of other things of course :-). The size of the output window can already be changed by dragging the border. Analyses windows will be rewritten to a different format which make the resizing easier too.
We made an improvement in the next version JASP 0.9 to zoom in and out in the result window (on Mac by Cmd+,Cmd-,Cmd=). We are in the the Beta phase with this version and the release will become very soon. Other improvements on this issue are placed on our backlog .

Kind regards
Frans Meerhoff
