### ISSUE TITLE
Network Analysis crash

### ISSUE THREAD

**Issue by Marian-Popa** [jasp-stats/jasp-desktop#2564]
## Template for bug reports

* JASP version: .8.6.0
* OS name and version: Windows 10 version 1803
* Analysis: Network
* Steps to reproduce: Select variables-setting options one by one, starting with network plot.
The crash message appears after selecting more than 2 options, first of them being network plot. 
If I select only network plot finish with OK, and after that I make another network analysis, with the same variables, and selecting further options (without network plot), the crash does not happens.
It seems that the crash is related with network plot. If I want use Color nodes by, I must set first this option, and then select the network plot, otherwise the crash happens.        

![image](https://user-images.githubusercontent.com/30208007/40464943-d2f00068-5f26-11e8-96ff-0a991f39010f.png)

**Comment by AlexanderLyNL** [comment]
Could you please send us the JASP file?

**Comment by Marian-Popa** [comment]
You may find the file in attachment.

 

Best regards,

Marian

**Comment by AlexanderLyNL** [comment]
Hi Marian,

It doesn't appear here. Can you please add the zip to the github thread? 

https://github.com/jasp-stats/jasp-desktop/issues/2564#issuecomment-396607894

Kind regards,
Alexander

**Comment by Marian-Popa** [comment]
Here is it...

[NTW 1.zip](https://github.com/jasp-stats/jasp-desktop/files/2094578/NTW.1.zip)

**Comment by AlexanderLyNL** [comment]
Hi Marian,

I've tried this on the development version and the problem seems to be fixed. The new version will be available soon. Please reopen if the problem reappears.

Cheers,
Alexander

**Comment by Marian-Popa** [comment]
Great, cheers... 
Marian

**Comment by Marian-Popa** [comment]
Hi, Alexander

Unfortunately, the problem still persists in JASP 0.9.0.1
See the excel file below.
Best regards,
Marian

[ProQol_19aug2018.xlsx](https://github.com/jasp-stats/jasp-desktop/files/2300393/ProQol_19aug2018.xlsx)

**Comment by Marian-Popa** [comment]
A kind remainder about the above comment.
JASP always crash during Network analysis, after more options are added.
Thanks,
Marian

**Comment by AlexanderLyNL** [comment]
Dear Marian,

I've tried to run the analysis again and was unable to replicate your issue. Could you please try our experimental build and see if the problem is still there? 

Mac:
https://static.jasp-stats.org/JASP-0.9.1.0-Nightly-03-10-2018.dmg

Windows:
https://static.jasp-stats.org/JASP-0.9.1.0-Setup-Nightly-03-10-2018(64).exe
https://static.jasp-stats.org/JASP-0.9.1.0-Setup-Nightly-03-10-2018(32).exe

Cheers,
Alexander
