### ISSUE TITLE
Feature request for "take JASP for a spin"

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2565]
The startup screen presents the message "So open a data file and take JASP for a spin!"
It would be nice if the user could click that text, which should then simply act as if the user had selected "File" from the menu bar (with "Open" selected by default).
Not a top priority, obviously, but it would be nice.
E.J.

**Comment by FransMeerhoff** [comment]
E.J.

Coincidence, but believe me or not, but I was busy with this  :-)

Cheers Frans



On 24 May 2018, at 10:18, EJWagenmakers <notifications@github.com<mailto:notifications@github.com>> wrote:


The startup screen presents the message "So open a data file and take JASP for a spin!"
It would be nice if the user could click that text, which should then simply act as if the user had selected "File" from the menu bar (with "Open" selected by default).
Not a top priority, obviously, but it would be nice.
E.J.
