### ISSUE TITLE
Simple Items Still Nice

### ISSUE THREAD

**Issue by ksanders12** [jasp-stats/jasp-desktop#2572]
I was looking at Jasp and thought it was nice for some of the complex analytical items. Then I realized sometimes the simple things can be helpful as additional information were missing.  Kinda a "side thing" in the output.

It would be good to add 
MEAN
MEDIAN
SUM
MAX
MIN
 
etc.

**Comment by AlexanderLyNL** [comment]
Dear ksanders12,

Thanks for the feedback, but this type of information is available in the "Descriptive Statistics" pane. 

Cheers,
Alexander
