### ISSUE TITLE
Bug when trying to show plots from repeated measures anova with BS factors

### ISSUE THREAD

**Issue by AugustOlsson** [jasp-stats/jasp-desktop#2576]
I have a dataset with 3 BS conditions with 24 participants in each of two experimental conditions and 90 participants in a control condition. Each participant has produced 28 judgements on different stimuli.

I have computed an repeated measures BANOVA with 1 within-subject factor with 28 levels and a BS factor with 3 levels. 

JASP manages to perform the BANOVA calculation, but when I try to produce a plot with the within-subject actor on the horizontal access and the BS factor as lines I get the following error message:

"This analysis terminated unexpectedly.

Error in if (usePooledSE) {: argument is of length zero

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.rmAnovaDescriptivesPlot(descriptivesDataset, options, perform, status, stateDescriptivesPlot = NULL)

.summarySEwithin(as.data.frame(dataset), measurevar = 'dependent', betweenvars = .v(betweenSubjectFactors), withinvars = .v(repeatedMeasuresFactors), idvar = 'subject', conf.interval = options$confidenceIntervalInterval, na.rm = TRUE, .drop = FALSE, errorBarType = options$errorBarType, usePooledSE = options$usePooledStandErrorCI)

.summarySE(data, measurevar, groupvars = c(betweenvars, withinvars), na.rm = na.rm, conf.interval = conf.interval, .drop = .drop, errorBarType = errorBarType, usePooledSE = usePooledSE)"

Best regards,
August

**Comment by AlexanderLyNL** [comment]
Hi August,

This is fixed in the newest version. Can you please send me the JASP file in a zip to this thread? Then I can see if this is indeed the case. 

Cheers,
Alexander

**Comment by AugustOlsson** [comment]
Forgot to add that I am on JASP 0.8.6.0, using Windows 10 Education as IOS. There is a lot of other stuff in the same file, but I'll clean it up for you and send you a version in the afternoon.

Best,
August

**Comment by charlesmalpas** [comment]
Hi all,

I have replicated the bug on 0.8.6 on Mac OSX 10.13.4 using the example 'Bugs' dataset. I specified the within subjects factors only (no between subjects). Trying to plot produces the same error.

![image](https://user-images.githubusercontent.com/955468/40882274-a47372e6-671f-11e8-9359-2aafbd2e2ec9.png)

Hope this helps!

Charles

**Comment by AugustOlsson** [comment]
Hi again,

I can't share the orginal data-set due to confidentially because its ongoing research. I'll try and make time to set up a "sham" data-set with the same number of factors, but I am I kind of swamped atm. Maybe the "Bugs"-dataset is enough? Otherwise I'll try to make time as soon as possible.

/August

**Comment by EJWagenmakers** [comment]
It may be best to wait for the upcoming version, because I think we have fixed the issue.
Cheers,
E.J.

**Comment by AlexanderLyNL** [comment]
It's fixed in the newest version, but I wanted to confirm this for other data sets as well. The newest release will be online after some checks. Please reopen if the bug persists in the newest version.
