### ISSUE TITLE
Proposed name change to Correlation to Correlation Matrix

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#258]
@EJWagenmakers, we have two sorts of Bayesian correlation; the matrix one (like the classical one), and the pairs one (similar UI to the paired t-test).

We could call these (acutally, we've already been calling them):
1. *Correlation Matrix*
2. *Correlation Pairs*

If so, we might like to change the name of the classical correlation to be *Correlation Matrix* as well

thoughts?

**Comment by EJWagenmakers** [comment]
Yes, good idea; let's keep things as symmetric as we can (between classical
and Bayesian).
EJ
