### ISSUE TITLE
ANOVA bug

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2592]
From the forum:
http://forum.cogsci.nl/index.php?p=/discussion/4176/error-messages-and-other-issues

Cheers,
E.J.

**Comment by MichlF** [comment]
Hi,

Michif here from the forum post.
I tried it with the new JASP version (9.0.0) but the issue still occurs.
I have attached the .csv file to reproduce the issue.
[CDAstatistics_delay1_300-900.zip](https://github.com/jasp-stats/jasp-desktop/files/2128129/CDAstatistics_delay1_300-900.zip)

**Comment by EJWagenmakers** [comment]
Team: the relevant forum entry is here: http://forum.cogsci.nl/index.php?p=/discussion/4176/error-messages-and-other-issues

**Comment by MichlF** [comment]
Hi Johnny,

my apologies. Indeed, the error does no longer occur in the newest version.

The dragging and dropping, however, still remains. Same applies to changing the sizes of the windows.

**Comment by AlexanderLyNL** [comment]
I could not reproduce this error. This seems to be fixed. Please reopen if the issue reappears.
