### ISSUE TITLE
Output window automatically scrolls to the top after addition of new elements

### ISSUE THREAD

**Issue by noahmotion** [jasp-stats/jasp-desktop#2594]
## Template for bug reports

* JASP version: 0.8.6
* OS name and version: High Sierra 10.13.4
* Analysis: Descriptive stats, various plots
* Steps to reproduce: Read in data, add a plot, add another plot (or add/remove an element to/from a plot) and the output window scrolls to the top, typically away from the plot of interest (e.g,. if you've already produced a table or figure or two).

**Comment by FransMeerhoff** [comment]
Hi @noahmotion 

Sorry for the late response.
We are aware of this issue and at the moment we are optimizing the recalculation of the analyses.
In that optimation this issue will be fixed too. 
We expect this in one the the next releases before the end of the year, but it is on our backlog list.

Kind regards 
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Solved in 0.9.1
