### ISSUE TITLE
Error adding interaction in Bayesian linear regression

### ISSUE THREAD

**Issue by Steffijasp** [jasp-stats/jasp-desktop#2613]
Dear JASP Team, 
When I wanted to add an interaction between the variables 'gender' and 'depression' in the Bayesian linear regression analysis, the following error popped-up: 

This analysis terminated unexpectedly.
Error in rawToChar(as.raw(out)): embedded nul in string: 'depression0�gender'
Stack trace

What does this error mean?? What can I do to make sure this error won't pop up again? 

* JASP version: 0.8.6
* OS name and version:
* Analysis: Bayesian linear regression
* Steps to reproduce: adding an interaction

**Comment by AlexanderLyNL** [comment]
Hi Steff,

Can you please add the JASP file as a zip? Then we can study it more closely.

Cheers,
Alexander

**Comment by Steffijasp** [comment]
Hi Alexander,


Thank you for the fast response!

Attached I put the jasp file as a zip. Let me know if you can open it.

So, in this dataset I did the Bayesian linear regression.

As an outcome variable I chose 'suirisk' and all the other variables are the predictor variables.

The error came when I wanted to create an interaction between 'gender' and 'depression'.

Look forward to your response!


Cheers,

Steffi


________________________________
Van: AlexanderLyNL <notifications@github.com>
Verzonden: vrijdag 8 juni 2018 14:19
Aan: jasp-stats/jasp-desktop
CC: Steffijasp; Author
Onderwerp: Re: [jasp-stats/jasp-desktop] Error adding interaction in Bayesian linear regression (#2613)


Hi Steff,

Can you please add the JASP file as a zip? Then we can study it more closely.

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
Could you please do this in the github thread?

https://github.com/jasp-stats/jasp-desktop/issues/2613#issuecomment-395750488

I'll have a look at it and see whether it's fixed in the beta release first.

**Comment by Steffijasp** [comment]
[suiciderisk.zip](https://github.com/jasp-stats/jasp-desktop/files/2084406/suiciderisk.zip)

Hope you can open this correctly!

**Comment by AlexanderLyNL** [comment]
Hi Steffi,

This problem is solved, so you'll be able to run this in next release. To help you out, I've already done the analysis. Depending on your preference, I can upload the new JASP file here, or I can send it to you in private. You can see the results in 0.8.6 by opening the JASP file, but indeed not run it.

Cheers,
Alexander

**Comment by Steffijasp** [comment]
Hi Alexander, 
Thank you very much for your help! Could you send the file to me in private? 

Cheers, 
Steffi

**Comment by AlexanderLyNL** [comment]
Please send me an email at a.ly@jasp-stats.org
