### ISSUE TITLE
Notes in JASP files are lost at random

### ISSUE THREAD

**Issue by Kucharssim** [jasp-stats/jasp-desktop#2618]
* JASP version: 0.9
* OS name and version: Windows
* Analysis: Any
* Steps to reproduce: Create a note (1), save a .jasp file. Open a .jasp file, make a different note (2), and save. Open .jasp file and the original notes from step (1) are lost.

Annoyingly, this bug does not occur reliably and sometimes does not happen. Usually, making the note again and saving again saves the note, but sometimes not. I know that this is not much information to track the bug, I will post here again if I observe some regularities. But the frequency of this happening is high enough to really annoy me working with notes! (I am certain that it is not because I forgot to save changes or accidentaly deleted them.)

**Comment by EJWagenmakers** [comment]
This is important to fix (also because it is annoying for the user, who might see part of his/her work lost). Simon, this has nothing to do with copy-paste? (that is, it occurs also when you are not using copy-paste to create a new version of the note?)

**Comment by Kucharssim** [comment]
Yeah, I am not copy pasting anything...

**Comment by AlexanderLyNL** [comment]
See the Sheet
