### ISSUE TITLE
B T-Tests: Missing values and sequential analysis

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#264]
@EJWagenmakers, @quentingronau 

at the moment, the sequential analysis shats itself if the data set begins with missing values. can we simply leave the Bayes factor at 1 for these values? alternatively, we can exclude them.

everywhere else we've tried to automate the handling of missing values.

also, i think it doesn't like it when the first couple of values are the same. is there no way we can handle this without throwing an error?

**Comment by EJWagenmakers** [comment]
Yes, when the analysis starts with NAs just leave it at BF=1 (basically,
update the initial BF=1 only if there is no error). Yes it will also shit
itself when the first few values are the same. It would be nice to catch
all of these start-up errors and take appropriate action -- for instance,
leaving BF as 1, or even better, not plotting those values.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
