### ISSUE TITLE
JASP 0.9 does not recognize special characters on Mac and Windows

### ISSUE THREAD

**Issue by tegedik** [jasp-stats/jasp-desktop#2641]
## Template for bug reports

* JASP version: 0.9
* OS name and version: Mac El Capitan (10.11.6)
* Analysis: - 
* Steps to reproduce: -

I can't open the program after updating from the previous version to 0.9 ("JASP quit unexpectedly."). I deleted and reinstalled. It didn't work. Previous versions (e.g., 0.8.6) work without an issue. 

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by boutinb** [comment]
Hello @tegedik El Capitan is an old version of Mac OS. Can't you upgrade it to Sierra or even High Sierra?

**Comment by tegedik** [comment]
I don't prefer to upgrade to Sierra. It is more demanding as an OS and I don't need its features. But is that the reason behind the problem? If so, does JASP work only on most recent OSX versions? El Capitan is not that old either. Besides, under Installation Guide for Mac OS X on the website, it says "JASP is available for Mac OS X, version 10.10 (Yosemite) and above".

**Comment by vicenteinefo** [comment]
I have the same problem and I can't upgrade my Mac OS version, I've an old macbook.
I'm university professor and I use this software to teach statistics in a sport sciences degree, It's an excellent tool but It's a pity if I can't use the last improvements.

JASP version: 0.9
OS name and version: Mac El Capitan (10.11.6)
Macbook 13" aluminium late 2008

**Comment by boutinb** [comment]
I just suspect that it is the problem. I don't have yet an El Capitan version where I can test it. The framework we use (Qt) says it should be compatible, but it is maybe a problem of the compiler we use. I will look further.

**Comment by AlexanderLyNL** [comment]
Hi tegedik and vicenteinefo, 

Thanks for this feedback. We didn't see this coming, as all of us have upgraded our macOS to Sierra or higher. As such, we don't have any macs to test this on. Once Bruno made new builds, would you both be keen to help out with testing this issue? We would very much appreciate your help on this. 

Cheers,
Alexander

**Comment by vicenteinefo** [comment]
Hi AlexanderLyNL,

I will be happy to help.
I've saved the previous version (0.8.6) to be able to use it at any time.
I suppose that I will always be able to use the immediately previous version that is stable on my computer.
I await your instructions

**Comment by vicenteinefo** [comment]
Hi boutinb,
I've downloaded the version you attached and it seems to work perfectly :)
Will you upload this version to the official web?
Thanks for your gorgeous job

**Comment by tegedik** [comment]
hello @boutinb 
It works for me too. Thanks a lot for the fix.
Best,
Tahir

**Comment by vicenteinefo** [comment]
Hi @boutinb 

I've just open an old JASP file analysis and it seems that the new version doesn't recognize special characters like accents. Here's an example: Valoraci**ó**n

The error message reported is this:

This analysis terminated unexpectedly.

Error in (structure(function (...) : Cannot find column **Valoracin** del cliente (estado de salud, **valoracin** de los factores de riesgo cardiovascular, **condicin fsica**.<80>)

Stack trace

analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.readDataSetHeader(columns.as.numeric = variables, columns.as.factor = splitName)

.fromRCPP('.readDataSetHeaderNative', unlist(columns), unlist(columns.as.numeric), unlist(columns.as.ordinal), unlist(columns.as.factor), all.columns ≠ FALSE)

do.call(obj, args)

(function (...) 
{
    .External(InternalFunction_invoke, xp, ...)
})(NULL, c('Actividades bailadas', 'Aquagym/aquafitness', 'Actividades de sala verde (pilates, yoga, espalda sana...)', 'Entrenamiento personal', 'Entrenamiento funcional', 'Entrenamiento para el aumento de masa muscular', 'Entrenamiento con poblaciones especiales (embarazadas, etc.)', 'Entrenamiento del CORE', 'Entrenamiento con resistencias inerciales', 'Habilidades directivas', 'Estrategias de marketing y venta', 'DEA y primeros auxilios', 'Prioridad 1', 'Prioridad 2', 'Prioridad 3', 'Valoracin del cliente (estado de salud, valoracin de los factores de riesgo cardiovascular, condicin fsica.<80>)'
), NULL, 'Dpto', FALSE)

**Comment by akashrajkn** [comment]
@vicenteinefo thank you for reporting this. Is this specific to an analysis?

**Comment by vicenteinefo** [comment]
@akashrajkn it seems not to be specific to the analysis, in fact if I correct the word typing it without accents or special characters, the analysis seems to be executed without problems

**Comment by boutinb** [comment]
@vicenteinefo Can you send such a file (via GutHub)?

**Comment by akashrajkn** [comment]
@vicenteinefo thank you for the info. 

@boutinb  I am able to replicate this issue on mac and windows (it works fine on linux)

**Comment by boutinb** [comment]
@vicenteinefo: I have made a new setup with the hotfix: https://static.jasp-stats.org/JASP-0.9.0.1.dmg. Can you test it?

**Comment by vicenteinefo** [comment]
I've test it, the analysis runs well and doesn't appear any error message but I realized that the special characters of the different categories of the variable are omitted. I attach a screenshot for details

![captura de pantalla 2018-06-25 a las 19 59 39](https://user-images.githubusercontent.com/29978768/41867108-74791f88-78b2-11e8-93c0-f445acede19f.png)

**Comment by boutinb** [comment]
@vicenteinefo: I have made a new version, same link:  https://static.jasp-stats.org/JASP-0.9.0.1.dmg
Hopefully this one has no problem anymore!

**Comment by vicenteinefo** [comment]
@boutinb it seems to work properly! Thanks a lot

**Comment by boutinb** [comment]
Nice! We will set this release today.

**Comment by Jennifer500** [comment]
Hello - 
I have the same problem, also under Mac OS 10.11.
Jasp was working perfectly until I tried to upgrade to 0.9 and now it won't even load, it crashes with a Mac OSX problem report window. 

I've already tried the newer versions referenced in this thread but it still won't open. 

thanks for any help you can provide 

Jennifer

**Comment by IrisMW** [comment]
Hi Jennifer and all,
I have the same problem. JASP used to work fine, but now it won't open anymore (MAC error message "JASP quit unexpectedly"). I deinstalled my older version and installed 0.9.0.1, but still same problem.

Thanks for any help with this!
Iris
