### ISSUE TITLE
[Solved] JASP 0.9.0.1 Apple installation error - Installed JASP for OSX 10.12 on an OSX 10.11 workstation

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-desktop#2668]
Morning folks
I have just uninstalled JASP 0.8.6 and downloaded the latest version.  Double clicked the dmg file and dragged the icon to applications. On trying to open JASP I get an error message "JASP quit unexpectedly" - send report to Apple. The report generated is below.

Cheers
Mark

Process:               JASP [2295]
Path:                  /Applications/JASP.app/Contents/MacOS/JASP
Identifier:            org.jasp-stats.jasp
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           JASP [2295]
User ID:               501

Date/Time:             2018-07-02 10:39:00.315 +0100
OS Version:            Mac OS X 10.11.6 (15G20015)
Report Version:        11
Anonymous UUID:        5CD8C954-541B-9ABE-1523-3936F109F64C

Sleep/Wake UUID:       6B2D2388-73DE-4A01-A899-F1635D54A00B

Time Awake Since Boot: 15000 seconds
Time Since Wake:       1100 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

kernel messages:

VM Regions Near 0x7fff746490a8 (cr2):
    __LINKEDIT             00007fff6c32c000-00007fff6c341000 [   84K] r--/rwx SM=COW  /usr/lib/dyld
--> Submap                 00007fff70000000-00007fff80000000 [256.0M] r--/rwx SM=PRV  process-only VM submap
    unused shlib __DATA    00007fff731ba000-00007fff77763000 [ 69.7M] rw-/rw- SM=COW  system shared lib __DATA not used by this process

Thread 0 Crashed:
0   dyld                          	0x00007fff6c2b9000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000000000000d  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff5996fc68
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff6c2b9000  rfl: 0x0000000000000201  cr2: 0x00007fff746490a8
  
Logical CPU:     0
Error Code:      0x020000f4
Trap Number:     133

Binary Images:
    0x7fff6c2b8000 -     0x7fff6c2efa47  dyld (???) <C8E77F6D-CE86-3C5B-8576-2584A799B51E> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 7069
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=308K resident=0K(0%) swapped_out_or_unallocated=308K(100%)
Writable regions: Total=10.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=10.2M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Process Corpse Info               2048K        2 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
VM_ALLOCATE (reserved)               4K        2         reserved VM address space (unallocated)
__DATA                             240K        3 
__LINKEDIT                          84K        2 
__TEXT                             224K        2 
mapped file                       7092K        4 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             73.5M       14 
TOTAL, minus reserved VM space    73.5M       14 

Model: MacBook8,1, BootROM MB81.0172.B00, 2 processors, Intel Core M, 1.3 GHz, 8 GB, SMC 2.25f87
Graphics: Intel HD Graphics 5300, Intel HD Graphics 5300, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, 0x4544464231363441314D412D47442D462020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, 0x4544464231363441314D412D47442D462020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x131), Broadcom BCM43xx 1.0 (7.21.95.178.1a2)
Bluetooth: Version 4.4.6f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
Thunderbolt Bus:

**Comment by DrMarkGS** [comment]
Let me check. Thanks for prompt reply
Mark

**Comment by DrMarkGS** [comment]
Looks like I did in error
Thanks

**Comment by AlexanderLyNL** [comment]
Hi Mark,

Thanks for this report. 

Cheers,
Alexander
