### ISSUE TITLE
Bug in Logistic Regression

### ISSUE THREAD

**Issue by timdraws** [jasp-stats/jasp-desktop#2675]
When changing the reference class in logistic regression, only one of the ways to do it automatically triggers a change in the table. When doing it the other way, I have to change something in the analysis in order to display the table with a different reference class. See the GIF below.

![bug](https://user-images.githubusercontent.com/36475541/42275292-1ccb72ce-7f90-11e8-9360-d34f6cc3bd28.gif)

**Comment by vankesteren** [comment]
This seems to be a bug with the triggering of re-analysis after reordering

**Comment by JorisGoosen** [comment]
Fixed it!

**Comment by JorisGoosen** [comment]
(well, @FransMeerhoff  did ;))
