### ISSUE TITLE
Bayesian Correlation Pairs: Sequential analysis plot not possible

### ISSUE THREAD

**Issue by CarolinePeters** [jasp-stats/jasp-desktop#2677]
JASP version: 0.8.6
OS name and version: MacOS High Sierra Version 10.13.4
Analysis: Bayesian correlation Pairs

Hey guys, 
I am using the Bayesian correlation in JASP. It worked fine until this error appeared for one pair of datasets when trying to plot the sequential analysis: 
"Plotting is not possible: Fehlender Wert, wo TRUE/FALSE nötig ist".
The German part means: missing value where TRUE/FALSE is necessary (I do not know why the second part is in German).
As you can see in the screenshot below, there are no missing values in my dataset and it looks just like any other dataset I analysed so far without any problems. I import data as .csv files that I produce using Matlab.
Is there something wrong with my data or is it a bug?

Thanks in advance!
Caroline

![image](https://user-images.githubusercontent.com/40830662/42279307-aaa42e9e-7f9d-11e8-967f-73a00c87cda3.png)

**Comment by AlexanderLyNL** [comment]
Dear Caroline Peters, 

Could you please try to run this analysis in JASP 0.9.0.1? This bug should have been fixed in the newest version. Please let me know the result, so I can either close this thread or study this a bit further. 

Cheers,
Alexander

**Comment by CarolinePeters** [comment]
Dear Alexander,
thanks for your enormously quick reply!
As you suspected, in version 0.9.0.1 it works. So you can go ahead and close this thread, I am happy!
Thanks again
Caroline

**Comment by AlexanderLyNL** [comment]
Thanks for the feedback!
