### ISSUE TITLE
SEM MODULE: Grouping variable, does not seem to work

### ISSUE THREAD

**Issue by MAgojam** [jasp-stats/jasp-desktop#2678]
* JASP version: 0.9.0.1
* OS name and version: Windows 7 x64 Pro Ita
* Analysis: SEM module
* Steps to reproduce: Grouping variable

Hi @vankesteren,
Thank you for improving the SEM module for Jasp.

With the data "HolzingerSwineford1939" I tried to compare the output of the SEM module of Jasp with that obtained from lavan 0.6-1 in RStudio.
The request for an analysis for several groups with **Grouping variable**, does not seem to work (see screenshot).
![sem_screenshot](https://user-images.githubusercontent.com/36552289/42283709-8bf5a63c-7faa-11e8-8838-9530cfc98ac1.png)

All my esteem and interest in the great work you are doing.
Maurizio

**Comment by vankesteren** [comment]
Hi Maurizio, 

thank you for submitting this issue; I'll look into it on tuesday!

**Comment by vankesteren** [comment]
Hi Maurizio, this was indeed a pertinent bug in JASP 0.9.0.1. With the next release, this will be fixed (#2689). Until then, I suggest you revert back to a previous version of JASP if you want to run multigroup SEM!
