### ISSUE TITLE
Mixed ANOVA with filter applied

### ISSUE THREAD

**Issue by richjallen** [jasp-stats/jasp-desktop#2679]
## Template for bug reports

* JASP version: 0901
* OS name and version: OS High Sierra 10.13.5
* Analysis: Repeated measures ANOVA with between subjects factor (2x2). Filtering applied to omit 1 level of the originally 3-level between-subjects factor. 
* Steps to reproduce: Analysis works until the between-subjects factor is added in. Bayesian ANOVA works fine, problem is with the frequentist.
In uploaded data file, repeated measures factor is load, with "PER_REC_AMB" and "PER_REC_SEM" as levels. Between-subjects factor, and filtered factor, is "Exper"

Error message:
This analysis terminated unexpectedly.

[Data.csv.zip](https://github.com/jasp-stats/jasp-desktop/files/2166266/Data.csv.zip)

Error in contrast.emmGrid(referenceGrid[[contrast$variable]], contrCoef): Nonconforming number of contrast coefficients

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.resultsContrasts(dataset, options, referenceGrid)

emmeans::contrast(referenceGrid[[contrast$variable]], contrCoef)

contrast.emmGrid(referenceGrid[[contrast$variable]], contrCoef)

stop('Nonconforming number of contrast coefficients')

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by AlexanderLyNL** [comment]
This is fixed in our newest version (please refresh the analysis). Please reopen if the issue resurfaces.
