### ISSUE TITLE
[Solved] JASP build on XCode8.2 does not work for MAC OS 10.10.5 (Yosemite). A: Signing issue for 10.11 build

### ISSUE THREAD

**Issue by eric-kruger** [jasp-stats/jasp-desktop#2681]
## Template for bug reports

* JASP version: 0.9.0.1
* OS name and version: MAC OS X 10.10.5
* Analysis: NA
* Steps to reproduce: Install, copy to applications folder, start JASP and I receive the following error
Process:               JASP [1326]
Path:                  /Applications/JASP.app/Contents/MacOS/JASP
Identifier:            org.jasp-stats.jasp
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           JASP [1326]
User ID:               502

Date/Time:             2018-07-07 08:35:59.819 -0600
OS Version:            Mac OS X 10.10.5 (14F2315)
Report Version:        11
Anonymous UUID:        E3E8F1C2-BD6E-3816-28BF-E11502964299

Sleep/Wake UUID:       724D5919-ABA2-44EC-A920-71257A4AF3B6

Time Awake Since Boot: 10000 seconds
Time Since Wake:       710 seconds

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000

kernel messages:

VM Regions Near 0x7fff7aaad0a0 (cr2):
    __LINKEDIT             00007fff6a55f000-00007fff6a573000 [   80K] r--/rwx SM=COW  /usr/lib/dyld
--> Submap                 00007fff70000000-00007fff80000000 [256.0M] r--/rwx SM=PRV  process-only VM submap
    unused shlib __DATA    00007fff784b3000-00007fff7aab7000 [ 38.0M] rw-/rw- SM=COW  system shared lib __DATA not used by this process

Thread 0 Crashed:
0   dyld                          	0x00007fff6a4f0000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000000000000d  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff5a64fc78
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff6a4f0000  rfl: 0x0000000000000201  cr2: 0x00007fff7aaad0a0
  
Logical CPU:     0
Error Code:      0x020000f4
Trap Number:     133

Binary Images:
    0x7fff6a4ef000 -     0x7fff6a52592f  dyld (???) <B1762705-1D4F-3B93-B515-61A547AB6346> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 4716
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=300K resident=300K(100%) swapped_out_or_unallocated=0K(0%)
Writable regions: Total=8420K written=0K(0%) resident=12K(0%) swapped_out=0K(0%) unallocated=8408K(100%)
 
REGION TYPE                      VIRTUAL
===========                      =======
STACK GUARD                        56.0M
Stack                              8192K
VM_ALLOCATE                           8K
VM_ALLOCATE (reserved)                4K        reserved VM address space (unallocated)
__DATA                              228K
__LINKEDIT                           80K
__TEXT                              220K
mapped file                        7356K
shared memory                         4K
===========                      =======
TOTAL                              71.7M
TOTAL, minus reserved VM space     71.7M
 

Model: MacBookPro5,5, BootROM MBP55.00AC.B03, 2 processors, Intel Core 2 Duo, 2.26 GHz, 8 GB, SMC 1.47f2
Graphics: NVIDIA GeForce 9400M, NVIDIA GeForce 9400M, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x859B, 0x435434473353313036374D2E433136464B00
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x859B, 0x435434473353313036374D2E433136464B00
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.106.98.100.24)
Bluetooth: Version 4.3.6f4 17916, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Crucial_CT240M500SSD1, 240.06 GB
Serial ATA Device: HL-DT-ST DVDRW  GS23N
USB Device: Internal Memory Card Reader
USB Device: Built-in iSight
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
Thunderbolt Bus:

**Comment by boutinb** [comment]
@eric-kruger Did you install the JASP version for El Capitan? If you have installed the version for Sierra, it crashes on a El Capitan Mac OS

**Comment by eric-kruger** [comment]
Yes, I installed the verison 'JASP-0.9.0.1-XCode8.2.dmg' by clicking on the El Cap link

**Comment by AlexanderLyNL** [comment]
@boutinb or @FransMeerhoff can we try an older compiler?

**Comment by eric-kruger** [comment]
Okay, I can do that. You should probably make clear on the website that the link just works for El Capitain and not El Capitain and below.

**Comment by AlexanderLyNL** [comment]
This issue might be related to #2682

**Comment by AlexanderLyNL** [comment]
Hi @eric-kruger,

Out of curiosity, does the following version work for you?

https://static.jasp-stats.org/JASP-0.9-XCode8.2.dmg

Cheers,
Alexander

**Comment by boutinb** [comment]
There is apparently a problem with a code signing for this version. I have made a version without code signing and it seems to work for other people: https://static.jasp-stats.org/JASP-0.9.0.1-XCode8.2-NoSigning.dmg. Can you try it?

**Comment by eric-kruger** [comment]
That worked!

**Comment by AlexanderLyNL** [comment]
@eric-kruger are you still on Yosemite?
@boutinb Any idea why the signing went wrong for 10.11 (and below?), while it works fine for 10.12 and above?

**Comment by eric-kruger** [comment]
still on Yosemite, 10.10.5 never did change before you made this change.

**Comment by AlexanderLyNL** [comment]
Thanks for letting us know!
