### ISSUE TITLE
Can't Open JASP 0.9.0.1 for MAC OS X 10.11

### ISSUE THREAD

**Issue by tegedik** [jasp-stats/jasp-desktop#2682]
## Problem returns

* JASP version: 0.9.0.1
* OS name and version: Mac El Capitan (10.11.6)
* Analysis: - 
* Steps to reproduce: -

Although there is an installer for MAC OS X 10.11 or below, I can't open JASP. I asked a similar question [here](https://github.com/jasp-stats/jasp-desktop/issues/2641) before. Unfortunately, I have the same problem again.

**Comment by Jennifer500** [comment]
Hello -
(sorry I replied on the earlier thread - copying my question here)

I have the same problem, also under Mac OS 10.11.
Jasp was working perfectly until I tried to upgrade to 0.9 and now it won't even load, it crashes with a Mac OSX problem report window.
"
Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

kernel messages:

VM Regions Near 0x7fff7c04f0a8 (cr2):
    __LINKEDIT             00007fff69fa6000-00007fff69fbb000 [   84K] r--/rwx SM=COW  /usr/lib/dyld
--> Submap                 00007fff70000000-00007fff80000000 [256.0M] r--/rwx SM=PRV  process-only VM submap
    unused shlib __DATA    00007fff79441000-00007fff7d9ea000 [ 69.7M] rw-/rw- SM=COW  system shared lib __DATA not used by this process

Thread 0 Crashed:
0   dyld                          	0x00007fff69f33000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000000000000d  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff59dc4cb0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff69f33000  rfl: 0x0000000000000201  cr2: 0x00007fff7c04f0a8
  
Logical CPU:     0
Error Code:      0x020000f4
Trap Number:     133
"

I've already tried the newer versions referenced in the other by @tegedik thread but it still won't open.

thanks for any help you can provide

Jennifer

**Comment by AlexanderLyNL** [comment]
Just for clarity, the post 

https://github.com/jasp-stats/jasp-desktop/issues/2641#issuecomment-399091168

suggests that the fix 

https://static.jasp-stats.org/JASP-0.9.0.1-XCode8.2.dmg

worked previously. Can you tell me what happened in between? This could provide us with valuable information. 

Cheers,
Alexander

Did something change in the meantime?

**Comment by tegedik** [comment]
That comment was for the version JASP-0.9-XCode8.2. This version still works for me. But the new one on the website (JASP-0.9.0.1-XCode8.2) is not working. I have no idea why this is the case.

**Comment by Jennifer500** [comment]
I tried both files from the website link yesterday, and then from the link in the forum this morning. 
Neither are working for me

Jennifer

**Comment by boutinb** [comment]
From the error message, I see that there might be a problem with the code signing. I have made a version without this code signing: https://static.jasp-stats.org/JASP-0.9.0.1-XCode8.2-NoSigning.dmg. Could you try it?

**Comment by Jennifer500** [comment]
Yes it works now! Thanks so much for fixing this!
:)
Jennifer

**Comment by boutinb** [comment]
Fine!

**Comment by GerardoGold** [comment]
I had the same problem with version 9.0.1, and it was solved with the above fix. However, I just installed version 0.9.1 on a Mac, and I get the exact same problem. WHat can I do to run version 0.9.1?
Thanks!
Gerardo

**Comment by sjayejohnston** [comment]
Same here, my Jasp 0.9.1 crashes on attempting to open.
