### ISSUE TITLE
No table scrolling

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-desktop#2698]
## Template for bug reports
<after the table opening it is impossible to scroll it anf to change the columntype
[No scrolling.zip](https://github.com/jasp-stats/jasp-desktop/files/2194896/No.scrolling.zip)
>

* JASP version: 0.9.0.1
* OS name and version: Win10
* Analysis:
* Steps to reproduce: 

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by AlexanderLyNL** [comment]
Dear Nikita,

I've looked at the docx file and saw that it contains a screenshot of the default correlation matrix output with two columns and two rows. By impossible to scroll, are you referring to the data file? You can move your mouse over the data viewer and press the left mouse button, the hand will then grab onto the data viewer allowing you to scroll. Alternatively, if your mouse has a scroll wheel, you can use that instead. To change the column type we recommend left clicking the symbol next in the column header. Perhaps it relates to the entry in the data file. We can look into this a bit more if you add the csv or jasp file in a zip to this thread. 

Cheers,
Alexander

**Comment by NikitaKhromov-Borisov** [comment]
Dear Alexander,
The scroll wheel provides the scrolling in the vertical dimension, however, I need to scroll in horizontal one from left to right.
Cheers,
Nikita

**Comment by NikitaKhromov-Borisov** [comment]
Dear Alexander, 

I have understood how to scroll the data tables. However, now I have met another problem. See the attachment.
It seems in previous JASP versions the quality of images was better. Is it possible to copy each plot separately?
[PlotsJASP.ZIP](https://github.com/jasp-stats/jasp-desktop/files/2197856/PlotsJASP.ZIP)

Cheers, Nikita

**Comment by AlexanderLyNL** [comment]
Hi Nikita, 

To only copy the plots that you're interested in, you can remove the variables that you're not interested in from the variables pane on the right hand side. This way only the variables that you're interested in will be shown. 

Cheers,
Alexander
