### ISSUE TITLE
Ugly correlation plots

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-desktop#2699]
## Template for bug reports
<copied corealtion graphs are ugly
[CorrPlotsUgly.xlsx](https://github.com/jasp-stats/jasp-desktop/files/2194923/CorrPlotsUgly.xlsx)
>

* JASP version: 0.9.0.1
* OS name and version: Win 10
* Analysis: corelation
* Steps to reproduce: correrlation graphs

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by AlexanderLyNL** [comment]
Dear Nikita, 

I've looked at the file and, in my opinion, the graphs look fine, meaning that they resemble the JASP output. Is there any in particular in the plot that puts you off?

Cheers,
Alexander
