### ISSUE TITLE
Could you include Welch's ANOVA and Games-Howell post-hoc test in next JASP release?

### ISSUE THREAD

**Issue by Felipe3105** [jasp-stats/jasp-desktop#2711]
## Template for enhancement requests
 
Hello, I was wondering if some developers could work on including an option for conducting a Welch's ANOVA test which is the best option when the assumption of homogeneity of variances has been violated. I know that Kruskall-Wallis is a good non-parametric alternative, but I've read that an ANOVA with Welch's correction is more robust than K-W and thus preferred. The same for Games-Howell's post-hoc test; Tukey's HSD, although being the favorite post-hoc, assumes equal variances which isn't always the case. I'm looking forward to your reply and thanks in advance.

Felipe.

**Comment by JohnnyDoorn** [comment]
Hi Felipe, 
Yes, we are working on this, and it will be in the next release!
Kind regards
Johnny
