### ISSUE TITLE
Problems changing measurement level

### ISSUE THREAD

**Issue by C23CAMBIER** [jasp-stats/jasp-desktop#2715]
* JASP version: 0.9.0.1
* OS name and version: OSX EL CAPTAIN
* Analysis: ANOVA

**Problems changing measurement level**

HI.  I encountered troubles changing measurement level. Jasp named one of my metric variables as being a nominal one and it seems to be impossible to change into a metric. With the older version I had an alert telling me 'You cannot change this column to type Scale'  with the newest version (0.9.0.1) it simply does not answer. Is there a solution to this ? 

Thanks !

**Comment by AlexanderLyNL** [comment]
Dear C23cambier,

Could you please include the JASP file in a zip to this thread? Then we can have a closer look at what's going on.

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
I think that this is solved in the newest version. Please reopen if this is not the case.
