### ISSUE TITLE
cannot download JASP files

### ISSUE THREAD

**Issue by NathenHarp** [jasp-stats/jasp-desktop#2717]
I cannot download tutorial JASP files at..
https://jasp-stats.org/2018/04/18/how-to-conduct-a-classical-independent-sample-t-test-in-jasp-and-interpret-the-results/

via https://osf.io/m345y/

I contacted OSF and here's the reply...
"Thank you for your email. As you’re attempting to download the dataset from JASP and not OSF, we can’t be of any help. We only provide support for OSF-hosted materials. In this way, I recommend reaching out to JASP’s user support to ask what you can do."

**Comment by EJWagenmakers** [comment]
Hi Nathen,

But you can *view* the output, right? I'm guessing the OSF folder was not set up to allow downloads. I'll check in with Tim Draws you manages this.

Cheers,
E.J.

**Comment by AlexanderLyNL** [comment]
Hi Nathen,

To simplify matters, I've attached both the csv and JASP to this comment as a zip. 

[drpExample.zip](https://github.com/jasp-stats/jasp-desktop/files/2244556/drpExample.zip)

It surprises me that the file cannot be downloaded, as it works fine for me. It would be good to figure out what happened here exactly. Could you please tell me whether: 
1. Can you view the jasp file?
2. Do you see the buttons at the right top as displayed in the screenshot?

<img width="1550" alt="screen shot 2018-07-31 at 11 08 20" src="https://user-images.githubusercontent.com/10271675/43450127-4bb928b0-94b2-11e8-9835-62a01c4ed228.png">

Cheers,
Alexander

**Comment by NathenHarp** [comment]
Yes. The download functions work correctly, the problem is being able to locate the results in the OSF search (i.e., files, projects, users, etc..).  For example, no results are returned when searching for 'JASPBlogPosts' or 'DRP'

**Comment by NathenHarp** [comment]
It's seems to be a permission issue when trying to download the file from link above...I forgot to mention previously with screenshot below..
![capture](https://user-images.githubusercontent.com/41922530/43465009-647fd13a-94aa-11e8-87bb-ee84ca3da578.GIF)

**Comment by timdraws** [comment]
I relocated the supplementary files of this blog post to a different OSF folder, where we also host the files for other blog posts: https://osf.io/zvxjw/. It should work properly now.

**Comment by AlexanderLyNL** [comment]
@timdraws Thanks! Could you please update all the links in the other blog posts as well, so people without an OSF account can view and download the JASP and CSV files? Once you've done that, could you please close this thread?

**Comment by timdraws** [comment]
There does not seem to be a problem with any other blog posts, as the according supplementary files are either located in the OSF folder mentioned above or in other public ones.
