### ISSUE TITLE
Ordinals in filter (and computed column) cannot be compared for inequality

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-desktop#2718]
An Ordinal column cannot be compared using operators such as '<' or '>'. This is because underneath it all JASP codes it as factors and R does not want to compare them like that. It is however unexpected that one can not compare ordinals like that so a solution must be found.

-------

A solution would be to coerce the data to integers (the levels underneath) and compare based on that. 

A problem then: Suppose a column has the following levels and factors:

`level fac`
`1     '2'`
`2     '1'`
`3     '3'`
It would create a discrepancy between using '<' and '==' for instance. Because in the latter case one would want to compare with the label/factor and not the level.
col < 2 would yield: `TRUE FALSE FALSE`
while col == 2 would yield `TRUE FALSE FALSE`

But one cannot ignore the factors either in case they are meaningful strings or something..

**Comment by AlexanderLyNL** [comment]
I've tried this in R and for me it yields the correct results: 

data <- data.frame(x=LETTERS[1:3], col=as.factor(c(2,1,3)))
data$col
col <- as.integer(data$col)

col < 2
col == 2

In JASP we have factors, nominal and text factors. This problem would not occur with text factors, as they cannot be converted into numerics or integers. Would the distinction between these three cases help?

**Comment by JorisGoosen** [comment]
Yeah but now you are messing up the order of your ordinal right?
What is the point of putting 2 in the first place otherwise?

**Comment by JorisGoosen** [comment]
should '2' be smaller than '1' or not?

**Comment by JorisGoosen** [comment]
Hmm, it seems that you can use ordered factors and then everything works as expected I think, see: https://stackoverflow.com/questions/23396591/factors-ordered-vs-levels

Now I just need to find a way of turning on "ordered" in Rcpp.

**Comment by JorisGoosen** [comment]
Fixed in  #2787
