### ISSUE TITLE
Export compute column results

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-desktop#2721]
@EJWagenmakers got a great idea from a user: copying/pasting data to JASP.

The first part of it would be being able to select data in the dataview of JASP and then being able to copy this to Excel/Libreoffice/GoogleDocs/whatever. Could be nice in conjunction with computed columns to retrieve the calculated new column.

The second part is the other way round, where one would copy a column, row or matrix (cols X rows) from a spreadsheet editor and paste it right into JASP. Which would then add the columns and rows as needed.

The first part is relatively easy because it requires only adding a selection-modus to the dataview and then using [qclipboard](http://doc.qt.io/archives/qt-4.8/qclipboard.html#details) to make it available elswhere.

The second part is harder beause it involves creating new columns and even rows if need be. For the rest it would use the reverse process of the copy to read in the new data. Maybe we could reuse parts of the csv-importer to determine column datatype?

**Comment by JorisGoosen** [comment]
The second step would, of course, imply that the datafile would be perfectly synchronized with JASP? What would we do here?

**Comment by AlexanderLyNL** [comment]
I'm not sure whether copying data from JASP to an editor is relevant anymore, because we can access the data by double clicking it. The second one could be created with compute column, but why not just copy and paste this in your preferred editor and save the data file?

**Comment by AlexanderLyNL** [comment]
Perhaps it's good to export it upon request, otherwise, we'll have quite some write actions. All in all, this seems to be easily doable once we decided.

**Comment by JorisGoosen** [comment]
As in, add an extra option somewhere? Maybe we could add an extra option to the double click on the data?

Or you mean as in: somebody wants to access this data and then we add the feature? Might be nice to anticipate this.

**Comment by AlexanderLyNL** [comment]
By request, I mean when the user wants to save the data. For instance, using export data in the file menu What do you think about that? The thing that worries me is the dependency and whether a computed column should change after we exported it.

**Comment by JorisGoosen** [comment]
Aah, i had missed that option. Yeah, that would be a good place to actually export the data yeah.

Why would it have to change after exporting it though? I assume nothing in the data would be changed through the action of exporting?

**Comment by AlexanderLyNL** [comment]
I was more worried about manipulations after we export the data. For instance, if the computed column is 

  asdf = firstColumn - mean(firstColumn) 

and the data are exported. Then after exporting, firstColumn changes, do we want asdf to change? If so, we then have to somehow tell JASP that asdf is a computed column. On the other hand, if someone just grabs the csv and then changes firstColumn, asdf won't change. If we now want to save the fact that asdf is a computed column in a csv file, we need to adapt that format, which doesn't sound like a good idea.

**Comment by JorisGoosen** [comment]
well, if you export the data that means that you just get a csv with the data.
If they want to save the fact that it is a computed column then they should save it as a .jasp file right?

**Comment by AlexanderLyNL** [comment]
Yes that sounds reasonable.
