### ISSUE TITLE
enhancement: filter for next analysis

### ISSUE THREAD

**Issue by ajestudillo** [jasp-stats/jasp-desktop#2735]
The filter is a very interesting tool. But it wuold be great to have a filter that applies to the next analysis and not  chaning all the previous output. Would this be possible?

**Comment by AlexanderLyNL** [comment]
Hi Ajestudillo,

This is something that we thought about as well, and another idea was to press an "okay" button before we apply the filter. We were also tossing up to have the user decide on which analysis the filter is applied to. In the end, as a design choice, we decided to make JASP as responsive as possible. I hope that you understand our design choice on this one. Please continue this discussion, if you have strong feelings about this. 

Cheers,
Alexander
