### ISSUE TITLE
Error Creating SSL context () when attempting to access OSF on Windows 7 64 bit JASP 0.9.0.1

### ISSUE THREAD

**Issue by Alexhauson** [jasp-stats/jasp-desktop#2749]
* JASP version: 0.9.0.1
* OS name and version: Windows 7 64 bit
* Analysis: Whenever I try to access OSF, I get the error message:
Error Creating SSL context ()
Username and/or password are not correct. Please try again
* Steps to reproduce:  See above. I have full access to OSF on my browser and using the same username and password, JASP gives me the error message: "Error Creating SSL context ()" then the box "Username and/or password are not correct. Please try again"

**Comment by boutinb** [comment]
Apparently it misses the OpenSSL dlls on Windows 7.
You can find them here: http://static.jasp-stats.org/ssleay32.zip
Download it, unzip it, and copy the 2 dll's file in the installation folder of JASP (usually C:\Program Files\JASP 0.9.0.1).
Tell me if that helps.
Bruno

**Comment by Alexhauson** [comment]
Dear Bruno,
Thank you, that worked perfectly.

**Comment by FransMeerhoff** [comment]
HI @Alexhauson 

Good to hear. I've closed this issue
