### ISSUE TITLE
JASP crashes or does nothing when hungry zombie example is selected

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2751]
Upon trying to open the hungry zombie csv file in JASP, we have the following:
1. On my laptop, JASP crashed (without an error message)
2. On a participant's laptop (Mac 10.13.6), nothing happened when he double-clicked. After closing and re-opening JASP, it did work.

Cheers,
E.J.

**Comment by JorisGoosen** [comment]
Fixed with latest PR
