### ISSUE TITLE
Bayesian binomial test missing subscripts

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2752]
The "BF" in the table for the Bayesian binomial test is missing the subscripts. See attach. The Summary Stats version still has them.
E.J. 
![subscriptsmissing](https://user-images.githubusercontent.com/8603015/44663631-662a1500-aa11-11e8-8a85-6e4c08fcff93.png)

**Comment by AlexanderLyNL** [comment]
Fixed PR #2760
