### ISSUE TITLE
Bug in value labels in the output

### ISSUE THREAD

**Issue by baltzis** [jasp-stats/jasp-desktop#2755]
## Template for bug reports

* JASP version: 0.9
* OS name and version: Windows 10 Pro (version 1803, build 17134,228
* Analysis: As of the last version of JASP (0.9), the value labels in non-latin alphabet (e.g. in Greek) appear in gibberish in the output pane. See the attached image: while in the data pane the value labels appear correctly, in the output pane they are unreadable (they appear as "51β‚¬ Ξ¬Ο‰Ο‚ 150β‚¬...").
* Steps to reproduce: Use the provided test SPSS file to get descriptive statistics in JASP.

[Files.zip](https://github.com/jasp-stats/jasp-desktop/files/2326704/Files.zip)

**Comment by FransMeerhoff** [comment]
Dear @baltzis 

This issue has been solved in the latest version JASP 0.9.0.1 (With  
https://github.com/jasp-stats/jasp-desktop/issues/2641) 
So if you download the latest version from our site and if you rerun the analysis or refresh the results in the jasp file with the 'Refresh All' option (see screenshot) your problem will probably be solved.
If not, please re-open this issue.

Kind regards
Frans Meerhoff

![screen shot 2018-08-28 at 09 38 41](https://user-images.githubusercontent.com/15656960/44708628-ed29cc80-aaa7-11e8-93bb-80a217ec4bcd.png)

**Comment by baltzis** [comment]
Thanks a lot for the prompt answer. The issue is actually solved. Sorry for not checking the latest version. I thought I had it installed.

Best regards
