### ISSUE TITLE
Summary Stats Correlation Tweak

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2758]
In the Summary Stats module, analysis "Regression" -> "Bayesian Correlation Pairs", we specify sample size and the sample correlation. However, the input field just asks for "Correlation Coefficient". Can we change that to "Sample Correlation Coefficient", so that there is no confusion on what needs to be entered there?
@akashrajkn @AlexanderLyNL See attach
![summarystats](https://user-images.githubusercontent.com/8603015/44719285-1ad03f00-aac3-11e8-9695-9ac8d6266cab.png)

**Comment by AlexanderLyNL** [comment]
Fixed in PR #2761
