### ISSUE TITLE
Plots: nested tick boxes should be "un-ticked" when higher order tick box is not selected anymore

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#276]
Hi Jonathon,

This is really a minor comment, but I noticed that if I select for the B t test e.g., "Prior and posterior" & "Additional info", and then "un-tick" (that's not the correct word in English, I guess) "Prior and posterior", the "Additional info" box remains ticked. The same holds for the
![tickboxes](https://cloud.githubusercontent.com/assets/8697436/6151674/ad534424-b217-11e4-9b11-47a3feeef54d.png)
 other nested structures of these boxes, e.g., the correlation.

**Comment by jonathon-love** [comment]
i think this is the expected behaviour :P

**Comment by jonathon-love** [comment]
you can think of it as:

"the last time this person wanted to view the prior and posterior, they wanted to see that additional information; so next time the person wants to see the prior and posterior, they will probably want to see the additional information"

"what the person did last time" is a good default.

**Comment by jonathon-love** [comment]
untick, and uncheck are both good [programmer] english words.

**Comment by quentingronau** [comment]
- "what the person did last time" is a good default -

That makes perfect sense, I did not think about that.
You can close this issue if you want.
