### ISSUE TITLE
Type I and III Sum of Squares for ANCOVA

### ISSUE THREAD

**Issue by DrChesnut** [jasp-stats/jasp-desktop#2763]
## Template for bug reports

* JASP version: 0.9.01
* OS name and version: macOS High Sierra 10.13.6
* Analysis: ANCOVA
* Steps to reproduce: Comparing the Sum of Squares between Type I and Type III models in the ANCOVA. Steps are pretty easy, just include an outcome variable in the dependent variable box, a covariate in the covariates box, and a categorical variable in the fixed factors box. I have attached an example dataset. It was simulated for classroom instruction. You may need to convert to .csv first.
[ChildAchieveEx.xlsx](https://github.com/jasp-stats/jasp-desktop/files/2328575/ChildAchieveEx.xlsx)
DV: recall.post; Covariate: recall.pre; Fixed Factor: prog

Ultimately, the issue / bug arises when examining the sum of squares in the order of entered predictors when the Type I sum of squares option is selected. For example, when running an ANCOVA with only the covariate included in the model and the type I SS selected, it reports an SS of 140.1 and a residual of 392.1. The sum of these two align with the total SS of 532.2. When I include the fixed factor after the covariate and ensure it follows the covariate in the 'model' options, the SS for the covariate is adjusted. The total SS is still correct, but the values for the SS for each of the predictors is not.  In an ANCOVA with just the fixed factor, the SS aligns with that of the ordered ANCOVA model with both the factor and the covariate. It looks like the model is partitioning out the variance attributable to the factor and then examining the remaining variance attributable to the covariate. This should be in the other order.

The total SS effect for both predictors can be obtained by adding together the SS for the factor and the SS for the prog (163.3 + 160.7 = 324), which also corresponds to the value reported in a regression with the factor's dummy coded equivalent. When using the type I SS, the variance attributable to the covariate should be partitioned out before examining the remaining variance attributable to the factor. If reported correctly, the Type I SS should indicate that that the SS shared with the covariate is 140.1 (as shown in the first ANCOVA) and the SS shared with the factor is 324-140.1 = 183.9 (approx 184). This should be the correct SS for the prog after controlling for the the covariate, which I can obtain from the Type III SS model. The one issue with the type III model is that the SS for the covariate is then estimated after controlling for the variance attributable to groups, which is not what I want to report in an ANCOVA model as it doesn't add up to the total SS. I have attached a screenshot showing the issue with the Type I and Type III SS models.

![jasp screen shot](https://user-images.githubusercontent.com/42776298/44733342-02552a00-aaad-11e8-9a1b-e1ba5b2c70c3.jpeg)

**Comment by DrChesnut** [comment]
Sorry for so many posts today, just trying to keep a log of the issues... It seems if I move the DV to the box, the covariate to the box, and then the factor to the box, I can include an interaction in the model that seems to keep the order of the variables correct... This also gives me the correct Type I SS

![interaction involved in model](https://user-images.githubusercontent.com/42776298/44740188-67b21680-aabf-11e8-9db3-6e4744c6105c.jpeg)

The instant I remove that interaction, however, it goes back to the wrong order.. even though the model terms are still in the correct order...

![interaction removed from model](https://user-images.githubusercontent.com/42776298/44740196-6da7f780-aabf-11e8-8dd2-758050b68c30.jpeg)

**Comment by JohnnyDoorn** [comment]
Hi DrChestnut,
Thanks for bringing this to our attention! The order in which the factors/covariates are input does not get taken into account in the current JASP version - it simply inputs the factors first and then the covariate. I was not aware that this might be something that some users would like to see differently, and I understand your motivation. I will look into an option for this - maybe a checkbox somewhere, where you can specify whether you want the covariate included first, and the fixed factors later, or the other way around. Do you think this will solve your problem?
Kind regards,
Johnny

**Comment by DrChesnut** [comment]
Hi Johnny,

Thank you for jumping on this! A check box could work. I also wonder if you could use the features you already have built in, with a little behind the scenes code, to accomplish this. Let me describe..

When I am in the ANCOVA analysis menu, there is a dropdown section titled 'Model'. In this section, I can move included variables between 'Components' and 'Model Terms'. Right now, when I click on variables in the components and move them over to the 'Model Terms' section, they always move over in the same order as they show in the 'Components' section. Would there be a way to code in an order to the move of variables from one box to the next that also translates into the order they are included in the formula? 

To give an example. Let's say I have a list of variables in the 'Components' section. When I select one and click on the arrow, I am indicating that I want it to be first in the 'Model Terms' section. When I select another variable and click on the arrow, I am indicating that I want it to be second in the 'Model Terms' selection. Should I include an interaction, it goes in the order that it was moved over. In running the analysis, the linear formula would then be built from the order of variables in the 'Model Terms' section. 

Does something like this seem feasible? 

Thanks!
Steven

**Comment by JohnnyDoorn** [comment]
Hi Steven,
That's very helpful! My programming contributions for JASP are more on the R-level, while this seems to also pertain to the way JASP reads in input. Maybe @boutinb or @akashrajkn can chime in a bit on how to solve this? When JASP can take the order of input into account, it will probably be a very easy fix to have the underlying R-code respect this order.
Kind regards,
Johnny

**Comment by DrChesnut** [comment]
Johnny,

This sounds like a great idea. How do I / we go about getting them involved in this project?

Steven

**Comment by JohnnyDoorn** [comment]
They are across the corridor from my office, so I'll take it up with them!

**Comment by DrChesnut** [comment]
Thanks, Johnny!
