### ISSUE TITLE
Bug: Distribution plots (descriptives) omit and close up gaps in distribution values

### ISSUE THREAD

**Issue by JimWeinrich** [jasp-stats/jasp-desktop#2767]
I think this is a bug; others might consider it to be a feature request.
[Wanted.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/2342672/Wanted.jasp.zip)

## Template for bug reports
* JASP version: 0.9.0.1 (and most or all previous versions)
* OS name and version: Mac OS X 10.13.4
* Analysis: If a Scale variable has integer values, JASP's distribution plot (Descriptives) will omit bars for any missing integer, and CLOSE UP THE SPACE BETWEEN ADJACENT BARS. This makes it very difficult to spot gaps in data and natural places to dichotomize the data set.
* Steps to reproduce: I'm attaching a JASP file to show distribution plots when:
   * all integers from 1 to 10 are in the variable (first variable)
   * variable only contains values 1, 2, 3, and 6, 7, 8, 9, 10 (second variable)

I don't like this behavior under any circumstances, but I would not consider it a bug if:
   * the behavior does NOT happen when the variable is Scale
   * I would tolerate it ☺ ☺ ☺ ☺ ☺ if it does happen when the variable is Ordinal

Workaround: change one of the integer values to something with a decimal (i.e., change 4 to 4.01). I don't like this because it changes the data and confuses students.

## Template for enhancement requests
* Enhancement: 

Add a checkbox to force the X axis in a distribution plot to include all values from the minimum to the maximum for each individual variable

Add a checkbox to force ALL the X axes in a series of distribution plots to range from the minimum of ALL variables to the maximum of ALL variables (i.e., if the data set consists of 10 Likert scales ranging from 1 to 20, all plots will have X values ranging from 1 to 20, even if the actual ranges of some of them are smaller)

**Comment by vankesteren** [comment]
Hi @JimWeinrich,

Thank you for submitting this issue! It will be fixed with the next release of JASP, there was an earlier issue (#2546) where this came up. I have fixed this in pull request #2746 which is now part of the main program 😄

**Comment by vankesteren** [comment]
![afbeelding](https://user-images.githubusercontent.com/11596858/45020347-07772380-b02f-11e8-810d-3ab1379c375d.png)
