### ISSUE TITLE
Can't open and sync data file (CSV or ODS) with Libreoffice directly from JASP 9.0.1 on Debian Stretch

### ISSUE THREAD

**Issue by 4x1eg** [jasp-stats/jasp-desktop#2777]
- JASP version: 9.0.1 - September 17, 2018, gnu/linux Flatpak
- OS name and version: Debian 9.5 (Stretch)
- Analysis: Can't open and sync data file (CSV or ODS) with Libreoffice directly from JASP 9.0.1 on Debian Stretch
- Steps to reproduce: 1) Open a Data Set with analysis. 2) Double click on a cell

Any ideas why Libreoffice is not opening and editing an ODS or CVS data file with LibreOffice on Debian Stretch 9.5?
Tried different syntaxes for command (in preferences) but to no avail. Although it should work with: "Libreoffice". Libreoffice is associated with CSV and ODS and naturally opens it.
Also, it is the default editor. It always states: "Unable to start the editor: Libreoffice. Please check your editor settings in the preference menu."
On Windows 10 it works fine with LibreOffice.
Any ideas?

**Comment by boutinb** [comment]
Duplicate issue: #2392
