### ISSUE TITLE
 IC95% of the mean difference in Post-Hoc tests' ANOVA

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-desktop#2815]
* Enhancement: to add the  IC95% of the mean difference in Post-Hoc tests' ANOVA. The closest thing is in the “Marginal Means” procedure, but exposes the IC95% of each group.
* Purpose: In order to improve the results' interpretation

![image](https://user-images.githubusercontent.com/29978768/46333555-0ed72000-c621-11e8-8897-80913ecf4a1c.png)

![image](https://user-images.githubusercontent.com/29978768/46333602-362ded00-c621-11e8-9f64-e8d3fce33985.png)

**Comment by AlexanderLyNL** [comment]
Implemented in 0.9.1
