### ISSUE TITLE
Feature request: add "pause updating" button

### ISSUE THREAD

**Issue by jrf1111** [jasp-stats/jasp-desktop#2837]
* Enhancement: add a button that will (temporarily) prevent JASP from updating its calculations
* Purpose: often I have to add several variables to a model, add interaction effects, or make several changes to the settings.  Everytime I make a single change, JASP recalculates the tests, which can use a lot of my CPU.  For example, if I want to change both the location and scale of a prior, JASP reruns the analysis after I make each change. A more problematic example is if I want to add two additional predictors to a Bayesian linear regression.  If I have a large N, that is a lot of unnecessary recalculating between the time I add the first and second predictors. Adding a "pause updating" button would avoid this.  Alternatively, make a setting option so calculations aren't run until after a certain amount of time has past since the last user command/change.

**Comment by AlexanderLyNL** [comment]
Hi jrf1111,

This is a good suggestion. We're working on some structural changes that will address this issue. 

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
I close this, because we do this implicitly already.
