### ISSUE TITLE
Unable to export plots to PDF or EPS

### ISSUE THREAD

**Issue by asribar** [jasp-stats/jasp-desktop#2839]
* JASP version: 0.9.0.1
* OS name and version: MacOS High Sierra
* Analysis: any plot - RM ANOVA, descriptive plots
* Steps to reproduce: export to PDF or EPS... 4 additional "Quartz2" windows will open and  sometimes will display the output, sometimes will not. However those windows cannot be closed, only if main JASP window is closed - otherwise they are labeled by OS as not responding.

I could live with that (just manually close JASP after each plot is exported) - however there is no PDF file exported.
Export to PNG works fine,

![slika zaslona 2018-10-08 u 21 48 01](https://user-images.githubusercontent.com/35798123/46630230-ef218980-cb43-11e8-81bb-083234f955fe.png)

![slika zaslona 2018-10-08 u 21 44 37](https://user-images.githubusercontent.com/35798123/46630082-5db21780-cb43-11e8-8ab2-9490f00788ff.png)

**Comment by AlexanderLyNL** [comment]
Hi @asribar,

This is solved in our newest version. In the meantime, please use our experimental builds please: 

Mac:
https://static.jasp-stats.org/JASP-0.9.1.0-Nightly-03-10-2018.dmg

Windows:
https://static.jasp-stats.org/JASP-0.9.1.0-Setup-Nightly-03-10-2018(64).exe
https://static.jasp-stats.org/JASP-0.9.1.0-Setup-Nightly-03-10-2018(32).exe

Please refresh before saving. 

Cheers,
