### ISSUE TITLE
Bugs in Plotting Correlation Matrix

### ISSUE THREAD

**Issue by luckyluuuk** [jasp-stats/jasp-desktop#2843]
Jasp 0.9.0.1
Windows 10

I try to plot a correlation matrix and this error pops up:
![grafik](https://user-images.githubusercontent.com/44018396/46720326-884dbe80-cc70-11e8-9bf0-3c95a0bf7f91.png)

What are 'ylim' values?
What is the problem?

I am thankful for every information.
Cheers 
Lukas

**Comment by AlexanderLyNL** [comment]
Hi Lukas,

Can you please add the jasp file to this thread in a zip? 

Cheers,
Alexander

**Comment by luckyluuuk** [comment]
Hi Alexander,
thank you for the answer. I realized, the problem doesn´t occure, when i only open one file.

So i am good.

Cheers,
Lukas

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: AlexanderLyNL <notifications@github.com>
Gesendet: Wednesday, October 10, 2018 9:06:35 PM
An: jasp-stats/jasp-desktop
Cc: luckyluuuk; Author
Betreff: Re: [jasp-stats/jasp-desktop] Bugs in Plotting Correlation Matrix (#2843)


Hi Lukas,

Can you please add the jasp file to this thread in a zip?

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
I consider this solved then. Please reopen if the problem resurfaces.
