### ISSUE TITLE
bug report : simple main effect analysis in repeated ANOVA terminated unexpectedly

### ISSUE THREAD

**Issue by lisonfanuel** [jasp-stats/jasp-desktop#2845]
Hi, 

* JASP version:  0.9.0.1 
* OS name and version: windows 10 64 bits
* Analysis: repeated measure ANOVA
* Steps to reproduce: 
I was trying to compute simple main effects for a three way ANOVA (3 factors, 2 levels each) and the following message appeared : 

"""
This analysis terminated unexpectedly.

Error in `[.data.frame`(x, r, vars, drop = drop): undefined columns selected

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.rmAnovaSimpleEffects(dataset, options, perform, fullModel, results[['withinSubjectsEffects']], results[['betweenSubjectsEffects']], status, singular, stateSimpleEffects)

.rmAnovaModel(cbind(subDataset, subCovDataset), subOptions, status = status)

.shortToLong(dataset, options$repeatedMeasuresFactors, options$repeatedMeasuresCells, c(options$betweenSubjectFactors, options$covariates))

subset(dataset, select = .v(rm.vars))

subset.data.frame(dataset, select = .v(rm.vars))

x[r, vars, drop = drop]

`[.data.frame`(x, r, vars, drop = drop)

stop('undefined columns selected')
"""

Suprisingly, this occured only in one given analysis: I was able to compute the same simple main effects using other variables.
I attach the JASP file with (1) the analysis that did not work and (2) the same analyses using other variables that worked.

Hope this is enough information to see what's the problem here, please let me know if it's not. 

Thank you so much for your help, 

Best, 

Lison

[Memory task_filtered & unfiltered data + dprime calcul.zip](https://github.com/jasp-stats/jasp-desktop/files/2464423/Memory.task_filtered.unfiltered.data.%2B.dprime.calcul.zip)

**Comment by lisonfanuel** [comment]
I eventually found out what the problem was: two columns containing the exact same values. Sorry for asking questions and answering them right after, but hope this could help in the future. 
Best, 
Lison

**Comment by AlexanderLyNL** [comment]
Hi lisonfanuel,

Thanks for figuring this out and making us aware of this. 

Cheers,
Alexander
