### ISSUE TITLE
B IS T-Test: error with a particular analysis

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#285]
![screen shot 2015-02-13 at 2 15 01 pm](https://cloud.githubusercontent.com/assets/3240247/6187750/dd439d68-b38a-11e4-97eb-56c120ee3a9f.png)
![screen shot 2015-02-13 at 2 14 54 pm](https://cloud.githubusercontent.com/assets/3240247/6187751/dd468780-b38a-11e4-9c71-fce7df3c15b4.png)

**Comment by quentingronau** [comment]
Should be fixed with my latest pull request.
