### ISSUE TITLE
Error in parse(text = x, keep.source = FALSE): :1:18: unexpected symbol

### ISSUE THREAD

**Issue by yuttin1i2o** [jasp-stats/jasp-desktop#2853]
## Template for bug reports

When I set "Placebo group HbA1c" as covariate, then I see this error message. 
Similar error appears when I set "HbA1c baseline (NGSP)" as covariate.

[181012_JASP.zip](https://github.com/jasp-stats/jasp-desktop/files/2473404/181012_JASP.zip)

* JASP version: 0.9.1.0
* OS name and version: WIndows 10 Home
* Analysis: Meta Analysis
* Steps to reproduce: 
![image](https://user-images.githubusercontent.com/44092454/46874689-b996dc00-ce74-11e8-9c82-a34064dadeaa.png)
![image](https://user-images.githubusercontent.com/44092454/46874821-0975a300-ce75-11e8-89cf-8710c473e86f.png)
## Template for enhancement requests
 
* Enhancement: I want to know how to solve this problem.
* Purpose: I want to go through my analysis.

**Comment by AlexanderLyNL** [comment]
Hi yuttin1i2o,

The problem can be solved by removing the spaces, that is, changing the header to PlaceboGroupHbA1cChange. For some reason the meta-analysis is implemented differently then our other analyses and therefore not robust to special characters. Sorry about this. I'll make sure this gets addressed. Can you confirm that the analysis runs smoothly, if you remove the spaces in the header?

Cheers,
Alexander

**Comment by yuttin1i2o** [comment]
Thank you so much. Yes, it solved the problem.
