### ISSUE TITLE
This analysis terminated unexpectedly.

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-desktop#2861]
* JASP version: 0.9.1
* OS name and version: Mac OS El Capitan 10.11.6
* Analysis: Descriptive Statistics
* Steps to reproduce: Trying to show whatever plot

![captura de pantalla 2018-10-17 a las 21 10 48](https://user-images.githubusercontent.com/29978768/47110488-44028580-d251-11e8-855f-489b662a5f72.png)

[5 Single Sample t Data.zip](https://github.com/jasp-stats/jasp-desktop/files/2488874/5.Single.Sample.t.Data.zip)

**Comment by boutinb** [comment]
Hi @vicenteinefo Did you install the right El Capitan JASP version?

**Comment by boutinb** [comment]
Hi @vicenteinefo I have just checked it and saw that there was a mistake in a El Capitan JASP version. I have just a new version version: https://static.jasp-stats.org/JASP-0.9.1.0-XCode8.2.dmg
Can you try it, and tell me if it solves the problem?
Thanks, Bruno

**Comment by vicenteinefo** [comment]
I have just installed this version and it seems to work well. Thanks

**Comment by AlexanderLyNL** [comment]
Thanks for reporting this and for the feedback!
