### ISSUE TITLE
B PS T-Test: error message: can we improve on "Too few posterior samples ..."

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#288]
@EJWagenmakers 

can we improve on this? it's not very clear what the issue is, or how the user can fix it (perhaps the user can't fix it?)

![screen shot 2015-02-13 at 3 23 33 pm](https://cloud.githubusercontent.com/assets/3240247/6188731/7e6e3726-b394-11e4-97b5-b2df16df5b2a.png)

**Comment by EJWagenmakers** [comment]
So the BF is massively in favor of H+. This probably means zero samples
with a negative value. Are you plotting the posterior under H-?
EJ

**Comment by jonathon-love** [comment]
@quentingronau, could you clarify? cheers.

**Comment by quentingronau** [comment]
In case of an order restricted test (H- or H+), I take the posterior samples from the unrestricted case, and  renormalize the posterior for the interval of interest, i.e., (-Inf,0] or [0, Inf), such that the area under the curve is 1. To achieve this, I use the proportion of posterior samples that are in the interval of interest. As E.J. mentioned, if zero of the 10,000 posterior samples are in that interval this procedure does not work. This can happen when the evidence is very strong in favor of the not tested order-restricted hypothesis (H- or H+). So in this case the user cannot fix the issue.

**Comment by EJWagenmakers** [comment]
What I was confused about re. the screenshot is that BF_+0 is huge; so for
the plot to give an error the test it depicts must be BF_-0?

For now we can leave this as is (but a more informative error message could
be a good idea). In the future, what we can do is use a normal
approximation -- assume the posterior is normally distributed with a mean
and a variance equal to that of the samples. Then you can base the
renormalization factor and the plot on that normal distribution. The user
should be made aware that this is happening; maybe it can even be an option
that the user can tick.

Cheers,
EJ

**Comment by quentingronau** [comment]
I found this a little bit confusing as well, but the displayed BF is BF_+0 computed with the BayesFactor package.
I just tested it in R with the BayesFactor package and the results are the same as in JASP: Both, H_-0 and (!) H_+0 yield strong evidence in favor of the tested hypothesis. This seems peculiar to me (might be an error in the BayesFactor package?), but please correct me if I overlook something obvious.

> # Group 1 > Group 2
> ttestBF(d$difficulty, d$ssd, paired=TRUE, r=1, nullInterval= c(-Inf,0))
Bayes factor analysis
--------------
[1] Alt., r=1 -Inf<d<0    : 4.981505e+100 ±0%
[2] Alt., r=1 !(-Inf<d<0) : 1.68513e+89   ±0%

Against denominator:
  Null, mu = 0 
---
Bayes factor type: BFoneSample, JZS

> 
> # Group 1 < Group 2
> ttestBF(d$difficulty, d$ssd, paired=TRUE, r=1, nullInterval= c(0,Inf))
Bayes factor analysis
--------------
[1] Alt., r=1 0<d<Inf    : 1.68513e+89   ±0%
[2] Alt., r=1 !(0<d<Inf) : 4.981505e+100 ±0%

Against denominator:
  Null, mu = 0 
---
Bayes factor type: BFoneSample, JZS

Cheers,
Quentin

**Comment by EJWagenmakers** [comment]
Hi Richard,

See below. For the same data, the BF is strongly in favor other each of two
directional hypotheses (compared to the null). That should never happen.
Quentin, can you send Richard the data so he can check?

Cheers,
E.J.

**Comment by jonathon-love** [comment]
hey @EJWagenmakers, you can call someones attention to a discussion by typeing @ followed by their github user name. so we can invite rich with @richarddmorey.

**Comment by EJWagenmakers** [comment]
Yeah, could be a problem with the integration of a very spiked posterior.
Send me the data and I'll check.

On Saturday, February 14, 2015, Eric-Jan Wagenmakers <
ej.wagenmakers@gmail.com> wrote:

> Hi Richard,
>
> See below. For the same data, the BF is strongly in favor other each of
> two directional hypotheses (compared to the null). That should never
> happen. Quentin, can you send Richard the data so he can check?
>
> Cheers,
> E.J.
>
>
> On Sat, Feb 14, 2015 at 12:22 PM, quentingronau <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I found this a little bit confusing as well, but the displayed BF is
>> BF_+0 computed with the BayesFactor package.
>> I just tested it in R with the BayesFactor package and the results are
>> the same as in JASP: Both, H_-0 and (!) H_+0 yield strong evidence in favor
>> of the tested hypothesis. This seems peculiar to me (might be an error in
>> the BayesFactor package?), but please correct me if I overlook something
>> obvious.
>>
>> Group 1 > Group 2
>>
>> ttestBF(d$difficulty, d$ssd, paired=TRUE, r=1, nullInterval= c(-Inf,0))
>> Bayes factor analysis
>>
>> [1] Alt., r=1 -Inf<d<0 : 4.981505e+100 ±0%
>> [2] Alt., r=1 !(-Inf<d<0) : 1.68513e+89 ±0%
>>
>> Against denominator:
>>  Null, mu = 0
>>
>> Bayes factor type: BFoneSample, JZS
>>
>> Group 1 < Group 2
>>
>> ttestBF(d$difficulty, d$ssd, paired=TRUE, r=1, nullInterval= c(0,Inf))
>> Bayes factor analysis
>>
>> [1] Alt., r=1 0<d<Inf : 1.68513e+89 ±0%
>> [2] Alt., r=1 !(0<d<Inf) : 4.981505e+100 ±0%
>>
>> Against denominator:
>>  Null, mu = 0
>>
>> Bayes factor type: BFoneSample, JZS
>>
>> Cheers,
>> Quentin
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jasp-stats/jasp-desktop/issues/288#issuecomment-74371373>
>> .
>>
>
>

-- 
Richard D. Morey
Senior Lecturer
School of Psychology, Cardiff University
http://psych.cf.ac.uk/morey

**Comment by quentingronau** [comment]
Hi Richard and E.J.,

I have sent you the data and the R code.

Cheers,
Quentin

**Comment by richarddmorey** [comment]
hmm, my post got listed as EJ above. But...here's more info about this. This turns out to be the result of some weirdness in R (due to the extreme t statistic). In order to compute the Bayes factor, BayesFactor integrates the likelihood times the prior. Here is what the (log) likelihood looks like (using values from the data you sent):

    N = 336
    t =  -32.0557370318469
    df = N - 1
    rscale = 1
    
    ## Plot the likelihood (exp of this, times prior, will be integrated)
    dd = seq(1,3,len=1000)
    yy = dt(t,df,ncp=dd*sqrt(N),log=TRUE)
    plot(dd,yy,ty='l')

Definitely not a well-behaved function, but I'm not sure I would expect it to be with values that extreme. The question is how to work around it, and whether to submit a bug report to the R team.

**Comment by EJWagenmakers** [comment]
Woh. Definitely not well behaved. But no function should look like this,
even when t is extreme
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by richarddmorey** [comment]
Well, it's numerical instability. We're pushing the function to its (numerical) limit, and it is failing, clearly. Perhaps I can use a Laplace approximation instead in these extreme cases.

**Comment by jonathon-love** [comment]
> hmm, my post got listed as EJ above

yes, i think EJ forwarded the "reply-to" address he received from github to you.

**Comment by jonathon-love** [comment]
So, @EJWagenmakers, @quentingronau, returning to our original question.

&iquest;Could the error be something like:

Bayes factor is too large to plot

?

trying to connect it to something the user will actually understand.

**Comment by EJWagenmakers** [comment]
Yes that works, although it is not the Bayes factor that is being plotted.
So maybe something like "The Bayes factor is too large: results cannot be
plotted"
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
At the moment we phrase it the other way around:

`Plotting is not possible: the Bayes factor is too large`

**Comment by EJWagenmakers** [comment]
OK

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by quentingronau** [comment]
Isn't the issue when there are no samples for example in the interval (-Inf,0] which prevents plotting that BF_-0 which is what the user has selected, is probably very small?

**Comment by EJWagenmakers** [comment]
yes, that's the issue

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by richarddmorey** [comment]
This will be fixed via an approximation in the next version of BayesFactor.
