### ISSUE TITLE
Decimal place oddity

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-desktop#2889]
Hi folks
I was just playing around with some descriptive data for students and noticed that the values of SE kurtosis default to 16 decimal places.  Changing this in preferences has no effect.

Cheers
Mark

JASP 0.9.1
Windows 10

![dp error](https://user-images.githubusercontent.com/39003008/47848857-8e464380-ddc7-11e8-920c-02b941fe0ac4.PNG)

**Comment by vandenman** [comment]
line 185-186 of descriptives is:
```  
if (options$kurtosis) {           
stats$addColumnInfo(name="Kurtosis",                    type="number", format="sf:4")
stats$addColumnInfo(name="Std. Error of Kurtosis",      type="string", format="sf:4") 
}
```
clearly, type should be number not string. I'll open a PR later today
