### ISSUE TITLE
B 1S T-Test: tweak to error message: Bayes factor is zero?

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#290]
@EJWagenmakers, @quentingronau,

could this be "Bayes factor is zero" ?

![screen shot 2015-02-14 at 3 06 16 pm](https://cloud.githubusercontent.com/assets/3240247/6199826/18e350cc-b45b-11e4-98bb-ad943b4e2f06.png)

**Comment by EJWagenmakers** [comment]
Can't we have the same message as before (about the BF being too large?). I
know that internally it's a different issue, but it does not matter from a
user's perspective.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
> Can't we have the same message as before (about the BF being too large?)

though here the issue is that the BF is too small.

so:

`Plotting is not possible: the Bayes factor is too small`

but if the only *too small* Bayes factor is zero, then i'd favour:

`Plotting is not possible: the Bayes factor is zero`

**Comment by EJWagenmakers** [comment]
It can never be exactly zero.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
righto
