### ISSUE TITLE
[Solved] JASP difficulty with install/open with Mac Mojave OS. A: Right click open twice upon first start-up

### ISSUE THREAD

**Issue by schoenrade** [jasp-stats/jasp-desktop#3005]
When I downloaded JASP 0.9.2  onto a mac with Mojave OS 10.14.2, it would not open, even with the usual ' control click' (to override security' procedure).   It just disappeared. I panicked because external documentation (e.g https://www.macstats.org/macintosh/mojave.html)  seemed to suggest JASP might not work  with Mojave. 

 HOWEVER, if one attempts to open, it disappears, and then  a second open attempt is made (using the control-click procedure), it will then open.  Apparently, on the first attempt, a rule is being created that then allows it to open 

After I quit panicking, our IT department showed me  the step described above.  I think it is in your documentation, so I may just not have read thoroughly enough.  Just thought this info might help someone else in the same situation. Thanks!

**Comment by AlexanderLyNL** [comment]
Hi schoenrade,

Thanks for reporting this. We'll have a look into this. Otherwise, JASP is working fine isn't it? 

Cheers,
Alexander

**Comment by schoenrade** [comment]
Thanks Alexander,

   Much more than fine!  I am most grateful to you and all of the JASP crew.

Joy,
schoenrade
