### ISSUE TITLE
Frequency plots Descriptives

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#311]
It seems strange to me that the y-axis on the Plots show non-integer values.

![screen shot 2015-02-16 at 16 49 51](https://cloud.githubusercontent.com/assets/8667548/6214775/65dd7f3c-b5fb-11e4-9bc0-bd1384b73997.png)

**Comment by jonathon-love** [comment]
(i don't really care)

how do @EJWagenmakers and @quentingronau feel about this?

**Comment by quentingronau** [comment]
I agree that non-integer values are not reasonable. I fixed it with my latest pull request.

**Comment by EJWagenmakers** [comment]
Agreed. Good to have it fixed.
