### ISSUE TITLE
A problem with grouping in Independent samples T-test

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#312]
When using the dataset:
"x","y","z"
0,0,-0.901669347330913
0,1,-0.589648072383757
1,0,-1.62268823533667
1,1,1.99376489186951

Using x to group gives:
![screen shot 2015-02-16 at 17 00 39](https://cloud.githubusercontent.com/assets/8667548/6214965/dee28976-b5fc-11e4-93a8-697482780cdd.png)

Yet, using y to group gives:
![screen shot 2015-02-16 at 17 01 46](https://cloud.githubusercontent.com/assets/8667548/6214988/01a0ad1c-b5fd-11e4-87b8-ef4c46929bff.png)

**Comment by jonathon-love** [comment]
Doesn't seem to be reproducible; only affects marsman's build, and i don't think anyone elses.
