### ISSUE TITLE
B Crosstabs: plots look blurred

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#322]
Hi Jonathon,

I have a basic implementation for the crosstabs plot, but they look blurry. I thought it is due to
the width and height specified in the cpp file,

![optionscrosstabs](https://cloud.githubusercontent.com/assets/8697436/6233326/47509194-b6d2-11e4-8776-ec3c9f384f84.png)

 so I changed that to be equal to the t test (width= 320, height= 240), but it still looks blurred.

![examplecrosstabs](https://cloud.githubusercontent.com/assets/8697436/6233311/338ce964-b6d2-11e4-9df5-2be250d08df6.png)

Do you have a suggestion what the reason might be?

**Comment by jonathon-love** [comment]
so there's three places where you specify image height and width, and i guess these all should match.

1. the .cpp file
2. the .beginSaveImage() call
3. the in the list that represents the plot

these all match?

**Comment by quentingronau** [comment]
Oh, that's embarrassing, I forget to specify it in the list. It works now, thanks.
