### ISSUE TITLE
Implement two-tiered heading: ala Crosstabs

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#324]
Hi,

I recognized that for the B crosstabs, the column variable name is not displayed.

![namescrosstabs](https://cloud.githubusercontent.com/assets/8697436/6246751/9c9d206e-b76c-11e4-978d-383528da829e.png)

In SPSS it looks like this:

![namescrosstabsspss](https://cloud.githubusercontent.com/assets/8697436/6246754/a783fd4a-b76c-11e4-8e47-a4f5da5b41a9.png)

**Comment by jonathon-love** [comment]
yeah, we haven't implemented this two tiered heading thing, but you're right, it would be nice to have.
