### ISSUE TITLE
One sided issue in correlation test

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#325]
@AlexanderLyNL 
Suppose a correlation is really high, like .99. Then BF+0 > BF10 >> 1. However, BF-0 >> 1 too! This should not happen. The same problem occurs in the t-test BayesFactor package as well. In an earlier discussion, Richard pointed out this is due to integrating a highly peaked posterior in R. Still, it is an issue to be aware of, and it would be nice to see it fixed somehow. 

![image](https://cloud.githubusercontent.com/assets/8603015/6246929/7d6c8e58-b76e-11e4-95a9-8334b3522574.png)
E.J.

**Comment by EJWagenmakers** [comment]
@AlexanderLyNL It would be nice to have this fixed prior to the 0.6 release. No pressure :-)

**Comment by AlexanderLyNL** [comment]
When will it be released? I might start five minutes before, just to see how fast we can work on it.

**Comment by EJWagenmakers** [comment]
:-) No deadlines. Let's just say it's the JASP correlation issue that needs most attention now.

**Comment by AlexanderLyNL** [comment]
I can’t work without pressure

**Comment by jonathon-love** [comment]
@AlexanderLyNL's fix is merged!

**Comment by EJWagenmakers** [comment]
Awesome. Great work.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
