### ISSUE TITLE
What should basic table headings be: Std. Deviation vs SD

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#330]
hi @EJWagenmakers,

i've just been going over some of the basic tests, and found them inconsistent with respect to column headings.

i.e.

Std. Deviation   vs    SD
Std. Err. Mean   vs   SE

SPSS is the former, i think i prefer the latter, but don't really care. do you have feelings either way?

**Comment by EJWagenmakers** [comment]
I am indifferent, as long as we're consistent.
Actually, I might have a slight preference for SD and SE.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
