### ISSUE TITLE
Bayesian Paired Sample T-Test Descriptives Table has varying decimal places.

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#334]
See the reported means in the Descriptives Table below (includes dataset):

![screen shot 2015-02-20 at 13 10 50](https://cloud.githubusercontent.com/assets/8667548/6285891/94355d56-b901-11e4-9ee7-9ec844e4cbec.png)

**Comment by jonathon-love** [comment]
Fixed
