### ISSUE TITLE
An inconsistency in reporting Bayesian T-tests when error occurs

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#347]
When I run a Bayesian Independent or Paired Samples T-test with dependent *z* containing an infinity, the BF is reported as NaN with a nice note that its not defined and why.

![screen shot 2015-02-20 at 15 45 44](https://cloud.githubusercontent.com/assets/8667548/6288161/45f649aa-b917-11e4-8f57-78241a6a87cd.png)

However, when I run a One-sample T-test, the BF factor is given as blank (with the same nice note):

![screen shot 2015-02-20 at 15 48 28](https://cloud.githubusercontent.com/assets/8667548/6288182/6d8bab54-b917-11e4-8775-e65cf990c4af.png)

I think that the BF should be reported in the same way in the different analyses.

**Comment by jonathon-love** [comment]
hey @quentingronau, this worked in 0.5, could you take a look? (The IS T-Test is correct)
