### ISSUE TITLE
Proposed example data file meta information

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#365]
hey @EJWagenmakers,

for the meta information for the example data files, @doramatzke and i briefly discussed it, what about the following?:

    Title: Beer Tasting
    Description: A Beer Tasting Data Set
    Source: Bob's Brewing Survey

    Tags:
      - Descriptives
      - Correlation

    Variables:

      - Name: Brewery
        Type: Nominal
        Description: The brewery the beer is from
    
      - Name: Beer
        Type: Nominal
        Description: The name of the beer
    
      - Name: Average Rating
        Type: Continuous
        Description: The average rating as given by a panel of experts

tags is a list of analyses which might be interesting to do on the dataset.

is there anything you think we should add?

**Comment by EJWagenmakers** [comment]
I think this is fine. Do we need an optional "hypothesis of interest"
field? For some studies, this may be pretty unclear :-)

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
