### ISSUE TITLE
Terminology: What do we refer to variable types as?

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#366]
I've been referring to the variable types as:

 - Nominal
 - Ordinal
 - Continuous

Just because I like these (probably because these were what i was first taught), but there are other options:

SPSS uses:

 - Nominal
 - Ordinal
 - Scale

R uses:

 - Factor
 - Ordered factor
 - Numeric (?)

**Comment by EJWagenmakers** [comment]
This is tricky. The original scales proposed by Stevens consist of 4
categories (http://en.wikipedia.org/wiki/Level_of_measurement):

nominal
ordinal
interval
ratio

So we want a simple name for both interval and ratio.
Quick decision: stick with continuous
E.J.


********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
