### ISSUE TITLE
Changing "Crosstabs" to "Contingency Tables"

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#367]
Hi @Tahiraj,

We're going to change the names of the "Crosstabs" to "Contingency Tables"

Sound good to you?
If you're not in today, I'm happy to make the changes.

**Comment by Tahiraj** [comment]
I do think it is good to name cross tabs to Contingency table,  as it is more frequent than cross tabs. I am working from home because my children have vacation. Tomorrow for I’ll come for some hours.

I am trying to fix the issues #355 and #342.

**Comment by jonathon-love** [comment]
do you want to change the table names and analysis heading too? or would you prefer than i do it?

**Comment by Tahiraj** [comment]
I’ll do it.

**Comment by Tahiraj** [comment]
I think we don’t need to change the functions names!

**Comment by jonathon-love** [comment]
yup :)

we'll leave the function names for now, we can update them later

**Comment by Tahiraj** [comment]
issue #367 done

**Comment by jonathon-love** [comment]
merged!
