### ISSUE TITLE
Add normality tests

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#375]
We should add normality tests to analyses

**Comment by raviselker** [comment]
I added normality tests for all the classical T-Tests. Do we also want normality tests for the classical ANOVA's?

**Comment by jonathon-love** [comment]
i expect so. should this be called "test for non-normality" or some such?

**Comment by raviselker** [comment]
In ANOVA's you are more interested in normality of the residuals, something you check with the qqplot. So, I don't think we need to do the same normality checks as for the t-tests. Also, I think it's more clear if we use "test for normality" -- H0 actually represents the case where the data are normal so technically you are testing the hypothesis of normality.

**Comment by jonathon-love** [comment]
but you can't test the null.

**Comment by raviselker** [comment]
You can test the null, you just cannot accept the null.

**Comment by raviselker** [comment]
Btw, wikipedia also calls it a "test of normality": http://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test

**Comment by jonathon-love** [comment]
yup, but i think that if we call it a test for non-normality, and we include shapiro-wilk in it's name (probably in backets), then people won't be confused; and it makes the subtle but correct point that it can't tell you if the data is normal.

**Comment by raviselker** [comment]
We settled to do it my way in issue #515.
