### ISSUE TITLE
B T-Tests: Add support for Log(BF) Bayes factor option

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#384]
hey @quentingronau,

we're now adding a Log(BF) option to all of our Bayesian analyses. the UI is implemented and waiting!

no rush, 0.7 is not for at least 3 weeks

**Comment by quentingronau** [comment]
Hi @jonathon-love , @EJWagenmakers , 

I can implement this for the t test tables, but I am not completely sure how to handle it in the plots.
I could of course change the displayed BFs next to the probability wheel and in the legend, but for the BF robustness check plot and the sequential plot I use a special y-axis scaling and I am not completely sure what the best way would be to adjust it to log BFs. At the moment I already plot log BFs but use the "normal" numbers to label the y-axis which nicely match Jeffreys' evidence labels. I could label the y-axis log(1/3), log(1), log(3), ..., but if I switch to displaying log BFs at the top of the plot, this would not match intuitively, I think. Maybe you have a good suggestion?

![robustnessplot](https://cloud.githubusercontent.com/assets/8697436/6414102/5999ac4e-be95-11e4-9734-fb535258f7fd.png)

**Comment by EJWagenmakers** [comment]
Yeah, this is an issue.
This is a lot of work and additional thought for a minor change that was
never a top priority. There are more important things we need to fix right
now. So I think that for now, we should simply not change the plots.

We can revisit this issue again after finishing the correlation plots, the
sensitivity plots, and the one-sided coherency issue.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
i think the plots can remain the same. the main use of the Log(BF) is to make is easy to compare a table of BFs. we don't change the plots between BF10, and BF01, so let's not change it for these either.

**Comment by jonathon-love** [comment]
Done!
