### ISSUE TITLE
Feature request: Repeated measures general linear model

### ISSUE THREAD

**Issue by ojr23** [jasp-stats/jasp-desktop#389]
Per discussion on twitter! Not sure if this should be a pull request instead (github naive!).

**Comment by jonathon-love** [comment]
this is good! maybe make a bit of a case for it. why you think it's important (do a lot of people use it?), etc.

**Comment by ojr23** [comment]
I personally really like the flexibility of how RM GLM implemented in SPSS. Allows a mix of within and between subject factors. Can build simple and v complex models. It tends to be my goto for the sorts of designs I use. Can't speak for everyone, but can say it is very commonly used in all labs I've ever worked in!

**Comment by jonathon-love** [comment]
So in SPSS you can select the RM ANOVA via:

  Analyse -> General Linear Model -> Repeated Measures ...

In JASP, you access the equivalent functionality via:

   ANOVA -> Repeated Measures ANOVA

The 0.6 release does not provide covariates, but 0.7 will.

Is that what you need?

**Comment by ojr23** [comment]
Oh yes - now I see! Yes. Thats actually exactly what im looking for! I
didn't quite understand how the 'Factors' input box worked when I first
looked over it. Perfect.

And yes, the only other thing would be covariates - ill look forward to 0.7!

**Comment by jonathon-love** [comment]
Great!
