### ISSUE TITLE
Feature request - scale reliability (cronbach's alpha)

### ISSUE THREAD

**Issue by denohora** [jasp-stats/jasp-desktop#397]
Hi JASP,

This is a really impressive tool.  We use SPSS for our undergraduate psychology classes and JASP provides an interesting alternative.  One feature that we consistently use that is not currently supplied is to run scale reliability analyses (e.g., cronbach's alpha). Without this feature, we could not adopt JASP as our main tool.

Thanks for your work on this to date and best of luck combating spss' dominance!

Denis

**Comment by jonathon-love** [comment]
yup, great suggestion! we've been considering this.

cheers

**Comment by cstangor** [comment]
We are in the same situation as Denis here in Psychology at the University of Maryland. Without a cronbach alpha subprogram we cannot leave SPSS. These statistics are simple to calculate and would be useful for our students.  Thanks.

**Comment by raviselker** [comment]
Thank you for your feedback. We plan to have this analysis in the next release. Are there specific statistics for scale reliability that are essential when using it in statistics courses?

For now I added the following scale statistics:
- Cronbach's alpha
- Gutmanns lambda six
- Cronbach's alpha if item is omitted
- Gutmanns lambda six if item is omitted
- Item-Total Correlation

**Comment by nuskcalb** [comment]
Great news!

What about a measure of reliability for dichotomous variables? Not sure which one would be better, though. Maybe:
-  Kuder-Richardson Reliability Coefficients KR20

"The KR20 is a special case of Cronbach's Alpha in which the items are binary variables (usually scored as 0 or 1)."
(From: http://www-01.ibm.com/support/docview.wss?uid=swg21476088)

**Comment by cstangor** [comment]
Perfect!  Could put item means and stds but not essential.

Charles Stangor

**Comment by denohora** [comment]
This is fantastic news!  Thanks!

Denis

**Comment by lirabenjamin** [comment]
Exploratory Factor Analysis or Principal Components Analysis would also be great. Ideally based on polychoric correlations. With orthogonal and oblique rotations.

When is the next release scheduled for? I am preparing a workshop and would love to use JASP, but part of the course objectives is reliability and validity analyses.

**Comment by boutinb** [comment]
This should be released end of august including Exploratory Factor Analysis or Principal Components Analysis.
