### ISSUE TITLE
ANCOVA: Add "lsmeans" and "estimability" package to R bundle

### ISSUE THREAD

**Issue by raviselker** [jasp-stats/jasp-desktop#398]
I need these packages to compute the marginal means.

**Comment by jonathon-love** [comment]
Requires dependencies zoo, TH.data, sandwich, multcomp

**Comment by jonathon-love** [comment]
... and estimability

**Comment by jonathon-love** [comment]
here 'tis

[https://static.jasp-stats.org/development/R OSX for JASP (2015-02-27).zip](https://static.jasp-stats.org/development/R OSX for JASP (2015-02-27).zip)
