### ISSUE TITLE
Boot up Failure

### ISSUE THREAD

**Issue by jcawood** [jasp-stats/jasp-desktop#401]
Dowloaded 0.6 version to a Windows 7 Professional computer with 4GB of memory.  Installed it and when I started, the opening screen would come up for 5-10 seconds and then disappear.  All buttons were non-functional (e.g. options, etc.)

**Comment by jonathon-love** [comment]
Hi, thanks for your report.

During the first 5 - 10 seconds that it is visible, are you able to select the 'File' tab, or open a data file?

And when it disappears, it doesn't produce an error message?

Could you also let us know whether you are using the 32 or 64-bit version of JASP, and whether you are running a 32 or 64-bit version of windows?

lastly, do you have RStudio or R installed on your machine?

with thanks

jonathon

**Comment by jcawood** [comment]
Jonathon,
        I am using the 32 bit version and I cannot select the File tab
        and no error message appears.
        I also do not have RStudio or R installed on the machine.
        Best,
        Jim
        
      
    On 3/1/2015 3:02 PM, Jonathon Love
      wrote:
    
    
      Hi, thanks for your report.
      During the first 5 - 10 seconds that it is visible, are you
        able to select the 'File' tab, or open a data file?
      And when it disappears, it doesn't produce an error message?
      Could you also let us know whether you are using the 32 or
        64-bit version of JASP, and whether you are running a 32 or
        64-bit version of windows?
      lastly, do you have RStudio or R installed on your machine?
      with thanks
      jonathon
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
James S. Cawood,CPP,PCI,PSP
Factor One®
P.O. Box 1772
San Leandro, CA 94577
Phone: 510.352.8660
This E-mail (including attachments) is covered by the Electronic
Communications Privacy Act, 18 U.S.C. §2510-2521, is confidential and may be legally privileged. The contents of this e-mail message, including any attachments, are intended solely for the use of the person or entity to whom the e-mail was addressed. It contains information that may be protected by the attorney-client privilege, work-product doctrine, or other privileges, and may be restricted from disclosure by applicable state and federal law. If you are not the intended recipient of this message, be advised that any dissemination, distribution, or use of the contents of this message is strictly prohibited. If you received this e-mail message in error, please contact the sender by reply e-mail or phone. Please also permanently delete all copies of the original e-mail and any attached documentation. Thank you for your understanding and cooperation.

**Comment by jonathon-love** [comment]
hmm, this is peculiar. i've not seen this particular issue before.

how would you feel about me sending you a special version of JASP, you install it, see if it fixes the problem; i might get it to generate some debugging information too.

it might be obvious and easy to fix, or i might need to send you a few versions in narrowing down the issue.

how would you feel about participating in this process?

with thanks

jonathon

**Comment by jcawood** [comment]
Jonathon,
        I would be happy to help, but go in for some surgery tomorrow,
        so it might be a few days until I can get to this.
        Best,
        Jim
      
    On 3/1/2015 11:41 PM, Jonathon Love
      wrote:
    
    
      hmm, this is peculiar. i've not seen this particular issue
        before.
      how would you feel about me sending you a special version of
        JASP, you install it, see if it fixes the problem; i might get
        it to generate some debugging information too.
      it might be obvious and easy to fix, or i might need to send
        you a few versions in narrowing down the issue.
      how would you feel about participating in this process?
      with thanks
      jonathon
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
James S. Cawood,CPP,PCI,PSP
Factor One®
P.O. Box 1772
San Leandro, CA 94577
Phone: 510.352.8660
This E-mail (including attachments) is covered by the Electronic
Communications Privacy Act, 18 U.S.C. §2510-2521, is confidential and may be legally privileged. The contents of this e-mail message, including any attachments, are intended solely for the use of the person or entity to whom the e-mail was addressed. It contains information that may be protected by the attorney-client privilege, work-product doctrine, or other privileges, and may be restricted from disclosure by applicable state and federal law. If you are not the intended recipient of this message, be advised that any dissemination, distribution, or use of the contents of this message is strictly prohibited. If you received this e-mail message in error, please contact the sender by reply e-mail or phone. Please also permanently delete all copies of the original e-mail and any attached documentation. Thank you for your understanding and cooperation.

**Comment by jonathon-love** [comment]
> I would be happy to help, but go in for some surgery tomorrow, so it might be a few days until I can get to this.

thanks a lot jim! i'll have a version waiting for you when you come out :)

all the best with the surgery.

**Comment by jcawood** [comment]
Jonathon,
    If you have the new version ready to try, I am able.
        Best,
        Jim
    
    On 3/2/2015 7:08 AM, Jonathon Love
      wrote:
    
    
      
        I would be happy to help, but go in for some surgery
          tomorrow, so it might be a few days until I can get to this.
      
      thanks a lot jim! i'll have a version waiting for you when you
        come out :)
      all the best with the surgery.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
James S. Cawood,CPP,PCI,PSP
Factor One®
P.O. Box 1772
San Leandro, CA 94577
Phone: 510.352.8660
This E-mail (including attachments) is covered by the Electronic
Communications Privacy Act, 18 U.S.C. §2510-2521, is confidential and may be legally privileged. The contents of this e-mail message, including any attachments, are intended solely for the use of the person or entity to whom the e-mail was addressed. It contains information that may be protected by the attorney-client privilege, work-product doctrine, or other privileges, and may be restricted from disclosure by applicable state and federal law. If you are not the intended recipient of this message, be advised that any dissemination, distribution, or use of the contents of this message is strictly prohibited. If you received this e-mail message in error, please contact the sender by reply e-mail or phone. Please also permanently delete all copies of the original e-mail and any attached documentation. Thank you for your understanding and cooperation.

**Comment by jonathon-love** [comment]
awesome! i'll have something to you soon.

**Comment by jonathon-love** [comment]
hi jim,

try this one:

https://static.jasp-stats.org/JASP-0.6.5-Alpha1-32bit-Setup.exe

with thanks

**Comment by jcawood** [comment]
Jonathon,
        Same problem with this version.  I installed it and it seemed to
        install fine.  Then I opened it and the Windows Task Master had
        it come up as a running program and then none of the buttons
        worked and after about 15 seconds it shut down.  I thought it
        might be a Anti-Virus problem (AVG 2014), but when I shut down
        protection, it did the same thing after it loaded- 15 seconds
        than out with no buttons or other things working.  Then did the
        same thing after turning off Malware Bytes protection- same
        result.  So I am assuming since it installed correctly and still
        acted this way with both protections disabled, that there is
        another problem.
      
    On 3/7/2015 3:15 AM, Jonathon Love
      wrote:
    
    
      hi jim,
      try this one:
      https://static.jasp-stats.org/JASP-0.6.5-Alpha1-32bit-Setup.exe
      with thanks
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
James S. Cawood,CPP,PCI,PSP
Factor One®
P.O. Box 1772
San Leandro, CA 94577
Phone: 510.352.8660
This E-mail (including attachments) is covered by the Electronic
Communications Privacy Act, 18 U.S.C. §2510-2521, is confidential and may be legally privileged. The contents of this e-mail message, including any attachments, are intended solely for the use of the person or entity to whom the e-mail was addressed. It contains information that may be protected by the attorney-client privilege, work-product doctrine, or other privileges, and may be restricted from disclosure by applicable state and federal law. If you are not the intended recipient of this message, be advised that any dissemination, distribution, or use of the contents of this message is strictly prohibited. If you received this e-mail message in error, please contact the sender by reply e-mail or phone. Please also permanently delete all copies of the original e-mail and any attached documentation. Thank you for your understanding and cooperation.

**Comment by jcawood** [comment]
Jonathon,
        I also rebooted my computer and then tried to use this version
        again and it loaded the start screen, like the other times,
        showed an hourglass for the cursor, and then closed out again. 
        So rebooting does not seem to solve the problem either.
        Best,
        Jim
        
      
    On 3/7/2015 3:15 AM, Jonathon Love
      wrote:
    
    
      hi jim,
      try this one:
      https://static.jasp-stats.org/JASP-0.6.5-Alpha1-32bit-Setup.exe
      with thanks
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
James S. Cawood,CPP,PCI,PSP
Factor One®
P.O. Box 1772
San Leandro, CA 94577
Phone: 510.352.8660
This E-mail (including attachments) is covered by the Electronic
Communications Privacy Act, 18 U.S.C. §2510-2521, is confidential and may be legally privileged. The contents of this e-mail message, including any attachments, are intended solely for the use of the person or entity to whom the e-mail was addressed. It contains information that may be protected by the attorney-client privilege, work-product doctrine, or other privileges, and may be restricted from disclosure by applicable state and federal law. If you are not the intended recipient of this message, be advised that any dissemination, distribution, or use of the contents of this message is strictly prohibited. If you received this e-mail message in error, please contact the sender by reply e-mail or phone. Please also permanently delete all copies of the original e-mail and any attached documentation. Thank you for your understanding and cooperation.

**Comment by jonathon-love** [comment]
hmm, ok, this is very perculiar. the 15 second delay is really odd.

could you try uninstalling that version of JASP, and see if the 0.5 has the same problem?

https://static.jasp-stats.org/JASP-0.5-32bit-Setup.exe

this will let us rule out more recent changes.

with thanks

**Comment by jcawood** [comment]
Jonathon,
        I did load 0.6, same problem.
        Then I loaded 0.5 and it opened, I could get options to open and
        then got it to load a sample data set, then I got "it closed
        unexpectedly, please notify the JASP team" and it shut down.
        So version 0.5 got the farthest to work, but it still shut down.
        Best,
        Jim
      
    On 3/7/2015 11:04 AM, Jonathon Love
      wrote:
    
    
      hmm, ok, this is very perculiar. the 15 second delay is really
        odd.
      could you try uninstalling that version of JASP, and see if the
        0.5 has the same problem?
      https://static.jasp-stats.org/JASP-0.5-32bit-Setup.exe
      this will let us rule out more recent changes.
      with thanks
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
James S. Cawood,CPP,PCI,PSP
Factor One®
P.O. Box 1772
San Leandro, CA 94577
Phone: 510.352.8660
This E-mail (including attachments) is covered by the Electronic
Communications Privacy Act, 18 U.S.C. §2510-2521, is confidential and may be legally privileged. The contents of this e-mail message, including any attachments, are intended solely for the use of the person or entity to whom the e-mail was addressed. It contains information that may be protected by the attorney-client privilege, work-product doctrine, or other privileges, and may be restricted from disclosure by applicable state and federal law. If you are not the intended recipient of this message, be advised that any dissemination, distribution, or use of the contents of this message is strictly prohibited. If you received this e-mail message in error, please contact the sender by reply e-mail or phone. Please also permanently delete all copies of the original e-mail and any attached documentation. Thank you for your understanding and cooperation.

**Comment by jonathon-love** [comment]
jim! this is really helpful information!

but i am completely bamboozled as to what the issue could be. i will think about it some more.

thanks!

**Comment by jonathon-love** [comment]
hi jim,

1. you wouldn't happen to have R, or RStudio installed would you? (this shouldn't be an issue, but this has caused issues in the past)
2. you wouldn't happen to have JASP installed to a path with international characters in it? (i.e. ü)
3. is JASP installed on a system with more complex permissions? is it possible to "run as administrator"?

cheers

**Comment by jcawood** [comment]
Jonathon,
        Congratulations on you and your team being given some
        recognition in the APS write-up- nice.
        Regarding your questions:
        1.  No I don't have R or RStudio installed, nor have I at any
        time.
        2. The path is a straight "C:\Program Files\JASP XXX\JASP.exe".
        3.  Only one user on the system who is also the administrator
        (me) and I ran it as administrator and got the same start-up-
        then shut down problem.
        Interestingly, I have a laptop running Windows 8.1, 64-bit with
        the identical malware protection, anti-virus etc. as my desktop
        machine and no problems.
        So could it be a Windows 7 Professional conflict of some type? 
        Am I the only one reporting this?
        Best,
        Jim
      
    On 3/28/2015 3:21 AM, Jonathon Love
      wrote:
    
    
      hi jim,
      
        you wouldn't happen to have R, or RStudio installed would
          you? (this shouldn't be an issue, but this has caused issues
          in the past)
        you wouldn't happen to have JASP installed to a path with
          international characters in it? (i.e. ü)
        is JASP installed on a system with more complex permissions?
          is it possible to "run as administrator"?
      
      cheers
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
James S. Cawood,CPP,PCI,PSP
Factor One®
P.O. Box 1772
San Leandro, CA 94577
Phone: 510.352.8660
This E-mail (including attachments) is covered by the Electronic
Communications Privacy Act, 18 U.S.C. §2510-2521, is confidential and may be legally privileged. The contents of this e-mail message, including any attachments, are intended solely for the use of the person or entity to whom the e-mail was addressed. It contains information that may be protected by the attorney-client privilege, work-product doctrine, or other privileges, and may be restricted from disclosure by applicable state and federal law. If you are not the intended recipient of this message, be advised that any dissemination, distribution, or use of the contents of this message is strictly prohibited. If you received this e-mail message in error, please contact the sender by reply e-mail or phone. Please also permanently delete all copies of the original e-mail and any attached documentation. Thank you for your understanding and cooperation.

**Comment by jonathon-love** [comment]
> Congratulations on you and your team being given some recognition in the APS write-up- nice.

cheers!

> So could it be a Windows 7 Professional conflict of some type?

possibly. we have a win 7 pro machine here which works fine.

> Am I the only one reporting this?

yup :P

hmm, i will go away and think about this some more. your user name doesn't contain international characters?

thanks

jonathon

**Comment by jcawood** [comment]
Jonathon,
        No my user name is all normal letters and numbers.
        Best,
        Jim
      
    On 3/28/2015 9:11 AM, Jonathon Love
      wrote:
    
    
      
        Congratulations on you and your team being given some
          recognition in the APS write-up- nice.
      
      cheers!
      
        So could it be a Windows 7 Professional conflict of some
          type?
      
      possibly. we have a win 7 pro machine here which works fine.
      
        Am I the only one reporting this?
      
      yup :P
      hmm, i will go away and think about this some more. your user
        name doesn't contain international characters?
      thanks
      jonathon
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
James S. Cawood,CPP,PCI,PSP
Factor One®
P.O. Box 1772
San Leandro, CA 94577
Phone: 510.352.8660
This E-mail (including attachments) is covered by the Electronic
Communications Privacy Act, 18 U.S.C. §2510-2521, is confidential and may be legally privileged. The contents of this e-mail message, including any attachments, are intended solely for the use of the person or entity to whom the e-mail was addressed. It contains information that may be protected by the attorney-client privilege, work-product doctrine, or other privileges, and may be restricted from disclosure by applicable state and federal law. If you are not the intended recipient of this message, be advised that any dissemination, distribution, or use of the contents of this message is strictly prohibited. If you received this e-mail message in error, please contact the sender by reply e-mail or phone. Please also permanently delete all copies of the original e-mail and any attached documentation. Thank you for your understanding and cooperation.

**Comment by boutinb** [comment]
This issue is closed due to too long inactivity. Please re-open this issue is this problem still occurs.
