### ISSUE TITLE
Pre-existing R instance is ignored

### ISSUE THREAD

**Issue by mentalware** [jasp-stats/jasp-desktop#402]
Most stats folks whose companies allow them to use open source will already have a fully-loaded R installed on their systems (especially if they are likely JASP testers). 

Why not
a) check whether the R command is available before executing a hard-coded call which forces a copy of R to be buried inside the JASP directory instead of in /usr/bin or
b) allow the user to define where their R binary is to be found and use that for the comand invocation
c) provide an optional zip file with JASP configured to use a pre-installed R. 

At present, JASP comes with its own duplicate copy of R. I realize this allows you to control the list of installed packages, but if you provide us with a list of required packages, we can verify that our R setup has them when we download JASP.

**Comment by jonathon-love** [comment]
hi, thanks for the suggestion

we've been thinking about doing this for linux (more so we can get into repos, than to save disk space), but it's a substantial amount of work.

under windows and OS X we would need to modify the users R configuration (probably not what the user wants), so we can't do this there.

as for the list of packages, you can read that [here](https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-r-packages-list.md), and i'm pretty sure that people will be happy to burn the disk-space to save them the hassle of getting and installing these packages (some of them we've modified, some of them are specific versions checked out from github, many of them don't compile "out of the box" etc.)

cheers

jonathon
