### ISSUE TITLE
B correlation pairs: implement "Additional info" tick box for prior/posterior plot

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#409]
Hi Jonathon,

Could you maybe add the "Additional info" tick box to the prior and posterior plot for the Bayesian correlation pairs?

**Comment by jonathon-love** [comment]
Committed!

Remember how i said that if we make changes to analysis options from now on, you'll need to copy the contents of the jasp-desktop/Library folder into the build-JASP-..../Library folder? (after doing a rebase)

this is one of those times

**Comment by quentingronau** [comment]
Thanks!
