### ISSUE TITLE
Feature request: estimates of effects size in repeated measures ANOVA

### ISSUE THREAD

**Issue by ojr23** [jasp-stats/jasp-desktop#421]
It would be handy if the output table had a column for partial eta2

**Comment by jonathon-love** [comment]
Yup, we'll add this.

**Comment by ojr23** [comment]
Great!

**Comment by jonathon-love** [comment]
@raviselker has implemented this now. it will arrive in 0.6.5, due next week.

**Comment by ojr23** [comment]
Fantastic!

**Comment by jonathon-love** [comment]
oops, my bad. this is implemented for the independent samples ANOVA. should make it to the RM ANOVA in the 0.7

**Comment by jonathon-love** [comment]
it turns out a good, non-trivial, RM-ANOVA in R is really hard.

**Comment by ojr23** [comment]
I dont doubt it! Thanks for all your great work so far!
