### ISSUE TITLE
ModelTerms in Bayesian Linear Models

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#446]
When interaction effects are specified as nuisance, their main effects should be specified as nuisance as well. 
At this moment an error message is shown whenever the interaction is specified as nuisance, but a corresponding main effect is not.
Could we automatically make the main effects nuisance whenever a corresponding interaction effect is specified as nuisance.

Ps. It seems important that the user cannot change this behaviour by hand, and undo the assignment of nuisance to the main effects afterwards.

**Comment by mmarsman1** [comment]
In the overhaul of bayesian linear models this condition of nuisance is not checked and will consequently make the procedure throw a cryptic error.

It is thus important to resolve the issue before 0.6.5.

**Comment by jonathon-love** [comment]
Hmm, so now I automagically set the main effects as nuisance when the user specifies an interaction as nuisance. However, it's still possible for the user to get a non-nuisance main effect in there.

i.e.
1. user clears all variables from the model builder
2. user adds only the interaction
3. user sets the interaction as nuisance
4. user adds main effect

this is kinda tricky to handle. how difficult would it be to add the error message back in?

**Comment by mmarsman1** [comment]
Not that difficult.
I can add the error check + message back in on Friday morning.

I do think that this is best handled in the Gui, instead of that awful error message that we have now.
Perhaps 0.7 ?

On 11 Mar 2015, at 21:59, Jonathon Love <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, so now I automagically set the main effects as nuisance when the user specifies an interaction as nuisance. However, it's still possible for the user to get a non-nuisance main effect in there.

i.e.
1. user clears all variables from the model builder
2. user adds only the interaction
3. user sets the interaction as nuisance
4. user adds main effect

this is kinda tricky to handle. how difficult would it be to add the error message back in?

**Comment by jonathon-love** [comment]
> I do think that this is best handled in the Gui, instead of that awful error message that we have now.

yeah, that would be ideal. i'll see what i can do.

**Comment by jonathon-love** [comment]
can you try this out. i think i've got it working properly, but there are a *lot* of different combinations of behaviour to handle.

**Comment by jonathon-love** [comment]
oh, wait, it still needs some work.

**Comment by mmarsman1** [comment]
Haha, I just worked in all the exceptions in my code (but ugly though).

Awesome that this can be handled in the Gui; great work!

On 12 Mar 2015, at 12:50, Jonathon Love <notifications@github.com<mailto:notifications@github.com>> wrote:


can you try this out. i think i've got it working properly, but there are a lot of different combinations of behaviour to handle.

**Comment by jonathon-love** [comment]
@mmarsman1,

i think i might have it nailed. can you rebase and take a look?

**Comment by mmarsman1** [comment]
Yes.
