### ISSUE TITLE
32 bits version for Ubuntu

### ISSUE THREAD

**Issue by froukehe** [jasp-stats/jasp-desktop#451]
I would be very much interested in a 32 bits version for Ubuntu.

**Comment by jonathon-love** [comment]
hey! we'd love to do one, but we don't really have the resources at the moment. as it is, we're already prepping 5 versions; 2 x windows, 2 x ubuntu, and an osx.

hopefully we'll be able to pick up some maintainers who are interested in maintaining more than we can manage.

**Comment by jonathon-love** [comment]
you can now install 32-bit JASP from our PPA

https://launchpad.net/~jonathon-love/+archive/ubuntu/jasp
