### ISSUE TITLE
Superfluous statistics tab in contingency tables

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#452]
About the Bayesian contingency table: is there a reason why the
options are hidden under the "statistics" tab? In order to get
anything done the user needs to click on it. So we might just as well
remove it? This would also be consistent with the other analyses. The
same comment goes for the classical contingency table.
E.J.

**Comment by jonathon-love** [comment]
it is a good question; what options do we put in the top level, and what do we put beneath an expander?

for most options, the user will set them to the options they want, and these will be preserved from session to session (granted, JASP doesn't do this now, but it will). options that the user will regularly change should go at the top, but those where the user won't change, and will generally keep using the same settings, should go beneath a tab.

so i think it makes sense to keep all the classical ones beneath a tab, but what should and shouldn't go to the top level for the bayesian one bares some consideration. clearly BF10 vs BF01 should go at the top level.

**Comment by EJWagenmakers** [comment]
Yes that's right. It is also an issue of being consistent across analyses,
and striking a balance between providing too much information on the top
level vs. none at all. I think none at all is too little and makes the user
feel lost and without control.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
> I think none at all is too little and makes the user feel lost and without control.

perhaps, though that is the way that SPSS does it.

**Comment by EJWagenmakers** [comment]
Ah I see. For us I think it is probably more important to retain
consistency across different analyses. The lack of top-level options is
suprising if all the other analyses do it differently
EJ

**Comment by jonathon-love** [comment]
it's actually the t-tests (and correlation) which are inconsistent. i put all the options at the top level in the t-tests, because there was so few of it, it seemed silly. all the other analyses try not to overwhelm the user by putting it beneath expanders.

this is called [*progressive disclosure*](https://en.wikipedia.org/wiki/Progressive_disclosure)

but i agree it's appropriate to shift some stuff up in the contingency tables

**Comment by boutinb** [comment]
This issue is closed due to too long inactivity. Please re-open this issue is this problem still occurs.
