### ISSUE TITLE
Big 5 Bayesian Correlation Matrix 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#454]
When you add certain variables from the big 5 data set into the Bayesian Correlation Matrix, it stops working. Weird. We need to get to the bottom of this.

See screenshot.
![image](https://cloud.githubusercontent.com/assets/8603015/6578745/358141a0-c746-11e4-8eae-278ff03b501d.png)

**Comment by EJWagenmakers** [comment]
Perhaps this happens because the correlation is really high? @AlexanderLyNL , do you have an idea?

**Comment by jonathon-love** [comment]
@AlexanderLyNL, you've fixed this one, yeah?

**Comment by AlexanderLyNL** [comment]
Yeah
