### ISSUE TITLE
Suggestion: ability to highlight / copy values in output tables

### ISSUE THREAD

**Issue by ojr23** [jasp-stats/jasp-desktop#456]
If output tables are large (eg. bayesian RM ANOVA with 3 factors) it can be hard to work out which values near the centre correspond with which models. It would be helpful to be able to highlight all values in an individual row (alternatively, provide an option to add horizontal lines to the table? although that wont look as neat!). Similarly it would be good to be able to highlight and copy individual values for pasting elsewhere.

I can achieve both of these by exporting table as html and then opening in excel, but its a bit of work around...

**Comment by boutinb** [comment]
This issue is closed automatically due to too long inactivity. Please re-open this issue is this problem still occurs.
