### ISSUE TITLE
One-sided t-test issue with plots 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#458]
@quentingronau 

When I do a one-sided t-test, the prior is normalized (only positive or only negative). However, the posterior still appears to run across the entire real line. See the picture for an example. My point is: when the prior mass is zero, so it the posterior mass. The posterior should therefore be normalized as well as the prior.

![image](https://cloud.githubusercontent.com/assets/8603015/6596409/5b6a336e-c7f4-11e4-9c40-7777b47845e1.png)

**Comment by EJWagenmakers** [comment]
@quentingronau OK the posterior appears to be properly normalized (see attach), but there is still a black line at zero; I think that for the one-sided tests, we should just remove that line at zero (both for prior and posterior), unless there's a good reason to keep it.

![image](https://cloud.githubusercontent.com/assets/8603015/6596451/efe0828c-c7f4-11e4-9d39-0253ccf11b5e.png)

**Comment by jonathon-love** [comment]
> we should just remove that line at zero

not sure, but this might look a bit weird. empirical question.

**Comment by EJWagenmakers** [comment]
Agreed, empirical question.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by boutinb** [comment]
This issue is closed automatically due to too long inactivity. Please re-open this issue is this problem still occurs.
