### ISSUE TITLE
Paired sample t-test menu issue

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#459]
(1) In the main input menu of the Bayesian paired sample t-test, I cannot drag and drop 2 variables; it only handles one variable at a time; (2) When I then remove one of the variables, the other is removed automatically as well; (3) The two variables are displayed side by side instead of on top of one another.
Issues 1-3 are at odds with how it's done for the other menus, and I prefer us to be consistent (the user will have certain expectations, and it is always good to meet those when we can).
E.J.

**Comment by jonathon-love** [comment]
\1. yup, this used to work, will fix
\2. i think this actually makes it easier for the user; most of the time you're adding or removing pairs (if you want to change an individual element, it's easier to just to drop it on top of the one you want to replace). selecting a single cell should probably highlight the whole row though.
\3. this is the same as SPSS, and makes sense to me. the paired t-tests are different, and it's difficult to avoid that in the UI. another difference is that when you add them to the box at the right, the variable remains available in the left hand box. again, it's different, but it needs to be.

ps. you probably don't need to explain consistency to me.

**Comment by EJWagenmakers** [comment]
>
> \2. i think this actually makes it easier for the user; most of the time
> you're adding or removing pairs (if you want to change an individual
> element, it's easier to just to drop it on top of the one you want to
> replace). selecting a single cell should probably highlight the whole row
> though.
>
But it is still inconsistent with the other menus. I just don't see the
need to change the menu for this particular analysis. BTW, you could make
exactly the same argument for the correlation pairs as you do for the
t-test.

> \3. this is the same as SPSS, and makes sense to me. the paired t-tests
> are different, and it's difficult to avoid that in the UI. another
> difference is that when you add them to the box at the right, the variable
> remains available in the left hand box. again, it's different, but it needs
> to be.
>
So why can't we just have one op top of the other, as per usual? Again, I
don't see the need for the change. Maybe you can walk in and explain it.

Cheers,
E.J.

**Comment by jonathon-love** [comment]
placated
