### ISSUE TITLE
Jasp freezes once Bayesian Linear Regression is overwhelmed with models.

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#463]
In the below screenshot I specified one analysis with the kitchenrolls data:
![screen shot 2015-03-11 at 17 22 26](https://cloud.githubusercontent.com/assets/8667548/6601024/71d1acf8-c813-11e4-8a2a-5fa8b74923b5.png)

Note that Jasp is not computing anything (no icon appearing at least) nor does it populate the table. 
It seems to only happen when I drag all 10 covariates into the box at once.

More peculiar is that I cannot do anything anymore afterwards.
In the screenshot below I am doing a t-test, and it is not doing anything.

![screen shot 2015-03-11 at 17 22 51](https://cloud.githubusercontent.com/assets/8667548/6601018/6420caa8-c813-11e4-8008-b887ceda5a09.png)

As you can see there is no table emerging.

**Comment by jonathon-love** [comment]
my expectation is that enumerateGeneralModels() is taking a very long time to run.
in order for the UI to remain responsive, callbacks will need to be added to this function in the BayesFactor package.
it might just be easier to limit the number of covariates to 5 or so.

**Comment by mmarsman1** [comment]
But I would expect the “Jasp~hourglass~swirl” appearing, so that it is clear that it IS doing something at least.

It is of course a fringe thing, but I found the behaviour a bit worrisome. 

I would not go with a maximum number of covariates, since it is very restrictive.
Maybe we have to think a bit about how to get from models to output, and which models are actually estimated.
Perhaps a backward and forward model builder as commonly used in classical regression
@EJWagenmakers ?

**Comment by EJWagenmakers** [comment]
Best solved by sitting next to you & discussing.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by mmarsman1** [comment]
To summarise.
EnumerateGeneralModels takes forever to compute all possible models when more than 9 variables are included.

Given the idea of the Bayes factor and the way that the analysis is designed; it makes no sense to report over X * 100 models and to specify so many variables.
With more than 9 covariates, we are turning into variable selection as opposed to model selection; and this procedure is inefficient to do variable selection.

The possible solutions:
1. We can restrict the number of covariates to 5 as @jonathon-love suggested; this gives 31 models. (where null model allows for additional nuisance terms?)
2. We can restrict to two models (as opposed to variables)
3. Any more?

**Comment by EJWagenmakers** [comment]
Option 1 seems fine
EJ

**Comment by stephensrmmartin** [comment]
One could employ the Bayesian variable selection method mentioned in Kruschke's book.
I'm not sure how well one could do this with BayesFactor, but using jags it is possible.

Namely, you create one large hierarchical model, and the beta estimates are multiplied by some stochastic number from 0 to 1.
After running the model, variables with the multiplier closer to 0 could be dropped whereas those with a number of 1 should be kept.
In jags terms, beta[j] <- i[j] * Beta[j]; i[j] ~ dbern(.5); Beta[j] ~ dnorm(0,.0001). (dbern(.5) means your prior belief in the existence of the predictor is roughly half, this could be tweaked. Kruschke used .2 in his example)

One model must then be sampled from rather than generating exponential numbers of models and sampling.

**Comment by EJWagenmakers** [comment]
There are many perspectives on variable selection of course, and the BF way
is not the only one. I can foresee a JASP add-on module that implements a
different approach. But for the basic package, I prefer to keep things
consistent and use the Jeffreys
(Zellner-Siow-Liang-Scott-Berger-Rouder-Morey :-)) approach. That said, I
do think that shrinkage priors offer a promising and worthwhile
alternative. Perhaps we can accelerate development when it is easier for
other people to add their own JASP modules, but that still requires a lot
of effort.

Cheers,
EJ

**Comment by boutinb** [comment]
This issue is closed automatically due to too long inactivity. Please re-open this issue is this problem still occurs.
