### ISSUE TITLE
B ANOVAs: Error when main effects specified as nuisance

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#465]
If the user specifies an interaction as nuisance, we should automatically set all the main effects as nuisance. But having *just* the main effects as nuisance should be ok, yeah?

![screen shot 2015-03-11 at 9 18 40 pm](https://cloud.githubusercontent.com/assets/3240247/6605950/47eb6994-c834-11e4-979d-d3c7a29683a5.png)

**Comment by mmarsman1** [comment]
This is strange. 

> model.formula
XYmxvY2s ~ +XdHJpYWxUeXBl + XZGlmZmljdWx0eQ + XdGFyZ2V0 + XdHJpYWxUeXBl:XZGlmZmljdWx0eQ + 
    XdHJpYWxUeXBl:XdGFyZ2V0 + XZGlmZmljdWx0eQ:XdGFyZ2V0 + XdHJpYWxUeXBl:XZGlmZmljdWx0eQ:XdGFyZ2V0
> neverExclude
[1] "XZGlmZmljdWx0eQ"
> BayesFactor::enumerateGeneralModels (model.formula, whichModels = "withmain", neverExclude = neverExclude)
[[1]]
XYmxvY2s ~ +XdHJpYWxUeXBl + XZGlmZmljdWx0eQ + XdGFyZ2V0 + XdHJpYWxUeXBl:XZGlmZmljdWx0eQ + 
    XdHJpYWxUeXBl:XdGFyZ2V0 + XZGlmZmljdWx0eQ:XdGFyZ2V0 + XdHJpYWxUeXBl:XZGlmZmljdWx0eQ:XdGFyZ2V0

>

It should give me a large list of models, but gives me a single one.
Maybe it's the "+" after "~", although that should not lead to problems I suppose.

I'll have a quick look.

**Comment by jonathon-love** [comment]
righto. well let me know. this would be a show-stopper for the 0.6.5

**Comment by mmarsman1** [comment]
When was bayes-factor package last updated in our R-bundle?

**Comment by jonathon-love** [comment]
i'm pretty sure i can just temporarily revert your overhaul, and everything will be fine. why don't i do this?

after 0.6.5 i can revert the revert, and then all your work will be back again.

**Comment by mmarsman1** [comment]
I am almost there.

On 12 Mar 2015, at 09:58, Jonathon Love <notifications@github.com<mailto:notifications@github.com>> wrote:


i'm pretty sure i can just temporarily revert your overhaul, and everything will be fine. why don't i do this?

after 0.6.5 i can revert the revert, and then all your work will be back again.

**Comment by jonathon-love** [comment]
hahaha, good man :)

**Comment by mmarsman1** [comment]
The old code also needs some work, since some things like covariates in RM-covariates and the B01 / B10 / logB01 needed to be included. 
So if I can get this to work it would be at least more economical :)

**Comment by jonathon-love** [comment]
> So if I can get this to work it would be at least more economical :)

totally :)

oh man, i'm a bit nervous about this release! the number of fairly substantial bugs we've found in the last couple of days is not trivial!

**Comment by mmarsman1** [comment]
I know! I am in the office now. Fixed this stuff, will nex include the error messages. Then we can do some proper testing again and we will resolve it. I am also here tomorrow morning, so I can help where you need me. I am perfectly fine with working on other peoples code if that helps!

Verzonden van mijn HTC

----- Reply message -----
Van: "Jonathon Love" <notifications@github.com>
Aan: "jasp-stats/jasp-desktop" <jasp-desktop@noreply.github.com>
CC: "Marsman, Maarten" <M.Marsman@uva.nl>
Onderwerp: [jasp-desktop] B ANOVAs: Error when main effects specified as nuisance (#465)
Datum: do, mrt. 12, 2015 10:06


So if I can get this to work it would be at least more economical :)

totally :)

oh man, i'm a bit nervous about this release! the number of fairly substantial bugs we've found in the last couple of days is not trivial!

**Comment by mmarsman1** [comment]
Checking for the error was easy, yet the rest of the code was not designed to handle such exceptions.
I think I have it ready now, but lets test this properly. 
When are you in?

**Comment by jonathon-love** [comment]
hey, i'll probably pop in after lunch. 1400 or so.
