### ISSUE TITLE
jasp website

### ISSUE THREAD

**Issue by maffydoit** [jasp-stats/jasp-desktop#467]
It would be nice if the jasp website had a little more information about jasp, for example, what you need to use it, who to contact, how to set it up, a few pictures of what jasp looks like. Do you need to install R before installing jasp? Do you need to install jasp through R? In looking at the jasp website, I don't know any of those things. In looking a little at the github for jasp, I still don't know any of those things. All of that would make it easier for visitors to the jasp website to decide whether to pursue learning about jasp.

**Comment by jonathon-love** [comment]
hi,

thanks for the suggestions

re: website:
we have a video on the JASP website, but i agree it would be good to add some screenshots as well. and some contact info would be good; but most people end up making their way to the github page which is what we want; but you're right, we could make it more explicit.

re: JASP:
setting up JASP, is just like downloading any other "normal" piece of software. you don't need to install R, you don't need to install JASP through R. you don't need to know that R even exists, and probably most of our users don't :P

cheers

**Comment by jonathon-love** [comment]
hi @maffydoit,

i think i've addressed most of your concerns now. we have a "getting started" guide to get people going:

https://jasp-stats.org/user-guide/

kind regards
