### ISSUE TITLE
B-Correlation Matrix plot - Two-sided vs One-sided (exploratory vs inferential analysis)

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-desktop#479]
@quentingronau @EJWagenmakers 

When one switches from BF_{10} to BF_{+0} we see that the posteriors in the matrix plot changes from two-sided posteriors to one-sided posteriors. As it is concerned with an exploratory analysis I don't think that we should swap the two-sided posterior with a one-sided one. 

![screen shot 2015-03-12 at 22 50 39](https://cloud.githubusercontent.com/assets/10271675/6629443/53f8f05a-c90e-11e4-9273-0815c083eed2.png)
![screen shot 2015-03-12 at 22 50 47](https://cloud.githubusercontent.com/assets/10271675/6629444/53f9aba8-c90e-11e4-9a86-aeaa16b24a4b.png)

Note that the one-sided posterior could be negative due to an overflow BF_{+0} = 2 BF_{10} - BF_{-0}

**Comment by EJWagenmakers** [comment]
Why is it exploratory? In almost all practical research, there are strong
expectations about the direction of the effect.

In fact, the one-sided nature of the test is always almost a sign of a
confirmatory setup. For instance, in the kitchen roll experiment the
researchers had a strong, theory-based prediction about the direction.
Besides, these one-sided posteriors give you the BFs that correspond to the
one-sided test. Final argument: If you want to look at the two-sided
posterior, just select the two-sided test.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment]
What seems to be at issue here, when looking at the plots, is that the
posterior does not normalize properly when the effect is strongly in the
opposite direction. Perhaps this is also something that can be solved by
sampling.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by AlexanderLyNL** [comment]
The first time you showed me the (classical) correlation matrix plot, you were concerned with the fact that it showed a confidence interval, as it was supposed to be exploratory. 

I agree with the fact that one-sided are purely confirmatory, though, I do have some problem with their interpretations. I thought that the confirmatory analysis was supposed to be moved to the "Bayesian correlations pairs” rather than included in the correlation matrix plot. So what’s the use of the correlation pairs plot other than the figures?

**Comment by EJWagenmakers** [comment]
You are probably right.
Let's talk about this later, when we are both looking at the same screen
and when we can discuss the issue.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by boutinb** [comment]
This issue is closed automatically due to too long inactivity. Please re-open this issue is this problem still occurs.
