### ISSUE TITLE
Jasp crash when specifying anova

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#483]
When using ssgo-fred.csv, and specifying an anova model when I assign the fixed factors (see screenshot below), Jasp crashes.

![screen shot 2015-03-14 at 00 33 10](https://cloud.githubusercontent.com/assets/8667548/6648956/37130c36-c9e1-11e4-9578-f93bf460a8e0.png)

Qt dialog window:
![screen shot 2015-03-14 at 00 33 19](https://cloud.githubusercontent.com/assets/8667548/6648957/3b9bd170-c9e1-11e4-98c5-6bb22268d909.png)

Qt output:
send messages
vector::_M_range_check
libc++abi.dylib: terminating with uncaught exception of type std::exception: std::exception
The program has unexpectedly finished.

**Comment by mmarsman1** [comment]
Think this is on my end..

**Comment by jonathon-love** [comment]
this was an issue (caused a crash in yesterdays demonstration :P) but i've fixed it.

**Comment by mmarsman1** [comment]
Haha, aight!

Verzonden van mijn HTC

----- Reply message -----
Van: "Jonathon Love" <notifications@github.com>
Aan: "jasp-stats/jasp-desktop" <jasp-desktop@noreply.github.com>
CC: "Marsman, Maarten" <M.Marsman@uva.nl>
Onderwerp: [jasp-desktop] Jasp crash when specifying anova (#483)
Datum: za, mrt. 14, 2015 08:34


this was an issue (caused a crash in yesterdays demonstration :P) but i've fixed it.
