### ISSUE TITLE
Cryptic mode - warning in descriptives.

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#484]
When I generate 10,000 normal variates and ask descriptives of these, I get the peculiar error that there exist multiple modes. 

I suppose that this is due to a choice of bin sizes?

Also, the descriptives (and plots) take rather long to be produced; why is that the case?

**Comment by jonathon-love** [comment]
> When I generate 10,000 normal variates and ask descriptives of these, I get the peculiar error that there exist multiple modes.

do multiple modes exist in the data?

> Also, the descriptives (and plots) take rather long to be produced; why is that the case?

Is it always slow, or Is it only slow when you request plots? the density plots would be time consuming.

**Comment by jonathon-love** [comment]
> Also, the descriptives (and plots) take rather long to be produced; why is that the case?

can you send a dataset? running descriptives on my dataset of 10000 rows produces results and plots very quickly.
