### ISSUE TITLE
T-test warning message when an unvalid percentage is used for confidence interval.

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#485]
When I specify a 101% confidence interval the error message is cryptic (probably - R?) about 'conf.interval'.
Could we replace this with something less cryptic and not mention that a value between 0 and 1, but that a value between 0 and 100 needs to be specified?

I recall that I noted this before, but I forgot why that was not adressed :)

**Comment by jonathon-love** [comment]
Will be addressed with #314

**Comment by mmarsman1** [comment]
Ah yes, I thought it was already noted before :)
