### ISSUE TITLE
B paired-T does not produce value when n >= 10,000

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#486]
I suspect that this is a Bayes Factor issue, since ttestBF gives: 

> ttestBF(x,y,paired=TRUE)
Error in integrate(meta.t.like, lower - mean.delta, upper - mean.delta,  : 
  a limit is missing
Bayes factor analysis
--------------
[1] Alt., r=0.707 : NA ±NA%

Against denominator:
  Null, mu = 0 
---
Bayes factor type: BFoneSample, JZS

**Comment by jonathon-love** [comment]
hey @mmarsman1, this works for me. can you send an example dataset?

**Comment by boutinb** [comment]
This issue is closed automatically due to too long inactivity. Please re-open this issue is this problem still occurs.
