### ISSUE TITLE
B-AnCova with n >= 10,000 gives NaN when it should produce an infinity.

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#488]
I think this is a BayesFactor-error, since in R it produces:

> lmBF(formula(z~x),data.frame(z=z,x=x))
Bayes factor analysis
--------------
[1] x : NaNe-Inf ±NaN%

Against denominator:
  Intercept only 
---
Bayes factor type: BFlinearModel, JZS

The sample correlation (x,z) is equal to 0.995, so this should give infinity.

**Comment by boutinb** [comment]
This issue is closed automatically due to too long inactivity. Please re-open this issue is this problem still occurs.
