### ISSUE TITLE
Suggestion: descriptives multiple groups

### ISSUE THREAD

**Issue by ZuccheroZsuzsi** [jasp-stats/jasp-desktop#491]
Dear JASP team; first of all: love the statistics interface!

I've been trying out some things with my current dataset, and noticed some things that would make life with JASP alot better! Will post them separately according to subject.

So far I can't show (full) descriptives for multiple groups. To some extent this is possible in the t-test and ANOVA options (mean, sd, N), but still limited. Therefore a suggestion to add a group-factor in the main descriptives tab? Then you can also plot these two groups in one histogram if needed (which is the case for me.. ;-))

Thanks!

**Comment by ZuccheroZsuzsi** [comment]
Ah, and in the case of frequency histograms option: a frequency/density value on the y-axis would also be neat!

**Comment by jonathon-love** [comment]
> Therefore a suggestion to add a group-factor in the main descriptives tab?

i like this suggestion. i'll see what we can do.

> a frequency/density value on the y-axis is in some cases missing, as is the distribution line (see picture), but not in all. Not sure what makes this difference? 

continuous and categorical variables are treated differently; continuous get the density plot, and categorical get the frequency plot. in the case of your screenshot, you've discovered our bug where variables which are manually changed from categorical to continuous, sometimes aren't recognised as continuous. i really should get onto that :)

**Comment by ZuccheroZsuzsi** [comment]
Ah yes, you caught me there, I indeed manually changed age from cat to cont (not sure why that was categorical in the first place..). Looking forward to the bug-free and descriptive-group-factor rich update :-)

**Comment by jonathon-love** [comment]
> not sure why that was categorical in the first place..

from memory; a variable has to have at least 24 different values to be considered continuous (by default). this is the same as SPSS.

**Comment by boutinb** [comment]
This issue is closed automatically due to too long inactivity. Please re-open this issue is this problem still occurs.
