### ISSUE TITLE
B Correlation: One unviable plot, prevents all other viable plots

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#505]
if there's a problem with a single plot, it prevents all the other (viable) plots from working.

(for these sorts of errors, i would put the error message in the plot itself, as it only applies to that plot)

![screen shot 2015-03-17 at 2 50 16 pm](https://cloud.githubusercontent.com/assets/3240247/6688617/0b0051cc-ccb5-11e4-9b21-b2a258430b78.png)

**Comment by AlexanderLyNL** [comment]
@quentingronau When are you in?

**Comment by jonathon-love** [comment]
you could probably drop the heading for this plot too, because it's in the plot itself
