### ISSUE TITLE
Tests of normality, or non-normality; tests of homogeneity, or inhomogeneity

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#515]
hey @EJWagenmakers 

@raviselker and i have been discussing what the normality and homogeneity of variances tests should be called.

so far i've been calling the homogeneity test; "test inequality of variances" because that's what it actually tells you; if the variances are unequal.

so i think they should be:

 - [  ] Test inequality of variances (Levene's)
 - [  ] Test non-normality of residuals (Shapiro-Wilk)

ravi prefers the more historic:

 - [  ] Test equality of variances
 - [  ] Test normality

i think the former is more clear; typically you have to put a footnote on the Shapiro-wilk table to explain that a non-significant p-value means that the data isn't not normal. you have to explain this, because intuitively, people think that significance means that the data *is* normal (because that's the name of the test after all).

ravi prefers the latter, because you actually are "testing the null", which is probably more technically correct, but only understood by statisticians (and i argue that it is counter-intuitive)

i think people will make correct inferences a larger proportion of the time with the former labels, than the latter.

did you have a preference? i'm pretty easy, so don't feel like you need to make a long winded case.

**Comment by EJWagenmakers** [comment]
I am indifferent.
(but it is Wilks, I believe, with an s, and I'd state "Levene", not
"Levene's")
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
let's do it your way @raviselker
