### ISSUE TITLE
B 1-sample t test: error 

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#516]
Hi,

When I select one-sample Bayesian t test I obtain an error. I just did a rebase, maybe it is just something with my laptop, because I also get an error when I select Bayesian crosstabs and specify rows and columns.

Quentin
![errorttestdes](https://cloud.githubusercontent.com/assets/8697436/6709284/581ea170-cd78-11e4-97e6-0849066bb57a.png)

**Comment by jonathon-love** [comment]
oh right, try copying the contents of the

jasp-desktop/Library

folder to

build-JASP-.../Library

**Comment by quentingronau** [comment]
Thanks, it works now.
