### ISSUE TITLE
Analysis scripts

### ISSUE THREAD

**Issue by Matherion** [jasp-stats/jasp-desktop#525]
First: JASP looks great! It's like R but pretty, and SPSS but powerful, userfriendly, small, oh, and, pretty.

But of course, that's not why I'm here :-) In our teaching, we try to teach our students to document everything they do. It would be great if JASP could e.g. show the R commands that are used to generate the relevant output, also so that our students can attach these along with their theses etc. Of course, they needn't be R scripts; some JASP-specific scriptinging language would be fine as well. I could even survive it approaching the horrible SPSS syntax :-) But some means of documenting the analyses, bar having to make screenshots or infer them from the exported output, would be great :-)

After all, eventually we'll want all researchers and students to make their complete analysis scripts accessible to other researchers (i.e. publishing them alongside their data files), and teaching students that that's the way to go is a good way to start this process.

(Of course, you may very well be planning this already, but I just thought I'd suggest it anyway :-) )

Thank you for JASP, keep up the good work!

**Comment by jonathon-love** [comment]
hi!

the JASP approach is for the JASP analysis files themselves to document everything they do. if you want to know exactly how an analysis was specified, you just click on it, and it brings up the options that were used.

of course, at the moment we don't have the ability to save and reopen .JASP files, but this is in development.

my whole approach is to avoid the user from having to deal with syntax, or have to infer how the syntax maps on to the user interface elements; it's nicest if you just give them the user interface elements directly.

cheers

**Comment by TomScherndl** [comment]
HI,
sorry to chime in: even SPSS has a syntax feature (above each output you see the syntax used to generate the output) and those who want to use the syntax gain more control and deeper (yet still limited - it's SPSS) insight into what they are doing. Additionally, in the area of reproducible science, one has to include an efficient and effective way of saving and documenting the complete analysis. 

Personally, I think that JASP is a great tool for beginners who are afraid of R and its syntax and it already encompasses many useful analyses in an easy-to-use way. However, I think that more sophisticated analyses simply are not compatible with a pure GUI approach. SPSS tried and failed with their cluttered command dialog boxes. 
RCommander (and other R-GUIs, I think) encourage the user to make a change to the syntax by always showing the syntax before their output. I personally think this is a nice compromise: give the typical user a GUI but softly nudge them into the way of the (more powerful, but not GUI) underlying tool R. 
just my 2 cents - 
best, Tom

**Comment by jonathon-love** [comment]
> even SPSS has a syntax feature (above each output you see the syntax used to generate the output) and those who want to use the syntax gain more control and deeper (yet still limited - it's SPSS) insight into what they are doing

in our case, the syntax would be an exact representation of the UI elements (if it didn't map exactly to the UI elements, then it would be a mission to figure out how the syntax maps to the UI options). then, if it maps exactly to the UI options, it would not give any greater insight. so i have my doubts about this.

> in the area of reproducible science, one has to include an efficient and effective way of saving and documenting the complete analysis

i completely agree, which is why i don't think syntax is a very good solution; reading code, be it SPSS syntax, or somebody elses R code is difficult. where as nothing could be quicker than clicking on an analysis, and having the exact UI options used popup!

> However, I think that more sophisticated analyses simply are not compatible with a pure GUI approach

yup, you may be right, but in my view, the majority of users don't actually need *that* sophisticated analyses. there's a huge group of people just wanting to do t-tests, ANOVAs, and so i think that for the majority of people R isn't necessary.

jonathon

**Comment by jonathon-love** [comment]
actually, i have been thinking about implementing this; providing some sort of syntax. i'll keep you posted.

**Comment by Matherion** [comment]
Sorry, I'm not on GitHub as frequently as I should be :-)

IMHO, there are two reasons for scripting analyses. The first is gaining power. As you indicate Jonathan, most users don't need this. Or, more accurately, don't understand this, don't want to learn, and therefore make do with inferior approaches. But we can't teach everybody to think like a programmer, so this point I get. JASP is extremely userfriendly, partly because it's wholly GUI-driven. Especially since it aims to bring analyses that were traditionally seen as too advanced/sophisticated/complicated to a wider audience, it seems unwise to compromise here. So I'm with you.

But of course, there's the second reason :-) This is more about scrutiny and transparency. As JASP grows, people will use it for more and sequential analyses. It will approach SPSS in the sense that if you get back to your analyses after a few months or even years, you won't remember what you did and why. Worse, attempts to replicate your analyses usually fail. This is why scripts and comments are crucial. They make it possible for others to read your 'code' - even when the code consists of "do a t-test - then a regression analysis - save the residuals - use them for a correlation". "Syntax" or 'code', basically, having a step in between the GUI and the output that enables users to document their analyses and explain them to their future self and other researchers, is useful even when the analysis script contains no real 'code', but just some commands. If you know what I mean :-)

**Comment by jonathon-love** [comment]
hi @Matherion 

your ideas are good! that's why we're adding notes to JASP. you can add rationale/commentary/narrative/conclusions, etc. to the results panel. this will be coming in the next release. see the screenshot:

<img width="567" alt="screen shot 2015-09-28 at 12 54 42 pm" src="https://cloud.githubusercontent.com/assets/3240247/10133753/456e7932-65e0-11e5-9fe3-f72b2f17e2b2.png">
