### ISSUE TITLE
Add proportion test

### ISSUE THREAD

**Issue by IndrajeetPatil** [jasp-stats/jasp-desktop#528]
Is it possible to add a Chi-square test to JASP and also its Bayesian counterpart? 
For example, I would like to see if the observed frequency of two conditions is equal in my sample but there is no option currently to pursue this. 
Thanks.

**Comment by jonathon-love** [comment]
Proportion test is scheduled for inclusion in 0.7!

**Comment by IndrajeetPatil** [comment]
Awesome!

**Comment by FransMeerhoff** [comment]
This issue is embedded in version 7.5.6
