### ISSUE TITLE
Fix JASP installer to provide better feedback about necessity of Admin privileges

### ISSUE THREAD

**Issue by pscjd** [jasp-stats/jasp-desktop#533]
Hi,
Just tried downloading the latest Windows version (0.6.5) on two different PCs (32-bit and 64-bit). In both cases the setup.exe ran, appeared to extract files, but then it didn't start JASP at the end of the install, and I can't find JASP anywhere on the PC. Any suggestions?
Thanks,
Colin

**Comment by jonathon-love** [comment]
hi,
that is peculiar, we've never seen anything like this before.
what version of windows?
you should find JASP in the start menu, and if it isn't there, try looking in C:\Program Files
let me know how you get on
jonathon

**Comment by pscjd** [comment]
Hi Jonathon,
Thanks. We're using Windows 7. It's not in Program Files or the Start menu
...
Colin

On 23 March 2015 at 15:29, Jonathon Love <notifications@github.com> wrote:

> hi,
> that is peculiar, we've never seen anything like this before.
> what version of windows?
> you should find JASP in the start menu, and if it isn't there, try looking
> in C:\Program Files
> let me know how you get on
> jonathon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasp-stats/jasp-desktop/issues/533#issuecomment-85050237>
> .
>



-- 
Professor Colin Davis
School of Experimental Psychology
University of Bristol
Bristol BS8 1TU, UK
pscjd@bristol.ac.uk

**Comment by jonathon-love** [comment]
So there should be two Program Files directories, one *Program Files* and *Program Files (x86)* (or something like it), could you confirm that it is in neither?
cheers

**Comment by pscjd** [comment]
That's right -- it's not in either.
Colin

On 23 March 2015 at 15:41, Jonathon Love <notifications@github.com> wrote:

> So there should be two Program Files directories, one *Program Files* and *Program
> Files (x86)* (or something like it), could you confirm that it is in
> neither?
> cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasp-stats/jasp-desktop/issues/533#issuecomment-85054302>
> .
>



-- 
Professor Colin Davis
School of Experimental Psychology
University of Bristol
Bristol BS8 1TU, UK
pscjd@bristol.ac.uk

**Comment by jonathon-love** [comment]
hmm, i don't know what to suggest. i'd try re-running the installer, and seeing if that works. have you tried the 64-bit version of JASP on the 64-bit windows (it shouldn't matter, both should work)

**Comment by pscjd** [comment]
Hi Jonathan,
Figured it out -- it works here (University of Bristol) ONLY if I run the
installer by right-clicking and running as an administrator. Perhaps
there's some checking that should take place in the installer?
Thanks,
Colin

On 23 March 2015 at 15:46, Jonathon Love <notifications@github.com> wrote:

> hmm, i don't know what to suggest. i'd try re-running the installer, and
> seeing if that works. have you tried the 64-bit version of JASP on the
> 64-bit windows (it shouldn't matter, both should work)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasp-stats/jasp-desktop/issues/533#issuecomment-85056057>
> .
>



-- 
Professor Colin Davis
School of Experimental Psychology
University of Bristol
Bristol BS8 1TU, UK
pscjd@bristol.ac.uk

**Comment by jonathon-love** [comment]
ah! thanks for figuring this out!

> Perhaps there's some checking that should take place in the installer?

yup, i guess so. oh man, i hate installers.

cheers

**Comment by jonathon-love** [comment]
you might want to look at this one @dropmann

**Comment by dropmann** [comment]
I've taken the /nonfatal off of all the files and added an administrator check into the initialisation code. On win8.1 the installer asks for an administrator password if the user is a standard user.

**Comment by jonathon-love** [comment]
so i can close this?

**Comment by dropmann** [comment]
yes
