### ISSUE TITLE
loading csv-datasets into JASP

### ISSUE THREAD

**Issue by airee** [jasp-stats/jasp-desktop#534]
Hey, Jonathon :)

Got a sample dataset from EJ on the correlation of presidential height vs voter support (and others),
tried to load them into JASP & got a following error message:
![jasp_error_msg](https://cloud.githubusercontent.com/assets/11632261/6804058/e21a8bd8-d23b-11e4-8f29-c176b752ee74.PNG)

-- working on Win64, the files are on the local hard drive.

Thanks a lot!
Best of luck,
Aire

**Comment by jonathon-love** [comment]
hi, this looks like a file permission problem. are you able to open the files in any other software? i.e. excel or notepad?

**Comment by airee** [comment]
update: at first the problem-causing csv-files were in the 'My Documents' folder. Moving them into 
"...\Program Files\JASP 0.6.5\" helped solve the problem!

**Comment by airee** [comment]
... to answer your question -- yes, excel opens them very well from any location! was also checking the running processing (as to see if any other software could be accessing the files and making them thus inaccessible to JASP -- did not seem to be the case).

**Comment by jonathon-love** [comment]
Could you tell me the complete path to your "My Documents" folder? are there any international characters, etc. involved?
cheers

**Comment by airee** [comment]
Right, the international characters could be the explanation!: the path is: "C:\Users\aire\Documents\aire\Erasmus_Balatonföldvar", will try to change it in a minute now & see if that helps!

**Comment by airee** [comment]
Bingo! the letter "ö" was the culprit! :) Thanks and all the best wishes!

**Comment by jonathon-love** [comment]
excellent, i'll have to look into our international character handling.

thanks for your help.

**Comment by airee** [comment]
Most welcome, thank you and keep up the good work!

**Comment by jonathon-love** [comment]
hi @airee,
this issue should be fixed in 0.6.6, which is available now:
https://jasp-stats.org/download/

**Comment by airee** [comment]
Dear Jonathon,

Thanks for your excellent work and for being so helpful!

All the best wishes,
Aire :)
