### ISSUE TITLE
Generating Statistic Objects

### ISSUE THREAD

**Issue by abdullahgarcia** [jasp-stats/jasp-desktop#535]
Recreation steps:

Generate any type of object (ANOVA, T-Tests, etc.)

Select any of the objects in the right pane of the main window. 

Press DELETE button.

Result: You will not be able to create a new figure with that dataset again.

**Comment by jonathon-love** [comment]
the backspace key is interpretted as "back" by the results panel (which is just a web browser), which is why this occurs. will put a fix in shortly.

**Comment by abdullahgarcia** [comment]
I suspected. 

I guess the only problem is that the object becomes unavailable to display further analysis.

Jajaja greetings from the Bayesian Statistics Seminar with Eric!
