### ISSUE TITLE
Improves JASP's handling of hi-res displays under windows

### ISSUE THREAD

**Issue by rubenhub** [jasp-stats/jasp-desktop#538]
There is overlap between the parts of the visual interface and the ok-button. For reference see my poorly constructed jpg.
![bugvisual](https://cloud.githubusercontent.com/assets/11633883/6806646/4a6d0a9a-d24a-11e4-8960-6c4afb198a8b.jpg)d

I'm running Windows 8.1, 1920x1080x64. Hope this helps, otherwise feel free to contact me.

Good luck!

**Comment by jonathon-love** [comment]
thanks for the report

we're aware of this issue. it's actually very difficult to handle high resolution screens under windows, but we're intending on working on this soon.

cheers

**Comment by rubenhub** [comment]
Hi Jonathan,
Ok, good to know.  Good luck!
Cheers
Date: Tue, 24 Mar 2015 09:29:11 -0700

**Comment by boutinb** [comment]
This issue is closed automatically due to too long inactivity. Please re-open this issue is this problem still occurs.
