### ISSUE TITLE
Add silent installation mode into JASP windows installer

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#539]

**Comment by jonathon-love** [comment]
Apparently this is already implemented :)

**Comment by brennan-pilcher** [comment]
Any idea how this is supposed to be done? I've searched around for a while and tried all the common command line switches to no avail.

**Comment by FransMeerhoff** [comment]
@brennan-pilcher 

Sorry for the late reaction, and thanks for finding it out yourself.
Some extra info that might be useful for you: for any new releases we ship an installed Windows version (both 32/64 bits) that does not to be installed but can be unpacked and used.

Kind regards 
Frans Meerhoff
