### ISSUE TITLE
Find and Fix Permissions issue under Windows

### ISSUE THREAD

**Issue by uasolo** [jasp-stats/jasp-desktop#540]
I have just installed the Windows 32 binaries of Jasp 0.6.5 on my Windows7 64 bit. I am trying the demo data and I am experiencing several crashes. 
Example of crashing sequence: 
- select Big 5 data set
- in Common select Descriptives
- select any item, e.g. Neuroticism
- toggle Display Plots

result: Error window with internal error "".

**Comment by jonathon-love** [comment]
hmm, that it peculiar.

so it only happens when displaying plots? otherwise everything else seems to work?

with thanks

**Comment by jonathon-love** [comment]
another Q, you wouldn't happen to have international characters in your username on windows?

**Comment by uasolo** [comment]
trying other combinations I get a subscript out of bounds error. Basically nothing works.

**Comment by uasolo** [comment]
I installed Jasp from a username that grants me admin permissions. This username starts with ".\" , so dot , backslash. Then an alphanumeric combination follows, which includes a "-" (dash).

**Comment by jonathon-love** [comment]
is it possible to try running JASP under a different user name?

**Comment by uasolo** [comment]
I am running it from my usual non-admin user name, which is an alphanumeric combination follows, which includes a "-" . But I have installed it under the above mentioned user.

**Comment by uasolo** [comment]
I tried to run JASP from the admin user. Everything works fine there. So the problem seems to be related to the fact that I am a different user.

**Comment by jonathon-love** [comment]
ah, awesome - very valueable piece of information!
hmm, so it's something to do with permissions, or the like. i will have to see if i can set up a similar environment here, and reproduce the issue.

thanks for your report

**Comment by boutinb** [comment]
It exists now a ZIP download version for Windows. Can you try this it is helps?
