### ISSUE TITLE
Documentation about which versions of statistics are being calculated

### ISSUE THREAD

**Issue by jhclevenger** [jasp-stats/jasp-desktop#542]
JASP is great(!), but I'm a little in the dark about which versions of stats are being calculated. For some stats (e.g., effect size, confidence intervals), there are multiple possible versions and the documentation doesn't make it clear which is being reported. For instance, in the paired subjects t-test, the notation just says Cohen's d, but that doesn't distinguish between dav, dz, or drm (looks like dav is actually reported). 

While references for the stats would be nice (but is likely a lot of work), just providing some way to view the actual equations/code being used would be helpful. Is this currently possible and I'm not seeing it?

**Comment by jonathon-love** [comment]
hi,

i didn't realise there were multiple ways to calculate these things! we generally produce the same output as SPSS (which may, or may not be helpful to your understanding)

you can see most of the code for the analyses here:

https://github.com/jasp-stats/jasp-desktop/tree/development/JASP-Engine/JASP/R

we use R for the analyses, so we're just calling some R functions, but R documentation isn't that great either :/

so you'll probably need to look at the source code to the R functions, which is mostly here:

https://svn.r-project.org/R/trunk/src/library/stats/R/

we're currently developing documentation for these methods, so hopefully in future it won't be necessary to go digging through source code!

cheers

**Comment by jhclevenger** [comment]
Great, thanks. Again, JASP is wonderful.

**Comment by jonathon-love** [comment]
Appreciate the encouragement!
