### ISSUE TITLE
Bayesian one-sample t-test: test value missing

### ISSUE THREAD

**Issue by yyamani** [jasp-stats/jasp-desktop#543]
When trying to run a Bayesian one-sample t-test, it does not allow entering a test value as it does for one sample t-test in NHST. I assume that the default test value is 0, but is there anywhere else I can specify the test value? 

Yusuke

**Comment by jonathon-love** [comment]
sorry, this was a bug that we discovered 5 minutes after releasing 0.6.5 :/

will be fixed in the next release

**Comment by yyamani** [comment]
Looking forward to the next release! Thx.
