### ISSUE TITLE
B Correlation: PP plot, no credible interval with directional hypothesis

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#552]

**Comment by quentingronau** [comment]
At the moment we are not able to compute the credible interval for these cases, if I am informed correctly, but Alexander is working on a solution, I think.

**Comment by jonathon-love** [comment]
appears to be implemented

**Comment by quentingronau** [comment]
Yes, sorry, I forgot to reference that issue when I commited the change.
