### ISSUE TITLE
B Cont Table: Odds ratio plot: uses BF+0 notation when should use BF10

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#553]
also, is there something a bit funny with the rounding? the median is reported as -0.000 rather than 0.000

![screen shot 2015-04-02 at 5 20 55 pm](https://cloud.githubusercontent.com/assets/3240247/6966984/d21b0e24-d95c-11e4-8723-ae7d852178cf.png)

**Comment by quentingronau** [comment]
Concerning the rounding: I agree it looks funny. On the other hand, if we want to round to 3 decimal places, how would you like -0.0001712156 to be rounded? To 0.000? In this case, I would need to rewrite the format/rounding function of R.
