### ISSUE TITLE
Results for one-sided t-tests change a little upon recomputation

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#555]
The results for one-sided t-tests change a little every time they are recomputed. This happens because the posterior proportion is estimated via a fit based on samples. It would be nice if the user had an option, somewhere hidden and out of sight, to manipulate the number of samples that are drawn, so this can be increased if deemed necessary.

**Comment by jonathon-love** [comment]
currently, this result is calculated pretty quickly?

perhaps we can just increase the number of samples and call it a day?

**Comment by quentingronau** [comment]
I increased the number of samples from 10,000 to 100,000 on my laptop. This leads to more stable results (of course), but the plots take substantially longer (but to be fair, my laptop is slow in general). Furthermore, the issue of changing results remains for cases where the posterior area in the tested interval is very small (when the effect is clearly in the opposite direction). What do you think?

**Comment by EJWagenmakers** [comment]
Exactly. Because it depends on the situation, it makes sense to put the
researcher in charge of the precision. Also, if it is a result that will be
published in a paper, the researcher may want to run it for a longer time
to get more stable results, but not otherwise. So I see two options:
(1) leave it as is (otherwise some of these plots will take forever, like
the robustness plot or the sequential plot)
(2) put the user in charge and add a button for the number of draws

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
> put the user in charge and add a button for the number of draws

what if we do something iterative that targets 3 decimal places of precision?

the number of draws is one of those "implementation details", that the user shouldn't have to deal with. it also makes the person do trial-and-error; they'll have to try it a few times to check that the number of draws they specified produces consistent results. and how many times do they need to re-run it before they are confident that it will always produce consistent looking results? quite a few times to be properly satisfied.

**Comment by EJWagenmakers** [comment]
But the iterative procedure itself will take a lot of extra time.
I don't think this can be properly automatized; the basic problem is that
for most analyses, accuracy up till three digits is *not* required, and
going for this target will needlessly slow down all analyses.

But for some analyses this accuracy *is* required, in the sense that it
will make authors feel better when they report they results. Also, just
having the ability to obtain stable results (albeit at the cost of a very
slow analysis) will make users feel good -- "ah, OK, I can get stable
results if I just up the number of samples and wait 10 minutes. Great. But
for these preliminary analyses, that is not needed; so I'll just go with
the default until I know exactly what to report, and then I'll collect more
samples".

The final problem is that three-digit accuracy is nigh unattainable in
extreme cases -- the sampling could take hours. Having that as a default is
not a good idea.

I take it the main problem is where to present this option do that it does
not clutter the view? Can't we have a tab with "advanced options"? We might
want to use this in the future to add in other stuff as well.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
> But the iterative procedure itself will take a lot of extra time.

it will take less time than the person rerunning the analysis 12 times to make sure that the result is stable.

> the basic problem is that for most analyses, accuracy up till three digits is *not* required, and going for this target will needlessly slow down all analyses.

isn't for most analyses, 3 digits very quick?

> The final problem is that three-digit accuracy is nigh unattainable in
extreme cases

we can put an upper limit on it.

**Comment by EJWagenmakers** [comment]
The problem remains: the user needs this kind of precision only sometimes.
EJ

**Comment by jonathon-love** [comment]
> The problem remains: the user needs this kind of precision only sometimes.

but excess precision isn't a problem. surely the problem is:

sometimes the users wants precision **AND** sometimes precision takes a while to produce

and a conjunction of two sometimes can be a; "not that often", or "hardly ever".

anyhow, i'm interested in exploring how often "sometimes precision takes a while to produce" occurs in common datasets. if a small proportion of users have to wait a little bit longer because they're looking at extreme datasets, then i'd be reluctant to add an option.

if a reasonable proportion take a while, then it would make sense to have this option.

having said that; the option should be expressed in terms of the goals of the user (i.e. target precision), and consistent throughout (i.e. also affecting the output we take from the bayes factor package)

**Comment by jonathon-love** [comment]
following up; asking the user to specify the number of samples is *text-book* bad user interface design. it is asking "how is the underlying implementation written?" rather than "what does the user want to do?". asking "how does a computer work?", rather than "how does a person work?"

**Comment by EJWagenmakers** [comment]
It is easy to explore. As Quentin said, it does depend on the posterior
itself; the more extreme the result, the more samples will be needed (when
testing for a negative effect that happens to come out positively, a large
two-sided BF10 needs to be multiplied with a tiny correction factor, this
becomes more unstable as both numbers become more extreme).

My guess is that getting the results stable to three digits when the result
is not that extreme will make the process slow down by a factor of 10 at
the very minimum. But we can do a quick test and see.

Cheers,
EJ

**Comment by jonathon-love** [comment]
.05 seconds x 10 = .5 seconds?

**Comment by EJWagenmakers** [comment]
Which is why it could be hidden under some tab for advanced use. It is not
perfect,  but for the purpose of publishing results some researchers may
desire the stability, and it would be  shame if we force these people to
use the  BayesFactor package anyway, because it does allow this option to
be specified.
EJ

**Comment by EJWagenmakers** [comment]
We could have the user specify some precision instead of number of samples,
but that would mean a much slower search process.

**Comment by EJWagenmakers** [comment]
Which will make the robustness ans sequential plots too slow. And this was
my minimum estimate. This could easily take 100 times as long. The problem
is that the required numberof samples is problem-specific.

**Comment by jonathon-love** [comment]
> The problem is that the required number of samples is problem-specific.

which is why making the user figure out how many samples they need a-priori is problematic.

the user is going to have to go through this search process themselves, and they're likely to be conserative (i.e. just bang a really big number in there)

> Which will make the robustness ans sequential plots too slow

don't these only need to be precise to a pixel?

**Comment by EJWagenmakers** [comment]
Let's discuss this later, together with Quentin so we can look at some
examples. Getting this right has relatively low priority as far as I am
concerned.
EJ

**Comment by boutinb** [comment]
This issue is closed automatically due to too long inactivity. Please re-open this issue is this problem still occurs.
