### ISSUE TITLE
C Correlation: Confidence intervals need to be implemented

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#556]
The classical correlation does not present a button to compute CIs. The plot function does show them, and that's great, but it would be better to have the button as well (as we do for the other analyses).
E.J.

**Comment by jonathon-love** [comment]
there's actually a checkbox already in there (hidden when built for release), we just don't have anyone responsible for classical correlation.

**Comment by jonathon-love** [comment]
if you get bored @quentingronau :)

**Comment by EJWagenmakers** [comment]
Woh that's quick.
EJ

**Comment by jonathon-love** [comment]
Can the `upper 95% CI` be title case: i.e. `Upper 95% CI`

**Comment by jonathon-love** [comment]
oh, and we're also missing some m-dashes:

![screen shot 2015-04-18 at 10 53 37 am](https://cloud.githubusercontent.com/assets/3240247/7214733/3b824a68-e5b9-11e4-9b8c-c6e9dd92f29c.png)

**Comment by EJWagenmakers** [comment]
Do we want caps for R, Rho, and Tau? I prefer lower case.
EJ

**Comment by quentingronau** [comment]
I have changed it to r, rho, tau.
