### ISSUE TITLE
C RM ANOVA: Issue with particular analysis

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#559]
![screen shot 2015-04-07 at 11 23 36 pm](https://cloud.githubusercontent.com/assets/3240247/7033803/3fac3f52-dd7d-11e4-8352-5516424ea569.png)

**Comment by hcp4715** [comment]
no option for C RM ANOVA with windows 64-bit version ?

I am trying to using classic RM ANOVA  as in SPSS, but only found the F-value table, without the part of "Model", "Contrast", "Post-hoc Tests" and "Option"
![qq 20150421110118](https://cloud.githubusercontent.com/assets/7300419/7244937/cf684dbe-e815-11e4-869e-b2ef28c471ee.png)

**Comment by jonathon-love** [comment]
> I am trying to using classic RM ANOVA as in SPSS, but only found the F-value table, without the part of "Model", "Contrast", "Post-hoc Tests" and "Option". Tha't a problem of version or a bug?

hi @hcp4715,

this feature isn't in 0.6.6, but will be in the next release (0.7)

cheers

**Comment by hcp4715** [comment]
@jonathon-love 
Thanks for reply!
looking forward it

**Comment by hcp4715** [comment]
@jonathon-love 
Hi,Jonathon, I hope that the 0.7 release could integrate the method provided in Lakens, D. (2013), which is very useful.

Lakens, D. (2013). Calculating and reporting effect sizes to facilitate cumulative science: a practical primer for t-tests and ANOVAs. Front Psychol., 4, 863. doi: 10.3389/fpsyg.2013.00863

**Comment by jonathon-love** [comment]
yeah, *common language effect size* is kinda neat.
