### ISSUE TITLE
C RM ANOVA: small spaces between terms and residual

### ISSUE THREAD

**Issue by raviselker** [jasp-stats/jasp-desktop#563]
It would be great to have something other than a full space between rows. In the RM ANOVA I would like to separate different within subject "blocks" with a full space while still being able to separate the "residual" term from the other terms using a small space. At the moment it looks as follows:

![screen shot 2015-04-08 at 14 17 13](https://cloud.githubusercontent.com/assets/4669197/7045057/39b459a4-ddfa-11e4-94f9-0135b72a7051.png)

**Comment by jonathon-love** [comment]
At the moment, full spaces are designated with `.isNewGroup`. can you add `.isNewSubGroup` to the rows you want to have small spaces above, and i'll take it from there.
