### ISSUE TITLE
export not working for graphical output

### ISSUE THREAD

**Issue by bhismalab** [jasp-stats/jasp-desktop#568]
hi, 
the graphical output do not get exported on html outputs, while the tables export fine.
am using , jasp v 0.6.6 on os x yosemite.
thanks for any help,
bhisma

**Comment by dropmann** [comment]
I suspect this should work now, but i don't have a mac to test it. Jonathon could you check please?

**Comment by jonathon-love** [comment]
everything seems to work, except error messages which don't appear to be exported. is it possible to give the document a bit more padding (similar padding to the results panel?)

**Comment by dropmann** [comment]
I did the exporting of error messages and added padding around the document when exported.
