### ISSUE TITLE
Feature: Add facility to split dataset by factor, and have analyses run multiply, side-by-side.

### ISSUE THREAD

**Issue by IndrajeetPatil** [jasp-stats/jasp-desktop#575]
Hi all,

It will be great if JASP adds a facility to split the file by group factor (like in SPSS) so that the same analysis can be repeated for different groups simultaneously. 

Thanks, :)
Indrajeet

**Comment by jonathon-love** [comment]
yup, we've been thinking about this. probably won't happen for a while. maybe 0.8 or so.

**Comment by PhilJdal** [comment]
Was this ever implemented?

**Comment by EJWagenmakers** [comment]
Only for descriptives. We could do this for some of the other analyses, but I fear that the costs of making the interface more complicated isn't worth it...

**Comment by PhilJdal** [comment]
Dang :(

**Comment by boutinb** [comment]
What will do soon is data filtering per factor. You will be then able to run analyses for e.g. men, and with another instance of JASP, for women.

**Comment by PhilJdal** [comment]
That would be nice. Thanks!

**Comment by ArielGoldstein** [comment]
is it exists?

**Comment by AlexanderLyNL** [comment]
Hi Ariel,

Yes, we have analyses that you can split-by with factors. If there's one that's missing and necessary, please open a new thread. 

Cheers,
Alexander
