### ISSUE TITLE
B T-Tests can use the state-system more effectively

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#579]
hey @quentingronau,

great work on the B t-tests use of the state-system, but they could be improved.

when the analysis is changed, the images are replaced with the blank place-holders, before being replaced with the image again. this results in a flash, which we're trying to avoid.

same with the tables; they are replaced with their empty counter-parts, before being replaced with filled in versions again.

but other than that, looks great!

**Comment by quentingronau** [comment]
Hi Jonathon, thanks. You are absolutely right, I recognized the flash, too. I will work on it soon.
