### ISSUE TITLE
B 1S T-Test: Possible problem?

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#580]
hey, i got this, but now i'm not able to reproduce it. :/

can you see a way that this error could be produced?

![screen shot 2015-04-12 at 9 25 08 am](https://cloud.githubusercontent.com/assets/3240247/7104739/5205cb1a-e0f6-11e4-9984-e2e5a6b5dc5b.png)

**Comment by quentingronau** [comment]
Hi, at first glance I am a little bit puzzled. I have no object called "Inf0", it might be an error in the eval function which should somehow be related to the arguments I use for it. I will try to reproduce it and see if I can solve it.
