### ISSUE TITLE
C correlation does not produce reasonable table

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#600]
Hi @jonathon-love, 

The classical correlation does not produce a reasonable table (see below). Since I am the last one that changed the correlation.R file, it is probably my fault, but I do not quite understand it, I am relatively sure, that it worked when I commited it. Do you maybe have a suggestion what the reason could be?

![bugcorrelation](https://cloud.githubusercontent.com/assets/8697436/7154697/e37df522-e358-11e4-9a1b-336b4fbdc984.png)

**Comment by quentingronau** [comment]
Sorry, I found it, when I don't select a correlation coefficient that probably makes sense :).

**Comment by jonathon-love** [comment]
yeah, we should probably do something about this; if you select no coefficient, it would be nice for it to default to pearson.
