### ISSUE TITLE
C correlation: small inconsistency

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#609]
Hi @jonathon-love,

I noticed a small inconsistency: The order of the checkboxes for pearson, kendall, and spearman is different from the table output (i.e., pearson, spearman, kendall). Shall I just change it in the R file or do you want to change the checkbox order?

Cheers

![correlationinconsistency](https://cloud.githubusercontent.com/assets/8697436/7197606/25e1b076-e4e3-11e4-9315-d0a61fbf93bd.png)

**Comment by jonathon-love** [comment]
good catch. we should put the more popular one second, and the least popular one third.

i just google battled them:

http://www.googlebattle.com/?domain=spearman+rank&domain2=kendall+tau&submit=Go!

and spearman won, so i'll update the UI
