### ISSUE TITLE
B correlation pairs robustness plot: range prior width?

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#623]
Hi @AlexanderLyNL , @EJWagenmakers ,

I started working on the Bayes factor robustness check plot for the Bayesian correlation pairs.
What values for the prior width kappa do we want to consider? Alexander, I saw you introduced a lower bound of kappa=0.5 for the correlation matrix, shall we consider e.g., kappa \in [0.5,2]?

**Comment by EJWagenmakers** [comment]
So kappa = 1 is default and yields the flat prior. Can you remind me what
kappa represents?
EJ

**Comment by quentingronau** [comment]
Alexander is the expert here of course In his paper it says that kappa can be thought of as a scale parameter like the r for the cauchy effect size prior. Alpha is the parameter of the symmetric beta prior distribution and is obtained by alpha= 1/kappa. I'm not sure if this is what you wanted to know.

**Comment by EJWagenmakers** [comment]
OK. So in our t-test, the robustness plot makes r range from 0 (in which
case H1 = H0 by definition) to something very broad, say r=1.5. Now we want
to do the same for correlation. When kappa = 0, alpha is infinite and H1 =
H0, so this is where we start. Kappa = 1 is the uniform, which is pretty
broad, but I think as an end point we should have alpha = 0.5, so kappa =
2. So I would argue for kappa ranging from 0 to 2, with 1 being the default.

Also, in the future we should allow the user to test against all sorts of
correlations, not only 0. But that only works for some priors, so let's
postpone that for now.

EJ

**Comment by quentingronau** [comment]
Ok. I have mad two example plots. The first one behaves like expected, when kappa approaches zero the models become more and more similar and the Bayes factor approaches one. In the second example however (using the ssgo data set), the Bayes factor increases as kappa approaches zero. That makes me a little bit puzzled, probably something in my reasoning is wrong?

![examplerobustnesscorrelation_2](https://cloud.githubusercontent.com/assets/8697436/7219757/798a0926-e6af-11e4-948c-6dd82368eb2b.png)

![examplerobustnesscorrelation](https://cloud.githubusercontent.com/assets/8697436/7219761/8364a7b2-e6af-11e4-8ad6-756e7be49f13.png)

**Comment by EJWagenmakers** [comment]
No, that just looks like a bug; this should never happen. When kappa = 0
the models are identical and BF should be 1. Weird. Alexander, can you help
out?
Cheers,
EJ

**Comment by AlexanderLyNL** [comment]
Hi Quentin, 

Your plot is actually correct. The weird behaviour is due to the large sample size (n=1372). Furthermore, due to the transformation kappa=1/alpha we have two issues to we have to discuss:

1. Scaling: We should not separate the kappas between zero and two equidistantly, that is, don’t use someKappas <- seq(0, 2, by=0.01) or something. 
2. Overflow: There’s an overflow problem at kappa=0. The trick is to hard code the Bayes factor as one for low values of kappa. 

Hence, the line actually dips to 1 beyond that point, but for very low kappa. 

——

Moreover, we should think about the next issue: high n and high r, as the methods we have been using so far break down then. Instead, we should use a Metropolis-Hasting sampler that Marsman wrote. I have to look into this as the proposal distribution yields bad results as kappa goes shrinks. I’ll look into it later this week.

**Comment by jonathon-love** [comment]
just following this one up. should this be closed, or assigned to someone?

**Comment by EJWagenmakers** [comment]
The Marsman sampler should have resolved some of the issues here. Let's
discuss when I'm back.
EJ

**Comment by jonathon-love** [comment]
just following this one up. should this be closed, or assigned to someone?
is this going in the 0.7, or a later release?

**Comment by EJWagenmakers** [comment]
This should go in the 0.7.
Alexander, has the Marsman sampler been implemented to address this issue?
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by AlexanderLyNL** [comment]
The Marsman sampler will probably be implemented in JASP. On a theoretical level, the state system has been implemented .

**Comment by jonathon-love** [comment]
> On a theoretical level, the state system has been implemented.

i'm not sure i understand, but feel free to open a pull-request when ready.

cheers
