### ISSUE TITLE
Bayesian RM ANOVA not working?

### ISSUE THREAD

**Issue by njmedeir** [jasp-stats/jasp-desktop#634]
I'm working with a dataset that has 178 columns and 319 rows. I'm trying to do a Bayesian Repeated Measures ANOVA with a within subjects factor (2 levels) and a between subjects factor (5 levels). I placed my variables in the appropriate places, but nothing shows up in the results/output area except an empty table (and a spinning circle for about 35 minutes). I've attached a screenshot in case that helps. This was on my MacAir running 10.10.3 (and JASP ver 6.6). 

Really loving this product so far and already figuring out how to use it when I teach stats again!

![screen shot 2015-04-22 at 2 32 22 pm](https://cloud.githubusercontent.com/assets/12073692/7284050/7b071b06-e900-11e4-8aaa-1bd330c0663a.png)

**Comment by njmedeir** [comment]
Oops. Looks like I just needed to wait a bit more for the results to show up. I closed other apps and have tried other variables. Looks like it is now taking about 15 minutes per analysis. Sorry for submitting my bug prematurely!

**Comment by jonathon-love** [comment]
not a worry nate! yup, the Bayesian RM ANOVA does take a while. we're looking into ways to speed it up.

cheers

jonathon
