### ISSUE TITLE
C RM ANOVA: Unfortunate error message

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#641]
026_hasfu.csv

![screen shot 2015-04-24 at 12 24 44 pm](https://cloud.githubusercontent.com/assets/3240247/7317084/f571f9ba-ea7c-11e4-9c33-e9f72df89dee.png)

**Comment by jonathon-love** [comment]
and you should look at type I too

**Comment by raviselker** [comment]
Where can I find the csv file?

**Comment by jonathon-love** [comment]
have sent it already, but will resend
