### ISSUE TITLE
Contingency table does not update correctly

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#642]
I did two contingency table analyses. Afterwards, clicking on the output of the first analysis fails to recover the correct input options!
![image](https://cloud.githubusercontent.com/assets/8603015/7318837/3f67947c-ea90-11e4-9358-e56c9f5d4c8c.png)

**Comment by jonathon-love** [comment]
*chuckles*, this turned out to be a pretty serious bug! i think it affects almost all analyses, and has probably existed in JASP since the beginning :P

**Comment by EJWagenmakers** [comment]
Bonus points for EJ! :-)

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
