### ISSUE TITLE
B IS T-Test: Peculiar error, presumably related to the state system

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#645]
To reproduce, open Kitchen Rolls.jasp, then change the Bayesian T-Test to be one tailed

I will send through Kitchen Rolls.jasp

![screen shot 2015-04-25 at 4 14 09 pm](https://cloud.githubusercontent.com/assets/3240247/7333204/218b990e-eb66-11e4-974c-2ef603d41686.png)

**Comment by jonathon-love** [comment]
hey @quentingronau 

is this fixed? one of those issues that gets fixed incidentally? i can't reproduce it now.

**Comment by quentingronau** [comment]
I can't reproduce it either, so I think (hopefully) the issue has been solved with other changes.
