### ISSUE TITLE
graphing means and standard errors in ANOVA

### ISSUE THREAD

**Issue by jamestenns** [jasp-stats/jasp-desktop#654]
many instructors of statistics for behavioural research tell students that one thing SPSS does very badly, in its display of results, is that it emphasizes the outcome of F tests over the pattern that exists among the means and their standard errors.  I could be wrong, because I'm a newbie to JASP, but it appears that JASP is propagating this bad habit.  Short version:  can we expect JASP to display means and standard errors alongside reports of the ANOVA tables in the future (either near or long term)?

**Comment by jonathon-love** [comment]
hi!

the profile plots depict the means and standard errors.

it's possible we could add another table with these values too, but we don't want to overwhelm the user with results or options; and maybe the plots provide exactly what you want any how.

jonathon

**Comment by jamestenns** [comment]
the profile plots are great for 1-way designs.  also for exploring main effects in factorial designs.  Its the interactions among factors that are invisible in the current implementation of plots. There seems to be no way to break down the means for one factor, based on the values of the other factor.

**Comment by jonathon-love** [comment]
*separate lines* doesn't do what you want?

**Comment by jamestenns** [comment]
ahhh...the separate lines and plots work nicely for independent group designs.  And ANCOVA has them as well.  I've learned something and so I'm completely happy there. It's in repeated measures and mixed designs where they disappear. I was fixated there, so should have been clearer all along ...and maybe there is a way to hijack the factorial and ANCOVA programs to do the interaction plots before popping over to the repeated measures, but I haven't been able suss it out yet.

**Comment by jonathon-love** [comment]
ah, yup, we're planning on adding the *Profile plots* to the RM ANOVA in the next release.

**Comment by jamestenns** [comment]
I'm all in then, thanks!  I plan to begin teaching with JASP then in September 2015,

**Comment by jonathon-love** [comment]
awesome! :)

**Comment by jamestenns** [comment]
Is there any update on your comment from May 2015 "ah, yup, we're planning on adding the Profile plots to the RM ANOVA in the next release."?  My stats course begins in Sept and repeated measures ANOVA are an integral part of what students in psychology must learn to do.

**Comment by jonathon-love** [comment]
ooh, we should be able to achieve that. let me attend @raviselker (the RM ANOVA dev) to this.

**Comment by raviselker** [comment]
The profile plots option for the RM ANOVA is available for the current release. We renamed this option though--it's now called "Descriptives Plots"--because we thought this name was a little clearer.

**Comment by jamestenns** [comment]
that’s it.  thanks.  I just had to download the latest version.

**Comment by jamestenns** [comment]
The following 3 factor ANOVA (2 x 2 x 4), for the columns c2-c17 in the attached data set crashes with this message.  Any ideas?  3 factor RM design is beyond the current scope of the program?  Data has 30 rows (subjects) and 16 columns of relevant data (cols c2-c17).  I can get it to run when I set it up as 4 x 2 x 2 (which is incorrect for my data), but not when I specify 2 x 2 x 4 (which is correct).

**Comment by jonathon-love** [comment]
hi james,

could you email me the data set?

jon [at] thon [dot] love

i'm pretty sure this will be fixed in the next release, but i could double check for you.

with thanks

**Comment by jamestenns** [comment]
sorry, here it is.  I thought I had it attached but must have missed it.





The following 3 factor ANOVA (2 x 2 x 4), for the columns c2-c17 in the attached data set crashes with this message. Any ideas?  3 factor RM design is beyond the current scope of the program?  Data has 30 rows (subjects) and 16 columns of relevant data (cols c2-c17).  I can get it to run when I set it up as 4 x 2 x 2 (which is incorrect for my data), but not when I specify 2 x 2 x 4 (which is correct).
