### ISSUE TITLE
ttestpairedsamples.R

### ISSUE THREAD

**Issue by borisma** [jasp-stats/jasp-desktop#655]
Hi, I think there is a problem in the SE Difference and in the Cohen's d of the Paired Sample T-Test in rows 117 and 119 of ttestpairedsamples.R:

SE Difference must be divided by the square root of n, thus:

117     sed <- .clean(sd(c1-c2, na.rm = TRUE)/**sqrt(**length(na.omit(c1-c2)))**)**

Cohen'd: The mean difference must be divided by the SD of the difference variable (otherwise it is Cohen's d for the independent sample t-test). The SD of the difference variable is: sqrt (var(c1) + var(c2) - 2*cov (c1, c2))

Thus, line 119 should read:

119     es <- .clean((mean(c1)-mean(c2))/(sqrt(sd(c1)^2+sd(c2)^2-2*cov(c1, c2)))

current version:
119     es <- .clean((mean(c1)-mean(c2))/(sqrt((sd(c1)^2+sd(c2)^2)/2)))

**Comment by jonathon-love** [comment]
Yup, good catch!

I can quickly make these changes, but if you'd like, you could submit a pull-request. This way your contribution to JASP will be recorded in the git history.

I always like for people to have some credit for their contribution.

Let me know what you'd like

Jonathon

**Comment by borisma** [comment]
Hi Jonathon,

Thanks for the reply. Pull request, why not? Do I have to do it myself or can you do it for me? (I am new to github…).

Best, Boris



Am 05.05.2015 um 12:10 schrieb Jonathon Love <notifications@github.com<mailto:notifications@github.com>>:


Yup, good catch!

I can quickly make these changes, but if you'd like, you could submit a pull-request. This way your contribution to JASP will be recorded in the git history.

I always like for people to have some credit for their contribution.

Let me know what you'd like

Jonathon

**Comment by jonathon-love** [comment]
haha, yeah, it's pretty involved if you've never used git or github before. let me see what i can do.

**Comment by jonathon-love** [comment]
ok, i can put you as the author of the commit, but i'll need your email address.

you can post here, or email me at:

jon [at] thon [dot] cc

**Comment by borisma** [comment]
I updated my profile with email no longer private. Thanks!

**Comment by jonathon-love** [comment]
great! you're now in our contributors page:

https://github.com/jasp-stats/jasp-desktop/graphs/contributors

:)

**Comment by borisma** [comment]
Thanks a lot!!

**Comment by jonathon-love** [comment]
incidentally, what is going down at unibe at the moment? i've seen a big surge in downloads from there.

**Comment by borisma** [comment]
Well, I started to use JASP (only the frequentist part yet) in my introductory statistics lecture... we compare our hand-computed stuff to JASP output, which is when I detected the little inconsistencies...
This is only the start, we are still thinking about the best moment to use mostly JASP for our teaching. It is really such a milestone in academic stats software!

**Comment by borisma** [comment]
Another question: Are there any beta versions to download before the official new version comes out?

**Comment by borisma** [comment]
And another one: why is coyping of results directly into Powerpoint (as a table) not possible? I can go the detour via Word, but then it is inserted in Powerpoint as a kind of Word-macro. I can imagine that it may be difficult to keep all table proportion in ppt, but it would be cool to have that feature.
Also: some students had trouble using JASP on a windows platform. The part where one specifies the analyses is not completely visible, cutting some options. When I install it on the Windows partition of my Mac I get a similar thing, but I can move/drag the field where analyses are specified, so I can reach all options. Some students (especially Windows 8) couldn't, though.

**Comment by jonathon-love** [comment]
> Are there any beta versions to download before the official new version comes out?

we haven't had so far, but i think starting with the next release (0.7) we'll begin doing betas. we're getting to that stage.

> why is coyping of results directly into Powerpoint (as a table) not possible?

yeah, i'm not sure, i've never tried. :P presumably powerpoint doesn't support pasting HTML objects. i will look into what it does support, and see if we can provide something that it can use.

you might like to create a new issue, "Add support for pasting JASP output into powerpoint", that way you will be able to track our progress.

> Also: some students had trouble using JASP on a windows platform. The part where one specifies the analyses is not completely visible, cutting some options

yeah, we're aware of this issue; it's to do with the way that windows handles very high resolution screens. it's actually a *really* difficult issue to solve, and lot's of developers struggle with it, but we really should get onto it soon. #538 

cheers, and it's great you're using JASP in the classroom! keep in touch with your experiences.

jonathon

**Comment by jonathon-love** [comment]
following this one up:

> And another one: why is coyping of results directly into Powerpoint (as a table) not possible?

it *is* possible in Powerpoint 2013

**Comment by borisma** [comment]
Thanks! 
To mention it although there are other threads including this topic: When do you think it will be possible to save analyses? I can imagine that the crucial thing is that if you wanna save them as they are (i.e., still manipulable/changeable, not as pure output), you need to save a connection the data file. Pretty challenging, it seems... Have a nice weekend, 
Boris

**Comment by jonathon-love** [comment]
> I can imagine that the crucial thing is that if you wanna save them as they are (i.e., still manipulable/changeable, not as pure output)

yes, you nailed it. that's been the design goal from the beginning.

we're actually pretty close, this feature will arrive in the 0.7, so perhaps 3 or 4 weeks away.

we're pretty excited about it too :)

jonathon

**Comment by borisma** [comment]
Great! This will be another breakthrough...
