### ISSUE TITLE
State system does not work anymore for plots (t-test, B correlation pairs), maybe also for tables

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#663]

**Comment by quentingronau** [comment]
I think it works for the tables, sorry.

**Comment by jonathon-love** [comment]
i think the issue is that you're not returning state from the init phase. i.e.

line 451 in `ttestbayesianindependentsamples.R` is:

> 		return(list(results=results, status="inited"))

as a result, it assumes the state file is no longer needed, and deletes it.

**Comment by quentingronau** [comment]
Ok, thanks, I will take a look.
It's weird that it worked before though.

**Comment by jonathon-love** [comment]
yeah, i think i changed it so it more aggressively cleans up after itself.

**Comment by quentingronau** [comment]
Hm, so I looked at descriptives, and there you return a "keep" object in the init phase, but not a state object and it seems to work. Maybe I can talk to you tomorrow about that, because at the moment I think I need to change quite some things to deal with the changed state system behavior, but maybe we could look at the current code together, you probaby have a good tip for me, that would be great.

Cheers

**Comment by jonathon-love** [comment]
yup, sure.
