### ISSUE TITLE
Effect sizes

### ISSUE THREAD

**Issue by doramatzke** [jasp-stats/jasp-desktop#665]
@jonathon-love We might want to consider using the escalc() R function in the metafor package to compute effect sizes in all kind of different designs.

**Comment by jonathon-love** [comment]
oh yes, why is this?

**Comment by doramatzke** [comment]
Because we had bugs in the effect size calculations before (standard errors/within-group standard deviations that were not based on the right scores, failing to account for correlations in dependent designs, or something similar). This function is more foolproof I guess, and it gives the Hegdes’g measure, which is an unbiased estimator of the population effect size (vs. Cohen’s d is biased in small samples). Just a thought.

Gr,
d

**Comment by FransMeerhoff** [comment]
This issue is closed due to long inactivity. If this problem still occurs, please reopen it.
