### ISSUE TITLE
C Linear Regression: Collinearity Diagnostics

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#667]
Hi @jonathon-love ,

I am working on the collinearity diagnostics. SPSS displays the VIF and the Tolerance in the coefficients table and the other diagnostics in an own table (see below). I am not completely sure how to handle the variance proportions. SPSS has a two-layer heading to display "Variance Proportions" and the predictors. I know we are using something similar for crosstabs, I think it's done with "combine=TRUE" in the fields? What is your opinion from a user interface perspective, you are the expert: Do you think I should try to mimic SPSS or do you have another idea how to structure the collinearity diagnostics?

Cheers,
Quentin

![collinearityestimates](https://cloud.githubusercontent.com/assets/8697436/7567724/e765626e-f7fe-11e4-93df-8af5df99f8f1.png)
![collinearitydiagnostics](https://cloud.githubusercontent.com/assets/8697436/7567728/eb43b034-f7fe-11e4-83e7-9564534d4c72.png)

**Comment by jonathon-love** [comment]
let's ask @raviselker

**Comment by jonathon-love** [comment]
i don't know, because i'm not really sure what collinearity statistics are, but i'd be fairly confident that the SPSS way is ok.

**Comment by boutinb** [comment]
This issue is closed automatically due to too long inactivity. Please re-open this issue is this problem still occurs.
