### ISSUE TITLE
How to use overTitle also for last column in table?

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#668]
Hi @jonathon-love,

I could need a hint how to use overTitle also for the last column of a table. At the moment, I can
use overTitle if I exclude the last column of a table:

![overtitle1_1](https://cloud.githubusercontent.com/assets/8697436/7634310/6d8c9ed6-fa5a-11e4-80af-d99aaa008849.png)
![overtitle1](https://cloud.githubusercontent.com/assets/8697436/7634312/6e8c8616-fa5a-11e4-9f79-27eda3b44a9f.png)

However, when I want to include the last column, the overTitle disappears:

![overtitle2_1](https://cloud.githubusercontent.com/assets/8697436/7634327/83acff3a-fa5a-11e4-9632-c7d9e0e18e04.png)
![overtitle2](https://cloud.githubusercontent.com/assets/8697436/7634328/898cec3a-fa5a-11e4-838d-988413e72898.png)

Cheers,
Quentin

**Comment by jonathon-love** [comment]
at a guess this is a bug. do you want to commit your code, and i'll take a look.

also, i notice you're using sf:4;dp:2, where as we use sf:4;dp:3 everywhere else. not sure if this was intentional.

**Comment by quentingronau** [comment]
I commited the regression code. In the Coefficients table, I would like to use overTitle for the "Tolerance" and "VIF" columns and center the overTitle "Collinearity Statistics" above them. In the Collinearity Diagnostics table, Iwould like to center the overTitle "Variance Proportions" above the columns with the independent variables. 
"also, i notice you're using sf:4;dp:2, where as we use sf:4;dp:3 everywhere else. not sure if this was intentional."
This was the case because, I was trying the overTitle function using code from crosstabs.

**Comment by jonathon-love** [comment]
yeah, contingency tables are counts, so they're generally greater than 1, which is why we display slightly fewer decimal places. but i think for this one sf:4;dp:3 would be appropriate (unless you think otherwise?)
