### ISSUE TITLE
bell rings when analysis done

### ISSUE THREAD

**Issue by andytwoods** [jasp-stats/jasp-desktop#671]
Just a thought anyway! Those 3-way repeated measures ANOVA take time! :)

**Comment by jonathon-love** [comment]
haha, it's a neat idea. i'll think about it. :)

**Comment by andytwoods** [comment]
Just a thought: like with Statistica, you can 'enter' more than one set of variables into a design-model. JASP then would serially compute each design-model, but perhaps detail the variables entered into each design-model in the results file. 

Perhaps a rare need though (although i think it would be nice to see the variables included at the top of the results).

**Comment by jonathon-love** [comment]
> Perhaps a rare need though

yeah, it's not a bad idea; we do something similar with the simple t-tests, and the contingency tables. i'll give it some thought; my main reluctance is from a desire to keep the ANOVA options simple.
