### ISSUE TITLE
Add facility to copy and paste images from JASP

### ISSUE THREAD

**Issue by lvm3n** [jasp-stats/jasp-desktop#672]
It would be great if plots would be as easy exportable as tables. Now I have to export results and then search (by "inspect element" in web browser) for folder where plots are saved (something like /home/lvm3n/.JASP/temp/21834/3/_141.png).

It would be really nice to make this little easier. 

Thanks!

**Comment by jonathon-love** [comment]
yup, the intention is to add this in 0.7

cheers

**Comment by dropmann** [comment]
this can be closed i think.
