### ISSUE TITLE
Minus sign misaligned with infinity sign?

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#686]
When the output shows "-\infty", the minus sign is located too low. See screenshot.
![image](https://cloud.githubusercontent.com/assets/8603015/7965517/5eb33694-0a1e-11e5-8021-a03cfcda24d2.png)

**Comment by EJWagenmakers** [comment]
Perhaps the font size for that infinity sign could also be increased a notch. But maybe it is my weird laptop.

**Comment by jonathon-love** [comment]
yeah, i'm not sure there's much we can do about this.

**Comment by jonathon-love** [comment]
can't fix :(
