### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by rmwillen** [jasp-stats/jasp-desktop#706]
I get no output. The output window remains the same, with welcome message, regardless of data set (the included example files) and analysis. Now running JASP 0.6.6 in Ubuntu Vivid Vervet, but had same problem with older versions of JASP and Ubuntu. JASP 0.6.6 works fine on my Windows computer. 

![screenshot jasp](https://cloud.githubusercontent.com/assets/12911318/8183065/95dce450-1435-11e5-868a-e03a532c2e90.png)

**Comment by jonathon-love** [comment]
hi,

we only provide 0.6.6 for Ubuntu 14.04 and 14.10, so i would not expect it to work on 15.04

we'll be releasing 0.7 for 15.04 in the coming weeks, so i'd encourage you to wait for that one.

providing different versions for all the different ubuntus, as you can imagine, is a bit of an epic task!

cheers

**Comment by rmwillen** [comment]
Right, but I had the same problem with JASP in Utopic Unicorn. 
I'll be at the SARMAC workshop next week, so maybe we can take a look at it then if you've got time.

**Comment by jonathon-love** [comment]
yup, righto.

under utopic, i think this can be caused by libblas and liblapack not being installed.

if you run JASP at the terminal, and copy the output that is generated there, i might be able to figure it out.

cheers

**Comment by rmwillen** [comment]
you were right - libblas and libapack were not installed. 
sorry for newbie mistake. 
thanks for help!

**Comment by jonathon-love** [comment]
cool! let me know if it works under vervet. i'm not expecting it too, but i'm open to being pleasantly surprised :)

**Comment by rmwillen** [comment]
So far it works totally fine under Vervet! 

I thought libblas and liblapack would be automatically installed when using the Lindeman script, but I never checked until you reminded me of them.

**Comment by jonathon-love** [comment]
hey @lindemann09,

i have a report of your script not installing libblas and liblapack. would you like to follow this up?

cheers

**Comment by lindemann09** [comment]
That's right the installation script didn't ensure that theses packages are installed. That's bug. I fixed it: https://gist.github.com/lindemann09/10ff7d5893dd7006b6d4/revisions

**Comment by jonathon-love** [comment]
awesome!
