### ISSUE TITLE
Bug in opening data

### ISSUE THREAD

**Issue by davidaarmstrong** [jasp-stats/jasp-desktop#708]
I was reading in a .csv file and continued to get an internal error "" (see attached screen shot). You can download the file I was trying to read in from here: 
https://www.dropbox.com/s/zc682b5rxbzhyld/weakliem2.csv?dl=0

![image](https://cloud.githubusercontent.com/assets/4712277/8184757/cf1714a0-1405-11e5-87d1-cdccded7932e.png)

**Comment by davidaarmstrong** [comment]
Sorry, should have left more info about my system. 
![image](https://cloud.githubusercontent.com/assets/4712277/8185051/7c3b7378-1407-11e5-8a97-0107605e9ceb.png)

BTW, the problem also happens when trying to open one of the included datasets.

**Comment by jonathon-love** [comment]
cool, thanks for your report.

do you have RStudio, or R installed? it's possible there may be a 'collision' with these softwares. i thought i had resolved all such issues, but it's possible there's still something outstanding.

i'm guessing you will be unable to open *any* datasets.

could you try running JASP from the terminal, and sending me any output that appears?

with thanks

**Comment by davidaarmstrong** [comment]
I do have both R and RStudio installed. Below is the output after 
starting JASP up from the terminal. Not sure whether or not it matters, 
but most of my packages are installed in a personal library 
(~/Library/R/3.#/library) rather than the global one 
(/Library/Frameworks/R.framework/Versions/3.#/Resources/library).

A colleague sent me a link to the software today and I have to say that 
I'm really excited about it. I've been wringing my hands over what 
software to use with our undergrads and this looks like it will be the 
perfect tool.

Best,
Dave.


./JASP
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_server_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_server_method
qt.network.ssl: QSslSocket: cannot resolve SSL_select_next_proto
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
qt.network.ssl: QSslSocket: cannot call unresolved function 
SSL_get0_next_proto_negotiated
subprocess started
subprocess started
subprocess started
subprocess started
"Warning: namespace ‘BayesFactor’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
"
"Warning: namespace ‘BayesFactor’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
"
"Warning: namespace ‘BayesFactor’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
"
"Warning: namespace ‘BayesFactor’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
"
"Warning: namespace ‘BayesFactor’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
"
"Warning: namespace ‘BayesFactor’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
"
"Warning: namespace ‘BayesFactor’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
"
"Warning: namespace ‘BayesFactor’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
"
"libc++abi.dylib: terminating with uncaught exception of type 
boost::interprocess::interprocess_exception: No such file or directory
"
"libc++abi.dylib: terminating with uncaught exception of type 
boost::interprocess::interprocess_exception: No such file or directory
"
"libc++abi.dylib: terminating with uncaught exception of type 
boost::interprocess::interprocess_exception: No such file or directory
"
"libc++abi.dylib: terminating with uncaught exception of type 
boost::interprocess::interprocess_exception: No such file or directory
"
subprocess error 1
subprocess finished 0
subprocess error 1
subprocess finished 0
subprocess error 1
subprocess finished 0
subprocess error 1
subprocess finished 0
QThread: Destroyed while thread is still running





Jonathon Love wrote:

**Comment by jonathon-love** [comment]
you're not low on disk-space?

**Comment by davidaarmstrong** [comment]
Nope, I have ~2TB free.

**Comment by jonathon-love** [comment]
> A colleague sent me a link to the software today and I have to say that I'm really excited about it. I've been wringing my hands over what software to use with our undergrads and this looks like it will be the perfect tool.

awesome! well hopefully we can get to the bottom of this hiccup!

it is quite peculiar; re-examining the code, i really can't see how it can happen. i will think about it some more.

cheers

**Comment by davidaarmstrong** [comment]
I have a substantively similar setup on my macbook air (OS X 10.10.3) which
has both R and RStudio installed.  The user library structure is the same
and everything works fine.

I tried building JASP from source on my desktop, but can't say that doing
so is really in my wheelhouse.  After a few failed attempts and moving some
files around, I didn't really have time to continue down that rat hole
without much indication that I would ultimately be successful.  Looking
forward to using the software.

Best,
Dave.

**Comment by jonathon-love** [comment]
yeah, it's to do with JASP's use of shared memory. the UI process loads the data set into shared memory, and then separate background processes are responsible for the actual analyses. it appears the background processes are failing to locate the shared memory.

have you/could you try restarting your machine?

**Comment by davidaarmstrong** [comment]
I hadn't tried restarting my machine, but I did that this morning and 
got the same error message.  Happy to do any other diagnostic stuff that 
might be helpful.

Best,
Dave.

**Comment by matthewdye** [comment]
I'm having the same "unexpected internal error" when clicking within a dataset.

![jasperror](https://cloud.githubusercontent.com/assets/16241579/11717328/eac5f2ea-9f1d-11e5-83b0-30d8322bedf9.png)

Running Mac OS X as follows:

![os](https://cloud.githubusercontent.com/assets/16241579/11717400/45db52d8-9f1e-11e5-9e2b-40a7c3410ab0.png)

R and R Studio are not installed. Tried the latest version and ale oa legacy version (0.6.6) -- get the same error.

-- Matt

**Comment by jonathon-love** [comment]
hi @matthewdye 

try upgrading to a more recent version, and let me know if the problem persists.

with thanks

**Comment by matthewdye** [comment]
Hi Jonathon,
0.7.1.12 produces the same behavior.
Cheers -- Matt

**Comment by jonathon-love** [comment]
what if you try the 0.7.5 beta?

with thanks

**Comment by matthewdye** [comment]
0.7.5 beta does not produce the internal error - thanks - but I can't figure out how to bring up the Results window in the right hand pane ...

![jasp_noresults](https://cloud.githubusercontent.com/assets/16241579/11717966/94b5377c-9f21-11e5-8e1a-2bc4afc20300.png)

**Comment by jonathon-love** [comment]
yup, this is broken too. we changed some things in the 0.7.5 which means it's broken in a different way. :/

we've found this bug very challenging to solve, because we've never been able to reproduce it (it only affects a very small number of users)

i'll let you know if we have any break throughs.

with thanks

**Comment by matthewdye** [comment]
OK thanks. Really hoping to use JASP as an entry way into thinking about Bayesian approaches. I have the Kruschke book, but it's not exactly easy reading!

**Comment by boutinb** [comment]
This issue is closed automatically due to too long inactivity. Please re-open this issue is this problem still occurs.
