### ISSUE TITLE
correlation.R

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-desktop#710]
@jonathon-love 

correlation.R on line 763

	p.value <- state$tablePValues[[variable.name]][[column.name]]

Shouldn't this be 

	p.value <- state$tablePValues[[variableIndex]][[column.name]]

**Comment by jonathon-love** [comment]
not sure, maybe check in with @quentingronau

**Comment by quentingronau** [comment]
I think the code is ok. I can index the p-values by name. I only need variableIndex (i.e., a number) to index the rows that are passed via the state system.
