### ISSUE TITLE
B Lin Regression: NaN's without explanation

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#724]
the NaN's in the following screenshot are because one of the independents contain infinity. we always try and explain why a value can't be calculated.

![screen shot 2015-06-18 at 8 46 27 pm](https://cloud.githubusercontent.com/assets/3240247/8239297/3a06b9d6-15fb-11e5-8f8c-8a1a231df3d2.png)

cheers

**Comment by mmarsman1** [comment]
This is strange, as I tested that issue a long time ago and it was properly handled at the time.

Do we throw an error, a note, or do we delete lines?

**Comment by mmarsman1** [comment]
Let's do an error, as it is likely that it affects multiple BFs.

**Comment by jonathon-love** [comment]
yeah, that's a good idea in this instance.

**Comment by mmarsman1** [comment]
Okay, this should fix it. 

Remains strange, as my notorious file number 3 breaks this.
