### ISSUE TITLE
B IS T-Test: Could have a few small tweaks

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#727]
ultra-low priority, but here's a couple of tweaks that would make it nicer:

* checking, and unchecking *Prior and posterior*, or *Descriptives* places a loading indicator on the table (when it doesn't change)
* checking/unchecking "Additional info" re-does the descriptives plot
* changing Bayes factor type re-runs the whole analysis, when only the first table needs to change (see if you can do this in the init phase. store the BFs in the state system, and then you can calculate the new values without looking at the data)

**Comment by quentingronau** [comment]
Sorry, I was a little bit confused and did not refer to this issue in my commit: Commit #797 fixes this issue.
