### ISSUE TITLE
B Corr Pairs: Issue with plots

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#738]
hey @quentingronau 

i found this issue, it worked fine in the 0.6.6

doesn't seem to matter what data is used

![screen shot 2015-06-20 at 9 49 12 am](https://cloud.githubusercontent.com/assets/3240247/8266505/041416e2-1732-11e5-8139-182d50159c0f.png)

**Comment by quentingronau** [comment]
Oh, I am sorry, I just realized that Alexander renamed the output of .posteriorBetaParameters which is the reason why the plot produces the error because the a and b parameter cannot be found. I will fix it...
