### ISSUE TITLE
B Corr Matrix: Doesn't mark the analysis as complete when complete in the init phase

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#742]
If the analysis is completed in the init phase, then it can return a status of "complete". this prevents an unnecessary run phase (running quicker, and preventing the blinking run indicator).

more info here:

https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/r-analyses-guide.md

**Comment by boutinb** [comment]
@AlexanderLyNL Can you do it?
