### ISSUE TITLE
Bayesian Correlation Matrix fails to produce posterior distribution 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#743]
For the presidents example, an attempt to plot the posterior distribution results in an error:
![image](https://cloud.githubusercontent.com/assets/8603015/8268143/8cdfc118-177a-11e5-8426-3872107d609a.png)

**Comment by jonathon-love** [comment]
yeah, we already found and fixed this. slipped through due to the very last minute-ness of the work. i have produced a 0.7 Beta 2 for OSX, and am in the process of making Beta 2's for Windows and Linux.

duplicate #738

**Comment by EJWagenmakers** [comment]
I downloaded the latest version (beta2) and I *still* get this error. Note: it is under Bayesian correlation *matrix*, and happens whenever "posteriors under H1" is ticked.

**Comment by jonathon-love** [comment]
Fixed
