### ISSUE TITLE
Help functionality

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#744]
I see the button "Help", and I click it, but whenever I do so I never see any actual text with an explanation -- all I see is a white area.
![image](https://cloud.githubusercontent.com/assets/8603015/8272518/e1b983ba-1845-11e5-9696-46f248c647d1.png)

**Comment by jonathon-love** [comment]
yup, @dropmann is onto this. only affects windows versions.

**Comment by jonathon-love** [comment]
fixed
