### ISSUE TITLE
Do not install JASP on platforms that are not supported

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#748]
Some people complain that JASP does not work, only to learn later that some (ancient) OS's are simply not supported. It would be more efficient to check the OS and only proceed with the installation when the OS is in order. An exception could be made for Linux I guess, because who knows whether it will work, but for Windows and the Mac, we might want to build this in so people don't get frustrated and we don't have needless work answering the Emails.

**Comment by jonathon-love** [comment]
i think this is only an issue under older versions of OS X (to download JASP for OS X, you have to click a link which says *JASP for 10.8 and above*), and i think the latest beta uses the mechanism in OS X to notify users that it isn't compatible.

do you know of any other situations where this is a problem?

**Comment by EJWagenmakers** [comment]
We just had a few complaints from someone using Vista. In general, simply
not installing it on unsupported platforms is better than telling people.
Don and Sarahanne both managed to install JASP on unsupported platforms. We
should simply not allow installation on platforms that won't make it work.
If we can issue a warning we can also simply refuse the install.
EJ

**Comment by jonathon-love** [comment]
yeah, it should work fine under vista.

> In general, simply not installing it on unsupported platforms is better than telling people.

we support all windows platforms from XP onwards, and only windows uses an *installer*. neither OS X or Linux have an installation process. under OS X, you just copy it to your Applications directory (this is standard installation procedure under OS X) trying to launch it under OS X tells them that it isn't compatible (in the latest beta).

**Comment by EJWagenmakers** [comment]
OK
