### ISSUE TITLE
Shifting panels

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#750]
I ran a Bayesian two-sample t-test. Then I clicked on a different analysis (one-sample t-test, I think), and suddenly my input panel shifted to the left, so that a quarter of the input area is no longer visible. Weird -- I know it might be my laptop, but still, worth checking whether this behavior occurs for others as well.
![image](https://cloud.githubusercontent.com/assets/8603015/8302778/73824152-1999-11e5-83e1-299574c3be34.png)

**Comment by EJWagenmakers** [comment]
Well maybe it isn't a quarter that's being cut off, but still, it is unwanted behavior. I should stress that this behavior (the panel being cut off at the left) is now present for all analyses. So I'll have to quite the program and hopefully go back to normal.

**Comment by EJWagenmakers** [comment]
It seems this shift occurs only when there is a figure in the output panel.

**Comment by EJWagenmakers** [comment]
But after it has shifted I cannot unshift it. See screenshot.
![image](https://cloud.githubusercontent.com/assets/8603015/8303058/6e3307ac-199b-11e5-93b4-45dcaec66a18.png)

**Comment by jonathon-love** [comment]
yeah, that is interesting. none of that code has changed, so this has probably been present in JASP from the beginning. we just need to find the circumstances under which it occurs :/

**Comment by jonathon-love** [comment]
did you have the help system open when this happened? (if so, that would explain how we've not seen it before.)

**Comment by EJWagenmakers** [comment]
Maybe! I will look into it

**Comment by boutinb** [comment]
This issue is closed due to too long inactivity. Please re-open this issue is this problem still occurs.
