### ISSUE TITLE
Beta* prior width in Bayesian correlation *pairs* can be silly

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#751]
Can we make it so that "Beta* prior width" (in the Bayesian correlation pairs) does not accept negative numbers? This restriction has been implemented in the Bayesian correlation *matrix*, but not in pairs.
![image](https://cloud.githubusercontent.com/assets/8603015/8302928/75b58ae6-199a-11e5-9c84-978a9c440cdf.png)

**Comment by jonathon-love** [comment]
sure.
