### ISSUE TITLE
Copying and pasting citations into Word places them all on one line.

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#755]
When Richard demonstrated the citation functionality, the three citations for ANOVA "ran together" (no empty line separating the citations). Can we add those empty lines?

**Comment by jonathon-love** [comment]
yeah, this is actually a problem with Word, but we should be able to work around it.

**Comment by jonathon-love** [comment]
hey @dropmann,

if you paste the citations into Word, i think they're interpreted as HTML, which means new line characters are ignored. This results in three separate citations being placed on a single line. (In contrast, if you paste them into notepad, they come out fine).

could you take a look at this?

**Comment by dropmann** [comment]
Hey, it works fine for me here when i paste it into word, libre writer, notepad++ and notepad. I tested both beta 4 and my branch. Any hints on where else i should try?

**Comment by jonathon-love** [comment]
are you copy/pasting multiple citations? if you copy/paste from the Bayesian analyses there will be multiple citations (across multiple lines).

**Comment by dropmann** [comment]
yep, i was copying/pasting from the Bayesian analyses and getting three separate citations across three lines, each separated by an empty line.

**Comment by jonathon-love** [comment]
hmm, seems to be a Word for OSX issue. i can solve it by sending the cites as HTML to the clipboard. is it possible to send both HTML and text to the clipboard at the same time?

**Comment by dropmann** [comment]
I'll look into it.

**Comment by jonathon-love** [comment]
incidentally, pasting into libreoffice with cites surrounded by `<p>` tags does work more nicely. it invokes the paragraph formatting, and you don't need the extra new line character to separate things visually.

i.e.

<img width="867" alt="screen shot 2015-07-09 at 11 05 35 am" src="https://cloud.githubusercontent.com/assets/3240247/8598771/a49652ea-262a-11e5-82f1-d226395485e2.png">

the former is from HTML, and the latter is from text (it is perhaps not the clearest illustration :P ). the latter has an additional empty line (which the user will want to remove, and then manually adjust the paragraph spacing), where as the former has no empty line and has used the default paragraph spacing [desired].

(i assume pasting plain text changes the paragraph spacing to be zero, so as to be consistent with the source document, where as pasting HTML retains the target document's formatting [desired])

however, pasting html into Word (on OSX at least) does override the font to be sans-serif (i think you specify this in the export code). it would be nice if we could specify no font, so pasting into Word uses Word's defaults (but at the same time, retain the sans-serif in the HTML which is produced by the export button :P ).

this is all pretty involved! who would have thought copy/paste would be such a debacle!

**Comment by dropmann** [comment]
So i have done the format preservation or relaxing, but i'm not super clear as to what you are wanting to do with this citation issue/benefit. I feel like you would like citations to be copied as HTML?

**Comment by jonathon-love** [comment]
ideally, they'd be pushed as both html and text, but they can be pushed as just html if that would be easier.
