### ISSUE TITLE
Descriptive plots for Bayesian and classical tests

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#756]
The "Bayesian correlation pairs" needs a plot showing the data. Same for the Bayesian t-test, and the classical versions. Ravi created some nice descriptive plots for ANOVA, but we need these *everywhere*! Maybe Quentin can create the plots for correlation, and Ravi can create them for the tests involving means? I want to stress this functionality a bit, because I am discovering that if you want to present the results of an experiment, you need both a plot of the data (with CIs, for instance) and the inferential stats. Trying to do all the descriptive stuff under "Descriptives" is impossible and confusing.

**Comment by jonathon-love** [comment]
@quentingronau, do you want to take a look at this? @raviselker can probably kit you out with plots.

**Comment by quentingronau** [comment]
Hi,

I implemented a scatterplot for the Bayesian correlation pairs. With regard to the T-Tests: Ravi implemented plots for the classical T-Tests which show the mean(s) and (a) confidence interval(s) for the mean(s) (in case of the paired T-Test, the confidence interval is adjusted, I think). They look like this:

![descriptivesttestplot_one](https://cloud.githubusercontent.com/assets/8697436/9378637/49e851a8-4723-11e5-95bc-b2b130b1e14f.png)
![descriptivesttestplot_ind](https://cloud.githubusercontent.com/assets/8697436/9378640/50098cb4-4723-11e5-8cf5-4f8764da34a9.png)

@EJWagenmakers: How would you like the descriptives plots to look for the Bayesian T-Tests?

Cheers,
Quentin

**Comment by EJWagenmakers** [comment]
I think it is easiest to have the plots look the same, but use an x%
credible interval instead of an x% confidence interval. Because it is a
descriptive plot (more or less), I think we should obtain the credible
interval by assuming, for each condition, that the data come from a normal
distribution with unknown mean and variance, with uninformative priors. It
may be the case that this gives the same numerical results as the classical
interval, for this specific scenario. In the future perhaps we could also
plot the entire distribution as a violin (a tick box for the user). This
would highlight the additional inferences that a Bayesian can make.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by quentingronau** [comment]
Hi,

Ok, assuming Jeffreys prior (p(mu, sigma^2) proportional to 1/sigma^2), I can evaluate the marginal posterior of mu analytically (it's a shifted t-distribution, compare Gelman et al., p.67) which makes it easy to compute the credible interval:

![marginalmu](https://cloud.githubusercontent.com/assets/8697436/9381352/cacbd25a-4736-11e5-99c8-826388e394e2.png)

For the paired t-test, do you think it is appropriate to do this for both groups separately? Maybe a bivariate model which allows a correlation between the observations might be more appropriate although more difficult to implement. Assuming again Jeffreys prior (in this case for bivariate data), the marginal posterior distribution of mu would be a bivariate shifted t distribution:

![marginalmu2](https://cloud.githubusercontent.com/assets/8697436/9381487/110bbcf2-4738-11e5-9c78-ee0220ecdc8b.png)

However, I am not sure how to report the credible interval then. What do you think?

**Comment by EJWagenmakers** [comment]
I would argue we present this for any of N groups, so it can be used for
ANOVA as well. So then we go for N groups separately. Now Maarten believes
this is silly and we should use the model to inform the estimates, but I
think we can leave this for later.

Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by quentingronau** [comment]
Ok. I implemented the plots for the three Bayesian T-Tests.
Cheers,
Quentin

**Comment by boutinb** [comment]
This issue is closed due to too long inactivity. Please re-open this issue is this problem still occurs.
