### ISSUE TITLE
Weird characters

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#757]
I love this bug. I had a file open in JASP (AdamSandler.jasp; I'll send this over Email). Then I started a new JASP process, and tried to open the same file (I forgot I had already opened it). By the way, working on the same file could cause conflicts -- have we thought about this? Anyway, that file is messed up: 
![image](https://cloud.githubusercontent.com/assets/8603015/8359432/2034c992-1b1b-11e5-86d7-d8c42a7f451e.png)

**Comment by jonathon-love** [comment]
> By the way, working on the same file could cause conflicts -- have we thought about this?

shouldn't really be a problem, but it makes sense to handle it a bit differently to how we have.

> Anyway, that file is messed up

yup. if you look at the screenshot, you'll notice that you've opened it in JASP 0.6.5, which can't handle .jasp files and is treating it as a CSV file.

in hindsight, we should have added some more smarts to the earlier versions of JASP to not open non-csv files.

**Comment by jonathon-love** [comment]
> in hindsight, we should have added some more smarts to the earlier versions of JASP to not open non-csv files.

actually, there *are* smarts in the earlier versions of JASP to not open non-csv files, but the recent items list bypasses them.

**Comment by jonathon-love** [comment]
can't fix.
