### ISSUE TITLE
Post hoc analyses for ANOVA

### ISSUE THREAD

**Issue by goshengott** [jasp-stats/jasp-desktop#758]
Probably the most frequently used post hoc test is the Tukey HSD test.  Can you please implement it in your package.
Likewise, the Schefe test, which is very similar to contrast analysis, but with a more conservative rejection area, should be implemented.
Both of these appear in all standard textbooks

**Comment by jonathon-love** [comment]
hey @raviselker,
tukey HSD seems like a good idea.

**Comment by goshengott** [comment]
Thanks.  Not to belabor the point, Schefe is a variation on contrast
analysis and should entail 4 lines of code (the question, as EJ says, is
what are the lines)
Jonathan

On Fri, Jun 26, 2015 at 8:41 AM, Jonathon Love <notifications@github.com>
wrote:

> hey @raviselker <https://github.com/raviselker>,
> tukey HSD seems like a good idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasp-stats/jasp-desktop/issues/758#issuecomment-115735702>
> .
>



-- 
----------------------------------------------------
Prof. Yonatan Goshen-Gottstein
Department of Psychology
Tel-Aviv University, Ramat Aviv
69978
Mobile +972 544-787614

**Comment by raviselker** [comment]
I will look into both tests.

**Comment by Greenmat** [comment]
I am also looking forward to seeing both Tukey HSD and Scheffé implemented, thanks!

**Comment by jonathon-love** [comment]
implemented! will be in the next release.

**Comment by goshengott** [comment]
Thank you so much!!!!!

On Thu, Aug 20, 2015 at 4:57 PM, Jonathon Love <notifications@github.com>
wrote:

> implemented! will be in the next release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasp-stats/jasp-desktop/issues/758#issuecomment-133017078>
> .
>



-- 
----------------------------------------------------
Prof. Yonatan Goshen-Gottstein
Department of Psychology
Tel-Aviv University, Ramat Aviv
69978
Mobile +972 544-787614

**Comment by Greenmat** [comment]
Thank you mate!!

**Comment by goshengott** [comment]
Dear Jonathon,

So again, I thank you.  I am having trouble accessing the program for
writing in additional ideas for future development, so I am taking the
liberty of writing you directly.

I was on the verge of moving my class to JASP, when I noticed the following
difficulties. So alas, I'll wait till next year.

Thank you,

Yonatan


A) Planned contrast analysis

1) Contrast analysis is available for between-subjects designs.
Within-subjects designs are more prevalent, and planned comparisons need be
available for these too.

2) There is no possibility to assign weights to the contrast analysis.
Assigning weights is critical to conduct planned comparisons and to ensure
the orthogonality of the comparisons. A planned comparison uses the error
factor of the omnibus ANOVA and cannot be replaced by any other procedure.
For example, in a one-way ANOVA with three levels, a planned comparison
should be available for A1 vs. A2 + A3, corresponding to weights 2, -1, -1.
Or with 5 levels, a contrast of -3, -3, 2, 2, 2 should be available. In
standard programs, the user plugs in the weights, whose sum is
1, corresponding to the required hypothesis.

3) Likewise, in a two-way ANOVA with two factors (A, three levels, and B,
two levels),  a planned comparison should be available for both variable A
(for example A1 vs. A2 + A3), variable B (B1 vs. B2) and variable A within
a single level of variable B (A1 vs. A2 + A3 within level B1).


B) Simple effects

Even though the ANOVA with multiple variables is available, there is no
possibility to conduct follow-up simple effects. Simple effects (i.e.,
ANOVA for an independent variable within one specific level of another
independent variable) is a critical analysis to elucidate the nature of an
interaction. A simple effects analysis in factorial ANOVA uses the error
factor of the omnibus ANOVA and  cannot be replaced with a one-way ANOVA or
t-tests.


C) Non parametric tests

Kruskal-Wallis

Friedman ANOVA

Wilcoxon matched pair test

Sign test


Thank you,

Yonatan

On Thu, Aug 20, 2015 at 5:49 PM, goshengott . <goshengott@gmail.com> wrote:

> Thank you so much!!!!!
>
> On Thu, Aug 20, 2015 at 4:57 PM, Jonathon Love <notifications@github.com>
> wrote:
>
>> implemented! will be in the next release.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jasp-stats/jasp-desktop/issues/758#issuecomment-133017078>
>> .
>>
>
>
>
> --
> ----------------------------------------------------
> Prof. Yonatan Goshen-Gottstein
> Department of Psychology
> Tel-Aviv University, Ramat Aviv
> 69978
> Mobile +972 544-787614
>
>
>


-- 
----------------------------------------------------
Prof. Yonatan Goshen-Gottstein
Department of Psychology
Tel-Aviv University, Ramat Aviv
69978
Mobile +972 544-787614

**Comment by jonathon-love** [comment]
thanks for the feedback yonatan,

pretty much all the features you list are on our todo list. hopefully we can have them ready for you for next year!

you have to admit it's remarkable we provide as much as we do, given how briefly the project has existed, and how few full time people we have :)

cheers, and thanks

**Comment by goshengott** [comment]
Jonathon,
Absolutely!!  It is remarkable how much you've gotten done.  In my mind's
eye,  I was about to convince my university to stop the purchase of some of
the software packages,  and fly you over to Tel Aviv for a tutorial .  It
looks like this will have to wait a bit.  There is no way you'll say no to
Tel Aviv.  Right?
Yonatan

**Comment by jonathon-love** [comment]
> There is no way you'll say no to Tel Aviv. Right?

certainly not! :)
