### ISSUE TITLE
Cannot read all levels when specifying repeated measures cells

### ISSUE THREAD

**Issue by JasonFriedman** [jasp-stats/jasp-desktop#759]
I tried to run an RM ANOVA, and chose descriptive level names, e.g.
factor1 has levels Congruent and Incongruent
factor2 has levels Target and Distractor
factor3 has levels Left and Right
etc

In the right half of the section "Repeated Measures Cells"  where it tells me which column I need to select (e.g. Congruent Distractor Left), the text is cut off (it shows ...) and I could not find any way to read the whole line.

**Comment by jonathon-love** [comment]
thanks for the report. i'll look into ways we can solve this.

in the mean time, you can choose shorter level names (you can also drag the divider to the left to give you a little more space).

cheers
