### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by MarioDalmaso** [jasp-stats/jasp-desktop#761]
I love JASP, but I was thinking that an auto-update option or at least a newsletter with news etc. could be helpful.

Many thanks, cheers
Mario

**Comment by jonathon-love** [comment]
yup, this is a good idea. this is certainly on the todo list.

**Comment by MarioDalmaso** [comment]
Many thanks,
Mario

**Comment by boutinb** [comment]
There is also a forum http://forum.cogsci.nl/index.php?p=/categories/jasp-bayesfactor.
But a newsletter would be indeed a nice idea...
