### ISSUE TITLE
Make JASP compileable on Debian

### ISSUE THREAD

**Issue by MaxG87** [jasp-stats/jasp-desktop#764]
Hi,
I tried to compile JASP on Debian Testing today but I couldn't finish since there is no 'boost nowide' package available. Compilation stops when needing 'uuid.hpp'. Since I run 32Bit Debian I could not even install the precompiled versions you provide.

Is there anything I've overlooked in order to compile it cleanly? If not, I would be happy about several points:
  * Could you please provide Linux 32Bit versions of JASP.
  * Could you please improve the documentation about how to compile JASP, i.e. noting that one has to call 'qmake' before 'make' and how exactly.
  * Could you please make it compatible to Debian for example by providing the needed libraries not available as a package. Then, as far as I know, you should be compatible to Ubuntu anyway.

Thank you very much for your effort and your help.
sincerely,
Max

**Comment by jonathon-love** [comment]
hi!

> Could you please provide Linux 32Bit versions of JASP.

yes, we would love to, but as you can imagine, supporting all the different linux configurations becomes quite a burden, and our resources are limited. hopefully some of distro communities will pick us up at some point.

> Could you please improve the documentation about how to compile JASP, i.e. noting that one has to call 'qmake' before 'make' and how exactly.

oh yes, we can make a note of that. none of our team use qmake directly (we all use QtCreator), so we've never ever done this, but i should sit down and do this at some point.

> Could you please make it compatible to Debian for example by providing the needed libraries not available as a package.

nowide is available here: http://cppcms.com/files/nowide/nowide.zip

thanks for your feedback!

jonathon

**Comment by MaxG87** [comment]
I tried a bit harder to compile jasp on Debian Testing 32Bit.

I copied the nowide library into '/usr/local/include' which solved quite a few
issues. Nonetheless, my opinion is that since boost-nowide is packaged neither
for Debian nor for Ubuntu it could be shipped with the jasp project for
convenience. Not everyone has the opportunity to drop stuff into system
directories, though.

First I tried to compile it using command line. I issued a

    qmake -project && qmake && make 2> err_out

but it fails when building analysis.cpp. The error messages (i.e. err_out) can
be found under https://paste.ee/p/hAuVu for the next week.

Furthermore, I tried to build it with QtCreator. Unfortunately it also fails.
The relevant part of the error message is:

    cd JASP-Engine/ && /usr/bin/make -f Makefile 
    make[1]: Entering directory '/home/username/Projekte/build-JASP-Desktop-Debug/JASP-Engine'
    CMD INSTALL --library=/library /home/username/Projekte/jasp-desktop/JASP-Engine/JASP
    Makefile:186: recipe for target 'RPackage' failed

The problem is, that the path to the R executable (i.e. R_EXE from JASP-Engine.pro; It may be because $OUT_PWD resolves empty on my system.) is empty. I installed R by

    sudo aptitude install r-base

I hope that these information help you to make jasp compileable on Debian.

**Comment by jonathon-love** [comment]
> The problem is, that the path to the R executable (i.e. R_EXE from JASP-Engine.pro; It may be because $OUT_PWD resolves empty on my system.) is empty.

hmm, this is all pretty strange. i don't use debian, and i don't have any of these issues on ubuntu. i'm not really sure what else to recommend.

`$OUT_PWD` resolving to empty is really strange, i can't think why that would happen.

i will think about it.

**Comment by MaxG87** [comment]
I tried the commands `echo $PWD` and `echo $OUT_PWD` on a terminal emulator on several systems (Debian Testing, Ubuntu 15.04, Neurodebian, Mint 17)

`echo $PWD` behaved everywehre as expected.

`echo $PWD` was empty everywhere. Below is a copy of the output:

    ~$ echo $OUT_PWD
    
    ~$

I hope this helps a bit.

**Comment by jonathon-love** [comment]
hmm, in this instance, OUT_PWD should be provided by qmake, i.e.

http://doc.qt.io/qt-5/qmake-variable-reference.html

you could try substituting OUT_PWD with something completely different, assigning an absolute path to it, and then seeing if that would work.

cheers

**Comment by jonathon-love** [comment]
hey, just FYI, i'm working on this at the moment.

i'm hoping to make a debian source package that i can put into a PPA, and hopefully after that, into the debian repos themselves!

**Comment by MaxG87** [comment]
That sounds great.
If you need someone to test a deb-package or to test the build scripts just let me know.

**Comment by jonathon-love** [comment]
hi,
JASP is now available in a PPA.

https://launchpad.net/~jonathon-love/+archive/ubuntu/jasp

you should be able to

    apt-get source jasp

to get the source package

**Comment by MaxG87** [comment]
Hi,
I fear that did not do the trick. apt-get can't find the i386-version of the package, but I'm not sure it would find a amd64-version since apt-get looks in Debian specific folders.

I'll dump bash output here:

    sudo add-apt-repository ppa:jonathon-love/jasp
    You are about to add the following PPA to your system:

     More info: https://launchpad.net/~jonathon-love/+archive/ubuntu/jasp
    Press [ENTER] to continue or ctrl-c to cancel adding it

    gpg: keyring `/tmp/tmpclmnf_ws/secring.gpg' created
    gpg: keyring `/tmp/tmpclmnf_ws/pubring.gpg' created
    gpg: requesting key 43751C3B from hkp server keyserver.ubuntu.com
    gpg: /tmp/tmpclmnf_ws/trustdb.gpg: trustdb created
    gpg: key 43751C3B: public key "Launchpad PPA for Jonathon Love" imported
    gpg: Total number processed: 1
    gpg:               imported: 1  (RSA: 1)
    OK
    ~$ sudo apt-get update
    OK   http://neurodebian.ovgu.de data InRelease
    OK   http://neurodebian.ovgu.de jessie InRelease
    OK   http://debian.morphium.info testing InRelease
    Ign http://ppa.launchpad.net stretch InRelease
    OK   http://security.debian.org testing/updates InRelease
    OK   http://neurodebian.ovgu.de data/contrib i386 Packages
    Ign http://ppa.launchpad.net stretch Release.gpg
    OK   http://neurodebian.ovgu.de data/main i386 Packages
    Ign http://ppa.launchpad.net stretch Release
    Holen: 1 http://debian.morphium.info testing/main Sources/DiffIndex [7.876 B]
    OK   http://neurodebian.ovgu.de data/non-free i386 Packages
    OK   http://neurodebian.ovgu.de jessie/main i386 Packages
    OK   http://neurodebian.ovgu.de jessie/contrib i386 Packages
    OK   http://neurodebian.ovgu.de jessie/non-free i386 Packages
    OK   http://security.debian.org testing/updates/main Sources
    Holen: 2 http://debian.morphium.info testing/non-free Sources/DiffIndex [7.819 B]
    OK   http://security.debian.org testing/updates/contrib Sources
    Holen: 3 http://debian.morphium.info testing/contrib Sources/DiffIndex [6.025 B]
    OK   http://security.debian.org testing/updates/non-free Sources
    OK   http://security.debian.org testing/updates/main i386 Packages
    Holen: 4 http://debian.morphium.info testing/main i386 Packages/DiffIndex [7.876 B]
    Holen: 5 http://debian.morphium.info testing/non-free i386 Packages/DiffIndex [7.819 B]
    Holen: 6 http://debian.morphium.info testing/contrib i386 Packages/DiffIndex [7.819 B]
    Holen: 7 http://debian.morphium.info testing/contrib Translation-en/DiffIndex [3.817 B]
    Holen: 8 http://debian.morphium.info testing/main Translation-en/DiffIndex [7.876 B]
    Holen: 9 http://debian.morphium.info testing/non-free Translation-en/DiffIndex [4.507 B]
    OK   http://security.debian.org testing/updates/contrib i386 Packages
    OK   http://security.debian.org testing/updates/non-free i386 Packages
    OK   http://security.debian.org testing/updates/contrib Translation-en
    OK   http://security.debian.org testing/updates/main Translation-en
    OK   http://security.debian.org testing/updates/non-free Translation-en
    Fehl http://ppa.launchpad.net stretch/main i386 Packages
      404  Not Found
    Ign http://ppa.launchpad.net stretch/main Translation-de_DE
    Ign http://ppa.launchpad.net stretch/main Translation-de
    Ign http://ppa.launchpad.net stretch/main Translation-en
    Es wurden 61,4 kB in 1 s geholt (33,3 kB/s).
    W: Fehlschlag beim Holen von http://ppa.launchpad.net/jonathon-love/jasp/ubuntu/dists/stretch/main/binary-i386/Packages  404  Not Found

    E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.
    ~$ sudo apt-get source jasp
    Paketlisten werden gelesen... Fertig
    Abhängigkeitsbaum wird aufgebaut.
    Statusinformationen werden eingelesen.... Fertig
    E: Quellpaket für jasp kann nicht gefunden werden.

**Comment by MaxG87** [comment]
Since there is this PPA now, I tried to build the repo by myself. Unfortunately there are still errors.

If I use QTCreator 3.4.1 (from testing-repos) I can build JASP-Common. Building JASP-Desktop failed. First it failed because QNetworkAccessManager could not be found. This was resolved by adding "network" at the end of the QT += … - list.
Then QLockFile was not found. I was unable to resolve this. Since QLockFile does exist on my PC I think the error caused by QtCreator not handling the installation of (parts of) Qt4 and Qt5 correctly. This may be just an configuration problem but I could not resolve it. I am unable to remove Qt4 since it is a dependencie of KDE/Plasma 5 on Debian/testing.

I also tried to build JASP from the command line (using a fresh git-clone, of course). Here even JASP-Common can't be build. I append a bash log and link to a log of the error messages.

    ~/Downloads/Quellcodes/jasp-desktop$ qmake -project
    ~/Downloads/Quellcodes/jasp-desktop$ qmake
    RCC: Warning: No resources in 'JASP-Desktop/resources/win/stylesheets.qrc'.
    ~/Downloads/Quellcodes/jasp-desktop$ make 2> errout
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/backstageform.ui -o ui_backstageform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/mainwindow.ui -o ui_mainwindow.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/optionsform.ui -o ui_optionsform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/ancovabayesianform.ui -o ui_ancovabayesianform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/ancovaform.ui -o ui_ancovaform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/ancovamultivariateform.ui -o ui_ancovamultivariateform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/anovabayesianform.ui -o ui_anovabayesianform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/anovaform.ui -o ui_anovaform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/anovamultivariateform.ui -o ui_anovamultivariateform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/anovaonewayform.ui -o ui_anovaonewayform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/anovarepeatedmeasuresbayesianform.ui -o ui_anovarepeatedmeasuresbayesianform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/anovarepeatedmeasuresform.ui -o ui_anovarepeatedmeasuresform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/contingencytablesbayesianform.ui -o ui_contingencytablesbayesianform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/contingencytablesform.ui -o ui_contingencytablesform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/correlationbayesianform.ui -o ui_correlationbayesianform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/correlationbayesianpairsform.ui -o ui_correlationbayesianpairsform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/correlationform.ui -o ui_correlationform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/correlationpartialform.ui -o ui_correlationpartialform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/descriptivesform.ui -o ui_descriptivesform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/r11tlearnform.ui -o ui_r11tlearnform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/regressionlinearbayesianform.ui -o ui_regressionlinearbayesianform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/regressionlinearform.ui -o ui_regressionlinearform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/semsimpleform.ui -o ui_semsimpleform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/ttestbayesianindependentsamplesform.ui -o ui_ttestbayesianindependentsamplesform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/ttestbayesianonesampleform.ui -o ui_ttestbayesianonesampleform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/ttestbayesianpairedsamplesform.ui -o ui_ttestbayesianpairedsamplesform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/ttestindependentsamplesform.ui -o ui_ttestindependentsamplesform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/ttestonesampleform.ui -o ui_ttestonesampleform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/analysisforms/ttestpairedsamplesform.ui -o ui_ttestpairedsamplesform.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/ribbons/ribbonanalysis.ui -o ui_ribbonanalysis.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/ribbons/ribbonhome.ui -o ui_ribbonhome.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/ribbons/ribbonr11tlearn.ui -o ui_ribbonr11tlearn.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/ribbons/ribbonsem.ui -o ui_ribbonsem.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/widgets/anovamodelwidget.ui -o ui_anovamodelwidget.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/widgets/boundassignwidget.ui -o ui_boundassignwidget.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/widgets/datasetselectwidget.ui -o ui_datasetselectwidget.h
    /usr/lib/i386-linux-gnu/qt4/bin/uic JASP-Desktop/widgets/progresswidget.ui -o ui_progresswidget.h
    g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -IJASP-Common -IJASP-Common/options -IJASP-Common/lib_json -IJASP-Common/base64 -IJASP-Common/importers -IJASP-Common/libzip -IJASP-Desktop -IJASP-Desktop/widgets -IJASP-Desktop/analysisforms -IJASP-Common/exporters -IJASP-Engine -IJASP-Desktop/ribbons -I. -I. -o analysis.o JASP-Common/analysis.cpp
    Makefile:6970: recipe for target 'analysis.o' failed

The errlog file can be found under https://paste.ee/p/AOpst for the next week.

**Comment by jonathon-love** [comment]
yeah, JASP requires Qt5. you would need to find a way to prevent your system from invoking Qt4 tools. isn't there some qt-chooser, or like application? i'm not sure.

it's a shame there's not a debian equivalent of launchpad, otherwise this would be really easy.

**Comment by jonathon-love** [comment]
keeping you in the loop, i'm expecting to have JASP in debian repos within a fortnight. i just have to bundle a pile of R packages first. you can follow my progress here:

https://bugs.debian.org/cgi-bin/pkgreport.cgi?dist=unstable;submitter=jon%40thon.cc

**Comment by Argafal** [comment]
I am also trying to compile JASP on Linux (Debian). Any news? It's certainly been a fortnight. ;)

Two solutions for problems mentioned above:
a) Forcing qt5 is no problem, one can set QT_SELECT to qt5. This requires the package qtbase5-dev-tools.
b) The initial comment reported a missing uuid.hpp. That is part of the Debian package libboost1.58-dev, which should be installed as a dependency.

Problems found:
a) You provide the boost library in JASP-Common, but it's not found there. Somehow you are missing an include path:
JASP-Common/analysisloader.cpp:21:36: fatal error: boost/nowide/fstream.hpp: No such file or directory

b) JASP-Common/importers/csvimporter.h:21:28: fatal error: datasetpackage.h: No such file or directory
But the file is there: $ find . -name datasetpackage.h
./JASP-Common/datasetpackage.h 
Again, I think you are missing some include statement.

c) Loooots of warnings. Maybe someone should review some of the coding standards?

May I also suggest to add three things to the jasp download website: 
a) a link to a zip/tarball of the sources, including a checksum
b) a list of depending libraries
c) instructions how to compile (as mentioned above in this thread)

Many thanks!

**Comment by Argafal** [comment]
Some solutions, new problems.

a) export CPLUS_INCLUDE_PATH=JASP-Common/:JASP-Desktop fixes the include of nowide/boost and other header files.

b) Installing qtbase5-dev adds some of the necessary dependencies, such as QString.

c) Then I stumbled over a missing QNetworkAccessManager and similar problems. Which is also part of qtbase5-dev, so again some include must be wrong. JASP-Desktop/activitylog.h:24:33: fatal error: QNetworkAccessManager: No such file or directory. I changed files the following way:

JASP-Desktop/activitylog.h:
#include <QtNetwork/QNetworkAccessManager> and 
JASP-Desktop/activitylog.cpp:
#include <QtNetwork/QNetworkRequest>
#include <QtNetwork/QNetworkReply>

JASP-Desktop/appdirs.cpp and JASP-Desktop/application.h:
#include <QtWidgets/QApplication>

JASP-Desktop/mainwindow.h:
#include <QtWidgets/QMainWindow>

JASP-Desktop/widgets/progresswidget.h:
#include <QtWidgets/QWidget>

JASP-Desktop/analysisforms/analysisform.h: 
#include <QtWidgets/QWidget>                               
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QPushButton> 

JASP-Desktop/widgets/availablefieldslistview.h:
#include <QtWidgets/QListView>

JASP-Desktop/widgets/listview.h:
#include <QtWidgets/QListView> 
#include <QtWidgets/QAbstractItemView>

JASP-Desktop/widgets/droptarget.h:
#include <QtWidgets/QAbstractItemView>

JASP-Desktop/widgets/tablemodelvariables.h:
#include <QtWidgets/QAbstractItemView>

JASP-Desktop/widgets/button.h:
#include <QtWidgets/QPushButton> 

JASP-Desktop/widgets/boundlistview.h:
#include <QtWidgets/QListView> 

JASP-Desktop/osfnam.h:
#include <QtNetwork/QNetworkAccessManager> 

JASP-Desktop/onlinedataconnection.h:
#include <QtNetwork/QNetworkAccessManager> 

JASP-Desktop/onlinedatanode.h:
#include <QtNetwork/QNetworkAccessManager> 

JASP-Desktop/onlinenode.h:
#include <QtNetwork/QNetworkAccessManager> 

JASP-Desktop/onlineusernode.h:
#include <QtNetwork/QNetworkAccessManager>

JASP-Desktop/optionsform.h:
#include <QtWidgets/QWidget>

JASP-Desktop/assignments.h:
#include <QtWidgets/QWidget>

d) That brings me another include problem, in file JASP-Desktop/assignments.h, where the path was wrong, this is the correct version for git-trunk:
#include "../JASP-Common/options/option.h"

Then it fails with "JASP-Desktop/assignments.h:14:49: fatal error: ../JASP-Common/optionassignedfields.h: No such file or directory", and this include I cannot locate anywhere. Please advice.

**Comment by boutinb** [comment]
Discussion went on with issue #1146
