### ISSUE TITLE
Additional prior to t-test

### ISSUE THREAD

**Issue by goshengott** [jasp-stats/jasp-desktop#765]
At present, the Baysian t-test can only be carried out assuming the prior distribution as Cauchy.  Is it possible to implement other distributions?
EJ writes in a 2012 paper, regarding a replication of Bem:
Alternative hypothesis 2, H2 assumes that effect size is distributed as a half-normal
distribution with positive mass only and the 90th percentile at an effect size of 0.5

Is this an entire family of prior distributions which should be implemented?

**Comment by jonathon-love** [comment]
@EJWagenmakers ??

**Comment by goshengott** [comment]
Of course.  The one and only ej

**Comment by EJWagenmakers** [comment]
Yes in due time we intend to add other, more flexible prior distributions,
maybe as separate modules.
EJ

**Comment by goshengott** [comment]
Great.  Thanks.
Yonatan
