### ISSUE TITLE
Data descriptives in (Bayesian) LMs

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#770]
Add some form of descriptives of the data in B-LMs.
I think that this should be optional for the analysis, and not given by default.
It might pay out to write a generic function for descriptives that we could add to a specific analysis.

**Comment by jonathon-love** [comment]
@raviselker, could you add these options and checkboxes when you get a chance?

**Comment by raviselker** [comment]
What would be the exact options and checkboxes?

**Comment by boutinb** [comment]
Issue closed due to too long inactivity
