### ISSUE TITLE
Zero-inclusion probabilities when multiple BF10s are infinite.

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#771]
This concerns an issue reported by @cowann.

Below there are multiple BFs that show infinite support; however, all other values that are computed after this have problems (like P(M | data), BF_M, and the corresponding Analysis of Effects Table).

![screen shot 2015-07-07 at 10 18 34](https://cloud.githubusercontent.com/assets/8667548/8541859/8a40ae44-2491-11e5-8dd9-1732dafcbf69.png)

I am not entirely sure what the correct behavior here should be, since based on the BFs it is impossible to choose between models 2 (SP), 4 (SP + group) and 5 (SP + group + SP*group).
As compared to the null model, we could choose to set P(M | data) to 1/3 for these three models.
But there is no principled way to do this, since we simply do not know.
All that we now is that SP matters.
So we could just as well choose (1,0,0) for models 2, 4, 5.

What do you think @EJWagenmakers @richarddmorey?

When I include SP in null-model (to figure out what is going on) the results are:
![screen shot 2015-07-07 at 10 30 22](https://cloud.githubusercontent.com/assets/8667548/8542074/2a015bee-2493-11e5-8f40-2892ce6aca4f.png)
Showing that there is at least some variability left (i.e., unexplained by SP alone) and group matters as well.

I have to dive into the data for this particular analysis to see if there is something else going on.
The classical test flags the sphericity condition to be violated.

**Comment by EJWagenmakers** [comment]
I can think of the following solutions:
1. If one of the BF10's is \infty, simply do not report the other information (such as posterior probabilities).  Perhaps underneath the table you can print a statement indicating that this is what happened. This may be the easiest short-term solution.
2. If one of the BF10's is \infty, automatically add those factors as nuisance and present the table based on that.
3. A combination of the foregoing. Present two tables; first, the one from (1), showing only the BF10 column; second, the one from (2) with the infinitely supported factors as nuisance.
4. Ultimately, in this situation we might want to switch to a method that computes BFs not via transitivity to H0, but via transitivity to some other model. In fact, I think we can already do this. So suppose one of more BF10 are \infty. Then we take the least complex model that is \infty and use it as nuisance. Hopefully this will allow all posterior probabilities to be computed (we already know that the one for H0 equals 0). If there are still \infty's, we take the second-least complex model, etc. So basically, I think we can solve this in a relatively straightforward fashion!

**Comment by jonathon-love** [comment]
why not set P(incl|data) to 1 and BF(inclusion) to infinity?
this is what used to happen i'm pretty sure.

**Comment by mmarsman1** [comment]
Since you dont know which effects need to be included; just the main or also the interaction?

I am not keen on restarting the analysis, especially since it is based on a rule that becomes arbtrary at some point where two main effs are infinite.
I suggest to flag the problem and give maybe give a suggestion how to proceed.

An even better solution would be to let the user specify only two models (no model fishing).

Verzonden van mijn HTC

----- Reply message -----
Van: "Jonathon Love" <notifications@github.com>
Aan: "jasp-stats/jasp-desktop" <jasp-desktop@noreply.github.com>
CC: "Marsman, Maarten" <M.Marsman@uva.nl>
Onderwerp: [jasp-desktop] Zero-inclusion probabilities when multiple BF10s are infinite. (#771)
Datum: di, jul. 7, 2015 18:25


why not set P(incl|data) to 1 and BF(inclusion) to infinity?
this is what used to happen i'm pretty sure.

**Comment by jonathon-love** [comment]
> Since you dont know which effects need to be included; just the main or also the interaction?

ah, yup, makes sense. (although you could look at the model comparison table to tell you?)

**Comment by mmarsman1** [comment]
Since both the model with the main (SP) and the interaction (SP + group + group * SP) have infinite support as opposed to the null, we don't know if it is SP alone or also group * SP.

I am surprised that we did not see this behaviour before (or something has changed that makes all related stuff break)...

@EJWagenmakers; now without a phone, so I can now elaborate a bit :)
1. I think this is the best solution.
2. I see two problems: 
 i) the rule to decide what to do is hidden from the user, and Jonathon always tells me that this makes for bad user experience; especially when multiple decisions are being made.
 ii) I don't see directly how to do this, since the initial analyses needs to abort with a flag, then a new analysis needs to start where a variable is selected as nuisance based on the old analysis that was aborted. Can we use the state system for this @jonathon-love?
3. This needs to dynamically set the meta and number of tables based on past X-iterations of the rule (which will become a mess; but I can redesign the analysis to build it around the state system).  
4. I thought of this option too, but then realized that this is not a precision problem, and the BF-package most likely returns "Inf". So this doesn't help unfortunately (Inf / Inf = NaN, and we don't know which model is more "Inf" than others to decide)

As an alternative; note that there are no problems such as this occurring if we only compare two models.
This might be a more correct approach overall; the Bayes factor is designed to compare two models, and people are not automatically model phising ("oh wait, this model is also interesting"; I hear them say that all the time when we run an analysis at my desk).
How do we feel about this?

**Comment by EJWagenmakers** [comment]
I don't think the result becomes arbitrary with multiple infinities. This
is a numerical problem, not a conceptual one. The present output is just
wrong so that ought to be fixed.
EJ

**Comment by mmarsman1** [comment]
It is arbritrary. 
Each of these choices for models 2, 4, 5 can be used: (1,0,0) or (1/3,1/3,1/3) or even (1/2,0,1/2).
Therefore, I think we should simply not give them (we don't know which one it is).

So my basic suggestion would be to give a note  / warning, and don't compute things that are not possible to compute. 

That's the short term fix that I planned to add tomorrow (not that it matters, as 0.8 is miles away, but still).

The long-term fix is another thing; I suggest reworking B-LMs into a binary model choice.
Would be nice to work this through for 0.8, since it solves not only this, but many other problems.

M

**Comment by EJWagenmakers** [comment]
It cannot be arbitrary. The only reason we see \infty is because the
computer is unable to deal with these large numbers. Suppose I have three
models. BF10 for the first is 100, BF10 for the second is 200. Suppose I
have a computer that can only present numbers up to 50. Then the two BF10's
will be shown as \infty (yes it is a very very old computer). But if we
include one of the effects as nuisance, we learn that one of the models
receives *twice* as much support as the other. This is not arbitrary.
EJ

**Comment by mmarsman1** [comment]
Yes, but based on Table I cannot decide, only based on Table 2 (which I did not see).

What concerns me is that Jasp produces Inf (and not 1e+9999 or something similar) we are able to calculate with the marginal likelihoods (otherwise the second table would also fail).
Perhaps option 4 is feasible after all; I’ll have a look at this.

On 08 Jul 2015, at 07:15, EJWagenmakers <notifications@github.com<mailto:notifications@github.com>> wrote:

It cannot be arbitrary. The only reason we see \infty is because the
computer is unable to deal with these large numbers. Suppose I have three
models. BF10 for the first is 100, BF10 for the second is 200. Suppose I
have a computer that can only present numbers up to 50. Then the two BF10's
will be shown as \infty (yes it is a very very old computer). But if we
include one of the effects as nuisance, we learn that one of the models
receives *twice* as much support as the other. This is not arbitrary.
EJ

**Comment by jonathon-love** [comment]
we can mitigate this problem, to a large extent (almost entirely?), by using logs (this is what rich does)

at the moment we are bounded at 10^308, but using logs will take us up to 10^10^308, which is colossally larger.

i will need to add a log format to the columns; i.e. "sf:4;dp:3;log10", which i've been meaning to do for a while, but other than that the changes shouldn't be *too* significant?

**Comment by mmarsman1** [comment]
Yes, I though of that as well, and I can rework the Model-block and Table functions, as it only needs to have the marginal likelihoods and not the Bayes factors, so that should be more stable for (re)computing. 

The problem now is that if BF is infinite I store Inf (in the model-block) and taking the log of that returns Inf, whereas if I take the log from the beginning, it is most likely giving a finite number.

However, If I use the marginal likelihoods (in the model-block), I can actually compute the log-BF from scratch (Table function) using log-P(data|M) - log-P(data|0), which is a better way.

The general problem can still occur and we need to think about a principled solution to handle the problem in general.
There is no hurry, so I can think about it. 

Whats the eta on 0.8?

Cheers, M.

**Comment by jonathon-love** [comment]
yeah, i think the simplest solution for now is to set P(incl|data) to 1, BF to Inf etc.

this is simple to implement (it used to work this way) and consistent with the way *Analysis of Effects* normally works

people can always refer back to the *Model Comparison* table to disentangle the main effects and the interaction, or set one as nuisance manually.

if we move to logs, i think the infinity overflow won't happen very often, and i think this is a good trade off between effort and reward.

(i personally don't think there's a better way to handle it, even with infinite resources, etc. i would still do it this way. consistency is key.)

**Comment by jonathon-love** [comment]
hey @mmarsman1,

i've added support for log10 formatted results. you can specify a format like "sf:4;dp:3;log10" and the table renderer will `exp(10, x)` it.

**Comment by richarddmorey** [comment]
I have never seen an infinite Bayes factor with BayesFactor, due to my use of logs. I also use log probabilities, so perhaps you can solve this by using BayesFactor's built-in support for probabilities?
http://cran.r-project.org/web/packages/BayesFactor/vignettes/odds_probs.html
Use the development version; there is a bug in the CRAN version that gives an error sometimes.

**Comment by mmarsman1** [comment]
@cowann

One problem with this analysis is that it does not fit your needs.
The ANOVA model assumes continuous (and approximately Normally distributed) dependent variables. 
In your analysis this is clearly not the case as the the dependent variable is discrete with 13 unique values:

<img width="625" alt="screen shot 2015-07-15 at 23 52 58" src="https://cloud.githubusercontent.com/assets/8667548/8710809/e5af19f2-2b4c-11e5-87f9-65e034d3881d.png">

So fixing the current problem in JASP still leaves you with a misspecified model.
I would be more than happy to help model this properly if you want, since this has been on my to-do list for some time now.

@richarddmorey 
The Bayes - Factor output indeed does not produce any "Inf"s here.
The problem occurs when I extract values from a BF object:

#In R:
> BF <- generalTestBF(formula(dependent ~ subject + SP + Group), whichRandom = "subject", data = data)
> BF
[1] subject              : 9.090974e-11  ±0%
[2] SP                   : 5.812498e+417 ±0%
[3] subject + SP         : 2.860396e+466 ±0.44%
[4] Group                : 3746.285      ±0%
[5] subject + Group      : 3.104484e-08  ±1.18%
[6] SP + Group           : 2.027887e+444 ±0.7%
[7] subject + SP + Group : 2.977379e+475 ±1.13%
> Against denominator:
>  Intercept only 
>
> #compare to model including subject:
> BFj <- BF[c(3,5,7)] / BF[1]
> BFj
[1] subject + SP         : 3.146413e+476 ±0.44%
[2] subject + Group      : 341.4908      ±1.18%
[3] subject + SP + Group : 3.275094e+485 ±1.13%
> Against denominator:
>  dependent ~ subject 
>
> #How I compute model [1] in JASP:
> mar1 = lmBF(formula(dependent ~ subject + SP), whichRandom = "subject", data=data)
> mar0 = lmBF(formula(dependent ~ subject), whichRandom = "subject", data = data)
> mar1 / mar0
[1] subject + SP : 3.151475e+476 ±0.46%
> Against denominator:
>  dependent ~ subject 

Looking decent!

Now, I compute this model in JASP itself:
#NULL model (dependent ~ subject):
bf <- try (BayesFactor::lmBF (null.formula,
	data = dataset, whichRandom = .v (unlist (options$randomFactors)),
	progress = FALSE, posterior = FALSE, callback = .callbackBFpackage))
null.model$bf <- bf

#Model 1 (dependent ~ subject + SP):
bf <- try (BayesFactor::lmBF (model.list [[m]],
	data = dataset, whichRandom = .v (unlist (options$randomFactors)),
	progress = FALSE, posterior = FALSE, callback = .callbackBFpackage))

model.object [[m]]$bf <- model.object [[m]]$bf / null.model$bf
print (model.object [[m]]$bf)

> [1] SP + subject : 3.16697e+476 <U+00B1>0.68%
> Against denominator:
>  dependent ~ subject

No problem here.

The problem occurs when I extract the BF value from the BF object (which I need to pass it to a Table output):

> bf <- mar1/mar0
> #this gives the log-value
> bf@bayesFactor$bf
[1] 1097.178
> #transforming back:
> exp(bf@bayesFactor$bf)
[1] Inf

And I have a problem here.

@jonathon-love 
Is this something that we can handle using that "exp(10, x)" thing you suggested?

**Comment by jonathon-love** [comment]
> Is this something that we can handle using that "exp(10, x)" functionality you suggested?

yup!

**Comment by mmarsman1** [comment]
So, I reworked all the code such that its using logarithms now (except for some things in the effects table, but I will do that later). 
It has the same precision as what Richard has in his BFs and probabilities.

The "exp(10,x)" functionality is not working appropriately for smaller numbers.
Richard has a nice function ("expString") that works decently in my code, so we could base our table formatting on this if we cannot get "exp(10,x)" to work.
M.

**Comment by mmarsman1** [comment]
So, ("exp(10,x)") works up to the value "0", which should give "1", but still gives "0".
The effects table stuff is too complicated for this moment, so I will pass on that for now.
(I spent the entire day on it, but cannot squeeze more precision at this moment for the BFinclusion and related quantities. So BFinclusion here gives "Inf", and that's what it is.)
The model comparison table works properly.

M.

**Comment by jonathon-love** [comment]
done!
