### ISSUE TITLE
Version is now unknown!

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#776]
<img width="374" alt="screen shot 2015-07-09 at 8 06 54 pm" src="https://cloud.githubusercontent.com/assets/3240247/8609650/0fa7fb7e-2676-11e5-9003-cdf6cf789997.png">

**Comment by dropmann** [comment]
I left out the index.html when committing. Sorry. And also forgot to add closes #776. Sorry.
