### ISSUE TITLE
Cite menu doesn't work

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#778]
Hey @dropmann,

the notification for "Citation copied to clipboard" no longer seems to work, but i'm wondering if we even need these notifications.

i originally put them in, because the tool buttons were a bit [completely] ambiguous, and there wasn't good feedback when you clicked them, but now the menu is text it's completely unambiguous ... oh wait, i guess "Cite" is still pretty ambiguous.

anyhow, there wasn't good feedback that you'd clicked them, where as now the menu flashes blue or whatever.

so what if we change "Cite" to "Copy Citations", and do away with the "Copied to clipboard" notifications? alternatively, if you like the notifications, we should add the "Citation copied to clipboard" back in.

thoughts?

**Comment by jonathon-love** [comment]
Wait. I don't think that the "Cite" menu works at all :/

**Comment by dropmann** [comment]
i'll look into it. It worked this arvo. Committing can be complicated as i have a whole bunch of other changes that i don't want to commit and it always needs sifting.

**Comment by jonathon-love** [comment]
> Committing can be complicated as i have a whole bunch of other changes that i don't want to commit and it always needs sifting.

yup. consider maintaining separate branches.

**Comment by dropmann** [comment]
yep. k

**Comment by dropmann** [comment]
I just did a pull request for this issue but also forgot... AGAIN... to say closes #779. Is there anyway i can rectify this without you having to do it if i happen to forget in the future. I'll obviously attempt not to.

**Comment by jonathon-love** [comment]
i don't think there's a way to rectify it :)

**Comment by jonathon-love** [comment]
all works nicely :)
