### ISSUE TITLE
Error message when copying whole analysis into word

### ISSUE THREAD

**Issue by raviselker** [jasp-stats/jasp-desktop#781]
I tried copying a whole analysis and pasting it into word but when I tried I got the following error message:

<img width="565" alt="screen shot 2015-07-10 at 14 20 40" src="https://cloud.githubusercontent.com/assets/4669197/8629290/ca23805c-270e-11e5-973f-63dd541c6e35.png">

**Comment by jonathon-love** [comment]
yeah, i guess you don't have a enough memory or disk space :)

**Comment by raviselker** [comment]
Yes, that's what you would think but unless the copied analysis is bigger than 6 GB this shouldn't be a problem.

**Comment by jonathon-love** [comment]
So it's a bug in Word.

**Comment by raviselker** [comment]
Don't know. I can copy the images and tables separately though.

**Comment by jonathon-love** [comment]
yup. yeah, i don't know why it does it. it works fine under windows.
