### ISSUE TITLE
Help remains after analysis discarded

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#783]
Not vital for beta release. Discarding an analysis should also remove the associated help information?!
![image](https://cloud.githubusercontent.com/assets/8603015/8630764/bfe6d340-271e-11e5-9827-e6075980cf88.png)

**Comment by jonathon-love** [comment]
that behaviour seems ok to me. you would prefer it to remove the help content?

**Comment by EJWagenmakers** [comment]
Judgement call, but I think it is more consistent to remove *all aspects*
of the discarded analysis, including the help.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
