### ISSUE TITLE
Citations need work

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#787]
Not vital for beta release.
Some of the citations that are copied need work. For instance, here is one:
Rouder, J. N., Morey, R. D., Speckman, P. L., Province, J. M., (2012) Default Bayes Factors for ANOVA Designs. Journal of Mathematical Psychology. 56. p. 356-374.
In brackets, here are the mistakes:
Rouder, J. N., Morey, R. D., Speckman, P. L., [add &] Province, J. M.[,] (2012) Default Bayes [F]actors for ANOVA [D]esigns. Journal of Mathematical Psychology[. -- comma needed] 56[. -- comma needed] [p. -- not needed, comma suffices] 356-374.
I suspect that this is not an isolated incident. Is there an easy way to go over all citations and make sure they are correct?

**Comment by jonathon-love** [comment]
just to look at the source code of the analyses, pretty straight forward.

**Comment by EJWagenmakers** [comment]
OK, well, let's do this when we are back in Amsterdam. It is a little
sloppy when these aren't right, and they'll be in the program for the
duration.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
so this should be:

Rouder, J. N., Morey, R. D., Speckman, P. L., & Province, J. M., Default Bayes Factors for ANOVA Designs. Journal of Mathematical Psychology, 56, 356-374.

??

This is a 2 second fix, so if there's any other citations that need fixing let me know.

I just copy/pasted these from the Bayes factor package, so i'll let rich know too.

**Comment by jonathon-love** [comment]
... with the year?:

Rouder, J. N., Morey, R. D., Speckman, P. L., & Province, J. M., (2012). Default Bayes Factors for ANOVA Designs. Journal of Mathematical Psychology, 56, 356-374.

**Comment by EJWagenmakers** [comment]
This is the right one (no comma after Province, no caps in the title except
for what is needed):

Rouder, J. N., Morey, R. D., Speckman, P. L., & Province, J. M. (2012).
Default Bayes factors for ANOVA designs. Journal of Mathematical
Psychology, 56, 356-374.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
