### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#790]
When JASP is open, it is not clear to me where I can see what the version number is. This could be relevant information -- some functionality will only be available in later releases; when the user posts a JASP file it would be nice to know what version was used to generate the file, etc. Not having this information available might cause confusion at some later stage. How can we best add version number information to (1) the JASP GUI (an "About" tab?); (2) the .jasp file? I don't know but it would be nice.

**Comment by jonathon-love** [comment]
the start menu entry has the version number, the intro screen has the version number, and the .jasp file includes what version it was created in; but i agree we need an "about box".

**Comment by EJWagenmakers** [comment]
I can't see the version number of the ,jasp file after I open it. Where should I look?

**Comment by jonathon-love** [comment]
you need to rename the .jasp file to a zip file, unzip it, and look in the META-INF/manifest.mf file (or something like it), but it's in there.

**Comment by EJWagenmakers** [comment]
OK, but perhaps we can think about an easier way to provide this
information to the user.


********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
is there a use case, where the user would be interested?

we always put the version of the software that creates a file in the file (because it's interesting for debugging), but i've never heard of software exposing this to the user. it's just not important.

**Comment by EJWagenmakers** [comment]
Suppose researcher A conducts an analysis in 0.71. He uploads the jasp file
to the OSF. Some time in the future, researcher B opens this file with
version 0.97. Researcher B then wonders why researcher A did not select
Fancy New Analysis X That Was Added Only In Version 0.85. The answer
(unavailable to Researcher B at the moment) is that the jasp file was
created with version 0.71.

Plus, hopefully we don't cut analyses because who knows what will happen
then. Linking analyses files to versions is important for the kind of
emerging statistical software package.

Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by boutinb** [comment]
Issue closed due to too long inactivity
