### ISSUE TITLE
Bayesian 2x2 factorial ANOVA in JASP

### ISSUE THREAD

**Issue by KayaJoanne** [jasp-stats/jasp-desktop#791]
Hi JASP developers, 

I’m very enthusiastic about JAPS, it seems like the perfect tool to make Bayesian analyses accessible to non-statisticians. However, I’m struggling with the interpretation of the Bayesian variant of the 2x2 factorial ANOVA. I am comparing these analyses with a conventional 2x2 ANOVA run in SPSS to determine how I should interpret the non-significant findings for the main and interaction effects. Briefly my question is, when using JASP, how can I determine whether main and interaction effects where present for the Bayesian variant of a 2x2 factorial ANOVA?
When trying to answer this question myself, I found the Output – Effect option in JASP (0.7.0 Beta 4). Should I look at e.g., the BFinclusion to determine whether there is evidence for (the absence of) main and interaction effects? Or should I use the method described in Wetzels, Grasman & Wagenmakers (2011, in The American Statistician), i.e., dividing the BF10 of the model with both main effects by the BF10 of the model with the main effect of factor 2 to determine the main effect of factor 1 and dividing the BF10 of the full model with both main effects and interaction effect by the BF10 of the model with both main effects to determine for the interaction effect? The procedures provide different results and thereby lead me to a different conclusion regarding the evidence for (the absence of) an interaction effect (differing between inconclusive and substantial evidence for the null hypothesis). 
I would be very happy to learn how I can interpret the data that JASP provides!

Thank you for developing the software up to this point and I’m looking forward to its further development!

Kaya

**Comment by jonathon-love** [comment]
hey @EJWagenmakers,

do you want to take a look at this one?

**Comment by jonathon-love** [comment]
Hi kaya,

i would do what you describe:

> divid[e] the BF10 of the full model with both main effects and interaction effect by the BF10 of the model with both main effects to determine for the interaction effect

but EJ may have more to add

**Comment by EJWagenmakers** [comment]
Yes that is correct. A more detailed description is here (in press for
Psychological Methods):
http://www.ejwagenmakers.com/inpress/RouderEtAlinpressANOVAPM.pdf

Sorry about the tardy response, I'm at a conference.
Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment]
Also, you should get the same BF if you take the two main effects as
"nuisance", so that H0 includes these main effects and the only comparison
left is to a H1 that includes both main effects *and* the interaction.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by KayaJoanne** [comment]
Thank you very much for your help Jonathon and E.J., I should be able to interpret it correctly now!
