### ISSUE TITLE
"Too" new, not "to" new 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#793]
![image](https://cloud.githubusercontent.com/assets/8603015/8635629/3efa831c-27e1-11e5-8cb8-419134a76dde.png)

**Comment by dropmann** [comment]
i don't understand why he was getting this error message (independent of the typo). What version file was he using. Was it an old one?

**Comment by EJWagenmakers** [comment]
I saved a file using the latest beta version, and then tried to open it
with an earlier version.
EJ

**Comment by dropmann** [comment]
This might be normal behaviour. Did you try and open it in a 0.6.x?

**Comment by EJWagenmakers** [comment]
Sure, this seems reasonable. I was only pointing out the typo in the
message...
EJ

**Comment by dropmann** [comment]
Just checking, because if that msg appeared when trying to open the file in a previous 0.7 version it would be a problem.

**Comment by jonathon-love** [comment]
the exporter placed an "Alpha 1" on the file version string, so i removed it (introduces the wrinkle that 0.6 won't open newer files, but that's fine at this stage of development). the compatibility checks are all working fine. it's just the spelling.

**Comment by dropmann** [comment]
The title of this issue is very Shakespeare of you.

**Comment by jonathon-love** [comment]
:P

**Comment by EJWagenmakers** [comment]
OK, I checked and I get the error when I save a file using the latest beta,
and open it with version 0.7.0 Beta 3.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by dropmann** [comment]
"the exporter placed an "Alpha 1" on the file version string, so i removed it (introduces the wrinkle that 0.6 won't open newer files, but that's fine at this stage of development). the compatibility checks are all working fine." - Jonathon

This will also happen for 0.7.0 beta's but that's fine at this stage of development also.
