### ISSUE TITLE
Adding levels to repeated measures ANOVA

### ISSUE THREAD

**Issue by HelenSteingroever** [jasp-stats/jasp-desktop#795]
I tried to add levels to the repeated measures ANOVA. I think this was only possible by typing the new level (see screenshot). In a previous version of JSAP, the new level appeared automatically when I clicked into the field. I think this was handier.

![screen shot 2015-07-11 at 18 34 16](https://cloud.githubusercontent.com/assets/7047722/8640170/f5340708-28a3-11e5-8510-6566d414e8eb.png)

**Comment by jonathon-love** [comment]
> I think this was handier.

yeah, we did get a few complaints about the old behaviour, and i did see a number of people accidentally doing the wrong thing with it (i.e. they would click somewhere else in the box to indicate they had finished editing the level name, but the click would fall on a new level and a new level would be inserted, and then the user would be puzzled and annoyed), and i've received positive feedback about the change.

i agree the old behaviour was quicker, but it did cause some confusion.
