### ISSUE TITLE
Repeated measures ANOVA

### ISSUE THREAD

**Issue by HelenSteingroever** [jasp-stats/jasp-desktop#796]
I did a frequentist repeated measures ANOVA and added some levels. When I afterwards did the Bayesian repeated measures ANOVA with the same data set, I had to add all levels again. I think it would be handier if, after carrying out a frequentist analysis, the same settings (i.e., levels) automatically appear for the Bayesian analysis (and vice versa).

**Comment by jonathon-love** [comment]
yup good idea!, it just happens to be a massive amount of work to add this feature :)

duplicate #395

**Comment by jonathon-love** [comment]
hmm, actually there might be a way to do this, that's not too much work.
