### ISSUE TITLE
BB Image renderer sometimes places resize indicator, when no resize available

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#805]
it seems to disappear when i move the mouse around.

<img width="1292" alt="screen shot 2015-07-15 at 2 38 21 pm" src="https://cloud.githubusercontent.com/assets/3240247/8706706/3edb843c-2aff-11e5-84f8-af2abb278d9b.png">

**Comment by dropmann** [comment]
i'll look into it.

**Comment by dropmann** [comment]
I think i understand the problem but not sure how to fix it yet. To do with some weird behaviour of the mouseleave event. I'll plotting along with it.

**Comment by jonathon-love** [comment]
i assumed the resize graphic came from the image being rendered inside some sort of "resizer" widget. don't you just need to bypass the resizer widget, when the image doesn't support being resized?
