### ISSUE TITLE
Some suggestions for independent samples T-tests (Bayesian and Classical)

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#809]
I recently did a large number of independent sample T-tests, and I missed the following conveniences:

1. The independent samples T-test does not use the state system. So when I want to keep a certain value in a .jasp file (for future reference), I need to recompute things such as the log(BF_10) or BF_01 elsewhere.
2. For some analyses, I wanted the table and effect-size plot to be in a certain direction. Say that I have two groups A and B, the current analysis automatically chooses A as the first group and B as the second. For the Contingency Tables I can change the order that is set, but here I cannot.
3. For some analyses, I have a group indicator with multiple levels, say 3. If I want to do a t-test between A and B, A and C and B and C, I need to make 3 "indicator" variables to achieve this. It would be nice to have the possibility to include a variable, possibly with multiple levels, but making it possible to select the first and second group from the variable's levels. This would also solve no. 2.

Cheers, 
M.

**Comment by boutinb** [comment]
Issue closed due to too long inactivity
