### ISSUE TITLE
Table export: Table cell alignment is lost

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#812]
hey @dropmann,

i think we have a regression in table cell alignment. i.e. the following is strange because the numbers are left aligned:

<img width="640" alt="screen shot 2015-07-17 at 8 32 23 am" src="https://cloud.githubusercontent.com/assets/3240247/8750803/6801f066-2c5e-11e5-9d2f-a08cb9f3eaa1.png">

**Comment by dropmann** [comment]
That would have happened because the text-align style was removed leaving it up to the word processor to decide using it's style formatting. This should not to be the case?

**Comment by dropmann** [comment]
It needs to be right aligned because of the *'s?

**Comment by jonathon-love** [comment]
> It needs to be right aligned because of the *'s?

yup, and several other reasons, like aligning the decimal point. the following for example:

-10234.344
1.122

becomes

    -10234.344
         1.122

which is easier to parse
