### ISSUE TITLE
Should we narrow the menu select area to just the text?

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#814]
for example, i've been caught out trying to select the Correlation Matrix analysis at the bottom (see screenshot), but all i can get is the menu. (immediately, without thinking about it, i try and click the white to the right of the heading. it takes me a couple of retries before my brain kicks in and says "you need to scroll down and click below the headings"). i think if we just make the headings clickable, it will be more intuitive.

what do you think?

<img width="1292" alt="screen shot 2015-07-17 at 11 04 39 am" src="https://cloud.githubusercontent.com/assets/3240247/8753830/b1723174-2c73-11e5-9f36-f9f64379364a.png">

**Comment by dropmann** [comment]
yep, i have had a similar issue. I'll play around with it and see what i can do.
