### ISSUE TITLE
Cohen's d not appearing

### ISSUE THREAD

**Issue by IndrajeetPatil** [jasp-stats/jasp-desktop#818]
Hi,

I am using JASP 0.7-beta4 and I am not getting Cohen's d for paired samples t-tests. Am I doing something wrong? 
![cohen s d](https://cloud.githubusercontent.com/assets/11330453/8761412/ee78f80e-2d50-11e5-8a6e-8c1058f831f7.jpg)

Thanks,
Indra

**Comment by jonathon-love** [comment]
seems to be to do with us not handling missing values correctly

**Comment by jonathon-love** [comment]
affects one sample t-test as well.

**Comment by jonathon-love** [comment]
thanks for reporting this @IndrajeetPatil !

**Comment by IndrajeetPatil** [comment]
Great! Thanks for resolving this.

Glad I could be of any help! :)
