### ISSUE TITLE
two ways repeated measure ANOVA

### ISSUE THREAD

**Issue by Greenmat** [jasp-stats/jasp-desktop#819]
Hi guys, could you please add the analysis of a 2x2 repeated measure ANOVA where BOTH variables are within (say "pre-post" and "left hand-right hand")? Thank you!!

**Comment by jonathon-love** [comment]
like this?

<img width="1339" alt="screen shot 2015-07-18 at 8 19 27 am" src="https://cloud.githubusercontent.com/assets/3240247/8762166/bcf202a6-2d25-11e5-9b43-24397e241e13.png">

**Comment by Greenmat** [comment]
Hi yes, exactly like that. I have just started using JASP so it wasn't clear to me how to do it. I thought just one factor could be put in. Your example  was more than enough to got me out of doubts. Thank you!

**Comment by Greenmat** [comment]
One last thing: is there any possibility to run post-hoc tests with this kind of analysis (again including also Turkey HSD or Scheffé)?

**Comment by jonathon-love** [comment]
> One last thing: is there any possibility to run post-hoc tests with this kind of analysis (again including also Turkey HSD or Scheffé)?

hi, not in the current version, but should be in the next major version. you can follow issue #758 to see our progress.

**Comment by Greenmat** [comment]
Excellent! Looking forward to it!
