### ISSUE TITLE
Add *Remove Analysis* to the analysis menu (in the results panel) ?

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#820]
it's funny, i've found myself looking for the "Remove Analysis" button in the analysis menu (even though i know and am familiar with where the "Remove Analysis" button actually is).

**Comment by jonathon-love** [comment]
another one you might like @dropmann

**Comment by dropmann** [comment]
completely agree! I wanted to do it already. As good as done.
