### ISSUE TITLE
Loading Indicator Descriptives Frequency Table (Nominal/Ordinal) does not disappear

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#830]
![loadingindicatordescriptivestable](https://cloud.githubusercontent.com/assets/8697436/8890257/7a6a6c0a-32f9-11e5-8427-fac6524020ac.png)

**Comment by jonathon-love** [comment]
good catch!

**Comment by jonathon-love** [comment]
hey, i'm having difficulty reproducing this; can you give more detailed instructions to reproduce?

**Comment by jonathon-love** [comment]
hey, i'm having difficulty reproducing this; can you give more detailed instructions to reproduce?

**Comment by quentingronau** [comment]
Hi, maybe this is something that just happens on my laptop (e.g., I also still don't get a loading indicator for the plots). For me, it happens, for example, if I load the 'ssgo-fred' data, click on 'Descriptives', select 'ssd' as variable and then click on 'Display Frequency Tables (nominal and ordinal)'.
