### ISSUE TITLE
non-continuous variables in matrix plot

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#832]
hey @quentingronau,

we refer to "numeric variables" as "continuous" throughout JASP

you could soften the message a bit too, perhaps something like:

"Correlation plots are not available for nominal or ordinal variables"

you could put this message over multiple lines.

but then, it may just be easier to plot these variables as is; it's clear to the user what's going on (perhaps more clear than the message "why can't you plot nominal or ordinal variables?!") and i can think of situations where it could be useful (think nominal vs a continuous for example).

whatever you think is best.

**Comment by quentingronau** [comment]
Ok, for the moment, I simply changed "numeric" to "continuous", but I will think about this more.
