### ISSUE TITLE
JASP 0.7.1 "JASP has experienced an unexpected internal error"

### ISSUE THREAD

**Issue by ceed12** [jasp-stats/jasp-desktop#842]
Installed JASP 0.7.1.
Open screen - if I do nothing it is OK
Select file - select Big 5 example data set
wait 20 seconds and this message appears:

 "JASP has experienced an unexpected internal error
if you could report your experiences to the JASP team that would be appreciated
JASP cannot continue and will close now"

System: Win 7 service pack 1, 64-bit - R, Rstudio and JAGS installed

Thanks

**Comment by jonathon-love** [comment]
hi ceed,

i've heard about people having this issue once or twice before. i'm pretty sure it's something to do with R, but we haven't been able to reproduce it.

does your machine have any sort of complex permissions scheme? i.e. it's part of a workgroup? or is it a single user setup?

thanks for your report

jonathon

**Comment by ceed12** [comment]
No, the machine is not part of a work group.

I just tried installing JASP 0.7.1 on a colleague's machine that is the same make/model running the same OS etc. - and it runs perfectly. The only thing I can think of is that on the machine that throws the error, R is installed under c:\ and not in the default location; whereas on the machine that JASP runs on R is installed in the standard C:\Documents and Settings location.

**Comment by jonathon-love** [comment]
yup. so JASP has it's own version of R bundled with it. the issue is that it's difficult to stop R from looking for packages elsewhere on the system.

what happens is that the JASP R finds a version of Rcpp from the system R, and this has been compiled with a different compiler, and so is incompatible.

we've had this issue in the past, but i thought i had it completely solved :(

**Comment by jonathon-love** [comment]
... and the system R has Rcpp installed, because of RStudio.

**Comment by ceed12** [comment]
Thanks Jonathan for the clear explanation - really appreciate the work put into all this!

**Comment by jonathon-love** [comment]
ok. i think i have a fix. i'll have something for you in the next couple of days.

**Comment by jonathon-love** [comment]
hi @ceed12 

could you try the latest JASP 0.7.1.1 ?

https://jasp-stats.org/download/

with thanks

**Comment by ceed12** [comment]
I tried JASP 0.7.1.2. No good I am afraid.

After installation the message "The program cannot find libarchive.dll " popped up and then it ran.

However, on loading the "Big 5 (Dolan et eal data) the message "JASP has experienced an unexpected internal error if you could report your experiences to the JASP team that would be appreciated JASP cannot continue and will close now" is displayed.

I did a complete uninstall using Revo and reinstalled - no strange missing .dll message but got the above message on loading any data .BTW, It does not crash like this if no data is loaded.

Thanks for thinking about this.

**Comment by jonathon-love** [comment]
hmm, one thing you could try is running the following:

    C:\Program Files\JASP-0.7.1.2\R\bin\x64\R.exe

(note that it has to be in x64, `C:\Program Files\JASP-0.7.1.2\R\bin\R.exe` won't work)

and seeing if a normal R session ensues. you could try seeing if the BayesFactor package can load:

    library("BayesFactor")

that might help diagnose this.

with thanks

**Comment by jonathon-love** [comment]
hmm, turns out there can be a .Renviron file in one's home directory under windows. can you see if one of these exists? should be in something like:

C:\Users\%UserName%\.Renviron

if it's the culprit, i'll have to find a way to prevent R from using it. :/

cheers

**Comment by jonathon-love** [comment]
it's possible the current release will fix the issue as well; 0.7.1.3

**Comment by ceed12** [comment]
Installed 0.7.1.5 (I see you have been busy ;). 

I got "The program can't start because libarchive.dll cannot be found" message - but the program loaded anyhow. Got a new message "The exception unknown software exception (0x40000015) occurred in the application at location 0x6fc5b87b".

Then when I retried JASP, I got the usual "JASP has experienced an unexpected error ... " message.

This may be useful: I tried running R.exe from a dos prompt in the directory "C:\Program Files\JASP-0.7.1.5\R\bin\x64" and I got the message "c:\Program' is not recognized as an internal or external command, operable program or batch file.". 

BTW, I do have a .Renviron in C:\Users\name\Documents - it consists of "TMP = '<c:\\Temp>'
write("TMP = '<c:\\Temp>'", file=file.path(Sys.getenv('R_USER'), '.Renviron'))"

Er, now a new R release (R 3.2.2) is up - maybe I should install it in the default directory and see if that helps with JASP?

Once again thanks for your efforts - Oh, & I have been travelling and will be again - so I haven't been able to access this site as often as I would wish...

**Comment by jonathon-love** [comment]
hmm, this is pretty puzzling.

could you look in `C:\Program Files\JASP 0.7.1.5` and see if libarchive.dll is in there?

> This may be useful: I tried running R.exe from a dos prompt in the directory "C:\Program Files\JASP-0.7.1.5\R\bin\x64" and I got the message "c:\Program' is not recognized as an internal or external command, operable program or batch file.".

what if you try opening the `x64` folder in windows (not in dos), and execute R.exe ?
then try loading the BayesFactor package or something similar.

thanks for your help, time and patience!

jonathon

**Comment by ceed12** [comment]
Yes, libarchive.dll  is in the JASP 0.7.1.5 dir - I think that what happened was on the initial run the virus checker (avast) was blocking it until it checked out - anyhow, that message no longer occurs.

I tried executing R.exe (Run as administrator) but it just flashes up a dos window -- that I think gives the same message "c:\Program' is not recognized as an internal or external command, operable program or batch file." - BTW, I can of course run R.exe from C:\R\R-3.2.0\bin\x64 (where I have R installed).

**Comment by jonathon-love** [comment]
> I think that what happened was on the initial run the virus checker (avast) was blocking it until it checked out - anyhow, that message no longer occurs.

ah, this is excellent to know. we can mention this in our installation guide, etc.

> I tried executing R.exe (Run as administrator) but it just flashes up a dos window -- that I think gives the same message "c:\Program' is not recognized as an internal or external command, operable program or batch file."

ah! this is significant! i'm pretty sure you won't be getting that same error message.

the error message in the first instance: "C:\Program is not recognized ... " is because of the space in `Program Files`

at the dos prompt, try executing it with quotes:

    "C:\Program Files\JASP-0.7.1.5\R\bin\x64\R.exe"

cheers!

**Comment by ceed12** [comment]
I tried the dos command with quotes but gave the same message as before. This message comes up even if I just run the R.exe part in dos from the C:\Program Files\JASP 0.7.1.5\R\bin\x64\ directory.

>i'm pretty sure you won't be getting that same error message.
I did a screen grab of the dos window and it is the same message
