### ISSUE TITLE
Bayes factor is switched

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#843]
As Richard "discovered" during his lecture, when you do a one-sided unpaired t-test, and you first select the order restriction, *then* change the output from BF10 to BF01, and then click "plots" and "more info", the BF is reported (in the figure) the wrong way around. See screenshots. We need to check whether this happens for some of the other analyses as well!

![image](https://cloud.githubusercontent.com/assets/8603015/9133627/877802f0-3cfd-11e5-94f5-1ae2e56683ec.png)

**Comment by EJWagenmakers** [comment]
Preliminary tinkering suggests that the error occurs *only* when BF01 is selected, and then, *very quickly*, the plot options are ticked.

**Comment by jonathon-love** [comment]
ah yup, this might be my fault then.

**Comment by quentingronau** [comment]
I think I found the error and fixed it. If it is still not working on your computers, please let me know.
