### ISSUE TITLE
Clicking options very quickly leaves output blank in Bayesian correlation pairs test

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#845]
In an attempt to check whether the correlation test has the same bug as the t-test, I used the presidents example and selected the options very quickly. That is, I first clicked "BF01" and then clicked the "plot" and "more info" boxes as quickly as I could. The result: no output is shown. See below:

![image](https://cloud.githubusercontent.com/assets/8603015/9135608/a96291c0-3d0f-11e5-93fa-645ad1299e53.png)

**Comment by jonathon-love** [comment]
hey @EJWagenmakers,

could you do a rebase and tell me if this issue persists?

https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/git-guide.md

**Comment by EJWagenmakers** [comment]
It is solved!
E.J.
