### ISSUE TITLE
Selecting main effects as nuisance causes crash for insect data

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#846]
Courtesy of Rene Zeelenberg:

![image001](https://cloud.githubusercontent.com/assets/8603015/9136201/f0a2d82e-3d14-11e5-98a9-cfbf39d0dbef.png)

**Comment by jonathon-love** [comment]
affects 32-bit windows only, i think it's a BayesFactor issue

**Comment by jonathon-love** [comment]
fixed.
