### ISSUE TITLE
QQ plot of residuals

### ISSUE THREAD

**Issue by cjalbers** [jasp-stats/jasp-desktop#848]
I'd like to be able to see a QQ-plot of the residuals of my t-test / ANOVA / linear regression. 
My guess is this is easy to implement; a checkbox and the code "qqline(model$residuals)" is nearly all you need.

**Comment by boutinb** [comment]
@raviselker : should we close this issue?

**Comment by raviselker** [comment]
I don't think we did this yet for the t-test, and the repeated measures ANOVA.

**Comment by philippberens** [comment]
a qq-plot in the descriptives tab would also be nice
