### ISSUE TITLE
Boxplot (in ANOVA)

### ISSUE THREAD

**Issue by cjalbers** [jasp-stats/jasp-desktop#849]
When performing ANOVA, I'd like to look at the boxplots to assess homogeneity of variances (and spot outliers). If this functionality could be added, that would be great.

**Comment by jonathon-love** [comment]
hey @cjalbers,

would this be better placed in descriptives?

**Comment by cjalbers** [comment]
Yes - it is essentially a descriptive method. (Although you could have a checkbox for it in the ANOVA-dialog as well)

**Comment by dave9986** [comment]
I second the request for comparative boxplots with outliers (1.5 IQR from "box") and extreme values (3 IQRs from "box").  Other features like making box width proportional to sample size and including a marker for the mean would also be nice (but not critical).

**Comment by cjalbers** [comment]
There are many additional options that are desirable - I really like violin plots as alternative to box plots as well - but having a basic ('default') box plot would already be a very good start.

**Comment by jonathon-love** [comment]
so we already provide basic plots for the ANOVA, but i gather you're after a bit more information about the distribution of data within the groups?

**Comment by cjalbers** [comment]
Indeed - it are the within group distributions I want to see.

**Comment by vankesteren** [comment]
This is possible in the descriptives of the latest version of JASP!
