### ISSUE TITLE
Residual plots

### ISSUE THREAD

**Issue by cjalbers** [jasp-stats/jasp-desktop#851]
For the regression dialog:
Option for regression plots: y vs residuals, and x vs residuals.
These are useful to detect non-linear patterns in the data as well as outliers

**Comment by quentingronau** [comment]
Hi @cjalbers,

Thank you for your feature request, we would like to add this functionality to JASP. We are thinking about adding different residual plots:

- observed y values vs. residuals
- each predictor vs. residuals
- predicted y values vs. residuals
- Q-Q plot residuals vs. normal distribution

I think you suggested to add the first two, but maybe you could, with regard to these options, tell us which of them you would like to see implemented first. Furthermore, would you prefer to display the residuals, standardized residuals or studentized residuals?

Quentin

**Comment by jonathon-love** [comment]
i think @raviselker has already implemented this...

**Comment by jonathon-love** [comment]
oh wait, not for regression i don't think.

**Comment by cjalbers** [comment]
HI Quentin,

I think the first three are already in the order I'd like to see them implemented in.
The QQ plot falls into a slightly different category.

Displaying the residuals in untransformed, standardised or studendised form is of minor importance IMHO: the figures will look exactly the same, apart from the scaling on the vertical axis. The untransformed display is closest related to the data, so that would be my choice for the first implementation.
You could even do it better than SPSS by displaying two vertical axes simultaneously (if you can use the standard plotting tools of R this takes minimal effort. That way, you can have a residual plot where you can read off both the "raw" residuals (e.g. on the left vertical axis) as the standardised residuals (on the other vertical axis). See the code below for a minimal working example.
```R
x <- rnorm(10,10,3)
y <- rnorm(10,2*x+1,1)
res <- lm(y ~ x)$residuals
par(mar = c(5, 4, 4, 4) + 0.3)  # Leave space for z axis
plot(x,res,xlab="x values",ylab="'raw' residuals",type="p")
par(new=TRUE)
plot(x,res/sd(res), axes = FALSE, bty = "n", xlab = "", ylab = "",pch=19)
abline(0,0)
axis(side = 4, at = pretty(range(res/sd(res))))
mtext("standardised residual",side=4,line=3)
```
