### ISSUE TITLE
Regression with interactions between continuous variables (moderator analysis)

### ISSUE THREAD

**Issue by cjalbers** [jasp-stats/jasp-desktop#852]
I noticed
that the Bayesian regression model already had this functionality, but the frequentist model doesn't have it yet. In SPSS, one also cannot do a moderator analysis easily (for the model y ~ x + z + (x*z) you either first have to compute a variable (k = x*z) then run the model y ~ x + z + k, or you have to resort to third-party scripts such as https://people.ok.ubc.ca/brioconn/simple/simple.html ). It would be a good selling point of JASP if JASP can do this easily (including checkboxes on whether you want to standardise/centre x and/or z first, and simple regression plots with e.g. the relation y ~ x for z = -1sd, 0, +1sd).

**Comment by jonathon-love** [comment]
hey @EJWagenmakers,

we're thinking this through at the moment. so casper's request is for a way to produce standardized regression coefficients (for the classical linear regression), etc.

at the same time, we receive requests for the Bayesian analyses for posterior estimates which are unstandardized (in the raw units, rather than in effect size).

it would be good if we could come up with a UI which is consistent between the two.

**Comment by EJWagenmakers** [comment]
I think we should prioritize the standardized approach. It is also
consistent with the way we deal with the t-tests (prior and posterior are
on delta). We can add the unstandardized results at a later stage with a
tickbox perhaps.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
yeah, it's more the UI i'm wondering about.

**Comment by boutinb** [comment]
@quentingronau: Did you implement this?

**Comment by quentingronau** [comment]
Yes, I think I implemented interactions between continuous variables a while ago. 
Here is an example screenshot (using the latest JASP version, i.e.,  0.8.0.0):

![example_regression_interaction](https://cloud.githubusercontent.com/assets/8697436/18099108/4bcc4822-6ee5-11e6-8482-56871c010f53.png)


Cheers,
Quentin
