### ISSUE TITLE
Keeping logs or syntax

### ISSUE THREAD

**Issue by cjalbers** [jasp-stats/jasp-desktop#856]
Our (psychology at Groningen university) students currently work mostly with SPSS. A new requirement for our students (aimed at better transperancy, open science, etc.) is that, whenever they hand in a report containing a quantitative analysis, they should also hand in the syntax they used to obtain the output from the raw data (for the vast majority of students, this is either the SPSS syntax, obtained through the "paste" button or some R script). 
It would be great if JASP has a similar functionality.
It would, for our purposes, already be sufficient if the "copy analysis" functionality that JASP already has is extended to include the options that were selected. ("E.g. Frequencies / Contingency Tables, with Rows = A, Cols = B, Counts = F. Options selected: X^2 continuity Correction")

**Comment by jonathon-love** [comment]
hey @cjalbers,

just get them to submit a JASP file! if you want to see exactly what options were used, you just click on the analysis, and up comes all the options that were used.

**Comment by cjalbers** [comment]
Ow, that's pretty cool actually! I hadn't noticed that a .jasp-file not only contains the output but also the "settings" of the analyses. My 'issue' can be processed as 'dealt with' :-)

**Comment by jonathon-love** [comment]
yeah, this was one of my goals from the outset with JASP, rid the world of syntax! it's an underlying technical detail that the user should not need to deal with.

we're also adding the ability to annotate JASP files at the moment, so you can add blocks of descriptive text to the results panel. this way you can describe why you ran a particular analysis, why you did X and not Y.

in this way we want to bring the data, the results, the options, and the commentary/motivation all into one place. hopefully, JASP files can just end up serving as informal appendices for papers.
