### ISSUE TITLE
several .dll issues

### ISSUE THREAD

**Issue by Indycool** [jasp-stats/jasp-desktop#858]
Hi,

I installed Jasp on my desktop PC (under W10) et it works perfectly fine but it won't run on my laptop (also W10).

Several error messages occur:
1: c:\Program Files\JASP 0.7.1.3\libarchive.dll is either not designed to run on Windows or it contains an error.
2: c:\Program Files\JASP 0.7.1.3\libstdc++-6.dll is either not designed to run on Windows or it contains an error.
3: c:\Program Files\JASP 0.7.1.3\Qt5Core.dll is either not designed to run on Windows or it contains an error.
4: libgcc_s_dw2-1.dll is missing

Would you have an idea about this strange difference between my two PCs please?

Sincerly

Indy

**Comment by jonathon-love** [comment]
my guess is that your laptop is 32-bit, and after doing some investigating, the 32-bit release of 0.7.1.3 for windows is broken. i've pushed out a fix:

https://static.jasp-stats.org/JASP-0.7.1.4-Setup.exe

sorry for the inconvenience!

**Comment by Indycool** [comment]
It is indeed a 32-bits. Thank you!
