### ISSUE TITLE
Problem with Qt platform plugin Windows

### ISSUE THREAD

**Issue by Indycool** [jasp-stats/jasp-desktop#859]
Hi,

It's me again, again with my W10-32bits laptop. I installed the 0.7.1.4 version, the .dll issues are gon but there is a new one. I linked images 1 and 2 to let you see the problem.
I enjoy JASP very much on my other PC, it's so smooth:)

Have a nice week-end.

Indy
![image 1](https://cloud.githubusercontent.com/assets/13798585/9279187/15ba9c18-42b6-11e5-86c6-3d946776d86d.jpg)
![image 2](https://cloud.githubusercontent.com/assets/13798585/9279188/15beee26-42b6-11e5-90a2-a78c9c2824ff.jpg)

**Comment by jonathon-love** [comment]
hahaha, oh shit, you are so right. expect a 0.7.1.5 soon!

**Comment by jonathon-love** [comment]
ok, try this one!

https://static.jasp-stats.org/JASP-0.7.1.5-Setup.exe

so sorry. feeling pretty embarrassed :P

jonathon

**Comment by Indycool** [comment]
Thank you so much, it works! My students will be able to use it on their laptops too, thx :)

**Comment by jonathon-love** [comment]
awesome!
