### ISSUE TITLE
B IS T-Test: large variability in results

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#861]
hey @EJWagenmakers, @quentingronau 

is this level of variability expected? i wouldn't have thought so. four identical analyses.

![screen shot 2015-08-17 at 3 44 01 pm](https://cloud.githubusercontent.com/assets/3240247/9306177/e13e0d9c-44f6-11e5-9b1e-6479bb0f986d.png)

**Comment by EJWagenmakers** [comment]
No. Can you Email me the JASP file please?
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by quentingronau** [comment]
Hi @EJWagenmakers ,

At the moment, I am trying to implement an algorithm that automatically increases the number of samples if the BF variability is too large. My first naive attempt is to do the following: I start with 1,000 samples and then calculate the BF five times. If the variability (expressed as percentage of the BF, i.e. sd(BF) / mean(BF)) is larger than .05 and the number of samples is below a certain threshold, say two Mio., I double the number of iterations and do the same thing again. So the algorithm ends if either the variability is below .05 or the maximum number of samples is reached. This yields eventually five BFs that might not be the same (the five BFs for the last number of iterations). Now my question is, what to output to the user. Would it be reasonable to report the mean/median of these BFs?

Cheers,
Quentin

**Comment by EJWagenmakers** [comment]
Hi Quentin,

> At the moment, I am trying to implement an algorithm that automatically
> increases the number of samples if the BF variability is too large. My
> first naive attempt is to do the following: I start with 1,000 samples and
> then calculate the BF five times. If the variability (expressed as
> percentage of the BF, i.e. sd(BF) / mean(BF))
>
Is this on the log scale? It ought to be, because a BF near 0 is not small,
but very large (in the sense of evidential impact). So take the logs first
(and then the absolute number).

is larger than .05 and the number of samples is below a certain threshold,
> say two Mio., I double the number of iterations and do the same thing
> again. So the algorithm ends if either the variability is below .05 or the
> maximum number of samples is reached.
>
OK!

This yields eventually five BFs that might not be the same (the five BFs
> for the last number of iterations). Now my question is, what to output to
> the user. Would it be reasonable to report the mean/median of these BFs?
>
Yes, the mean I think.
E.J.

**Comment by quentingronau** [comment]
Ok, thank you.

**Comment by jonathon-love** [comment]
implemented.
