### ISSUE TITLE
B correlation pairs: create "plot data" tick box

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#862]
Hi Jonathon,

Could you please create a tick box which I can use for the plot of the data?
I am not sure about the name, maybe "plot data" or "scatterplot" could work.

Cheers,
Quentin

**Comment by jonathon-love** [comment]
sure, will do.

i think it might be time... i showed you how to create your own checkboxes :P

**Comment by quentingronau** [comment]
This should be fixed with my commit #864.
