### ISSUE TITLE
B Corr Pairs: dot in results

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#867]
hey @quentingronau 

dot in results

![screen shot 2015-08-18 at 3 56 59 pm](https://cloud.githubusercontent.com/assets/3240247/9331826/dd029d08-45c1-11e5-8397-4a959bf7cba7.png)

**Comment by quentingronau** [comment]
hey @jonathon-love, it says "ssgo-fred", but it looks like my "ssgo-fred2" data set? With "ssgo-fred2", I could reproduce the error. For me, it works now (see my latest commit), but please let me know if you still get the same error.
