### ISSUE TITLE
Making JASP compilable on Arch Linux

### ISSUE THREAD

**Issue by stephensrmmartin** [jasp-stats/jasp-desktop#870]
I am trying to build jasp on Arch Linux.

The first problem is that the included R bundle uses libraries that are compiled assuming a different soname for libpcre.
My workaround is to create an Arch linux specific R bundle. This fixed all R-specific errors.

However, I am hitting some C++ compilation errors when building jasp-desktop.
E.g., term.h:12:18: error: ‘vector’ in namespace ‘std’ does not name a template type
  Term(const std::vector<std::string> components);

I am attaching my build log and the scripts I am using to build everything.

Logs and scripts:
https://gist.github.com/stephensrmmartin/0bbbe94a8a2550a1f747

**Comment by stephensrmmartin** [comment]
Followup: The problem is that term.h does not include <vector>

A simple #include <vector> fixed one issue.

The next issue:
```
terms.cpp: In member function ‘void Terms::set(QByteArray&)’:
terms.cpp:367:20: error: variable ‘QDataStream stream’ has initializer but incomplete type
  QDataStream stream(&array, QIODevice::ReadOnly);
                    ^
terms.cpp:367:29: error: ‘QIODevice’ has not been declared
  QDataStream stream(&array, QIODevice::ReadOnly);
                             ^
```

**Comment by jonathon-love** [comment]
cool, thanks for your report.

quick Qs, what version of GCC are you using, and what version of Qt?

jonathon

**Comment by jonathon-love** [comment]
yup, once again, i think these are just missing #includes (which aren't an issue on all our other systems; so i'm surprised they're cropping up). i'm happy for you to report them, and i'll add them in as necessary (but i recognise this is kinda un-fun for you), or you could add them in and do a pull-request.

i've fixed the two you mention.

**Comment by stephensrmmartin** [comment]
I use GCC 5.2 and Qt 5.5.

So the #includes were added to the devel branch?
What was the other missing #include?

**Comment by jonathon-love** [comment]
yup, in the development branch

other include is:

    #include <QIODevice>

**Comment by stephensrmmartin** [comment]
Perfect. The devel branch compiled and launches just fine. I get warnings about unexpected versions of the R packages, but otherwise everything seems to work fine.

In the final directory, there should be: 

- JASP
- JASPEngine
- Help
- Resources
- R

Correct?

Finally, do you have an SVG of the JASP icon? I can extract the icon.ico, but linux desktops prefer SVGs.

**Comment by jonathon-love** [comment]
awesome!

yup, that's the correct folder structure.

are you going to be submitting this to a repo or something? in which case i'd like to merge development into master, make it a 0.7.1.7, and tag it.

JASP svg is here: https://en.wikipedia.org/wiki/JASP#/media/File:JASP_logo.svg

**Comment by stephensrmmartin** [comment]
I am just writing a PKGBUILD for arch linux's AUR.
The pkgbuild is basically a bash script called by arch linux's makepkg to create a package for arch linux. The AUR is the arch user repository where any arch user can submit pkgbuilds.

I am going to compile the package once more to make sure everything works properly (and the icon and .desktop work properly), then will upload to the AUR for others to use.

The PKGBUILD will:
Download the R bundle you created, primarily just for the modified gnm (if I recall correctly), clone the devel branch of the git repo, create an arch-specific R bundle, copy the modified gnm and install the JASP R package, then will work through your qmake/make system.
It then just copies everything to /usr/share/jasp-desktop and installs the icon and .desktop file elsewhere.

The pkgbuild only really depends on the new #includes you added (and will not build otherwise). There is no modified code otherwise. I suppose you could just merge the pkgbuild into the repo though?

**Comment by stephensrmmartin** [comment]
A side note: The make *will fail* if you try to build in the source directory itself. You actually *must* build in a separate directory. It will fail when copying resources or the help file because 'cp' will refuse to copy a file to itself.  The docs currently state that it's recommended to build in a separate directory but indeed it is required to.

The arch pkgbuild is now here: https://aur.archlinux.org/packages/jasp-desktop-git/
You can click 'view pkgbuild' to see what I have written.

**Comment by jonathon-love** [comment]
> Download the R bundle you created, primarily just for the modified gnm (if I recall correctly)

the modified *gnm* is actually only necessary for OS X, so you could use arch's R installation if you wanted.

i'll make and merge a 0.7.1.7 into master, and then your script can clone from master. master always contains the most recent release (so when people use your script, they'll always have a proper release; this will make it easier for us when they submit bugs reports!)

> A side note: The make will fail if you try to build in the source directory itself. You actually must build in a separate directory.

yeah, i've been aware of this, but haven't come up with a good solution yet.

> The arch pkgbuild is now here: https://aur.archlinux.org/packages/jasp-desktop-git/

awesome!

**Comment by jonathon-love** [comment]
> i'll make and merge a 0.7.1.7 into master

done.

so i'd like to provide some instructions for using your installer, like i have for ubuntu in the user guide:

https://jasp-stats.org/user-guide/

how would one install JASP using this script?

**Comment by stephensrmmartin** [comment]
Arch users should know how to use the AUR.

```
git clone https://aur.archlinux.org/jasp-desktop-git.git
cd jasp-desktop-git
makepkg -si
```
And that should work.

**Comment by jonathon-love** [comment]
awesome.

it doesn't need to be run as superuser or anything? doesn't need sudo?

**Comment by stephensrmmartin** [comment]
They will be prompted for their password when pacman attempts to install the package.
In fact, they should never build as root. If they do and the bash script contains a mistake (e.g., rm -rf /usr/share instead of rm -rf $pkgdir/usr/share), then they can destroy their installation.

**Comment by stephensrmmartin** [comment]
For reference, makepkg -s means 'grab all dependencies needed to build and use this package' and -i means 'then install the package afterward'

I would also recommend to the user to not clear the src/ directory after building, because right now I backup the custom R bundle to that directory. When you build the package again, it will restore the custom R bundle if it is present, and has to rebuild it if it isn't present.
So I would only clear src if the build is failing.

**Comment by stephensrmmartin** [comment]
The latest version just finished compiling.  Everything works as expected. The only remaining "issue" is that it complains about R packages not being the expected version. I'm not sure which component of JASP is defining expected R package versions, but basically every package in the custom R bundle is more updated than the one JASP expects.

Everything still works though. It is the only warning I see.

Should I close the thread?

**Comment by jonathon-love** [comment]
> The only remaining "issue" is that it complains about R packages not being the expected version

yeah, don't worry about that too much; all the versions i ship complain about that too :P that's something i'm working on.

i've updated the user guide to explain how to install under arch linux:

https://jasp-stats.org/user-guide/

thanks for all your work!
thanks for

**Comment by jonathon-love** [comment]
> A side note: The make will fail if you try to build in the source directory itself. You actually must build in a separate directory.

i've fixed this now, btw.

**Comment by jonathon-love** [comment]
> Edit: Ooh, actually. I had to package boost-nowide too

i've release 0.7.1.8 today, and i've removed the dependency on boost-nowide (included it in the project, actually). so if you won't need nowide in future.

cheers

**Comment by stephensrmmartin** [comment]
Got it. I bumped the version and removed the dep.

**Comment by stephensrmmartin** [comment]
/home/hwkiller/Builds/mine/jasp-git/jasp-desktop-git/src/jasp-desktop/JASP-Desktop/analysisforms/regressionloglinearbayesianform.cpp:2:48: fatal error: ui_regressionloglinearbayesianForm.h: No such file or directory

Compiling .9 fails

**Comment by jonathon-love** [comment]
fixed!

**Comment by jonathon-love** [comment]
hey,

i've moved away from using our provided R bundle for JASP under linux, and are now using the system's R installation. you can continue using the R bundle of course, but i won't be adding required packages to it (i'll keep you in the loop when we require another package; we'll be requiring conting [and it's dependencies] soon, and probably the new afex package too)

new build instructions:
https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-building-guide.md

the other change is that JASP will look for R in `/usr/lib/R`, and packages in `/usr/lib/R/library` and `/usr/lib/R/site-library`

so you can go one of two ways; transition to using the system R, or maintain the JASP bundle and patch the JASP sources before building.

happy to provide any assistance you need.

**Comment by stephensrmmartin** [comment]
Eek, ok. That would require an arch package for every dependency, as well as their dependencies. I'll think a bit more about how to implement that.

**Comment by jonathon-love** [comment]
ooh, it does also search for packages *beside* the JASP executable. so it installs the JASPR package beside `JASP` and `JASPEngine`. you could just place all the other packages there as well.

**Comment by stephensrmmartin** [comment]
You mean:

JASP
JASPEngine
Help/
bayes64/
BayesFactor/
boot/
car/
...
?

**Comment by jonathon-love** [comment]
yup

**Comment by stephensrmmartin** [comment]
Seems messy, but I'll update it to work like that for now.

I'll work on transitioning it over to using the system packages. I think that's a better method anyway. No duplication that way.

I may be able to create one large pkgbuild that generates all the needed packages.

**Comment by jonathon-love** [comment]
> Seems messy, but I'll update it to work like that for now.

yeah tots :P

i wanted to create an R folder beside JASP, JASPEngine, and then put the JASPR package inside there (this would also tidy things up for you). but copying/creating folders can be a dog in qmake.

actually, now i think about it, it's copying which is the issue, not the creating of dirs... maybe i can do that. let me get back to you.

**Comment by stephensrmmartin** [comment]
Wait wait, that's what I currently have, and it appears to be working.
My jasp-desktop folder is:
total 3936
drwxr-xr-x 1 root root      80 Aug 31 16:34 Help
-rwxr-xr-x 1 root root 3346832 Aug 31 16:29 JASP
-rwxr-xr-x 1 root root  676304 Aug 31 16:29 JASPEngine
drwxr-xr-x 1 root root      60 Aug 19 14:38 R
drwxr-xr-x 1 root root      32 Aug 19 14:38 Resources

Where R/ is 
drwxr-xr-x 1 root root  296 Aug 31 16:34 bin
drwxr-xr-x 1 root root   86 Aug 31 16:34 etc
drwxr-xr-x 1 root root  164 Aug 31 16:34 include
drwxr-xr-x 1 root root   14 Aug 31 16:34 lib
drwxr-xr-x 1 root root 1762 Aug 19 14:39 library
drwxr-xr-x 1 root root   70 Aug 31 16:33 modules

**Comment by jonathon-love** [comment]
yeah, but i broke that :P
that R folder is no longer used, and i want to replace it with another which just contains packages.

**Comment by stephensrmmartin** [comment]
Ah, gotcha. Yeah, I'll work on creating the various cran packages for arch. and just dump the bundle into the root for now.

**Comment by stephensrmmartin** [comment]
Is that broken as of v.12 or is that in the dev branch only right now?

**Comment by jonathon-love** [comment]
not in .12, what's in dev right now (come on, i'll give you more notice than that :P ) planning a 0.7.2 in a couple of weeks, will probably be in that.

**Comment by stephensrmmartin** [comment]
Oh, and a clarification question;
1) is the bundle required for compilation?
2) If so, where should the individual packages be located with respect to the src tree?

**Comment by jonathon-love** [comment]
the only packages needed for compilation are RInside and Rcpp.

it expects these in `/usr/lib/R/library/RInside` and `/usr/lib/R/library/Rcpp`

but if you need to change this location, you can patch jasp-desktop/JASP-Engine/JASP-Engine.pro

(i don't know what arch is like, but in debian there's a patch system built into packaging. i've been patching this file in my ubuntu packages before i made these changes)

**Comment by stephensrmmartin** [comment]
Arch has patching, yeah. It's how I patch in simplesem when building.

Well, perhaps it would be easier for now to just package RInside and Rcpp for dependencies, then create the bundle and dump the library contents to .../R/ or .../ itself.

**Comment by jonathon-love** [comment]
yup.

**Comment by stephensrmmartin** [comment]
Maybe... since the r-cran-* packages are not really wanted by arch (for the same reason that many distributions don't bother packaging the bajillion python libs found via the python installers), I could create a standalone package for the jasp R dependencies, install those to the system library folder, and just declare that the package provides r-cran-{rcpp,rinside,bayesfactor,*}.

That would be far easier to maintain (update occasionally with Rscript, install with R-script). Still messy, but I don't know of a better solution.

**Comment by stephensrmmartin** [comment]
In file included from /usr/lib/R/library/Rcpp/include/RcppCommon.h:29:0,
                 from /usr/lib/R/library/Rcpp/include/Rcpp.h:27,
                 from /usr/lib/R/library/RInside/include/RInsideCommon.h:38,
                 from /usr/lib/R/library/RInside/include/RInside.h:26,
                 from /home/hwkiller/Builds/mine/jasp-git/jasp-desktop-git/src/jasp-desktop/JASP-Engine/rbridge.h:4,
                 from /home/hwkiller/Builds/mine/jasp-git/jasp-desktop-git/src/jasp-desktop/JASP-Engine/engine.cpp:14:
/usr/lib/R/library/Rcpp/include/Rcpp/r/headers.h:52:15: fatal error: R.h: No such file or directory

R.h is in /usr/include/R/
What might be the issue?

**Comment by stephensrmmartin** [comment]
I'm guessing the build process defines where the R includes /should/ be.
On debian they are in /usr/lib/R/include, but arch they are /usr/include/R/

**Comment by stephensrmmartin** [comment]
ah wait... this may fix it. Let me play with it some more.

**Comment by stephensrmmartin** [comment]
Fixed. Let me know when you merge those changes. I'll merge the new pkgbuild and upload to aur.

The process will now be slightly modified.
I created a package with all the R packages that JASP needs.

'''
git clone https://aur.archlinux.org/jasp-rbundle.git
cd jasp-rbundle
makepkg -si
cd ..
git clone https://aur.archlinux.org/jasp-desktop-git.git
cd jasp-desktop-git
makepkg -si
'''

**Comment by jonathon-love** [comment]
cool. i'm working on making this a bit nicer for you.

a few changes (not yet committed):
 - when you build JASP, it will read the R_HOME variable as the location of R (so you can go back to bundling R with JASP if you like)
 - it will load packages from a directory R-library rather than beside the JASP and JASPEngine executables.

i.e.

JASP
JASPEngine
R-library/ ... packages go in here

this should simplify things a bit.

**Comment by stephensrmmartin** [comment]
So R-library/ will have JASPR within it?

I think the way I am currently doing it will work fine.

I have jasp-rbundle which is nothing more than a collection of R packages installed to the system library (/usr/lib/R/library/).
It provides and conflicts with any other packages that provide those packages (but arch only supplies r; it doesn't package *any* of the cran packages outside of the recommended base install).
The AUR has a few r-cran-* packages, but not enough to worry about.
So really, the jasp-rbundle is just a massive package supplying several R packages to the sys library.

jasp-desktop-git then depends on the jasp-rbundle package

When building jasp-desktop-git, I patch in sem and change the include location:
```
diff --git a/JASP-Engine/JASP-Engine.pro b/JASP-Engine/JASP-Engine.pro
index a030e79..5bdcdad 100644
--- a/JASP-Engine/JASP-Engine.pro
+++ b/JASP-Engine/JASP-Engine.pro
@@ -60,7 +60,7 @@ QMAKE_CXXFLAGS += -Wno-c++11-extra-semi
 win32:QMAKE_CXXFLAGS += -DBOOST_USE_WINDOWS_H
 
 INCLUDEPATH += \
-    $$R_HOME/include \
+	/usr/include/R \
     $$R_HOME/library/RInside/include \
     $$R_HOME/library/Rcpp/include
```
Then I only package JASP JASPEngine, Resources, and now R-library to install to /usr/share/jasp-desktop/

**Comment by jonathon-love** [comment]
ok, i've merged the changes i describe above into development.

**Comment by stephensrmmartin** [comment]
Devel compiles fine.
I'm not sure what "r11t Learning" is; I assume it is some example for the iowa gambling task as per a paper by Wagenmakers?

Anyway, great job on the merged features. I'll wait until a tagged release before pushing to the AUR.

**Comment by jonathon-love** [comment]
hey, it's me again :P

i've changed the behaviour again slightly. now the JASP package is installed into `$program_dir/R/library`, and (assuming R_HOME hasn't been defined at compile time) it will check at runtime whether there's an R installation at `$program_dir/R`, and if not drop back to `/usr/lib/R`.

this allows ultimate flexibility:
 - the R install location can be defined at compile time
 - failing that, JASP will use the custom R install (in $program_dir)
 - failing that, JASP can use the system R install

additionally, if there's an issue with a particular version of an R package, we can just place a compatible version in $program_dir/R/library (irrespective of whether a custom R install exists), and JASP will use that instead.

(there's an issue with the versions of R from CRAN under ubuntu trusty for example).

so we can use the system defaults, but at the same time override the R version, and package versions as necessary. i think i'm pretty happy with this.

[yeah, r11t Learning was an attempt to do the IOWA gambling task stuff. we need some upstream changes to stan/JAGS before we can do it properly though]

**Comment by stephensrmmartin** [comment]
I'm trying to build the development branch now, and I'm experiencing a runtime error.

Here are the steps I've taken:
I patched the project file to add arch linux's R include files at /usr/include/R
I did not define R_HOME at compile time, because my R-bundle package installs to /usr/lib/R/library. This is where RInside is installed to.

JASP builds without any errors, as far as I can tell.

When I run JASP, a segmentation fault occurs.
When I run JASPEngine, I get the error:
```
/usr/share/jasp-desktop/JASPEngine: error while loading shared libraries: libRInside.so: cannot open shared object file: No such file or directory
```
And running ldd on that executable indeed shows that libRInside.so can't be found, although it *is* in /usr/lib/R/library/RInside/lib/

How might you suggest fixing this issue? Is this a JASP build issue or a configuration issue?
Note: the latest versioned release works fine.

**Comment by stephensrmmartin** [comment]
Update: I tried forcing the linker to recognize RInside by using LD_LIBRARY_PATH and the RInside lib was found, but then JASP failed because JASP wasn't in /usr/lib/R/library (it was in /usr/share/jasp-desktop/R/library

So now I have repackaged my R bundle to put all of its libraries in /usr/share/jasp-desktop/R/library.
However, now the build fails without any warning really. It failed at the final step: 
```
g++ -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-rpath-link,/usr/lib -o ../JASP main.o analyses.o mainwindow.o datasettablemodel.o enginesync.o availablefields.o asyncloader.o maintableview.o maintablehorizontalheader.o assignbutton.o availablefieldslistview.o boundcheckbox.o boundlistview.o expanderbutton.o infopopup.o ribbonbutton.o toolbutton.o boundtextbox.o boundgroupbox.o progresswidget.o anovamodelwidget.o listview.o draganddrop.o assignbuttonmenu.o tableview.o boundpairstable.o boundcombobox.o boundtableview.o tableviewmenueditor.o tableviewmenueditordelegate.o analysisform.o anovabayesianform.o ttestpairedsamplesform.o anovamultivariateform.o ttestbayesianonesampleform.o ancovaform.o anovaform.o descriptivesform.o anovaonewayform.o ttestonesampleform.o ttestindependentsamplesform.o ancovamultivariateform.o regressionlinearform.o correlationform.o boundassignwidget.o anovarepeatedmeasuresform.o contingencytablesform.o correlationpartialform.o ribbonwidget.o ribbonsem.o ribbonanalysis.o ribbonhome.o semsimpleform.o boundtextedit.o stealthbutton.o ttestbayesianindependentsamplesform.o ttestbayesianpairedsamplesform.o itemmodelselectitem.o itemmodelselectvariable.o tabbar.o optionsform.o textmodellavaan.o terms.o term.o tablemodelanovamodelnuisancefactors.o tablemodelpairsassigned.o tablemodelvariables.o tablemodelvariablesassigned.o tablemodelvariablesavailable.o tablemodelvariableslevels.o tablemodelvariablesoptions.o tablemodelanovamodel.o tablemodelcontrasts.o tablemodelanovadesign.o appdirs.o tablemodelanovawithinsubjectcells.o ancovabayesianform.o anovarepeatedmeasuresbayesianform.o correlationbayesianform.o contingencytablesbayesianform.o correlationbayesianpairsform.o application.o regressionlinearbayesianform.o qutils.o activitylog.o lrnamreply.o lrnam.o webview.o button.o r11tlearnform.o ribbonr11tlearn.o breadcrumbs.o verticaltabbar.o verticaltabwidget.o backstagewidget.o fsentrywidget.o fsbrowser.o verticalscrollarea.o elidelabel.o backstageosf.o backstagecomputer.o backstagepage.o opensavewidget.o regressionloglinearform.o regressionloglinearbayesianform.o fsbmexamples.o fsbmodel.o fsbmcomputer.o fsbmrecent.o fsbmrecentfolders.o fileevent.o boundsingleitemview.o binomialtestform.o bayesianbinomialtestform.o bffromtform.o variableswidget.o levelstablemodel.o variablestablemodel.o fsbmosf.o osfnam.o onlinedatamanager.o onlinedataconnection.o onlinedatanodeosf.o onlinedatanode.o onlineusernode.o onlinenode.o onlineusernodeosf.o qrc_backstage.o qrc_html.o qrc_icons.o qrc_resources.o moc_analyses.o moc_datasettablemodel.o moc_enginesync.o moc_analysisform.o moc_assignbutton.o moc_availablefieldslistview.o moc_boundcheckbox.o moc_boundlistview.o moc_expanderbutton.o moc_infopopup.o moc_ribbonbutton.o moc_toolbutton.o moc_boundtextbox.o moc_boundgroupbox.o moc_anovabayesianform.o moc_ttestpairedsamplesform.o moc_anovamultivariateform.o moc_ttestbayesianonesampleform.o moc_boundpairstable.o moc_asyncloader.o moc_progresswidget.o moc_anovamodelwidget.o moc_listview.o moc_assignbuttonmenu.o moc_tableview.o moc_maintableview.o moc_tablemodel.o moc_ancovaform.o moc_anovaform.o moc_descriptivesform.o moc_anovaonewayform.o moc_ttestindependentsamplesform.o moc_ttestonesampleform.o moc_ancovamultivariateform.o moc_maintablehorizontalheader.o moc_regressionlinearform.o moc_mainwindow.o moc_correlationform.o moc_boundcombobox.o moc_tableviewmenueditor.o moc_tableviewmenueditordelegate.o moc_boundassignwidget.o moc_anovarepeatedmeasuresform.o moc_contingencytablesform.o moc_correlationpartialform.o moc_ribbonwidget.o moc_ribbonsem.o moc_ribbonanalysis.o moc_ribbonhome.o moc_semsimpleform.o moc_boundtextedit.o moc_stealthbutton.o moc_ttestbayesianindependentsamplesform.o moc_ttestbayesianpairedsamplesform.o moc_itemmodelselectvariable.o moc_tabbar.o moc_optionsform.o moc_textmodellavaan.o moc_tablemodelpairsassigned.o moc_tablemodelvariables.o moc_tablemodelvariablesassigned.o moc_tablemodelvariablesavailable.o moc_tablemodelvariableslevels.o moc_tablemodelvariablesoptions.o moc_tablemodelanovamodel.o moc_tablemodelcontrasts.o moc_tablemodelanovadesign.o moc_tablemodelanovawithinsubjectcells.o moc_ancovabayesianform.o moc_anovarepeatedmeasuresbayesianform.o moc_correlationbayesianform.o moc_contingencytablesbayesianform.o moc_correlationbayesianpairsform.o moc_application.o moc_regressionlinearbayesianform.o moc_activitylog.o moc_lrnamreply.o moc_lrnam.o moc_groupbox.o moc_button.o moc_webview.o moc_r11tlearnform.o moc_ribbonr11tlearn.o moc_breadcrumbs.o moc_verticaltabbar.o moc_backstagewidget.o moc_fsentrywidget.o moc_fsbrowser.o moc_verticalscrollarea.o moc_elidelabel.o moc_backstageosf.o moc_backstagecomputer.o moc_backstagepage.o moc_opensavewidget.o moc_regressionloglinearform.o moc_regressionloglinearbayesianform.o moc_fsbmexamples.o moc_fsbmodel.o moc_fileevent.o moc_boundsingleitemview.o moc_binomialtestform.o moc_bayesianbinomialtestform.o moc_bffromtform.o moc_variableswidget.o moc_fsbmosf.o moc_osfnam.o moc_onlinedatamanager.o moc_onlinedataconnection.o moc_onlinedatanodeosf.o moc_onlinedatanode.o moc_onlineusernode.o moc_onlinenode.o moc_onlineusernodeosf.o   -L.. -lJASP-Common -lboost_filesystem -lboost_system -larchive -lrt -lQt5WebKitWidgets -lQt5WebKit -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
make[1]: Leaving directory '/home/hwkiller/Builds/mine/jasp-git/jasp-desktop-git/src/jasp-build/JASP-Desktop'
```

**Comment by stephensrmmartin** [comment]
Yet another update:
I reverted my R bundle to use /usr/lib/R/library (system libs).
I then compiled the project using:
qmake R_HOME=/usr/lib/R PREFIX=/usr
make

RInside is still not found without manually specifying it in LD_LIBRARY_PATH. This is odd, because everything I've seen seems correct: -L/usr/lib/R/library/RInside/lib -lRInside is correct, and libRInside.so is in that directory.

Regardless, when I start JASP with LD_LIBRARY_PATH, RInside is found, but segmentation fault occurs.
When i do the same with JASPEngine, I get the following error:
```
terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
  what():  No such file or directory
zsh: abort (core dumped)  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/R/library/RInside/lib/ 
```

**Comment by stephensrmmartin** [comment]
Running JASP in gdb:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe1b28700 (LWP 3909)]
[New Thread 0x7fffd4a81700 (LWP 3910)]
QLayout: Attempting to add QLayout "" to BackStageWidget "backStage", which already has a layout
QLayout: Attempting to add QLayout "" to VariablesWidget "variablesPage", which already has a layout
[New Thread 0x7fffcfd1d700 (LWP 3911)]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000574044 in BackstageOSF::setOnlineDataManager(OnlineDataManager*) ()
```
JASPEngine in gdb has the above stated problem with boost::interprocess::

**Comment by stephensrmmartin** [comment]
Ok, I just did a git bisect. Commit a2bd7c9ded51d7ad3dfe4ffb57d6cdc00d8f296e is the first commit where:
1) RInside is not found and must be specified manually via LD_LIBRARY_PATH
2) the errors above are found.
Before that commit, JASP builds and runs fine.

**Comment by jonathon-love** [comment]
1) You should have a lot of flexibility with where you put JASP dependencies (the R packages) now, so i'm surprised that's an issue. you should be able to place them in:

 - /usr/lib/R/library
 - \*an R location of your choice\*/library    (by specifying R_HOME at compile time)
 - \*location of JASP execurable\*/R/library

2) to my knowledge we don't have this issue under windows, osx or ubuntu, but we'll look into it (this stuff is in development, so i am expecting some issues).

**Comment by jonathon-love** [comment]
2) fixed!

**Comment by jonathon-love** [comment]
hey, we've made a JASP 0.7.5 beta 1, and it's in the master branch.

we're not going to publish it (we'll publish a beta 2 soon), but it's very close to what the next release will be.

**Comment by stephensrmmartin** [comment]
I assume this includes all the changes from development with, e.g., the new R/library locations and such? (R_HOME, yadda yadda).
I'll go ahead and push the beta 1 to prep others for the next release. I'll finally upload my R bundle package for others to use.

**Comment by jonathon-love** [comment]
> I assume this includes all the changes from development

yup.

ooh, just re-reading this:

> 1) I either must ship a full R installation with JASP, or keep all JASP dependencies in /usr/lib/R/library and move the JASP package to that directory.

you don't have to put the JASP package in /usr/lib/R/library (but it won't hurt). i put it in `%JASP_executable_location%/R/library`. you can see locations of all the install files here, at the bottom of the launchpad build log:

https://launchpadlibrarian.net/228825749/buildlog_ubuntu-wily-amd64.jasp_0.7.5.0.1-0ubuntu0ppa7~wily_BUILDING.txt.gz

jonathon

**Comment by mgundogdu1** [comment]
Hi.
I installed Jasp about a month ago and its worked fine until last week. Last week I cant open and also I cant install another machine. Then I follow the error and I copy some files and one folder to in R directory and problem solved:
/usr/share/jasp-desktop/R/library/Rcpp/include/Rcpp.h to /usr/lib/R/library/RInside/include/
/usr/share/jasp-desktop/R/library/Rcpp/include/RcppCommon.h to /usr/lib/R/library/RInside/include/
/usr/share/jasp-desktop/R/library/Rcpp/include/Rcpp/ to /usr/lib/R/library/RInside/include/

Thanks for great efforts.
Best regards.
