### ISSUE TITLE
JASP site is down

### ISSUE THREAD

**Issue by stephensrmmartin** [jasp-stats/jasp-desktop#873]
I am not sure if you've noticed, but jasp-stats.org is unable to load currently.

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

Others are reporting a similar problem.

**Comment by jonathon-love** [comment]
yeah, i know :(

i've contacted our host, and they're working on it.

totally cramping my style!

**Comment by jonathon-love** [comment]
up again!
