### ISSUE TITLE
Ribbon missing?

### ISSUE THREAD

**Issue by stephensrmmartin** [jasp-stats/jasp-desktop#874]
I built the latest master build (v0.7.1.7), and I only see the "File" and "Common" ribbons. Should there be others (e.g., simple sem?).

**Comment by jonathon-love** [comment]
i've (temporarily) dropped SEM support from linux, just because it requires so many R packages, and i haven't got around to adding them to my PPA  (and it is a pretty half-baked module too). but i did that a while ago.

**Comment by stephensrmmartin** [comment]
Ah, got it. Thanks.

I wish the Onyx developer could collaborate with you all to implement a visual lavaan model creator for jasp (and even cooler -- a visual jags modeler in the likeness of Kruschke's diagrams; If I knew any CPP, I would jump on that project, but alas ...).

**Comment by jonathon-love** [comment]
yeah, all these ideas are eminently doable, it's just a matter of resources. hopefully as JASP gains momentum, and we gain credibility, funding agencies will start throwing money at us for these sort of things.

> I wish the Onyx developer could collaborate with you

them open-sourcing their code would be a good start

**Comment by stephensrmmartin** [comment]
If only they would.

In my arch linux package, I am re-enabling the SEM option, but I am messaging the user that it is an unsupported feature should any errors occur.

**Comment by jonathon-love** [comment]
cool.
