### ISSUE TITLE
Can save to file

### ISSUE THREAD

**Issue by caschoen** [jasp-stats/jasp-desktop#875]
Working on Win7, standard NTFS, all rights, can save, message:
Unable to save file
boost::filesystem::permission

**Comment by jonathon-love** [comment]
quick Q, are you saving *over* an existing file, or saving a *new* file?

**Comment by dropmann** [comment]
another Q, if you are saving over a file, is it possible to confirm the owner of that file? properties->security->advanced->owner

**Comment by dropmann** [comment]
i think i have found the problem.

**Comment by dropmann** [comment]
fixed it.

**Comment by jonathon-love** [comment]
pull request?

**Comment by dropmann** [comment]
just rebasing and then i'll commit and request.

**Comment by jonathon-love** [comment]
hey @caschoen,

i've rolled us back to 0.7.1.5 which doesn't have the issue. we'll try and push out a 0.7.1.8 in the next 24 hours.

**Comment by caschoen** [comment]
Thanks, I like your software
Christian

Von: Jonathon Love [mailto:notifications@github.com]
Gesendet: Freitag, 21. August 2015 10:30
An: jasp-stats/jasp-desktop
Cc: Christian Schoen
Betreff: {Disarmed} Re: [jasp-desktop] Can save to file (#875)


hey @caschoen<https://github.com/caschoen>,

i've rolled us back to 0.7.1.5 which doesn't have the issue. we'll try and push out a 0.7.1.8 in the next 24 hours.
