### ISSUE TITLE
Colon in ANOVA UI

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#886]
colons are strictly verboten!

![screen shot 2015-08-23 at 2 12 12 pm](https://cloud.githubusercontent.com/assets/3240247/9428158/16bc90de-49a1-11e5-9117-8ce59dbc6a7d.png)

**Comment by raviselker** [comment]
Why?

**Comment by jonathon-love** [comment]
they're just unnecessary clutter, and we use indentation to indicate hierarchy.

i've been most heavily influenced by [the Gnome HIG](https://developer.gnome.org/hig/stable/) and it [doesn't use them](https://developer.gnome.org/hig/stable/visual-layout.html.en).
