### ISSUE TITLE
Windows installer should clean up after itself a bit better

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#895]
1. the windows installer currently leaves shortcuts behind (in the start page)
2. it could also remove the version specific temp folders (if possible)

**Comment by dropmann** [comment]
i found the shortcuts issue. Will look into the temp folder thing on Monday.

**Comment by jonathon-love** [comment]
cool.

**Comment by dropmann** [comment]
Couldn't solve the appdata\roaming issue because the installer is set for all users rather than current. I have emailed the new file.

**Comment by jonathon-love** [comment]
fixed!
