### ISSUE TITLE
Changing variable type deletes data

### ISSUE THREAD

**Issue by raviselker** [jasp-stats/jasp-desktop#896]
When you have a character nominal variable in your data set and you change the variable type you lose your data and you cannot change it back to character nominal variable to get your data back. This means that every time you accidentally change the variable type for these types of variables you have to reload the data.
 
<img width="91" alt="screen shot 2015-08-29 at 13 21 36" src="https://cloud.githubusercontent.com/assets/4669197/9561710/76407548-4e51-11e5-89d9-af0e3479bbcd.png">
<img width="92" alt="screen shot 2015-08-29 at 13 21 53" src="https://cloud.githubusercontent.com/assets/4669197/9561711/765f17aa-4e51-11e5-93d3-d31b38da9395.png">

**Comment by jonathon-love** [comment]
we need an undo facility... this won't happen for a while.
