### ISSUE TITLE
Ioana Ileana: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by IoanaIleana** [jasp-stats/jasp-desktop#897]
<p><br><blockquote>This issue was created by @IoanaIleana via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by jonathon-love** [comment]
hi @IoanaIleana,

you would like to contribute to the JASP project?

**Comment by IoanaIleana** [comment]
Hi there! Thanks for the quick reply! : ) 
Yup I would love to contribute. Not sure though if I can be of any help : )
I am a former SDE umm "converted" to academia. Did a lot of C/C++, some Java as well as some database research BUT have very limited experience with JS and kinda low knowledge in stats. I am actually trying to improve on those currently and (coincidence \o/) just discovered the JASP project (while unfocusedly browsing this morning). The aims and topics got me instantly interested.
Would you have time to chat a bit about ways I could help? I am available every day next week starting from 5pm (CEST).
Thanks again,
Ioana

**Comment by jonathon-love** [comment]
yup, for sure. 1700 CEST tomorrow sounds good. my skype name is jeru.habib

**Comment by IoanaIleana** [comment]
Hi again & sorry. I just found out I am actually "booked" for a meeting today at 17:00 : ( Would it possible to chat tomorrow or on Wed? (same hour?) 
I apologize for the setback,
Ioana 

p.s. My Skype id is ioana.maria.ileana. I can also do irc :)

**Comment by jonathon-love** [comment]
yup, tues sounds good.

cheers

**Comment by jonathon-love** [comment]
hey, did you see this? just came out:

http://blog.efpsa.org/2015/09/01/introducing-jasp-a-free-and-intuitive-statistics-software-that-might-finally-replace-spss/
