### ISSUE TITLE
JASP output does not show plot

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#898]
Quentin created some .jasp files. When I open these I can see that the plotting option was selected, but I do not see the plot itself. See screenshot. Maybe the JASP versions do not align? Mine is....actually, I can't easily get that information. Maybe we can have an "About" option that provides this information?
![image](https://cloud.githubusercontent.com/assets/8603015/9568305/f6789ea8-4f45-11e5-9f33-354b16c4c1a4.png)

**Comment by jonathon-love** [comment]
can you send through the file?

**Comment by jonathon-love** [comment]
... and what version of JASP are you using?

**Comment by jonathon-love** [comment]
i am expecting a couple of little breakages like this with some recent changes.

**Comment by EJWagenmakers** [comment]
Attached is the file.
I'm using JASP 0.7.1.5
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
you can't send attachments to GitHub :/ so you'll have to send it to me directly.

**Comment by quentingronau** [comment]
Hi, 

I have the same issue. I created the files with the latest JASP version 0.7.1.8, but when I open them again (with the same JASP version), the plots are not displayed.

![plotnotvisible](https://cloud.githubusercontent.com/assets/8697436/9568538/a04f4778-4f4c-11e5-86f8-a320fb711af0.png)

**Comment by jonathon-love** [comment]
hmm, 'tis unusual. i can't reproduce it here.
