### ISSUE TITLE
Feature request: Pairwise comparisons following rmANOVA

### ISSUE THREAD

**Issue by nickwan** [jasp-stats/jasp-desktop#90]
Hi JASP team,

In SPSS, I would have to write syntax in order to include all the meaningful pairwise comparisons related to repeated measures ANOVA results. It read like this:

GLM time1_type1 time2_type1 time1_type2 time2_type2 BY Group
  /WSFACTOR=type 2 Polynomial time 2 Polynomial 
  /METHOD=SSTYPE(3)
  /EMMEANS=TABLES(Group*type*time) COMPARE(Group) ADJ(LSD)
  /EMMEANS=TABLES(Group*type*time) COMPARE(type) ADJ(LSD)
  /EMMEANS=TABLES(Group*type*time) COMPARE(time) ADJ(LSD)
  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=type time type*time
  /DESIGN=Group.

In this case, I wanted three separate pairwise comparisons: one comparing groups, holding type and time constant; one comparing type, holding group and time constant; one comparing time, holding group and type constant. 

Even though JASP features a t-test function, it's time-intensive to set up multiple .csv's in order to execute a pairwise comparison following an rmANOVA. Having a feature like this built-in would certainly benefit a lot of people looking at 2-way and >2-way interactions.

**Comment by da-bu** [comment]
Hi, thanks for the great work on JASP!

I cannot find pairwise comparisons for RM ANOVA (I have the currently lastest version 0.7.1.12). In the RM ANOVA panel, I have "Model", "Options" and "Descriptives Plots", but no option for pairwise comparisons. Am I missing something here?

**Comment by luq-0** [comment]
I'm only exploring JASP at the moment, but I second the previous comment: while there are post-hoc tests in rm-ANOVA, it outputs different tables. I can't find the equivalent pairwise comparisons option that is available through SPSS syntax using /EMMEANS, which is comparing differences between levels of a factor, on every level of other factors. Referenced commit seems to add only post-hoc tests which output tables for comparing between levels of the same factor, in separate tables for each factor, and that's not what this issue describes.
