### ISSUE TITLE
Comment system is awesome!

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#906]
a few tweaks:

 - the starting title can just be `Results` rather than `Untitled Results`
 - we should also push this title to the window title, and the default save file name (but leave this to me, because i'm changing all that stuff at the moment)
 - when editing, it would be nice to be able to end editing with a key combination; i.e. cmd+enter (like in thunderbird, how you can go cmd+enter and it means send)
 - i think leaving editing by clicking outside the edit box, should not select or unselect an analysis
 - clicking *into* some notes, when a different analysis is selected, should unselect that analysis
 - perhaps we need a little + or x beside `Add note` and `Remove note` respectively
 - are these buttons different sizes, or is that an optical illusion?:

<img width="241" alt="screen shot 2015-08-31 at 10 32 00 pm" src="https://cloud.githubusercontent.com/assets/3240247/9589677/2e45be34-5030-11e5-824b-987e5554a8a6.png">

.... i think it's an optical illusion

(we've decided not to italicise notes? i'm ok with that)

i've merged your work into the banch `next`

**Comment by dropmann** [comment]
these things have been done and committed to the temp_development branch. Let me know wheat you think.

**Comment by raviselker** [comment]
Pasting text into the title when editing the title crashes JASP.
