### ISSUE TITLE
File version needs to be bumped with the comment system?

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#908]
opening in the current 0.7.1.11:

<img width="525" alt="screen shot 2015-08-31 at 10 59 28 pm" src="https://cloud.githubusercontent.com/assets/3240247/9590287/fef847c4-5033-11e5-8a22-3c15c4e7adca.png">

**Comment by jonathon-love** [comment]
even without bumping the file version number, this error message suggests the current analysis loader isn't perfect. surely it could just ignore fields it doesn't know about, or did we change something structural?

**Comment by dropmann** [comment]
This has been fixed.
