### ISSUE TITLE
Using Excel as Data Set

### ISSUE THREAD

**Issue by sametdeniz** [jasp-stats/jasp-desktop#911]
Hello Jonathon,

I downloaded JASP and tried to use it but it seems I cannot use an Excel file as a data set. Is there any way to open Excel files in JASP? If not, do you consider making it available? 

Thank you for all of your efforts and response in advance,

Best regards,

Samet Deniz

**Comment by jonathon-love** [comment]
yes, absolutely. it's on our todo list. in the mean time, you can export your data from excel as a .csv file, and then open that in JASP.

cheers

**Comment by sametdeniz** [comment]
Thanks a lot!

**Comment by boutinb** [comment]
We are busy to support ODS file (which is supported by Excel and LibreOffice/OpenOffice).
