### ISSUE TITLE
Could person-oriented statistics be included in JASP?

### ISSUE THREAD

**Issue by Makoi** [jasp-stats/jasp-desktop#913]
I've just learnt about this software and my question is could person-oriented statistics be included?

I'm refering to the approach propagated by Bergman, Magnusson or von Eye (http://eha.ut.ee/wp-content/uploads/2014/04/2_02_bergman_wangby.pdf, http://link.springer.com/chapter/10.1007%2F978-3-531-90537-2_8). I don't know whether there would copyright issues or not, but should this area of psychological statistics be included, I believe that would add quite a lot to this enterprise which is why I wanted to present this question as a Feature Request.

**Comment by jonathon-love** [comment]
hi, i've just had a quick glance at the article. it's not immediately clear to me what *person oriented statistics* is.

perhaps you could make some concrete suggestions for what analyses JASP could provide.

**Comment by Makoi** [comment]
Oh, ok, alright; I tried to make a quick list:
* latent class analysis
* latent profile analysis
* configural frequency analysis
* prediction configural frequency analysis

Here's their journal: http://www.person-research.org/, and here's a program called SLEIPNER that I believe can do person-oriented statistics: http://w3.psychology.su.se/sleipner/

**Comment by renenob** [comment]
This would really be cool!

**Comment by jonathon-love** [comment]
yup, these are good suggestions. at the moment our focus is providing the core analyses used very commonly, but as we get better coverage, we can begin to implement more niche analyses, like these ones, too. thanks for your suggestions.

**Comment by boutinb** [comment]
Issue closed due to too long inactivity
