### ISSUE TITLE
Hierachical multiple regression

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#928]
hey @quentingronau,

@borisma was asking

> How do I add an additional Model (a.k.a. „block“ in SPSS) for hierarchical multiple regression? I couldn’t find it…. 

what was the issue again? SPSS did something completely weird that we couldn't figure out. boris sounds like he might actually know how it works, so it could be good to hear his take on it.

cheers

**Comment by renenob** [comment]
By "block", he means that the user should have an option as to which predictors and how many predictors to include first in hierarchical regression, and which predictors would be added next.

**Comment by jonathon-love** [comment]
yeah, we understand this much. it's just that SPSS doesn't/didn't do at all what we expected.

**Comment by borisma** [comment]
The main feature is actually to compare the models. The one with only the first block of predictors with the one including an additional block. This is done by R {stats}'s anova(model1, model2) function. The Delta-R2 (R2-Change) actually makes sense only if you do this, because you can then see how much variance of the DV the variables in the second block jointly explain in addition to those of the first block (i.e., when controlling for those of the first block).

**Comment by quentingronau** [comment]
You are absolutely right about the model comparison with R2-Change and I think we should add the "blocks" back in. The weird behavior occured for the stepwise procedures. Assume you enter three predictors in the first block with "backward",

![hierarchicalregression_1](https://cloud.githubusercontent.com/assets/8697436/9703963/8b50fcca-5494-11e5-8097-bfa0cc57c3a1.png)

and two predictors in the second block with "forward" specified.

![hierarchicalregression_2](https://cloud.githubusercontent.com/assets/8697436/9703965/9c821344-5494-11e5-8214-b98f9e473cfc.png)

It is certainly possible that this is wrong, but I would have expected that the backward procedure is done first for only the three predictors in block one, and when this is done, the forward procedure is applied to the two predictors in the second block. However, it seems that SPSS enters all five predictors and then applies the "backward" procedure.

![hierarchicalregression_3](https://cloud.githubusercontent.com/assets/8697436/9703973/d8012964-5494-11e5-9ce4-a36d0a9dcefa.png)

![hierarchicalregression_4](https://cloud.githubusercontent.com/assets/8697436/9703975/dbfb1e76-5494-11e5-8898-a9456269939e.png)

But I definetely see the value of the model comparison with R2-change, so maybe a solution could be to add the blocks back in and to not allow for stepwise procedures if multiple blocks are specified.

**Comment by borisma** [comment]
Yes, that one is really strange, but it is kind of artificial. When doing hierarchical regression, you normally use the method "enter". The different stepwise methods make much more sense when having only one block ("normal" multiple regression). 
But I think the example you give is the only really strange one: if you use the same method in all blocks, it remains understandable (especially with forward and stepwise - they can also be combined in different blocks without resulting in confusion). If you use backwards, the "problem" is that SPSS already gives out several models per block, and this makes it confusing. And combining forward and backward in different blocks as you did, leaves it intractable (at least for me).  
Maybe restrict to enter, forward and stepwise when using multiple blocks?

**Comment by jonathon-love** [comment]
so, the proposal is to allows multiple blocks, but not if the user specifies backwards?
is there any other combination we should prevent?

**Comment by renenob** [comment]
This would be a great improvement. In my experience, hierarchical regression is regularly used, particularly for controlling potential extraneous variables, in Psychological research, and other social science researches.

**Comment by borisma** [comment]
Hi there, I checked it now again, especially with regard to the (very important) option R2-Change and the related F-statistic comparing the models: backward simply makes no sense for hierarchical regression, at least not the way implemented in SPSS: first a model with all variables (regardless of block) is computed, and this is then reduced step by step by removing variables, but also regardless of block (i.e. only regarding the least contribution to R2).
One possibility would be to not allow backward for hierarchical regression. However, different from my last post, there can be also multiple models per block in stepwise and forward (if more than one variable per block reaches significance), and this also leads to more model comparisons than blocks. This is not a problem per se, but usually you are interested in the model comparisons of the *blocks*, which may not appear when using stepwise or forward.
Maybe it would be an option to start with hierarchical regression allowing only "Enter"? 
As renenob says, hierarchical regression / blocks and the corresponding model comparisons definitely has to be implemented ...as soon as possible...   ;)
Best, Boris

**Comment by jonathon-love** [comment]
OK, discussing this with quentin a bit more, this totally sucks!

so we can add the multiple blocks back in, and at the moment we're thinking of only supporting the 'enter' method with multiple blocks (if you enter multiple blocks with any other method, you receive a "multiple blocks is not supported with this method at this time")

**however** the multiple blocks thing is not compatible with the model builder (at least as it currently is). the model builder is what lets you add interactions into the model (by default, only the main effects are included), but it only works with a single model. SPSS avoids this problem by not letting you add interactions into the models in linear regression.

i can modify the model builder to allow you to add terms to multiple models, but this is a non-trivial amount of work (these model builders are one of the most difficult things to program i know of)

in the short term, if you had to choose between allowing interactions in a model, and allowing multiple blocks, which would you choose?

**Comment by borisma** [comment]
Hi! I have got the following suggestion:
1) Remove the model builder from LR and allow only main effects like SPSS.
2) Add parameter estimates (= regression coefficients) and respective t-tests to ANCOVA. Actually, what you name ANCOVA is a (univariate) general linear model. If you include only covariates as predictors, you have a regression model (and you can specify interactions in the model builder...)

Apart from that, please include a test of the overall model in ANOVA and ANCOVA (already there in LR). It is really necessary since its significance is the precondition for interpreting the (main and interaction) effects included.

**Comment by borisma** [comment]
If you include the parameters estimates in ANCOVA this would also include the parameters related to the factors - which depend on the parametrization. Also the question would be whether standardized parameters should be included then (for the covariates/regressors). I would rather say no: 1) if you're using interactions / test moderation you usually are not interested that much in standardized coeffs  2) you would have to standardize factor-related parameters as well which is odd 3) if you really need the standardized beta for a model with interaction you still can construct the interaction variable yourself and then enter it (as a main effect) into the LR procedure.

**Comment by renenob** [comment]
I would favor multiple blocks with R2 change for hierarchical regression over interactions in a model.  Interactions can be tested by creating interaction term as another variable to be included in the model.  Additional simple slope analysis (with significance test) would be quite powerful for simple moderation analysis!

**Comment by boutinb** [comment]
This issue is closed due to too long inactivity. Please re-open this issue is this problem still occurs.
