### ISSUE TITLE
contingency tables error

### ISSUE THREAD

**Issue by dostodabsi** [jasp-stats/jasp-desktop#930]
hey again,

when I want to calculate the classical log odds ratio, I get the error "Unable to jsonify".

I guess you don't do Bayesian log odds ratio just yet? (it's also not in the recent paper: http://ejwagenmakers.com/submitted/JamilEtAlGunelDickeySubm.pdf)

However, if it would be implemented already: I get a NaN and -- naturally -- a plotting error.

cheers,
Fabian

![jsonify_jasp](https://cloud.githubusercontent.com/assets/6568110/9704929/84b9364a-54b5-11e5-8668-38ef83124635.png)

![logodds](https://cloud.githubusercontent.com/assets/6568110/9704937/c14f6dc2-54b5-11e5-9092-0007bd4f3a58.png)

**Comment by dostodabsi** [comment]
oh it's in the appendix! Yes, so then there is also the Bayesian log odds error.

**Comment by jonathon-love** [comment]
can you send me the dataset?

jon [at] thon [dot] love

with thanks

**Comment by jonathon-love** [comment]
this one i *can* reproduce on ubuntu vivid, but not on windows or osx (which is why it escaped our notice)... still digging.

**Comment by dostodabsi** [comment]
gotta keep the linux community happy, right :)

**Comment by jonathon-love** [comment]
i do try to! they don't make it easy :P

**Comment by jonathon-love** [comment]
ok, if you run your software updater, you'll receive an update for the R package RJSONIO, and this will fix the first issue. not sure about the second.

**Comment by dostodabsi** [comment]
not quite. I also updated and reinstalled, but I still get the json error.

**Comment by dostodabsi** [comment]
the json error is now gone, and I get the classical log odds ratio (but still not the Bayesian one)

**Comment by jonathon-love** [comment]
the issue in both instances is a call to stats::quantile(), for whatever reason, the argument `probs` does not appear to be part of the function on your system.

perhaps i should have asked this ages ago, but what version of R is installed? and could you send me your system's help for stats::quantile? (i.e. what `?stats::quantile` says)

thanks for bearing with me!

**Comment by dostodabsi** [comment]
latest R version, that is, 3.2.2. sure it is!

x <- runif(10)
quantile(x, probs = c(0, 1))

does as advertised.

thanks for both saturday *and* sunday night help!

**Comment by jonathon-love** [comment]
ah, what if you run:

`/usr/lib/R/bin/R --version` ?

same version?

**Comment by dostodabsi** [comment]
yes.

I will also be in the office tomorrow, if it might be easier to look at this in person?

**Comment by jonathon-love** [comment]
what?! are you at the UvA?

**Comment by dostodabsi** [comment]
yeah, I'm EJ's intern for the next weeks

**Comment by jonathon-love** [comment]
oh, righto. that will probably make it a lot easier :P

see you tomorrow then.

**Comment by dostodabsi** [comment]
yeah, sorry for saying this so late!

see you tomorrow.

**Comment by jonathon-love** [comment]
ok, i can now reproduce this. i didn't realise you were using R from CRAN.

i'm pretty close to declaring it to be a bug in R.

**Comment by jonathon-love** [comment]
no solution; you can't use R 3.2.2 with JASP under Ubuntu Trusty and derivatives. JASP in the PPA has been updated to reflect this.
