### ISSUE TITLE
rm anova interface

### ISSUE THREAD

**Issue by dostodabsi** [jasp-stats/jasp-desktop#932]
hey,

it would be nice to be able to scale the "repeated measures cells" to the left and right so that all names are visible. This is possible for the frequentist case, though somewhat unintuitive, but not possible for the Bayesian case (see attach).

cheers,
Fabian

![rm_anova_interface](https://cloud.githubusercontent.com/assets/6568110/9713222/4529e768-5550-11e5-90db-35e57cf62514.png)

![rm_anova_interface_bayesian](https://cloud.githubusercontent.com/assets/6568110/9713389/45239b5a-5551-11e5-8d2f-0277902c611a.png)

**Comment by jonathon-love** [comment]
oh, i thought i'd already done this.

**Comment by jonathon-love** [comment]
will be in the next release.
