### ISSUE TITLE
post hoc test error

### ISSUE THREAD

**Issue by fdabl** [jasp-stats/jasp-desktop#933]
hey,

attached an error I received when doing post hoc tests in 2x2 anova. I've sent you the jasp file.

![posthoc_anova](https://cloud.githubusercontent.com/assets/6568110/9714193/7b8e5054-5556-11e5-9f66-c1c701ecb499.png)

**Comment by boutinb** [comment]
Sorry for the very late answer. Does this problem still occur in the new JASP version (0.8.1)?

**Comment by boutinb** [comment]
If this error still occurs, reopen this issue
