### ISSUE TITLE
equal variance t-test problems

### ISSUE THREAD

**Issue by dostodabsi** [jasp-stats/jasp-desktop#934]
hey,

this one is a little bit more involved (no direct error message). When I run a classical independent t-test (assuming equal variance), I get the following result:

![ttest1](https://cloud.githubusercontent.com/assets/6568110/9714888/b0b9beb2-555b-11e5-882e-f1535fe6b8b3.png)

This is confusing. When I do not assume equal variance (Welch's t-test), I get an answer (the "correct" one):

![ttest2](https://cloud.githubusercontent.com/assets/6568110/9714906/de14c208-555b-11e5-940b-8147c39ee602.png)

Why? Both t-tests should be possible -- they are in R. Further, when I test for equality of variance, it doesn't show the output:

![ttest3](https://cloud.githubusercontent.com/assets/6568110/9715922/78d1849e-5565-11e5-8ed6-cec07fc5645a.png)

thanks!

**Comment by jonathon-love** [comment]
yeah, this is another weird R 3.22 under Ubuntu 14.04 issue. i'll figure it out.

**Comment by dostodabsi** [comment]
great! let's see what this afternoon leads to :)

**Comment by jonathon-love** [comment]
i think perhaps you are enjoying this too much :P

**Comment by dostodabsi** [comment]
haha, maybe :P

**Comment by jonathon-love** [comment]
no solution; you can't use R 3.2.2 with JASP under Ubuntu Trusty and derivatives. JASP in the PPA has been updated to reflect this.
