### ISSUE TITLE
variable type wrong

### ISSUE THREAD

**Issue by dostodabsi** [jasp-stats/jasp-desktop#937]
hey,

this one seems subtle. Whenever a column includes 0, it is coded as nominal (ordinal?) instead of metric, precluding any analysis (or maybe the icons are just wrong).

I've sent you the data.

![variables](https://cloud.githubusercontent.com/assets/6568110/9719458/bc75ad0a-5584-11e5-8724-660ff33fc2b0.png)

cheers,
Fabian

**Comment by jonathon-love** [comment]
less than 50 unique values in a column results in a nominal variable (see user guide)
