### ISSUE TITLE
invalid comparison with complex values

### ISSUE THREAD

**Issue by fdabl** [jasp-stats/jasp-desktop#947]
hi,

this one seems rather odd, since the data doesn't include complex numbers

![complex](https://cloud.githubusercontent.com/assets/6568110/9762357/3802610a-5703-11e5-9ff7-3009f84b15d9.png)

I've sent you the jasp file.

cheers,
Fabian

**Comment by raviselker** [comment]
Can you send me the csv file?

**Comment by jonathon-love** [comment]
is this with the distro R (3.0.2) or with CRAN R?

jonathon

**Comment by dostodabsi** [comment]
I think this was with 3.0.2, since JASP doesn't work with CRAN R anymore. I would like to check, but I have to get some work done, and apparently R 3.0.2 is missing some crucial packages; will check later and inform you.

**Comment by dostodabsi** [comment]
yep, was with 3.0.2

**Comment by boutinb** [comment]
Also here, sorry for the answer, but does this bug still occur in the newest JASP release?

**Comment by boutinb** [comment]
If this error still occurs, reopen this issue.

**Comment by esdalmaijer** [comment]
Can confirm that the bug still occurs in the latest JASP release (0.8.2), with a more informative error message:

```This analysis terminated unexpectedly.

Error in complete.cases(x, y): not all arguments have the same length

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback, state = state)

.resultsPostHoc(referenceGrid, options, dataset, fullModel)

t.test(unlist(postHocData[listVarNamesToLevel[[k]]]), unlist(postHocData[listVarNamesToLevel[[i]]]), paired = T, var.equal = F)

t.test.default(unlist(postHocData[listVarNamesToLevel[[k]]]), unlist(postHocData[listVarNamesToLevel[[i]]]), paired = T, var.equal = F)

complete.cases(x, y)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports ```
