### ISSUE TITLE
Comments not saved with new B t-test plot meta structure

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#966]
Hi,

When I add a comment to one of the Bayesian T-Test plots, save it, and open the .jasp file again, the comment is gone.

![comment_1](https://cloud.githubusercontent.com/assets/8697436/9816809/7d93c0ea-589f-11e5-8b13-ccffb27c1c90.png)

![comment_2](https://cloud.githubusercontent.com/assets/8697436/9816823/9d963238-589f-11e5-94c7-e00974ec6a86.png)

**Comment by dropmann** [comment]
this can be closed. It has been fixed.
