### ISSUE TITLE
Interaction between Classic and Bayesian RM Anova

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-desktop#967]
@mmarsman1 @quentingronau @raviselker @EJWagenmakers @jonathon-love 

Hi peeps,

There seems to be something going on with the classical and Bayesian RM Anova. 

Main problem: 
- Different result for the Bayesian analysis when I do a classical analysis first
- Different result for the classical analysis when I do a Bayesian analysis first

In particular: 

1 Classical, 2 Bayesian
![screen shot 2015-09-11 at 17 59 31 pm](https://cloud.githubusercontent.com/assets/10271675/9819543/fbeb4cc4-58ae-11e5-97a1-f63bc307787a.png)

Note that: 
- a. Task * Relatedness has an F(1, 28) = 0.628, p=0.435, which aligns with the OSF and R analysis. 

<b>For some reasons my variables got shuffled. Why?</b>
![screen shot 2015-09-11 at 17 59 54 pm](https://cloud.githubusercontent.com/assets/10271675/9819866/b7c4a020-58b0-11e5-86db-08d0a5bfcb2e.png)

Note that:
- b. Posterior inclusion probability is 1

1 Bayesian, 2 Classical
<b>I reproduced the shuffling by clicking BF01, it was computing the BF10s. Why?</b>

![screen shot 2015-09-11 at 17 59 45 pm](https://cloud.githubusercontent.com/assets/10271675/9819564/1886b288-58af-11e5-9d6c-f51f70c9ba54.png)

Note that: 
- a. Task * Relatedness has an F(1, 28) = 445.266,  p<0.001, which does NOT align with the OSF and R analysis. More importantly, it doesn't align with itself. 

![screen shot 2015-09-11 at 18 00 00 pm](https://cloud.githubusercontent.com/assets/10271675/9819871/c1c5e980-58b0-11e5-9051-99ba194cecf1.png)

Note that: 
- b. Posterior inclusion probability is 0.186

Am I doing something incorrect here? The data file are sent to you by mail.

**Comment by raviselker** [comment]
Regarding the misalignment of the two classical RM ANOVA's: while you specified the repeated measures cells correctly for the first analysis, you misspecified the repeated measures cells for the second analysis. Therefore, the repeated measures factors are misrepresented and will give you wrong results. It clearly is important to correctly align the variables to the cells :)

**Comment by EJWagenmakers** [comment]
Does this solve the inconsistency between the classical and Bayesian result
as well?
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by raviselker** [comment]
Yes, I think so.

**Comment by AlexanderLyNL** [comment]
The variables got scrambled around for some reason while it was computing
things.

I can reproduce the bug in the Bayesian analysis by switching from BF10 to BF01
while it's computing some of the Bayes factors. This shuffling of the variables
is quite weird and may lead to confusion.

On Sat, Sep 12, 2015 at 6:40 pm, Ravi Selker < notifications@github.com [notifications@github.com] > wrote:
Yes, I think so.

—
Reply to this email directly or view it on GitHub
[https://github.com/jasp-stats/jasp-desktop/issues/967#issuecomment-139794879] .[https://github.com/notifications/beacon/AJy7u8bgi62j8-NM2xzPHc4Xfm24u69Hks5oxEzugaJpZM4F73OT.gif]

**Comment by EJWagenmakers** [comment]
Clearly an important matter!
EJ

**Comment by mmarsman1** [comment]
Let’s discuss this on monday, since I don’t really get what’s going on.

On 12 Sep 2015, at 19:28, EJWagenmakers <notifications@github.com<mailto:notifications@github.com>> wrote:

Clearly an important matter!
EJ

**Comment by boutinb** [comment]
This issue is closed due to too long inactivity. Please re-open this issue is this problem still occurs.
