### ISSUE TITLE
Bayesian RM Anova: Effect negative Bayes factor

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-desktop#968]
@mmarsman1 @quentingronau 

For some reason I get a negative Bayes factor here (BF10)
![screen shot 2015-09-11 at 18 20 49 pm](https://cloud.githubusercontent.com/assets/10271675/9820104/02eee9b0-58b2-11e5-99c5-509ead7212dc.png)

**Comment by quentingronau** [comment]
Hi,

I think it is a numerical issue. The critical part is the calculation of the posterior odds [2].
When I printed posterior.inclusion.probabilities[2], it appeared to be one which would lead to posterior odds (1 / (1-1)) which should be Inf. However, I obtained a different result. When I printed all possible decimal places, I recognized that from the 16th decimal place on there are some digits larger than zero. I think this is a numerical imprecison, so I solved it by forcing it to be exactly one.

![negativebf](https://cloud.githubusercontent.com/assets/8697436/9854091/4b8e4c4a-5b07-11e5-9d4d-2ff10a0824c4.png)
