### ISSUE TITLE
Plotting option in ANOVA -- maybe fix the axes range across plots?

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#970]
@raviselker I've plotted results from a 2x2x2 ANOVA in two panels. There does not appear to be an interaction. However, what makes the result difficult to compare across the panels is that the scale on the y-axis is different. Should we enforce a common scale across the panels, by default? I think it might make sense...
![image](https://cloud.githubusercontent.com/assets/8603015/9824139/4964df26-58cb-11e5-8642-a002a5aaae74.png)

**Comment by raviselker** [comment]
Yes, it makes sense. That's why I already implemented this change :). I think this change is already in the 0.7.1.12 release, but if not it will definitely be in the next release.

**Comment by EJWagenmakers** [comment]
:-)
