### ISSUE TITLE
Dunnett adjustment for multiple comparisons with a control

### ISSUE THREAD

**Issue by bdwade** [jasp-stats/jasp-desktop#971]
Beautiful program!

Please add Dunnett's adjustment/correction to the Post Hoc Tests for ANOVAs.  I just may be able to break free of SAS if this is implemented!  :o)  Links to relevant publications follow.

http://dx.doi.org/10.1080/01621459.1955.10501294

http://dx.doi.org/10.2307/2528490

**Comment by AlexanderLyNL** [comment]
0.9.1
