### ISSUE TITLE
Long variable names cropped in selection window

### ISSUE THREAD

**Issue by nicebread** [jasp-stats/jasp-desktop#976]
![bildschirmfoto 2015-09-14 um 11 44 05](https://cloud.githubusercontent.com/assets/2391270/9846933/eb3b625a-5ad5-11e5-8e1f-a8530cb26ea8.jpg)

Would be nice if the variable selection window could be expanded, e.g. as textareas on web sites.

**Comment by boutinb** [comment]
Add tiptool

**Comment by boutinb** [comment]
The columns in the data view could be resizable, but they were reset to fix size. This is solved and the fix will be present in the next release (probably in April).
