### ISSUE TITLE
just for the record (regression in linux under R 3.2)

### ISSUE THREAD

**Issue by fdabl** [jasp-stats/jasp-desktop#983]
hey,

if you ever get around updating to the latest R (which is important for linux users, since many packages do not work with the shipped R version), these issues in classical regression would need fixing:

problems with residual checks:
- casewise
  ![casewise](https://cloud.githubusercontent.com/assets/6568110/9903430/b84d825e-5c76-11e5-9f8c-c0a20e7150ad.png)
- Durbin-Watson
  ![durbinwatson](https://cloud.githubusercontent.com/assets/6568110/9903431/b84e1228-5c76-11e5-8f1c-0cd95dd00071.png)
- Q-Q Plot
  ![qqplot_linreg](https://cloud.githubusercontent.com/assets/6568110/9903429/b84c191e-5c76-11e5-990c-a1b12355c9fa.png)

all works beautifully in R 3.0, though!

cheers,
Fabian

**Comment by boutinb** [comment]
All R packages will be upgraded next release (in April)
