### ISSUE TITLE
Order levels .shortToLong function

### ISSUE THREAD

**Issue by raviselker** [jasp-stats/jasp-desktop#989]
When using the .shortToLong function in common.R, the levels of the repeated measures are ordered alphabetically by default. This is not the preferred behaviour as some of the functions use this order to produce plots/tables (e.g. the DescriptivesPlot functions). It would be nicer if the order of the levels would mimic the order of RM Factors on the left side panel. This way, the user has more control of the order of levels in the RM Factors.

**Comment by jonathon-love** [comment]
hmm, i'm surprised it doesn't work the way you describe.

can you post a screenshot of where you would like different behaviour?

**Comment by raviselker** [comment]
See screenshot for an example:

<img width="1552" alt="screen shot 2015-09-19 at 01 20 31" src="https://cloud.githubusercontent.com/assets/4669197/9973039/c082c7e8-5e6c-11e5-85d8-d73fabdc1e63.png">

**Comment by jonathon-love** [comment]
hey, do you want to do this?
i'm looking at `.shortToLong()`, and i have absolutely no idea how it works.
i don't know that i've ever been so bewildered by code that i've written.

**Comment by jonathon-love** [comment]
oh wait up. i think i've got this.
