### ISSUE TITLE
C RM ANOVA: doesn't work?

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#991]
<img width="1317" alt="screen shot 2015-09-19 at 2 43 18 pm" src="https://cloud.githubusercontent.com/assets/3240247/9976205/d9ad1f82-5edc-11e5-8560-63a21441bff7.png">

**Comment by raviselker** [comment]
Which OS? I cannot reproduce the error on Yosemite: 

<img width="1552" alt="screen shot 2015-09-19 at 17 49 16" src="https://cloud.githubusercontent.com/assets/4669197/9976965/c88b01aa-5ef6-11e5-8145-f49ac4423ac7.png">

**Comment by jonathon-love** [comment]
ah yup, hadn't updated my r bundle
