### ISSUE TITLE
C RM ANOVA: Changing levels is not reflected in the plots

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#992]
the design is 4x1, where as the plot is 2x1

if i create the plot last, there isn't an issue. but if i create the plot, then go and change the design, this isn't reflected in the plot.

<img width="1031" alt="screen shot 2015-09-19 at 6 52 11 pm" src="https://cloud.githubusercontent.com/assets/3240247/9977216/a7dd5896-5eff-11e5-8d29-48155f57a109.png">

**Comment by raviselker** [comment]
Yes, I already noticed this behaviour and it's a problem with the state system. I'll fix it.
