### ISSUE TITLE
Bayesian contingency table: No error message appears

### ISSUE THREAD

**Issue by Tahiraj** [jasp-stats/jasp-desktop#995]
In plotting odds ratio an error message appears, 

<img width="1208" alt="screenshot 2015-09-21 12 23 10" src="https://cloud.githubusercontent.com/assets/9108433/9989946/27adf9c8-605d-11e5-8037-5a19cfc034a2.png">

after that if we switch between the option from BF10 to BF01 the plot window shows no error message 

<img width="1162" alt="screenshot 2015-09-21 12 23 33" src="https://cloud.githubusercontent.com/assets/9108433/9989951/3ba37a3e-605d-11e5-8346-cc7240944b0b.png">

**Comment by boutinb** [comment]
@AlexanderLyNL: I cannot reproduce this problem. can we close this issue?

**Comment by AlexanderLyNL** [comment]
The bug is fixed, though, the error message is not adaptive. Easy to fix. I'll do this later.
