### ISSUE TITLE
Bayesian LogLinear: Add an option for  (alpha)%  Highest posterior density intervals

### ISSUE THREAD

**Issue by Tahiraj** [jasp-stats/jasp-desktop#997]
@jonathon-love

**Comment by jonathon-love** [comment]
hi, can you describe this a bit more. where should it go for example?

**Comment by Tahiraj** [comment]
I think you need to add Loglinear  coefficients, estimate and then confidence intervals as in we have in classical one under the statistics tab.

**Comment by jonathon-love** [comment]
hey, sorry for the delay. damo's been working on some UI changes, and so i'm still waiting on that to be done before i can work on this. should be in the next day or so.

**Comment by Tahiraj** [comment]
Fine
